### ISSUE TITLE
block and transaction version numbers

### ISSUE THREAD

**Issue by jl777** [zcash/zcash#1000]
Not a critical issue, but it would be nice if the version numbers used for blocks and transactions are not overlapping with bitcoin versions.

My rationale is that all zcash blocks and tx are slightly to dramatically different than bitcoin and while any code that handles both will need to special case things for zcash, if the version numbers are not in common with bitcoin, then it will avoid having the same version number meaning totally different things.

**Comment by str4d** [comment]
I'm +0 on this. The block headers for Zcash are significantly different now (see [#724 (comment)](/zcash/zcash/issues/724#issuecomment-224138202)), so I doubt code that handles both will be reusing much of the header-parsing code at the level where version numbers matter. And doing so will restrict not only what version numbers we can pick, but what version numbers Bitcoin Core can pick. But if it will legitimately make the lives of developers easier, and Bitcoin Core is onside, I'm not opposed to the idea.

**Comment by jl777** [comment]
In my codebase, I do use the same code to parse the headers, with a special case for the bignonce and the solution, but you never know when having the same thing mean different things might cause unexpected behavior.

my iguanacore is a multicoin bitcoin protocol daemon, but I am probably the only one in the world right now dealing with such issues.

Just a general defensive coding on my part, to reduce assumptions and dependencies as much as possible, whenever possible. By my metric if I have to have a special case for version number vs version number AND coin, the latter has an extra condition and is less desirable.

Probably it wont ever matter, but if it is no trouble I'd appreciate it. More important are my other performance oriented suggestions to group all the 256bit values together and ordering from largest to smallest fields. Again, it probably wont matter for most implementations that build an in-memory object, but iguana creates memory mapped files and directly uses them, so any misaligned integers can be much slower on some CPU.

Thanks!

**Comment by str4d** [comment]
Another possible alternative for your datastructure (having never looked at it :stuck_out_tongue_winking_eye:) is to precede every block header with a `nCoinType`, and then in your code have `(nCoinType, nVersion)` be the identifying factor instead of ever relying solely on `nVersion`.

Regarding arrangement of fields, you're welcome to comment on #724 :smile: Since we're changing the block header anyway, I don't have a problem with reordering the fields for performance (and I expect others will comment there if they do have concerns).

**Comment by jl777** [comment]
I already know what coin is being used, but the idea is to have as little code as possible dealing with (coin, field). the more code that is just based on (field) alone, the more portable, the more robust it will be as every coin would run that codepath. As soon as something is in a conditional, that codepath is less tested.

**Comment by nathan-at-least** [comment]
My impression is that this is a pretty special case within the design of iguanacore so I currently don't consider that a strong motivation for altering Zcash block versions. Is that true?

Meanwhile I am pretty interested in iguanacore and that kind of use case, because I see a growing need for multi-chain end-user software.

BTW- Is iguanacore open source?

**Comment by jl777** [comment]
yes, it is all open source, even as I am debugging it

https://github.com/jl777/SuperNET

as far as version numbers go, it is more a philosophical thing about maximizing interoperability whenever it doesnt cost anything expensive. If hundreds of coins all did things without regard to interop, well it makes for a lot more work and a messy solution.

All I ask is that zcash team thinks about version and tx numbering in the context of a shared bitcoin protocol across hundreds of coins. The fewer special cases needed, the less special cases need to exist and the less likely bugs due to the same number meaning two different things. I know there is a zcash context that can be used, but just imagine hundreds of coins each doing dozens of things that require specific checks...

**Comment by daira** [comment]
Zcash block version numbers do mean a different thing to the corresponding Bitcoin ones. I don't think we're going to change that since we're past spec freeze. This was previously discussed in detail on issue #114; it took us quite a while to reach consensus and I don't want to reopen that can of worms. Sorry @jl777!
