### ISSUE TITLE
OP_RETURN,CLTV, CSV, blocksize

### ISSUE THREAD

**Issue by jl777** [zcash/zcash#1010]
I am assuming CLTV and CSV will be supported as they are quite useful.

Also I assume, but wanted to verify, that there isnt any arbitrary 1MB per block limit and there is a sane way to adjust the blocksizes based on actual usage.

A more obscure but still quite important issue is the size allowed for OP_RETURN. In bitcoin it is 80 (was even as low as 40 for a while), which is quite small and forces multiple tx to be used to create a larger data store. So having a really small limit could be counterproductive. There is no need to go crazy, but maybe use the limit of ~1500 bytes, which is used for limiting the size of some transaction elements.

**Comment by mcelrath** [comment]
OP_RETURN is an example of externalized, and unaccounted-for cost in the Bitcoin ecosystem.  Externalized costs lead to a "tragedy of the commons".  One ought to be able to use such things to store data, but their economics are entirely different than transactions for the underlying coin.

I'm personally of the opinion that data storage outputs should:
1. Pay a fee for the data storage, which should be related to the storage costs of the data, rather than the transaction fee.
2. Have an expiration date after which nodes are not expected to keep the data, and it can safely be pruned.

Thus a storage cost can be calculated as (# nodes)*(# bytes)*(time) and a rate established for data storage.  That rate can be compared the transaction fees of regular transactions (as they also have a data storage cost).  I also believe regular old UTXOs should have expiration dates, after which they can be reclaimed by miners.

**Comment by jl777** [comment]
seems a bit drastic to confiscate a long term holder's coins, just because he doesnt spend them. Especially for privacy oriented value storage, where each and every transaction increases the risk profile, if only by a little.

data in an OP_RETURN or data in a spend script, it is still just data. And all are charged by the size they occupy on the blockchain. Regardless of things, OP_RETURN is part of the bitcoin protocol and it is used by applications, so if compatibility with them is any sort of priority, then best to at least keep it as is. 

You do realize that if you change the pricing artificially for data storage, that it will migrate to other parts of the tx, which likely wont be able to be pruned as easily. OP_RETURN data does not go into the utxo dataset as it is unspendable and as such it seems the least overhead place for data. My prediction is that if OP_RETURN is crippled/disabled, then we will end up with the same data encoded as part of transactions that have an active utxo, which increases the cost to the network

Adding expiration to OP_RETURN would be fine for many use cases, but not for all. I guess the issue is with all things in zcash being bigger (block headers, transactions) then it would make sense for the OP_RETURN to also be a bit bigger, not smaller

**Comment by daira** [comment]
CTLV (BIP 65) is supported, CSV is not. OP_RETURN is the same as in Bitcoin. Block size is 2000000 bytes (and a change to that would require a hard fork).

It's too late to make changes to consensus now, so I'm closing the ticket. Apologies for not getting to answering these questions earlier. Future consensus changes will be handled via the Zcash Improvement Proposal process.
