### ISSUE TITLE
how to go from buckets to transparent utxo?

### ISSUE THREAD

**Issue by jl777** [zcash/zcash#1014]
the examples show how to go from transparent utxo into the encrypted bucket -> decrypted bucket and pouring into another encrypted bucket.

but it isnt clear how to, or if it is possible to go the other way.

also, are there always 2 encrypted bucket outputs?

**Comment by ebfull** [comment]
In order to go the other way (spend a confidential note and send it to a transparent address) you must create a transaction which sends coins to the recipient (`createrawtransaction [] {"recipient address":$VALUE}`) and use that with `zcrawpour` in a way like: `zcrawpour $RAWTX '{"decbucket":"key"}' "{}" 0 $VALUE`.

The last two parameters of `zcrawpour` are "vpub_old" and "vpub_new". `vpub_old` takes value from the transaction and makes it available inside the confidential operation. `vpub_new` does the opposite, and is what you'll want to use to bring value back out.

**Comment by jl777** [comment]
thanks! I will try to make that work. I guess there are the transparent ZEC that works as a normal bitcoin fork, but you can transfer them into the untraceable form and back out, without any leakage of info during the round trip (assuming the crypto isnt cracked)

So, this probably means there is no way to do any normal block explorer, but it would be normal for the transparent coins and then a single global total that is protected.

**Comment by Voluntary-zcash** [comment]
@ebfull I'm trying to combine the example from your post above with what I've learned from the Public Alpha Guide but I'm getting hung up on single and double quotes, dollar signs and the general syntax of whatever language this is.  Could you, or someone else that knows how, start with an unprotected input, protect it and then spend it to a transparent address?  And then, most importantly, could you then copy and paste your command line for that session either here or into a Zcash forum thread?

**Comment by Voluntary-zcash** [comment]
btw How does one query the balance of their own protected address?

**Comment by str4d** [comment]
The `z_sendmany` RPC command supports sending from z-addrs to t-addrs.
