### ISSUE TITLE
Start providing a Linux binary/package so people can start testing z.cash without the compilation hassle

### ISSUE THREAD

**Issue by loxal** [zcash/zcash#1034]
More people would start testing when you provide binary snapshots.

**Comment by daira** [comment]
See also #540.

**Comment by daira** [comment]
I added this to the Signed Binaries milestone because that's the latest it can happen. There's no reason why we shouldn't provide binaries for earlier releases (signed or otherwise) before then.

**Comment by ralphtheninja** [comment]
+1

**Comment by ageis** [comment]
Once the build and signing process is worked out, I'm keen on providing .debs and .rpms for Zcash via a publicly-available repository.

I have an automation role I've written for another project which sets up [aptly](http://www.aptly.info/), the Debian package repository management tool, and can handle uploading, GPG-signing and publishing packages on a webserver. The process for Yum/.rpm would be a little different ([Pulp](http://pulpproject.org/) looks like one option), but I'm sure it could be worked out. I have code for a keyring package that can be used to keep our repository signing key updated for end users in case it expires or needs to be rotated. The signing key should ideally be an offline key. One process I'm famliliar with leverages Tails OS, DVDs for moving data from the build machine to the air-gap, and QR codes for transferring data off of the air-gap.

For a key to building the .deb, if no one has investigated it yet, we could examine the code for the bitcoin-qt/bitcoind packages that are already in Debian. It shouldn't be laborious to migrate it to Zcash, add hooks for downloading the zkSNARK parameters, etc.

**Comment by daira** [comment]
Note that some of our dependencies, for example libgmp, may be aggressive in choosing compilation options for the platform they are compiled on, as pointed out here: https://github.com/zcash/zcash/issues/1378

We should make sure to build binaries only with options that are likely to work for the vast majority of x86 processors in current use. We might also have to build different binaries for different families of Linux distributions; I'm not sure. The earlier we can start producing binaries in order to get reports from users on platform-specific problems, the better. This should *not* block on being ready to sign binaries. (We'd be distributing them over https anyway.)

**Comment by daira** [comment]
Also note that we can compile/publish binaries for a release without delaying that release milestone. I'd like us to do this for the beta 2 release.

**Comment by ageis** [comment]
I grabbed the source for the Debian package for Bitcoin and I only just began to convert and construct a .deb package that will work installing for Zcash.

Question: do we want the Debian packaging-related files to be committed in a subdirectory of this repository, or should we make a separate one?

**Comment by bitcartel** [comment]
Assigning to @ageis as he has already started and made progress on this.

**Comment by str4d** [comment]
@ageis what else remains before we can close this issue?

**Comment by ageis** [comment]
@str4d Besides tagging the release and running the Gitian build for it, closing the loop depends on #609 and #1381 and standing up the repository server, which I can take care of this week.

**Comment by ageis** [comment]
This is done, with the guide here: https://github.com/zcash/zcash/wiki/Debian-binary-packages
The repository server is https://apt.z.cash.
The Zcash software signing key fingerprint is `F1E2 1403 7E94 E950 BA85 77B2 63C4 A216 9C1B 2FA2`.
We _could_ add direct .deb downloads to the website, but I'd rather insist people follow the repository process, so that they can receive updates through their package manager.
Still some documentation (release process) and other little stuff that should be updated, but we can handle that in separate rc2 issues.
