### ISSUE TITLE
Please provide GPU mining support before launch to level the playing field

### ISSUE THREAD

**Issue by mgbtcfv** [zcash/zcash#1040]
Zcash dev team should provide GPU mining support prior to launch. Otherwise a small group of people will have unfair advantage over others.  Please refer to this reddit thread - 
https://www.reddit.com/r/Zcash/comments/4i9zz5/zcash_gpu_cloud_mining_on_launch/

**Comment by zookozcash** [comment]
This is a serious concern to me. I agree that we should either have a publicly-available GPU implementation or else that we should change the algorithm (if necessary) to make it more profitable to mine on CPUs.

At the moment, we don't even know if it is more advantageous to use a GPU or a CPU to mine Equihash.

**Comment by mgbtcfv** [comment]
Zooko, can the dev team outsource this prior to launch? The Zcash community as a whole can contribute to the cost. Certainly I would be willing to contribute and so will be many others.

**Comment by Voluntary-zcash** [comment]
Are there industrial controllers that combine x86 with graphics card class memory?  Also. would it be reasonable to set Equihash parameters beyond the capacity of graphics cards?

**Comment by faddat** [comment]
Really glad to hear that you take this seriously.  Have a look at what's happened on STEEM's mining area since closed-source GPU mining implementations made it to town..... 

@Voluntary-zcash it's difficult to go beyond the capacity of graphics cards without ruling out a really wide spectrum of users, given z.cash's laudable goal of running on devices from mobile phones to servers.  The best bet, I think, would be to ensure that the project itself makes a GPU miner release.  

I suppose the other alternative (which would be unenforcable, I think) would be to include a viral open source clause in z.cash's code, but this would limit derivative implementation and work in the closed source realm.  

#toughproblem.

**Comment by Voluntary-zcash** [comment]
I think this problem will solve itself when more people get involved in mining.  I also think pool mining is a more important objective than a GPU miner.

**Comment by str4d** [comment]
As a result of the [Zcash Open Source Miner Challenge](https://zcashminers.org/), there were publicly-available GPU miners at launch.
