### ISSUE TITLE
Make alerts able to put nodes into safe mode

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1106]
https://en.bitcoin.it/wiki/Alert_system#Safe_mode

**Comment by daira** [comment]
IMHO, at least in the early life of the network, ability to respond quickly to security flaws outweighs risk of DoS attacks by holders of the alert private keys. We can always turn it off later, as Bitcoin did.

**Comment by daira** [comment]
We can also make this behaviour dependent on either the priority of the alert (say >= 3000) or on an explicit flag, so that it is still possible to send alerts that don't trigger safe mode.

**Comment by zookozcash** [comment]
I agree with https://github.com/zcash/zcash/issues/1106#issuecomment-233126433.

**Comment by nathan-at-least** [comment]
I like this feature choice. Let's aim to enable this in z9.

**Comment by daira** [comment]
Did we decide to enable this in z9? @nathan-at-least indicated support for that but then changed the milestone to "Audit Tasks", which has me confused.

**Comment by daira** [comment]
Actually, as release manager I'm deciding that we don't need this in z9, it can just as well go into Beta 1.

**Comment by nathan-at-least** [comment]
I agree with @daira that we should put this in Beta 1.

**Comment by daira** [comment]
This isn't actually a consensus change.

**Comment by daira** [comment]
@nathan-at-least suggested that this might be overrideable by a user.

**Comment by nathan-at-least** [comment]
More specifically when considering "should we make it a feature goal for 1.0 to freeze the wallet on alert?" -then I start to wonder about the trade-off between introducing a DOS vector (and the associated damage from wide-spread economic halt) versus preventing loss of funds, and it's a difficult trade-off to make.

If, on the other hand, the wallet halts and a message says something like:

> The wallet functionality has been suspended due to the following developer alert:
> …
>
> You may choose to undo this suspension by adding … to your config file and restarting. Do this at your own risk and please take precautions and study the relevant security issues before making this choice.

-then I'm easily convinced we should add that as a 1.0 feature, because the potential for malicious economic halt is mitigated, and users remain in control.

**Comment by str4d** [comment]
@nathan-at-least the user can disable this functionality in two ways: set `-alerts=0` to disable alerts entirely, or `-disablesafemode` to ignore all safe-mode suggestions (both local and by alerts). If desired, we could add a third flag to just disable the alerts-trigger-safe-mode functionality.
