### ISSUE TITLE
Is the PandaA arithmetic library useful to us or libsnark?

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#1123]
PandA claims to be a pairing/arithmetic library that's constant time and protects against side-channels. Investigate if it might be useful for adding side-channel defenses to libsnark.

https://link.springer.com/chapter/10.1007/978-3-319-04873-4_14

**Comment by daira** [comment]
Unpaywalled link:

https://cryptojedi.org/papers/panda-20131204.pdf

**Comment by daira** [comment]
I like the API, but have some concerns about the extent of algorithmic optimisation of operations that we rely on heavily. For example:

"For the constant-time version [of G<sub>1</sub> multi-scalar multiplication], due to the slow complete addition routine, the function currently simply carries out each scalar multiplication separately and adds them together at the end."

**Comment by daira** [comment]
This is no longer relevant.
