### ISSUE TITLE
Deemphasize upstream version number

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1138]
daira
> Proposal: decouple Zcash versions from upstream versions, and call the next release Zcash v0.8 rather than v0.11.2.z8
> The launch release would be Zcash v1.0 (with the usual beta/release candidate version structure)
> Hmm, but 0.8 < 0.11.2. Any suggestions to fix that?
> I guess we could keep the v0.11.2.z* pattern until 1.0 beta 1 (which would be the first release that supports the payment API).
> Everyone refers to the releases as just z* anyway, but I do feel that the full version number gives undue weight to the upstream version we forked from.

jackgavigan
> v0.12

jack
> -1 on v0.12, that's going to get too confusing

daira
> On reflection I think "keep the v0.11.2.z* pattern until the payment API release" is a better approach. And then going straight to 1.0 beta 1 will avoid any confusion with Bitcoin releases. I don't know what we'll do with the version number APIs; we'll have to think about that in advance so that changing them doesn't block that release.

**Comment by bitcartel** [comment]
How about Ubuntu's date-based version numbering? 

14.04
14.04.1 (point release)

I find them easy to understand and the version number, being a date, serves as a reminder to upgrade or seek out a new version.

**Comment by zookozcash** [comment]
I'll leave this question up to others to decide. I _have_ been calling the version that is going to launch the genesis block "1.0". Maybe we could switch from "1.0" to date-based version numbering after 1.0.

**Comment by daira** [comment]
Note that the protocol spec uses versions starting with a 4-digit year.

**Comment by nathan-at-least** [comment]
Let's make this a goal for our beta to have a new versioning scheme (and new branching scheme).

**Comment by nathan-at-least** [comment]
I propose this versioning scheme:

* Beta releases will be versioned ``1.0.0-beta<N>`` with N incrementing for each beta release.
* Before we launch, we'll have one or more release candidates with version ``1.0.0-rc<N>``.
* The launch will be version ``1.0.0``.

There are three numbers in the version schema. The initial/major number (starting at ``1``) corresponds to our marketing terms for release phases, so ``1`` is `sprout`, ``2`` is `sapling`, etc... The middle number corresponds to the introduction of notable new features, and the last number is for minor features and bugfixes.

Changes to the middle number may signal breaking backwards compatibility, such as in the RPC interface or disk formats. We will probably adopt a "phase-out" policy where deprecated features are supported for a few releases before support is dropped, and that may be tied to the version number.

We intend to advocate hard-fork upgrades, and it's undecided how those will map to version numbers. Changes to major version numbers are likely to involve hard-forks, but hard-forks may occur within middle-version number updates.

These versions are decoupled from protocol versions and spec versions.

Future releases may also have beta and rc versions, especially for large-scale changes such as hard-forks.

This version scheme has a drawback, given that we want to do regular timed release schedules. Suppose we want to introduce a feature which is a major change, and/or deprecate features, then this would necessitate incrementing the middle version number. However, since we are donig timed releases, if that feature is not ready by a cut-off date, then the resulting release may need to have a different version (eg: incrementing the third version number, rather than the second). This means the decision of which features go into a release blocks selection of a version number.

**Comment by str4d** [comment]
There are several aspects to the version system:

- The visible version (`zcash* -version`)
  - This comes from the Git tag for clean builds, and otherwise is generated in `clientversion.cpp`.
- The implementation version (in e.g. network messages) - [BIP-14](https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki)
  - This comes from `FormatSubVersion` in `clientversion.cpp`
- The `CLIENT_VERSION` integer
  - This is generated in `clientversion.h`
- The protocol version
  - Divorced from the client version in Bitcoin 0.6 with BIP-14, and can be ignored here.

To ensure a correct visible version for releases, it suffices to ensure that we create the tags correctly following the above scheme. For user builds, and to ensure a correct implementation version, we need to update the codebase to remove the `z#`, and to handle intermediate versions properly.

The generated versions currently have the following form:

`v$MAJOR.$MINOR.$REVISION[.$BUILD].z$#[-$SUFFIX]`

`CLIENT_VERSION` is generated from `$MAJOR`, `$MINOR`, `$REVISION` and `$BUILD`, and is used all over the place when serializing data to disk.

What we need to decide is whether the `-rc#` or `-beta#` values should be represented in `CLIENT_VERSION`. Bitcoin Core does not appear to do so, relying solely on Git tags to represent their `-rc#` builds. Note that if we do not represent them in any way, `CLIENT_VERSION` will not change between those builds, but if we *do* represent them (e.g. by replacing `$BUILD` with the beta number), then `CLIENT_VERSION` would need to be constructed slightly differently (otherwise a `-rc#` or `-beta#` would have a higher `CLIENT_VERSION` than the subsequent release).

**Comment by str4d** [comment]
@ebfull and I have decided to operate exactly like Bitcoin, ie. `-betaN` will be represented by the Git tag, while `CLIENT_VERSION` will be set to `1.0.0`.

**Comment by daira** [comment]
IMHO CLIENT_VERSION *should* distinguish beta releases. Upstream uses 99 in the revision field for non-releases. Also note that the client version is used in alerts to distinguish which releases an alert applies to. I propose that we set the version to:
* (A, B, 99, 0), for development branches preceding the A.(B+1) series
* (A, B, C, D) with D < 10, for vA.B.C-betaD
* (A, B, C, 10), for vA.B.C

**Comment by daira** [comment]
The CLIENT_VERSION for beta 1 was 1.0.0.0. It's retrospectively consistent with the above proposal :-)

**Comment by nathan-at-least** [comment]
I agree with Daira that `CLIENT_VERSION` _should_ be distinguished for users. The displayed version and the git tag should be identical, and there should be different releases that display the same version.

@str4d or others: how does upstream use `BUILD` in their versions?

@daira: Your proposal seems like a workable hack given the current constraints. Questions:

* How hard is it to rework those constraints so that we have explicit tracking of beta and rc releases in code?
* Does this scheme break if we have >10 beta releases?
* How are rc releases represented?

Can we make the dev branch releases include a git revision (thus not fitting my proposed schema above)? I don't consider those "publicly facing product identifiers" so I'm fine relaxing the schema for that case. (Bonus: distinguish between builds from a "pristine checkout" versus git with uncommitted modifications.)

**Comment by daira** [comment]
* We could make betas have a build of 0..9; rcs have a build of 10..19, and final versions have a release of 20. Or any similar scheme up to a build number of 98 (99 being reserved for non-release dev versions).
* Yes. But we could increase the number at which it breaks to, say, 40.
* See first answer.

**Comment by daira** [comment]
CLIENT_VERSION only allows numbers 0..99 for each component, so it can't represent got commit ids.

**Comment by str4d** [comment]
@nathan-at-least 
> Can we make the dev branch releases include a git revision (thus not fitting my proposed schema above)? I don't consider those "publicly facing product identifiers" so I'm fine relaxing the schema for that case. (Bonus: distinguish between builds from a "pristine checkout" versus git with uncommitted modifications.)

This already happens for the visible version numbers. It does not affect `CLIENT_VERSION` however; that is only affected by major, minor, revision and build.

Also note that the visible version for development versions includes the build, so if we appropriate build for incrementing `CLIENT_VERSION` between betas and RCs, then the visible version for non-clean checkouts of a release, or checkouts of e.g. the first commit after a tagged release, will show e.g. `v1.0.0.20-commitid`.

**Comment by str4d** [comment]
If we do choose to appropriate build, we could also just remove it from the visible version, or adjust the version string to be aware of the semantics, so a `CLIENT_VERSION` set to effectively `1.0.0.19` would render as `v1.0.0-rc10`. Then we could use the second half of the build range for actual build numbers, so e.g. `CLIENT_VERSION = 1.0.0.59` would appear as `v1.0.0.39` or `v1.0.0-b39`.

**Comment by str4d** [comment]
I spent an entire evening trying and failing to get https://github.com/zcash/zcash/issues/1138#issuecomment-246578592 to work (because mixing macro string concatenation and constexpr arithmetic is hard). I may have another go at completely replacing the macros in `clientversion.cpp` over the weekend, but this is low-priority to me, because the key user-facing version is determined from the git tag.

**Comment by str4d** [comment]
Turns out the Boost has preprocessor macros that make this so much easier! Here's the strategy I'm going with for interpreting `BUILD`:

- 0-24: `1.0.0-beta1`-`1.0.0-beta25`
- 25-49: `1.0.0-rc1`-`1.0.0-rc25`
- 50: `1.0.0`
- 51-99: `1.0.0-1`-`1.0.0-49` (or `1.0.0-dev1`-`1.0.0-dev49`)
- (`REVISION` rolls over)
- 0-24: `1.0.1-beta1`-`1.0.1-beta25`

The idea is that `-#` or `-dev#` builds are on top of the current release version, whereas `-beta#` and `-rc#` are preparing for the next release version.
