### ISSUE TITLE
Add ASan to Continuous Integration

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1216]
https://github.com/zcash/zcash/issues/1215#issuecomment-238912712

**Comment by str4d** [comment]
@ageis should be the one to implement this since it is infrastructure, but another engineer should pair with him on it for handling compile-side issues.

**Comment by ageis** [comment]
I'm missing a clear picture of the path forward and some domain-specific knowledge. I've never even run the tests locally. In #777 there were some compile options and stuff posted in order to run tests under ASan. Do those changes need to get merged into Zcash/master, some dependencies installed on the CI server, and then we are all set? Or are there modifications to our Buildbot config required as well? Does ASan need to be separated from valgrind? 

My best guess with the understanding I have is that you want to define a new ASan function to be used by the `zcashperformance` builder and run the same tests under it.

(for the record, my specialization is in Linux sysadmin, automation/config management and infosec, not so much programming / software engineering)

**Comment by ageis** [comment]
There's a new zcashASan builder on https://ci.z.cash/. On its first tests it found a heap-use-after-free. 

Still TODO related to CI: run this builder + Valgrind on a new buildslave on another machine.

**Comment by nathan-at-least** [comment]
This is in place. Nice work!

https://ci.z.cash/builders/zcashASan
