### ISSUE TITLE
Implement the Founders' Reward.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#125]
For the Founders' Reward we desire these properties:

* the public can verify the total amount of the reward.
* the public can verify the rate at which the reward is disbursed / thaws. (see #96)
* the founders & investors are satisfied that the reward meets the agreed upon terms and distribution.

I also propose this engineering goal:

* the exception to consensus rules is minimal and contained in only the genesis block. eg: There is a single exceptional txOut containing all of the reward amount, and all subsequent distribution is through non-exceptional transactions.

A further goal might be:

* While the public can verify the reward total, the public cannot see the internal distribution. (Note that the founders/investors of course must be able to individually verify their reward amount.)

**Comment by daira** [comment]
This ticket needs review to make it reflect the plan for the Founders' reward to be a proportion of mining rewards for a set period.

**Comment by zookozcash** [comment]
Yeah, I don't think it will work to use the technique suggested above, of time-locked transactions baked into the genesis block. That would be cool, but there would be way too many transactions, since the Founders Reward is supposed to be distributed frequently, ideally with every block.

So I propose instead the simpler thing of having a single special payment address for the founders baked into the consensus rules.

**Comment by daira** [comment]
I think that using a single payment address as the destination of the Founders' Reward is incredibly risky. It concentrates spend authority over (eventually) 10% of the money supply into a single secret. Granted, it would be possible &ndash;and highly advisable&ndash; to regularly spend from that address to other addresses that are less concentrated targets. However, if the spending key were compromised then it would still put the Zcash company in the position of having to race with the attacker to spend each and every block reward. The only way to resolve this situation would be a &ndashpossibly controversial&ndash; hardfork to change the Founders' reward payment address.

**Comment by daira** [comment]
Note that it's possible to monitor the blockchain for unauthorized spends of Founders' rewards. However, without support for viewing keys, this requires the spend authority key to be permanently online somewhere in order to compute the serial numbers to compare with the ones spent in each transaction. Also, you still have to regularly empty the Founders' reward address(es) to limit how much the thief can steal before detection.

**Comment by ebfull** [comment]
The founders reward should be sent to a P2SH address, a 2-of-3 multisig.

**Comment by zmanian** [comment]
What if Zcash a specified a different P2SH address every 1250 blocks for the Founders reward, you could store the 2 of 3 keys(or whatever) in an isolated manner so that a compromise of those keys would only do limited amount of damage to the Founders Reward rather than potentially loosing the entire future founders reward without a hard fork. This would only require storing 42 PSH outputs in the consensus which seems like a small price to pay for some defense in depth.

This concentration of the Founder's Reward in only a few keys seems like one downside of the ZCash approach vs the Ethereum approach.

**Comment by nathan-at-least** [comment]
#831 has merged, so this is complete. Nice work @ebfull et al.
