### ISSUE TITLE
Install trouble - bash: sudo: command not found

### ISSUE THREAD

**Issue by jackwatson86** [zcash/zcash#1278]
Hi guys,

If the subject title didn't give it away, I might as well be upfront - this is my first attempt at mining anything and I'm pretty noob at this stuff, but I figured I would be able to copy and paste the commands easily enough.

Anyway, I've install Debian using Parallels for Mac and went into the terminal to paste the first command in the Public Alpha Guide to install...

```
sudo apt-get install \
    build-essential pkg-config libgtest-dev libc6-dev m4 \
    g++-multilib autoconf libtool ncurses-dev unzip git python \
    zlib1g-dev wget bsdmainutils

```
and got back the line...

`bash: sudo: command not found`

Does anyone know what might be causing this? Is it asking for admin rights? I'm the only user I set up when installing Ubuntu so I'm a bit lost here.

Thanks for any help!
Jack

**Comment by str4d** [comment]
Hi!

Yes, `sudo` is used to get admin rights to execute the command (in this case, install packages). If `sudo` isn't being found, that is an issue with your Debian / Parallels setup rather than with Zcash. None of us developers are using that setup, so I'm afraid you're unlikely to find answers here.

A better place to look for help regarding this would be our forum: https://forum.z.cash/ It's quite possible that another user has encountered this before :smiley:

**Comment by jackwatson86** [comment]
Ok cool, I'll give that a try. Thanks 👍

**Comment by anandumdas** [comment]
The error happens because the binary you are trying to call from command line is only part of the current user's PATH variable, but not a part of  root user's PATH.

You can verify this by locating the path of the binary you are trying to access. In my case I was trying to call "bettercap-ng". So I ran,

`$ which bettercap-ng`

`output: /home/user/work/bin/bettercap`

I checked whether this location is part of my root user's PATH.

`$ sudo env | grep ^PATH`

output: `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

So sudo cannot find the binary that I am trying to call from commandline. Hence returns the error command not found. 

You can direct sudo to use the current user's PATH when calling a binary like below.

`$ sudo -E env "PATH=$PATH" [command] [arguments]`

In fact, one can make an alias out of it:

`$ alias mysudo='sudo -E env "PATH=$PATH"'`

It's also possible to name the alias itself sudo, replacing the original sudo.

Please refer to [this video][1] for step by step solution


  [1]: https://youtu.be/nTLuTZqQbNI
