### ISSUE TITLE
Add idempotent versions of RPC operation status queries

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1293]
It's necessary to have the option for these queries not to consume completed statuses, as I noted on #701.

**Comment by bitcartel** [comment]
Discussed previously with @nathan-at-least that we did not have a policy as to how long the result of an operation should stay in memory or if it should be persisted to disk.

During that discussion it was decided that  z_getoperationstatus should return the result and remove it internally.

It might be better for z_getoperationstatus to be idempotent and only return the status (not the result object itself), keeping track of these until another call z_getoperationresult actually retrieves the result, but that would mean a user having to make two calls instead of one.

**Comment by daira** [comment]
The problem is that with the current design it's not possible to implement, e.g., status widgets that don't interfere with the operation of the node.

**Comment by bitcartel** [comment]
How about this?
z_getoperationresult (removes result internally)
z_getoperationstatus (does not remove anything)

**Comment by bitcartel** [comment]
Implemented as part of RPC calls introduced by async z_sendmany.  Closing ticket.
