### ISSUE TITLE
Enable loud hard-fork detection

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#131]
This feature may be a fairly light configuration of an existing feature: #109 is for documenting the existing feature, and it links to this bitcoin-development message which alludes to the feature:

https://www.mail-archive.com/bitcoin-development@lists.sourceforge.net/msg06273.html

**Comment by daira** [comment]
I'd like to revisit whether this should be in 1.0, because I think that putting it in 1.0 would make it much easier to safely implement hard-forking post-1.0 changes.

**Comment by ebfull** [comment]
+1 on revisiting this.

**Comment by zookozcash** [comment]
This seems to be related to https://github.com/zcash/zcash/issues/688. Perhaps https://github.com/zcash/zcash/issues/688 is an implementation of this which causes the node to freeze — ignoring all transactions — in case it detects a hard fork?

**Comment by zookozcash** [comment]
Unfortunately upstream Bitcoin-Core is talking about removing this from that codebase due to it being unsatisfactory in some way: https://botbot.me/freenode/bitcoin-core-dev/2016-03-31/?msg=63274564&page=2 They've been saying, in IRC chat, that they want to put back a "fixed" implementation of it in the future. I don't understand what's wrong with the current implementation or what fixed implementation they'd want.

**Comment by zookozcash** [comment]
Whoops, my mistake. The thing that they're talking about disabling is not the hard-fork-detector, it is the network-partition-detector: https://botbot.me/freenode/bitcoin-core-dev/2016-03-31/?msg=63275812&page=2 Thanks to sipa for clarifying!

**Comment by defuse** [comment]
#1009 makes it run the `-alertnotify` command when there's a hard fork adds an RPC test that checks the hard fork detection.
