### ISSUE TITLE
Extensible payment addresses

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1344]
One axis for changing the protocol to support new features is to add new information in payment addresses.

As a concrete example, suppose that we want to include a field in addresses that will be included in the memo of notes sent to that address, so that it is possible to generate addresses distinguishable by the recipient without additional overhead. (To give credit where it is due, this is a pattern I first saw in the "data byte" of start keys in the  [KeyKOS](https://www.cis.upenn.edu/~KeyKOS/NanoKernel/NanoKernel.html) capability operating system.)

With the current spec, an obstacle to adding such extensions would be that current clients will reject the new address format. It might be preferable, for a particular extension, to allow use of a new address without the new functionality.

This obstacle can be eliminated very simply by making the format of addresses extensible: in section 5.6.3 'Protected Payment Addresses' of the spec, allow the raw encoding of an address to be longer than the current 66 bytes, and say that any bytes after that are ignored, but retained when addresses are stored in wallets. (The purpose of retaining them is that if you obtain an address _and then_ upgrade your wallet, the new functionality will Just Work for existing addresses.)

**Comment by daira** [comment]
A disadvantage of this is that it means an address is in general no longer completely determined by its spending key.

**Comment by nathan-at-least** [comment]
Hm...  I'd like to postpone discussion of post 1.0 features at least for one or two weeks/eng meetings to focus on Beta releases and 1.0 launch. @daira if we remove the label can you remember to reset it in two weeks?

**Comment by daira** [comment]
Er, probably not. Shall I remove the label but put it in the beta2 milestone so that we don't forget it?

**Comment by nathan-at-least** [comment]
Let's leave the label and we'll probably postpone discussion to a later week.

**Comment by nathan-at-least** [comment]
Two potential drawbacks:

* If addresses with new extensions appear, they will have different lengths, and this will have some side-effects throughout the protocol. Eg: if they appear in encrypted notes, then note encryptions will need to be extended to support the extension (thus introducing a backwards incompatible transaction difference). However, it might be useful to have flexibility in part of the protocol (eg addresses) even if we don't know *now* how to address other parts of the protocol (eg note encryption).
* There may be DOS vectors or parsing ambiguity or chosen-input-flexiblity issues if we allow senders to insert arbitrary noise anywhere an address appears.

Two alternative directions moving forward:
a. Do nothing, launch with "non-extensible addresses", figure out how to deploy them later in an upgrade. In this world, all clients in the future would have to support the new and old formats.
b. Do extensible addresses now, and do them well. In this world, we risk introducing protocol vulnerabilities for the benefit that all clients can support a single address format moving forward.

**Comment by ebfull** [comment]
I know that we will want to combine `pk_enc` and `a_pk` somehow in the future, can whatever solution we come up with leave room for a combination like that in the future if possible?

**Comment by str4d** [comment]
For that, we'd probably want to add an additional version or flag byte, and have it encoded before the current content (which makes it a slightly less trivial change than @daira's proposal). I'd be inclined to have this inside the ZCPaymentAddress class rather than the base58 encoding, so that we retain the `zc` prefix whether or not extensions are used.

**Comment by daira** [comment]
Addresses do not appear in encrypted notes, so that's not a problem.

I disagree that there are parsing ambiguity or DoS issues. Parsing is unambiguous and will be clearly specified; there's no reason to believe that a parsing issue here is more likely than anywhere else. The proposed spec has a limit of 66 bytes for the extension field to address DoS concerns. I don't understand precisely what is meant by chosen-input-flexibility issues, but note that the creator already has a lot of flexibility; vanity Zcash addresses are certainly possible (although somewhat expensive to generate), and there's already no guarantee that any given address will be valid.

The encoding of a<sub>pk</sub> already has four reserved bits (one of which matches up with a reserved bit in the PRF input formats) to enable changes that affect the existing a<sub>pk</sub> and pk<sub>enc</sub> fields. But using that would require a hard fork, and four bits are only enough for a tag to distinguish completely new address types. This extensibility proposal is specifically for additions to an address that shouldn't affect the ability to use it with the existing protocol.

This proposal does introduce a (minor, IMHO) complication that is worth thinking about: with this change there will be multiple valid addresses for the same spending key — whereas currently a valid z-address is completely determined by its spending key. Note that Zerocash never had the property that an address is determined only by the spending key, anyway, so this cannot be introducing any cryptographic weakness relative to Zerocash.

So, I'm still in favour of this proposal. Note that it isn't a consensus change, although I'd like to do it anyway in beta 2 if possible.

**Comment by str4d** [comment]
> Addresses do not appear in encrypted notes, so that's not a problem.

Ah yes, I was misremembering that a note contains `a_pk`, which is linkable to the address but not the whole address. My DoS concern is alleviated :smile:

**Comment by daira** [comment]
I don't quite understand what the concern was, but I guess that's academic.

**Comment by nathan-at-least** [comment]
My overall concern is "I don't believe we have time to cautiously evaluate the safety of protocol changes that are system-wide and have long term impacts."

Is it true that the only reason to rush it is to avoid future clients to support two address formats for compatibility reasons? Maybe I'm underestimating *that* cost, but to me it seems like a much safer route.

I may be wrong. _I_ certainly am pretty constrained on time. We'd want to have auditors carefully review changes. We've tried rushing in "simplifying protocol changes" already and it did not work well. As stated publicly in the blog about the beta series and by myself on many occasions: *the purpose of the Beta and RC releases is to fix critical flaws or security issues*. In my opinion, that *tends* to exclude changes for removing technical debt, because technical debt isn't an urgent (short term) flaw. It could be argued to be a long-term flaw, but it's not a show-stopper, and so I *might* be convinced, but I have a very high bar for accepting changes with systemic impact. (A counterexample is changing our address format prefixes, so maybe it's worthwhile for me to reread the following criticisms using that as a candidate change.)

Okay, so that's my stance. Everything that follows is more brainstorming about how this could go wrong in ways that we don't have adequate time to evaluate.

I didn't spend much time to evaluate the proposal, and I was just spitballing concerns. My point is that I don't have confidence that I personally will be able to notice all possible negative impacts to security, usability, scalability, etc...

So, just going depth first on parsing and flexibility:

> I disagree that there are parsing ambiguity or DoS issues. Parsing is unambiguous and will be clearly specified; there's no reason to believe that a parsing issue here is more likely than anywhere else.

I disagree. The basic premise is that an order-of-magnitude more software and systems will handle addresses compared to any other piece of our protocol.

If we're successful, they'll appear on block explorers, various websites, text messages and emails, projects like OpenBazaar, newly evolving web payment systems, micropayment channels, etc...  Their reach is qualitatively similar to URLs. Obviously we can make this much much simpler than URLs, but there has been pervasive problems with URLs throughout history. Even today different browsers can't agree on the UX of https://microsoft.com@example.org/ and many websites automagic URL parsing fails to accept some URL suffixes.

> I don't understand precisely what is meant by chosen-input-flexibility issues, but note that the creator already has a lot of flexibility;

I meant issues such as you allude to in this paragraph:

> This proposal does introduce a (minor, IMHO) complication that is worth thinking about: with this change there will be multiple valid addresses for the same spending key — whereas currently a valid z-address is completely determined by its spending key. Note that Zerocash never had the property that an address is determined only by the spending key, anyway, so this cannot be introducing any cryptographic weakness relative to Zerocash.

Again, I disagree this is minor. Can a third party who is not the spending authority insert arbitrary data into an address and still end up with a valid address? How does a consumer of these extensions authenticate that the extensions were indeed created by the spending authority holder? What impacts would there be if third parties can modify addresses undetectably? (Remember, the ecosystem for addresses is much larger than just our consensus+p2p protocol.)

Suppose we ensure only the spending authority secret holder can specify extensions. I am still quite concerned that there are now an arbitrary number of addresses for a single spending authority. What tricks or confusions can a malicious spending authority owner pull with this? (Again, these impacts are in an ecosystem much larger than our protocol, thus incredibly difficult to predict.)

In general I consider protocols that allow arbitrary extensions which _should_ be ignored to be qualitatively more dangerous than protocols that must be comprehensively consumed, even though there's an obvious flexiblity and versioning benefit. This kind of flexibility might allow for protocol confusion vulnerabilities (eg: whan a JAR file can also be an image and can thus be hosted on image hosting sites to leverage attacks, eg: when Tor control port used to accept unrecognized lines as no-ops, so malicious HTTP requests could hijack Tor, etc…).

Again, in summary, I don't *know with any certainty* that any of these concerns are valid, but the amount of time it takes to evaluate them safely is far too great at this point in our schedule, IMO, versus the alternative of a future upgrade that introduces two addres formats, old and new/extensible.

**Comment by nathan-at-least** [comment]
Another concern (related to the many addresses per single spending authority):

Suppose software needs to compare two addresses for identity. In our current scheme is it true that this is just a bytewise comparison as per C's `strncmp`?

In the new proposal, how can software successful determine if two addresses are for the same spending authority? (-and what systems will be broken if they assume that's easy or possible to do? Even if it's possible, which systems will be broken because the creators don't realize there's this complex comparison rule and just used `strncmp`?)

Note, if our current address scheme isn't correctly comparable with `strncmp` then this concern *already applies* to our addresses!

**Comment by nathan-at-least** [comment]
I think we all like this in principal, but I'm concerned about various kinds of potential attacks or risks this would introduce around address comparisons, extension stripping, etc... so we're postponing consideration of this feature for later.

**Comment by daira** [comment]
The issue that changed my mind about including this in 1.0 is the following: suppose we define an address extension and all clients have changed to support it. I publish an address that uses the extension. Then, an attacker can strip the extension and publish a related address that will force a downgrade to the old functionality, even in clients have have upgraded.

**Comment by daira** [comment]
Note that the above "extension stripping" objection could be solved if the address were made nonmalleable, for example, by including a signature of the rest of the address using a component of the address that acts as a signature public key. But even if we used [BLS short signatures](https://en.wikipedia.org/wiki/Boneh%E2%80%93Lynn%E2%80%93Shacham) for that, it would increase the raw address size by 32 bytes (~44 characters in Base58).

**Comment by daira** [comment]
I nevertheless think that we should discuss this for the Sapling upgrade, since there might be some other way around the extension-stripping issue, or we may decide the advantages of extensibility outweigh that issue.

**Comment by daira** [comment]
If we were to implement #340 (Address Registration Protocol), then user-visible addresses would remain short, but the lower-level addresses they map to could be extensible without impeding usability or security, since there would be less pressure on their length.

**Comment by veikkoeeva** [comment]
@daira To add to the discussion, the payment card numbers [have a meaning](https://en.wikipedia.org/wiki/Payment_card_number) (see also [www.binlist.net](https://binlist.net/)). Maybe it could be thought of as a physical world token, which alone can be used to determine something about the cyber-world. It's like "pre-decentralized" a bit already.

A quote from the Wikipedia link:
> In the United States, IINs are also used in NCPDP pharmacy claims to identify processors, and are printed on all pharmacy insurance cards. IINs are the primary routing mechanism for real-time claims.

I am not sure if the serials in cards would be just some random numbers with check codes if the system were devised in the current world. I'm not an expert. :)

**Comment by daira** [comment]
@veikkoeeva Card numbers do have structure, but we want the short ids to be unlinkable, so they wouldn't have non-random structure.

**Comment by daira** [comment]
The argument that convinced me we weren't ready to support extensible addresses for Sprout was @nathan-at-least's point about the extension fields not being protected against modification (that is, an adversary could potentially derive an advantage from publishing an address differing from the target's in an extension field, and observing the target's interaction with payments sent to that address).

#570 offers a way to solve that problem because the diversifier is effectively integrity-protected: a recipient can always detect modification of this field, and attempted payments to such a modified address will fail. (In fact this is to prevent an attack precisely of the form Nathan conjectured.)

So, at the expense of some loss of indistinguishability of addresses in the case where extensions are used (because at least the length is visible), we could add a reserved bit to the diversifier which would allow extensions when it is set. If the length of the diversifier were less than an input block of the GH hash &ndash;e.g. 64 bytes for Blake2s&ndash; this would cause no additional circuit overhead.

Relevant to #2528.

**Comment by daira** [comment]
How about this: the internal form of the diversifier is always 512 bits (a Blake2s input block), but the encoding of an address allows compact representation when only some bits are used. We only generate and import *private* keys with an 80-bit diversifier, but we allow payments to addresses with longer diversifiers, and warn that future versions of the protocol may define new behaviour for those on the receiving side.

**Comment by daira** [comment]
Unified Addresses are extensible, so this ticket is essentially done.
