### ISSUE TITLE
NCC-2016-007 - Upgrade OpenSSL

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1348]
Short-term alternative to #145 (Investigate feasibility of removing OpenSSL dependency).

Note that code we've written no longer depends on OpenSSL, but code inherited from Bitcoin does.

**Comment by str4d** [comment]
I'm working on this as part of #867, and looking to jump to 1.1.0 if possible. One minor blocker on determining how hard this will be is that OpenSSL 1.1.0 gets mistaken for LibreSSL, which causes the default compile to fail (backhistory: before BIP66, using LibreSSL instead of OpenSSL was technically consensus-breaking). Since BIP66 has been accepted, bitcoin/bitcoin#6732 removed that check.

Our codebase forked after BIP66 landed, and the checkpoint for requiring it was `block.nVersion >= 3`. Since we use `block.nVersion = 4`, we are guaranteed to be fine for this, and so I will backport the Bitcoin PR (made slightly more complicated because a build fix in bitcoin/bitcoin#6501 was only half-backported to 0.11 in bitcoin/bitcoin#6703, which we forked on top of).

**Comment by str4d** [comment]
Side-note: I've tried this evening / early morning to migrate to both 1.0.1t and 1.0.2h in addition to 1.1.0; all three had issues, so I figure I may as well work on the one that is supported.

Also, I am aware of the upcoming security releases for all three branches, and will use then when available.

**Comment by str4d** [comment]
[Boost doesn't yet support OpenSSL 1.1.0](https://svn.boost.org/trac/boost/ticket/12238), but there are patches linked in that ticket that enable support (once ported to Boost 1.62), which I have ported and applied. The only other changes necessary are to `src/ecwrapper.cpp` to use the upgraded API.

**Comment by str4d** [comment]
Also `src/wallet/crypter.cpp` (a simple change) and `src/test/bignum.h` (not so much, haven't figured out a bypass yet).

**Comment by str4d** [comment]
I now have Zcash compiling with OpenSSL 1.1.0 and all tests pass locally.

**Comment by ageis** [comment]
https://mta.openssl.org/pipermail/openssl-announce/2016-September/000080.html

**Comment by nathan-at-least** [comment]
Came here to see if we're going with `1.1.0b` as per @rcseacord's recommendation in email, and that looks like the most recent commit. Nice work @str4d!

It sounds like we should routinely check for openssl upgrades due to a high rate of expected security issues/patches. Of course our higher priority longer term goal is to remove it as a dependency, a la #145, but until we do, let's not neglect upgrades.

**Comment by str4d** [comment]
Boost 1.62 includes the patches for supporting OpenSSL 1.1.0, so I have removed them from #1429.

**Comment by daira** [comment]
Let's routinely upgrade OpenSSL on every release. In addition, we should pay attention to OpenSSL security advisories to see whether an unscheduled release is needed (this would probably only be the case if we has reason to believe the vulnerability affects Zcash; many OpenSSL bugs are specific to the SSL/TLS/DTLS/X.509 code which Zcash does not use).

**Comment by str4d** [comment]
@daira agreed. I have updated the release process in #1429 to remind future release managers.
