### ISSUE TITLE
Do we want non-outsourceable PoW?

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#138]
@amiller just presented a new result that allows converting (any?) PoW puzzle into a non-outsourceable version. Is this practically applicable today? If so, should we make nonoutsourceable a property requirement for PoW?

**Comment by daira** [comment]
@zookozcash: Isn't the issue whether individual miners are able to effectively compete with centralised large-scale ones (regardless of whether the later are centralised polls or centralised custom mines)? Surely anything we can do to encourage individual mining relative to centralised mining is helpful.

**Comment by amiller** [comment]
@daira My opinion that adopting a non-outsourceable puzzle, without *also* adopting at the same time several other significant changes to the reward payout scheme (as described in the paper), would likely make centralization even worse.

  Basically, mining pools (at least, some of the ones today) are the most benign form of coalition, but also the most fragile... even weak nonoutsourceable puzzles would make low-signup-cost pools impossible to join. I say they are "most benign" mainly because: 1. pool members own their own equipment, so they can easily switch from one pool to another (or to solo mining) if the first one is caught being bad,  2. some pools allow members to choose their own transactions to include, and 3. P2Pool in particular is awesome and legitimately decentralized, if only we could steer more miners to it.

The most dangerous form of coalition, in my opinion, is large hosted-mining services that own their own equipment, get massive benefits of economy of scale, and sell "shares" of their equipment to customers to raise even more money to invest in more growth. Especially since their customers might otherwise be solo miners if not tempted away.

**Comment by taoeffect** [comment]
Clarity would be appreciated. If by "non-outsourceable" you're saying that mining pools should consist of machines that are owned only by the owner of the mining pool, then that has some serious negative consequences that need to first be addressed.

Such a system would disenfranchise most people from being able to participate in mining.

I'm still not clear on the relationship and implications of zk-SNARKs and the PoW algorithm, but at least in Bitcoin what is desirable is a PoW algorithm that allows transaction selection at the edges (such as Bitcoin's P2Pool, and Bitcoin's GetBlockTemplate stuff).
