### ISSUE TITLE
Remove fPowAllowMinDifficultyBlocks

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1380]
On the Bitcoin testnet, minimum-difficulty blocks are allowed after double the target block interval (according to local time). We removed this behaviour for Zcash in beta 1, as part of #1338. However, we didn't remove the `consensus.fPowAllowMinDifficultyBlocks` variable or the code that uses it in `miner.cpp`. This variable is still set to `true` for the testnet chainparams, which means that the miner is going through a slightly different code path between testnet and mainnet.

Removing `fPowAllowMinDifficultyBlocks` would simplify this code and eliminate the possibility of differently-buggy behaviour on testnet vs mainnet. (It's only a few lines, so this change eliminates more risk than it introduces.)

**Comment by daira** [comment]
Incidentally, I think it's extremely unlikely that we would want to add back the old behaviour (it was a bad idea).

**Comment by bitcartel** [comment]
Agree we should disable for launch but perhaps use an assert rather than remove the code.  There is a possible use-case for a minimum difficulty block on mainnet: to prevent sudden-withdrawal infanticide where an attacker is not motivated by mining reward but instead wants to disrupt the network to render it unreliable and unusable for practical purposes.  Needs more discussion post-launch etc.

**Comment by daira** [comment]
I think we should remove the code; it's distracting and nothing prevents us from putting it back. Note that minimum-difficulty blocks violate the principle that consensus only depends on the history of blocks, so it would be a security flaw to allow them on mainnet (the only way to verify them would be to trust the block timestamps, which are obviously not trustworthy).

**Comment by bitcartel** [comment]
Low priority.
