### ISSUE TITLE
Design per-block ``{addr -> [ UTXO ] }`` tree root into block headers.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#139]
If verifiers must construct and verify the root of a per-block UTXO map, this would remove a vulnerability SPV clients have towards the SPV service in upstream Bitcoin:

In Bitcoin an SPV client follows the longest PoW chain headers, but does not know about transactions. They must request relevant UTXO's from an SPV service, and that service may omit relevant transactions.

If instead, the service could provide a UTXO set and a single proof that it maps to the current block root, the client can justifiably believe this is set is complete and fresh.

Notice also, that in the upstream design, _each_ UTXO requires a merkle path to the transaction root of some block, whereas in the alternative there is only a single merkle path (to a different root: UTXO map rather than transactions list).

Full verifying wallets need to track the map of `{addr → [ UTXO ] }` for any addr of interest already, so the _code_ complexity of this change should not be large. However, we need to consider the operational costs, because now the map expands to _all_ UTXO's for any address.

_Caveat:_ Neither alternative protects the confidentiality of the SPV client from the SPV service. This is a separate problem, which we should ticket separately for either alternative we choose.

**Comment by amiller** [comment]
Another advantage is that you can have a "gradual full node" that uses a checkpoint or an SPV proof to find the best chain, and then downloads just the state pertaining to the most recent block. (The state in Zcash would correspond to the leading edge of the commitment tree, the utxo set, and the serial numbers set). This can be much faster than downloading the entire chain.

I believe it is possible to soft-fork to include such a commitment, for example in the coinbase transaction. As long as the data structure can be computed deterministically from the blockchain, then the upgrade timeline would look like:
- upgraded nodes begin computing the data structure (if it needs an extra pass over historic data, then this may take a while or require a batch/background process)
- upgraded nodes begin including the root of this data structure in their coinbase transactions
- once the vast majority of blocks contain the correct commitment structure, miners begin rejecting blocks that do not contain it

**Comment by defuse** [comment]
I wonder if in Zcash we can prove to an SPV client that a coin hasn't been spent in a simpler way than you could prove a cleartext transaction is in the UTXO set. Just sort the spent serials list (which we already have) and send two paths on both sides of where the supposedly-unspent coin's serial would go if it had been spent. Since the list is sorted, the SPV client is convinced that serial hasn't been spent.

It might be more efficient since with a Merkle tree over the UTXO set you have to append elements to the end and remove elements from unpredictable places but with the serials list you just have to insert elements in unpredictable places. Maybe there's some cool kind of Merkle tree that lets you do that without completely regenerating the tree.

**Comment by nuttycom** [comment]
Our focus is on shielded functionality, and this doesn't really have a strongly motivating use case.
