### ISSUE TITLE
Recommendation 6.9 - alter signature hash to cover hashes of ins/outs instead of their pre-images.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1408]
We haven't determined if we will do this for Beta 2 yet, but it deserves evaluation.

**Comment by str4d** [comment]
@daira and I paired on this and implemented an alternative proposal that splits up the common and per-input data for serialization. We think this will make future caching much simpler, as then we will only need to cache a single 256-bit hash for the transaction, rather than one hash per input('s output) and output.

**Comment by str4d** [comment]
Per https://github.com/zcash/zcash/pull/1421#issuecomment-249704702, we've removed this is a target for our launch. To upgrade to something like this after launch, we'll need to go through the ZIP process.

**Comment by str4d** [comment]
I think that (as has been discussed previously) we should consider making the existing per-node 100kB transaction size limit a consensus parameter, at least for launch. We can always hard-fork to increase it later when we implement a proper fix for this.
