### ISSUE TITLE
Change block reward to smooth asymptotic function.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#143]
Bitcoin has block reward halvings on block heights that roughly correspond to every four years. It's not clear what impact the halving events have on the economy, but it is clear that they are qualitative shifts in monetary policy over time.

A similar overall and long term monetary policy (approximating asymptotic approach to a fixed constant cap) can be implemented that adjusts every block. My thinking here is that doing so can "smooth out" any impact of decreasing block rewards and remove the need for anticipating/predicting-outcomes of sudden shifts every four years, without altering the larger scale overall monetary policy behavior.

A drawback is that Bitcoin's halving rule is simpler to state and it's easier to remember what the block reward is, whereas with a "smooth function", people would need to calculate or look up today's reward, next month's reward, etc...

**Comment by tromer** [comment]
I strongly support a smooth reward function in principle, but concede that, conditioned on Bitcoin-as-we-know-it surviving 11 Jul 2016 (http://www.bitcoinblockhalf.com/), we too can bite the bullet in v1.0.

**Comment by ebfull** [comment]
I would like us to consider not biting the bullet if possible. I think with the block subsidy changes we've made for slow start mining that this should be reconsidered as a holistic solution.

**Comment by zookozcash** [comment]
Let's not reconsider feature-selection decisions unless there's a compelling reason to think our previous decision is dangerous to the success of Sprout. I don't think this one qualifies. The first halving won't even occur until long after Sprout's launch so we can think about it after Sprout.

**Comment by ebfull** [comment]
I do agree that we could add this after Sprout, so this isn't an emergency or anything, but it might be easier to just do it now if we're already making changes to the block subsidy code that breaks our upstream delta minimization goals. Additionally, rejecting this for 1.0 was a decision we made over a year ago, so it's worth discussing at the engineering meeting I think.

**Comment by ebfull** [comment]
> Let's not reconsider feature-selection decisions unless there's a compelling reason to think our previous decision is dangerous to the success of Sprout.

I agree with this, but in this case it has a debatable impact on things such as the founders' reward and so on, so it may not just be easier to do it now technically but also politically. (Whether that meets a "danger" standard or not is anyone's guess.)

**Comment by daira** [comment]
We can't actually change this after Sprout. We're effectively committing to a particular money supply curve by launching (actually by what we say before the launch), and any attempt to change it would be so contentious as to be not worth the benefits.

**Comment by zookozcash** [comment]
I don't necessarily agree. In any case I don't want to spend time on this issue now. We have more important things to do! (https://github.com/zcash/zcash/milestones)

**Comment by daira** [comment]
Let's agree that next week's engineering meeting is our last chance to change this. I'm in favour of changing it then, but strongly opposed to any change later if we agree not to do it then.

**Comment by zookozcash** [comment]
Let's agree that our last chance to change feature-selection for Sprout was the engineering meeting several weeks ago! In fact, I think that was already our agreement.

**Comment by nathan-at-least** [comment]
I concur with Zooko. This is one of the dozens (or hundreds) of equally "easy-and-kind-of-important" little things we've excluded for 1.0. In addition to that, we're late with the testing milestone, in danger of the current milestone slipping, and the next milestone seems overfull. We already have a full load to launch with just the features we've already agreed on! Let's not waste precious diminishing meeting time revisiting tickets with "not in 1.0".

**Comment by nathan-at-least** [comment]
I'm going to remove "engineering meeting agenda". We've already made this decision, and decision churn is a major cost for us.

**Comment by str4d** [comment]
Having implemented the mining slow start, I concur with Zooko also. The mining slow start only adds one small ramp change, and is enough to cause considerable work in the tests. Changing to a smooth function would in itself be trivially easy (like slow start was), but would have a high test load. It would also result in a different total monetary supply (due to Zatoshi rounding issues in the "smooth" function), which has already been publicly committed-to by Zooko.

**Comment by zawy12** [comment]
I came here concerned about the meaning of the phrase "Zcash Sprout" in the blog.  That sounds like one of several future product launches.  But the whole point of a coin is to not change in its character.  I thought the supply curve was supposed to be a contract no one can break.   So the following is a little concerning:

Daira
> We can't actually change this after Sprout. We're effectively committing to a particular money supply curve

Zookozcash
>I don't necessarily agree.

A change to the curve seems like it's not too far away from changing the quantity. Is anonymity going to be as flexible as coin issuance?  Of course I don't think so. But seeing the word "Sprout" in place of a simple "launch" was a red flag.

**Comment by ebfull** [comment]
I can't speak for Zooko, but I believe he was trying to say that making the reward a smooth asymptotic function would not break our commitment to the supply curve; i.e., it would not increase the total currency supply nor would it significantly impact economics. I agree, and I think it's doubtful such a change would be controversial.

"Sprout" is our codename for 1.0, just like Ethereum branded their earlier release "Frontier." We want people to understand that "Zcash will begin life as a young, tender thing, but will be a living organism with great potential to grow." It is not a separate product.

**Comment by zawy12** [comment]
I actually agree supply curve might need to change even after launches, if it advances core objectives. But for marketing purposes it is risky because it gives the impression developers could and would change quantity. 

My sensitivity to seeing it considered is partly based on decision-makers being large holders of the coin in quantities unknown even to each other. The rest of this paragraph is against this type of proof-of-stake voting, an issue I posted on yesterday [#1112](https://github.com/zcash/zcash/issues/1112) The complexity of the tech issues in Zcash makes the founders de facto stock-like insiders despite it being open source. Explicit voting by size of stake is bad because it is a bias for short term holding value at expense of long-term marketplace-use value, which is the basis of long term holding value. Voting by size of stake under the pretense of having an unbiased interest in the long-term health of the coin is worse. Proof of stake voting underlies Bitcoin's woes. "Our developers will not mine". But how will you know? I am not really concerned about this major concern, but the laws have not caught up and the company could accidentally do things that would normally be illegal if it follows a path that is intuitively good.  Voting by size of stake is a bias towards a chain letter. Doing it secretly is a bias towards ponziness.   Does Satoshi's abandonment of the project indicate awareness of a conflict of interest as a large stakeholder / insider that should be illegal? Would him selling without disclosure normally be illegal and the reason he has not sold any?  

All things considered, I think the company should explicitly state its contract with society (what the coin must always be) in its principles of organization, self-referentially unmodifiable, with a copy-left inheritance requirement in the event of a buyout, rigidly connected to and defining the "Zcash"
trademark. The target audience of the contract would be with future holders of the coin, not current holders. Then add it to the blog and code, before launch.

ETH giving release names seems more necessary because the system's philosophy and understanding of itself is still changing. This is why I have very little interest in it. I would like an asset. I want them to succeed in replacing government and banking. But I still want an asset I can understand that is not connected to complexity and self-identity confusion, let alone "Turing-complete security holes".

Both supply curve and name changes give an impression of "instability". Name changing is more of an issue with me because it implies the coin's identity is changing.  That's great for improving products who's primary features are changing. They need to change identity in order to advance. But Zcash should have a rigid, limited, stated philosophical identity like Excel and Powerpoint instead of CPU-like name changes.  I think Zcash is trying to be anonynous, secure, bitcoin quantity and at least similar curve, distributed mining as much as possible, and fast and efficient as much as possible.  Since these features should only improve and without substantial change or any foreseeable addition, names seem to add only confusion as to what the name means (is it one of many products under a Zcash company umbrella? Has the coin changed it's anonymizing or hash method?)  and gives an impression of changeability.  Of course everyone wants the product to improve the stated goals, but not to otherwise change. A major anonymizing or hash algorithm change is a detail that should fall under Zcash "2.0" or whatever release notes.

**Comment by zawy12** [comment]
I know it's not going to be worked on in the near term, but here are the best linear and exponential decay solutions to this issue I can come up with.

If exponential decay is judged too messy, it will help to know that under linear decay total coins produced is Total=R/2*(N^2+N).  Set Total to remaining coins needed, N to remaining blocks, and solve for R. 

Unlike the above, there is not a decay rate that needs to be solved for exponential decay because Satoshi already chose it.  The question is at what block number is it applied so that the number of blocks and total coins come out correct.

Half-life decay is exponential decay in disguise because there's just a conversion factor:  2^(-x) = e^(-0.693*x).  An exponential decrease instead of a linear decrease might be needed to keep the "spirit of Satoshi". He might have had a reason for exponential instead of linear decay. However, such sudden drops would indicate it's not really a big deal.  And sudden halvings allowed ending on 1 satoshi rewards.

Assume Zcash will use R= 0.0005 coin/block ramp for 1st 25000 blocks as mentioned, then 12.5 ZEC/block for a while.  How long should 12.5 ZEC/block issued so that a continuous Satoshi-like halving function ends up with 21M after the correct 6.93M*4 blocks?  The answer from experiment, summing up all the blocks "Satoshi's" exponential decay function is:  at block **480636** which is a little more than half way in to the first "BTC" halving event, a little over 2 years.
 
Derivation of the most Satoshi-like halving function is straightforward:
Bitcoin:
BTC/block = 50*2^(-H/33) where H is halving event number.
To make it "continuous" as a function of block number and in ZEC terms, this becomes:
 ZEC/block = 12.5*2^(-N/840000)  which means it is halved after 840000 which comes from bitcoin*4: 210,000*4 blocks.
This would be 15M instead of 21M ZEC if it began at block 1 because the heavily-weighted front end was not decreasing from day 1 in Satoshi's scheme.  So not using a continuous halving formula at the beginning actually shifts the curve to accidentally help solve this. The more correct math would have been to start with more than 12.5 ZEC/block, but that would have caused the known problems.

So the answer continuous halving decay formula is:
**ZEC/block per N after 480636 blocks = 12.5*2^(-N/840000)** 
where N is number of blocks after 480636.  At N=1 this is 12.49998969.  At N=2, 12.49997937. Rounding errors negate each other. The last 700,000 blocks of the total 27,720,000 ZEC blocks (4*bitcoin) are a roughly linear decrease from 0.5E-8 to 0.3E-8 ZEC/block, below a Satoshi. They sum up to about 0.003 ZEC.

**Comment by daira** [comment]
I think it was an oversight that this ticket was not already closed in May. Can we close it now?

**Comment by zookozcash** [comment]
Thank you for the analysis, zawy!

**Comment by zawy12** [comment]
To demonstrate the year example above more easily: dropping each year by 2^(-1/4) is 16% (0.8408964153),  giving the 1/2 drop every four years because 2^(-1/4) ^ 4 = 1/2.  This permits every 4 years to fall on a whole ZEC value.    This is what the script above does.  It is so complicated to make sure 21M coins would be generated and to see how many coins and blocks short it will be.  There is no simple way to get the exact number of coins and blocks without adding something.

Correction: 
Year needs to be 365.25 to account for leap years. This gives starting at block 582786.
90 days and 30 days my need to be changed to 365.25/12 and 365.25/4.

**Comment by zookozcash** [comment]
I don't think there is much enthusiasm in the broader community for making this change, and I think there would probably be substantial pushback from the broader community. And, I don't think this change is a big improvement. I don't know if it is an improvement at all. Let's forget about it so we can spend 1/1000th of our brain on each of 1000 other more important improvements. :-)
