### ISSUE TITLE
Research GHOST, the Ethereum-variant there-of, and DAG-chains

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#15]
In my opinion, this area of mining/consensus design space is probably outside our desired features list.  However, it'd be prudent to understand them and the arguments that they may help with lower confirmation times, and pool-centralization resistance.

Sompolinsky and Zohar authored [GHOST](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CCAQFjAA&url=https%3A%2F%2Feprint.iacr.org%2F2013%2F881.pdf&ei=M4KHVPynKcW1oQTCgIHoDw&usg=AFQjCNH3OFYZrdhjmR0GTaf4dk0OFuJOzg&bvm=bv.81456516,d.cGU&cad=rja), and the [Ethereum Design Rationale](https://github.com/ethereum/wiki/wiki/Design-Rationale) describes their modified incentives as well as alluding to newer work by Sompolinsky and Zohar wrt block DAGs.

**Comment by joshmh** [comment]
I hope it's not bad protocol to comment on a long closed ticket, although it's still being referenced, so it seems fair game. This ticket is already an excellent summary.

This is just an update to note that Ethereum's version of GHOST has been running very successfully on the main chain for a few months now, as Ethereum became the 2nd biggest altcoin after Bitcoin. I haven't researched this much, but block times have certainly been kept to around 17 seconds. Other than one bug which has now been corrected, I haven't heard of any issues with the protocol.

I'm not suggesting that this ticket be re-opened or that this feature be implemented in 1.0. I just wanted to add some info, to note that this algorithm has been implemented and is being field tested in the 2nd biggest altcoin. From my perspective in the Bitcoin ATM business, this is one of Ethereum's most compelling advantages over Bitcoin. Processing Bitcoin-to-cash transactions is a nightmare with long confirmations and I suspect this is the case in many Point-of-Sale situations.

I agree it's not practical to implement this in 1.0 because of its code complexity. However, if one were looking for extra features to add beyond privacy, this would probably be my top choice, especially because it would be difficult to add later due to required changes in wallets, miners and clients.
