### ISSUE TITLE
zcashd crashes after sending to a ZAddr from encrypted wallet

### ISSUE THREAD

**Issue by vaklinov** [zcash/zcash#1502]
I have reproduced this problem several times with ZCash beta2 - I think it is critical. Steps to reproduce:

1. Start with an unencrypted wallet that has some Z Addresses - at least one with some balance
2. Encrypt the wallet 
3. Send some cash from one ZAddr to the other in the same wallet (via z_sendmany)

When the transaction gets included in the next block zcashd crashes with an assertion failure:
```
zcashd: wallet/wallet.cpp:1140: mapNoteData_t CWallet::FindMyNotes(const CTransaction&) const: Assertion `GetSpendingKey(address, key)' failed.
```
I attach here a ZIP with the unencrypted and also the encrypted version of the wallet (password is 1234): [crash_wallet.zip](https://github.com/zcash/zcash/files/518228/crash_wallet.zip)

I have built  ZCash beta2 from source on an Ubuntu 15.10: Linux ivan-laptop 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by str4d** [comment]
@daira and I diagnosed this in our pairing. The issue is that when the wallet is locked, `FindMyNotes` can't cache the nullifiers for received notes, because it can't get the spending key. It currently crashes because it assumes that it can. The first-order fix is that it should just not cache nullifiers when the wallet is locked, and then cache them as soon as the wallet does get unlocked. However, this results in two further issues:

1. Parent transactions can't be marked dirty in `MarkAffectedTransactionsDirty` when a transaction that spends their output notes is updated.
2. `GetFilteredNotes` can't filter out notes without cached nullifiers as spent.

I don't believe that @bitcartel implemented any caching of values for notes, so 1 is not a problem (for now). `GetFilteredNotes` is used in three places:

- `z_getbalance`
  - This could become inconsistent.
- `z_listreceivedbyaddress`
  - Not a problem, because this doesn't try to filter out spent notes.
- `z_sendmany`
  - Not a problem, because the wallet must be unlocked in order to spend anything.

We decided that the only time the wallet could incorrectly believe a note was not spent would be if someone with access to the spending key spent the note from a different Zcash node, or if the transaction was created manually somehow. Thus this should be a rare case in general, and so we think it is okay for the wallet to assume that a note is not spent. The worst that will happen is that `z_getbalance` will show a larger balance than is available, but the `z_sendmany` call fails. `z_getbalance` will show the correct balance immediately afterwards.

**Comment by daira** [comment]
That sounds right to me.

We need:
* a test that provokes the current bug;
* another test that spends a note while the wallet is locked (we can just mine a raw transaction to do that), checks that the ``z_getbalance`` result is *not* updated, and then checks that it *is* updated as soon as the wallet is unlocked.

**Comment by str4d** [comment]
I'm still working on tests, but for now here's the comment I'm planning to add just above the definition of `mapNullifiersToNotes` in `CWallet`:

```
    /**
     * The reverse mapping of nullifiers to notes.
     *
     * The mapping cannot be updated while an encrypted wallet is locked,
     * because we need the SpendingKey to create the nullifier (#1502). This has
     * several implications for transactions added to the wallet while locked:
     *
     * - Parent transactions can't be marked dirty when a child transaction that
     *   spends their output notes is updated.
     *
     *   - We currently don't cache any note values, so this is not a problem,
     *     yet.
     *
     * - GetFilteredNotes can't filter out spent notes.
     *
     *   - Per the comment in CNoteData, we assume that if we don't have a
     *     cached nullifier, the note is not spent.
     *
     * Another more problematic implication is that the wallet can fail to
     * detect transactions on the blockchain that spend our notes. There are two
     * possible cases in which this could happen:
     *
     * - We receive a note when the wallet is locked, and then spend it using a
     *   different wallet client.
     *
     * - We spend from a PaymentAddress we control, then we export the
     *   SpendingKey and import it into a new wallet, and reindex/rescan to find
     *   the old transactions.
     *
     * The wallet will only miss "pure" spends - transactions that are only
     * linked to us by the fact that they contain notes we spent. If it also
     * sends notes to us, or interacts with our transparent addresses, we will
     * detect the transaction and add it to the wallet (again without caching
     * nullifiers for new notes). As by default JoinSplits send change back to
     * the origin PaymentAddress, the wallet should rarely miss transactions.
     *
     * To work around these issues, whenever the wallet is unlocked, we scan all
     * cached notes, and cache any missing nullifiers. Since the wallet must be
     * unlocked in order to spend notes, this means that GetFilteredNotes will
     * always behave correctly within that context (and any other uses will give
     * correct responses afterwards), for the transactions that the wallet was
     * able to detect. Any missing transactions can be rediscovered by:
     *
     * - Unlocking the wallet (to fill all nullifier caches).
     *
     * - Restarting the node with -reindex (which operates on a locked wallet
     *   but with the now-cached nullifiers).
     *
     * Several rounds of this may be required to incrementally fill the
     * nullifier caches of discovered notes.
     */
```

**Comment by daira** [comment]
The having to do several rounds of reindexing sounds like a significant usability problem.

**Comment by str4d** [comment]
@daira On second thought, I'm not actually sure if several rounds are necessary. The wallet can only miss pure spends, ie. those only linked to us by their nullifiers. My original thought with that comment was that you could get chains of JS transactions that need to be uncovered, but mid-points in the chain will always be discovered because all JoinSplits are trial-decrypted regardless of nullifiers. Thus we should only ever miss the ends of chains, so a single reindex should be sufficient.

**Comment by daira** [comment]
I wrote at https://github.com/zcash/zcash/issues/1528#issuecomment-253975215 : 
> Ouch, I hadn't realised that the balance seen due to this problem could be greater than the amount the wallet ever had, due to change. (The wallet sees the amount of change notes plus the notes that they were spent from.)
>
> Given that, I'm now in favour of disabling wallet encryption for launch. We need to give a good explanation of why, though. (The other arguments for doing so are: there's no way to decrypt a wallet once encrypted without exporting all the keys; we want to improve the key derivation and switch to authenticated encryption; it's possible to use disk encryption in the short term to mitigate not having wallet encryption.)
