### ISSUE TITLE
Review libsnark for misuse of OpenMP directives

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1517]
I started doing this in https://github.com/zcash/zcash/issues/896#issuecomment-219886855 but that ticket was auto-closed.

**Comment by daira** [comment]
Working on this now.

**Comment by daira** [comment]
There is a systematic problem when profiling is enabled, in that the profiling calls functions that have data races. This was already discussed at https://github.com/zcash/zcash/issues/896#issuecomment-219886855 . In ``src/init.cpp`` and in ``src/gtest/main.cpp`` we set:
```
libsnark::inhibit_profiling_info = true;
libsnark::inhibit_profiling_counters = true;
```
which should be sufficient to avoid this problem. However, I have seen libsnark profiling output from non-gtest parts of the test suite, so I think there are still some more places where this needs to be added for test executables. (It is not ok for tests to have undefined behaviour, even though the attack surface is small.)

**Comment by daira** [comment]
I found no data races in any of the code containing ``#pragma omp`` or the ``MULTICORE`` macro.

Most of it was straightforward parallel loops with independent iterations. There's some tricky code in ``_basic_parallel_radix2_FFT_inner`` that could do with a comment explaining why it is ok.

I did not check for more complicated misuses of OpenMP, so I want to leave this ticket open, but we've done a sufficient review for 1.0.

**Comment by solardiz** [comment]
I tried sending the below to this ticket via e-mail 3 hours ago, but somehow it's not appearing. Sorry if it appears twice:

On Tue, Oct 25, 2016 at 06:51:56PM -0700, Daira Hopwood wrote:
> I found no data races in any of the code containing ``#pragma omp`` or the ``MULTICORE`` macro.

With OpenMP, good practice is to always use default(none) along with explicit private(...) shared(...), so that by default no outer scope variables are visible in the parallel region's scope. This helps spot inadvertent races not only now, but also with future changes. (I always do this in JtR core tree, as well as in yescrypt; JtR jumbo is not always as careful, unfortunately.)

Also, why do we even go for use of threads there (is this code considered performance critical?) if we (IMHO wrongly) don't dare to use -O2 (opting for -O1 instead)? Looks like misguided paranoia to me. ;-)

A risk of OpenMP is that, at least as implemented in gcc's libgomp, it can silently produce wrong results if one of the threads dies (e.g., is OOM-killed on Linux with memory overcommit, which is something I've seen happen when stress-testing yescrypt). The parallel region may complete anyway, and the master thread goes on, but the computation is incomplete. There's no "exit code" from parallel regions - in security-critical code we'd have to invent our own indication that each thread has finished its portion of the computation (e.g., all iterations of a "for" loop actually reached end of block). I like OpenMP and I think when it's appropriate and is appropriately used it makes source code more readable than the code would be with explicit pthreads, but this behavior on error is really nasty.

**Comment by daira** [comment]
I agree about those scoping directives.

This code is absolutely performance-critical; it's used for JoinSplit proving, and the speed-up from use of OpenMP is quite substantial — I haven't measured it recently but IIRC it makes the difference between JoinSplit time being tolerable or not on a typical fairly-recent CPU. The -O2 thing is a separate question but IMHO, we should only be using -O2 or higher on code that actually is performance-critical, not on the whole codebase.

The silently wrong results problem you mention is indeed nasty and I'm surprised that OpenMP users aren't up-in-arms about it. In our case it could cause a JoinSplit proof to be incorrect (and maybe cause uninitialized reads? not sure). I believe that we don't use OpenMP for proof *verification* (this needs to be checked), so it cannot cause us to accept an incorrect proof.

**Comment by solardiz** [comment]
Sorry for out-of-context comments, but:

On Tue, Oct 25, 2016 at 06:51:56PM -0700, Daira Hopwood wrote:
> I found no data races in any of the code containing ``#pragma omp`` or the ``MULTICORE`` macro.

With OpenMP, good practice is to always use default(none) along with explicit private(...) shared(...), so that by default no outer scope variables are visible in the parallel region's scope. This helps spot inadvertent races not only now, but also with future changes. (I always do this in JtR core tree, as well as in yescrypt; JtR jumbo is not always as careful, unfortunately.)

Also, why do we even go for use of threads there (is this code considered performance critical?) if we (IMHO wrongly) don't dare to use -O2 (opting for -O1 instead)? Looks like misguided paranoia to me. ;-)

A risk of OpenMP is that, at least as implemented in gcc's libgomp, it can silently produce wrong results if one of the threads dies (e.g., is OOM-killed on Linux with memory overcommit, which is something I've seen happen when stress-testing yescrypt). The parallel region may complete anyway, and the master thread goes on, but the computation is incomplete. There's no "exit code" from parallel regions - in security-critical code we'd have to invent our own indication that each thread has finished its portion of the computation (e.g., all iterations of a "for" loop actually reached end of block). I like OpenMP and I think when it's appropriate and is appropriately used it makes source code more readable than the code would be with explicit pthreads, but this behavior on error is really nasty.

**Comment by daira** [comment]
(I deleted the delayed duplicate comment by @solardiz .)

**Comment by daira** [comment]
I wrote:
> I believe that we don't use OpenMP for proof verification (this needs to be checked), so it cannot cause us to accept an incorrect proof.

[Indeed we do not.](https://github.com/zcash/libsnark/blob/master/src/algebra/curves/alt_bn128/alt_bn128_pairing.cpp)
