### ISSUE TITLE
Cryptographically sign Git commits

### ISSUE THREAD

**Issue by ghost** [zcash/zcash#1546]
Opening a new issue for this, as @bitcartel remarked that it is out of scope for #609.

As [previously mentioned](https://github.com/zcash/zcash/issues/609#issuecomment-247674745), here is an account explaining _why_ Git commits should be signed:
- https://mikegerwitz.com/papers/git-horror-story

and here are accounts of _how_ to sign Git commits:
- https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
- https://help.github.com/articles/signing-commits-using-gpg/

**Comment by daira** [comment]
I disagree that the article mentioned provides a good reason to sign *commits*.

We will be signing tags anyway. But we cannot have the original author of each commit sign it, because that interferes with rebasing. The overhead of having the original author re-sign it in the case of a rebase is too great even if it were always possible (which it isn't, because the original author isn't always available). If the person doing the rebasing signs it, on the other hand, then I don't see the point: that person can't vouch for the code in all cases. In practice we don't attribute blame to people for making commits that introduce security bugs, as the article seems to assume, anyway; it's much more complicated than that.

**Comment by sampablokuper** [comment]
> In practice we don't attribute blame to people for making commits that introduce security bugs, as the article seems to assume

The point about blame is secondary to the main thrust of the article. The main thrust is that for an attacker to be able to add a security hole undetected (in this case, by masquerading as a trusted developer) is a nightmarish scenario that projects should avoid at all costs.

For the innocent developer to then be wrongly blamed for introducing that security hole merely *adds* some secondary nightmarishness to the situation.

Even if you are certain that Zcash would *never, ever* blame a developer for that\*, the primary point still stands.

\* *And how can you be certain? Zcash's management or culture might change in the future, and become more accusatory.*

**Comment by daira** [comment]
I want to make sure that we only start using signed commits if doing so will actually improve security at reasonable cost. In order for it to improve security, there cannot be any unsigned commits (otherwise an attacker would just use one of those). Imposing the requirement that all commits are signed is adding significant development overhead that we shouldn't impose lightly.

**Comment by sampablokuper** [comment]
> I want to make sure that we only start using signed commits if doing so will actually improve security

Clearly, it would.

> at reasonable cost.

What constitutes "reasonable cost" is subjective, and also depends upon the context.

If Zcash were software that had little reason to be attacked (e.g. an application with no networked functionality, intended to process no data with monetary value, intended only for use by a tiny number of people), then perhaps the cost of signing commits would be excessive.

However, Zcash is the opposite of that. It is software for which a successful attack could be *extremely* valuable to everyone from nation states to organised criminals. If it ends up being as widely used as its founders desire, and for the applications they appear to desire (e.g. cryptographically auditable tax returns; a more secure and private alternative to Visa/Mastercard/AMEX/PayPal/etc), then it will become among the most prime targets for exploitation in the world.

> [Requiring] that all commits are signed is adding significant development overhead that we shouldn't impose lightly.

Indeed, but creating a new monetary system intended for massive uptake and scalability is also something that shouldn't be done lightly ;)

**Comment by nuttycom** [comment]
Our policy is that tags are required to be signed, but signing of individual commits is up to the discretion of the committer.
