### ISSUE TITLE
Remove zcraw* RPC methods

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1555]

**Comment by 5a1t** [comment]
I found the zcraw functions useful.

For example, with the new payment API it is difficult to send many-to-many txs.  This is useful for pools, for example, since they will have many coinbase txs and want to send one tx to many participants.  With z_sendmany, you supply an address as an input and:
-Inputs are selected for you, but only from that address.  Does not provide tight control over selected inputs, so fees are unpredictable.
-Does not permit you to use coinbase utxos ("Could not find any non-coinbase UTXOs to spend.") With zcrawjoinsplit gone, how is one supposed to wash generated coins easily?
-Change addresses are automatically used. While this is good for many cases, since z_sendmany requires an address as input, funds may end up fractured across many change addrs for miners that can't be used in z_sendmany as a single tx.

Assuming zcraw* functions were removed today, what would the correct process be for someone to:
-Collect many mined coinbase txs.
-Wash all mined coins to a transparent addr.
-Send entirety of an addr to multiple participants without dust

I can do this with zcraw* functions, but shouldn't be building on soon-to-be-deprecated functions.

**Comment by daira** [comment]
These are good arguments. I think we should make some improvements to z_sendmany (support for multiple input addresses and an explicit change address, in particular), before removing zcraw*.

**Comment by daira** [comment]
Note that z_sendmany does allow you to spend from coinbase UTXOs, but not if there are transparent outputs. (This is a consensus rule so not something you can bypass with zcraw*.)

**Comment by 5a1t** [comment]
I'll have to try that, I'm currently including both a z_addr and a t_addr (same t_addr that contains the coinbase UTXOs).  The code looks like this is a possible way to bypass change address generation and fee calculation, as fees are removed from the t_addr send if it is the same address you are sending from. No change address is generated since the entire balance is sent, and the required fees are removed from the looped funds.

**Comment by tromer** [comment]
RPC for transactions with multiple input addresses is also discussed in  #1785 and #1811.

**Comment by daira** [comment]
Assigning to me to file a new ticket to improve ``z_sendmany``.

**Comment by str4d** [comment]
In the intervening time, we've added `z_shieldcoinbase` and `z_mergetoaddress`. The `zcraw*` methods were disabled by default in 5.0.0, and will be removed in 5.4.0.
