### ISSUE TITLE
Reduce depth of merkle tree over commitments.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#16]

**Comment by daira** [comment]
This ticket should be deciding on the maximum number of coins we need, rather than directly the depth. The resulting depth is log_arity(max_coins) where the arity is determined by the input size of the hash. The arity for SHA-256-compress is 2, but it may be larger if we implement #40.

**Comment by ebfull** [comment]
I think we should settle on a depth soon, and I think we should pick a small one. A few years of maximum blockchain capacity, then overestimate from there? We should have a performance hardfork by then.

**Comment by matthewdgreen** [comment]
Early on in the process we had discussed the idea of windowing, i.e. supporting multiple trees simultaneously in an overlapping fashion. I'm not suggesting we implement this now, but let's assume a hardfork in the not-too-distant future. Are there small changes we could make now that would make it less painful to support this in later versions?

**Comment by ebfull** [comment]
My recommendation is a depth 32 tree. Nice and round, isn't it?

Let's pretend a pour can be expressed in 500 bytes, via *magic*. This means in a 2MB block we can fit 4000 of them optimistically. This is 1600 pours per minute with a 2.5 minute block size, or `8409600000` pours in ten years, requiring a depth 32 tree.

You *could* do a more rigorous analysis, but I've picked these constants so that we have plenty of buffer room to update the protocol, change the hash function we use, increase the depth by a huge amount, etc.

We don't need to pick a depth based on empirical evidence yet; we may never have to.

**Comment by ebfull** [comment]
If a depth-32 tree is exhausted, our nullifier set will be at least 274GB, which is unsustainable.

**Comment by daira** [comment]
+1 for depth 32, provisionally.

**Comment by daira** [comment]
@imichaelmiers wrote:
> Early on in the process we had discussed the idea of windowing, i.e. supporting multiple trees simultaneously in an overlapping fashion. I'm not suggesting we implement this now, but let's assume a hardfork in the not-too-distant future. Are there small changes we could make now that would make it less painful to support this in later versions?

Yes, I believe #790 would help. I've opened #829 to explore the design space for this.

**Comment by daira** [comment]
We chose depth 29; the discussion of why is on #994.
