### ISSUE TITLE
> 50% block rejections on RC2 testnet

### ISSUE THREAD

**Issue by timolson** [zcash/zcash#1652]
We are getting more than 50% of our blocks on RC2 testnet rejected.  If we point to RC1 then everything looks good.

The response from `submitblock` is `{"result":"inconclusive","error":null,"id":1}`.  We have verified that we are using the correct `previousblockhash` and there is a time gap between when we submit and when the next "real" block is found, so I do not think it's a problem with stales.

We do use `getblocktemplate` with `coinbasevalue` and `getblocksubsidy`, so there are some related PR's and issues:
https://github.com/zcash/zcash/pull/1602
https://github.com/zcash/zcash/issues/1424

Here's an example `submitblock` which resulted in an `inconclusive` response and which was rejected by the network: http://pastebin.com/FSe2AkTa

We have enabled more debugging on zcashd to try to track this down.  We are also trying to set up a private RC2 testnet to debug.

**Comment by timolson** [comment]
After some debugging with @str4d we think this is a problem with our miner.  Still a mystery which RC1 -> RC2 is different.  We will leave this open for now and investigate further.

**Comment by artlav** [comment]
I have encountered this before.
The "inconcluseve" usually means that the block got too old by the time you mined it.
That is, someone else mined this block, but your solver/pool was not made aware of the fact soon enough.
I solved this by adding a override command to the solvers, that force them to terminate current solution and start a new one.

**Comment by timolson** [comment]
We ran against public testnet last night.  We submitted a block which zcashd reported as "inconclusive", then zcashd no longer updated the blockheight (at least via GBT) and kept reporting block 2680 from GBT, causing our miner to mine stale blocks from then onwards.  Here is a log of our communication with zcashd: http://pastebin.com/D5W6n0JJ
I'll get our log from zcashd as soon as Salt is awake…

**Comment by daira** [comment]
Could this be related to #1593? Does it clear itself if you restart the node?

**Comment by timolson** [comment]
Not sure… our current workaround is to timeout the GBT request and try again.  Zcashd seems responsive if we just try the request again even without restarting zcashd.

**Comment by daira** [comment]
That sounds like a problem with the async request queue. Alternatively, the GBT request could be failing without marking itself as having failed.

**Comment by daira** [comment]
[Deleted comment with wrong hypothesis; getblocktemplate is not an async call.]

**Comment by str4d** [comment]
The issue is likely related to wallet code, as that is what was newly-communicated-with in RC2 (in order to switch from `coinbasevalue` to `coinbasetxn`). It's possible there is a lock contention issue.

**Comment by str4d** [comment]
The logs linked in https://github.com/zcash/zcash/issues/1652#issuecomment-256623018 appear to show the following behaviour:

- Intially `longpoll` works as-intended: a few minutes afterwards, a block template is received.
- During this time, `submitblock` successfully accepts blocks
- At some point, a `longpoll` call is made that hangs.
- During the hang, `submitblock` returns `inconclusive`.

`getblocktemplate` initially locks on `cs_main`, but during `longpoll` it releases the lock and then waits until either the tip changes, or new transactions appear. Then it tries to retake the `cs_main` lock. My guess is that somewhere in the `longpoll` code is something that is locking on `cs_wallet` and not releasing before trying to take `cs_main`, while the regular block chain updates lock on `cs_main` and then try to take `cs_wallet` (e.g. in `IncrementNoteWitnesses`).

We would need debug logs of `zcashd` to track this issue further.

**Comment by str4d** [comment]
Unconfirmed, but I believe that the temporary fix for anyone running into this issue is to revert the following 4 lines of diff:

https://github.com/zcash/zcash/pull/1602/files#diff-c2c990fee1c3381462640e80ae7db0d0L543

```diff
-        CScript scriptDummy = CScript() << OP_TRUE;
-        pblocktemplate = CreateNewBlock(scriptDummy);
+        CReserveKey reservekey(pwalletMain);
+        pblocktemplate = CreateNewBlockWithKey(reservekey);
```

and then build the coinbase transaction manually.

**Comment by str4d** [comment]
We have decided to push this out past launch, but keep it prioritised for afterwards.

**Comment by timolson** [comment]
We have more evidence from mainnet now 1.0.0.  We have two zcashd's running and two approaches with the miners.  One miner is using GBT longpolling against zcashd-A and it suffers from stales.  zcashd-A will hang on the longpoll and also not recognize new blocks even though it's peered with zcashd-B.  The other miners are running through my proxy which is doing 5-second quick polls against zcashd-B.  They are working fine and getting the new blocks as expected.

We have a third zcashd-C built with the changes suggested by @str4d but we haven't tested that yet.

**Comment by daira** [comment]
@timolson Can you test those changes soon? We are planning a 1.0.1 maintenance release and it would be useful to have more evidence of whether that change fixes the problem.

**Comment by timolson** [comment]
Yes, we have a separate build now, and we'll divert a few miners to it tonight.

**Comment by 5a1t** [comment]
@str4d It looks like the code you mentioned in rpcmining.cpp was modified in v1.0.0.  Would you like us to use rc2 and revert this section, or supply a new patch for us to try in sprout?

**Comment by str4d** [comment]
@5a1t here's the diff I'm proposing that you try:

```diff
diff --git a/src/rpcmining.cpp b/src/rpcmining.cpp
index 3759bd0..8096894 100644
--- a/src/rpcmining.cpp
+++ b/src/rpcmining.cpp
@@ -553,8 +553,8 @@ Value getblocktemplate(const Array& params, bool fHelp)
             delete pblocktemplate;
             pblocktemplate = NULL;
         }
-        CReserveKey reservekey(pwalletMain);
-        pblocktemplate = CreateNewBlockWithKey(reservekey);
+        CScript scriptDummy = CScript() << OP_TRUE;
+        pblocktemplate = CreateNewBlock(scriptDummy);
         if (!pblocktemplate)
             throw JSONRPCError(RPC_OUT_OF_MEMORY, "Out of memory");
 
```

If this works, it means that my supposition about it being a locking issue is likely valid.

Note to anyone else: **DO NOT** use this diff if you are not building the coinbase transaction yourself, because this **WILL** result in `getblocktemplate` providing a coinbase transaction that is useless to you!

**Comment by 5a1t** [comment]
@str4d Thank you.  Unfortunately this did not fix the issue.  We did some additional testing today and found the following results by tracking getbestblockhash and comparing it to the reported getblocktemplate previous block hash on the longpoll connection:
-No consistent time for block refresh.  When problematic, times until refresh ranged from 4 to 8 minutes.
-No pattern in blocks.  Sometimes it seemed like the longpoll connection would be updated on every other block, but we found this to not hold up.
-Polling getblocktemplate with zcash-cli always reports the proper, up to date information, even when longpoll connection is bad.

The issue was observed with both a direct longpoll connection from our mining software, and a longpoll proxy written in python (to reduce load on zcashd). v1.0.0 was used with the above patches on mainnet.  No other miners were connected.

**Comment by str4d** [comment]
@5a1t do you think it's possible that this is actually a result of #1680? It would make sense to me, given that longpoll would inherently rely on TCP keepalive. It would be interesting to know if 1.0.3 resolves this issue.

**Comment by sammy007** [comment]
Caught inconclusive tonight. I believe it's late block, but can zcash provide more relevant error message like `stale` in case if block is late?

```
2016/11/23 10:09:17 Valid share at height 15185 798902.4653/512877.8453 from XXX
2016/11/23 10:09:17 Block found at height 15185 by XXX [00000000a800ad674bb788c1b8b902ab807beb474d73825d9842da97992e83af]
2016/11/23 10:09:17 BLOCK SUBMIT ERROR: inconclusive <nil>
2016/11/23 10:09:17 Valid share at height 15185 2.2846/512877.8453 from XXX
2016/11/23 10:09:18 New block to mine on Main at height 15186 with 0 tx, 7.59350000 reward, 0.00000000 fees (37.089µs, 874.184µs)
```

Also it's prolly even good to accept it and propagate.

**Comment by str4d** [comment]
The stuck RPC issue will be continued in #1593. We will narrow the scope of this issue to the `inconclusive` RPC error.

Next steps for this issue:
- Understand the code paths that generate an `inconclusive` result.
- Rename or split off the `stale` state to improve usability of the RPC.
- Improve the documentation (or return message) for `inconclusive` (if it remains).

**Comment by str4d** [comment]
bitcoin/bitcoin#5106 is the origin of the `inconclusive` result. @luke-jr [pointed out](https://github.com/bitcoin/bitcoin/pull/5106#r19447158) that the reason for the inconclusiveness isn't something that can be determined at that point - I assume because the method of gathering the result data requires that the block get fully-processed, whereas in some instances that does not happen. Backstory in bitcoin/bitcoin#5083, which I'm still grokking to understand a next step.

Regardless, we shouldn't alter the return message `inconclusive` (because it should remain machine-parsable) but we can clarify its meaning a bit in the `submitblock` RPC help text.

**Comment by arcalinea** [comment]
So the next step is improving `submitblock` RPC help text?

**Comment by daira** [comment]
@timolsen Read https://github.com/bitcoin/bitcoin/issues/5083 to see why the "inconclusive" result might be returned. My impression is that it means that the node doesn't know whether the block is valid because it is not on the best chain (typically, validation is only done for blocks on the current best chain).
