### ISSUE TITLE
How do i see the mined blocks and coins?

### ISSUE THREAD

**Issue by DSofter** [zcash/zcash#1675]
I've successfully mined some blocks. Which command should i use to see the blocks i mined? And which command should i use to see the addresses of which the coins are mined to?

Thanks!

**Comment by DSofter** [comment]
I guess to clarify my question: how to i know which address(es) i'm mining to?

**Comment by amgadma** [comment]
/src/zcash-cli z_listaddresses?

**Comment by daira** [comment]
``z_listaddresses`` won't show addresses you're mining to because those are t-addresses. ``listtransactions`` will show them (both blocks and addresses).

If this is a sufficient answer, please close this ticket.

**Comment by DSofter** [comment]
@daira appreciate your answer! This is what i saw:
![screenshot from 2016-10-28 11-51-44](https://cloud.githubusercontent.com/assets/1687829/19818559/1cf32298-9d05-11e6-9ef4-181e9e26c036.png)

It says i have received 57 blocks in the last 4 hours, but `listtransactions` gave me nothing. Is it a bug?

**Comment by daira** [comment]
That's the total number of blocks mined on the rc4 testnet in the last 4 hours, not the number of blocks you have mined. (It's less than expected probably because a lot of mining power will have left the rc4 testnet in order to mine on mainnet, and the difficulty hasn't had time to adjust downward.) It appears that you haven't mined any blocks, which is perfectly normal.

**Comment by DSofter** [comment]
that's very good to know! @daira i'll close the ticket.

**Comment by DSofter** [comment]
BTW @daira is  there a doc that has all the information about which command does what?
