### ISSUE TITLE
WARNING: abnormally high number of blocks generated

### ISSUE THREAD

**Issue by imkane** [zcash/zcash#1690]
When I run:
`root@z:~/zcash# ./src/zcash-cli getinfo`

I see:
> "errors" : "WARNING: abnormally high number of blocks generated, 455 blocks received in the last 4 hours (96 expected)"

Not sure what that means. Should I be concerned?

**Comment by daira** [comment]
No, this is not a serious cause for concern. The block time is currently shorter than the target time of 2.5 minutes, because the difficulty adjustment algorithm has taken time to adjust to the high hash rate at launch. We expected this to happen, and it was part of the motivation for mining slow start, although the effect is slightly stronger than we anticipated because of the huge initial interest in mining. As I write this the block time average is at about 110 seconds, so it's getting towards the 150-second target.

Note that the diffculty adjustment has to be stable under normal network conditions, and this is actually a higher priority than adapting immediately to the launch difficulty. I estimate that the excess blocks mined at launch will only reduce the slow-start period by about 2 days or so.
