### ISSUE TITLE
fetch-params.sh missing from gitian builds

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1728]
This was mentioned during launch; I don't remember any details.

**Comment by ageis** [comment]
Partial ACK. Thanks for taking care of this! @str4d, another refinement that we should make is to make it so that `build-debian-package.sh` works with the paths of the binaries extracted from the Gitian release tarball. Presently, I have to extract the Gitian release tarball and move them into `/src` (as if I was building Zcash in a regular source tree) for the Debian package script to work.
