### ISSUE TITLE
Add backwards compatibility to OpenSSL 1.0.0

### ISSUE THREAD

**Issue by daniel-lucio** [zcash/zcash#1729]
As I have seen before, ECDSA_SIG_set0 is a exclusive function of OpenSSL 1.1.  

Please add compatibility with older 1.0.0 series. Reason is very simple. OpenSSL is a very complex package, Linux distributions deal perfectly with OpenSSL bugs and updates. Thats why shared .so libraries exists, and thats why we link against those.

By using own OpenSSL you are opening a window to have a vulnerable software, not because the OpenSSL wont fixt it, it is because users will need not to forget to compile manually to get the patch.

So please think about it.

I was building RPMs for Mageia and later CentOS, and I got stuck on this (yes, I have all done the RPM's for all dependencies, including libsnark RPM). 

Adding this support will allow me to give RPM's that will benefit all users.

**Comment by daira** [comment]
I think it's exceptionally unlikely that we will do this. It would create a fork risk from differences in behaviour between the OpenSSL versions. Users won't forget to compile the right version manually because the depends system does that for them. It's a package developer's responsibility to make sure that the provided OpenSSL is the same version that would have been compiled when not using a package.

In any case, we want to get rid of OpenSSL entirely, and I think that's a better use of engineering resources.

**Comment by daira** [comment]
Think of it this way: the number of possible behaviours when multiple OpenSSL versions are allowed is the product of the number of Zcash versions and the number of allowed OpenSSL versions -- as opposed to just the number of Zcash versions when each one requires a fixed OpenSSL. That's asymptotically more complicated to reason about.

**Comment by radix42** [comment]
Also, older versions of openssl than that currently used by zcash just plain do not contain the features that zcash is using (I know this from building on non-linux platforms that can't use the depends system, and the things they can't find in the openssl 1.0.0 header files when trying to link against a system provided openssl 1.0.0 installation....just are not in that version)

**Comment by daniel-lucio** [comment]
In all the code, there is only one function, one line that is forcing the OpenSSL 1.1.

Good job making this harder be adopted

**Comment by daira** [comment]
See #145 for progress on removing the OpenSSL dependency.
