### ISSUE TITLE
transactions specify retrospectively which branch they are valid on

### ISSUE THREAD

**Issue by zookoatleastauthoritycom** [zcash/zcash#174]
Here is an idea to reduce the damage from competing blockchain-forks: each transaction is required to commit to a recent block:

Third bullet point on:

https://en.bitcoin.it/wiki/User:Gmaxwell/alt_ideas
- Transaction block commitments. Each transaction (or signature?) should contain a block index and 32 (?) least significant bits of the block hash. The transaction's fees are only valid (or only their full value?) if they are mined in a chain they agree with. This would let people making bitcoin transactions 'vote with their wallets' on the identity of the chain they consider important. This isn't a viable POW replacement, but would greatly reduce the economic benefit of mining moderate depth forks, esp as fees begin to dominate the block reward. "You don't get (all) of my fee payment if you are mining a chain I don't like!"
  - Nodes would typical checkpoint a few blocks in the past from their current height to avoid overstating their opinion unnecessarily.
  - Deep checkpoints could be automatically triggered by observing a critical mass of coins-day-destroyed confirming them— creating a PoS-ish system, though this is subject to the 'nothing at stake' problem of PoS, and is probably very dangerous. (e.g. isolation risk for newly bootsrapping nodes)

**Comment by daira** [comment]
Note that Zcash transactions containing Pours already refer to blocks: the anchor of at least the first Pour in a transaction must reference the final treestate of a (preferably recent) earlier block (see https://github.com/Electric-Coin-Company/zips/blob/daira-wip/protocol/protocol.pdf section 2.7). Note however that treestates only include the sequence of coin commitments, so the anchor wouldn't distinguish forks with the same coin commitments.

**Comment by daira** [comment]
Why the 32 least significant bits, rather than the full block hash?

**Comment by zookozcash** [comment]
Forget the idea of using only 32 bits. We'd definitely want full-sized hashes for this.

**Comment by rebroad** [comment]
@zookozcash Why do you think longer than 32bit hashes are going to be better?

**Comment by daira** [comment]
There's no good reason to restrict the hash length (the block size saving is negligible). It would be bad crypto design to do so without a reason.

**Comment by daira** [comment]
A 32-bit hash, in particular, would allow an adversary mining on a different chain to brute-force a block that matched the hash referenced from a given transaction.

**Comment by ebfull** [comment]
> If they had to repeat the proof-of-work for each trial then this would be too expensive an attack to be worthwhile

In particular I believe the argument is that it would always be more expensive than launching a 51% attack. But I agree, that keyspace is just not large enough. Why play around?

**Comment by zookozcash** [comment]
I think this principle is Ferguson, Schneier, and Kohno's "Security must be a local property." principle. I guess we can call it the "Locally-Verifiable Security" principle.

**Comment by zookozcash** [comment]
Please read https://github.com/zcash/zcash/issues/1162 because I think people were mistakenly posting comments to that ticket which were intended for this ticket (i.e. all (?) of gojomo's comments on https://github.com/zcash/zcash/issues/1162#issuecomment-236465437). In https://github.com/zcash/zcash/issues/1162#issuecomment-237029557 I stated that I think the whole idea is probably a bad idea and that ticket should probably just be closed with "wontfix" or "nope" or whatever they call it on github.

**Comment by daira** [comment]
This is a similar proposal for Bitcoin: https://github.com/luke-jr/bips/blob/bip-noreplay/bip-noreplay.mediawiki

**Comment by zookozcash** [comment]
Here are some Bitcoiners trying to urgently figure out how to do this in case of a sudden blockchain split: https://bitcoin.stackexchange.com/questions/52210/what-is-the-best-way-to-prevent-replay-attacks-in-the-event-of-a-bitcoin-hard-fo

I hope we have a solid solution to this well-integrated long before we face a blockchain split.

**Comment by daira** [comment]
I want to do this before or at the first hard-fork we do on mainnet.

**Comment by nathan-at-least** [comment]
This could be one way to ensure we do a bilateral hardfork for HF0.

**Comment by str4d** [comment]
I paired with @daira on this, to go over a proposal I've been mulling over. Here's a rough summary.

For Network Upgrade 0, we need (among other things) transaction-level replay prevention (this issue, and possibly #1162). This could be done in a variety of ways / consensus rules, such as specifying a recent block (proposed above), or using `SIGHASH_FORKID` as proposed in #2584. The latter basically takes the SegWit hashing format ([BIP 143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki)), and ORs a fork ID into the sighash type at the end (a crude form of domain separation for the outer double-SHA256 hash before the signature). By virtue of using that, it also "solves" the quadratic hashing problem, because that is what BIP 143 does.

IMHO a branch ID is easier to implement, and leaks less private information, than committing to a recent block hash.

Now, this does mean a non-trivial change to the signature hash format (especially as we aren't pulling in any of the rest of SegWit right now, and possibly not in future). But another thing we need to do for NU0 is modify the signature hash (and txid hash) to be extensible with future transaction data (Sapling in the initial case). So, if we are modifying the sighash algorithm already, we should just fix quadratic hashing at the same time. And given that we would be modifying the BIP 143-style sighash algorithm anyway, we should just use BLAKE2s with a personalisation instead of SIGHASH_FORKID and an outer double-SHA256, because that has better security properties and is more obviously domain separation.

We could also do other things we've been thinking about, like making the internals a Merkle tree (to enable more efficient circuit proofs over parts of a transaction), which is partly getting into #2071 territory (but doesn't actually require redesigning the transaction format, just knowing how the existing data will be hashed together in an extensible Merkle tree). It's not strictly required for NU0 however, and could easily be defined to be out of scope. I raise it, however, because there's a trade-off between adding complexity now (which might not be more complex than what we'd be adding in already), vs. making another sighash change in future (this being a reason I want to include network upgrade awareness in the NU0 change, so we can easily account for transaction format changes in Sapling, Bamboo, etc.).

**Comment by nathan-at-least** [comment]
After more discussion between @daira, @str4d, and myself, we are converging on something similar to @str4d's proposal without the merkle tree part. So the proposal is similar to SIGHASH_FORKID except we'd like to use `blake2` (`-b` or `-s` depends on hardware wallet considerations) where the forkid is the `blake2` personalization field (which is designed specifically for this kind of domain separation).

Also, we want to make this a feature goal for Network Upgrade 0 (formerly "HF0") to resolve the outstanding quadratic signature validation performance issue.

**Comment by nathan-at-least** [comment]
We're planning to *exclude* this from Network Upgrade 0. In a conversation with @daira, @hughkhan, @str4d, and I, we thought this ticket had these motivations:

- Replay protection in the case of a chain split. As an alternative we're doing #2584.
- Enabling consensus rules around the creation time of transactions. We discussed this and rejected it from NU0.
- Protocols or applications which depend on proving transactions were created after a given time.
- Incentive protection against reorgs. We already have this somewhat due to the presence of JoinSplit anchors and any transactions that depend on them downstream.

**Comment by daira** [comment]
As far as I can see, #2584 completely obviates this.
