### ISSUE TITLE
Does a GPU pool miner count as a node?

### ISSUE THREAD

**Issue by DSofter** [zcash/zcash#1775]
I'm sorry for posting this question here but I feel like I'm more likely to get a better answer here than in the forum. Basically what i have found now is that i have zero motivation to run a zcash node: I've run it for days with miner and got nothing. Running a GPU pool miner would give me $1 back each day and I have the hope to see ZEC price go up. 

Is zcash designed in a way that anyone can support it by running a node and benefit from it?

A related question would be: does a GPU pool miner count as a node? I figured this would be the best place to get an official answer.

Thanks!

**Comment by ebfull** [comment]
This would be a great question for the [forum](https://forum.z.cash/), this bug tracker is mostly for software issues.

If you run a node, you support the network, but you won't benefit financially from it. If you mine, you may benefit from it depending on how effective of a miner you are, or if you're exceptionally lucky. Pools usually run nodes on the network just like solo miners do, though sometimes they cut corners and don't run the correct software, and because they get large there is a centralization risk. I encourage people to mine at smaller pools!

**Comment by DSofter** [comment]
@ebfull I appreciate your patience and answer! I'll post it in the forum as well. But i figured the forum could be very noisy.
