### ISSUE TITLE
Swapping ecdsa for mss?

### ISSUE THREAD

**Issue by sidhujag** [zcash/zcash#1789]
https://en.wikipedia.org/wiki/Merkle_signature_scheme

Cmss20 can be 10x faster signing and is quantum resistant over bitcoins ecdsa.. is it somethinf to consider at the early stages of zcash to implement something like this?

**Comment by sidhujag** [comment]
Since it would be quantum resistant you arent faced with the inconvenient workaround of  using only one time use addresses

**Comment by daira** [comment]
A one-time signature algorithm works fine for JoinSplit signatures.

However, the transparent script signing inherited from Bitcoin requires stateless signatures, because there's no reliable way to keep track of the current public key index across copying of wallets, restore from backup, etc. (Cmss20 is not stateless; it allows forgery if a private key index is ever reused.)

Current stateless hash-based signature schemes like SPHINCS are probably efficient enough for this application, but the signature size is too large. [Declaration of interest: I'm a co-designer of SPHINCS.]

**Comment by daira** [comment]
Also, use of one-time addresses in Bitcoin is primarily for privacy (to the extent it can be achieved) and possibly to mitigate key compromise; I'm not sure what you meant by relating that to quantum resistance.
