### ISSUE TITLE
Recoverable brain wallet.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#18]
Needs to track all information needed to generate a Pour transaction.

**Edit 2015-08-24** We decided that #31 is a duplicate of this ticket.

**Edit 2017-01-24** This ticket means different things to different people and thus needs to be split out into specific tickets:

* #2038 - feature to recover everything important from a static secret seed.
* #2039 - mnemonic entropy encoding (a la BIP39).
* #2040 - ~"Allow users to pick their own weak passwords for deterministic secret seeds. (strawman)"~

**Comment by zookozcash** [comment]
Related: https://lists.zca.sh/pipermail/zcash-dev/2016-February/000064.html

But, I've decided that Zcash-product-1.0 will *not* come with a brain-wallet, for two reasons:

1. It is easy for users to use them unsafely and lose money. (e.g. http://eprint.iacr.org/2016/103)

2. I don't feel that the added value is up to the added engineering costs of supporting it. (This is a judgment call that others could reasonably disagree about. I know that Matt, for one, really values a brain wallet.)

3. If we ship Zcash-product-1.0 without a brain-wallet, users can layer a brain-wallet on top of it by encrypting the spending-authority with a memorized passphrase and publishing/storing the resulting ciphertext somewhere very safe against loss.

**Comment by ebfull** [comment]
1. I disagree, we should prohibit brainwallets which are not canonical. The paper you link only shows passphrases which were created by users manually with low entropy. In our brainwallet scheme, the passphrase would not only be a large sequence of words, but also contain a checksum to avoid mistakes or to make "creating your own crappy passphrases" much harder.
2. I also disagree with this, in fact I think it would be *easier* to implement brainwallets than maintaining a keychain. One example where this already may come in handy: https://github.com/Electric-Coin-Company/zcash/issues/715#issuecomment-181978486
3. I agree with this, but we should learn from Bitcoin. When I helped write (the failed) BIP-39 I had a front-row seat to the terrible state of brainwallet conventions in their ecosystem. If we don't set conventions early on, we run the risk of incompatible implementations and thus wallet vendor lock-in from the get-go. (Which is exactly what has happened in Bitcoin-land.)

**Comment by daira** [comment]
@ebfull re:
> 2. I also disagree with this, in fact I think it would be easier to implement brainwallets than maintaining a keychain.

But presumably we would have to implement both, since some users would not want to or would be incapable of memorizing a sufficiently secure passphrase. Implementing both cannot have less engineering cost than implementing one.

**Comment by daira** [comment]
@ebfull re:
> If we don't set conventions early on, we run the risk of incompatible implementations and thus wallet vendor lock-in from the get-go. (Which is exactly what has happened in Bitcoin-land.)

This is a strong argument, but I don't think it overrides the other arguments against. Let's discuss this at the next engineering meeting.

**Comment by ebfull** [comment]
> But presumably we would have to implement both,

In our case, the keychain would just be a brainwallet on disk.

**Comment by daira** [comment]
Maybe this ticket/feature is misnamed. It sounds like what @ebfull is referring to is a deterministic wallet, i.e. one in which all addresses can be generated deterministically from an initial generator key. The ability to represent the generator key as a phrase (which is not a bad idea in itself, but see the point below about forward secrecy) is almost incidental to this, as long as we are requiring it to be randomly generated and not making any compromises in its entropy relative to what we would have chosen otherwise.

"Brain wallet" is an awful name for this because it carries the implication that users should be able to memorise the phrase representation of the generator key. Perhaps some users would be able to do that, but from what I've observed about the distribution of people's reliable-memorisation abilities, we should absolutely not depend on that or expect it of more than a minuscule proportion of users. Remembering cryptographically secure keys might make a good party trick at certain parties, but it is not credible as a user interface. (Note that the key derivation cannot have any input other than the generator key, for it to be a fully deterministic wallet.)

*If* we implement a deterministic wallet, we should recommend that generator keys are printed out or written down (and we should provide a way for a user to reenter the phrase representation to check that they transcribed it correctly; in fact we might want to make that mandatory).

**However**, I also consider it to be a requirement to support:
* forward unspendability: there are no secrets that I have to maintain forever in order to prevent an attacker spending my funds if those secrets are compromised. Ideally, there are no secrets that I have to maintain for more than a known bounded length of time;
* forward transaction view secrecy: there are no secrets that I have to maintain forever in order to prevent an attacker from viewing my incoming or outgoing transaction metadata if those secrets are compromised. Again, ideally there are no secrets that I have to maintain for more than a known bounded length of time. (This could be related to the time I'm legally obligated to keep financial records, say, or perhaps just to the time for which it's convenient for me to keep the most recent records online.)

Forward secrecy doesn't preclude deterministic wallets, but it does preclude "flat" derivation schemes (i.e. schemes in which all keys are derived directly from the generator key), and it requires that the generator key evolve over time. (So, any backup of the phrase representation should be regularly updated over time, and earlier copies destroyed.) Regularly creating new wallets manually is not a good implementation of this; it should be automatic and routine.

[Sorry for the wall of text.]

**Comment by zookozcash** [comment]
Regarding brainwallet per se, here's medua coverage of that recent paper: http://arstechnica.com/security/2016/02/password-cracking-attacks-on-bitcoin-wallets-net-103000/

**Comment by ebfull** [comment]
I am happy with this ticket being "not in 1.0," because we (or wallets that other people make for zcash) can support brain wallets, especially if we support deterministic wallets. I am only concerned about standards and conventions.

Also, as I mentioned before, "The paper you link only shows passphrases which were created by users manually with low entropy." People were making brainwallets with tools that allowed them to use any arbitrary passphrase they wanted. I think there was a website that allowed people to do this. We don't have to allow users to select an arbitrary passphrase.

**Comment by daira** [comment]
I'm mainly concerned with avoiding making design decisions that would paint us into a corner and prevent us from supporting wallets that are *both* deterministic and forward-secure (i.e. forward-unspendable and -confidential).  This means that we have to consider forward security when designing every other feature that has a possible interaction with it.

**Comment by ryancdotorg** [comment]
If you do anything on this, I urge you to provide randomly generated mnemonics, and implement it in such a way that it's difficult for anyone to make up their own. Including an extra word or two as checksum, for example.

**Comment by ebfull** [comment]
There is already a standard for mnemonics for passphrases which meets that goal: https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039.mediawiki

Lots of people (myself included) use this for their cryptocurrencies, including Zcash! It's a well-thought-out and well-supported standard.

**Comment by nathan-at-least** [comment]
I'm on the hook to split this up into distinct tickets. I started by adding #2038 to split out stateless recovery.

**Comment by nathan-at-least** [comment]
I'm closing this ticket because I believe the three breakout tickets in the updated description cover the main conflated proposals in this thread. If I missed something, let me know and I can add more sub-tickets.
