### ISSUE TITLE
Add OS X and Solaris 11 support to fetch-params.sh

### ISSUE THREAD

**Issue by noloader** [zcash/zcash#1830]
Sorry about the copy/paste. I just learned GitHub does not support `diff` filetype.

```
$ git diff > fetch-params.sh.diff
$ cat fetch-params.sh.diff 
diff --git a/zcutil/fetch-params.sh b/zcutil/fetch-params.sh
index ac5327b..e176af9 100755
--- a/zcutil/fetch-params.sh
+++ b/zcutil/fetch-params.sh
@@ -1,8 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 set -eu
 
 PARAMS_DIR="$HOME/.zcash-params"
+LOCKFILE="/tmp/fetch_params.lock"
 
 SPROUT_PKEY_NAME='sprout-proving.key'
 SPROUT_VKEY_NAME='sprout-verifying.key'
@@ -12,6 +13,9 @@ SPROUT_VKEY_URL="https://z.cash/downloads/$SPROUT_VKEY_NAME"
 SHA256CMD="$(command -v sha256sum || echo shasum)"
 SHA256ARGS="$(command -v sha256sum >/dev/null || echo '-a 256')"
 
+IS_DARWIN=$(uname -s | grep -i -c darwin) || true
+IS_SOLARIS=$(uname -s | grep -i -c sunos) || true
+
 function fetch_params {
     local url="$1"
     local output="$2"
@@ -45,13 +49,19 @@ EOF
 
 # Use flock to prevent parallel execution.
 function lock() {
-    local lockfile=/tmp/fetch_params.lock
-    # create lock file
-    eval "exec 200>/$lockfile"
-    # acquire the lock
-    flock -n 200 \
-        && return 0 \
-        || return 1
+    if [[ ("$IS_SOLARIS" -ne "0" || "$IS_DARWIN" -ne "0") ]]; then
+        # http://unix.stackexchange.com/a/13025
+        mkdir -p "$LOCKFILE" \
+            && return 0 \
+            || return 1
+    else
+        # create lock file
+        eval "exec 200>/$LOCKFILE"
+        # acquire the lock
+        flock -n 200 \
+           && return 0 \
+           || return 1
+    fi
 }
 
 function exit_locked_error {
@@ -105,5 +115,11 @@ EOF
 }
 
 main
-rm -f /tmp/fetch_params.lock
+
+if [[ ("$IS_SOLARIS" -ne "0" || "$IS_DARWIN" -ne "0") ]]; then
+    rm -rf "$LOCKFILE"
+else
+    rm -rf "$LOCKFILE"
+fi
+
 exit 0
```

**Comment by buzztiaan** [comment]
whats the point? does the wallet compile without SSE2 yet?

**Comment by noloader** [comment]
@buzztiaan,

>whats the point?

Well, the fourth step listed in the process at [Zcash 1.0 "Sprout" Guide](https://github.com/zcash/zcash/wiki/1.0-User-Guide) tells us to do it. Is it no longer required?

> does the wallet compile without SSE2 yet?

I'm not sure about this question. I have not gotten that far into the process.

**Comment by solardiz** [comment]
BTW, this is a security hole either way, right?

    local lockfile=/tmp/fetch_params.lock
    eval "exec 200>/$lockfile"

    LOCKFILE="/tmp/fetch_params.lock"
    eval "exec 200>/$LOCKFILE"

It's not proper use of `/tmp`, and a (sym)link attack by another local user can result in the user's file (any of the attacker's choice) being clobbered here. Introduced in 2e113f6b9d68ccba73333fc70c43157c6c0ab8b2.

If we don't worry about mere local DoS against `fetch-params.sh` itself, then e.g. `ln -s` or `mkdir` can be used (thus, creating a "lock dangling symlink" or "lock directory" instead of a "lock file") with its exit code checked. The drawback is that this will make stale locks possible, and the script would need to catch signals and remove the lock in there to reduce such occurrences. The current use of the `flock` utility avoids that, but OTOH, besides the issue above, the dependency on `flock` is probably unacceptable.

BTW, I see that the man page on `flock` uses a similar example, but with `/var/lock` rather than `/tmp`, and this makes for a lot of difference. Here, we want to allow builds as any user, making this approach unsuitable.

That said, if we don't need locking against other users - and we probably don't since the download is within the user's home directory - we can and should place the lock file/link/directory (whatever we choose) inside the user's home directory as well (near the file being downloaded).

**Comment by solardiz** [comment]
IOW, instead of the Darwin and Solaris checks here, we should fix the broken and non-portable code to be non-broken and portable.

**Comment by noloader** [comment]
@solardiz,

Yeah, I was kind of wondering about the potential race in `/tmp`, too. Sorry about not flagging it for you guys.

**Comment by radix42** [comment]
For my Mac port, users have to install flock from brew, which is ok right now since everyone has to build from source, but as soon as I have a binary distribution, it becomes problematic, since I don't want binary-only users to have to install the whole brew package management system.

Over on Windows, where I have a port in progress, the open source, cross-platform flock that is distributed in brew doesn't work due to underlying differences in kernel and filesystem semantics, aside from in the Bash On Ubuntu On Windows subsystems, and not using that is the whole point of a native windows port.

**Comment by radix42** [comment]
@noloader Are you building successfully on Solaris, and if so what toolchain/compiler version?

I'm going to grab the above patch for the Mac port in my fork (also, are you building on Mac, too?), because as I mention above I currently have flock from brew (or otherwise built from the cross-platform version on github) as a dependency.

Thanks

**Comment by noloader** [comment]
@radix42,

> Are you building successfully on Solaris, and if so what toolchain/compiler version?

No. But as I encounter problems I just clear them. To date the issues are low hanging fruit, like assuming `$MAKE` is always `make` instead of `gmake`.

As I got deeper into the build I found Solaris needed the following:

    solaris:zcash$ PATH="/usr/gnu/bin:$PATH" ./zcutil/build.sh -j 4

I'm now dying at:

```
$ PATH="/usr/gnu/bin:$PATH" ./zcutil/build.sh -j 4
...
Preprocessing libsodium...
mkdir -p /export/home/jwalton/zcash/depends/work/build/x86_64-unknown-linux-gnu/
libsodium/1.0.11-48c3ad464f3 /export/home/jwalton/zcash/depends/work/build/x86_6
4-unknown-linux-gnu/libsodium/1.0.11-48c3ad464f3/.patches-48c3ad464f3
cd /export/home/jwalton/zcash/depends/work/build/x86_64-unknown-linux-gnu/libsod
ium/1.0.11-48c3ad464f3;   cd .; ./autogen.sh
libtool is required, but wasn't found on this system
```

`libtool` is there, I just ned to get it on-path:

```
$ find /usr -name 'libtool' 2>/dev/null
/usr/apr/1.5/build/amd64/libtool
/usr/apr/1.5/build/libtool
```

-----

> are you building on Mac, too?

Yes, I'm working through builds on OS X and BSD too. Its mostly in parallel because they mostly have the same workarounds due to closeness to Posix (and lack of GNU extensions). If I clear something on Solaris, I scp the change over to OS X and NetBSD and try it (and vice versa). Solaris tends to be the most unusual at times, so I try to start with it when porting.

On OS X I use MacPorts, but I don't think it will make a material difference as far as Flock or Brew is concerned. With a GCC compiler things should mostly just work. On OS X when using Clang, I expect the Integrated Assembler is going to cause the most trouble. It took us a couple of months to get decent native Clang support into another library with lots of hand tuned assembly language.

----

By the way, I am also interested seeing how an i686 port will go because of [x86_64-unknown-linux-gnu](https://forum.z.cash/t/why-is-x86-64-unknown-linux-gnu-hardwired-into-the-source-code/7862). i686 provides upto AVX and BMI just like its big x86_64 brother. I have not tried the i686 port yet.

-----

Since you are porting, do you want access to some of my testing machines? The two most interesting ones are a G5 running Solaris (dual Xeons), and an OS X 10.5 PowerMac (PPC cpu). If so, send over your SSH key to *noloader, gmail account*.

**Comment by radix42** [comment]
@noloader I completed a Mac port with brew a while ago, the current branch in my fork is at:
https://github.com/radix42/zcash/blob/v1.0.2-mac-gcc/README-mac.md

It needs a patched libsnark (I have a fork of that in my github, too, that my fork builds against in depends/packages/libsnark.mk); the issues is with a function that is not in the standard library on Mac in profiling.cpp. See the commit log for the commit referenced in libsnark.mk in my branch above.

i686 is currently a no-go, libsnark needs some work to support 32 bit architectures (there is a ticket in here somwhere which has a reference to the issue in libsnark's issue tracker or a mailing list)

I've worked a bit already with the FreeBSD ports team on getting zcash going over there, the ticket tracking that effort (which I'll have more to add to soon, hopefully) is at:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213930

Are the solaris or powermac's 64 bit? I'm so I'd take a crack at them, I'll email you.

I'm not even going to bring up my windows ports-in-progress in this ticket :-)

**Comment by noloader** [comment]
> I completed a Mac port with brew a while ago, the current branch in my fork is at:
https://github.com/radix42/zcash/blob/v1.0.2-mac-gcc/README-mac.md

Oh, that's great. I wonder why its not in Master. Does it need testing?

> Are the solaris or powermac's 64 bit? I'm so I'd take a crack at them, I'll email you.

Yes, both are 64-bit.

You are welcomed to use them for all your projects. I bought them to test a few libraries I regularly work with (Crypto++ and OpenSSL). Anyone who wants an account is welcomed to it. There's no sense in leave spare cycles laying around.

**Comment by radix42** [comment]
@noloader ah I see, as I emailed you, your build triplet in your libsodium error is a linux one, so the depends system isn't getting the right one (and you need hack that up in build.sh...my mac fork uses a modified version of it called build-mac.sh which autodetects the triplet for making zcash itself, but you need to add a new platform to the bitcoin derived depends system).

Oh, and libsnark only builds with gcc or clang no newer than 3.4, regardless of platform.

**Comment by radix42** [comment]
My mac port isn’t in the main Zcash repo because we had to do some violence to a few things that won’t shoe horn into it easily, not without a lot of platform  conditionals in a lot of places, and I don’t have the time/money to do that. Someone from the Ethereum project sent me a patchset that got me over the hump for the port to build, but it does a fair amount of violence to things in a few places, although some of them bits keeping it from being integrated upstream are getting dealt with one at a time. It’s been fairly widely tested now on Yosemite and newer OS X by nearly 100 users so far according to github stats.

**Comment by noloader** [comment]
@radix42,

Now open on [miniupnp](https://github.com/miniupnp/miniupnp) bug reporter: [Issue 216: Compiler or options invalid; UNIX 03 and POSIX.1-2001 applications](https://github.com/miniupnp/miniupnp/issues/216).

**Comment by radix42** [comment]
I had no trouble building MiniUPnP on windows with the msys2 distro of the mingw64 gcc toolchain, fyi...no idea about cygwin. I abandoned them a while ago because of the gui only package management. msys2 is the way to fly these days for 64-bit POSIX porting on Windows.

**Comment by kozyilmaz** [comment]
Just a reminder, OS X does not have flock and wget. I used a patched version of Zclassic's [fetch-params](https://github.com/kozyilmaz/zcash-apple/blob/master/zcash/patches/003-zcash-macos-zclassic-fetch.patch) to make it work on OS X

**Comment by radix42** [comment]
heh, yeah I wrote that initially :-)
@movrcx altered it further

**Comment by radix42** [comment]
A version that works on mac is in my fork, too

**Comment by daira** [comment]
This *may* be fixed.

**Comment by kozyilmaz** [comment]
This PR https://github.com/zcash/zcash/pull/2784 should address this

**Comment by mms710** [comment]
We just need someone to check to see that this is fixed.

**Comment by noloader** [comment]
I can provide remote access to an old MacBook with Xcode and Solaris 11.3 for testing software.

The old MacBook is a Core2 Duo. It runs OS X 10.10. It has Xcode 6 through 8.

If you want the access, then email me at *noloader, gmail*. Please send your `authorized_keys` file. Be sure it includes an RSA key.

**Comment by mms710** [comment]
Sorry the note was vague - we need someone at the Company to try to reproduce the issue on their machine to ensure it was fixed.

**Comment by daira** [comment]
We don't support Solaris, and fetch-params works for macOS.
