### ISSUE TITLE
Compile flags include "-fwrapv"

### ISSUE THREAD

**Issue by noloader** [zcash/zcash#1832]
`-fwrapv` is used by illegal programs to try and keep them from self destructing. I'm fairly certain its a bad idea for any component in the suite to depend on the flag. Also see [Ian Lance Taylor's Signed Overflow](http://www.airs.com/blog/archives/120). In other contexts use of `-fwrapv` generates a low-level security defect.

Its probably best in the long term to fix the program.

**Comment by solardiz** [comment]
There's no specific problem we're aware of that zcash's use of `-fwrapv` is trying to fix. It's just about staying on the safe side. "Defensive compiling", so to speak. It was not my decision to use a set of safer compiler options for building zcash, but I was the one to suggest inclusion of `-fwrapv` in particular. (Personally, I think that the decision to go with `-O1` may very well have been wrong, and not only for performance reasons, but `-fwrapv` and `-fno-strict-aliasing` are fine.)

There's no arguing that instances of signed integer overflow, once they become known, should be fixed in code regardless. A valid argument, though, is that they might be slightly more likely to go unnoticed when even test builds are using this option.

**Comment by solardiz** [comment]
> In other contexts use of -fwrapv generates a low-level security defect.

Can you explain what you mean by this?

**Comment by noloader** [comment]
@solardiz - It looks like `-fwrapv` may have been acting as suspenders to keep ccache's pants from falling down. Also see [Ccache Issue 155](https://github.com/ccache/ccache/issues/151).

**Comment by noloader** [comment]
>> In other contexts use of -fwrapv generates a low-level security defect.
>
> Can you explain what you mean by this?

Yes. When Acceptance Testing or Security Evaluation and Testing occurs, an external library or program using `-fwrapv` generates a security defect. Some make them blocking issues so they must be remediated.

**Comment by solardiz** [comment]
@noloader As I clarified to you via e-mail, and I feel I need to repeat for others here, I am not speaking on behalf of Zcash project. With respect to Zcash, I am just a community member, much like you. My use of "we" was a reference to the community, or the general public. Thus, it's up to someone else more closely involved with Zcash to decide on whether and what to do on your suggestions.

Personally, I think that basically this is a non-issue. You thought the use of `-fwrapv` was because of known bugs in the `zcash` tree or/and with intent to avoid fixing bugs, and that's not the case. In fact, the opposite is true: there's intent to fix bugs (including all instances of signed integer overflow, which is well understood to be undefined) _and_ to use "defensive compiling" nevertheless (in case any instances are missed, and in a large enough project, especially with use of third-party libraries, many inevitably will be).

The only real issue here is that with `-fwrapv` staying in the tree for a long time, bugs that creep in later, or that would be taken advantage of by future/different compiler versions, are more likely to stay undetected. For this reason, some of the testing builds may need to be done without that option (and without other "defensive compiling" options as well). If Zcash project doesn't intend to do that sort of testing builds, which unfortunately may very well be the case, then _that_ is a reason to possibly reconsider use of "defensive compiling" in general.

**Comment by noloader** [comment]
@solardiz,

My bad. The reply was simply the answer to the question:

>> In other contexts use of -fwrapv generates a low-level security defect.
>
> Can you explain what you mean by this?

The short answer to your question is *"some organizations have higher bars"*, and the use of `-fwrapv` is a red flag. They want the problems fixed and the flag removed.

Sorry it was not more clear. I was not attempting to get into a philosophical debate.

**Comment by solardiz** [comment]
@noloader I appreciated your answer and I think I had understood it as you intended. It's just that "they want the problems fixed and the flag removed" isn't necessarily better/safer than Zcash's "they know of no current problems, want to fix whatever problems they learn of, yet keep the flag for added safety". In fact, the very reason Zcash uses that flag is they want to be safer than those "merely known problems fixed and then we drive without seatbelts" projects. Sorry for the philosophical debate; my only intent is to get us on the same page, not to argue.

**Comment by noloader** [comment]
@solardiz,

But the flags the project is using speaks otherwise. First, it says *"don't tell me about optimizations taken due to signed overflow"* by omitting `-Wstrict-overflow` or `-Wstrict-overflow=2` (be careful of level 2); second, it covers it up by saying *"don't remove the code that has undefined behavior behavior and would be removed"* by using `-fwrapv`.

-----

We can also look at `--enable-hardening`. From `configure.ac` shown below, it looks like its only using:

* -Wformat and -Wformat-scurity
* -Wstack-protector or -Wstack-protector-all
* -D_FORTIFY_SOURCE=2 (breaks on Android, IIRC; needs -D_FORTIFY_SOURCE=1)
* -Wl,-z,now and -Wl,-z,relro
* -fPIE

it looks like a few recommended options and flags are missing, depending on their scurity posture. From [C-Based Toolchain Hardening](https://www.owasp.org/index.php/C-Based_Toolchain_Hardening#GCC.2FBinutils):

* -Wstrict-overflow 
* -Wformat=2 -Wformat-security
* -Wtrampolines 
* -Wl,-z,nodlopen and -Wl,-z,nodump 
* -Wl,-z,noexecstack and -Wl,-z,noexecheap (NX haps on PAX kernels like Gentoo)
* -Wreorder and maybe -Woverloaded-virtual  (for C++)
* -Wnon-virtual-dtor (for C++ code)

Windows is missing a handful of flags, too:

* /sdl 
* /GS 
* /SafSEH
* strict_gs_check 
* /d2guard4 with link /guard:cf (Control Flow Guard for VS2015)

I also believe the build system also fails to export `CFLAGS` and `CXXFAGS` once its sets them. That means build systems which try to honor `CFLAGS` and `CXXFAGS` may not pick them up. I can only say *may* because I have not audited all the dependencies.

I know where the dead bodies are buried with OpenSSL and some of Boost. I'm working on `miniupnp` at the moment (four issues found so far, the worse is the buffer overflow at https://github.com/miniupnp/miniupnp/issues/220).

-----

```
AC_ARG_ENABLE([hardening],
  [AS_HELP_STRING([--enable-hardening],
  [attempt to harden the resulting executables (default is yes)])],
  [use_hardening=$enableval],
  [use_hardening=yes])
```

And:

```
if test x$use_hardening != xno; then
  AX_CHECK_COMPILE_FLAG([-Wformat],[HARDENED_CXXFLAGS="$HARDENED_CXXFLAGS -Wformat"],[AC_MSG_ERROR(Cannot enable -Wformat)])
  AX_CHECK_COMPILE_FLAG([-Wformat-security],[HARDENED_CXXFLAGS="$HARDENED_CXXFLAGS -Wformat-security"],[AC_MSG_ERROR(Cannot enable -Wformat-security)],[-Wformat])
  AX_CHECK_COMPILE_FLAG([-Wstack-protector],[HARDENED_CXXFLAGS="$HARDENED_CXXFLAGS -Wstack-protector"],[AC_MSG_ERROR(Cannot enable -Wstack-protector)])
  AX_CHECK_COMPILE_FLAG([-fstack-protector-all],[HARDENED_CXXFLAGS="$HARDENED_CXXFLAGS -fstack-protector-all"],[AC_MSG_ERROR(Cannot enable -fstack-protector-all)])

  AX_CHECK_PREPROC_FLAG([-D_FORTIFY_SOURCE=2],[
    AX_CHECK_PREPROC_FLAG([-U_FORTIFY_SOURCE],[
      HARDENED_CPPFLAGS="$HARDENED_CPPFLAGS -U_FORTIFY_SOURCE"
    ],[AC_MSG_ERROR(Cannot enable -U_FORTIFY_SOURCE)])
    HARDENED_CPPFLAGS="$HARDENED_CPPFLAGS -D_FORTIFY_SOURCE=2"
  ],[AC_MSG_ERROR(Cannot enable -D_FORTIFY_SOURCE=2)])

  AX_CHECK_LINK_FLAG([[-Wl,-z,relro]], [HARDENED_LDFLAGS="$HARDENED_LDFLAGS -Wl,-z,relro"],[AC_MSG_ERROR(Cannot enable RELRO)])
  AX_CHECK_LINK_FLAG([[-Wl,-z,now]], [HARDENED_LDFLAGS="$HARDENED_LDFLAGS -Wl,-z,now"],[AC_MSG_ERROR(Cannot enable BIND_NOW)])

  if test x$TARGET_OS != xwindows; then
    # All windows code is PIC, forcing it on just adds useless compile warnings
    AX_CHECK_COMPILE_FLAG([-fPIE],[HARDENED_CXXFLAGS="$HARDENED_CXXFLAGS -fPIE"],[AC_MSG_ERROR(Cannot enable -fPIE)])
    AX_CHECK_LINK_FLAG([[-pie]], [HARDENED_LDFLAGS="$HARDENED_LDFLAGS -pie"],[AC_MSG_ERROR(Cannot enable -pie)])
  else
    # These are only available on Windows.
    AX_CHECK_LINK_FLAG([[-Wl,--dynamicbase]], [HARDENED_LDFLAGS="$HARDENED_LDFLAGS -Wl,--dynamicbase"],[AC_MSG_ERROR(Cannot enable --dynamicbase)])
    AX_CHECK_LINK_FLAG([[-Wl,--nxcompat]], [HARDENED_LDFLAGS="$HARDENED_LDFLAGS -Wl,--nxcompat"],[AC_MSG_ERROR(Cannot enable --nxcompat)])
  fi

  case $host in
    *mingw*)
       AC_CHECK_LIB([ssp],      [main],, AC_MSG_ERROR(lib missing))
    ;;
  esac

  CXXFLAGS="$CXXFLAGS $HARDENED_CXXFLAGS"
  CPPFLAGS="$CPPFLAGS $HARDENED_CPPFLAGS"
  LDFLAGS="$LDFLAGS $HARDENED_LDFLAGS"
  OBJCXXFLAGS="$CXXFLAGS"
fi
```

**Comment by solardiz** [comment]
@noloader Thank you, these are good suggestions inline with what @daira and @defuse were getting into this project a few months ago. IIRC, there was a specific GitHub issue about the hardening. It looks like you could take this from where they brought it so far and continue from there.

**Comment by noloader** [comment]
> It looks like you could take this from where they brought it so far and continue from there.

Yes, I'd be happy to help.

For what its worth, I wrote the OWASP article.

**Comment by daira** [comment]
`CONFIGURE_FLAGS=--enable-debug` now enables `-ftrapv` instead of `-fwrapv`. This is definitely the Right Thing for both debug and non-debug. It's also [consistent with the behaviour of Rust](https://rust-lang.github.io/rfcs/0560-integer-overflow.html).
