### ISSUE TITLE
Evaluate using a single globals.cpp to avoid C++ undefined behaviour

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1879]
From section 2 of https://medium.com/@g.andrew.stone/a-short-tour-of-bitcoin-core-4558744bf18b 

> The simplest example of the problem is the mutex locks used by CCriticalSection. These objects need to be constructed before and destructed after any other object that contains a CCriticalSection, yet CCriticalSection global variables are declared in many other modules (net.cpp, main.cpp, and rpcwallet.cpp to grab 3). So the C compiler cannot guarantee that the mutex is available before a CCriticalSection uses it.

> We first saw this problem as core dumps on the Mac platform. To solve the problem, we placed all dependent global variables in a dedicated file called “globals.cpp”. Since all dependent globals are now in a single “translation unit”, constructor and destructor order is well-defined. This is a common solution to this well-known problem.

Example of globals.cpp file:
https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/release/src/globals.cpp

**Comment by radix42** [comment]
As the maintainer of 2 downstream ports (with others in progress), I'd just like to give a big thumbs up to this idea

**Comment by daira** [comment]
Not only does this fix the unspecified initialisation order problem, it's also better software engineering. (Better still would be to eliminate any global mutable state, but let's improve things incrementally.)

**Comment by nathan-at-least** [comment]
Added this to the Security/Stability project in addition to Portabililty.

**Comment by radix42** [comment]
yes, if you have to do the wrong thing, at least do it correctly :-)

**Comment by syd0** [comment]
I'm having a look at this, and although having everything in a global file does solve the problem, I think it's a bit ugly to have all of this unrelated stuff living in a separate file, far away from where the code is actually used. It also makes it possible for people in other translation units to use those variables since they are no longer static.

How do you feel about a static accessor function like so instead:
```
static Foo &foo()
{
    static Foo *s_foo = new Foo();
    return *s_foo;
}
```

All of the callers in the file that used to look say `foo.bar()` will now have to say foo().bar() instead.

The nice thing about this is that this at least keeps these static objects in their own files. The downside is that their destructors don't get called on program exit, but usually that isn't an issue for globals like this. Note that C++11 guarantees that that the initialization of the static is thread-safe.

Global (non-static) variables that are meant to be shared would similarly be hidden behind an accessor.

Thoughts?

**Comment by daira** [comment]
I agree that it's ugly that the visibility becomes global.

However I think using accessors is likely to be too disruptive. Maybe we'll do something like that eventually, but I'd like a more incremental approach that just fixes the initialization order problem first, and results in a smaller diff.

I'm not a C++ expert and I don't know how to get the visibility right with least disruption. Any ideas?

**Comment by syd0** [comment]
Unfortunately the only way I know how to do this is either to use accessors or to put everything in the same translation unit. :-/ 

I can go ahead and add everything to a globals.cpp (perhaps I'll also enclose them in a globals namespace so that we at least have a bit of code-clarity win).

**Comment by daira** [comment]
Please hold fire for a bit to see if we can come up with a better solution.

**Comment by syd0** [comment]
Ok, standing by. I tried to think of various solutions but unfortunately they all involved changing the call-sites.

Just to be clear, the non-globals.cpp solution i'm suggesting is that I would replace declarations like this:
```
static boost::mutex dd_mutex;
...
{
    d_mutex.lock();
....
```

With:
```
DEFINE_STATIC_GLOBAL(boost::mutex, dd_mutex);
...
{
    d_mutex().lock();
...
```

So there will be a ton of code diffs, but they will be small and it's the kind of thing that will fail compile if we forget use the accessor somewhere. One downside here is that all of those diffs will make it harder to merge in code from bitcoin core, but I'm not sure how often that happens.

**Comment by nuttycom** [comment]
We might consider this approach if upstream Bitcoin adopts it, but otherwise it will make backports from upstream more difficult than they already are, so closing for now.
