### ISSUE TITLE
Large blocks detected causing spike in cpu load for full nodes

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1886]
User reports that their mining nodes sometimes have a very high CPU load.

For example, on blocks 12975 - 12985.

Nearly all those blocks have a 750Kb size.

- https://explorer.zcha.in/blocks/0000000015cbbff39a64f00f0e3d5b7cf29790d70b772162e16c28b5bad53f4d
- https://explorer.zcha.in/blocks/00000000bfa143b38cd2d88a8b89582e71aeb4478d95872bbd53f2c3c75fdef4
- https://explorer.zcha.in/blocks/000000009c22845021a2ff300986026b9530abd961c8ba90d95a7486a9dbe4a4
- https://explorer.zcha.in/blocks/000000010b39700d2c98ee212e423fb008f310c90cedbad3ddb7fc2b3eae0833
- https://explorer.zcha.in/blocks/00000000c95f0bc59f940106278692ea58b6b650b5f6280407b4adabf9fffdaf

User would like more information about the issue to plan node configuration.

**Comment by nathan-at-least** [comment]
I don't understand this last sentence:

> User would like more information about the issue to plan node configuration.

If users experience very high CPU load, but their systems always succeed in syncing, then this is a performance annoyance, but not a failure or blocker.

Dangerous situations which would elevate the issue to a blocker might be requiring a significant fraction of the 150s block target time, or otherwise inhibiting users from successfully syncing (or leading to systemic problems).

**Comment by sammy007** [comment]
I believe if large blocks causing very high CPU load on efficient hardware (pools using dedicated servers with Xeons usually) it can cause effective DoS if someone will decide to spam network.

**Comment by bitcartel** [comment]
Closing.  Miner created valid block.
