### ISSUE TITLE
Add RPC to remove local unmined transactions from mempool and unroll their effect on local wallet

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#1958]
A fresh transaction may be consistent with the blockchain but remain unmined for a very long time (e.g., because the transaction is too large for its fee, so it's treated as a rate-limited "free" transaction). In this case, the `zcashd` that generated the transaction will keep it in its mempool, and will keep its effect on the wallet balance. This means the funds stay in limbo, neither reaching their destination nor being spendable otherwise by the sender.

Currently, the only way to recover is to create a fresh wallet and import the secret key from the old wallet ~(which is buggy, #1941)~.

We should add an RPC interface for removing transactions from the mempool and their effect on the local wallet. (Both for individual transactions, and a complete mempool flush.)

Note that this does not guarantee cancellation of transactions that were already broadcast. If they're eventually mined, the effect on the wallet will be reinstated.

Also note that this makes it easier for users to mistakenly or maliciously broadcast double-spending transaction (by spending notes, then quickly using the new RPC to undo effects on local wallet and re-spending the same notes). But this is not a protocol change, and the same can be done by users today, using multiple wallets or by rolling back their `~/.zcash` directory.

(Related to #1821, which is about aborting async transactions _before_ they reach the mempool.)

**Comment by nathan-at-least** [comment]
One problem here is that if you wipe the transaction from the local mempool in order to generate a new transaction consuming some of the same inputs, other nodes may relay the first transaction back into your mempool, so there's a race condition there (and this is slightly different than the race condition for mining the two contending transactions).

This could work as expected for transactions which have not been relayed.

Note that transaction cancellation is a very frequently requested feature based on my searches, and it's also fairly at odds with the whole Bitcoin design. We'll have to think more about how to do this well.

**Comment by daira** [comment]
An alternative approach is to give transactions an expiration block height (#754), so that the wallet can automatically unroll them if they are not in the block chain by that height (plus a fudge factor to allow for reorgs). I think this would be more usable.

**Comment by daira** [comment]
See also #2482 (Support abandontransaction RPC call).

**Comment by nuttycom** [comment]
Transaction expiry is the correct solution here; due to the unreliability of removing anything from the mempool and the destruction of history involved in removing a transaction from the wallet we will not make this change.
