### ISSUE TITLE
Fix the rate-limit threshold problem that occurs with JoinSplits.

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#1969]
Transactions with fees that are too low, compared to their size, are considered "free", and the *total* size of such transactions is subject to rate limit of 15000 bytes/minute by miners (by the default; it can be overridden with `-limitfreerelay`).

Such "free" transactions, when exceeding the rate limit, will be rejected by mining nodes. Their `debug.log` (if suitably enabled) will show the following error:
```
ERROR: AcceptToMemoryPool: free transaction rejected by rate limiter
<txid> from peer=<...> was not accepted into the memory pool: rate limited free transaction
```

This error is not visible to the sending node, so from the user's perspective the transaction will just silently and inexplicably fail to be mined (see #1959). If they keep their node online, it will continue broadcasting the transaction, so it will eventually get mined, subject to the rate limit and luck.

When using the default parameters, a transaction is considered "free" if it larger than 10kB. That's easy surpassed.

The default transaction fee ought to be chosen large enough so the transaction is not considered "free" by miners using the default parameters. In particular, it should grow with the transaction size. 

Alternatively, disable the rate-limit DoS protection.

Note that transactions with too-low fees used to be simply rejected (#1851), but we added a kludge that exempts JoinSplits from this (9ddb6ad028ec5c89a3b00eb2c291243b914162d5). The kludge does not affect the rate-limiting code.

---

Code references:
`main.cpp`:
```
        // Continuously rate-limit free (really, very-low-fee) transactions
        // This mitigates 'penny-flooding' -- sending thousands of free transactions just to
        // be annoying or make others' transactions take longer to confirm.
        if (fLimitFree && nFees < ::minRelayTxFee.GetFee(nSize))
```

The minimum fee to not be considered "free" is 0.00001 ZEC/kB, calculated as
`nSatoshisPerK*nSize / 1000`      (`amount.cpp:20`)
where `nSatoshisPerK` is initialized to `DEFAULT_MIN_RELAY_TX_FEE`    (`main.cpp:7`3)
which is 1000 zatoshis    (`main.h:64`).

The default transaction fee is 10 times that (`ASYNC_RPC_OPERATION_DEFAULT_MINERS_FEE` in `asyncrpcoperation_sendmany.h`), hence suffices for 10kB.

**Comment by tromer** [comment]
Related to #398.

**Comment by bitcartel** [comment]
@tromer We could add a rule:

If a transaction contains a joinsplit and the fee attached to the transaction is >= ASYNC_RPC_OPERATION_DEFAULT_MINERS_FEE, the transaction is exluded from the rate limiter.

This means that a transaction with joinsplit(s) and an explicit fee of 0 (user wants it to be a free transaction) would hit the rate limit, thus helping to protect against shielded penny flooding (even though this is unlikely given the cost of generating a joinsplit).

**Comment by tromer** [comment]
Yes, we could add additional special cases for transactions that happen to have JoinSplits, but this distorts the economics around block space as an (eventually) scarce resource. Also note that the problem is not just with JoinSplits; in fact, we first noticed this problem with transactions whose size was dominated by t-address inputs.

So wouldn't it it be better to keep the fee-per-byte threshold a la Bitcoin, and choose the default fee to match?

**Comment by bitcartel** [comment]
@nathan Is the rate-limit exception for joinsplit transactions mentioned above a satisfactory solution for this ticket?

**Comment by bitcartel** [comment]
@nathan-at-least Is the rate-limit exception for joinsplit transactions mentioned above a satisfactory solution for this ticket?

**Comment by tromer** [comment]
With the rate-limit exception, a rogue node can DoS the network by broadcasting huge transactions (each containing single JoinSplit and many public outputs), without paying any fee.

I'd rather not rely on JoinSplit generation as a proof-of-work prevent such DoS...

**Comment by bitcartel** [comment]
@nathan-at-least How can we get this issue unstuck?

The rate-limit exception could be applied to only taddr->zaddr and zaddr->zaddr tx only to avoid the issue mentioned above by @tromer.

**Comment by bitcartel** [comment]
This ticket argues for simplifying fee policy: https://github.com/zcash/zcash/issues/1896

A roadblock to growing the transaction fee to match the transaction size is that we currently do not have a transaction builder which creates a preview of the transaction from which we can compute the actual fee to use, or to provide user feedback.

Note that even if we did, the user would assume that since the software has automatically computed a fee, the transaction will be mined promptly, but miners do not guarantee inclusion of transactions and fee competition means that the computed fee may be insufficient, which in turn confuses the user who expects the software to calculate an appropriate fee.  By placing fee selection in the hands of the user, fee policy is no longer centralized in the software.

**Comment by nathan-at-least** [comment]
Hm… My ideal would be for full-node wallets to choose competitive fees based on their mempool, according to a user knob adjusted between low-latency vs low-fee. (Note that we have a 'two bucket' roadmap for fee policy, which I will hunt down and crosslink here.)

With that behavior, I would then want to entirely remove the rate limiting layer, which I consider to be a hack trying to duct-tape over proper fee behavior (*).

So big picture we should consider at least four alternatives:

a. adding fee calculation based on mempool, then removing rate-limiting.
b. paying the minimum threshold to make txns 'non-free'.
c. adding some exception to rate-limiting for JS txns.
d. lowing the rate-limiting threshold so that the current JS txn fee is above the threshold, even for large transactions.

My preferences are: a first, cleanest / most correct / best network dynamics, d. easiest to do (if it is plausible), b, then c.

I assume a. is a fair amount of work (we should figure out how much), so the first thing we should do is investigate d.

To be specific about d, what if we take take the constant JS-txn fee (0.0001 ⓩ == 10000 zatoshi), divide by the largest txn size allowed by consensus (100kb ?), to arrive at 0.0001 zatoshi/byte or 0.1 zatoshi/kb.

Would that be feasible? We already are running into precision limitations here. What if we also bumped up the constant JS-txn fee by x10? At today's exchange rate, that would mean a default of around $0.03 per JS-txn. Then we would need to calculate how much it would cost to pass the threshold with txns that have the highest possible UTXO/nullifier cost.

(*) Some might argue that spam transactions are incurring a cost of UTXOs / nullifiers for all nodes, and so we need to protect the network against them. The problem here is that a single miner gets paid, while the entire network pays the UTXO/nullifier cost, and this is a fundamental economic flaw in Bitcoin and Zcash. 'Rate limiting' is still duct-tape over that flaw. (i.e. miners can always choose not to do the rate limiting, perhaps they are paid a fee out of band, etc… but the txns still carry large UTXO/nullifier growth; or a wealthy entity can pay large fees but still contribute to UTXO/nullifier growth.)

**Comment by daira** [comment]
I'm opposed to us increasing transaction fees to users essentially as a hack to work around the fact that upstream Bitcoin code doesn't handle transaction fees well.

**Comment by daira** [comment]
@bitcartel wrote:
> A roadblock to growing the transaction fee to match the transaction size is that we currently do not have a transaction builder which creates a preview of the transaction from which we can compute the actual fee to use, or to provide user feedback.

Relevant article: https://medium.com/@g.andrew.stone/optimizing-bitcoins-transaction-generation-code-92bd222bae85

**Comment by nathan-at-least** [comment]
Ok, I am persuaded by @daira's comment, but think about option c. in my comment. That means users still suffer fee behavior due to the Bitcoin hack, but only if their transaction does not include a JS. That doesn't seem at all intuitive, and arguably worse due to the inconsistency.

Right now d. is my favorite approach. Increase `ASYNC_RPC_OPERATION_DEFAULT_MINERS_FEE` to 0.001, a factor of 10, which means JS will cost 10 times as much by default! Then also decrease `DEFAULT_MIN_RELAY_TX_FEE` by a factor of 1000 (down to 1 zatoshi/kb).

Pros:
- a change of two constants to address a usability edge case.

Cons:
- users may be suprised to pay *10 by default for txns.
- makes Zcash cheaper to spam with txns. (It's already relatively cheap vs Bitcoin because of exchange rate.)
- tweaks a bad design without fixing the underlying bad design.

Then as follow up, we need to put fee policy / mechanism on the roadmap for improvement.

**Comment by bitcartel** [comment]
I think option c is fairly easy to understand from an end-user perspective.

1. Bitcoin-style transparent transactions behave like Bitcoin

2. Shielded transactions behave differently.

Enabling free/cheap shielded transactions may help improve the anonymity set.  It's also a form of compensation for the extra computational resources required to generate a shielded transaction.

I think there are too many cons for option d.   Not to mention, the market can change in the blink of an eye whereas updating the code with new sane defaults and getting the network to upgrade is a slow process.

Maybe there should be no default z_sendmany fee and the user must always supply the fee parameter?   This won't solve the ticket itself but it does move us away from central planning.

**Comment by daira** [comment]
@nathan-at-least wrote:
> To be specific about d, what if we take take the constant JS-txn fee (0.0001 ⓩ == 10000 zatoshi), divide by the largest txn size allowed by consensus (100kb ?), to arrive at 0.0001 zatoshi/byte or 0.1 zatoshi/kb.

There seems to be a miscalculation here. Currently the "free" threshold is 0.00001 ZEC/kB according to @tromer's description. To make a fee of 0.0001 ZEC always exceed this threshold even for the maximum tx size of 100 kB, we only need to reduce the threshold by a factor of 10 to 0.000001 ZEC/kB, which is 100 zatoshi/kB. (So @nathan-at-least's calculation was a factor of 1000 out.) There is no precision problem with this AFAICS.

**Comment by daira** [comment]
@bitcartel wrote:
> Maybe there should be no default z_sendmany fee and the user must always supply the fee parameter? This won't solve the ticket itself but it does move us away from central planning.

User input into fee selection can potentially be used to distinguish users.

**Comment by bitcartel** [comment]
For reference as part of wider discussion on fees:

Bitcoin transaction accelerator

- https://www.viabtc.com/tools/txaccelerator/

Multibit HD wallet hard-coded fee limits now out of date.
- https://github.com/keepkey/multibit-hd/blob/c7bb908bf0c6a24e42b292371d96ca64e9fd6363/mbhd-core/src/main/java/org/multibit/hd/core/services/FeeService.java#L11
- https://www.reddit.com/r/btc/comments/5w7750/everybody_is_advised_to_move_bitcoin_out_of/?st=izm7nlsf&sh=a2cc55d0

**Comment by daira** [comment]
I propose that we reduce the "free" transaction threshold to 100 zatoshi/kB for 1.0.7. That should solve the problem.

**Comment by daira** [comment]
If changing the default free tx threshold, remember to also change (or preferably remove, so that it doesn't get stale again) this comment: https://github.com/zcash/zcash/blob/master/src/primitives/transaction.h#L277-L278

**Comment by nathan-at-least** [comment]
Re: https://github.com/zcash/zcash/issues/1969#issuecomment-281210517 In light of my miscalculation, let's do the simple single constant change soon. However, let's make sure we follow up long term with a full review of fees / relay / rate-limiting. We have a topical meeting scheduled for that topic.
