### ISSUE TITLE
Wallet support for import, export, and derivation of incoming viewing keys

### ISSUE THREAD

**Issue by zmanian** [zcash/zcash#1997]
I'd like to be able to generate a protected address offline, and then import the address and viewing key so that an online node can detect when a payment is received but cannot spend the funds. Related #1996

**Comment by tromer** [comment]
Depends on #406.

**Comment by daira** [comment]
Depends on https://github.com/zcash/zips/issues/101 .

**Comment by nathan-at-least** [comment]
The next step here is to specify a user-facing encoding with the viewing key and sufficient info to generate the full address. The RPC interface will produce/consume this.

**Comment by daira** [comment]
That will be done in https://github.com/zcash/zips/issues/101

**Comment by daira** [comment]
Review needed for https://github.com/zcash/zips/pull/117

**Comment by str4d** [comment]
One (now-obvious) problem I've stumbled into is that `z_getbalance` and `z_gettotalbalance` cannot show accurate balances for viewing keys, because spends cannot be detected. This is less of a problem than for #1528, because the user knows they are dealing with watch-only ZEC, but it is still an inconsistency. `z_listreceivedbyaddress` (which IMHO is poorly named, as it has very different semantics to `listreceivedbyaddress`) is not noticeably affected (yet), as it currently only lists incoming transactions and gives no indication of whether the notes have been spent.

@daira do the proposed Sapling changes to nullifiers happen to fix this?

**Comment by str4d** [comment]
By my reading of https://github.com/zcash/zcash/issues/2277#issuecomment-295027482 this problem is resolved by using vk<sub>all</sub> as the watch-only address. In that case, do we even want to implement viewing keys as currently-specified before the Sapling upgrade? Seems like a waste of the `VK` base58 prefix, which technically has not been defined yet (as https://github.com/zcash/zips/pull/117 has not yet been merged) and AFAIK is only implemented in a single place (https://github.com/FiloSottile/zcash-mini/pull/8). But perhaps even that is enough to have "burned" this prefix. And the current viewing key spec is still useful to enable showing incoming historic transactions, as all users can access it (unlike outgoing transactions, for which no payment disclosure has yet been saved). So I think I've talked myself back into continuing this :smile:

**Comment by daira** [comment]
We don't have to use VK as the prefix for incoming viewing keys. We could use VI for incoming, VO for outgoing and VA (or VK) for vk<sub>all</sub>, for example. Let's not delay the feature just because of bikeshedding over prefixes; there *might* be other reasons to delay the feature, but that isn't a good reason.

**Comment by str4d** [comment]
> One (now-obvious) problem I've stumbled into is that `z_getbalance` and `z_gettotalbalance` cannot show accurate balances for viewing keys, because spends cannot be detected.

There are a couple of different use cases for this feature:

1. Active: watching node / offline node split (#2542)
2. Passive: watching node for a remote online node
3. (Anything else?)

Case 2 is problematic because the watching node is completely passive, and must rely entirely on incoming blocks to detect spends. However, in case 1 there is user-mediated interaction between the watching node and the offline node; all spent transactions can be fully-logged as they are imported to the watching node, ensuring that an accurate balance is maintained.

The tricky part is conveying the above distinction to users. But if case 1 is uncommon, maybe it's fine?

**Comment by arielgabizon** [comment]
It seems the simple/doable thing is to have a watch only listreceivedbyaddress, that doesn't give the correct balance, cause it doesn't know about spends; just lists the incoming txs.
What do you think about that?

**Comment by arielgabizon** [comment]
A simple way to get this, perhaps not very clean, is to have a `makeWatchOnly` method that takes z_addr as parameter and simply deletes the spending key. If I understood the code correctly, scanning received txs should continue to work fine,

**Comment by str4d** [comment]
> It seems the simple/doable thing is to have a watch only listreceivedbyaddress, that doesn't give the correct balance, cause it doesn't know about spends; just lists the incoming txs.
What do you think about that?

That's certainly an okay interface on its own, but I expect what users want is more like what I've implemented in #2143 (ie. watch-only z-addresses), which has the aforementioned problem. I'm leaning towards documenting and ignoring the above problem, because I think that case 1 will be far more prevalent than case 2, and is fine for cold storage usage (where a user just wants to track incoming funds, and will burn the storage address completely when they go to spend any of it).

**Comment by arielgabizon** [comment]
Ahh.. I didn't find that PR before, so made some duplicate effort :) and implemented this makewatchonly  https://github.com/arielgabizon/zcash/tree/z_makewatchonly

**Comment by daira** [comment]
Note that the specification part of this has been merged: https://github.com/zcash/zips/pull/117
