### ISSUE TITLE
How much Ksol's is = Gh's

### ISSUE THREAD

**Issue by janellebradleyZ8p** [zcash/zcash#2029]
Somebody know, how to calculate and compare speed to classical sha256 mesurement. ?

**Comment by daira** [comment]
They're not really comparable at all. SHA-256-based mining is typically done on ASICs; Equihash mining is done on CPUs and GPUs. So it's not even meaningful to give a rough comparison on the same platform -- not to mention that the total mining power and hence the difficulty level is completely different for each coin.

**Comment by str4d** [comment]
From a technical perspective (in terms of how the values are calculated), 1 Sol/s in Zcash is equal to 1 H/s in Bitcoin. But if you run a Bitcoin miner and a Zcash miner on the same hardware, you'll get higher numbers for the Bitcoin miner, because Bitcoin's proof-of-work function is easier. So I agree, it doesn't make sense to try to compare them.
