### ISSUE TITLE
Evaluate Flexible Transactions or Similar

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2071]
Bitcoin issues fixed by Flexible Transactions (https://bitcoinclassic.com/devel/Flexible%20Transactions.html):

- Malleability
- Linear scaling of signature checking
- Hardware wallet support (proofs)
- Very flexible future extensibility
- Double Spend Proofs
- Makes transactions smaller
- Supports the Lightning Network
- Support future Scripting version increase

Comparison with SegWit:
https://bitcoinclassic.com/devel/FlexTrans-vs-SegWit.html

**Comment by HostFat** [comment]
Same topic :)
https://bitco.in/forum/threads/buip037-hardfork-segwit.1591

**Comment by daira** [comment]
This earlier post is also worth reading: https://zander.github.io/posts/Flexible_Transactions/

**Comment by radix42** [comment]
Having skimmed the code for both SegWit and FlexTrans, I know that I'd much rather maintain ports that had merged FlexTrans

**Comment by daira** [comment]
We'll discuss this in the topical meeting on February 28.

**Comment by zander** [comment]
Sounds like a good idea ;)

**Comment by bitcartel** [comment]
9th March 2017: A malleability attack on upstream Bitcoin https://www.reddit.com/r/Bitcoin/comments/5ykl4g/bitclub_why_are_you_doing_malleability_attack_now/?st=j042agov&sh=a823b654

**Comment by ebfull** [comment]
I don't oppose the approach FlexTrans takes to solving malleability problems (it's not too different from what segwit does), though I do think we will need a solution tailored to our needs. The kinds of txid relationships we have in our existing protocol may be removed in the future as they are inherently privacy-violating. This may change our general approach to these problems.

However, I don't think CMF is a good serialization format for Zcash transactions.

CMF has no ordering constraints on tokens, and encourages skipping "unknown" tokens for forward-compatibility purposes. We have a general goal of making our transactions indistinguishable from each other, which means they should mostly consist of fixed-size blobs of data that are indistinguishable from randomness. Both of these properties of CMF, and probably others that I've overlooked, seem like threats to that goal.

We want a very rigorous and well-specified format for our transactions. We intend to hard-fork to adopt new transaction formats and protocol features, so we do not need forward-compatibility. Perhaps we could adopt CMF and have a strict interpreter of some kind, but why accept the overhead costs (CMF can't support fixed-size blobs, self-identifying tokens when our schema is strictly ordered, etc.) and the code complexity?

**Comment by zander** [comment]
> However, I don't think CMF is a good serialization format for Zcash transactions.  
> CMF has no ordering constraints on tokens, and encourages skipping "unknown" tokens for forward-compatibility purposes.

This misunderstands CMF, the format is essentially like XML in that it is just a way to serialize data. How you format the actual data is a layer on top (like a schema).

In FlexTrans I initially actually had an ordering constraint, but later removed it from the parsing code in CTransaction as I didn't see the point. In my opinion, the protocol should not be the one to define how its used. The wallets can decide on a specific format that are all the "standard" if they want to. I personally don't really see why that warrants restricting the protocol.  You can re-add the forced ordering without much of an issue, though.

The second point of critique you have is that it 'encourages skipping unknown tokens', and this is a slightly more complex topic. As I did it in Bitcoin Classic, a node by default skips those unknown tokens, but there is a flag you can set on your own node which causes it to detects and rejects any transactions with tokens it doesn't recognize.  
The suggestion is that miners enable that stricter validation in order to avoid wallets getting creative and putting in tokens without there being a network consensus on their usage.

This allows the best of both worlds in Bitcoin, nodes are backwards compatible and nobody can abuse this system because miners won't allow you. If you think this is a real issue for zcash, just change the policy rule to be a consensus rule.

> CMF can't support fixed-size blobs, self-identifying tokens when our schema is strictly ordered, etc.

I'm unable to parse this critique...

**Comment by ebfull** [comment]
> I'm unable to parse this critique...

Our proofs are fixed-sized binary blobs. CMF forces us to include a varint length preceeding them, yet their sizes are statically known. This is just an overhead problem _for us_ not really a critique of CMF.

Additionally, tokens have to identify themselves because there is no ordering requirement, but if there is one, and we have a strict schema, and almost everything we do is fixed size, then why should we use CMF?

**Comment by ebfull** [comment]
@zander Hopefully you don't interpret my comments as attacks. I don't have any opinions on CMF, I just don't (currently) see how it meets our needs for Zcash.

**Comment by bitcartel** [comment]
@zander Have you used CMF in other projects?  Where did it originate from?

@ebfull I don't think having a length token would be overhead.  It's only a few bytes.  Big picture, a joinsplit is around ~2000 bytes, so it seems to be a small price to pay for forward compatibility.  Fwiw, I'm not really a fan of varints.  Needless complexity.

This problem of cross platform serialization has been solved many times over... we just have to pick one that works for our needs.  I think we need a solution which offers compact wire representation, easy to update IDL schemas (developer sanity), and cross-language support (happy ecosystem).

Outside of CMF as discussed, Protobof is an obvious candidate and Flatbuffers looks interesting if we can take advantage of zero copy i.e. we can hash over the bytes we need for a txid without having to create a second representation of the transaction in memory.

https://google.github.io/flatbuffers/flatbuffers_benchmarks.html
https://capnproto.org/news/2014-06-17-capnproto-flatbuffers-sbe.html
https://code.facebook.com/posts/872547912839369/improving-facebook-s-performance-on-android-with-flatbuffers/

**Comment by zander** [comment]
@ebfull putting a size-int in front of a byte-array is rather standard method to allow backwards / forwards compatibility. It is, for instance, also done for the prev-tx-id.  Its only one byte there.

@bitcartel CMF is based on ideas in the industry, you'll see a lot of parallels with protobufs. The problem with using a 3rd party library is that it is a dependency for something that **needs* to be canonical.  For similar reasons that Bitcoin Core removed the openssl dependency, I think it makes sense to avoid any external dependency.

The truth is that CMF is trivial to implement. I provided implementations here; https://github.com/bitcoinclassic/cmf-bindings

What you'll find in the 'cpp' folder there is a zero-copy solution for building your messages. It also has some memory management solutions for a large amount of 'messages' in the form of ConstBuffer / BufferPool.  
Shortly I'll release a proof of concept in Bitcoin Classic that introduces new block and a new transaction classes based on that. They avoid the interpretation step (canonical format is kept) and the transactions instead share the memory of the block they are contained in. This is based on the ConstBuffer class provided in the cmf-bindings project.

In short; CMF (and the CMF-bindings repo) is build exactly for the reasons you outline;

* zero copy
* compact wire representation. (which for transactions is also the canonical representation)
* great APIs (builder pattern, SOX consumption pattern) to make IDL-like schemas as flexible and back/forward compatible as you want.

The code that currently resides in the FlexTrans [branch](https://github.com/zander/bitcoinclassic/tree/flextrans) is not fully using the functionality because it was a minim and non-intrusive change. The load/saving code there is more dirty than I would like it to be. The technology is there, but the Bitcoin codebase is too... not-clean... to apply it easy. I prefer thinking long term, though, and creating great foundations to build on. Which is what CMF is, in my opinion.

**Comment by str4d** [comment]
Possibly useful: https://github.com/zcred/zser#comparison-with-other-serialization-formats

**Comment by zookozcash** [comment]
Related: https://github.com/bitcoincashorg/workgroups/blob/master/wg-malfix/summaries/20180130%20-%20Meeting%20Summary.md

**Comment by daira** [comment]
This seems a bit too ambitious for Blossom, but I may be wrong.

**Comment by zookozcash** [comment]
I'm 👎 on this ticket for the same reason as https://github.com/zcash/zcash/issues/2593#issuecomment-439671784: because I think we shouldn't be spending effort improving t-addresses (making them non-malleable) when we could instead spend that effort improving z-addresses. Also per https://github.com/zcash/zcash/issues/2071#issuecomment-286819579, I agree that flexibility in formatting, such as making it easier to make things have variable length, appear in different orders, or be "skipped"/optional may be unnecessary or even harmful to our goals.

**Comment by nuttycom** [comment]
Closing as we've already addressed nonmalleability, and the rest of the changes aren't really worth doing in zcash. Reopen if this ever changes.
