### ISSUE TITLE
showmetrics interferes with start-up error prompts

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2095]
When -showmetrics is active, the "Do you want to rebuild the block database now?" prompt does not work (see https://forum.z.cash/t/zcash4win-beta-is-out/14155/13 ).

**Comment by bitcartel** [comment]
Perhaps the showmetrics screen should only appear after the start-up process is complete e.g. all possible interactive prompts have been presented to the user, or reindexing is complete?

**Comment by str4d** [comment]
The `CClientUIInterface::ThreadSafeMessageBox` interface returns a boolean. In the QT implementation this boolean reflects whether the message button was clicked; in the noui and metrics implementations, this always returns false, because there isn't anywhere to get a response. So the prompt has never worked for CLI users of Bitcoin.

Upstream fixed this inconsistency in bitcoin/bitcoin#8257, but we *could* alter the metrics screen to enable taking that kind of user input (as startup progress is blocked anyway, so disabling screen refreshing to get a response should be fine).
