### ISSUE TITLE
Benchmark t-addr performance for large wallets

### ISSUE THREAD

**Issue by arcalinea** [zcash/zcash#2156]
User feedback from https://github.com/zcash/zcash/issues/1749#issuecomment-270073129:

> [W]ith wallet files > 200 MB (lots of transactions) the wallet still gets "slowish" in responsiveness. Creating a new wallet.dat, sending all funds there and then working from that new wallet fixes the issue for a month or so (until the wallet grows to 200 MB again..)

**Comment by str4d** [comment]
We have received feedback from several other users, along similar lines: wallets containing many t-addresses (in one case over 226k keys) suffer from severe performance problems. We have yet to determine whether the cause is the presence of many *keys* or many *transactions*, but for larger users these are likely interchangeable.

**Comment by arielgabizon** [comment]
I wonder if it has to do with the fact that the availablecoins method 
https://github.com/zcash/zcash/blob/59de56eeca6f9f6f7dc1841630d53676075242a5/src/wallet/wallet.cpp#L2191
 seems to return all unspent outputs, and is invoked each time sendtoaddress or z_sendmany is invoked.  If there was a way to give it an amount,  and to stop when it's accumulated that amount

**Comment by nathan-at-least** [comment]
I just renamed this to focus on benchmarks. There are at least two conditions I'm aware of affecting large-scale users:

- many t-addr keys. Reports of somewhere less than 300k.
- many UTXOs. I'm not sure on UTXO distribution per key yet, so we could guess what a reasonable distribution might be.

We should have two datasets:

- a wallet with a very large number of t-addresses, with some distribution of UTXOs for those addresses.
- a wallet with a single t-address which holds many UTXOs.

Let's add benchmarks for similar cases for z-addresses with notes as a separate ticket: **FIXME: file ticket**.

Then we should take multiple measurements for each dataset:

- Latency for RPC calls. Let's find out from high-volume users which RPC calls are experiencing performance problems.
- Memory consumption?
- On-disk wallet size.
- I/O usage statistics?

**Comment by nathan-at-least** [comment]
One suspect for poor performance in creating t-addr -> t-addr transactions, such as with `sendtoaddress`, is that we introduces a full-utxo-set on-demand sort (at my request). So once we have a benchmark in place for multiple RPC calls which pass through that sorting path, a quick improvement check is to remove the sort and use the underlying UTXO order. HT @arielgabizon 

Related: #2411

**Comment by str4d** [comment]
I have put together a preliminary benchmark, by using the RPC test system to create a wallet with 65k UTXOs (each to a unique address in the wallet), and then measuring how long it takes for that wallet to run `sendtoaddress` (to another new address in its own wallet each time). Bear in mind that by definition, each iteration has a different UTXO set to the previous iteration. I think this is fine, because it's more like what actual users would experience.

Here are the results (in seconds) for taking 10 measurements on my laptop (Core i7-6600U CPU @ 2.60GHz):

```
[
  {
    "runningtime": 3.471206
  },
  {
    "runningtime": 4.908124
  },
  {
    "runningtime": 3.21015
  },
  {
    "runningtime": 6.818006
  },
  {
    "runningtime": 4.789534
  },
  {
    "runningtime": 4.735652
  },
  {
    "runningtime": 4.851208
  },
  {
    "runningtime": 3.655416
  },
  {
    "runningtime": 4.930604
  },
  {
    "runningtime": 3.178228
  }
]
```

The 65k number is rather arbitrary: it's how many inputs my laptop could generate over the course of about 12 hours. I used a fake RPC test to generate the wallet, by creating two nodes, having one mine a bunch of blocks to get some coinbase, and then continually sending 0.001 TAZ to new addresses from the other node. I observed that the rate at which transactions could be created did slow down over time, which itself is something we may want to investigate (maybe related to UTXO counts increasing on that node, or possibly just linked to the wallet size).

**Comment by arielgabizon** [comment]
You said it slows down over time, but the measurements you wrote are not increasing.
Also, I wonder if it's easy for you to test with different set sizes to compare? e.g. 30k, 100k
To get a sense of how it changes with set size.
The complaints I see of an exchange were with 200k size.

**Comment by str4d** [comment]
On 17 Aug 2017 11:27 am, "Ariel" <notifications@github.com> wrote:

You said it slows down over time, but the measurements you wrote are not
increasing.

Different measurements. I said that *creating* the 65k UTXOs slowed down
over time (and it was over thousands of transactions that the slowdown was
seen, not the ten I give here). That's a different measurement to *using*
the UTXOs, which is what the numbers above are for. Given that I have
wallets for both cases now, I'm keen to make benchmarks for both cases.

Also, I wonder if it's easy for you to test with different set sizes to
compare? e.g. 30k, 100k
To get a sense of how it changes with set size.
The complaints I see of an exchange were with 200k size.

I was trying to create one with 200k UTXOs to start with, but it was taking
too long on my laptop. I'll use one of the servers to generate that. We
definitely want to see how set size affects it - this is exactly how we
could measure the slowdown I was seeing. We would only pick e.g. three
sizes though, so we'd want to make them representative of actual use cases.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zcash/zcash/issues/2156#issuecomment-323030760>, or mute
the thread

**Comment by arielgabizon** [comment]
@str4d I wonder if you would be interested in trying a version I wrote,
where availablecoins only collects enough coins for the tx
https://github.com/arielgabizon/zcash/tree/fastcoinselection

**Comment by arielgabizon** [comment]
My experiments show the above version is ~30 times faster for @str4d 's dataset

**Comment by str4d** [comment]
I've created a [200k UTXO dataset](https://z.cash/downloads/benchmarks/benchmark-200k-UTXOs.tar.xz) (each 0.001 TAZ) for use in benchmarks. Here are the relevant metrics:

```
$ ./src/zcash-cli -datadir=benchmark-200k-UTXOs/node0 getwalletinfo
{
  "walletversion": 60000,
  "balance": 200.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 200000,
  "keypoololdest": 1504137695,
  "keypoolsize": 2,
  "paytxfee": 0.00000000
}
$ ./src/zcash-cli -datadir=benchmark-200k-UTXOs/node0 listunspent | grep txid | wc -l
200000
$ ./src/zcash-cli -datadir=benchmark-200k-UTXOs/node1 getwalletinfo
{
  "walletversion": 60000,
  "balance": 1633.52423681,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 609.60076319,
  "txcount": 200304,
  "keypoololdest": 1504137702,
  "keypoolsize": 2,
  "paytxfee": 0.00000000
}
$ ./src/zcash-cli -datadir=benchmark-200k-UTXOs/node1 listunspent | grep txid | wc -l
185
```

**Comment by str4d** [comment]
We now have benchmarks of `sendtoaddress` latency and memory usage for several wallet cases:

- Wallet contains 200k transactions creating 200k UTXOs (all 0.001 TAZ, all in separate t-addrs)
- Wallet contains a little over 200k transactions and only ~200 UTXOs (nearly all 10 TAZ in value IIRC)

For latency, we test sending amounts that in the former wallet would require 1, 10, or 100 UTXOs (and in the latter wallet should only require one UTXO in every case). I think this sufficiently covers the brief.
