### ISSUE TITLE
Upgrade gcc on build servers from 4.9.2 to 6.x

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2219]
The build servers currently use gcc 4.9.2.

[Resolved by updating build options for older version of cmake on the build server] The AMQP PR https://github.com/zcash/zcash/pull/2189 cannot be merged as it appears to require gcc 5.x or greater.  This issue prevented merging for the 1.0.8 release.

However, changing the gcc version can lead to the build script `check-security-hardening.sh` failing:
https://github.com/zcash/zcash/issues/2212

**Comment by bitcartel** [comment]
Updated ticket to move to gcc 6 since that is what Debian 9 (Stretch) will be using when it is released, sometime in Q2 or Q3 of 2017.

**Comment by nathan-at-least** [comment]
I want to systematize how we configure our builders, when we upgrade them, how that connects to our supported platforms, etc… I wrote a first pass on an official policy on our wiki: https://github.com/zcash/zcash/wiki/supported-platforms-policy

According to that policy, for a platform like debian testing we would do an apt-get distupgrade or something similar for each CI deployment, which should happen between each release. Otherwise, we shouldn't use any non-standard/non-default versions for the target platform.

**Comment by nathan-at-least** [comment]
I'm leaving this in 1.0.9, since the policy above was just written moments ago. For 1.0.9, we should ensure the builder is as close to stock debian stretch which has been recently updated as possible.

**Comment by nathan-at-least** [comment]
I was confused. This is now a NACK for me because our current builder is Debian Jessie (currently stbale), and the standard gcc for is 4.9.2.

Instead of upgrading the compiler, we should create a new builder for Debian Stretch and make that a fully supported platform. Then if our software doesn't build on Jessie, we should deprecate that platform altogether.

**Comment by nathan-at-least** [comment]
Closing in favor of #2366.

**Comment by daira** [comment]
I disagree that we should have a policy that automatically precludes supporting platforms on which the default toolchain cannot build Zcash. It is perfectly commonplace for the default toolchain to be several releases behind what a developer would typically use, and so if we have this policy, then we will:
* abandon support for some very commonly used platforms, and/or
* suck development effort into trying to make our code (including dependencies) build using obsolete or buggy toolchains.

Note that we do build correctly using gcc 4.9, so I'm not sure why we were trying to upgrade to 6.x specifically. My point is that the policy being followed here could be harmful in other cases (for example, it would preclude supporting Ubuntu Trusty, which only has gcc 4.8 in its default toolchain, but is still commonly used).
