### ISSUE TITLE
Modify CI infrastructure to be able to target non-master branches for performance benchmarks

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2236]
We need to be able to do benchmarking on PR's *prior* to making merge decisions.

**Comment by str4d** [comment]
It turns out that we did add this ability months ago - the `zcashperformance` builder can be triggered directly from the CI interface (it's what I used while diagnosing #2238). However, the Buildbot config ignores the `repository` setting and uses a hard-coded reference to the main Zcash repository, so we can currently only benchmark branches there. So we still need to make modifications.
