### ISSUE TITLE
Decide how spends from old notes or addresses will work after the Sapling circuit upgrade

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2248]
If the Sapling upgrade changes the calculation of new note commitments and/or addresses, then we will still need a way to spend from old notes and/or old addresses. There are several cases we might need to deal with depending on how the circuit is changed:

1. The circuit does not change either note commitments or addresses. (It may still upgrade the commitment Merkle tree.)
2. The circuit changes note commitments, but not addresses.
3. The circuit changes addresses, but not note commitments. New addresses have an a<sub>pk</sub> field that is the same size as the old a<sub>pk</sub> field (32 bytes), so that the commitment derivation does not need to change.
4. The circuit changes both addresses and note commitments. The new commitment derivation is always used for new addresses, and the old one is always used for old addresses.
5. The circuit changes both addresses and note commitments. The new commitment derivation is always used for new payments, even to old addresses.

Case 1 needs no further discussion here.

For cases 2, 3, 4, and 5 we have two possibilities:

   a) Assume we also do #647. There is a separate circuit for a subtransaction that takes a shielded input from an old-style note commitment and address, and passes it to the value commitment output.
   b) The new circuit(s) directly support spending from an old note and address. If the note commitment has changed then they must always pay the cost of two SHA256Compress evaluations to compute the old-style note commitment, in addition to any new commitment function (if it does not use SHA256Compress). If the address derivation has changed then they must always pay the cost of one SHA256Compress evaluation to compute PRF<sup>addr</sup>, in order to confirm knowledge of the input spending key, in addition to any new address derivation (if it does not use SHA256Compress).

The advantage of a) relative to b) is that the new circuit(s) do not have to consider old notes and/or addresses, and so can be more efficient.

The disadvantage of a) is that spends from old notes or addresses are distinguishable. Note that in this case it's possible to tell publically how many old notes are left; however the size of the anonymity set does not decrease &mdash; even the last spend of an old note could be spending any old note that the adversary does not know to have already been spent.

**Comment by daira** [comment]
A variation on a) is that the compatibility circuit produces a transparent output, rather than an output in the value commitment. That would allow the total value that has gone through old shielded notes to be audited, at some cost in privacy. Note that this drastically reduces the privacy of the last few transactions that spend from old notes, since their values can potentially be inferred. On the other hand it would provide confidence that there has been no overall inflation of the monetary base while the old zk-SNARK curve, circuit, and parameters were being used &mdash; regardless of weaknesses in the old curve, bugs in the old circuit implementation, or compromise of the old toxic waste.

**Comment by daira** [comment]
For cases 3 and 4, if we support both old and new addresses after the circuit change then that greatly complicates the new circuit. For 3a) and 4a) we could only support sending to old addresses via the compatibility circuit. (This would be transparent to users; the shielded transaction planner would choose the right circuit(s) depending on the input notes and output addresses.)

**Comment by daira** [comment]
My preference is for 4a) with only transparent outputs from the compatibility circuit.

This option allows maximising the performance of the new circuit by changing both commitments and address derivation to use more efficient hashes. However it is one of the simplest options (besides option 1), and enables dropping the compatibility circuit later to reduce technical debt, after leaving a reasonable time for users to move old notes. It also facilitates auditing the old-note monetary base in order to increase confidence that there was no overall inflation due to security weaknesses in the old curve, circuit, or parameters.

**Comment by daira** [comment]
If we require compatibility JoinSplits to be *individually* transparent, then that would reveal more information than if we make each compatibility JoinSplit take and produce a value commitment but separate those commitments from the ones used in the new circuit. I.e. the total balance of compatibility JoinSplits in a transaction would be transparent, but individual note values would not be revealed. This is still compatible with auditing the old-note monetary base.

**Comment by str4d** [comment]
@daira wrote:
> Note that in this case it may be better to require users to explicitly move value from old notes to a transparent address, rather than doing so implicitly whenever old notes are needed to make up the required value, because that makes it clearer that the amount is being exposed.

Agreed, but rather than requiring a transparent address, we should instead return an error if we don't have enough new notes but do have enough old notes, telling the user how to migrate their funds (and the associated risks).

> My preference is for 4a) with only transparent outputs from the compatibility circuit.

This is also my preference.

> It [..] enables dropping the compatibility circuit later to reduce technical debt, after leaving a reasonable time for users to move old notes.

This would also enable @zookozcash's note-recycling idea (at this one point in time, not repeatedly into the future) - notes that have not been migrated would be provably-unspendable after the compatibility circuit is removed, and thus anything left between the audited value and the expected value (at the height we introduced the new circuit) could be later re-introduced to the network through block subsidies.

> If we require compatibility JoinSplits to be individually transparent, then that would reveal more information than if we make each compatibility JoinSplit take and produce a value commitment but separate those commitments from the ones used in the new circuit. I.e. the total balance of compatibility JoinSplits in a transaction would be transparent, but individual note values would not be revealed. This is still compatible with auditing the old-note monetary base.

Here's another idea: what if we additionally had a new sub-circuit that let users spend old funds to old addresses, but only with knowledge of the old address's spending key? Then we could turn off the old circuit entirely, forcing users to migrate to new addresses, but still give them the ability to move money between addresses they control or split value off from that pool. This would make it possible for the wallet migration code to use common transparent values for additional privacy, thus only leaking a small non-common amount (which could be done carefully at a different time to the other migrations - maybe even automatically after first upgrade, so that only a round number of ZEC remains in the old addresses for manual migration).

**Comment by daira** [comment]
@str4d wrote:
> [...] notes that have not been migrated would be provably-unspendable after the compatibility circuit is removed, and thus anything left between the audited value and the expected value (at the height we introduced the new circuit) could be later re-introduced to the network through block subsidies.

I think this should be excluded from the scope of Sapling; we could do it in a later hard-fork, possibly.

**Comment by nathan-at-least** [comment]
**TODO:** Spell out some requirements I'd like (they may already be here, I haven't read the backlog):

- one-shot global accounting of all value which entered/will leave Sprout "shielded domain" as a check against counterfeiting.
- Immediately turn off send-to-Sprout, leaving send-from-Sprout.
- no *explicit* address expirty (although after enough time, we probably want to remove Sprout entirely)
- upgrade from Sprout to Sapling cannot involve intermediate transparent UTXOs.

**Comment by nathan-at-least** [comment]
Eventually we want to remove Sprout addresses, as long as we can do it safely. This would logically have two steps:

Step 1. disable Sprout addresses as destinations
Step 2. disable Sprout addresses as source addresses.

Step 2 will destroy funds, so we must be extremely careful there. The reason we expect step 2 to destroy funds is due to lost keys, and it is difficult to predict how much value is lost in this manner (versus long-term storage).

Our current thinking is that we would specify criteria for Step 2 up front to remove any potential for discretionary abuse which would specify:

- timescale for disabling Sprout addresses.
- what to do with any deficit of funds.

We need to propose any deprecation plan before the Sapling upgrade.

**Comment by gojomo** [comment]
Considering "Step 2", a definitive end-of-life for Z-Sprout addresses: this also presents a risk-of-loss due to inattentive hodlers (who miss or misunderstand any announcements of urgent, transfer-or-lose cutover dates) or network congestion as the last-block-to-evacuate-Z-Sprout funds approaches. While the easiest "Step 2" would be a "simple flag day" (block) after which sends-from-Z-Sprout are invalid, I believe that'd increase the risk of such losses.

So, an idea: what if instead, there are a stepped series of deadlines, each of which applies an increasing decay to evacuated Z-Sprout funds? 

Plenty of warning would still be given to evacuate 100% of funds. But then the first decay would be a tiny amount – a 'warning shot' – with lots of time to react. There'd be plenty of online fury at that point, no matter how small the decay – but that would also serve to get the word out that evacuating Z-Sprout addresses is urgent, far more effectively than any sternly-worded and oft-repeated warning of imminent future losses. Further deadlines/decay would accelerate.

Variations & related thoughts:

* Rather than entering a "known-dead" pool for (maybe someday) future re-issue in block rewards, any decayed funds could be immediately rewarded to miners. Or even, to earlier-Z-Sprout-evacuators, or earlier Z-Sapling arrivers, as an extra incentive for helping to quickly transition into improved Z-Realms.

* Even separate from the Z-Sprout to Z-Sapling transition, given other future Z-Realm additions, or (maybe someday) total-sunset of T-Addresses, it'd be useful for ZCo or ZFo to indicate its intended 'advance warning' periods, and notification-standards, before changes that might invalidate idle old balances. For example: "Barring emergencies, at least 2 years' warning; warning repeated monthly through official channels A, B, C; with additional persistent countdown banners displayed at X, Y, Z."

* Obviously, if there ever appears to be an otherwise-valid transaction that makes the net of funds moved *out* of Z-Sprout exceed the net transparently moved *into* Z-Sprout, that indicates a serious, perhaps extinction-of-the-system-level bug. Is there currently consensus-code enforcing the bottom-line constraint, and if so, does it do anything more than alert-and-panic? Notably, once a second Z-Realm (Z-Sapling) is online, such a Z-Sprout ZEC-inflation bug might *not* be fatal to the whole system, if code catches that bottom-line violation and uses it to rapidly contain the damage to the old-realm. OTOH, "Step 1" alone above could trigger a race by any entity/entities in secret possession of Z-Sprout ZEC-inflation bugs to evacuate Z-Sprout balances – accelerating the exercise-and-revelation of such a bug. Perhaps, the staging of the Z-Sprout-to-Z-Sapling transition could moderate how damaging such a (hypothetical) Z-Sprout inflation bug would be. For example, overall robustness might be improved by triggering 'Step 1' only after the total ZEC in Z-Sapling is N times what remains in Z-Sprout. 

* One way of looking at both the 'decay' and the bottom-line net-realm constraint is that there's a sliding cap on the total-number-of-ZEC recognized as inside a Z-Realm. As that cap decreases during a phase-out, any ZEC remaining over the cap get a proportional haircut. Perhaps the sliding cap could also be used as a new realm in phased-in. This would be a usability nightmare for early adopters – attempts to use the new realm might fail based on others using available ZEC capacity first – but would serve as a obtrusive indicator "this still needs the test of time" and potentially limit the damage of serious bugs in the new realm that are revealed during the phase-in.

**Comment by daira** [comment]
Everything in this comment is just my opinion, not a ZcashCo position.

There is a clear security rationale for the Sprout phase-out. A situation where the security (balance preservation, privacy, DoS resistance) of Zcash would depend on *both* the Sprout and Sapling subprotocols, would incur risk that is unnecessary and unacceptable if it were sustained for more than a known, limited period. Supporting both subprotocols also adds significant technical debt that we would have a strong incentive to remove.

This suggests a fixed time-based phase-out. It makes sense for the deadline to be measured from when Sapling activates, since that's what is relevant to how long users have to transfer their funds. (Sprout notes *can* be unshielded to a unique transparent address before the Sapling activation, and that doesn't actually lose much additional privacy; of course users who do that might lose some privacy if they moved the funds again before the activation. In any case I think this doesn't change the argument for measuring the deadline period from the Sapling activation point.)

We need to consult the user base on the deadline period, even before Sapling is implemented. It would be unfortunate if we imposed a deadline that ended up upsetting a significant portion of users, and that would feed into FUD about Zcash being subject to centralized decision-making.

Technically, it is possible to make the schedule for phase-out dependent on the proportion of Sprout funds that have been unshielded (relative to the amount at the Sapling activation point). For example, a possible straw-man schedule could be:

* Wait until 50% of Sprout funds have been unshielded, then disable Sprout addresses as destinations.
* Wait another 6 months, then disable Sprout addresses as sources.

But after careful consideration I don't really see what this gains us. It adds significant complexity, both for the implementation and for explaining to the Zcash user base when the phase-out will happen. Third party ecosystem developers (exchanges, wallet devs, etc.) would not have a clear schedule for what they have to implement by when. In particular, the first phase might happen more quickly than expected, leaving almost no time for third-party devs to respond. Alternatively, it might never happen, leaving us in an extended period of uncertainty similar to the situation that Bitcoin had with Segwit (note that this argument is independent of the technical merits or otherwise of Segwit). Overriding the policy with another hard-fork would then cause more controversy than if it had been time-based in the first place. It is possible to have a deadline dependent on both time and funds transferred, but this doesn't really help much over a simple time-based deadline.

@gojomo wrote:
> For example: "Barring emergencies, at least 2 years' warning; warning repeated monthly through official channels A, B, C; with additional persistent countdown banners displayed at X, Y, Z."

I know the particular time period is not the main point you were trying to make, but in my opinion, two years is far too long to incur the significant security, engineering, and support costs of both circuits being enabled. Also, based on current performance estimates, there will be such a clear rationale for moving funds to Sapling, independent of whether it's forced, that I really think the phase-out will turn out not to be much of a problem in practice. We shouldn't exaggerate the issue of hypothetical unresponsive hodlers of static shielded funds.

> Obviously, if there ever appears to be an otherwise-valid transaction that makes the net of funds moved out of Z-Sprout exceed the net transparently moved into Z-Sprout, that indicates a serious, perhaps extinction-of-the-system-level bug. Is there currently consensus-code enforcing the bottom-line constraint, and if so, does it do anything more than alert-and-panic?

This is ticket #2351 (which I think should be implemented soon, preferably in 1.0.13). I think it should *only* alert-and-panic, but let's discuss on that ticket.

The incremental haircut idea adds a great deal of complexity and I don't like it (but thanks for the feedback).

Note that recycling lost funds to miners gives a perverse incentive for miners to obstruct the unshielding of Sprout notes. I think this wouldn't be much of a problem in practice unless we had a serious revolt from a large proportion of miners, but that possibility should be considered.

**Comment by nathan-at-least** [comment]
Note, we may want to re-use a similar kind of address-freeze / turnstile mechanism as an emergency recovery mechanism in the case of a cryptographic break that allows counterfeiting. Imagine if we discover there's a plausible vulnerability for counterfeiting, then it might be a helpful contingency mechanism to be able to freeze spends from or to addresses within a particular circuit or commitment tree. Once frozen, we'd have more time to decide on mitigations.

**Comment by gojomo** [comment]
Totally agreed that Z-Sapling (as currently envisioned) offers compelling security/usability advantages whose rapid adoption would benefit all ZEC users. But I think that must be weighed against:

* all such new tech needs real-use, with real value at stake – and essentially 'calendar time' – before it will be (or *should be*) widely trusted
* ZEC-holders may not be generally aware of the need to migrate balances regularly; despite prior indications to that effect from both ZCo & @zookozcash, it is a very different model from both traditional currencies & more-well-known cryptocurrencies. 

So even to the extent I agree that regular "realm migrations" (similar to software auto-sunsets) can offer benefits in keeping tech fresh, and tech-debt low, and estimations of the "live float" accurate, it needs very clear & careful expectation management. I haven't yet seen any official announcement with a firm indication of what ZCo/ZFo think a fair-warning period for address-obsoletion would be – but it'd be appropriate to set general standards even before making the specific Z-Sprout decisions. (And, as the very first warning of its kind, if anything, the Z-Sprout should have a more generous period than later periods, which can move more quickly after the precedent is understood & publicly-demonstrated.) .

While disabling Z-Sprout-origins is the step with the largest risk of irreversible value loss, other risks would be associated with disablement of Z-Sprout-destinations faster-than-expected, in broken wallet/payment software. So the guidance might take the form "at least N months' warning will be given before an address-type becomes invalid as an origin, and at least M months' warning before an address-type becomes invalid as a destination". I'd expect M<=N. As my strawman idea of a plausibly-fair N was 24 months, my strawman of a fair M would be 6 months.

@daira writes:

> Also, based on current performance estimates, there will be such a clear rationale for moving funds to Sapling, independent of whether it's forced, that I really think the phase-out will turn out not to be much of a problem in practice. We shouldn't exaggerate the issue of hypothetical unresponsive hodlers of static shielded funds.

I hope you're right! What do you think is a reasonable known, limited period in which both Z-Sprout and Z-Sapling would both be active? 

My not-yet-firm preference, motivated by concerns above, would be that first, the "M, N" generic guidance above about future Z/T-address obsolescence is given. Then, Z-Sapling is activated,  *without* any firm Z-Sprout obsolescence dates – just guidance that they will be announced soon, based on observed adoption of Z-Sapling. (Thus, the overlap is *at least M* months.) Then, with extra real-world info about legacy Z-Sprout persistence, the 'definitive' dates for obsoleting Z-Sprout-destinations and then Z-Sprout-origins would be announced. (Ideally, these would be within the hoped-for context of: "Z-Sapling adoption has been impressively rapid; already Y times more ZEC are in Z-Sapling than Z-Sprout, so we can now set firm Z-Sprout EOL dates of...")

(I wouldn't suggest any instant/surprise feature-disablements, dependent on others' unpredictable usage, like "disable Z-Sprout-destinations the block after sum_in(sprout) < 0.5*max_ever(sprout)". But I could see such automatic thresholds starting a multiple-month countdown, so the exact date isn't known at first, but it becomes increasingly likely, then locks in a definitive date with adequate warning. Such a trigger could serve as a sort of stake-based confirmation of the ZCo team's conjectures about the benefits of Z-Sapling, and thus increase community confidence in the timing. And if the 'never happen' risk materializes – that is, lots of ZEC *wants* to stay in Z-Sprout, despite the ostensible benefits of Z-Sapling – then maybe our shared prior expectations about its desirability were so wrong that a fixed-date would have been even more community-hostile – making a fresh HF plan warranted.)

The incremental haircut might be made more palatable if it were implemented as a "late evacuation fee". Any perverse miner-incentive to ignore such transactions might be avoided by awarding the 'fee'/dead-ZEC instead to early-evacuators (on some sort of 'FOFI' basis: "First-Out, First-In(centivized)"). To be honest, I expect every discussion and decision regarding any potential ZEC destruction or resuscitation to generate anger/nastiness/FUD. That includes this incremental-decay idea. In fact, I could even see decay generating extra criticism, along the lines of "if we have this period to rescue 99% of our Sprout-ZEC, why can't it be 100%?" But that criticism itself could serve to reduce the number of addresses that'd otherwise (under an all-or-nothing policy) be surprised by 100% losses. Suffering more FUD but keeping more users' ZEC alive could be a valid tradeoff.

**Comment by daira** [comment]
@gojomo wrote:
> Totally agreed that Z-Sapling (as currently envisioned) offers compelling security/usability advantages whose rapid adoption would benefit all ZEC users. But I think that must be weighed against:
>
> * all such new tech needs real-use, with real value at stake – and essentially 'calendar time' – before it will be (or should be) widely trusted

As soon as Sapling activates, its cryptography and implementation will be subject to the risk of attack. This is unavoidable. Of course individual users can choose to limit their exposure, but that doesn't really affect how we think about the systemic security risks. There may be options to turn off the new circuit in an emergency, but those become less and less useful as legitimate Sapling transactions accumulate after the activation. Depending on details of any flaw, its exploitation may or may not be detectable in previous transactions, and if it is not then it's unclear how to recover. In other words, we have to get the crypto for Sapling right, just as we had to at launch.

> * ZEC-holders may not be generally aware of the need to migrate balances regularly; despite prior indications to that effect from both ZCo & @zookozcash, it is a very different model from both traditional currencies & more-well-known cryptocurrencies.

This is certainly not without precedent in fiat currencies; actually, it happens quite regularly. The UK just phased out all existing paper £5 notes (in favour of polymer notes), for instance, and it is [planned to do the same in 2018 for £10 notes](http://www.bankofengland.co.uk/banknotes/Pages/withdrawn/default.aspx). (Technically, the Bank of England still allows exchanging the old notes, but most people don't know about that.) There was little controversy as far as I'm aware. Of course, expectations about cryptocurrencies may be different to expectations about fiat currency; also, the analogy between withdrawing £5 notes and withdrawing Sprout notes is imperfect.

**Comment by gojomo** [comment]
Even if ZCo, for practical purposes, may be both "all-in" at the moment of Sapling activation, and extremely confident in Sapling's readiness, I see most outsiders as using a "wait-and-see" evaluation on anything so novel & precedent-breaking. Unable to personally evaluate its security, and also limited in their ability to even know which experts to trust, their heuristic is based more on observed-longevity, accumulated-reputation, and social-proof. (Especially: have others already taken the novelty-risk, and survived? And for how long?)  

Giving users more time to observe its actual operation, before forcing them to migrate at risk of loss-of-idle-funds, would increase their confidence in the system. 

Of course fiat banknotes are sometimes retired, but it's only basket-case, conquered, or anti-privacy regimes that make old notes worthless on a rapid schedule. I don't think any North American currencies have declared any notes valueless in any living person's memory. Old Mexican pesos, retired in 1993, can still 24 years later be redeemed at the fixed rate of 1000:1 for current pesos. In the EU, there was 9 years' warning before new notes/coins arrived in 2002, and redemption of all old notes for another 9+ years, and most of the old currencies still remain exchangeable-for-Euros today. 

In the mentioned recent Bank-of-England action, the old £5 notes retain their full value on exchange. But even if they didn't, being caught with a few worthless £5's on-hand has little similarity to irreversible loss of arbitrarily-large ZEC balances.

A better recent example might be India, which tried a [surprise rapid demonetization](https://en.wikipedia.org/wiki/2016_Indian_banknote_demonetisation) of larger notes late last year, to tax & track disfavored economic activity. The chaos & unpopularity of that move suggests it's not a regularly- or cheerfully- accepted operation.

If ZEC are only held (and kept in shielded Sprout addresses) by a small circle of people who've closely been reading the ZCash tea-leaves, there'll be no surprise about a deadline to move them. 

But lower-sophistication holders, who ultimately should be very important to the system's value, likely have no idea. They'll need prominent repeated warnings, and benefit from longer deadlines. And even if currently there are very few people in this class, setting a precedent of consideration for their low-attentiveness is important for the next wave of adoption. Ultimately maybe software auto-migrates between Z-realms, but even then, there'd need to be education about how often such software must be updated and run-to-network-synchronization. Users should understand: "ZEC balances are like [Tamagotchi](https://en.wikipedia.org/wiki/Tamagotchi): they might die if not fed occasional attention & CPU cycles – even while ZCash tickers signal health."

**Comment by nathan-at-least** [comment]
Let's give distinct names to some of these techniques:

- a protocol rule that prevents an address from *receiving* funds (but which may still allow spending from those addresses) is said to enact **receive-deprecation** for those addresses.
- a protocol rule that prevents *spending* from an address is said to enact **send-deprecation** for those addresses.

The fate of funds in addresses which have been **send-deprecated** is orthogonal. Possibilities (some of which are contentious, could include: destroying the funds (or permanently locking them), reallocating them, such as to miner rewards, later reverting a send-deprecation (might be useful in cases of phasing in some kinds of protocol upgrades), allowing the original owners to spend them through some other mechanism (ex: through related derived secrets that use different cryptographic primitives).

**Comment by daira** [comment]
To me "deprecation" in a technical context means saying that something is no longer guaranteed to be supported, but does not imply actually removing it (yet, or possibly at all). I would prefer we use "send-discontinuation" and "receive-discontinuation" for the action of actually preventing funds from being sent to or received from a class of addresses.

**Comment by nathan-at-least** [comment]
Note: when Sapling activates and until much later, after sufficient notice, we will not freeze or deprecate Sprout addresses.

**Comment by str4d** [comment]
It should be noted that there are two levels of *receive-discontinuation*:

- Any transaction with Sprout JoinSplits **must** have `vpub_old = 0` and `(vout.size() + sum(vsapling.vpub_old)) > 0`.
  - Can be enforced as a consensus rule, without any migration-specific transaction changes.
  - Does not prevent Sprout from being used, but *does* make it bleed ZEC.
- Any transaction with Sprout JoinSplits **must** have `v = 0` in all output notes, or that they are dummy notes.
  - Likely requires an additional circuit, and definitely requires more transaction data showing the opening of the output notes.

**Comment by daira** [comment]
Requiring v = 0 for output notes doesn't require an additional circuit; you can just decommit both output notes. A disadvantage of that approach is that it requires the total value of pairs of Sprout input notes to be revealed.

You could solve that problem by having a SproutSpend circuit that outputs a value commitment in the same way as a SaplingSpend, and then decommitting the sum of those value commitments. That would be more efficient, as well as more private, since the SproutSpend circuit wouldn't require the output side of the JoinSplit circuit, and it would presumably be using Groth16. (It would still require 34 SHA256Compress operations per Sprout input note.)

**Comment by daira** [comment]
The scope of this ticket was ambiguous, it was originally intended only to decide how the Sapling upgrade itself would handle compatibility with old notes and addresses. That decision is made; we're using option 4 with the Sprout JoinSplit circuit unchanged. Value can only be transferred from the Sprout to the Sapling shielded domain (and for the time being, back) via the transparent value pool.

For the option to migrate the Sprout circuit to Groth16, see #3071.

This ticket also has lots of valuable discussion about when to discontinue Sprout notes, but the more specific ticket about that is #2718.
