### ISSUE TITLE
BitGo hard-fork criterion 3: wipe-out protection

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2255]
https://blog.bitgo.com/bitgos-approach-to-handling-a-hard-fork-71e572506d7d

"The hard fork must provide wipe-out protection. This means, once forked, the fork should remain permanent. The software running the new fork should not be able to produce a reorganization back to the original chain, which would effectively wipe out existence of the new chain."

**Comment by nathan-at-least** [comment]
Note, this is related to #713, and in an HF0 planning meeting we realized different people had different beliefs about what this ticket means.

**Comment by str4d** [comment]
Another way to accomplish this (suggested by various people discussing Bitcoin hard forks) is to require that the sign bit of `nVersion` in the block header is set post-hardfork (ie. the version is negative). That would create a bilateral hardfork, as existing nodes require that `nVersion >= 4`. This obviously only works for a single hard fork at a time (though there isn't a case for parallel hard forks if we use block-height indication rather than in-band signalling).

In a simple implementation this would only work once; in a more complex implementation, the hard fork could require that only the forking block have the sign bit set (so future hard forks could be signalled by re-enabling that bit). Alternatively, we could introduce a more usable or intuitive mechanism in HF0, while using this mechanism for HF0 itself.

**Comment by daira** [comment]
Specified in [ZIP 202](https://github.com/zcash/zips/blob/master/zip-0202.rst) and [ZIP 143](https://github.com/zcash/zips/blob/master/zip-0143.rst) (as a consequence of the addition of the ``fOverwintered`` flag and new signature hash algorithm causing a bilateral consensus rule change, both for Overwinter and for future upgrades that update the consensus branch ID).
