### ISSUE TITLE
choose improved hash function for Merkle Tree (or replace Merkle Tree)

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#2258]
Zcash version 1 (“Sprout”) uses SHA-256-compression-function for the secure hash function for the Merkle Tree accumulator, and uses SHA-256, SHA-256-compression-function, or BLAKE2b in other places.

The Merkle Tree accumulator is by far the biggest cause of the [RAM](https://speed.z.cash/timeline/?exe=1&base=1%2B9&ben=memory+createjoinsplit&env=1&revs=1000&equid=off&quarts=on&extr=on) and [CPU costs](https://speed.z.cash/timeline/?exe=1&base=1%2B9&ben=time+createjoinsplit&env=1&revs=1000&equid=off&quarts=on&extr=on) of generating shielded transactions.

For Zcash v2 (“Sapling”) there are three candidates for a secure hash function which is more efficient to compute inside the SNARK prover:

* [Pedersen commitments](https://github.com/zcash/zcash/issues/2234): Huge feature: there is a security reduction (sometimes confusingly called a "security proof", by cryptographers) from Pedersen commitment to discrete log, which is (a) a gold standard of math-y crypto and more importantly (b) something that we already rely on. So we wouldn't be vulnerable to _more things that could go wrong_ if we replaced a hash function with Pedersen commitments. (Although there could potentially be different or worse _consequences_ if discrete log were broken in our groups in practice. See the ticket for thorough detail.)
* [MiMChash](https://github.com/zcash/zcash/issues/2233): New. Good performance. Designed for this sort of usage. Has at least a little bit of peer review. This is from the "symmetric" style of crypto (in contrast to the "math-y" style of Pedersen commitments) — a style which I (Zooko) have a particular fondness for.
* [subset-sum hash](https://github.com/zcash/zcash/issues/40): Old. Good performance. More peer review, I suspect, because it is older. Has a connection to classical math-y puzzles (subset sum) although I don't know at the moment if there are any useful security reductions for it.

Then there is a "out of left field" idea from Daira: [get rid of the Merkle Tree entirely](https://github.com/zcash/zcash/issues/2134). We could use a different accumulator! I haven't started going through the catalog of options to evaluate them for this. Hopefully the "Zcash-TNG" research team is looking at that.

Okay, to close this ticket, write a summary of the probable performance and probable security consequences of these options (including figuring out how many options there _are_ for non-Merkle-Tree accumulators and if any of them are worth evaluating).

This would make a nice white paper, blog post, science paper or something like that, if anybody has time to to provide the necessary context and coherence.

**Comment by daira** [comment]
Let's discuss this at the next Sapling meeting. I suspect the decision will be to go with Pedersen hashes. (Note: not the same thing as Pedersen commitments, although it will then make sense to go with Pedersen commitments in other parts of the circuit as well.)

**Comment by khovratovich** [comment]
The subset-sum hash may be vulnerable to an attack based on the [generalized birthday problem](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.399.4546&rep=rep1&type=pdf), from which Equihash rose (the idea is to increase the number of zero bits in a tree node level by level until a collision is found). The attack is usually applied to fields of characteristic two, but I would not be surprised to see it working for prime fields as well, at least for some primes. 

Said that, I am pretty sure that lightweight hash functions should easily stop this attack from working if the lowest tree level is still operating with full-scale hash functions (SHA-2/3, Pedersen, or MiMC). For example, one may use the 128-bit [SipHash ](https://github.com/veorq/SipHash/blob/master/siphash.c) there or something else. SipHash in its 128-bit version is about 8 times faster than Blake2b, and I think this can be further improved. I can not calculate the exact number of constraints for zkSNARKs as I am not yet mastering the technique, but hope we can do this collectively.

Note that some lightweight hashes (denote them by HL) have reduced collision security, like 64 bits. I am not sure if this is can be exploited if only the inner tree layers use HL. Indeed, to make a coin collision, one would need to produce colliding inputs to HL which are at the same time secure hashes of valid coin commitments to be exploitable. Thus mere collisions for inner layers are not sufficient for coin doubling. I hope to formulate a weaker property for inner hashes in the Merkle tree, closer to preimage resistance, which would allow smaller or reduced-round hash functions to be used.

**Comment by daira** [comment]
While it's technically correct that a collision in the internal hash would be made more difficult to exploit by having to match a note commitment at the leaf, I believe we can't risk using a lighter-weight internal hash given the severity of the consequences of forgery.

Pedersen hashes are provably as secure for collision-resistance as the Discrete Logarithm Problem on the Jubjub curve, which we'll also be relying on for the note encryption and for the one-way function from spending keys to addresses. A Pedersen hash can be implemented in [1881 constraints](https://github.com/zcash/zcash/issues/2234#issuecomment-338985293) (which is 11.2 times more constraint-efficient than BLAKE2s at [21056 constraints](https://github.com/zcash/zcash/issues/2630#issuecomment-336887601), and 14.6 times more constraint-efficient than SHA256Compress at approximately [27536 constraints](https://github.com/zcash/zcash/issues/426#issuecomment-179296593)).

Subset-sum hashes are no more constraint-efficient than Pedersen ([1923 constraints](https://github.com/zcash/zcash/issues/426#issuecomment-179296593) for a subset-sum hash of dimension 5) and we have less confidence in them, so they can be eliminated from consideration. In fact I already closed that ticket (#40) in July.

The best variant of MiMC is [2.92 times faster than Pedersen](https://github.com/zcash/zcash/issues/2233#issuecomment-291854536) for hashing, and has not yet been eliminated. However, given the limited amount of public cryptanalytic attention on MiMC, at this point I think it's almost certain we will be using Pedersen hashes and commitments for Sapling, unless something very unexpected comes up.

**Comment by daira** [comment]
@khovratovich wrote in https://github.com/zcash/zcash/issues/2630#issuecomment-341077012 , in response to an analysis of the performance cost of Skein-{256,512}:
> A full Skein is clearly an overkill. As it is slower than Blake2, it inevitably requires a bigger circuit.

I replied:
> @khovratovich : Remember that we don't only need a secure hash; we need to convince people that we have a secure hash (for the particular usage). Reducing the number of rounds is a hard sell, and would inevitably lead to accusations that we'd compromised on security, even if the reduction can be justified cryptographically. Also note that the main point of doing this cost analysis is to exclude candidates. We can now definitively exclude Skein and Keccak/SHA-3 in favour of BLAKE2s.
>
> If we're going to fiddle with numbers of rounds, then I'd much rather increase the number of rounds of MiMC than reduce the number of rounds of Skein, Keccak or BLAKE2. MiMC, in the [LongsightF-322/p/3](https://github.com/zcash/zcash/issues/2233#issuecomment-292807839) variant, requires only 644 constraints! That's 32.7 times cheaper than BLAKE2s; we could multiply the number of rounds by 10 and still be cheaper (or multiply it by 2 and still be cheaper than the Pedersen hash).

@khovratovich in https://github.com/zcash/zcash/issues/2630#issuecomment-341221160 :
> @daira I do not suggest using an insecure hash as is, I rather suggest using something more constraint-efficient than the Merkle tree. I think one do not need full hash functions in the nodes of a collision-resistant hash function with logarithmic commitment witnesses, like we do not need such for PMAC or GCM.

As you know, there is a security reduction of the collision resistance of a Merkle tree [Merkle1987] to the collision resistance of its underlying hash. In [this post](https://tahoe-lafs.org/pipermail/tahoe-dev/2010-July/004587.html) (describing a hash-based signature scheme which eventually became [SPHINCS](https://sphincs.cr.yp.to)), I explained why collision resistance is required:

> [Zooko asked](http://allmydata.org/pipermail/tahoe-dev/2010-June/004439.html) why the original Merkle tree construction, [Merkle1987], can't be proven secure (that is, to preserve the second preimage resistance of the hash it is based on) without assuming that the hash is collision resistant.
>
> First, note that the applicable security property is the eSec variant of second preimage resistance, since the input is not random as it would have to be for the Sec or aSec variants. (In general, the attacker chooses the inputs at the bottom level of the tree. Also, the output of the hash is not random because that's not implied by any of the properties studied in [RS2004], so neither is the input to the next-higher level.)
>
> So, we are looking for a tree hash that preserves eSec/TCR. Section 5.1 of [BR1997] explains why the Merkle-Damgård construction does not preserve this property in the case of a linear hash. Basically, it's because iterating the hash might result in violating the assumption that the input to later iterations is independent of the seed. The counterexample used to show this is completely contrived, but it's enough to show that security is not preserved for an arbitrary eSec compression function. The same counterexample also shows why the Merkle tree construction (with the same seed used for all of the hash applications) does not preserve eSec.

There have been various proposals for Merkle-tree-like constructions that aim to depend on weaker properties of the underlying hash, such as XOR trees [BR1997] or their improvements [Mironov2001], or SPR-Merkle trees [DOTV2008]. However, we looked closely (@zooko and I, independently) at whether it was possible to use any of these constructions in Zcash, and were not able to find a way to apply them to the Zcash commitment accumulator in a way that allowed relying only on a weaker hash property. The main sticking point is that all nodes have to be able to compute the effect of adding a commitment to the tree noninteractively and deterministically. (It may actually still help to use XOR or SPR trees even if they are deterministic, but it doesn't allow proving security based on a weaker property.)

Note that for a reduced-round variant of a conventional "bit twiddling" hash to be competitive with either the Pedersen hash or MiMC, even if we could rely on a property weaker than full collision-resistance, the original hash would have to start with a *huge* security margin for that property. For example, since Pedersen hashes are 11.2 times more constraint efficient than BLAKE2s, it would have to be the case that BLAKE2s had an 11.2 times security margin in terms of number of rounds (for whatever security property is needed), in order for a reduced-round variant of it to be competitive. And this is extremely unlikely to be the case given known attacks on BLAKE2s, or other similar hashes. But for the sake of argument suppose that were true, and the Merkle tree construction were changed to make less stringent demands on the hash function. Then it would still be difficult to make a convincing case for the security of that approach in the time available to design and analyse Sapling, because it would have to compete with the fairly straightforward reduction of Pedersen hash security to the hardness of DLP on the Jubjub curve, an assumption that we are relying on in any case.

Universal hashes can be made very circuit-efficient (see https://github.com/zcash/zcash/issues/406#issuecomment-190251511 which estimates 388 constraints per 16 bytes of input for Poly1305, which is 1552 constraints per 512 bits. (Note that Poly1305 authenticators are usually encrypted and this estimate does *not* include the cost of any encryption.) So that would be a possibility if there were a *deterministic* tree construction for which universal hashing alone were sufficient. I'm not aware of any such construction. (As pointed out in https://courses.engr.illinois.edu/cs598man/fa2014/slides/11.pdf , you can extend the domain of a UOWHF by using a tree with independent hashes at each layer. However, the overall tree hash is still only a UOWHF which is not sufficient for the Zcash accumulator.)

Also note that as I pointed out in https://github.com/zcash/zcash/issues/2630#issuecomment-341112492 , we can meet the performance goals of Sapling just with Pedersen hashes/commitments and BLAKE2s. Squeezing more performance out of the Merkle tree will have diminishing returns as the hashes in the rest of the circuit (which cannot use Pedersen as explained in https://github.com/zcash/zcash/issues/2630#issuecomment-341121797 ), come to dominate.

<hr>
[Merkle1987] Ralph Merkle,
"[A Digital Signature Based on a Conventional Encryption Function](https://people.eecs.berkeley.edu/~raluca/cs261-f15/readings/merkle.pdf),"
In proceedings of CRYPTO '87: Lecture Notes In Computer Science Vol. 293, pp 369-378, Springer-Verlag 1988.

[BR1997] Mihir Bellare and Phillip Rogaway,
"[Collision-Resistant Hashing: Towards Making UOWHFs Practical](http://cseweb.ucsd.edu/~mihir/papers/tcr-hash.html),"
July 17, 1997.

[Mironov2001] Ilya Mironov,
"[Hash Functions: From Merkle-Damgård to Shoup](http://www.iacr.org/archive/eurocrypt2001/20450165.pdf),"
Proceedings of Eurocrypt 2001, pp. 166-181.

[RS2004] Phillip Rogaway and Thomas Shrimpton,
"[Cryptographic Hash-Function Basics: Definitions, Implications, and Separations for Preimage Resistance, Second-Preimage Resistance, and Collision Resistance](http://eprint.iacr.org/2004/035/),
Full version, 2004.

[DOTV2008] Erik Dahmen, Katsuyuki OKEYA, Tsuyoshi TAKAGI, and Camille Vuillaume,
"[Digital Signatures Out of Second-Preimage Resistant Hash Functions](https://www.cdc.informatik.tu-darmstadt.de/~dahmen/papers/DOTV08.pdf),"
In Post-Quantum Cryptography, Lecture Notes in Computer Science Vol. 5299, pp. 109-123, Springer-Verlag 2008.

**Comment by khovratovich** [comment]
Thank you for the links! Note however that these proposals do not discuss a different structure for the Merkle tree. They also largely discuss keyed hash functions, which is not our case (and which is not necessary for many protocols [1]). That's why I think UOWHFs and their relatives are not of our concern, as we can safely live without them. 

The idea is to use another collision-resistant construction instead of all but lowest level of the Merkle tree. Precisely, let M1, M2, ... Mn be inputs, then the accumulator can be G(H(M1), H(M2), ... H(Mn)), where G is a fast-update hash function with logarithmic-size proofs. G may be collision-resistant but does not have to, as its inputs are unpredictable to the adversary and can be replaced by random oracle calls (or an unkeyed hash function like in [1]).

One can imagine various designs for G. For example, it can have a compressing SPN structure with properly chosen affine and nonlinear layers, which would guarantee an upper differential bound following the wide trail strategy [2] as well as resistance to truncated differential attacks.

>@daira If we're going to fiddle with numbers of rounds, then I'd much rather increase the number of rounds of MiMC than reduce the number of rounds of Skein, Keccak or BLAKE2. MiMC, in the LongsightF-322/p/3 variant, requires only 644 constraints! That's 32.7 times cheaper than BLAKE2s; we could multiply the number of rounds by 10 and still be cheaper (or multiply it by 2 and still be cheaper than the Pedersen hash).

I have been always questioning the idea of increasing the number of rounds "just because we can". I think it undermines the whole idea of public cryptanalysis. If there is an attack, there should be a protection. If not then there should be a security margin, but why should it be 90%? Attacks on well-studied designs do not progress that fast (for example for SHA-1, as we have just learned, they barely progress at all).

You can still use full-fledge MiMC for processing individual commitments, and a modified one for the other tree levels. It will be even faster than you calculate.

>There have been various proposals for Merkle-tree-like constructions that aim to depend on weaker properties of the underlying hash, such as XOR trees [BR1997] or their improvements [Mironov2001], or SPR-Merkle trees [DOTV2008]. However, we looked closely (@zooko and I, independently) at whether it was possible to use any of these constructions in Zcash, and were not able to find a way to apply them to the Zcash commitment accumulator in a way that allowed relying only on a weaker hash property. The main sticking point is that all nodes have to be able to compute the effect of adding a commitment to the tree noninteractively and deterministically. (It may actually still help to use XOR or SPR trees even if they are deterministic, but it doesn't allow proving security based on a weaker property.)

These constructions do not actually lighten the tree construction, even worse many of them need a keyed function - so there is no need in them.

>For example, since Pedersen hashes are 11.2 times more constraint efficient than BLAKE2s, it would have to be the case that BLAKE2s had an 11.2 times security margin in terms of number of rounds (for whatever security property is needed), in order for a reduced-round variant of it to be competitive. 

This assumes that at least a full round of Blake is needed for one tree layer, but as I said this might not be necessary.

> Squeezing more performance out of the Merkle tree will have diminishing returns as the hashes in the rest of the circuit (which cannot use Pedersen as explained in #2630 (comment) ), come to dominate.

For all circuits being as small as 1-2 iterations of MiMC/Pedersen seems to be a sound performance goal. It will be even better if no circuit is a bottleneck in SNARK generation.  

[1] P. Rogaway, ["Formalizing Human Ignorance: Collision-Resistant Hashing without the Keys"](http://web.cs.ucdavis.edu/~rogaway/papers/ignorance.pdf)

[2] J. Daemen, V. Rijmen, ["Wide Trail Design Strategy"](ftp://nozdr.ru/biblio/kolxo3/Cs/CsLn/Cryptography%20and%20Coding,%208%20conf.(LNCS2260,%20Springer,%202001)(ISBN%203540430261)(424s).pdf#page=230)

**Comment by daira** [comment]
@khovratovich wrote:
> The idea is to use another collision-resistant construction instead of all but lowest level of the Merkle tree. Precisely, let M1, M2, ... Mn be inputs, then the accumulator can be G(H(M1), H(M2), ... H(Mn)), where G is a fast-update hash function with logarithmic-size proofs.

I encourage you to work on this, but it seems unlikely to be ready for Sapling. Maybe for Bamboo (the subsequent circuit change) or another later update.

**Comment by daira** [comment]
We will be using Pedersen commitments (#2234).

**Comment by zooko** [comment]
I do too!
