### ISSUE TITLE
Auto-senescence

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2274]
Add a feature to our software that *by default* causes the node to exit with an error once it is too old, as defined by an explicit public deprecation policy. I prefer allowing users to disable this feature with a configuration setting, because the intent isn't to force them to do anything, but just to ensure that all users know they should upgrade or opt-out.

**Comment by radix42** [comment]
As long as it spits out a useful error message about needing to upgrade to BOTH stdout and debug.log, that sounds good. I've seen some users habitually only check one or the other when things go wrong.

**Comment by str4d** [comment]
The configuration setting for opting-out should be something like `-disabledeprecation=1.0.9`, so that if a user upgrades they need to explicitly re-opt-out. This is fine IMHO because:

- Upgrades could introduce or change functionality that affects the user's reason for disabling deprecation.
- Upgrades (in the cases this is relevant for) require user intervention already; if the user's node is auto-upgrading, it won't ever hit deprecation.

**Comment by nathan-at-least** [comment]
BTW- we're considering defining auto-senescence deadline in terms of absolute block height. This has two advantages (at least): not dependent on local clock (or ex NTP attacks), and it also allows us to coordinate protocol upgrade schedules based on block heights.

**Comment by bitcartel** [comment]
Rather than exit, perhaps after a certain age the node should display a suitable message in the console, metrics screen and also fall into RPC safe mode.  Less scary than an exit for end users.

**Comment by daira** [comment]
And disable mining.

**Comment by radix42** [comment]
and somehow indicate in json results that it is in that state and why, for wallets connected to that node to know tell that to someone

**Comment by str4d** [comment]
@bitcartel I don't think the proposal was for an abrupt exit, but to effectively be a call to `Shutdown()` (so files get flushed and closed, etc.) and then a block during startup that checks for deprecation.

Whether I lean towards auto-shutdown or not depends on the deprecation timescale. I'm currently more in favour of auto-shutdown than against, but if we didn't implement auto-shutdown then I agree it should be strictly more of an effect than if we had sent an alert that put the RPC into safe mode - otherwise, we could just do all this with alerts. (In fact, we still could, by defining a higher alert level, but IIRC we dismissed that idea in a meeting.)

**Comment by str4d** [comment]
I'm going to go ahead with implementing the apoptosis variant of senescence, which should be mostly pre-cursor work to safe-mode-style deprecation.

**Comment by bitcartel** [comment]
Some nodes are running on headless servers in the cloud.  They may be left running without any further human interaction, in order to support a function e.g. explorer.  The user may not be checking for warning or deprecation messages in `getinfo`.  As @radix42 mentions, we should consider a way to communicate the change in state from normal to deprecated (assuming rpc safe mode and not shutdown).

**Comment by daira** [comment]
See also #2268 (How to report serious errors in a way that reliably attracts node operators' attention).

**Comment by bitcartel** [comment]
In the world of shrink-wrap software, you can still run old versions of Turbotax.  Users are reassured that they can still access their old data.  It might be scary for users if they are not able to launch the software to export their private keys and obtain transactional data stored locally.  They may decide that they do not want to run the latest version of zcashd for some reason.  They maybnot want to upgrade in order to access their data.  So I am now against having this feature auto shutdown.  We will have to look at RPC safe mode to see what functionality a user can still perform and consider if there should be another mode.

**Comment by daira** [comment]
@bitcartel wrote:
> They may decide that they do not want to run the latest version of zcashd for some reason (technical, political, etc), so upgrading in order to access their data is not an option.

As far as I understood the proposed design, they would always be able to stick with an older version by setting a config field (once each time they upgrade).

**Comment by bitcartel** [comment]
Having to update a config field each time adds friction to the upgrade process.  One more thing to remember.  Having `disabledeprecation` be a boolean option might be easier for end users.

I quite like the idea of having an option like `deprecationpolicy=...`  which accepts values:

- none = do nothing (just like now)
- warning (default) = show deprecated/unsupported warnings in results of rpc commands, metrics sceren etc
- safemode = put node into safe mode when deprecated
- shutdown = shut down node when deprecated

This way, the user is in control and can decide what happens, rather than having the software behave in a way they did not expect, as they did not read the documentation, update a config file etc

**Comment by radix42** [comment]
I very much like this idea, @bitcartel

**Comment by daira** [comment]
Perhaps the node should exit with an error message on startup if the -disabledeprecation setting is present but does not match the current version. Then the node operator is required to make a choice of whether to enable/disable deprecation each time they upgrade.

**Comment by samsmith** [comment]
I’m unclear on the wisdom of having an automated calendar based deprecation cycle, when there is a manual release process in which reality can intervene.

Rather than hard-coding it to 4 months (ie after 3 intermediate releases), auto-senescence could use information from the chain itself to determine when the client is now too old (and then either exit, warn, or carry on regardless) rather than a hardcoded/predefined date.

Whether you deprecate via a signed message on a chain, detecting newer version numbers of daemons, or block numbers, is something that I leave as an implementation detail.

It would allow you to change the behaviour of deployed code, without having to be locked into past decisions, in the way a calendar deprecation schedule locks you in. Because you guys deserve time off over xmas, and that then screws up your schedule at least once a year.

In the case of a remotely executable vulnerability, or consensus failure, you can simply age out all past clients or drop them into a read-only mode; and this mechanism should also work for third party z-cash clients, and delayed-but-automated upgrade processes.

**Comment by nathan-at-least** [comment]
> Rather than hard-coding it to 4 months (ie after 3 intermediate releases), auto-senescence could use information from the chain itself to determine when the client is now too old (and then either exit, warn, or carry on regardless) rather than a hardcoded/predefined date.

We plan to use block height, not actual dates as per https://github.com/zcash/zcash/issues/2274#issuecomment-295297796. However, note that for *this feature* the timing doesn't have to match the policy. For this feature I propose we lock down the node based on a block height that has a very high probability of occurring sometime after the 'deprecation date'.

> Whether you deprecate via a signed message on a chain, detecting newer version numbers of daemons, or block numbers, is something that I leave as an implementation detail.

These options have important differences. We're going with block numbers. A signed on-chain message leaves us in control of deprecation as a centralizing force, which we are largely motivated to move away from. (Note: we still retain control over the in-band alert keys, which are still such a centralized control, so I'd like to deal with those separately someday.) Relying on version numbers opens the protocol to various malicious attacks, such as connecting a bunch of nodes with a 'fake' new version to trigger existing nodes to drop out.

**Comment by nathan-at-least** [comment]
@bitcartel: I don't think shutting down is scary. It happens all the time with all kinds of server software for all kinds of reasons. A segfault is scary, but an orderly shutdown with an error message is not.

In fact, several of my zcash nodes just did an orderly shutdown because the disk was full. If instead they kept running but failing to update indexes and returning some RPC results but not others, I wonder how long it would have taken me to realize what the problem was?

Anyway, this is just my own opinionated stance on UX, and I don't mean to impose it as a design requirement. I'm like -0.5 on having more options for behavior on the general rule that more config options means more complex behavior in the wild, so when we're helping users with bugs or problems there's just that many more cases to analyze.

**Comment by nathan-at-least** [comment]
Actually I think this was disingenuous:

> In fact, several of my zcash nodes just did an orderly shutdown because the disk was full. If instead they kept running but failing to update indexes and returning some RPC results but not others, I wonder how long it would have taken me to realize what the problem was?

In truth, I ran a `zcash-cli` command, and it reported that there was no server response, so I looked at the log, saw orderly shutdown messages, and then scanned back to see:

```
2017-05-02 23:48:35 *** Disk space is low!
```

In fact, if `zcash-cli` had just immediately said 'error: disk space is low' it would have *saved* me time, so my argument doesn't pan out in this case. ;-)

**Comment by nathan-at-least** [comment]
Pondering a bit more if there were a 'safe mode' that would block *all* RPC calls and *always* return an error message with a clear description, that's what I would prefer.

If safe mode *only* blocks *some* calls, I consider it dangerous. What if a block explorer is using unfrozen methods, but that node is now on a minority fork without realizing it? People relying on that block explorer might make faulty decisions, etc… The impact is harder to predict.

**Comment by bitcartel** [comment]
I think this feature should be disabled by default as it goes against the grain of what users _expect_.  There are few (any?) examples of software doing what we're proposing.  It's also a short-term fix in lieu of providing users with an option to auto-upgrade, which users are familiar with.

Also, shouldn't this feature be considered an "experimental"?
