### ISSUE TITLE
Design hard fork activation mechanism

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2286]
This should satisfy the BitGo criteria (#2253, #2254, #2255), and preferably should not reinvent the wheel wrt upstream.

**Comment by nathan-at-least** [comment]
Because we have auto-senescence (see #2297), I propose a simple signalling mechanism which is to release software that activates new rules at a block height `H`, which is chosen such that the oldest release we've made which does not have that rule has auto-deprecated.

**Comment by nathan-at-least** [comment]
Note, we intend to do 'bilateral hardfork', so I believe if the rule is that at block height `H` and all future blocks *must* distinguishably use the new rules and *must not* be acceptable to nodes which do not adopt the new rules.

**Comment by daira** [comment]
Reminder to self to post comment about the distinction between block-bilateral hardforks, and transaction-bilateral hardforks.

**Comment by nathan-at-least** [comment]
We agreed in an HF0 planning meeting now to commit to https://github.com/zcash/zcash/issues/2286#issuecomment-301625612. There's an open question about if we want to do network partitioning, and how, to improve safety.

**Comment by nathan-at-least** [comment]
I claim this proposal fulfills two of the BitGo requirements:

- #2253 The activation mechanism is on chain, and the grace period is 'three releases.' If you don't want to follow the hardfork, you need to patch your software or downgrade withing three releases.
- #2255 wipe-out protection, so long as it is impossible to be confused whether a block at height ≥H belongs to one set of rules or the other. (Does this imply we need a requirement such as block header changes?)

I believe this proposal _does not_ provide for:

- #2254 replay protection: I see this as orthogonal to the activation logic, and we should follow up with a separate ticket.

**Comment by nathan-at-least** [comment]
See https://github.com/zcash/zcash/issues/2286#issuecomment-301625612 for rationale on the ticket title change.

**Comment by nathan-at-least** [comment]
The plan for Network Upgrade 0 looks like this:

- define in advance an activation block height `H`, which means transactions in block `H` _must_ follow new rules.
- we use a modified-FORKID scheme from #2584 so that transactions _must_ follow the new rules starting at block `H`. Therefore, as soon as block `H-1` is connected (or locally generated) we can empty the mempool (which is full of transactions which follow the old rules).

There will probably be other important activation details we need to spec out for this ticket.

**Comment by nathan-at-least** [comment]
In terms of replay protection and version:

- The ticket in #2584 for replay protection.
- The version field of transactions will be used "simply" to identify transaction serialization format (and the implied semantics) and it will not be used for replay protection or other kinds of "safety".

  + Avoid using versions that are already used by Bitcoin. Even though the networks are partitioned, the same tools may parse Bitcoin and Zcash transactions. Check for standards for "cross-chain" transaction safety for cases like this.

**Comment by nathan-at-least** [comment]
Transaction versioning and #2584:

- After a discussion we decided it would be best to reuse the same `FORKID` value in both the #2584 signature hash *and* the transaction serialization in the versioning field.
- The `FORKID` is required to be a 32 bit value and the msb is required to be `1`. Furthermore, each time there is an upgrade, the value is chosen by the developers of the upgrade.

  + **Governance Note:** If developers propose a `FORKID` that collides with existing ones including those in alternative proposed upgrades, that endangers users by endangering replay protection, so users should only adopt proposed upgrades that don't collide. Even if there are two contentious dev groups proposing mutually exclusive upgrades with no neutral coordinating authority, they should be able to find non-colliding `FORKIDs`.
- The serialization format of transactions starting with NU0 must begin with exactly the `FORKID`. Because the msb is `1`, existing Zcash tools and pre-NU0 Zcash tools will consider this an invalid version field. (Additionally, existing Bitcoin tools and many alt coins will hopefully also reject.)

Note, because the `FORKID` appears in both the signature personalization of #2584 and the serialization format, this means *every* network upgrade will require updating all parsing tools. Because we already intend on doing #2584 for replay protection (among other benefits), any tool doing signature validation would already have to have been updated. We consider the benefits of requiring these two fields to reuse the exact same value to outweight the cost of requiring parser upgrades for every network upgrade.

(We'd love to hear from evosystem developers such as hardware wallets, block explorers, light wallets, etc… if ths seems onerous.)

**Comment by bitcartel** [comment]
In meeting with @daira @arielgabizon today we discussed idea above and came up with the following design for the transaction format.

```
[  tx version field ]...[              new fields           ]
[msb | tx version ]...[ FORKID ] [ expiry height ]
1 bit       uint31             uint32          uint32
```

This enables a given fork FORKID to support multiple tx formats.

We can set the tx version set to 3 for this new format.

When computing tx version internally, the msb is masked off, so the tx version is effectively always positive (making it easier to update existing tests and conditional logic which uses > comparison).

**Comment by arielgabizon** [comment]
Also, if in `signatureHash`  we hash `FORKID` which is explicitly part of the tx now, that already gives the personalization of the fork in the signature.

**Comment by str4d** [comment]
> This enables a given fork FORKID to support multiple tx formats.

If we want to do this, that's fine, but we would need to specify exactly how multiple versions will be handled - otherwise we either end up in the same current situation, where we can't actually use the version as a good transaction format indicator, or we end up requiring network upgrades to enable new transaction formats, in which case the hard-coded `BRANCH_ID` separate from the transaction version is basically pointless.

> Once NU0 activates, the tx version is 3.
>
> When computing tx version internally, the msb is masked off, so the tx version is effectively always positive (making it easier to update existing tests and conditional logic which uses > comparison).

This is a clever idea, but will only work if there has never been a transaction in the Zcash blockchain with a version of 3 or greater. It also makes it sound like the plan is to still switch on transaction version, rather than `BRANCH_ID` (which would explain why you are appending the fields to the end, instead of inserting the `BRANCH_ID` after the version)? That doesn't seem like a good idea to me, given that the primary reason for including the `BRANCH_ID` in the transaction format is to defend against future version numbers colliding across branches, at which point version comparison won't be sufficient to determine the correct parser.

> Also, if in signatureHash we hash FORKID which is explicitly part of the tx now, that already gives the personalization of the fork in the signature; so I wonder if that seems sufficient to @str4d as the personalization mechanism.

No, this is insufficient: you would also need a separate consensus rule to enforce that blocks only contain transactions containing a `BRANCH_ID` matching the current branch you are on. With the personalisation approach, we don't need an additional consensus rule, because the rule validating the signatures is sufficient. That said, we'd probably add that rule anyway for performance reasons (to reject blocks before signature validation).

Note that in the previous proposal (where the `BRANCH_ID` was used as the transaction version) we discussed this, and still agreed that proper personalisation of the signature hash (with the nodes passing in their current `BRANCH_ID`) was a good idea.

**Comment by str4d** [comment]
In a meeting, we clarified that if we specify `BRANCH_ID` separately to the transaction version, it would go immediately after the version:

```
[msb | tx version ][ BRANCH_ID ]...
```

We also debated going with this format vs just using the `BRANCH_ID` as the transaction version. The latter only allows transaction format changes at network upgrades, while (in theory) this format enables transaction format changes without network upgrades (as "soft forks"). Given that NU0 gives us complete freedom to alter the transaction format beyond the 4-byte transaction version, if we want to enable soft-fork-style transaction format changes, we should adjust the transaction format to make this easier, having e.g. a flag byte or a zero-length array that can be added to later, but is rejected by non-upgraded nodes (ie. they accept `tx version >= 3` as the version parser for NU0, but enforce `flag_byte == 0x00` or `len(array) == 0` or something similar to provide an invariant that a soft fork could leverage.

**Comment by bitcartel** [comment]
Example of uncontroversial network upgrades:
- Pre-NU0: Old protocol version and new protocol version accept tx with tx version >= 1
- NU0 activates: tx version >= 3, BRANCH_ID = 0, empty flag_byte or array
- Sapling activates: tx version >= 4, BRANCH_ID = 1, empty flag_byte or array

Now we want to bump the protocol version and soft-fork in a minor change which requires adding 4 bytes of data to a transaction.

Should we use a flag byte or array?  I think an array would be more flexible.

Using a flag_byte, a parser would need conditional logic to check for data at the end of the raw transaction, i.e. updates to the serialization/deserialization code.

Using an array, the parser wouldn't need to do this, it could check "if tx version is 3, expect array to be empty, or ignore any elements in the array" and "if tx version is 4, expect 4 bytes of data as the first element"

Later on, for a new fork, tx version >= 5,  BRANCH_ID = 2, empty array

**Comment by str4d** [comment]
I'm thinking that this will be implemented similar to how checkpoints are implemented: we define an array of epochs, which are an array of relevant constants, and on startup those are loaded into a structure that we can access via `Params().GetConsensus()`.
