### ISSUE TITLE
RPC API zcrawpour staff

### ISSUE THREAD

**Issue by openalmeida** [zcash/zcash#2290]
```Bash
./src/zcash-cli zcrawpour 
error code: -32601
error message:
Method not found
```

**Comment by daira** [comment]
It's called ``zcrawjoinsplit`` (and is deprecated in favour of ``z_sendmany``). Where did you see the ``zcrawpour`` method name? It was [changed some time ago](https://github.com/zcash/zcash/commit/b7e4abd6f74adda0fe33b1e8cffd519f6afbe4ad).

**Comment by openalmeida** [comment]
wow, what a quickly reply
i was found some post at forum mentioned zcrawpour.
and i found changelog said it was deleted/deprecated,
when i just come back,
here comes your reply, how kind you are,
thank you so much.

btw, would you teach me what is the most right way to create raw transaction.

thanks again

**Comment by daira** [comment]
There was some documentation of how to use zcrawjoinsplit in [old versions of our Beta Guide](https://github.com/zcash/zcash/wiki/Beta-Guide/113c26de3b147e4730332fb05849a463b30893fd#protecting-your-testcoins), but note that we haven't tested those instructions for some time. Why did you specifically want to create raw transactions &mdash; as a learning exercise, or was it because there's something the higher-level API can't do?

**Comment by openalmeida** [comment]
everything under well known protocol maybe better, instead of a blackbox,
as [#2291](https://github.com/zcash/zcash/issues/2291) mentioned
about the private key create process staff.

i mean blackbox for common user, i know all about zcash is opensource,
but i am sorry about my poor C++ ability to read the sources,
otherwise i should submit pull requests instead of issue requests.

thanks a lot
