### ISSUE TITLE
Add a config option to limit the number of transparent inputs for txns accepted to the mempool

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2343]
Zcash inherits a design flaw from Bitcoin where [transaction validation takes work quadratic in the number of transparent inputs](https://bitcoinclassic.com/devel/Quadratic%20Hashing.html). We intend to solve this by adopting some variant of Flexible Transactions (#2071) or segwit (#451), probably the former. However, that cannot be done soon enough to respond promptly to critical short-term problems caused by the quadratic validation scaling, such as the ``getblocktemplate`` latency, block propagation latency, and mempool size inflation issues described in #2333. A fix that can be deployed quickly is to limit the maximum number of transparent inputs in a transaction accepted to the mempool. A config option is preferable to a hard limit.

**Comment by daira** [comment]
Implemented by #2342.

**Comment by daira** [comment]
Note that before launch we believed this would be adequately addressed by changing Bitcoin's standard-rule 100 KB limit on transaction size to be a consensus rule (#1475). That turned out not to be sufficient, as shown by #2333.

**Comment by daira** [comment]
As pointed out by peter_zcash on #zcash-dev, limiting the number of inputs for transactions accepted to the mempool, as opposed to just mined transactions, is necessary to address mempool size inflation and validation cost.

**Comment by nathan-at-least** [comment]
This would introduce a default policy, user-configurable. We discussed in 1.0.9 planning meeting about potential sharp edges here. There is one potential UX sharp edge here:

A user makes an RPC call that creates a transaction which would be rejected by this policy, then they're confused why their txn wasn't propagated or mined.

Note, if it propagates and doesn't get mined, this is potentially worse, because a node could detect if propagation fails locally, but not why transactions won't be mined. Also, in that case, non-minable transactions would probably accrue in the mempool.

There are a variety of ways this could happen:

* The implementation of this ticket doesn't cause the RPC interface to fail even though the transaction is rejected by the local AcceptToMempool policy. (This can be addressed by the patch and should be.)
* The user hasn't upgraded their node, but *all* their neighbors have, so their node doesn't know about the new policy, but their transaction is not relayed (which *could* be detected locally, but I doubt there's good feedback for this case).
* The user hasn't upgraded their node, and at least some of the neighbors accept the transaction (eg: they also haven't upgraded), *but* all miners have upgraded, so the transaction will not get mined.

**Comment by nathan-at-least** [comment]
Despite the UX issues I just posted, @daira, @arcalinea, and I believe it's the best option to deploy this feature in 1.0.9 and start improving user feedback about failed transaction propagation or mining subsequently.

**Comment by daira** [comment]
A saving grace for the usability issues mentioned above is that after implementing FlexTrans (or segwit, but I prefer FlexTrans), we won't need this restriction and can just remove it.

**Comment by zookozcash** [comment]
Red flag: Nathan mistakenly thought that the Incident Response team had required this ticket to be prioritised for 1.0.9. In fact the opposite was true, the Incident Response team (me as Executive Coordinator) had decided that we would take steps to fix the problem in the short term _explicitly under the assumption_ that this would not imply that this ticket would be prioritised for 1.0.9.

**Comment by bitcartel** [comment]
> This would introduce a default policy, user-configurable

@nathan-at-least PR #2342 doesn't introduce any new policy.  The user must explicitly specify the option with a value to be used as the input limit.  If the user doesn't specify the option in the config file or command line, then nothing happens i.e.:the limit checking code is never run, so current behaviour continues..

**Comment by daira** [comment]
@bitcartel and @zookozcash : the current patch is not enabled by default, but I strongly believe that making this enabled by default, with a sufficiently low default limit (e.g. 40), is necessary to address serious denial of service vulnerabilities. The longer we leave it out, the longer Zcash will be subject to those vulnerabilities. Whether it goes into 1.0.9 depends on the release manager's assessment of whether it's ready &mdash; which it probably can be, since the test is easy to write.

**Comment by nathan-at-least** [comment]
After reviewing this idea more I am against including this in zcashd. This is a short term duct-tape protection against DOS that will accrue technical debt. Furthermore, I believe it has a high chance of becoming a 'default policy by status quo'. Bitcoin is already full of multiple layers of 'solutions' like this.

I advocate addressing the underlying problems directly in the longer term, rather than adopting short-term mitigations that accrue technical debt. If there are future backlogs and the network grinds to a halt of fails, I will take full responsibility for this decision. You can link to this comment. ;-)

In my opinion, good long term solutions start from the assumption that no traffick pattern of valid transactions should be considered a 'DOS' in a malicious sense, and instead we should treat all high load transaction patterns as if they were legitimate high use. My reasoning is that we want to prepare for legitimate high scale use. So, assume the 'natural' or legitimate use is very high, then what goes wrong and how can we improve that most elegantly?

- giving users sufficient feedback to know when there is a backlog so that it's easy for them to know that's the network status. Examples could be public backlog graphs. It's especially important to give third-party services/products the ability to refer *their* users, to take the burden from them (eg: Jaxx or Kraken should be able to say 'It's a zcash network problem, not us, see: <link>'.
- introduce mempool size limits to protect nodes from crashing due to memory exhaustion.
- introduce transaction expiry by blockheight, so that when there is high load on the network, users know their transactions have failed and can then decide how to proceed. (We can't make that decision for them!)
- introduce better fee mechanics.
- improve 'vertical scaling': make our software more efficient at verifying full blocks.
- improve 'protocol scaling': make our protocol support a higher transaction throughput rate (and balance this against competing goals such as full node operational cost).

**Comment by bitcartel** [comment]
> 'default policy by status quo'

The PR associated with this ticket doesn't create a default policy.  The user must opt-in to and they must set their own personal limits - there is no default value.

> short term duct-tape protection 

Think of it as tool which is useful when circumstances call for it to keep things moving along.

Analogy... on family vacation with a rental car, one can attach a child's car seat using the seat-belt (satisfactory solution) if the car doesn't have the universal anchor system aka latch system for the car seat to hook onto (best solution).

**Comment by daira** [comment]
This is not intended to be a long-term solution; it's intended to be a critical short-term security fix.

Without it, the Zcash network is completely wide open to denial-of-service attacks. The fact that the recent incident wasn't a deliberate denial-of-service isn't relevant.

The only long-term fix for this specific DoS is to solve the quadratic scaling problem with the number of inputs to a transaction. When (not if) we do that, the short-term limit will go away. And it will go away completely, leaving no technical debt. Users will not thank us for avoiding some short-term ugliness if the network grinds to a halt or falls over completely.

**Comment by daira** [comment]
I wrote:
> And it will go away completely, leaving no technical debt.

This is correct, but I should mention that it is referring to the situation after the old transaction type / sighash method has been disabled, once the fix to quadratic scaling (e.g. FlexTrans) is complete.

**Comment by nathan-at-least** [comment]
Considering for 1.0.10.

**Comment by str4d** [comment]
Closed by #2342.
