### ISSUE TITLE
limit the mempool size

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2344]
Review upstream patches relating to mempool size limitation, and decide on a policy and associated config options. Generally we like random-drop policies (because they are less gameable by an attacker), but there may be variations such as weighted random-drop that may be useful to consider. Upstream tends to favour fee-based policies, but privacy and affordability considerations may discourage us from taking that route for Zcash.

**Comment by zookozcash** [comment]
Red flag: Nathan mistakenly thought that the Incident Response team had required this ticket to be prioritised for 1.0.9. In fact the opposite was true, the Incident Response team (me as Executive Coordinator) had decided that we would take steps to fix the problem in the short term _explicitly under the assumption_ that this would not imply that this ticket would be prioritised for 1.0.9.

**Comment by daira** [comment]
I believe this (and #2343) is necessary to address serious denial of service vulnerabilities, and the longer we leave it out, the longer Zcash will be subject to those vulnerabilities. Whether it goes into 1.0.9 depends on the release manager's assessment of whether it's ready (currently, we don't have a patch, so it will probably have to be 1.0.10).

**Comment by nathan-at-least** [comment]
Design Caution: Zooko and I like 'random eviction' style policies for two reasons: one is that they are conceptually simple (and therefore, hopefully the code is simple), and two is that they *should* avoid 'wrost-case' attacks. The latter would be where a more sophisticated solution could be gamed, but a random process will always make some progress regardless of gamed input.

However, I believe a random eviction of mempool contents without other changes *could*, without care, lead to a bandwidth cascade that looks something like this:

- node A mempool is too large, it evicts tx1.
- node B mempool is too large, it evicts tx2.
- node A and B discover the other has a transaction they don't currently have, so they send tx1 and tx2 via p2p protocol.
- the process repeats.

If all nodes on the network are in this state, it's easy to see how without the addition of any new transactions, there will be nonterminating bandwidth use.

It's easy to avoid this in a fairly simple manner:

- if the mempool is larger than K size, eject trnansactions.
- if the mempool is larget than L size, where L < K with some sufficient buffer, do not request new transactions when you learn about them.

Another note: random ejection isn't as simple as we'd like, because we must eject any dependents.

A further note: miners may want a different policy that's more sophisticated to maximize profit. My position is that our Zcash dev team should prioritize safety and stability, and if miners want to maximize their fee profit by making a different trade-off, they should develop and maintain their own policy. (This note is true of any design decision, whether or not we use random eviction.)

**Comment by nathan-at-least** [comment]
Given the complications with 'random eviction' above, I now favor a simpler policy and implementation: if adding a given transaction would require storing more than `MEMPOOL_SIZE_LIMIT` bytes, then do not add that new transaction.

This means old transactions are favored over new ones, and if there is a backlog, new submissions will tend to be dropped. This could be problematic if old transactions are somehow 'stuck' and could never be mined. If we implement transaction local wall-clock expiry, that is an orthogonal feature that would address 'stuck' transactions.

Finally, this policy _does not_ maximize fees. I strongly prefer simpler policies and implementations, over complex but more competitive ones. Miners who have an interest in being competitive could develop their own logic. In fact, if we tried to make something more sophisticated, successful miners will probably _still_ develop their own custom logic. Instead, we want to make the 'reference implementation' simpler and safer.

**Comment by nathan-at-least** [comment]
Hm, if there _are_ stuck transactions and some pathological or malicious case, it may be necessary for node operators to drop all txns from their mempool, or drop specific transactions. Do we have that either feature yet?

**Comment by daira** [comment]
We can't rely on transaction expiry to clear the mempool of transactions that are part of a DoS, because expiry is opt-in.

**Comment by Eirik0** [comment]
Closed by: https://github.com/zcash/zcash/pull/4145
