### ISSUE TITLE
Halt if ∑vpub_new > ∑vpub_old

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2351]
Proposal: halt if you see an *otherwise valid* block that would cause the total of all v<sup>pub</sup><sub>new</sub>, since genesis and including that block, to be greater than the corresponding total of v<sup>pub</sup><sub>old</sub>.

[Edit to take account of Sapling: this would apply to each shielded value pool. For Sapling the equivalent condition is "halt if you see an *otherwise valid* block that would cause the total of v<sup>balance</sup>, since Sapling activation and including that block, to be positive".]

This already cannot happen in the absence of a security flaw, but there is value in having a check independent of the zk-SNARK circuit, in case of a bug in the circuit, its implementation, or a compromise of the trusted setup.

In [Zcoin's inflation security incident](https://zcoin.io/language/en/zcoins-zerocoin-bug-explained-in-detail/) (page deleted; archived [here](https://web.archive.org/web/20170316185801/https://zcoin.io/language/en/zcoins-zerocoin-bug-explained-in-detail/)), its transparent monetary base ended up being larger than the total intended monetary base. (Note: despite the similarity in name, Zcoin uses an unrelated protocol and implementation to Zcash.) This went undetected for over two months (December 2016 to February 17 2017). The proposed check would detect such a case if it were to happen in Zcash.

Credit to Tezos for the idea, inspired by this text in their [overview paper](https://tezos.com/static/papers/Tezos_Overview.pdf):
> Our initial plan is to strike a compromise and integrate Zcash’s proof circuit in the protocol, but restrict its operations to a special token issued on the Tezos blockchain. This token will be convertible 1 to 1 with Tezos tokens, but the chain will keep track of how many tokens have been converted so that undetected inflation in the privacy preserving token cannot spill over onto the main token. Users who trust the security of the privacy preserving token will have full use of its functionality while those who don’t will remain protected as long as they do not make use of the privacy feature. This mechanism replicates the economic behavior of a side chain, but on a single ledger.

The check on v<sup>pub</sup><sub>new</sub> and v<sup>pub</sup><sub>old</sub> would have a similar effect but is independent of user-issued token support (#830).

**Comment by gojomo** [comment]
This seems a good idea for Z-Sprout whenever possible, but also then for each future Z-realm. 

For vividness, perhaps even block headers should explicitly declare net ZEC sums residing in (T, Z-Sprout, ...), as of the close of all their transactions. 

Does the check belong only against full blocks (locally-generated or received), or should block-generating nodes detect the error before completing such a block? If such a block is locally-generated, is the reaction completely local, or should the 'bad block' broadcast as a warning to others? 

Halt/panic seems reasonable while only Z-Sprout is available – as such a problem is likely fatal to the whole system. 

But as soon as there's more than one Z-realm, it is at least remotely possible that the system-as-a-whole might survive such a flaw – especially if most ZEC value is outside the flawed Z-realm, and another non-flawed Z-realm remains active. In such a case, the right reaction might be 'containment/warning/freeze' (as in the Tezos scenario). 

There may be a swashbuckling, "burn-the-ships-behind-us", "we-all-go-down-with-the-ship" rationale for *not* trying to survive/continue-operation beyond such a hypothetical flaw. And that might be the best way for the core team to signal confidence & commitment. But, 3rd party ZEC users might prefer a less all-or-nothing approach, even if it only saves pennies-on-the-dollar, and especially if none of their ZEC were in the flawed realm. 

(Notably it's also possible for such a bottom-line constraint violation to be detectable privately, before it's publicly known. If the public account of ZEC inside a realm falls below X, and one or more users know their own ZEC balance in that realm to be >X, they all know something has been wrong - but may only be narrowly-incentivized to evacuate some portion of their flawed-realm-ZEC, and liquidate other ZEC, rather than halting or announcing the discrepancy. Should there also be any detection-of or reaction-to this violation based on private-only additional knowledge? Or is only the global check appropriate here?)

**Comment by ebfull** [comment]
I proposed something similar to this a long time ago: https://github.com/zcash/zcash/issues/410

**Comment by daira** [comment]
Sorry @ebfull, if I'd seen that issue I would probably just have reopened it, since it does appear to be the same idea.

**Comment by str4d** [comment]
Two points raised in a meeting:

- This would be stored in the chain state, and therefore will only be enforced after a re-index.
- We could enforce this for the mempool as well. The sum total of "blockchain + valid txns in the local mempool" should still satisfy this rule. But just doing the check on the chain state is good enough for now.

**Comment by daira** [comment]
The set of mempool transactions can all be individually valid, but include double-spends.

**Comment by tromer** [comment]
Copying+extending a related chat discussion with @str4d and @dodger:

We can use a *"capped turnstile"* to limit the damage from hypothetical Sprout compromise by adding an explicit consensus rule that rejects transactions that could cause more ZEC to pass the turnstile than should be possible. Specifically, the following invariant would be checked:    
(transparent ZEC) + (total Sapling vpub_old) - (total Sapling vpub_new) <= total supply.

Transactions that would violate this would be rejected, but the node would not halt. If such a transaction is actually injected into the network, it suitable detectors would issue an alerts.

Without such "capped turnstile", faking Sprout-shielded ZEC will (arbitrarily) devalue everyone's ZEC.
With such "capped turnstile", faking Sprout-shielded ZEC would effectively steal the shielded ZEC of slow-to-transition Sprout users, but will preserve the value of Sapling-shielded ZEC.

That would also incentivize people to put their funds through the turnstile as quickly as possible, while not _forcing_ them to, if (for example) they have shielded cold storage.

**Comment by str4d** [comment]
Note that if we made this a consensus rule (whether we halt on it or not), we would need to require nodes to re-index on start (to build up the necessary chainstate).

**Comment by gojomo** [comment]
@str4d It occurs to me an re-index-from-genesis could be avoided for most nodes using a two-stage process. First, a version is made available (and indeed dominant because older versions have auto-sunset) that starts keeping a running net Sprout inflow/outflow tally from whenever it starts running. Of course, this tally is not yet sufficient to enforce the 'turnstile'. But, in the second step, at the eventual hardfork to enforce the turnstile, the software includes a community/team-verified net checkpoint tally, at block N, where N is past the time that the last version that *didn't* keep a running tally was sunset. At that point, "most" (and maybe even "nearly all") nodes can combine their running-tally with the hard-fork declared-at-N checkpoint tally to have their own enforceable tally.

(Laggard nodes that skip upgrades might still need to be able to do a from-genesis re-index. And perhaps this is too complicated compared to the current cost of a from-genesis re-index. But just wanted to point it out as a possibility, in case the "large pill" of a single-step re-index-from-start came to be a blocker.) 

Potentially, also, the net-inflow/outflow tally for each Z-realm could be explicitly declared in block headers – globally from the beginning when possible (or maybe "over last M blocks" in some other situations?). This could allow even certain kinds of 'light'/temporary observers to rapidly detect turnstile-violations.

**Comment by str4d** [comment]
Hmm, that does seem like a reasonable compromise. We would probably synchronise that checkpoint tally with a network upgrade, for simplicity, but it would technically be a soft-fork and could be introduced at any time. Users who don't want to trust the encoded checkpoint could do a reindex to ensure that they see the same value locally.

**Comment by str4d** [comment]
In the engineering meeting today, we decided that for 1.0.14, we would just implement the logic to collect this data, but not anything that acts on it (halting the node, rejecting blocks that cause a negative Sprout pool balance). That can be added in a later release, possibly in sync with a network upgrade.

**Comment by daira** [comment]
If this condition fails, other than as a result of local database corruption, it implies a fatal flaw in the protocol and no-one should run Zcashd until it has been fixed (possibly with a block chain rollback). I continue to believe that detecting this condition should halt the node.

**Comment by tromer** [comment]
How delicate is the accounting logic? If there are delicate corner cases (e.g., handling reorgs) then I suggest first merging the accounting logic with plenty of cross-checks and alerts/asserts to make sure it's correct, and then adding the halting/rejection in the next version.

**Comment by gojomo** [comment]
As mentioned in my [previous comment](https://github.com/zcash/zcash/issues/2351#issuecomment-332698955), if at some point a Z-Sapling realm is active alongside Z-Sprout, then a full halt on Z-Sprout turnstile-violation may not be the best policy. For example, imagine 40% of all ZEC are in t-realm, 50% in Z-Sapling, and 10% in Z-Sprout... and only *then* does a Z-Sprout turnstile-violation emerge. Holders of the 90% of system-value that's outside the broken realm – and indeed firewalled from too much damage due to the turnstile-enforcement – probably don't want a total network outage while that bug is addressed.

(There may even be a case for *allowing* the first turnstile-violating transaction into the blockchain, as a global-announcement/proof of the problem – while not respecting the excess value, and quarantining the entire Z-Sprout realm until an emergency-response can occur.)

**Comment by str4d** [comment]
I should note that we *could* choose to define two different behaviours here:

- From the next release (or the one after), if nodes detect such a state, they halt.
- From NU0 or NU1 (an upgrade point, to ensure all participating nodes enforce these rules):
  - Nodes only allow one such transaction to occur, as proof, but do **not** halt on its occurrence, and just reject subsequent blocks that add more transactions containing Sprout JoinSplits.
    - Would they reject blocks containing more than one such transaction? Might that delay notification?
  - If miners detect such a state, they mine the first of those transactions into a block as proof, and then (or after detecting such a transaction in another miner's block) disallow any further transactions containing Sprout JoinSplits.

> There may even be a case for allowing the first turnstile-violating transaction into the blockchain, as a global-announcement/proof of the problem – while not respecting the excess value, and quarantining the entire Z-Sprout realm until an emergency-response can occur.

This is in fact required if nodes only inspect the blockchain to make this determination, which technically is all they can enforce - you can't enforce consensus rules on the mempool, only standard rules (but those *could* also be monitoring for such transactions, which would enable earlier detection and potential halting).

**Comment by str4d** [comment]
For 1.0.14 we have added code to track the Sprout value pool. I've bumped this issue to 1.0.15 for deciding what to do with that information.

**Comment by daira** [comment]
I think we should just implement this as I originally proposed (halt as soon as this condition is detected).

**Comment by daira** [comment]
I am honestly perplexed why this proposal is controversial or why such a simple risk mitigation has been blocked since May 2017.

As I wrote in December 2017:
> If this condition fails, other than as a result of local database corruption, it implies a fatal flaw in the protocol and no-one should run Zcashd until it has been fixed (possibly with a block chain rollback). I continue to believe that detecting this condition should halt the node.

Let me emphasize: if this condition is violated, then nothing good can come of anyone continuing to run `zcashd`. The problem has to be investigated, fixed, and new software released. This is true regardless of whether the balance violation occurred maliciously or accidentally, *or even if it is a false alarm*. (The chance of it being a false alarm without indicating a serious bug is very low indeed.)

I'll address every objection made so far below.

@gojomo wrote:
> But as soon as there's more than one Z-realm, it is at least remotely possible that the system-as-a-whole might survive such a flaw – especially if most ZEC value is outside the flawed Z-realm, and another non-flawed Z-realm remains active. In such a case, the right reaction might be 'containment/warning/freeze' (as in the Tezos scenario).

It is implausible to me that if a balance violation flaw existed in one shielded pool/realm, that would not immediately cast suspicion on the other realm. The Sprout and Sapling subprotocols are not independent in terms of their design; the details are different but the basic concepts and much of the cryptographic structure are the same. If a balance violation were detected for one realm and not for another, it would not change my conclusion that everyone should stop running zcashd.

> There may be a swashbuckling, "burn-the-ships-behind-us", "we-all-go-down-with-the-ship" rationale for not trying to survive/continue-operation beyond such a hypothetical flaw.

This is a mischaracterisation of the rationale. No-one is saying that we don't attempt to fix the problem. I am saying that it absolutely will not help to fix the problem if zcashd instances that have detected a balance violation continue to operate with clearly invalid state.

@str4d wrote:
> Two points raised in a meeting:
>
> * This would be stored in the chain state, and therefore will only be enforced after a re-index.

Accounting of the Sprout and Sapling value pools was added in #2795 and #3255 respectively. It is technically possible that there are nodes that were originally created before those PRs were merged and have not reindexed since. I think that @gojomo's [proposal of a checkpoint tally](https://github.com/zcash/zcash/issues/2351#issuecomment-350815961) should be used in that case.

> * We could enforce this for the mempool as well. The sum total of "blockchain + valid txns in the local mempool" should still satisfy this rule. But just doing the check on the chain state is good enough for now.

I answered this in https://github.com/zcash/zcash/issues/2351#issuecomment-345158837 .

@tromer proposed an alternative policy:
> We can use a "capped turnstile" to limit the damage from hypothetical Sprout compromise by adding an explicit consensus rule that rejects transactions that could cause more ZEC to pass the turnstile than should be possible. Specifically, the following invariant would be checked:
(transparent ZEC) + (total Sapling vpub_old) - (total Sapling vpub_new) <= total supply.
>
> Transactions that would violate this would be rejected, but the node would not halt. If such a transaction is actually injected into the network, it suitable detectors would issue an alerts.

The problem with this proposal, in my view, is that it implicitly assumes that the balance violation is not ongoing. If there is evidence that balance violation occurred in the past, then there is no longer any reason to believe that it is safe to continue transacting at all, until that evidence has been investigated and any mitigations put in place.

(This also answers @gojomo's comment in https://github.com/zcash/zcash/issues/2351#issuecomment-351498243 .)

@tromer wrote:
> How delicate is the accounting logic? If there are delicate corner cases (e.g., handling reorgs) then I suggest first merging the accounting logic with plenty of cross-checks and alerts/asserts to make sure it's correct, and then adding the halting/rejection in the next version.

We essentially already did this; the accounting logic works fine and has been well-tested.

@str4d proposed another alternative:
> Nodes only allow one such transaction to occur, as proof, but do not halt on its occurrence, and just reject subsequent blocks that add more transactions containing Sprout JoinSplits.

If balance violation has occurred, it can't be isolated to the Sprout pool (or the Sapling pool if that is where it was detected). All of the pools are potentially affected. Pretending that the other pools are okay is just promoting a false sense of security.

**Comment by arielgabizon** [comment]
The reason I do not like the proposal is that I view it as the harshest mitigation of a forgery bug from the perspective of the honest players. E.g. suppose someone found a forgery attack, counterfeited 10,000 zec, sold them on an exchange (being careful not to cause, themselves, an overflowing of the pool); and happily continued with their lives forgetting about Zcash :)
Later on, some honest users try to exit the pool and suddenly it is overflowing - with this mitigation these honest users (and others just doing transparent txs near the time of the halt) will lose all their funds, or payments for goods that were frozen during the halt.
As opposed to allowing a little extra inflation, where, at least in the scenario where it stops at 5000-10000 zec averages out pretty negligibly in terms of people's loss.
Alternatively, given the overflow, you could give a little time for shutdown for people to exit the system/complete transactions for goods, rather than a sudden halt.
In general, not halting immediately, and just monitoring, doesn't seem to shrink the space of possible mitigations significantly (it doesn't seem to me the exact moment of overflow is special in terms of the damage in the system and it's significantly to halt then instead of a bit later)

**Comment by zebambam** [comment]
There's a lot of discussion of the mechanism in this thread, but maybe we need to consider first the monetary policy. If a shielded pool is over-emptied (pool total goes negative), there's an inflationary bug that has been exploited in that pool, and we have no way to know how much counterfeiting has really occurred, only that it has occurred in the past. 

But then why should a user who has only ever used Sapling addresses (and t-addrs) be unable to make their transactions? I don't understand why loss of faith in one shielded pool automatically means that we have lost faith in the other. Yes it will contain counterfeited funds, but for the other users of the otherwise unaffected, couldn't that result in no disruption to service or ill effects at all? 

Of course anyone stuck with funds left in the now-empty pool has lost their funds since they can't do anything about it, meaning that if we announced we were EOLing a shielded pool, it would be a race to get your legitimate funds out before counterfeiters take the entire allocation..

I'm interested in feedback on this, Nathan has asked me to write a sensible policy around it. Seems like not addressing it at all will result in ZEC --> 0, and that a halt causes complete chaos for other users and potentially leaves the remaining network open to abuse from whoever remains.

**Comment by daira** [comment]
The reason why loss of faith in all pools should be inferred immediately on a detected balance violation, is that an arbitrary amount of forged ZEC up to the detection threshold could already have been transferred to other pools. ZEC is fungible; the only way separate pools help is if we *actually take notice, as soon as possible* when balance violation is detected. In Zcoin, they didn't take notice, and as a result the collectivized loss was much greater than it needed to be. In total, 388450 XZC were forged, the vast majority of which (I can no longer find the information to tell precisely how much) should not have been forgeable since it exceeded the amount transferred into Zcoin's equivalent of the shielded pool. This was worth [roughly USD 500000](https://makebitcoingreatagain.wordpress.com/2017/02/18/is-the-zcoin-bug-in-checktransaction/#update6) at the time of the hack. The same bug was exploited [in Smartcash, and probably also PIVX](https://forum.smartcash.cc/t/smartcash-zerocoin-related-issues-and-the-path-forward/1359).

That's the only thing this proposal is trying to fix: to limit the amount of possible forgery. It is *not* trying to fix that users of Zcash will collectively lose money if a balance violation occurs. Of course they will lose money; the question is how much.

It's really no different from any other software assertion: we don't know *exactly* why the unexpected condition triggered (otherwise we would have avoided the bug), but we know that continuing to operate with corrupted state is unlikely to help and very likely to do harm. Note that we have plenty of assertions of this form already in the zcashd code base, and we have not had interminable arguments about whether halting is the right thing to do in those cases.

The only counterargument that I'm somewhat sympathetic to, is the potential for harm to users of nodes that don't detect the violation and continue to operate. A possible alternative is to trigger Emergency Mode. On the other hand, that can only be done if the violating block enters the chain (in order that the mode triggers at the same point for all nodes), at which point it's slightly more difficult to allow for a roll back than if the block had been rejected (since the violating block might contain other users' "innocent" transactions). I guess that's not a particularly strong argument, though. A more significant issue is that I didn't originally want this ticket to block on Emergency Mode, and I still don't think it needs to.

**Comment by daira** [comment]
Having nodes halt, BTW, does not "cause complete chaos" any more than a DoS or other bug &mdash; discounting uncertainty that is merely due to a balance violation having occurred, which would be caused anyway.

**Comment by daira** [comment]
Currently (as of block 425757), the Sprout shielded value pool has 304906.10355712 ZEC, and the Sapling shielded value pool has 23391.93786738 ZEC. The total monetary base is 5196981 ZEC. At the current ZEC price of USD 135.22, that is USD ~41.2million in shielded Sprout and USD ~3.2million in shielded Sapling, vs a total monetary base of USD ~703million.

Do we not want to limit the amount an adversary could forge in the case of a shielded protocol flaw/bug to (currently) USD ~44million? This seems like a no-brainer to me, and the minor differences in outcome associated with *how* we do it do not justify to me having quibbled about that for 18 months :-/

**Comment by zebambam** [comment]
So then halt is exactly the right thing to do.

**Comment by daira** [comment]
@arielgabizon wrote:
> The reason I do not like the proposal is that I view it as the harshest mitigation of a forgery bug from the perspective of the honest players. E.g. suppose someone found a forgery attack, counterfeited 10,000 zec, sold them on an exchange (being careful not to cause, themselves, an overflowing of the pool); and happily continued with their lives forgetting about Zcash :)...
or alternatively some weird bug caused some extra zec to appear in the shielded pool.
Later on, some honest users try to exit the pool and suddenly it is overflowing - with this mitigation these honest users (and others just doing transparent txs near the time of the halt) will lose all their funds, or payments for goods that were frozen during the halt.
As opposed to allowing a little extra inflation, where, at least in the scenario where it stops at 5000-10000 zec averages out pretty negligibly in terms of people's loss.

This assumes the adversary would act irrationally. The rational behaviour would be to forge right up to the limit of the allowed inflation margin, in which case this policy would leave none of that margin for honest users and would simply increase their collective loss.

But, you may say, might not an adversary be trying to avoid detection? Well, a careful adversary can pretty easily avoid direct tracing of its transactions. The main issue for it is prematurely tanking the price. However, it has the option of starting slowly, realising its gains by converting to another currency, and then repeating the attack becoming increasingly bold each time. There's really no downside to that strategy, if it is technically possible for a given vulnerability (which it probably is).

Adversaries whose main aim is to discredit the whole currency are in a different category, but my preferred strategy of allowing no extra inflation margin works well for them also.

**Comment by mms710** [comment]
Am I correct in assuming we are circling around the decision of "halt all nodes if we detect counterfeiting"? If that's true, I vote that we state that is our decision and move forward with implementation in a little over a week (next sprint), unless we'd like to leave more time for additional people in the community to weigh in. I'd also like to request that if we halt all nodes if we detect counterfeiting, we include a requirement that we page key people at Zcash Company to ensure we wake up and get to investigating and fixing the issue ASAP if we need to halt all nodes.

**Comment by gojomo** [comment]
My concern with a "full halt" is that it turns some possibly-survivable scenarios into a total loss, by creating even more disruption and a quite-likely-unfulfillable expectation that some "official fix" will be forthcoming shortly to resolve the halt. 

On the other hand, a "plow-through according to a prior plan, hoping problem doesn't affect the other (newer) pool "policy gives at least a tiny chance of some value surviving, in the case where the problem is truly in just one pool. 

In particular, I'd suggest a plow-through policy of (1) truncate the violating unshielding transfer to only having the effect the largest legal amount; (2) include that transaction in a block; (3) insta-disable all further transfers in or out of the pool whose balances have been violated. Perhaps call this "truncate-disable-proceed".

My conjecture is that this maximizes the possibility of a happy outcome for all ZEC-holders, especially compared to "halt-on-1st-observed-illegal-transaction" (which might let parts of the network proceed unaware). 

Under the scenarios where the flaw is unique to the originating shielded pool, "truncate-disable-proceed" successfully:

* turns any counterfeiting into a mere theft
* prevents any further benefit from counterfeiting in the disabled-pool
* allocates the losses from the balance violation about as fairly as any other conceivable policy, because there's no assurance the triggering transaction is actually from someone exploiting a bug – any counterfeiting could have happened and been unshielded successfully arbitrarily earlier
* informs all nodes of the new global state: total deactivation of the dead shielded pool
* prevents painting devs into no-win situation where, for example, the network is fully halted, the expectation is that it should only be restarted when some understood fix is ready & deployed, days/weeks are passing by, but the as-designed unassailable privacy of the defective shielded pool means there's nothing but a long list of untestable theories as to where the imbalance originated. 
* if, eventually, an explanation is discovered which confirms the flaw only affected the dead pool, or some 3rd pool added and Sapling evacuated without a turnstile violation, it allows trust & value in the still-operating chain to recover

Under scenarios where the flaw affects both shielded pools:

* that might not be understood for an arbitrarily long time after the turnstile violation – years? never? at the discretion of an attacker?
* when it is understood, there's a good chance it leaves the full chain unrecoverable, making all shielded amounts suspect - the only way forward might be a fork with fixes that preserves only transparent balances, or a total restart with a new genesis block 
* until it's understood, and while days or weeks are ticking away trying to understand it, the only way to provide any salvage value to users is continued hopeful operation of the parts of the system not proven flawed, allowing markets to value ZEC. 

In contrast, any full halt immediately sets the current value at zero, and each day of halt-without-confidence-inspiring-fix-being-imminent increases likelihood of a permanent zero value – even if in fact any flaw was only in the older, draining, successfully-quarantined shielded pool (Z-Sprout).

**Comment by zebambam** [comment]
If the bug is common to both pools, and our software continues when it could have halted, then we've made a very big mistake indeed.

**Comment by daira** [comment]
@gojomo wrote:
> In particular, I'd suggest a plow-through policy of (1) truncate the violating unshielding transfer to only having the effect the largest legal amount; (2) include that transaction in a block; (3) insta-disable all further transfers in or out of the pool whose balances have been violated. Perhaps call this "truncate-disable-proceed".

We can't do that. It would require a consensus change, and the next one of those (barring emergencies) is in October 2019.

**Comment by daira** [comment]
@gojomo wrote:
> My concern with a "full halt" is that it turns some possibly-survivable scenarios into a total loss, by creating even more disruption and a quite-likely-unfulfillable expectation that some "official fix" will be forthcoming shortly to resolve the halt.

In almost any circumstance I can imagine where this assertion would be triggered, there *would* be an official fix forthcoming, even if all it does is to disable the affected value pool(s). There is very likely to be some evidence available at that point that would tell us whether just one, or both (or all, in future) pools should be disabled.

**Comment by gojomo** [comment]
@zebambam writes:

> If the bug is common to both pools, and our software continues when it could have halted, then we've made a very big mistake indeed.

The problem is that from the moment of the turnstile violation, to the moment of understanding the true cause of the problem, involves a unknown delay D, where D may be hours, days, weeks, months, or years. 

If there's a default action that's likely to be taken after T hours, even if no clear diagnosis is yet possible – such as quarantine the known-bad shielded pool & continue with the possibly-good t- and Z-Sapling realms – then I propose it'd be better to just auto-program that default oblivious response beforehand.

Halting when halting offers no better solution than that default does extra damage. Meanwhile, if a surprise inflation bug really does affect both pools, zcash-as-we-know-it is almost certainly dead. Optimizing for that case is illogical. The one small chance of continuing – a compromise that turns out to be confined to just Z-Sprout – is the only branch of the possibility-tree with any positive payoffs. Thus we should pick what's best for that case and that case only. The "truncate-disable-proceed", by immediately handling that case in a pre-determined manner, allowing continuous operation of ZEC transfers/markets/uses with no disruption in service, seems to me to maximize value for ZEC holders in this one survivable case, for as long as confinement-to-Z-Sprout remains a plausible outcome. 

@daira writes:

> We can't do that. It would require a consensus change, and the next one of those (barring emergencies) is in October 2019.

It's not that it "can't" be done, but that the most-defensible time to do it would be the scheduled upgrade. OK, perhaps it's worth waiting. 

However, a "consensus change" that is only triggered in a catastrophic shouldn't-ever-happen scenario isn't quite the same as one that could cause a split under normal (or intentionally-triggerable) situations. Bitcoin Core's recent urgent CVE-2018–17144 fix was essentially an emergency consensus fix, where older agents would have allowed inflation that fixed clients would not.  But since the wrong behavior is so obviously against-design-intent, and sufficiently unlikely to occur without conscious exploitation, it's not thought of that way. 

We are talking about emergency-handling of what is hopefully a very very low probability event. And if the very very low probability event happens at all, I think there's a very very low probability the current incarnation of zcash survives at all. So there's a bit of survivalist-theorizing/fantasy here, like "what's the right mix of food and ammo in my underground bunker in case a massive meteor strikes the Earth and I survive the initial impact make it to my bunker in time". So delaying any change to a regularly-scheduled, well-tested consensus-upgrade point may be perfectly reasonable. 

Even adding a "halt on any violation" behavior is quite a bit like a consensus change: it means a violating transaction causes any node that sees it to drop out of the network immediately, while other older nodes continue along blissfully unaware.

> In almost any circumstance I can imagine where this assertion would be triggered, there would be an official fix forthcoming, even if all it does is to disable the affected value pool(s). There is very likely to be some evidence available at that point that would tell us whether just one, or both (or all, in future) pools should be disabled.

As mentioned above, if the default official fix in the absence of more info is likely to be, "disable affected pool, let now-suspected-but-not-yet-proven pools continue", I believe it would improve overall survivability to just automate that response. 

I'm not sure there would be any evidence that suggests the true extent of the problem, if a turnstile violation occurs - at least not promptly. 

Let's consider a concrete scenario already popular among anti-zcashers: posit that some Clever Counterfeiting Conspiracy (hereafter 'CCC') managed to compromise the Z-Sprout setup, either via collusion of all participants, or duping any honest participants, and possess the "toxic waste" secrets that should have ben irrreversibly destroyed. This CCC group could then have been counterfeiting at a moderate rate, not wanting to be discovered. But at some point as Z-Sprout is emptied – and a point not directly related to their own prior counterfeiting – the discrepancy will be discovered, as other non-conspirators evacuate their ZEC. And at the moment of ay Z-Sprout turnstile violation, this CCC will be the predominant theory among outsiders as to what went wrong. "We suspected all along," they'd shout. 

In such a case, the surviving privacy guarantees of Z-Sprout mean there'd be no evidence of when/where the counterfeiting happened. There'd be no remedies available better than just insta-closing the Z-Sprout shielded pool. (Better remedies would seem to require non-fungibility of shielded units – which would itself be as big a failure as the inflation.)

> No, why would [a halt set the current ZEC value to zero]? Not all nodes will halt. (It might actually be better if they did, but we have no available mechanism to ensure that.)

I should have been clearer: I'm saying the value is zero for the duration of the halt until some updated software is created and deployed, and that's a potentially unbounded amount of time because of the uncertainties of the situation. After the halt, no person/exchange with an up-to-date, supported node no can send/receive/transact any ZEC, unless they somehow trick their software into forgetting that it saw a turnstile-violation, or revert to older software. 

And if you're counting on some nodes continuing-in-ignorance (by user intention or dumb luck) in order to advance the chain, and thus lessen the total value freeze, then any supposed protective benefits of the full halt have been circumvented. There's even more chaos, compared to a pre-programmed "here's what all nodes will do to minimize the damage" strategy, because various nodes in non-halted islands that managed to operate a little longer may all have slightly-different local chain tips. If one, or seven, or fourteen days later ZCo recommends some new software with new behavior to allow continuing-past-turnstile-violating-transaction, which of these various rump chains should proceed? If it's one that managed to proceed the longest without its nodes halting, then the nodes that halted early have only been penalized by the halt – they missed out on potential mining rewards, or chances to transact in unaffected realms, compared to nodes that for whatever reason didn't halt. Does ZCo then anoint one of the rump chains as preferred for the restart? (Would it want that authority?)

**Comment by daira** [comment]
@gojomo wrote:
> > @daira writes:
>
> We can't do that. It would require a consensus change, and the next one of those (barring emergencies) is in October 2019.
>
> It's not that it "can't" be done, but that the most-defensible time to do it would be the scheduled upgrade. OK, perhaps it's worth waiting.

It's not. We can limit the potential collective loss due to forgery now with a simple change, and we should do so. There is no need to wait, and incur an avoidable risk for the whole period between now and October 2019.

> However, a "consensus change" that is only triggered in a catastrophic shouldn't-ever-happen scenario isn't quite the same as one that could cause a split under normal (or intentionally-triggerable) situations. 

We're not going to make an ad-hoc consensus changes that only trigger in an unexpected condition, outside the established network upgrade process (that has so far been spectacularly successful over two ambitious upgrades).

> Bitcoin Core's recent urgent CVE-2018–17144 fix was essentially an emergency consensus fix, where older agents would have allowed inflation that fixed clients would not. But since the wrong behavior is so obviously against-design-intent, and sufficiently unlikely to occur without conscious exploitation, it's not thought of that way.

That's not comparable. (It is comparable to the fix that we would make if a balance violation actually occurred, but *not* to adding considerable difficult-to-test complexity for a case that only *might* occur.)

**Comment by daira** [comment]
@gojomo wrote:
> After the halt, no person/exchange with an up-to-date, supported node no can send/receive/transact any ZEC, unless they somehow trick their software into forgetting that it saw a turnstile-violation, or revert to older software.

That's incorrect. Nodes don't remember that they saw a turnstile violation. (Again, perhaps they should, but we have no mechanism to do that and it's not what I'm proposing.)

I'm not going to address the conspiracy theory scenario, other than to say that this mechanism can't protect against conspiracy at all, and isn't intended to. It is intended to mitigate the effect of bugs and cryptographic design flaws, which are *far* more plausible.

**Comment by daira** [comment]
I will be occupied with other work until next week and won't be responding further on this ticket until then.

**Comment by mms710** [comment]
This other ticket fixes this issue and we're implementing it now: https://github.com/zcash/zcash/issues/3768
