### ISSUE TITLE
Add a *Zat variant of every amount-typed field

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2375]
The amount fields in the Bitcoin-inherited RPC, and those added in our additional methods, are in decimal format. This makes them more user-friendly, but inaccuracies can result from parsing these values with some floating-point implementations. We should add a corresponding `fooZat` field for every `foo`, which contains the amount in zatoshis, and is therefore an integer.

**Comment by oxarbitrage** [comment]
@str4d please check https://github.com/zcash/zcash/pull/4282 when you can. Instead of adding new result fields with the amount in satoshis i am using a different approach of adding a flag `inzatoshi` that will return amount fields as `int` when `true`.

I used `getreceivedbyaddress` in the PR to get started. In this case, the response is not json so adding a new field in addition to currently returned `amount` will break client side applications that are expecting just a decimal as response. 
Optional and disabled third argument will keep backward compatibility in this and other functions while keeping only 1 amount field in the response of the type the user wants.

Will like to discuss the approach before creating a list of calls and implement further. Thanks!
