### ISSUE TITLE
Add an RPC function or flag to create a shielding transaction that only contains coinbase

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2448]
Requested by an exchange. If a miner is sending their mining rewards to an address, and they happen to receive a coinbase output instead of a regular mining payout, then it becomes almost impossible to send transactions from that address until the coinbase output has been shielded. But the Bitcoin-inherited RPCs make it very expensive (in terms of RPC time) to figure out which UTXOs are from coinbase.

I'm imagining a new RPC function along these lines:

```
z_shieldcoinbase [output-z-address] (input-t-address)
```

This would take all coinbase outputs in the entire wallet (or in a single address, if `input-t-address` is provided), and send it to `output-z-address`.

This couples with #2446, which enables the reverse usage (enabling exchanges to build their own transactions that exclude coinbase).

**Comment by str4d** [comment]
Whether or not we create a new RPC function to do this, I definitely want us to consider excluding coinbase from regular `z_sendmany` spends, because I think users can easily make mistakes wrt the fact that change is sent to the recipient.

**Comment by daira** [comment]
@str4d As far as I know, change it not sent to the recipient in that case; exact change is required. (This does make shielding coinbases quite tricky, since you need to know the exact total value of input coins + fees.)

**Comment by str4d** [comment]
@daira yes, it turns out I was mis-remembering the UX of that API. I'm far more comfortable now that users can't make mistakes, but it's not exactly user-friendly, so treating coinbase as a separate "pool" or something (or at least having a unique RPC for dealing with it) is still a good idea IMHO.

**Comment by bitcartel** [comment]
To be consistent with ordered parameters in other send commands, where the from address is given first, I think the RPC look like this:

`z_shieldcoinbase taddr|* zaddr`

If '*' is given it means all taddrs.

**Comment by nathan-at-least** [comment]
Let's design this to follow the async operation framework to be consistent with `z_sendmany`.

In a discussion one idea for managing requests that would surpass transaction limitations (ex: txn size, input count), we could return "continuation information" in the result, such as how many UTXO's remain in coinbases for the source address(es). I like this idea, since it prevents a "trial and error" pattern, while also pushing the complexity of multi-transaction operations up the the higher layer.

**Comment by bitcartel** [comment]
@nathan-at-least @str4d I'm working on this now...

Regarding the API design:

There is no 'amount' field as the intent of the call is to simply shield coinbase outputs rather than send an arbitrary amount.

There is no 'minconf' field since coinbase outputs can only be spent after 100 confirmations, and the call will make sure they are spendable before including.

`z_shieldcoinbase taddr|* zaddress (fee)`

Do we need a `fee` parameter?  (I think yes).  We use the default z_sendmany fee of 10000 zatoshis if the fee parameter is not provided.

**Comment by str4d** [comment]
> There is no `amount` field as the intent of the call is to simply shield coinbase outputs rather than send an arbitrary amount.

What happens if there are more coinbase UTXOs than can be fitted into a single transaction? In practice, this will be lower than the benchmarked max of 555, because some transaction space will be taken up by the JoinSplit.

> Do we need a fee parameter? (I think yes). We use the default z_sendmany fee of 10000 zatoshis if the fee parameter is not provided.

I would say yes inasmuch as we "needed" it for `z_sendmany`. I'm still not entirely happy in general about just having a fee parameter with zero indication to the user that it affects their privacy, but in this specific case that's less of an issue (though non-zero) because the coinbase UTXOs are public.
