### ISSUE TITLE
Automate deployment of each released version in our monitoring infrastructure.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2483]
We should persistently run at least one instance of each release in our monitoring infrastructure in order to improve the chances of detecting version-specific or inter-version-specific issues.

**Comment by nathan-at-least** [comment]
For this release we need to be more conservative with infrastructure changes, so we'll postpone this.

**Comment by str4d** [comment]
@arcalinea what versions are we currently running across our detectors?

**Comment by str4d** [comment]
Just after releasing version X, we will have the following released and supported versions:

- X
- X - 1
- X - 2
- X - 3 (until #2686 has been resolved, at which point this version will always have undergone auto-senescence before we release version X).

We want to ensure consistent coverage of all supported versions. I propose the following upgrade strategy (based on running versions just after the release of X):

- Detectors on version X are eager: always on the latest release.
- All other detectors are lazy: only upgrading when auto-senescence requires them to.

This strategy makes the upgrade process simpler (we are simply upgrading to the latest release, rather than having to pin a version). We also only have to upgrade detectors twice per release cycle - once when X - 3 hits auto-senescence, and again when X is released.

To visualise this, assume we have the following detector deployment:

Detector | X - 3 | X - 2 | X - 1
--- | --- | --- | ---
1 | | | X
2 | | | X
3 | | | X
4 | | X |
5 | | X |
6 | X | |
7 | X | |

### X - 3 hits auto-senescence

Detector | X - 3 | X - 2 | X - 1
--- | --- | --- | ---
1 | | | X
2 | | | X
3 | | | X
4 | | X |
5 | | X |
6 | | | X
7 | | | X

### X is released

Detector | X - 3 | X - 2 | X - 1 | X
--- | --- | --- | --- | ---
1 | | | | X
2 | | | | X
3 | | | | X
4 | | X | |
5 | | X | |
6 | | | X |
7 | | | X |

### X - 2 hits auto-senescence

Detector | X - 3 | X - 2 | X - 1 | X
--- | --- | --- | --- | ---
1 | | | | X
2 | | | | X
3 | | | | X
4 | | | | X
5 | | | | X
6 | | | X |
7 | | | X |

### X + 1is released

Detector | X - 3 | X - 2 | X - 1 | X | X + 1
--- | --- | --- | --- | --- | ---
1 | | | | | X
2 | | | | | X
3 | | | | | X
4 | | | | X |
5 | | | | X |
6 | | | X | |
7 | | | X | |

To close this, we need to:

- Write a script to automate the above strategy (assuming it is ACKed).
- Update our internal infrastructure documentation to specify when and how the script should be used.

**Comment by arcalinea** [comment]
We currently run two versions back from the current release. I don't think this is reflected in ansible

**Comment by arcalinea** [comment]
And we had problems with 1.0.9 when we deprecated, so we upgraded those

**Comment by daira** [comment]
@str4d's suggested strategy looks good to me.

**Comment by nuttycom** [comment]
@mdr0id Should this be considered complete? Please close this if it's done.

**Comment by mdr0id** [comment]
This can be closed as it's done in several flavors across infra
