### ISSUE TITLE
Criteria for adding unsupported CI workers?

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2499]
PR #2470 intends to add an unsupported builder for Xubuntu.  Give the number of officially supported flavors of Ubuntu, where the only real difference is the desktop environment, is there some criteria for selecting xubuntu over lubuntu/kubuntu... e.g. a user filed a ticket i.e. #1283 ?
https://www.ubuntu.com/download/ubuntu-flavours

Linux Mint (derived from Ubuntu) is #1 on distrowatch and very popular on the desktop, a potential candidate too?
http://distrowatch.com/

Arch, RHEL derived Centos/Fedora and openSuse are distros which are sufficiently different from each other, in their layout and package management, that it might be a good idea to have unsupported workers for them.  I've seen tickets for all of these distros too.

**Comment by str4d** [comment]
I suggest that the workers *we* add cover as wide a range as possible in the areas that do affect us, so I would prefer to have a worker for e.g. Arch over Xubuntu (where the latter only differs from Ubuntu in GUI, which we don't have). The worker deployment system I'm writing will hopefully cover that, and should make it relatively easy to add flavours (by adding symlinks to the canonical version's configuration).

**Comment by daira** [comment]
We should definitely focus on increasing the range of distributions that differ in aspects that actually affect portability of our code, such as package management.

**Comment by nathan-at-least** [comment]
The Development Infrastructure project coordinator (currently me) is the one who nominates tickets, so they are prioritizing which workers to add. The release coordinator may reject the work of adding workers for a particular release, due to their own considerations (bandwidth, high level release goals, etc…).

I agree having some consistency would be good. Here's what I propose:

a. Don't add workers until users complain about a problem on a platform that doesn't yet have workers (_or_ I guess if we anticipate many users will use a platform, we may pre-emptively add unsupported for it.)
b. Prioritize the workers that seem to have the most users. (In practice, this might be the ones with the loudest users. :-/ )
c. When adding workers start by adding workers for the "most common" variant of any distro, then if users later encounter problems with a sub-variant, we can consider adding new workers at that point. So I propose we target Ubuntu Desktop (or Server, whichever we bet has more Zcash users), and see if that catches the Xubuntu users' issues.

Meanwhile, I just added a [CI Worker](https://github.com/zcash/zcash/labels/CI%20Worker) label to track requests to add specific workers. Let's file separate tickets for each kind of worker instead of having an umbrella ticket so we can distinguish among them.

**Comment by nathan-at-least** [comment]
If my previous comment is acceptable to the current participants (@bitcartel, @str4d, @daira, and myself), then let's close it as resolved.

I ACK the policy. ;-)

**Comment by daira** [comment]
ACK from me.

**Comment by str4d** [comment]
ACK from me. Where should this be documented? I could add it to the README for #2509 but IMHO this issue is more about *us* adding unsupported CI workers; the community should be more than welcome to contribute configs to the Ansible playbook in order to set up their own unsupported workers for our CI to use.

**Comment by daira** [comment]
A new section in https://github.com/zcash/zcash/blob/master/contrib/ci-workers/README.md does seem like the appropriate place. We should err on the side of not being too specific or discouraging contributions.

**Comment by nathan-at-least** [comment]
Still waiting on an ACK from @bitcartel.

**Comment by bitcartel** [comment]
![](http://i.imgur.com/9WZXD8S.jpg)

**Comment by daira** [comment]
(Please don't use that image to ACK everything :-p )

**Comment by nathan-at-least** [comment]
I count 15 ACKs, although I suspect a sybil attack. Added to README in pr #2543.
