### ISSUE TITLE
[Sapling] Define new serialisation format for BLS12-381 points

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2517]
The serialisation format for BN-254 points, taken from IEEE Std 1363-2000/2004, has some deficiencies:

* It requires a modular inversion to decode a G<sub>2</sub> element.
* It unnecessarily uses a different method of selecting the compressed y-coordinate bit for G<sub>1</sub> and for G<sub>2</sub>.
* It uses an extra byte, even though there is room to represent the compressed y-coordinate in a high-order bit of the bytes used to encode the x-coordinate.

Although these deficiencies are relatively minor, the inversion in particular is painful and it would be good to fix them, since we have the opportunity to do so without additional compatibility problems and there's relatively little value obtained from being strictly standards-conforming in this case.

**Comment by ebfull** [comment]
Cool!

> It uses an extra byte, even though there is room to represent the compressed y-coordinate in a high-order bit of the bytes used to encode the x-coordinate.

The overhead of the extra byte isn't really too big of a deal in practice. It would be a 2-3% improvement in the size of our proving key, for example. I say it's not worth the engineering complexity, and by not packing elements in this way we make debugging easier.

My proposed format is something like this:

`0b11110000` = point at infinity
`0b11110001` = X coordinate, then Y coordinate, follow
`0b11110010` = X coordinate follows, choose lexicographically smallest Y coordinate
`0b11110011` = X coordinate follows, choose lexicographically largest Y coordinate

The purpose of the leading `0b1111` is to distinguish this standard from the IEEE one.

Fq coordinates should be encoded in big endian byte order, always consuming 48 bytes. Fq2 coordinates, which are `c0 + c1 * u`, should be concatenated like `c0 || c1`. Each coefficient should always consume 48 bytes. Fq2 elements are thus 96 bytes when represented here.

This is probably not important, but in our curve, Y cannot be 0, so there will always be two distinct Y coordinates for each point.

**Comment by ebfull** [comment]
We could even go further and use one of the bits to indicate if the element is intended to be for G1/G2, also for debugging purposes.

**Comment by ebfull** [comment]
Note that we do not need nor want an Fq12 serialization format.

**Comment by daira** [comment]
Here's what I was thinking: the most significant three bits of the first byte would be

0b100 = point at infinity; zero padded to the length of an X coordinate
0b101 = X coordinate, then Y coordinate, follow
0b110 = X coordinate follows, choose lexicographically smallest Y coordinate
0b111 = X coordinate follows, choose lexicographically largest Y coordinate

followed by the remaining bits of the X coordinate, in big-endian order. (For BLS12-381 this just fits; more generally there would be ceiling((lg(q) + 3)/8) bytes in each coefficient.) Fq2 coordinates would be concatenated as ``c1 || c0`` (this retains consistent big-endian order, since ``c1`` is the most significant coefficient of the polynomial). This is still always distinct from the IEEE format.

**Comment by ebfull** [comment]
> this retains consistent big-endian order, since c1 is the most significant coefficient of the polynomial

Good point.

> 0b100 = point at infinity; zero padded to the length of an X coordinate

Hm... note that this extra padding would only be useful when using compressed points. We'll be using uncompressed points in the proving keys.

------------

This brings up an important topic: we _can_ (and perhaps should) design the Groth implementation so that there are no points at infinity anywhere in the on-disk parameters. This can be done since the prover, with some small extra memory cost, can deterministically evaluate the sparse structure of the A/B queries, and nothing else in the proving key should need to be a point at infinity.

This comes with several advantages: minimal size of the proving key (especially useful for MPCs), no need to have a leading byte anywhere in the proving key since they would all be the same, the ability to perform A/B swaps if we wanted to (though it shouldn't be necessary for a well-designed circuit), and avoiding the need to determine where in the key certain queries begin.

Since we _may_ encode Fq elements into the proving key in the Montgomery form, for performance reasons, or perhaps even in a representation that can be straight-up memory mapped into the process as not having points at infinity in the proving key doesn't disturb alignment, and because adding serialization to the `pairing` library generally requires adding some extra dependencies, I am leaning toward something new:

1. The `pairing` crate doesn't specify serialization in any way.
2. We design a format for the Groth16 proofs.
3. We design a format for the Groth16 parameters.

I like this because it keeps the `pairing` crate simpler. We might as well not have a generic specification for all G1/G2 points if we're going to do something completely different for the proofs and the parameters.

**Comment by daira** [comment]
OK, that makes sense to me. Let's still have the encodings of uncompressed points in the parameters and of compressed points in the proofs be disjoint, though (which should be easy to do).

**Comment by ebfull** [comment]
Yes, that's a good idea.

Here's how it may look concretely:

The `pairing` library is modified to add two new traits, `CurveCompressed` and `CurveUncompressed`, which can be transformed to and from their respective `CurveAffine` implementations. There are two ways each trait can be transformed into the affine, `into_affine` and `into_affine_unchecked` where the unchecked variant assumes the point is on the curve, in the correct order, etc. Transformation from affine is done via `to_compressed` and `to_uncompressed`.

The in-memory representation of BLS12-381 `CurveCompressed` elements will be `[u8; 48]` for G1 and `[u8; 96]` for G2. The most significant bit is set to distinguish this as a compressed curve point. The next most significant bit is used to encode the SORT distinguisher for the choice of y-coordinate. After masking, for G1, it is interpreted as a big-endian Fq x-coordinate, for G2, it is encoded as the Fq coefficients of the Fq2 x-coordinate in big-endian form, i.e., `c1 || c0`.

The in-memory representation of BLS12-381 `CurveUncompressed` elements will be `[u8; 96]` for G1 and `[u8; 192]` for G2. The most significant bit is left unset, so no masking is necessary. These represent the x and y coordinates in that order. These coordinates are encoded in the same way as the x-coordinates were encoded in the `CurveCompressed` case.

This punts actual (de)serialization of the `[u8; N]` elements downstream to bellman.

In the `bellman` crate during proof generation we'll maintain a bit vector to indicate whether points at infinity are expected at various points of the A/B queries.

**Comment by daira** [comment]
Linking to https://github.com/ebfull/pairing/commit/3faf8c526afc56ae9e2a995433c315e96fdfb80f so that I don't lose it.

**Comment by ebfull** [comment]
@daira I'm going to change it again to make it more like your proposal. But, I still am not sure what's best for the point at infinity. The zero-padding almost certainly should behave differently depending on whether the element is compressed or not, which might suggest that setting that distinguisher bit is necessary.

We have three bits, so...

* Is this not the point at infinity?
* Is this a compressed point element?
* If this is a compressed point element, should we select the lexicographically largest y-coordinate?

**Comment by daira** [comment]
I want to change this to:
* Is this a compressed point element?
* Is this the point at infinity?
* If this is a compressed point element, should we select the lexicographically largest y-coordinate?

the reason being, this allows to represent the point at infinity also in uncompressed representation, in such a way that the union of compressed and uncompressed representations is prefix-free, and without having to mask off an infinity bit in the normal uncompressed case.

**Comment by ebfull** [comment]
@daira I also briefly considered stealing the point-at-infinity-bit for distinguishing G1/G2, and using all-zeroes to indicate that it's the point at infinity instead. This perhaps would aid against fault attacks, since it's very possible to create a compressed G2 element that can be misinterpreted as a compressed G1 element. 

What do you think of this?

**Comment by ebfull** [comment]
> fault attacks

Not sure why I said this, I just mean bugs in general.

**Comment by ebfull** [comment]
Barring any more modifications, here's roughly what I intend to implement:

* Fq elements are encoded in big-endian form. They occupy 48 bytes in this form.
* Fq2 elements are encoded in big-endian form, meaning that the Fq element c0 + c1 * u is represented by the Fq element c1 followed by the Fq element c0. This means Fq2 elements occupy 96 bytes in this form.
* The group G1 uses Fq elements for coordinates. The group G2 uses Fq2 elements for coordinates.
* G1 and G2 elements can be encoded in uncompressed form (the x-coordinate followed by the y-coordinate) or in compressed form (just the x-coordinate). G1 elements occupy 96 bytes in uncompressed form, and 48 bytes in compressed form. G2 elements occupy 192 bytes in uncompressed form, and 96 bytes in compressed form.

The most-significant three bits of a G1 or G2 encoding should be masked away before the coordinate(s) are interpreted. These bits are used to unambiguously represent the underlying element:

* The most significant bit, when set, indicates that the point is in compressed form. Otherwise, the point is in uncompressed form.
* The second-most significant bit indicates that the point is at infinity. If this bit is set, the remaining bits of the group element's encoding should be set to zero.
* The third-most significant bit is set if (and only if) this point is in compressed form _and_ it is not the point at infinity _and_ its y-coordinate is the lexicographically largest of the two associated with the encoded x-coordinate.

**Comment by daira** [comment]
We also need a serialisation format for compressed Jubjub points, because they appear in addresses and as epk in a note ciphertext.  This should be as compact as possible, and doesn't need to be able to represent uncompressed points or the point at infinity. It's also only a single prime curve with no need to encode polynomials.

**Comment by daira** [comment]
Suppose that we encode only the x-coordinate in addresses and epk. Then to perform a key agreement with the resulting public key, we guess one of the two corresponding y-coordinates and do a cofactor multiplication by 8, followed by the scalar multiplication. If we guess the wrong square root for the y-coordinate, the sign of the resulting point will be flipped (because 2.(x, -y) = -2.(x, y) ). But this does not affect the y-coordinate of the result, and so we can take just the result's y-coordinate as input to the KDF.

This works only for key agreement, not for signatures. So, at first sight it might not appear to support signing using a Sapling private key as discussed in #1770 (taking advantage of the fact that key agreement with cofactor multiplication and EdDSA signatures are simultaneously secure for a shared key pair). However, for signatures there's a different trick. As proven in #2234, a given x-coordinate corresponds to only one y-coordinate for points in the prime-order subgroup. So, when generating keys we ensure that the public point is in the subgroup. Then we know that the signature verifier can find the unique correct y-coordinate for an EdDSA public key by checking which recovered point is in the subgroup. (We could have done this for key agreement as well, but we didn't want to primarily for efficiency :&mdash; checking that a point is in the subgroup costs a full-length scalar multiplication.) The verifier may find that an address has a public point that is not in the subgroup, but the verification algorithm can simply specify that the signature is rejected in that case.

**Comment by daira** [comment]
Only encoding the y-coordinate, on the other hand, would still work for key agreement but would not work for signatures.

**Comment by daira** [comment]
We have encodings for both BLS12-381 and Jubjub (the latter is the compressed encoding defined by EdDSA), which are described in the protocol spec and implemented. So this ticket can be closed.
