### ISSUE TITLE
z_sendmany usability bug

### ISSUE THREAD

**Issue by theilluminaughti** [zcash/zcash#2537]
### Describe the issue
This is a usability bug.

Currently, you have to use z_sendmany to send from a t-address. That's inconsistent. Particularly when you use "getnewaddress" to get a t-address and "z_getnewaddress" to get a z-address. It follows that you should use "sendmany" to send from a t-address and "z_sendmany" to send from a z-address.

The first time anyone uses Z, they try using "sendmany" and get an obscure error message, meaning that people think they've lost their coins.

#### If so, please list the steps to reproduce below:
1. Try to use "sendmany" to send from a t-address.

### Expected behaviour
"sendmany" should send from a t-address to a t-address

### Actual behaviour + errors
No transaction is made.

### The version of Zcash you were using:
v1.0.10-1

**Comment by daira** [comment]
As far as I know ``sendmany`` should work the same way as in Bitcoin. What error message do you get?

**Comment by theilluminaughti** [comment]
Sorry for the delay, I should have an answer for you shortly.

**Comment by theilluminaughti** [comment]
Ok,

`$ zcash-cli sendmany "$XX" "[{\"amount\": 0.1, \"address\": \"$YY\"}]"`

results in

```
error code: -11
error message:
Accounts are unsupported
```

Version v1.0.10-1

**Comment by ioptio** [comment]
@theilluminaughti as the error message says, accounts are not supported in Zcash. In order to be compatible with calls inherited from bitcoin that use an account parameter, there is a single default account for the wallet which contains all addresses. This means any calls that require an account parameter must use double quotes (`""`) to represent this default account. 

See https://github.com/zcash/zcash/blob/master/doc/payment-api.md#compatibility-with-bitcoin-core for more info.

So please try again with `""` for account parameter and let us know if that works.

**Comment by theilluminaughti** [comment]
Ah I see, got it. There were a couple of posts on the forum of similar nature, so at least I know it wasn't just me that got stumped. Thankyou :)
