### ISSUE TITLE
[Arch package] stack smashing detected by Fortify

### ISSUE THREAD

**Issue by FrederikLauber** [zcash/zcash#2549]
#### If so, please list the steps to reproduce below:
1. run zcashd
2. observe crash with "stack smashing detected" within a few seconds

### Expected behaviour
zcash should be running

### Machine specs:
- Arch Linux

Here is the issue on the Arch Linux Bug tracker including a stack trace.
https://bugs.archlinux.org/task/54835

**Comment by daira** [comment]
That's odd the failure is from Fortify, but we always compile with Fortify enabled already (and test that it is actually enabled).

The trace linked from the Arch ticket is from a stripped executable. Can you recompile the Arch package without stripping symbols? Also, can you link to any patches that were applied to build the Arch package?

**Comment by eli-schwartz** [comment]
Arch uses three patches: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/zcash#n24
The patches themselves can be seen here: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/zcash

It's not doing anything other than using system libraries for libgmp, libsodium, and rust (I assume because your build system doesn't inherently have any way to do that), and fix a boost linker flag.

**Comment by daira** [comment]
Hmm, what versions are the system Boost, libsodium, and Rust? It is plausible that memory safety bugs in one of those dependencies have been fixed between the system versions and the ones we normally use (i.e. Boost 1.62.0, libsodium 1.0.11, and Rust 1.16.0).

**Comment by daira** [comment]
Also, what gcc/g++ are you using?

**Comment by daira** [comment]
BTW, if the system Boost is compiled with single-threaded option then that would definitely cause a problem. But I suspect that it's compiled for multi-threaded and just lacks the "-mt" on the library name.

**Comment by eli-schwartz** [comment]
Our repos are at:
libsodium 1.0.13-1
boost 1.64.0-4
rust 1:1.18.0-1
gcc 7.1.1-4

The package was built with:
boost-1.64.0-3
gcc-7.1.1-3
libsodium-1.0.12-1

Our boost package is compiled with `--layout=system threading=multi`. :smile:

(Also note that I don't use this software, I am here because I triaged the bug on our bugtracker and followed the link here.)

**Comment by tensor5** [comment]
Arch package works after rebuilding, issue https://bugs.archlinux.org/task/54835 has been closed.

**Comment by daira** [comment]
Any idea what was different between the original build and the rebuild?

**Comment by tensor5** [comment]
@daira I'm not sure if this is related, but the default Arch's [CFLAGS recently changed](https://git.archlinux.org/svntogit/packages.git/diff/trunk/makepkg.conf?h=packages/pacman&id=0cd22d4454e0e1b3ae589b95274f808001465c15), and [glibc](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/glibc&id=e4db1c823e0d69073c7794671b1f4a68b984645c) was rebuilt with the new flags.

**Comment by bitcartel** [comment]
This is now resolved. Closing.
