### ISSUE TITLE
README and CLI should both link to https://z.cash/security/

### ISSUE THREAD

**Issue by jasondavies** [zcash/zcash#2576]
As [noted](https://chat.zcashcommunity.com/channel/zcash-dev?msg=HLrzXGv5jE2sq4B2W) by @zookozcash:

[README.md](https://github.com/zcash/zcash/blob/2a42478bff3e1298f73e0411eb6d69d83b89f6a0/README.md) links to [doc/security-warnings.md](https://github.com/zcash/zcash/blob/2a42478bff3e1298f73e0411eb6d69d83b89f6a0/doc/security-warnings.md), but the CLI links to <https://z.cash/security/index.html>.

* Ideally, the README should link to the website too so there is a single starting point for security warnings.
* The links should be shortened by dropping "index.html": <https://z.cash/security/>.

**Comment by bitcartel** [comment]
`https://z.cash/security/` is a 404 as that part of the website is now under `support`.

Created PR to link to `https://z.cash/support/security/`.

**Comment by daira** [comment]
Can we add a redirect? That URL is in old versions of zcashd.

**Comment by bitcartel** [comment]
I think a redirect for older nodes would improve the situation for existing users, where there is currently a 404.  Another option is to have https://z.cash/security/index.html display a short message saying the page has moved to a new url and include a link.

My gut feeling is that security info links should go directly to the intended resource, rather than inadvertently train users into accepting a redirect.

**Comment by daira** [comment]
That's what redirects are for, to allow reorganisations. I don't see any security problem with a redirect within a site.

**Comment by bitcartel** [comment]
So just to clarify, we want old nodes to point to a redirect and new nodes to point to the correct resource?  

In which case we need a website ticket to set up the redirect before we can close this issue.
