### ISSUE TITLE
More prominent link to roadmap and "whitepaper" (or equivalent, or not)

### ISSUE THREAD

**Issue by jasondavies** [zcash/zcash#2579]
Any respectable cryptocurrency simply needs a whitepaper (PDF), a roadmap, and of course a team of best-in-class experts!

Zcash clearly has the latter, but there isn't currently a prominent link to a roadmap, and a user [recently asked](https://chat.zcashcommunity.com/channel/zcash?msg=cQMhBKJyhMmmDE4hf) why the "whitepaper and roadmap" are not prominently linked to from the main website, as done by [Dentacoin](https://dentacoin.com/).

I think perhaps a link to the roadmap could be helpful, though maybe linking to the Wiki isn't the best idea; perhaps a new "roadmap" page would be helpful?

As for a whitepaper, I'm not sure prominently linking to the protocol specification PDF is necessarily that helpful.  It's already linked to from the footer.  In addition, the [learn more](https://z.cash/technology/index.html) link is very prominent and links to the "tech" page, which serves as an introduction to Zcash.  This also links to the published Zerocash paper, but maybe a link to the protocol specification in that section on the left would be helpful?

**Comment by arcalinea** [comment]
Thanks for raising these points, I think part of the mismatch in user expectations is because Zcash was conceived and launched before a million ICOs began to bloom, conditioning users to expect a certain format for cryptocurrency websites and materials. Thoughts:

Whitepaper - Zcash doesn't have an "official" whitepaper per se, though it's based on the original Zerocash paper which we link to on the Tech page. That paper is very in-depth and probably only interesting to a highly technical audience, so we put it on the Tech page for people willing to take deep dives.

Roadmap - This exists primarily as a wiki page since it's just a general overview that refers to the github milestones as the official source. It's worth considering putting a dedicated page on the website, though @nathan-at-least would have to write/approve it 

Protocol spec - I think we used to have the protocol spec on the Tech page, but it got moved to the Support section. Can add a link to the Tech page as well

**Comment by jasondavies** [comment]
Yes, and just to be clear, my comparison with ICOs was supposed to be somewhat tongue-in-cheek. :)  Having said that, I think it's worth thinking about areas to improve the website for new users.  I'm in agreement with your points, but just to reiterate:

* Roadmap - perhaps it could just be a relatively lightweight but dedicated roadmap page that illustrates the main upcoming improvements in Sapling, and links to the relevant blog posts and the milestones, and is updated periodically as more details are available over time.
* Protocol spec. could probably be *slightly* more prominent on the tech page.

**Comment by arcalinea** [comment]
Hehe, I see. :) 

Roadmap - I created an issue for this and will bring it up with @nathan-at-least and @ioptio in the website meeting 
Protocol spec - Easy fix, just put a link on the tech page: https://z.cash/technology/

**Comment by arcalinea** [comment]
Closing this issue since it will be addressed as part of ongoing roadmap development and website updates
