### ISSUE TITLE
Adapt SIGHASH_FORKID for (1) NU0 replay protection (2) fixing quadratic hashing (3) hardware wallets

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2584]
**Edit 2017-11-20 by Nathan:** We need to adapt `SIGHASH_FORKID` for Zcash by making several modifications: see https://github.com/zcash/zcash/issues/2584#issuecomment-347241512. Fulfilling this ticket requires doing that design work.

Upstream Bitcoin Cash clients have implemented SIGHASH_FORKID for

1. Replay protection
2. Quadratic hashing fix
3. Lightweight wallet signing e.g. hardware wallets

SIGHASH_FORKID is specified here:
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/abc/replay-protected-sighash.md
and discussed in context here:
https://github.com/Bitcoin-UAHF/spec/blob/master/uahf-technical-spec.md

SIGHASH_FORKID is an implementation of the digest algorithm for transaction signature verification as described in BIP143 (and used in BIP 141).
https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki

This ticket can resolve #1162, #2411, #2415, #2566 and satisfy #2254.

**Comment by nathan-at-least** [comment]
How much evaluation does that scheme have?

One immediate thought after a scan is item 6 in the [Digest Algorithm](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/abc/replay-protected-sighash.md#digest-algorithm) section:

Doesn't this add a new dependency on signature verification where the verifier must *load one transaction for every input* to look up the value? If so, that changes signature validation from "contextless" to requiring a transaction (or UTXO) index, which seems like a major change. Maybe there's a way around it by requiring the prevout values to be serialized next to the transaction?

Anyway, I need to think about this a lot more (as well as an alternative proposal from @str4d, and potentially others) before I feel comfortable with it.

**Comment by str4d** [comment]
> How much evaluation does that scheme have?

AFAICT (hard because the SIGHASH_FORKID proposal copied and then changed the Markdown formatting), the only difference between this propsal and BIP 143 is the ORing of a 24-bit fork ID into the sighash type. Thus it has the entirety of SegWit evaluation behind it.

> One immediate thought after a scan is item 6 in the Digest Algorithm section:

> Doesn't this add a new dependency on signature verification where the verifier must load one transaction for every input to look up the value? If so, that changes signature validation from "contextless" to requiring a transaction (or UTXO) index, which seems like a major change. Maybe there's a way around it by requiring the prevout values to be serialized next to the transaction?

This lookup has always been necessary; the sighash change just changes where it happens. Currently, the only way to verifiably check the value balance for a transaction is to load the input transactions, and validate them. This is fine for full nodes, but a lot of overhead for e.g. hardware wallets (see [this TREZOR blogpost](https://segwit.org/segregated-witness-and-trezor-46b3777f91e9)). With this change, the hardware wallet can just be given the values, and know that they are authentic (because they are part of the signature, rather than a hop away through the prevouts). The value still needs to be looked up, but this can be done when a block arrives, and then cached for later use.

**Comment by str4d** [comment]
I outlined my proposal in https://github.com/zcash/zcash/issues/174#issuecomment-344457030, which is the parent for (1) in OP title.

**Comment by nathan-at-least** [comment]
We changed the title to use "adapt" because we need to change these parts on top of SIGHASH_FORKID:

- specify how JoinSplits are covered by signatures.
- change the hashing scheme to blake2 with first-class personalization.
- add guidance for future upgrades about how to use the personalization field, especially when considering competing alternatives.

**Comment by nathan-at-least** [comment]
Also, let's pick a better name from `SIGHASH_FORKID`, which is confusing in a few ways:

- The hashing scheme for signature generation/validation applies to all `SIGHASH_*` types, such as `SIGHASH_ALL`.
- We wish to avoid the word `fork` due to various ambiguities.

**Comment by arielgabizon** [comment]
Are we sure we want to fix quadratic hashing, value signing in NU0?
If we would just want replay protection it would be much simpler probably.

**Comment by arielgabizon** [comment]
The simplest thing seems to be just to chance `nversion` to something unique for the fork.

**Comment by str4d** [comment]
> I mean, is someone really attacking any network with huge transactions with a lot of signatures? And they would have to keep it up for a lot of blocks to get any DOS effect.

We already see this happening non-maliciously: there are various exchanges trying to merge many UTXOs into more usable amounts. The first time this happened, individual blocks were taking between six and ten seconds to validate (see #2333), which broke many of the mining pools, and is why we implemented #2342 as a short-term fix. There are various other optimisations we need to pull in from upstream (https://github.com/zcash/zcash/issues/2333#issuecomment-299630014), but it isn't going to be possible to noticeably decrease the size of the UTXO set for these exchanges without fixing the quadratic hashing problem.

**Comment by arielgabizon** [comment]
Right, my mistake,  I thought you need to create an artificial script with a lot of checksigs to run into this.
There's still the question, do we want to do replay protection with this signature type `SIGHASH_FORKID`,  or just change the `nversion` for the fork?
And I'm curious with the short-term fix what num of inputs are miners allowing?
And is that interfering with mining pools' ability to make large transactions?

**Comment by arielgabizon** [comment]
Here's my first attempt at adapting the linear hashing code  from bitcoin  https://github.com/arielgabizon/zcash/tree/fix-quadratic-hashing

**Comment by arielgabizon** [comment]
Here's my second attempt,  using cherry-pick instead of copy-paste as @str4d requested  https://github.com/arielgabizon/zcash/tree/integrate-quadhash-fix
I have detailed notes about the process, with all the things I didn't cherry-pick on the way, that we may want to integrate.

**Comment by arielgabizon** [comment]
The function `signatureHash` will be changed when we decide on our hardfork mechanism.

**Comment by daira** [comment]
I think we should use BLAKE2b-256 rather than BLAKE2s. Section 3.3 of the [BLAKE2 paper](https://blake2.net/blake2.pdf) says that "a typical implementation of [BLAKE2s] in embedded software stores in RAM at least [168 bytes]. BLAKE2b only requires 336 bytes of RAM [...]".

The difference between 168 and 336 bytes is not material even for embedded implementations. For a hardware wallet you'll also want to be doing EdDSA signing, which also likely requires [at least 336 bytes](https://www.dlbeer.co.nz/oss/c25519.html) (and you don't need to do signing and hashing at the same time). For reference, Trezor uses a Cortex M3 [with 128 KiB of RAM](https://events.ccc.de/congress/2013/Fahrplan/system/attachments/2278/original/trezor-30c3.pdf).

Therefore, we should choose the (significantly) faster BLAKE2b-256, to reduce the cost of hashing large transactions/blocks.

**Comment by daira** [comment]
The Ledger Nano S uses [an ST31H320 with 10 KiB of RAM](https://www.reddit.com/r/ledgerwallet/comments/63kgsa/comment/dfwazx3). This is still sufficient that the difference in RAM usage between BLAKE2s and BLAKE2b is unlikely to be an obstacle.

Note that EdDSA requires a hash with 512-bit output for which we are going to use BLAKE2b (see https://github.com/zcash/zcash/issues/2853), and so an implementation of that will be required in any case for doing shielded spend authorisation signatures.

**Comment by daira** [comment]
Let's call it "Replay-Protected Scalable Lightweight hashing" or "RPSL hashing".

**Comment by str4d** [comment]
Closed by #2903.
