### ISSUE TITLE
 Your client is out of date and potentially vulnerable to blockchain disruption.

### ISSUE THREAD

**Issue by lokialice** [zcash/zcash#2595]
when i type cmd: ./src/zcash-cli getinfo
i recieve
{
    "version" : 1000050,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 173488,
    "timeoffset" : 0,
    "connections" : 4,
    "proxy" : "",
    "difficulty" : 4522390.28825207,
    "testnet" : false,
    "keypoololdest" : 1503596854,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00005000,
    "errors" : "Your client is out of date and potentially vulnerable to blockchain disruption. Please update to the most recent version of Zcash and use -reindex to ensure integrity of your blockchain state. More info at: https://z.cash/support/security/"
}

please explain to me "error"? this is error of my system or not?

**Comment by str4d** [comment]
@lokialice that error is because you are running version 1.0.0, which has security vulnerabilities. You should upgrade to the latest release (which is currently 1.0.11). I can see you are compiling the source code; you can find instructions for upgrading here:

https://github.com/zcash/zcash/wiki/1.0-User-Guide#upgrading

**Comment by nathan-at-least** [comment]
Hi @lokialice we believe we've addressed your concern, so I will close this ticket. If you still have an issue with upgrading, feel free to post new issues here.
