### ISSUE TITLE
Fix "Result: None" on download page.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2608]
The download page for the binary tarball currently instructs users to verify the `sha256sum` and compare it against "Result: None".

There's probably some automation that has broken which updates this page. The most straightforward task would be to fix that automation… But:

Here's an edgier proposal: remove instructions to check the sha256sum hash of the software.

Rationale:

- The instructions and the download link are both hosted by `https://z.cash`. If an attacker could subvert the download tarball by hijacking the website, they could also subvert the instructions to change the hash. The hash on the webpage does not protect against this attack.
- The hash on the webpage is automatically generated through automation. If an attacker could subvert the creation of the tarball anywhere in the automated pipeline before this hash is computed, the automation will compute the hash of the malicious tarball, so it provides to protection against this attack.
- All modern download software should be able to distinguish correctly downloading a complete copy of a target URL versus being interrupted mid-download. Therefore, there's little integrity protection provided by manually comparing a hash.
- Asking users to jump through extra hoops with hexadecimals and hashes turns out to be a worn out and useless "best practice" in this case, so it actually is security theatre that takes extra automation work on our end plus extra busy work on the user's end.

Therefore, let's remove it, improve UX and avoid confusing users about security guarantees.

**Comment by kristovatlas** [comment]
I frequently search the web for file hashes to help build my confidence in said hash. Various websites will regularly mirror open source software, and what I want to see is that for a given version/build all are in agreement about the hash as well as my own.

I don't know how common this kind of practice is amongst the probably fairly sophisticated user base of your client.

**Comment by zmanian** [comment]
You frequently see users behind the Great Firewall of China sourcing large binaries from unofficial sources. Having a hash digest on the page might protect a subset of those users.

**Comment by arcalinea** [comment]
Discussed during meeting, we'll leave it on the website and fix the script that pulls the hash

**Comment by nathan-at-least** [comment]
Awesome. Both @kristovatlas and @zmanian provided uses I wasn't too aware of.

@zmanian can you tell me more about China? Do large files get mirrored/replicated inside the firewall merely because of bandwidth issues, rather than outright URL censorship? If the firewall is preventing access to https://z.cash in the first place, then the "trust anchor" of the hash is lost anyway. The only way it could help is if Chinese users go to our download site to see the hash, but fetch the tarball from elsewhere. Does that really happen?

**Comment by gojomo** [comment]
I tend to view the same bundle hash, if reported at multiple places/times, as more credible than even a hash from the single, authoritative 'trust anchor' page. 

Why? It's evidence that many people have all seen, and run, the same bundle over time. That is, I'm not being force-fed a tailored bundle unique to me, nor receiving the result of any potential recent 'trust anchor' compromise that no one else has yet had a chance to detect/be-victimized-by.

**Comment by radiogena** [comment]
how to fix it?

Fetching libsnark...
https://z.cash/depends-sources/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz:
**2017-09-12 15:46:05 ERROR 404: Not Found.**
2017-09-12 15:46:06 URL:https://codeload.github.com/ZencashOfficial/libsnark/tar.gz/3854b20c25e8bc567aab2b558dec84d45f4a3e73 [144924/144924] -> "/home/user/zen/depends/work/download/libsnark-/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.temp" [1]
/home/user/zen/depends/work/download/libsnark-/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.temp: FAILED
**sha256sum: WARNING: 1 computed checksum did NOT match**
funcs.mk:238: recipe for target '/home/user/zen/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash' failed
make: *** [/home/user/zen/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash] Error 1
make: Leaving directory '/home/user/zen/depends'

**Comment by ca333** [comment]
@nathan-at-least no same misbehaviour in europe (NL). The tarball isn't the legacy one unfortunately. and we are not willing to modify it to the "new" one unless it is known why github tarballs checksums change. this should never ever happen unless you modify the data which actually is a nogo. i contacted github just for the case they got a directed attack for this purpose. Other github repos are unaffected. I compared zcash, zclassic, komodo dependcies and all those libsnark repos are affected by a changed checksum althouth they have not been updated since the repofork (many months). For isntance libdb dependency hosted on oracle still has the same checksum.

`shasum -a 256 libsnark-9ada3f84ab484c57b2247c2f41091fd6a0916573.tar.gz
93eafebf315651006a37d086341e34b8e73bc33701157e77d9a423d99a7bec24  libsnark-9ada3f84ab484c57b2247c2f41091fd6a0916573.tar.gz`
according to the commit hash it was downloaded with it should be `dad153fe46e2e1f33557a195cbe7d69aed8b19ed9befc08ddcb8c6d3c025941f`

what other assumptions than an infiltrated or errorous github cloud-infrastructure would this allow? either way - something critical is going on. And it should wake us up - majority of the opensource proejcts, which all cryptocurrencies are, are being hosted on a centralized service (paradox).

**Comment by str4d** [comment]
The libsnark hash mismatch needs a new issue.

**Comment by radiogena** [comment]
Dear str42d, can you create a new issue properly? Thanks

**Comment by ca333** [comment]
just opened one - https://github.com/zcash/zcash/issues/2610

**Comment by arcalinea** [comment]
Closing this issue, since it was focused on the hash of the tarball on our download page, and we've decided how to proceed and fixed it.
