### ISSUE TITLE
Please help me.

### ISSUE THREAD

**Issue by Erosluvu** [zcash/zcash#2611]
Hello ZCash community,
I need some help about this: 
Txn is bf53c286fef54eb75ce2e94bd4946c65a8674b5a5cfecb047ff60a1ec3813976
Check in Zchain:
https://explorer.zcha.in/transactions/bf53c286fef54eb75ce2e94bd4946c65a8674b5a5cfecb047ff60a1ec3813976

I send 29 zec out,but about 60 ZEC was deducted.
It's almost all of my possessions.
Please give me some help.I begging you.

**Comment by gojomo** [comment]
The (transparent) transaction you've referenced shows ~60 ZEC *involved* – 29 ZEC goes to one address (which I assume is your intended target), and 31.18280018 ZEC to another 2nd address. 

Normally, such a 2nd address is an autogenerated address that's already managed by your own wallet software. Most payments need to unlock more source ZEC (from multiple earlier transactions) than you're sending to an intentional target, and any excess (aka 'change') is then returned to another address under your control. The best practice (for transparent-addresses as in Bitcoin or ZCash t-addresses) is to avoid reusing old addresses, so each change address is new & unique. 

You *won't* see this change value associated with your original address (as if looking at that address on ZChain etc), but you *should* see it in whatever software generated the transaction, which will be managing change addresses along with any addresses you specifically created or imported. That software should recognize (and be able to spend) the change amount.

If you launch (and allow to catch up to the blockchain) the wallet software that sent the transaction, do you then see the expected remaining balance? If so, those ZEC remain under your wallet software's management.  (Be sure to keep that software & its data both backed-up & updated.)

**Comment by gotope** [comment]
don't  worry, it's generate other "unspent" record, 
you can getbalance see it only deducted 25 ZEC in total

**Comment by Erosluvu** [comment]
I've found the second address in my wallet.

Thank you very much.

**Comment by arcalinea** [comment]
Thanks for the great answers, @gojomo and @gotope! Closing this issue now.
