### ISSUE TITLE
Chain Split Aware Address Encoding

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2658]
**Synopsis:**

Our goal is to provide maximal user protection around Zcash consensus-upgrading chain splits. One such way is to alter address encodings so that *both users and the protocol* can always distinguish post-split addresses on the upgrade side of a chain split.

**Concepts:**

A consensus-upgrading chain split occurs when some fraction of nodes enact a new backwards-incompatible set of consensus rules. For some non-zero amount of time, nodes are partitioned into two sets, those which enact the new rules and those which don't. We call the ledger maintained by the former the "upgraded ledger" and the latter the "legacy ledger".

This proposal reuses a *disjoint encoding scheme* where two disjoint sets can be encoded such that no two elements from either set encode to the same result, and also that which of the two sets are encoded is directly available in the encoded result.

This proposal is related-but-orthogonal to "bilateral hardfork protection", see https://github.com/zcash/zcash/issues/2254#issuecomment-296331664 

It's important to emphasize these concepts are value-neutral: there's no implications that "upgrade" is preferable to "legacy", the the split should or should not persist, etc… Those considerations are up to users, not developers.

**Proposal:** - status: hand-wavy

The proposal is for the upgraded rules on the upgraded side of the split to include these requirements:

a. For each type of address (ex: t-addr P2PK, P2PKH, P2SH, Sprout z-addr, etc…) that address type now has two kinds: the "legacy" kind, and the "upgraded" kind. [1], [2]
b. The serializations of secret keys, public keys, address-related-hashes (ex P2PKH, P2SH) are subject to a disjoint encoding where the legacy kind encoding is unaltered and the upgraded kind encoding is unambiguous.
c. All user-facing encodings (addresses, secret key WIFs) are disjointly encoded and *additionally required* to have user-identifiable distinction. These will most likely be unique prefixes.
d. The upgraded encoding for any entity can be derived from the legacy encoding.
e. All legacy address kinds are Receive-Deprecated. (See [terminology definition](https://github.com/zcash/zcash/issues/2248#issuecomment-335056686).)

**Implications:**

If these rules are properly specified, they should ensure that:

- legacy software can still operate with no change on the legacy chain.
- upgraded software can spend from all legacy address types with minimal changes to software.
- upgraded software can calculate the upgraded address for any legacy address *BUT MUST NOT DO SO AUTOMATICALLY*. (See Drawbacks below.)
- transfers on the legacy chain cannot be replayed on the upgraded chain, because of the Receive-Deprecation.
- transfers on the upgraded chain cannot be replayed on the legacy chain, because the upgraded addresses, hashes, pubkeys are invalid on the legacy chain.
- and, most importantly *users can tell which chain split they are making a transfer on by visually inspecting the receive addresses*.

**Drawbacks:**

This introduces some amount of busy work for users on the upgraded chain who wish to send funds when they only know the legacy address. In that case (because it's a requirement that software does not automatically do the translation) they must explicitly translate addresses. A barebones thought is a new rpc call to translate addresses.

A GUI can translate *with user verification*, example "you tried to send to $LEGACY_ADDR which is a zcash-sprout legacy address. Do you wish to send to the equivalent $UPGRADED_ADDR instead?"

I fear that software won't ask for user verification, or even if it does, users will train themselves to click through without thought (such as for older browser TLS-problem dialog fatigue). That makes me wonder if we should instead require that it is *not possible* to derive an upgraded encoding given a legacy encoding, and force all users to ask for new recipient addresses. That would indeed be cumbersome.

**Footnotes:**

[1] Some address types may be "receive-deprecated" in the new rules, in which case, they do not need a "upgrade" kind.
[2] Note that *each* backwards incompatible upgrade has it's own "legacy" vs "upgrade" distinction.

**Comment by daira** [comment]
I generally disagree that we should force users to pay the *substantial* cost of upgrading addresses for a hard fork that would not otherwise need to change them or that doesn't provide new address-based functionality. It's not necessary to achieve strong replay protection.

**Comment by daira** [comment]
In general this is making hard forks much more obtrusive and onerous for users than they need to be. For replay protection, why does a user care about anything other than the fact that their transactions can't be replayed on an unintended chain? They decide which is the intended chain by choosing which software to run, **not** on a per-transaction or per-address basis. The latter cannot work because different chains must have different chain states and therefore different data directories.

**Comment by daira** [comment]
Let's look at the claimed advantages in more detail:

> legacy software can still operate with no change on the legacy chain.

It can anyway whether or not new address types are introduced.

> upgraded software can spend from all legacy address types with minimal changes to software.

It can anyway if there is no new address type.

> upgraded software can calculate the upgraded address for any legacy address BUT MUST NOT DO SO AUTOMATICALLY. (See Drawbacks below.)

Unnecessary if there is no new address type.

> transfers on the legacy chain cannot be replayed on the upgraded chain, because of the Receive-Deprecation.

A bilateral hard fork (in which a given transaction or block is never valid on both chains) achieves this with or without new addresses. There are many ways to achieve a bilateral hardfork without changing addresses; one of the most straightforward is to change the block and transaction version numbers to something rejected by the old consensus rules, e.g. by making them negative.

> transfers on the upgraded chain cannot be replayed on the legacy chain, because the upgraded addresses, hashes, pubkeys are invalid on the legacy chain.

This is a complicated and intrusive way of doing something really simple.

> and, most importantly users can tell which chain split they are making a transfer on by visually inspecting the receive address

Alternatively, they can tell which chain they are making a transfer on by what software they are running. This is much less intrusive in the expected case where the legacy chain drops out of use almost immediately. In the case where there's a split, it will be either due to a bug, or because there's controversy that causes a software/project fork. In the case of a bug, the desired response is to fix the bug and not have to change addresses. In the case of a controversy, nothing stops promoters of either chain from doing a hard fork to change address prefixes. I predict that they won't do so immediately, because neither chain will want to take the usability hit in the absence of a compelling reason to upgrade address-based functionality. However, this still can't cause replays. Any attempt to replay a transaction on the unintended chain will fail. Furthermore, it would be possible to generate addresses with a short chain-specific vanity prefix, which would work without any software changes and would isolate the cost to users who are willing to pay it.

**Comment by radix42** [comment]
I second Daira's opinion on this and agree with all her points above. Additionally I'd like to just add that I have managed splitting off or using Bitcoin Cash from a variety of wallets with varying key types (hex, seed phrases, etc) and did not have any trouble with merely running the sw appropriate for the chain I wanted to use.

**Comment by daira** [comment]
Note also that if there is a change of address types on every hard fork, then either:
* there will be more than three "generations" of addresses in use at a time, or
* the minimum latency between hard forks must be substantially increased, in order to give enough time to remove the n<sup>th</sup> generation from use before introducing the (n+2)<sup>th</sup>.

**Comment by gojomo** [comment]
I'd see a value in a weaker, opt-in form of this idea. In particular, if 'upgraded' chain users have the *option* of writing their (same old) addresses in some new convention, it could serve as an extra guard against laggard users sending funds on an old chain. 

The motivating case I have in mind:

Person A accepts ZEC payments, and is a moderately-attentive Zcash user, running the software regularly and upgrading their software in a timely fashion. Thus, they move with the main chain across a hard-fork upgrade. Person B is an inattentive user – perhaps using some reduced-functionality mobile multichain wallet (which itself could lag in its updates or be abandoned). They only launch the wallet when they need to spend ZEC, perhaps only every few months or once a year. Person B is thus more likely to wind up on a 'legacy' chain, without even making any conscious choice-of-software. After a year away, B wants to repeat some purchase/donation to A, and maybe even asks A, "hey, is your address the same?" to re-verify the prior address. B launches their laggard wallet & sends on the legacy chain without any conscious decision to do so. 

If the more-attentive A has the option of sending a 'upgraded' address – which is perhaps just a different encoding of the same raw address – B can see an error from their waller, and then make a conscious choice to catch-up. 

This new encoding could just be a new prefix. But another more subtle option – perhaps too subtle? – would be for 'upgraded' software to change the address-checksum procedure – XOR with another mask as a final step? – but also accept old checksums with a warning. 'Upgraded' addresses would always fail checksumming in 'legacy' software; 'legacy' addresses would trigger a "this address was generated by older software, are you sure?" warning in 'upgraded' software. 

Of course, in the scenario above, A might just assume "the address still works, it's right there as my last transaction, I'll just add a new memo and go." Other techniques like 

More generally, this desire for address functionality seems to fit inside a 'super-cluster' of related address-convention possibilities that would express or enforce extra protective limits on address usage, to prevent fund misdirection/destruction:

* #716 address revocation
* #718 address expiry
* #570 diversified public addresses
* #340 address registration
* #1344 extensible payment addresses
* #2319 payment requests
* #2658 chain-split-aware address encoding (this issue)

Potential other techniques helping the same goals might be:

* addresses/payment-requests that specify addresses should only be used once
* addresses/payment-requests that expire early in the case of chain-split detections (#1922, #1925)
* addresses/payment-requests that only want to receive funds in some way that the sender can reclaim them, if the receiver doesn't affirmatively collect them within some set timeframe. (This seems possible in t-realm if/when it matches Bitcoin with CLTV, CSV, RLT functionality #2237, but would require other support in a shielded-realm.)

**Comment by daira** [comment]
I'm closing this as wontfix. Address formats can of course be changed if there's a technical reason to do so, but they won't be changed just because there's an upgrade. Reopen if you have new arguments that I didn't refute above!
