### ISSUE TITLE
Support Hierarchical Deterministic t-addresses (BIP 32)

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#2673]
[Edit by @daira: this ticket originally considered z-addresses, but most of the comments are about lack of support for BIP 32 in t-addresses.]
[Edited by @tromer to correctly reflect zcashd's state.]

I suggest changing all address generation to use [BIP 32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) / [ZIP 32](https://github.com/zcash/zips/blob/master/zip-0032.rst) derivation from the wallet seed.

For context, currently in, zcashd:
* New t-addresses are _randomly generated_ ~~are deterministically generated from the wallet seed (using [BIP 32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)).~~
* New Sprout z-addresses are randomly generated.
* New Sapling z-addresses are generated via [ZIP 32](https://github.com/zcash/zips/blob/master/zip-0032.rst)

Consequentially, if you restore a wallet from an old backup, you _may lose any ZEC held by a t-address or Sprout z-address generated after the backup was taken_.

This makes safe usage of _t-addresses and Sprout z-addresses_ awkward. Also, many users are used to BIP 32 HD wallets (e.g., essentially all mobile and hardware wallet use BIP 32 recovery seeds), and would not expect this difference.

This is a simple special case of #2038 ("Recovery Secret Seed").

**Comment by nathan-at-least** [comment]
I currently thought that the `zcashd` wallet *does not* use BIP32, and new t-addrs are randomly generated. I'll look into that.

Either way, we want deterministic generation of both to avoid loss of funds after a backup followed by dataloss.

**Comment by radix42** [comment]
Right now zcashd itself doesn't support BIP32 address generation, but quite
a few wallets, both light wallets and GUI front ends to zcashd, do

**Comment by gotope** [comment]
Is it true of that "will lose any ZEC held by a z-address generated after the backup was taken." ?

**Comment by tromer** [comment]
> Right now zcashd itself doesn't support BIP32 address generation

Oh wow. This is... unexpected. AFAIK essentially the whole Bitcoin ecosystem, and everything but `zcashd` in the Zcash ecosystem, have moved to BIP32 by default.

**Comment by daira** [comment]
Yeah, I would have liked finishing off BIP32 support to be a higher priority.

**Comment by str4d** [comment]
Bitcoin added BIP32 support internally in bitcoin/bitcoin#8035, in 0.13.0. I'll look into pulling it in, though I expect it will have additional dependencies.

**Comment by radix42** [comment]
I know that there are comments in the source to the effect of "don't count
on these HD address generation prefixes staying the same" but a ton of ZEC
wallets ARE relying on them to do just that. So while zcashd itself doesn't
generate HD wallet addresses, the community is now relying on those
constants that are enshrined in chainparams.cpp

**Comment by daira** [comment]
The current status is that all Sapling addresses are generated by the zcashd wallet according to ZIP 32. Sprout addresses are not, and t-addresses are not generated according to BIP 32.

**Comment by LamassuSupport** [comment]
Our crypto ATM operators run zcashd nodes in order to offer Zcash to their end users.

Of the six coins we support, Zcash is the only one whose funds cannot be reliably restored by making an initial backup of the wallet, due to the lack of this feature.

Support for HD t-addresses would aid in avoiding ZEC loss scenarios for our operators if they lack a current backup. We'd be much appreciative if this were prioritised for inclusion. Thanks!

(If possible, it would be great if existing wallets could be made to derive new HD addresses following an update to a supporting zcash release, so that a fresh wallet need not be created to benefit.)

**Comment by str4d** [comment]
As part of adding Unified Address support to `zcashd`, we will be addressing this issue.

**Comment by str4d** [comment]
The plan here is:

- Implement HD derivation of transparent addresses.
- Root that on the BIP 39-compatible seed from #5176.
- Use account 0 specifically for HD derivation via existing legacy RPCs (i.e. `getnewaddress`), so that those addresses don't collide with t-addrs contained inside Unified Addresses.

**Comment by str4d** [comment]
Update: we decided to use 2<sup>31</sup> - 1 instead of 0 for legacy derivation, which will fit better with how mobile wallets currently generate shielded accounts.
