### ISSUE TITLE
How to check the amount for each taddress in one wallet

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#2678]
Is there a command for this operation to check the amount for each taddress in one wallet?

**Comment by tromer** [comment]
The closest I know of is using `listunspent` to show individual unspent transactions, and then summing the amounts for each t-address.

Conceptually, this should not be needed: the bitcoind philosophy, inherited by zcashd, is that all t-addresses are tributaries going into a joint pool, and outgoing transactions use utxos arbitrarily from this pool. Unfortunately, zcashd breaks this model because `z_sendmany` requires specifying a single, specific source address (see #2408, https://github.com/zcash/zcash/projects/15).

**Comment by ioptio** [comment]
You can use `listreceivedbyaddress 0 true`.

Bitcoin RPC for reference: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list

Let us know if this is what you're looking for.

**Comment by tromer** [comment]
@ioptio, `listreceivedbyaddress` shows all transactions (grouped by address), while `listunspent` shows just unspent transactions (not grouped by address).

The RPC is so non-orthogonal it would make baby Euclid cry.

**Comment by ioptio** [comment]
`z_getbalance` works for both z and t addrs and is documented in the payment api https://zcash.readthedocs.io/en/latest/rtd_pages/payment_api.html#accounting
