### ISSUE TITLE
Source changes under src/snark are not picked up without make clean

### ISSUE THREAD

**Issue by daira** [zcash/zcash#2689]
### Steps to reproduce:
1. Run ``zcutil/build.sh``.
2. Make an edit to a file under src/snark, e.g. ``src/snark/src/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc``.
3. Run ``zcutil/build.sh`` again.
4. The source changes are not picked up.

The problem is that the source file has been copied to, e.g. ``src/snark/build/include/libsnark/zk_proof_systems/ppzksnark/r1cs_ppzksnark/r1cs_ppzksnark.tcc``. That copy does not have the edit, and nothing in the Makefiles declares a dependency on the original source file.

Running ``make clean`` before the second build works around the problem.

This might also occur for other in-tree dependencies. I'm not sure why we should need to copy the source files at all.

### Expected behaviour
``make clean`` should not be necessary. Needing to run ``make clean`` to be confident you have a correct build defeats the point of having an incremental build system. This significantly slows down development or debugging, or leads to false conclusions about code behaviour that could be security-relevant.

(Yes, I know that one should not generally assume that Makefile dependencies are correct, and of course release builds should be done from scratch.)

### The version of Zcash you were using:
lowmemprover branch, but I think it happens also on master now.

**Comment by syd0** [comment]
Hi @daira - since libsnark is now in-tree, do you want to maintain the behavior of copying the files into a build directory? I was thinking that I could leave them in place, build the object files in the build directory, and just have everyone's #includes point to the original headers.

I can maintain the current behavior of copying everything into the build directory and getting dependency builds to work correctly, but avoiding the copy seems cleaner to me.

Any preference?

**Comment by daira** [comment]
Avoiding the copy is preferable.

**Comment by str4d** [comment]
We *might* be able to get away with renaming `src/snark/src` to `src/snark/libsnark`. However, libsnark itself uses a bunch of non-prefixed relative includes, and IDK how those will react. Upstream libsnark has already done the legwork to change all those to non-relative library includes (as well as the folder rename), possibly along with other necessary changes. There's a point at which we should consider just migrating to upstream, instead of expending significant duplicated effort.

**Comment by daira** [comment]
If it's easier to wait until we migrate to a later upstream libsnark before fixing this issue, then I'm okay with that. But I'm a little confused: we have other in-tree libraries such as libsecp256k1 that are built in-place without copying source files. libsecp256k1 has the same "src/.../src" directory structure and uses relative includes. I think we should just make libsnark work however that works.

**Comment by daira** [comment]
I just confirmed that libsecp256k1 does not exhibit the problem in the issue description.
