### ISSUE TITLE
Update libsodium.mk

### ISSUE THREAD

**Issue by hellcatz** [zcash/zcash#2693]
libsodium-1.0.11 is a dead link now
https://download.libsodium.org/libsodium/releases/

See https://github.com/hellcatz/zcash/commit/44603b9450c5170617891c80ad7e523ee4fd8174

Maybe update for libsodium-1.0.15 ?

**Comment by daira** [comment]
There seems to be nothing mentioned in the [release notes](https://github.com/jedisct1/libsodium/releases) that could cause a compatibility problem or regression, except possibly that a new implementation of ChaCha20 will be used on platforms that support AVX2 (since libsodium 1.0.12):

> AVX2 implementations of Salsa20 and ChaCha20 have been added. They are twice as fast as the SSE2 implementations. The speed gain is even more significant on Windows, that previously didn't use vectorized implementations.

We use ChaCha20 for note encryption.

There don't appear to have been any security fixes that affect us since 1.0.11. Despite that I think it's a good idea to avoid falling too far behind the current release.
