### ISSUE TITLE
Faster download for proving keys

### ISSUE THREAD

**Issue by l0k18** [zcash/zcash#2695]
I am waiting already almost an hour and still two hours more to go, to get that thing. Seriously, this is a problem. Why is it not being hosted on torrents? I have a 9Mb/s connection. I should have 868Mb in under 5 minutes.

I would be more than happy to contribute to a swarm of torrent seeds to make this happen.

**Comment by gojomo** [comment]
Some previous mention of p2p download potential at #1155 & #1296. 

If a (trackerless) torrent existed with just the two key files, and a `README` explaining where to put them (`~/.zcash-params/`), then perhaps the `https://z.cash/download.html` page could list that as an option with the magnet-link. IIUC, the fetch-params script when then run will not re-download, but *will* verify the keys' expected hashes. 

(Perhaps also, `fetch-params.sh` script could itself print a message before beginning its `wget` to the effect of: "if downloading is slow and you'd rather use BitTorrent, use [magnet-link] then follow directions in README and finally re-run `zcash-fetch-params`.)

**Comment by colibrae** [comment]
I have it running now on this magnet magnet:?xt=urn:btih:3B48FD96DDFB0C8C4E06679DD929B0BE6641EBBD&dn=sprout-proving.key&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce

**Comment by daira** [comment]
I'm opposed to having any documentation that tells users to put parameter files directly in the location they are expected by ``zcashd``, because that creates an unnecessary security failure mode if the file is not correct.

It's an unnecessary failure mode because there are at least two alternatives that solve the same problem without the security vulnerability:
1. We could tell users to put the parameter file(s) in some other well-known location, and have ``zcash-fetch-params`` move them from there to the place expected by ``zcashd`` only if they have the correct hash. This would only be a small change to ``zcash-fetch-params``.
2. We could have ``zcashd`` itself check the hash of the proving key before using it. In order to avoid a TOCCTOU vulnerability, it would be hashed as it is being loaded into memory rather than loaded twice. In that case it would be easiest to hard-code the verifying key (#1335).

**Comment by gojomo** [comment]
(2), having `zcashd` check the proving-key, seems the strongest protection against any kind of user error. 

But, there's still the issue of filling the default location with the right keys. If there's the (2) check, documenting (as non-default possibility) that a user can manually drop valid files into the right place involves very little risk/complication.  (I'd view such docs as similar in overall risk/complication as expanding `fetch-params.sh` with an extra local-to-local copy/move option or more exotic p2p fallbacks.)

I'd also see the most user-friendly approach as eliminating the `fetch-params.sh` script entirely, rather than expanding its complexity. Running `zcashd` alone could, if the needed parameters are missing, download and cache them. If this is slow or the canonical URLs unreachable, there'd be enough logging during the slowness/failure to suggest to the user alternate steps, such as a cmd-line option to specify an alternate URL or local-path.
. 
Out of curiosity, what's the risk of an installation using a bad proving key – a (loud?) failure to follow the blockchain? O an actual loss-of-funds, perhaps via a malicious proving-key tricking the node into broadcasting degenerate secret-revealing transactions?

**Comment by daira** [comment]
@gojomo wrote:
> Out of curiosity, what's the risk of an installation using a bad proving key – a (loud?) failure to follow the blockchain? Or an actual loss-of-funds, perhaps via a malicious proving-key tricking the node into broadcasting degenerate secret-revealing transactions?

The deserialization code in libsnark hasn't been audited for malicious input handling other than for the case of deserializing proofs, so I would conservatively assume undefined behaviour.

**Comment by radix42** [comment]
As an aside, my GUI wallets for zcash and forks that use a full node all
check its hash, download in the GUI if its missing, and some of them
download from a faster CDN rather than from Amazon s3. I also ship the tiny
verification key with the installer since its so tiny.

**Comment by daira** [comment]
Note that ``fetch-params.sh`` [does not](https://github.com/zcash/zcash/blob/master/zcutil/fetch-params.sh#L73-L99) currently check the hash if each file is already present at its final location, so copying them there and then running ``fetch-params`` is not sufficient.

**Comment by gojomo** [comment]
@daira Aha, I'd misread the script. Verifying even when the preexisting file is detected seems a reasonable idea, though – at least until/unless a hash-check is added inside `zcashd` instead.

**Comment by daira** [comment]
As well as #1155 and #1296, see also #2514.

**Comment by colibrae** [comment]
zcash4win verifies the proving key, this might be a good place to find the best method to do this. why does zcashd not do this? (it could even be onchain, the hash of the correct current proving key)

**Comment by tromer** [comment]
@colibrae, `fetch-params.sh` of zcashd does check the `sha256sum` of the keys.

**Comment by russianboss69** [comment]
for fast synchronization of the zcash blockchain you can download the blockchain in the archive:
mega.nz is a good replacement for torrent due to high speed

https://mega.nz/#!HSJByCzI!Wgqy_xoWWEyXGkp4rCot4y5fXmH4LRFIIhKR317Zd_c
Zcash Blockchain (12.7 Gb.)
Blocks: 565659
Date: 2019.07.11

for use, simply replace the folders "blocks" and "chainstate" in "C:\Users\Home\AppData\Roaming\Zcash"

**Comment by ageis** [comment]
@russianboss69 that link is dead; is anyone aware of where I can download the ZEC blockchain? found a torrent with no seeders, so far no luck.

**Comment by daira** [comment]
This would be mostly obviated by #3933 / #6661. For the remaining optional use of `sprout-groth16.params` there is not sufficient justification to implement this issue.
