### ISSUE TITLE
zec-addresses - belongs to which wallet?

### ISSUE THREAD

**Issue by martinpeterbauer** [zcash/zcash#2706]
In Bitcoin - i can get several usable addresses which are all different to each other - belonging to the same wallet(address). If i make 2 addresses A and B and someone transfers coins to A - i can send that money by using A or B - because this addresses belongs to the same wallet. This is how it works to give the addresses to foreign people (e.g. customers) to know who did send money to my wallet (paid the bill).

In zcash - is it the same? I have a zcash node running.... synchronized on mainnet .... 

I made a few tests - have got 4 addresses (2 by calling z_getnewaddress and 2 by getnewaddress). let's name them: tA, tB  and zA,zB

I send money to tA and i was expecting to "see"  that money balance for tA and tB - even for zA and zB. But i can only see a balance for tA address by using "z_balance". Trying to send money from tA works .... but sending from tB does not work - due to "no balance" ....

Is this true? am i wrong? How to manage to get "different" addresses belonging to the same "wallet"?

Regards, Martin

**Comment by radix42** [comment]
some bitcoin wallets send using commands that do not specify which address
you send from, such as "sendmany" and "sendtoaddress", both of which ARE
still present in zcash, but only work sending from and to t-addresses. They
also will send from more than one address at the same time, and I use them
somewhat frequently. This is also good for consolidating balances into one
taddr before sending to a zaddr.

**Comment by martinpeterbauer** [comment]
Thank you. So - it is like ETH/ETC and not like BTC -  one z-address belongs to it's own balance...

This makes it a bit more complicate to distinguish the received amounts... and i have to consolidate after the customer has paid to 'his' zec-address ....  to a zec-address of the shop system...

**Comment by radix42** [comment]
its exactly like bitcoin core was at version 0.11.2, which is when zcash
forked from bitcoin

**Comment by radix42** [comment]
in that way at least

**Comment by martinpeterbauer** [comment]
There is a difference .... balances from one t oder z-address belongs to exacly this t/z-address and not to any other t/z-address. With bitcoin - i have several addresses belonging to the same balance. So i can not use the addresses to distinguish between paying customers and having 'in one step' all the balances combined.

**Comment by str4d** [comment]
The issue you are having is not one of accounting, but of differing usability.

Bitcoin had a (now-deprecated) "accounts" system, whereby multiple addresses could be allocated to accounts. We disabled that in Zcash, instead going for per-address balances. The `z_*` RPC methods are all written with that in mind, so e.g. `z_getbalance` takes a single address and returns the balance of that address. If you are trying to use the `z_*` RPC methods, you will need to design your code from an "addresses have own balances" point-of-view.

If you are solely using t-addresses, you can still however use the Bitcoin model of "all addresses contribute to the same wallet pool", by using their RPC methods (that we inherited), which give minimal or no control over the inputs used. Just to be clear, though: this is simply a UI choice. In the backend, transparent Bitcoin-style addresses have balances belonging solely to those addresses, just like our z-addrs; the Bitcoin RPC methods just get their inputs from any address in the wallet, instead of only the address specified.

**Comment by martinpeterbauer** [comment]
Thanks to all for the clarification.
