### ISSUE TITLE
List all commits in final release notes

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#2755]
Our current policy is that we make an RC the week prior to a release, and the release itself only differs by version increments. The current `make-release.py` fills the release notes with a diff to the previous release tag, meaning that we generate the following release notes:

- Version `X-rc1`: `(X-1)..X-rc1`
- Version `X-rc2`: `X-rc1..X-rc2`
- Version `X`: `X-rc2..X`

We should alter `make-release.py` for non-RCs to diff back to the previous non-RC. This would give us the following:

- Version `X-rc1`: `(X-1)..X-rc1`
- Version `X-rc2`: `X-rc1..X-rc2`
- Version `X`: `(X-1)..X`

We could additionally just not create release notes for RCs.

**Comment by arcalinea** [comment]
Hm good point, right now all the substantive commits are falling into the release notes for `rc1` of whatever release we're on. 

I think it's cleanest if we don't do release notes for RCs, since any changes we make based on feedback or bugs found in RCs will get included in the notes for the next release anyways.

**Comment by daira** [comment]
I think we *should* include release notes for RCs according to @str4d's original suggestion.
