### ISSUE TITLE
Build native GUI clients

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#2838]
I think no one disagrees that the current situation is problematic.

Zcash makes the [daemon and the Linux CLI](https://github.com/zcash/zcash).
@kozyilmaz ports the [macOS daemon and CLI](https://github.com/kozyilmaz/zcash-apple).
@vaklinov makes the [swing GUI wallet written in Java](https://github.com/vaklinov/zcash-swing-wallet-ui).
@radix42 ports the daemon and CLI for both macOS and Windows, while adding a tweaked version of Vaklinov's GUI and packaging them as [zcash4mac](https://zcash4mac.com/) and [zcash4win](https://zcash4win.com/).

While everyone has done a great job on their respective end, it is obvious that this is unsustainable, as well as produces confusion to users.

I propose Zcash endorses and builds native GUI clients using a modern, fast and cross platform language. I suggest the use of [Swift](https://swift.org/about/#swiftorg-and-open-source).

The result is a modern looking and responsive client with feature parity that runs on Linux, macOS and [Windows](https://github.com/apple/swift/blob/master/docs/Windows.md).

**Comment by iScrE4m** [comment]
Just to bump this up and stress the urgency a bit more:

18th December 2016 - latest zcash4mac commit
6th January 2018 - swing GUI wallet depracted

**Comment by rex4539** [comment]
Can we please bump this?

I don't think it's such a big deal to hire a serious professional company to design and implement a cross platform wallet.

All Zcash GUI wallets are currently deprecated, while their design and performance is, arguably, horrible.

**Comment by naconner** [comment]
With all respect to the authors and due thanks for their contributions thus far: now that the three GUI implementations are deprecated (Zcash4Mac and SwingWallet) or experiencing issues (Zcash4Win), we get to see just how many users relied on third party wallets with a single maintainer to conduct the crowning feature of Zcash.

I'm fine myself with the cli, though Satoshi's first Bitcoin wallet was written for Windows for a reason: that for adoption we must make usage as simple and accessible as possible. And in the case of Zcash, that is conducting shielded transactions, its raison d'être.

Obviously to their credit, the Zcash team has made tremendous strides for what is still a nascent currency, now only a little over a year old. The Sapling upgrade will bring down the overhead to process a shielded transaction so that modern cell phones can accomplish the task, and delegated proving can eliminate that need altogether. I hope these both result in a Cambrian explosion in shielding-capable wallets that make an officially maintained GUI wallet irrelevant.

That the Zcash Foundation is pursuing their own independent node implementation, funding improvements to the above three GUI wallets, commissioning a new mobile wallet, and funding another node implementation provides me with confidence on their direction here:

- https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues/16
- https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues/32
- https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues/21#issuecomment-334900761
- https://github.com/ZcashFoundation/GrantProposals-2017Q4/issues/7 (withdrawn by requestor)

Still, I wouldn't want to see Zcash lose ground in the meantime due to retrograde progress in its available implementations that are accessible the average user. I would advocate that reasonable development resources be allocated to further shielding-capable GUI wallet support, native or independent.

**Comment by rex4539** [comment]
Did anyone say "bump" today?

**Comment by naconner** [comment]
@rex4539 Two revamps were announced today by @johanssonlc and @radix42:

https://github.com/johanssonlc/zcash-full-node-wallet ([tweet](https://twitter.com/johanssonlc/status/970399701089611778))

and http://winzec.com/ ([tweet](https://twitter.com/johanssonlc/status/970399701089611778))

**Comment by rex4539** [comment]
@radix42 essentially announced he's stopping support for zcash4mac and zcash4win and there will be several months of development for a new Windows only(?) version... At lest the name implies it's just for Windows. While I do appreciate that he's building something new, I sure hope it will be cross platform.

I have been trying to compile the other Swing wallet port from @johanssonlc since yesterday but [fails on my machine](https://github.com/johanssonlc/zcash-full-node-wallet/issues/1). It is though just another flavor of the same Swing wallet from @vaklinov

My request is to build native GUI clients.

**Comment by rex4539** [comment]
I have given up hoping that ECC could ever prioritize building GUI clients in-house. Retracting.
