### ISSUE TITLE
Add z_listunspent RPC call

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2910]
To enable users to diagnose wallets and tackles issue such as #2856 it would be useful if a user could list their unspent notes via a call such as `z_listunspent`.  This functionality would be similar to `z_listreceivedbyaddress`.

**Comment by nathan-at-least** [comment]
+½

I like this feature because it matches `listunspent` so it's easy for me to reuse that knowledge.

The only argument weakly against it is that we could extend `z_listreceivedbyaddress` to include a `spent` boolean in the outputs and/or to take an input parameter to filter out spent items. However, `z_listreceivedbyaddress` would still be limited to a single address at a time, unless we further extended its API.
