### ISSUE TITLE
z_listreceivedbyaddress show spent transaction

### ISSUE THREAD

**Issue by hocokbkapmahe** [zcash/zcash#2911]
I use z_sendmany to send coins from z address. Like:
z_sendmany ("address" => $to_Taddr,  "amount" => $amount),1,$fee

But when I do
z_listreceivingbyaddress I see "incoming" transaction what was spent from this Z address.

**Comment by hocokbkapmahe** [comment]
P.S. I send all coins from Z address to T address. I send 0.00243011


Now I see incoming transaction in T address:
https://zcash.blockexplorer.com/tx/8b80c9bfe940023a469e1ab976b9abd865633ab66b84bbc9d903ffed335b8008

z_listreceivingbyaddress show me:

>   {
    "txid": "8b80c9bfe940023a469e1ab976b9abd865633ab66b84bbc9d903ffed335b8008",
    "amount": 0.00243011,
    "memo": "f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "txid": "8b80c9bfe940023a469e1ab976b9abd865633ab66b84bbc9d903ffed335b8008",
    "amount": 0.00243021,
    "memo": "f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  },

**Comment by radix42** [comment]
That is the change from the transaction, as zaddr’s, unlike taddr a, don’t
send to a new change address

**Comment by hocokbkapmahe** [comment]
Ok, but I spent all coins from z address. 

> /zcash-cli z_getbalance "zcX8Q7Yx......
0.00000000

**Comment by bitcartel** [comment]
@hocokbkapmahe What does `z_gettotalbalance` show?  Also, using `z_getbalance`, apply each address from `z_listaddresses`.

**Comment by nathan-at-least** [comment]
I would not expect two different output notes sent to the same address within the same transaction as https://github.com/zcash/zcash/issues/2911#issuecomment-360946656 indicates. (Tangentially, I just filed #2932 which would distinguish the different notes within a single transaction by including their js index/output index.)

How could this happen?

- The output note selection logic might choose to do this. This would surprise me. Whichever dev works on this issue should review that code and then argue it is or is not possible with source links.
- The caller might include the same destination address multiple times in the `z_sendmany` destination array, which help docs call `amounts` in the second parameter. @hocokbkapmahe can you check whether the same destination address was included twice in the `z_sendmany` call?
- A bug in `z_listreceivedbyaddresses` or the wallet database that duplicates results. (Seems like the two are different, due to a subtly different `amount`.
- Other causes?

Note in the second case, a user may rely on the fact that they can include the same destination multiple times in order to provide different memos or for other reasons. Something to ponder…

**Comment by Eirik0** [comment]
Here's a bit of an update - 

I am able to recreate this issue. I start with a zaddr with 4 notes with values of 0.00000001, 0.00000010, and then 2 larger notes which sum to 0.00243011. If I then send the total balance of 0.00243022 to another address, the zaddr I am sending them from will now have 2 new received transactions with default memos and the same txid with the amounts listed above.

I am still researching if this behavior is incorrect.

**Comment by Eirik0** [comment]
This behavior as described above is expected. In sprout, it is only possible to consume 2 notes at a time. What we are seeing is a consolidation of notes to satisfy this restriction. In sapling this constraint is lifted and we will not see this same behavior.

**Comment by lindanlee** [comment]
We're closing this ticket. Feel free to reopen if the above comment didn't address your concerns. Hope it works out!
