### ISSUE TITLE
Rename auto-senescence to something which is more obvious to users

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2927]
We had a discussion today talking about auto-deprecation of Zcashd.  It was quite telling that nobody in the conversation referred to the feature by its proper name.

The actual name is auto-senescence.  However this is hard to type and most people need to look up* what senescence means in a dictionary, because its a scientific term lost on non-biologists.

Thus I imagine many users simply ignore the option completely... and panic when the node suddenly shuts down because it auto-senesces (that was hard to type).

Let's rename the option to auto-deprecation or something similar, so that users are aware that they must manually disable the feature to avoid having zcashd shut down on its own.

*aka Google

**Comment by gojomo** [comment]
It's not quite 'auto-deprecation' because that typically means "discouraged and possibly breaking soon but still for now working". An attention-grabbing term (though still not quite right) could be 'timed self-destruct'. Maybe 'auto-quarantine' or 'auto-expiration'?

Perhaps, though, clearer logged error messages around any auto-senescence-triggered failures would best clear up any confusion. Such messages could include both encouragement-to-upgrade, and a pointer to the senescence-disable option as a (discouraged) workaround.

**Comment by nathan-at-least** [comment]
I'm +1 on renaming to help users and ourselves. Maybe "deprecation" is good enough?

**Comment by zookozcash** [comment]
Yeah, maybe leave the "auto" out of it and tell users this is the "expiry" feature.

**Comment by leto** [comment]
Let's call it what it really is, Seppuku :
 
"to die with honor rather than fall into the hands of their enemies"

https://en.wikipedia.org/wiki/Seppuku

The whole point of this is to shut down before some horrific bug or exploit is found in old software, so Seppuku seems to fit the bill.

**Comment by daira** [comment]
Vetoing seppuku. First, it would be cultural appropriation; second, I oppose using any reference to suicide of any kind as a metaphor.

**Comment by gojomo** [comment]
'Apoptosis' could be an accurate word to borrow from biology, though not helpful for the many users likely unfamiliar with the word/concept.

**Comment by daira** [comment]
If I remember correctly, "apoptosis" was considered and rejected as too obscure/unfamiliar before we settled on "auto-senescence".

**Comment by daira** [comment]
+1 for just "expiry".

**Comment by nathan-at-least** [comment]
How about "autoshutdown" or "auto-shutdown" because that focuses on what it does, explicitly, and seems quite clear? Hm, it doesn't clarify why something is shutting down.

My second favorite is "expiry" although I feel that doesn't clarify what actually happens for many users (and it miiight be confused with transaction expiry?).

So what about a "*-shutdown" variant that makes it clear why it is shutting down, so that both the why and the what are in the term?

(As an aside: I personally like analogies from biology or cultural practices or elsewhere because I find it fun to make those connections, but I think they always tend to add confusion for many users, and can be otherwise problematic as @daira points out.)

**Comment by zookozcash** [comment]
How about "end of support" or "end of life"? What term does Microsoft use for no-longer-supported code?

**Comment by nathan-at-least** [comment]
I propose this terminology:

- **end of support halt**: The general feature by which `zcashd` shuts down at a given statically defined block height. This is defined independently for each release.
- **end of support halt height** or for short **EOS height**: The block height a specific release is programmed to halt at. (This is `zcashd` release specific.)
- **end of support date** or for short **EOS date**: The approximate future date or specific past date of a given EOS height.

This terminology has these benefits:

- *halt* is a very common and unambiguous English term for software behavior that is accurate and I expect most users will quickly comprehend.
- *End of service* makes it clear that this code feature is also matched directly to our social offer of support and vice-versa.

Because terminology selection can spiral forever if we seek perfection, I'm going to set a one week timer on this, and unless anyone has raised a "red flag" we'll proceed with it, even if there are warts or different-but-maybe-better proposals.

One week from now is 2018-05-25 and should be enough time to make a consistent terminology transition in time for the 2.0.0 release series.

**Comment by nathan-at-least** [comment]
Ok, no one raised any "blocker" level objections, so let's proceed with this new "End of Support *" terminology. I'll close this as resolved and open other tickets for actual code/doc changes.

**Comment by ioptio** [comment]
In "end of support halt", the words end and halt are redundant. Why not just "end of support" as the name of the general feature?

**Comment by daira** [comment]
"End" refers to the end of the support period, and "halt" refers to what the software does after that point. So they are not redundant. (Most software *doesn't* halt after the end of the support period.)

**Comment by radix42** [comment]
Standard corporate "enterprise" aka closed source universe terminology would be to call it End Of Life (EOL), which does fit the situation here fairly precisely

**Comment by nathan-at-least** [comment]
My thinking is that "end of support" means the human devs and company stop offering support effort, whereas "halt" is the specific behavior of the software. Typically many products reach an end-of-support period without literally halting.
