### ISSUE TITLE
generate z-private-key from natural-language words

### ISSUE THREAD

**Issue by openalmeida** [zcash/zcash#2928]
Hi, 

Output of `./src/zcash-cli z_exportkey ` (common generate way) is not friendly to remember.

I known it is risky, but any way the final of keep the output is user's own call,
such as print on paper and locked to nightstand, or encrypted as a file by password.

They are not real difference from generate private key from nature word(s),
but user can leave away the depends of zcash-cli (act as a middleware behind common generation),
and just depends on brain.

So, could anyone explain how z-private-key generated ?
Before submit this issue,
i've found t-key's generation from nature word(s),
because it is not much difference from Bitcoin private key.

But z-private-key's generation seems need zero-knowledge stuff,
God knows i am a Math expert.

**Comment by daira** [comment]
This is essentially #18 or #2040, which were closed because there was agreement that if users choose their own passphrases, they would not realistically be able to choose passphrases with sufficient entropy. Another data point is the [disastrous recent experience](https://twitter.com/nic__carter/status/954950774534090752) of IOTA with this idea.

If you meant that a wallet would generate a root key and provide a readable backup seed to the user, on the other hand, that is #2039.

**Comment by daira** [comment]
Closing since this is adequately covered by existing tickets.
