### ISSUE TITLE
Ecosystem-wide standard transaction fee

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#2942]
Establish an ecosystem-wide convention that all transaction fees are the same (currently 0.0001 ⓩ — 100 microZECs), whether for transparent or shielded transactions, and regardless of any other considerations. (This is for _normal_ transactions, initiated by an end-user through a normal wallet or service. It does _not_ have to apply to transactions that are being generated by some special-purpose code for some special-purpose application, by an expert.) But for all normal users, they should get used to the fact that regardless of which Zcash wallet, product, or service they use, that they always pay exactly 0.0001 ⓩ per transaction that they initiate.

The reasons for this are:

1. Privacy. If your software chooses a non-standard fee, this leaks information about you.

2. User experience. If users can expect a simple, fixed, predictable, low fee then this increases Zcash's usability for them.

Steps to accomplish this:

1. Publish documentation recommending this to third parties who make Zcash products and services. In particularly, recommend to them that the Zcash transaction fee _should not_ be configurable by the end user.

2. Either remove `estimatefee` or fix it to return 0.0001. https://github.com/zcash/zcash/issues/2552

3. Fix `sendmany` and `sendtoaddress` to return 0.0001. (Was https://github.com/zcash/zcash/issues/2551 &mdash; closed as duplicate of this ticket.)

Notes:

* If someone launches DoS attack that attempts to leverage this fixed-fee feature, then the miners will doubtless apply patches to discriminate against the DoS transactions, and we can of course help them understand how to do that if necessary. But we don't need to spend energy and complicate the protocol currently in order to prepare for that eventuality.

* In the future, we want to reduce the ecosystem-wide default fee from 0.0001 ⓩ (100 microZECs, which is about $0.045 at today's exchange rates) to 0.00001 ⓩ (10 microZECs, which is about $0.004 at today's exchange rates). In order to prepare for that, it might make sense to go ahead right now and recommend that third parties call `estimatefee` and use its return value as the fee (https://github.com/zcash/zcash/issues/2552). That way if we in a subsequent upgrade change it from returning 0.0001 to returning 0.00001 then all compliant products/services will do the right thing immediately.

**Comment by daira** [comment]
Another advantage not mentioned above: if the fee is fixed then miners have no reason to discriminate between transactions based on fee, which would cause upward price pressure on fees. (It's like a buyers' cartel.)

**Comment by mms710** [comment]
This should probably have a ZIP before we move forward.

**Comment by Mitchellpkt** [comment]
Interesting proposal, the "_every transaction will cost X_" property is a nice touch and would be a good selling point for Zcash. :- )

Removing the on-chain fee market will lead to off-chain user<-->miner interactions; is this considered a good thing, or bad thing? At this time I don't have a strong opinion either way.

(pondering:) Miners will be strongly incentivized to switch to pools that are accepting priority payments off-chain, since their profit margins and payouts will be greater than pools without the second income stream. The tricky part is that users who need to send Zcash during times with high transaction volume might find it challenging to obtain a spot on the chain unless they make a deal with some third-party block producer (which creates OpSec risks, KYC pressure, etc).

Regardless, I'm definitely in favor of preventing software fingerprinting due to unusual fees. Specifying and enforcing a few ecosystem-wide standard fee levels seems like a good move.

**Comment by daira** [comment]
Fixed by ZIP 317 and #6345.
