### ISSUE TITLE
Bump protocol version before releasing Overwinter with testnet activation height baked in

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2969]

**Comment by bitcartel** [comment]
Testnet: A 1.0.15 node with PROTOCOL_VERSION = 170003 on testnet will fork at the testnet activation height away from 170002 testnet nodes.

Mainnet,: A 1.0.15 node with PROTOCOL_VERSION = 170003 will connect as normal to <= 1.0.14 nodes running 170002.  Nothing will happen as the mainnet activation height has not been set in the code.

When 1.1.0 is released, which has the mainnet activation height, we need to change and set both OVERWINTER_PROTO_VERSION and PROTOCOL_VERSION to 170004, since 1.0.15 nodes running 170003 will always be on Sprout.  (Except for the case of testnet above).

Q. After testnet activation, if a fresh 1.1.0 node is launched and it needs to sync the testnet chain from scratch, can it do so?

Does this sound right

**Comment by str4d** [comment]
Yes:

- If the 1.0.15 testnet activation goes smoothly, then all the 1.1.0 nodes will be doing is increasing their protocol version number, which will mean it is trivially greater than the 1.0.15 protocol version number on testnet and thus not subject to its eviction policy.

- If the 1.0.15 testnet activation fails and we reset the testnet for 1.1.0, then the discussion is moot.

**Comment by str4d** [comment]
See https://github.com/zcash/zcash/pull/2919#pullrequestreview-98610149 - I'm now not certain the above analysis is correct for the "goes smoothly" case.

**Comment by daira** [comment]
@bitcartel wrote:
> Testnet: A 1.0.15 node with PROTOCOL_VERSION = 170003 on testnet will fork at the testnet activation height away from 170002 testnet nodes.
>
> Mainnet: A 1.0.15 node with PROTOCOL_VERSION = 170003 will connect as normal to <= 1.0.14 nodes running 170002. Nothing will happen as the mainnet activation height has not been set in the code.
>
> When 1.1.0 is released, which has the mainnet activation height, we need to change and set both OVERWINTER_PROTO_VERSION and PROTOCOL_VERSION to 170004, since 1.0.15 nodes running 170003 will always be on Sprout. (Except for the case of testnet above).

Note that a side-effect of this will be that on testnet, 1.1.0 nodes will disconnect from 1.0.15 nodes (because the latter are running the old ``OVERWINTER_PROTO_VERSION`` of 170003, not the new ``OVERWINTER_PROTO_VERSION`` of 170004), even though there is no further testnet activation. This seems undesirable, and is likely to cause a chain fork on testnet as discussed below.

> Q. After testnet activation, if a fresh 1.1.0 node is launched and it needs to sync the testnet chain from scratch, can it do so?

It will only be able to do so from other 1.1.0 nodes that were upgraded from 1.0.15. Unless the behaviour above is fixed, there will be a partition between 1.0.15 and 1.1.0 nodes that will cause a chain fork. Any node that is upgraded will experience a reorg that will either wipe out the blocks from the 1.0.15 fork once the 1.1.0 fork has more work, or will hit the 100-block reorg limit (depending on how long it remained running 1.0.15 after 1.1.0 was released).

**Comment by daira** [comment]
The above problem can be avoided by having distinct constants ``OVERWINTER_TESTNET_PROTO_VERSION = 170003`` and ``OVERWINTER_MAINNET_PROTO_VERSION = 170004``, and then having testnet nodes allow connections with any node having protocol version ``>= OVERWINTER_TESTNET_PROTO_VERSION``.

**Comment by bitcartel** [comment]
@daira Thanks, might not be necessary?  See commit and thread here: https://github.com/zcash/zcash/pull/2919#issuecomment-367822323

**Comment by daira** [comment]
That would work if there were separate ``NetworkUpgradeInfo`` tables for testnet and mainnet, but I see only one table. Have I missed something?

**Comment by daira** [comment]
Testnet and mainnet can use the same protocol version for Overwinter only if there are no incompatible changes in the protocol implemented between 1.0.15 and 1.1.0. Since the point of the testing period is that we might make such changes, I believe that we should plan to definitely increment the protocol version for 1.1.0, so that we don't have to think about two cases rather than one.

**Comment by bitcartel** [comment]
I've said this before, but the testnet activation height really shouldn't go in until the testing period is over.

**Comment by str4d** [comment]
Repurposing this ticket for mainnet.

**Comment by str4d** [comment]
Oh, I didn't need to repurpose it, as we already have #2738.
