### ISSUE TITLE
Tweak mininode.py for future protocol versions

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2982]
See comment: https://github.com/zcash/zcash/pull/2919#discussion_r170084526

**Comment by braddmiller** [comment]
This is going to need to be generalized to allow for future versions. (It isn't a case of "You Ain't Gonna Need It"; we definitely will need it for tests of Sapling.) Maybe use the protocol version constant instead of a boolean. Does not block.

https://github.com/zcash/zcash/blob/73fea254043097271e7ed6c494ca456e09e17751/qa/rpc-tests/test_framework/mininode.py#L1398

**Comment by braddmiller** [comment]
Currently a boolean needs to be some kind of representation of "overwintered" or "sapling"
