### ISSUE TITLE
the difference between listaddressgroupings and getaddressesbyaccount ""

### ISSUE THREAD

**Issue by gotope** [zcash/zcash#3045]
Some address of listaddressgroupings  are not list in getaddressesbyaccount  "", 
glance at the codes, the listaddressgroupings  returned the address had transactions, 
the getaddressesbyaccount  is generated by getnewaddress which might not be used before.
right?  

So the address list in listaddressgroupings are "mine" too, can receive amount of zcash.

**Comment by ioptio** [comment]
Sorry to miss this ticket originally. We'll double check this functionality and add clarity here.

**Comment by Eirik0** [comment]
One thing to note is that the call getaddressesbyaccount has been deprecated. I am not sure of the whole history behind this, but it is related to deprecating accounts. That being said, I think that it is still usable when passing in empty string.

I think that the difference between these two rpc calls is that getaddressesbyaccount returns all addresses in your wallet where as listaddressgroupings will return addresses belonging to you which exist on the blockchain. In other words, if no transaction has been posted to the chain with a given address, it will not show up when calling listaddressgroupings.

If you are trying to figure out which addresses you own, another option would be to call the rpc `dumpwallet`. I would expect this to list all of the same taddrs as listaddressgroupings.

I am not sure which of these calls is the preferred way to get this information, but since we are just dealing with transparent addresses, the answer should be the same as in bitcoin.

**Comment by ioptio** [comment]
Closing this but feel free to reopen if you have related questions.
