### ISSUE TITLE
use new proving system and parameters for Sprout notes

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#3071]
Let's change the consensus rules so that you can privately spend old notes from the Sprout system by using the new Groth16-ish/Jubjub/PowersOfTau/Bellman proving system, but still using the Sprout circuit. At the same time, the new consensus rules will reject using the old Sprout proving system and the First-Ceremony-parameters for Sprout-note-spends. This would make it so that you couldn't counterfeit money _even_ if you knew of a bug in the Sprout proving system or circuit, or if you had recovered the Toxic Waste from [the First Ceremony](http://www.radiolab.org/story/ceremony/).

Of course, it would also mean that you _could_ counterfeit money using the Sprout circuit if there were a bug in the new proving system, or if you had recovered the Toxic Waste from [The Powers Of Tau Ceremony](https://www.youtube.com/watch?v=I4cDAqeEmpU), but I think the new proving system and the new ceremony are better, and we're hiring a lot of independent third-party auditors to study the new proving system, and anyway by doing this there will only be _one_ proving system that has to be secure and parameters that have to be Toxic-Waste-free instead of two. (Because if there's a bug or Toxic Waste in the new system, you can counterfeit money using the new Sapling circuit, anyway.)

Edited to include the fact that we would redo the circuit using Bellman, too, thus protecting against bugs in the original circuit (per the first comment).

**Comment by str4d** [comment]
If we had time to design, implement and audit this circuit, we could generate its parameters at the same time as the Sapling input and output circuits. We do not have that time, so this would instead happen in a future circuit generation. If we are creating a new shielded value pool at that time (due to fundamental circuit changes, or for turnstile auditing of the monetary base), it would make sense to target that value pool instead of the Sapling one.

**Comment by daira** [comment]
I'm opposed to hiding the amount transferred out of the Sprout value pool.

In order to detect any overall balance violation due to flaws in the Sprout circuit or setup, it is necessary for *all* spending of Sprout notes to go through the turnstile, i.e. for the global balance of spent Sprout notes to be revealed. The only way we currently know of to do this is to reveal the balance of spent Sprout notes for *each* transaction.

@zookozcash wrote:
> [...] This would make it so that you couldn't counterfeit money even if you knew of a bug in the Sprout proving system or circuit, or if you had recovered the Toxic Waste from the First Ceremony.

That is not true. If you exploited the Sprout circuit while it was enabled in order to violate global balance, and then privately transferred the funds to the Sapling value pool as is being suggested here, there would be no way to detect that, even if the Sapling circuit and setup were flawless. The risk of global balance violation cannot be allowed to accumulate with each new proving system or circuit.

I'm not opposed to doing a Sprout input circuit for Groth16 implemented in bellman that would reveal the amount spent from the Sprout pool on a per-transaction basis (i.e. you have a proof for each input that yields a Sapling-style value commitment, but you must decommit the sum of these commitments separately from the Sapling ones). This minimizes any information leak for Sprout note holders as far as we currently know how to do, subject to detecting overall balance violation.

OTOH I'm somewhat skeptical that such a thing would a good use of our time and resources. If it happened in the next circuit change after Sapling, and if there is another NU2 upgrade before that one, then in the same (NU3) timescale we could reasonably just remove the ability to spend Sprout notes, requiring people to have used the existing Sprout/PHGR13 circuit implementation by that time to move their funds. Adding a new implementation of the same circuit clearly increases risk, since the attacker has the opportunity to use either implementation (at different times).

I don't see a point in supporting Sprout *outputs* in any new circuit.

For future turnstiles it might be possible to do a private turnstile; see #2373 and #2371. I believe we can't do this for Sprout -> Sapling without incurring unacceptable risk. Even defining global balance preservation independently of a given proving system raises unsolved issues, as discussed in #2289; a transparent turnstile currently the only way we know of to resolve those.

**Comment by daira** [comment]
Note that a Sprout circuit using Groth16 and bellman wouldn't be very much more efficient per-input than the current Sprout circuit implementation, unless we were to recompute the Sprout commitment tree using Pedersen hashes (which is possible).

**Comment by gojomo** [comment]
I didn't read this issue's original concept-description as intending to enable direct shielded zSprout -> zSaping transfers - just upgrading the zSprout realm to no longer be dependent on the original ceremony/circuits. If, however, such shielded transfer was implied, I agree with @daira that the loss of the turnstile-total-ZEC verification would be a significant downside.

I similarly agree that even within zSprout, simply eliminating the 1st-ceremony toxic-waste risk for future transactions is no longer a big win. Anyone seriously concerned about an intentional/malicious retention of the 1st-ceremony toxic-waste would just assume any counterfeiting occurred before the powers-of-tau circuit upgrade. The only way to nullify that concern is an eventual complete shutdown of zSprout – either by explicit deactivation, or just consciously-chosen neglect. 

Possible extreme-minority opinion here: assume the total ZEC in zSprout are at some point a tiny proportion of all ZEC after zSapling adoption. Imagine zSprout is officially announced as unsupported, and consciously neglected, but *not* forcibly deactivated on any chosen schedule. Then, there's a bug/crypto-breakthrough/mysterious-turnstile-enforcement-event that as of some surprise block, irrevocably makes all zSprout balances suspect, and thus a instant loss for laggard zSprout holders. (That is, a "Rapid Unscheduled Disassembly" of zSprout.) But at the same time, all T and zSapling operations continue to work as intended. I don't see that crisis as necessarily a fatal event for the whole system, and it might even be a useful example of how a multi-realm system, with uncorrelated crypto-primitives/initializations, can survive the surprise failure of one realm – provided the turnstile works to contain the damage.

That is, I'd rather trust the turnstile, than trust new extra work fortifying a zSprout system that should sunset eventually anyway.

**Comment by nathan-at-least** [comment]
I don't interpret Zooko's proposal as altering consensus rules about the turnstile. Instead I think it's proposing that we swap out the proving system for Sprout proofs so that while we use `Sprout on PGHR13` today, we could use `Sprout on Groth16-tweaked/Jubjub/PowersOfTau` in the future with the same circuit construction in the Sapling consensus protocol.

To me this is appealing for a few reasons:

- First, in contrast to @gojomo's intuition, I think it's very useful to be able to say "if the original ceremony *OR* PGHR13 *OR* `libsnark` was not yet compromised as of Sapling's activation date, it can no longer affect Zcash moving forward." That seems like a very useful reduction of the security reliances after a point in time that complements cointerfeit detection.
- Second, assume the two proving systems and MPC systems are flawless, so that we only consider operational security: the first ceremony depended on only 6 people, whereas the Powers-of-Tau based ceremonies include many many more people. If we could say "from this point in time onwards, a proving parameter compromise via opsec must have compromised all of the many Powers of Tau participants or the many Sapling Ceremony participants" that seems much stronger from an opsec perspective than all of that "plus that other time there were those 6 people." (Also, note the new MPC has two independent implementations, and the Sprout ceremony relied on a single-point-of-failure compute disk image.)
- Third, `PGHR13` and `Groth16-tweaked` rely on different security arguments, with different assumptions. While one may reduce to the other, I'm not aware of such a reduction yet. Therefore, if we did *not* do this, we have to say "Zcash currently depends on these two different security models for two different proving systems". I'd much rather say "in the past Zcash depended on one security model, and now it depends on this other one."
- Fourth, reimplementing the Sprout circuit on `bellman` will be a second implementation of the Sprout circuit, so it will give us better clarity about both the Sprout construction *and* `bellman` in contrast to `libsnark`. (The two implementations won't be proof-wire-compatible, but the constructions will be identical, as I understand it.)

Ok, so those are the appealing aspects. The drawbacks include:

- We might introduce new bugs. Swapping out a core component of a security system is always very risky! However, if the bugs affect any of Sapling it's already game over, and if we faithfully port any Sprout circuit bugs, this approach doesn't make that worse. So the only distinct bugs this could introduce are specifically within porting the circuit unfaithfully/differently to the Sprout construction.
- Complexity: The *software* still needs to generate/verify Sprout proofs for both proving systems as long as we're doing full historical chain validation. (This is a general technical debt problem that we will continue to face in many other areas, too, for example if we ever want to deprecate Sprout altogether.)
- Schedule and Logistical risk: more scope, more effort, more to audit, later to market.

**Comment by ebfull** [comment]
I agree with the principle of doing this. There may be some merit in doing it with _every_ upgrade, but the advantages are especially apparent in the upgrade from Sprout to Sapling. We're moving to a much more thoroughly tested circuit synthesis environment, using a really clean proving system and larger MPC, on top of a much more rigid curve construction implemented in a memory-safe language with over a year of attention given to its code quality and correctness.

If there's a critical bug in Sprout, we'll still need the turnstile to ensure the bug was never exploited, but unless we do what @zookozcash suggests then entire categories of bugs would be exploitable until we do some kind of emergency hardfork -- requiring us to _also_ be lucky enough to discover these bugs before an attacker did.

**Comment by bbuenz** [comment]
I am not quite sure that I follow everything since I am not too familiar with the terminology. However, I definitely am strongly opposed to what I believe you call the turnstile. The public audit of all accounts to ensure that the monetary base is what it is supposed to be. My reasons are as follows:
ZCash is marketed as and is generally viewed as the most privacy preserving (crypto)currency (deservingly so). Forcing users to reveal their balances seems like a breach of contract to me. It violates the security definition of the ZeroCash paper and adversaries will learn not only the distribution of money but can through network auditing directly determine how many ZEC an IP address has (TOR can be broken). My strongest argument against the turnstile is that it is not rational for users to accept it. There are two different scenarios and for either of them "not forking" seems to be the dominant strategy: Either the trusted setup is not broken then I am better off by not having had to give up privacy. Or it is broken in which case ZCash will likely become completely worthless and useless. Perhaps users who don't care at all about privacy are willing to accept the turnstile but that just means that this change would mainly hurt the people that care most about privacy and are likely the most vulnerable. Finally this hardfork will probably set the standard for how future upgrades will be handled. I hope that ZCash will choose privacy and user protection over some faulty notion of fixing old mistakes which cannot be fixed. I fully agree that the new system seems better and more secure and it would be better to not have to deal with the consequences of the old setup but I believe this is a pill that ZCash just needs to swallow since I the alternative seems worse.

**Comment by gojomo** [comment]
@bbuenz - Currently & unavoidably, net amounts that move from transparent T-addresses to (zSprout) shielded Z-addresses are already visible. The 'turnstile' just checks that the total ZEC ever moved-out of zSprout never exceeds the total amount moved-in - a sanity-check. That is, there's no extra revelation of any user balances by a 'turnstile' - just enforcing, on the amounts already seen moving to/from T(ransparent), that there's been no inflation in the shielded realm. (You can also think of it as a "value firewall".)

With the addition of the 2nd shielded realm, zSapling, there is the question of whether it (a) gets filled only by transparent amounts, and thus net-flow 'turnstile' auditing can be maintained, or (b) whether a direct, fully shielded zSprout->zSapling transfer is *also* supported.

Option (a) is a lot simpler, and has the benefit of assuring people, over the long term (and especially if zSprout someday is completely shut down) that no zSprout inflation/counterfeiting ever happened. Only the net amounts moving out-of-zSprout and into-zSapling would necessarily be revealed - not source or destination addresses. (You are correct that a network-surveilling adversary could potentially associate such balances to IP addresses, barring extra self-help in obscuring origin IPs.) Essentially, option (a) creates the possibility of some future cutover date, TBD, after which there is zero risk to ZCash from any of the 1st 'trusted setup' and early code decisions having errors/weaknesses. 

Option (b) is more complicated to implement, and forces slower/weaker zSprout code/state to remain active/maintained longer. It also indefinitely puts off a public proof that no zSprout inflation ever occurred. So in my estimation, it compounds & prolongs certain systemic risks, rather than reducing them by moving value/activity to a the new stronger realm.

**Comment by bbuenz** [comment]
@gojomo So the turnstile is exactly what I thought and I stand by my arguments before. I think that enabling option b) is vital to retain the security of ZCash as per the zero cash paper’s definition. I think that revealing the net amounts and distribution of money breaks the privacy that ZCash promises to provide to its users. Also this apparently then needs to happen with every upgrade of the proof system. I especially think that it isn’t rational for users to accept this (see above). Happy to be convinced otherwise on the last point.

**Comment by daira** [comment]
@nathan-at-least wrote:
> we could use Sprout on Groth16-tweaked/Jubjub/PowersOfTau in the future with the same circuit construction

If we do this, I don't want to use the same circuit construction. We don't need it; we only need the input side. There's an issue with just having the input side, though, which is that Sprout required use of intermediate change notes in order to spend more than two notes. We know how to avoid that now, using value commitments.

**Comment by daira** [comment]
@bbuenz wrote:
> Forcing users to reveal their balances seems like a breach of contract to me. It violates the security definition of the ZeroCash paper and adversaries will learn not only the distribution of money but can through network auditing directly determine how many ZEC an IP address has (TOR can be broken).

A transparent turnstile does not force users to reveal their addresses on the block chain. The source addresses are private, and the destination addresses can also be private. You're right that a network-observing adversary can potentially see which node introduced the transaction to the network, and therefore can add up the balances transferred by node. I'm not going to go into security properties of Tor here, but it does help against some classes of adversary.

**Comment by str4d** [comment]
#2373 is the open issue for designing a protocol for private auditing of the monetary base. It would be great to have at some point, but it won't happen before Sapling (like this issue), and so the only means of transferring funds from Sprout to Sapling will be through the transparent value pool.

**Comment by daira** [comment]
If I misunderstood @zookozcash's intent, I apologize for derailing the point of the ticket. Zooko can you clarify?

**Comment by ebfull** [comment]
I've written an implementation of the Sprout JoinSplit circuit that can be attached to our Sapling MPC.

https://github.com/zcash-hackworks/sapling-crypto/pull/52

**Comment by ebfull** [comment]
The parameters using the new implementation and proving system are 717MiB. It takes my computer 2.332s to load the parameters into memory from SSD. They occupy roughly this much space in memory as well. After params are in memory, proofs are taking 17.26s to construct on average.

**Comment by ebfull** [comment]
There are two reasons why the parameters are now _smaller_ despite the fact that BLS12-381 is built over a larger base field (48 bytes rather than 32 bytes). First, fewer multi-exponentiations are needed in Groth16. Second, libsnark serializes the sparsity of some vectors (as a bunch of ASCII numbers!) whereas bellman calculates this sparsity at proving time, since it's deterministic and inexpensive to compute.

**Comment by ebfull** [comment]
My implementation of the Sprout circuit now has a minimal diff from the Sapling code: https://github.com/zcash-hackworks/sapling-crypto/pull/54

**Comment by daira** [comment]
I didn't realize there would be this much performance benefit &ndash;more than a factor of 2 in both memory and proving time&ndash; just from moving to Groth16. This does make me a little more favourable to the proposal (of just copying the Sprout circuit with a transparent turnstile). I still consider it to be incurring additional risk, and potentially a distraction from more important things.

**Comment by ebfull** [comment]
My Sprout PR now passes test vectors against the old Sprout circuit, so I'm going to place it in the Sapling MPC.

**Comment by nathan-at-least** [comment]
@daira and @bbuenz: The issue of whether or not there is a direct z1→z2 shielded transfer is completely separate from the issue in this ticket. The turnstile issue is completely orthogonal AFAICT, except we might need different circuits for z1→t versus z1→z2. That was discussed and decided in https://github.com/zcash/zcash/issues/2248.

@bbuenz I understand your concern, let's continue the conversation on #2248.

**Comment by nathan-at-least** [comment]
@ebfull awesome work!

I think the pros/cons for switching to `Sprout-on-Groth16prime-BLS12-381-Bellman` from `Sprout-in-zcash-1.0` are:

**Pros:**

- After the protocol upgrade, any compromise or weakness of the original proving system or MPC setup can no longer be attacked.
- After the protocol upgrade, the whole system security will rely on a single proving system, rather than two different ones with two different security proofs/analyses.
- The new implementation is faster.
- The new implementation uses a memory safe language (rust vs c++).
- Because we are putting effort into porting the new Sapling stack into multiple other contexts (mobile, potentially hardware wallets, SPV wallets) this *might* also streamline porting z1 support to those contexts, along with any general Bellman resource improvements (ex: streaming proving).

**Cons:**

- The reduced attack surface only applies *after* protocol upgrade activation, and counterfeiting attacks prior to that activation are not directly detectable (outside of the turnstile accounting of #2248).
- The reduced security assumptions/proofs/analyses of the single-proof-system only applies after activation.
- A new implementation of the Sprout circuit may introduce new critical bugs.

Did I miss any pros/cons?

Given all of that, I'm in favor of including this new Sprout implementation as part of the Sapling upgrade.

**Comment by daira** [comment]
In my opinion it is too late to be making this change, unless the Sapling activation date slips to accomodate the additional review and auditing needed.

Even in that case, there is additional risk relative to sticking with the Sprout circuit. Let's go through the above statements asserting pros and cons:

> Pro: After the protocol upgrade, any compromise or weakness of the original proving system or MPC setup can no longer be attacked.

This argument is not convincing: if (purely for the sake of argument) an adversary had the toxic waste from the Sprout setup *or* a way of exploiting the libsnark/PHGR13 implementation of the Sprout circuit, then they would definitely exploit it before the Sapling activation &ndash;or already have exploited it before now&ndash; and would then be able to spend the ill-gotten gains after the activation, without incurring any additional risk of detection.

I realize you already gave this as the first Con, but the fact is that it almost neutralizes the benefit of this Pro for balance violation attacks. It does not neutralize it for privacy or for "on-line" attacks where the attack must be directed toward a specific victim, but note that privacy as far as the circuit is concerned is dependent on the zero-knowledge property of the proving system, which is quite robust to [non-memory-safety-related] errors in the circuit implementation, so that it is less likely that reimplementing the circuit helps against that class of attacks.

> Pro: After the protocol upgrade, the whole system security will rely on a single proving system, rather than two different ones with two different security proofs/analyses.

For new attacks, yes.

> Pro: The new implementation is faster.

Yes, about twice as fast (but still much slower than Sapling).

> Pro: The new implementation uses a memory-safe language (rust vs c++).

Yes.

> Because we are putting effort into porting the new Sapling stack into multiple other contexts (mobile, potentially hardware wallets, SPV wallets) this might also streamline porting z1 support to those contexts, along with any general Bellman resource improvements (ex: streaming proving).

The Sprout circuit still won't be practical for hardware wallets; it's the separate spend authorization signature that makes Sapling practical for those, not the Bellman/Groth16 performance improvements. The rest of this is valid. On the other hand, a strategy of only supporting Sapling for shielded transactions on mobile and SPV would reduce development costs, and I'm concerned about whether trying to support both Sprout and Sapling in those contexts would be biting off more than we can chew.

> Con: The reduced attack surface only applies after protocol upgrade activation, and counterfeiting attacks prior to that activation are not directly detectable (outside of the turnstile accounting of #2248).
> Con: The reduced security assumptions/proofs/analyses of the single-proof-system only applies after activation.

Already discussed above.

> Con: A new implementation of the Sprout circuit may introduce new critical bugs.

I believe you may be underestimating this risk. The current planned Sapling activation date ("Plan A") has no provision for the review and auditing needed for a Bellman/Groth16 implementation of the Sprout circuit.

You also missed a con: Sapling is *already* in specification freeze. We agreed that the only changes that could still be made are changes necessary to facilitate the security proof or correct security regressions. The proposal here does not fit those criteria.

**Comment by daira** [comment]
Arggh I wrote a *long* comment which was lost by Firefox :-(

**Comment by daira** [comment]
Another con: switching to Groth16 proofs requires a transaction format change, which means that v3 transactions would presumably have to be prohibited after Sapling activation. (If they are allowed, then we don't get any security benefit.) But that means that code that creates transactions independently of zcashd, that has had to be updated for Overwinter, will have to be updated again for Sapling.

**Comment by ebfull** [comment]
> switching to Groth16 proofs requires a transaction format change

This isn't strictly true. Groth16 proofs fit inside the existing proofs, activating this in Sapling is just a matter of changing the behavior of the verifier.

**Comment by str4d** [comment]
Not quite - in at least the parsers I've written, I've been checking the G1
and G2 encodings of y, which would become invalid for a Groth16-based
proof. So we'd need to tweak some (most?) of the transaction parsers (which
we could maybe do ahead of 1.1.0, but it would be additional work, so
likely it would have to happen later).

**Comment by ebfull** [comment]
What specifically are you checking? zcashd's parsers don't check this stuff during deserialization.

**Comment by ebfull** [comment]
If you mean the lead bytes of the G1/G2 elements that's fine. But if you're checking that the Fq/Fq2 elements are in the right bounds, yeah that would be a problem.

**Comment by str4d** [comment]
Just the lead bytes of G1 and G2, so the Groth16 Sprout proof would need to
conform.

**Comment by ebfull** [comment]
Cool, well even if you were checking the Fq/Fq2 encodings we could make that work also (with plenty to spare):

```
0x02 (g1 prefix, lsb_y = 0)
0x00 (ensures the alt_bn128::Fq element is in the field)
[31 bytes]
0x02 (g1 prefix, lsb_y = 0)
0x00 (ensures the alt_bn128::Fq element is in the field)
[31 bytes]
0x0a (g2 prefix, y_gt = false)
0x00 (ensures the alt_bn128::Fq2 element is smaller than q^2)
[63 bytes]
0x02 (g1 prefix, lsb_y = 0)
0x00 (ensures the alt_bn128::Fq element is in the field)
[31 bytes]
0x02 (g1 prefix, lsb_y = 0)
0x00 (ensures the alt_bn128::Fq element is in the field)
[31 bytes]
0x02 (g1 prefix, lsb_y = 0)
0x00 (ensures the alt_bn128::Fq element is in the field)
[31 bytes]
0x02 (g1 prefix, lsb_y = 0)
0x00 (ensures the alt_bn128::Fq element is in the field)
[31 bytes]
0x02 (g1 prefix, lsb_y = 0)
 (ensures the alt_bn128::Fq element is in the field)
[31 bytes]
```

**Comment by ebfull** [comment]
So, no changes to parsers necessary.

**Comment by daira** [comment]
I don't see how trying to shoehorn the Groth16 proofs into the same format as the PHGR13 proofs helps. It still makes v3 transactions created by existing code invalid after Sapling activation (which was not the case for the current plan). In fact, shoehorning the Groth16 proofs into the PHGR13 slot *without* changing the version or nVersionGroupId would be breaking a design rule about unambiguous parsability.

**Comment by ebfull** [comment]
Hmm... I agree we'd have to do a transaction format change.

**Comment by tromer** [comment]
This proposal is elegant and makes a lot of sense in principle, in terms of both software engineering and crypto. But doing it properly is a major detour/distraction on the way to getting Sapling out there and getting its usability and deployment advantages. And frankly I don't see what urgent problem it solves.

My recommendation:

1. Stay laser-focus on delivering Sapling as currently planned.

2. If the current Sprout *verifier* code becomes a bottleneck (e.g., for some reason mobile/hardware wallets have trouble with libsnark), see if we can offer an alternative but compatible Sprout verifier. Or just direct them to Jason Davies's. (There's no good reason for mobile/hardware wallets to run the Sprout prover, so that's no an issue.)

3. Observe Sapling adoption and figure the realistic schedule for obsoleting Sprout notes. If that's more than a year, revisit the question of Bellman-based proofs for Sprout notes.

**Comment by nathan-at-least** [comment]
We just had a meeting with @str4d, @daira, @ebfull, @zookozcash, and myself, and we arrived at these conclusions:

- We *will* make this a feature goal for Sapling activation.
- This means v4 transactions will have a new proof format for Sprout proofs.
- Sprout-on-PHGR13 will be deprecated at activation. We agreed to do this by deprecating v3 transactions.

Implications:

First the **risks/costs**:

- A new Sprout-on-Groth-Prime introduces at least two new categories of risk:

  + a new implementation bug that is not present in Sprout-on-PHGR13.
  + a new security flaw due to Sprout-circuit-construction on Groth-Prime instead of PHGR13. IOW, if the Sprout-circuit construction relies on a guarantee provided by PHGR13 that's not provided by Groth-Prime.

- This adds complexity/risk to the roadmap. However, we believe this can potentially _still fit in the current schedule_!
- Deprecating v3 so quickly after its introduction may be costly for some vendors, especially hardware wallets. We discussed this at length. Note that hardware wallets will *already* need to support v4, or else some fraction of transactions won't register with their wallets leading to a big UX problem. So we believe this "tight schedule" hurdle is *already* present, and this decision doesn't add much beyond that.

The **benefits** include:

- The simplistic narrative is that after Sapling activation all of the old cryptography and code is no longer an attack surface. (* this isn't quite true, see next:)
- Once Sapling activates, the window for any attacks on the Sprout-on-PHGR13 implementation, PHGR13, the original MPC ceremony, and the implementation is greatly reduced.

  + Note - one attack vector remains for newly bootstrapping nodes: an attacker could feed that node blocks that aren't in the canonical history which contain malicious proofs.
  + Any such attack's impact is limited by Nakamoto Consensus, so we assume that node will *eventually* discover the canonical history. Therefore, any counterfeiting attacks would be fairly ineffective.
  + By constrast memory-corruption-based attacks on libsnark would still be dangerous. If those exist currently they are easy to attack (by anyone who can submit a transaction). After this change, those attacks *also require* a network attack on bootstrapping nodes, so the risk of this class of attacks is largely reduced.
  + Both categories of risk can be entirely mitigated by check-pointing.

- To drive points 1 and 2 home: after Sapling activates, the attack surface of the original ceremony and `libsnark` will be largely mitigated.
- The new implementation will be on the Bellman stack, so all proving will now be on a single consistent purpose-built stack. This has multiple sub-advantages: for example, any tool-chain/porting work for Sapling will also apply to this new Sprout-on-Groth-Prime.
- The new implementation appears to be notably more efficient, perhaps enabling high-powered mobile wallets to provide built-in Sprout-to-Sapling upgrade features (or plain Sprout transactions).

As a parting note, I really wish I had shorter but accurate names for Sprout-on-PHGR13-and-libsnark versus Sprout-on-Groth-Prime-and-bellman.

**Comment by ebfull** [comment]
bellman currently only supports Groth16 and BLS12-381. (Groth-prime never manifested.) You can just call it bellman for now I suppose.

**Comment by str4d** [comment]
> As a parting note, I really wish I had shorter but accurate names for Sprout-on-PHGR13-and-libsnark versus Sprout-on-Groth-Prime-and-bellman.

SproutPL and SproutGB?

**Comment by daira** [comment]
Something I forgot to mention in the meeting: there could in principle be a bug that prevented transactions containing Groth16 proofs from working properly, and in that case the original, pre-#3071 plan would still have allowed Sprout shielded transactions to work after the Sapling activation &mdash; whereas now there is a common failure mode.

I think we are unlikely to miss such a bug if we've done sufficient smoke-testing on testnet. On the other hand, we did have a problem in 1.0.0 that prevented transactions with JoinSplits from propagating well (in a way that didn't happen on testnet), so this kind of bug can't be completely ruled out. I don't think it's a serious enough issue to change the decision.

**Comment by bitcartel** [comment]
For the record, I believe that @tromer's approach is the right one. https://github.com/zcash/zcash/issues/3071#issuecomment-377534611

**Comment by daira** [comment]
@nathan-at-least wrote on 2 April 2018:
> We just had a meeting with @str4d, @daira, @ebfull, @zookozcash, and myself, and we arrived at these conclusions: [...] We _will_ make this a feature goal for Sapling activation.

OMGhod I remember that meeting so well. (@str4d and I didn't know about the BCTV14 bug; @ebfull, @zookozcash and @nathan-at-least did.) Let's all have a game of poker at Zcon1, because I feel yous would be rather good at it :-p

**Comment by daira** [comment]
@zookozcash wrote:
> Let's change the consensus rules so that you can privately spend old notes from the Sprout system by using the new Groth16-ish/Jubjub/PowersOfTau/Bellman proving system, but still using the Sprout circuit. At the same time, the new consensus rules will reject using the old Sprout proving system and the First-Ceremony-parameters for Sprout-note-spends. This would make it so that you couldn't counterfeit money _even_ if you knew of a bug in the Sprout proving system or circuit, or if you had recovered the Toxic Waste from [the First Ceremony](http://www.radiolab.org/story/ceremony/).

Lol I only just noticed (in a pairing with @sellout) that this ticket was opened [only a week after the BCTV14 flaw was discovered](https://electriccoin.co/blog/zcash-counterfeiting-vulnerability-successfully-remediated/#timeline-of-events).

**Comment by bbuenz** [comment]
Given that info, a transparent turnstile was a good idea, lol.
