### ISSUE TITLE
Overwinter: fix testnet mining

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3101]
While this ticket remains open, we should be CPU mining testnet blocks.

To enable gpu mining of testnet blocks:

For Z-NOMP to work, the Overwinter ruleset needs to be implemented in the fork of bitcoinjs-lib that is being used by their fork of the Stratum JS library that is being used by Z-NOMP, their fork of NOMP.

**Comment by Tomas-M** [comment]
Is there any known update for Z-NOMP for Overwinter?

**Comment by Tomas-M** [comment]
The topic of this ticket should be changed to "fix z-nomp mining" because overwinter is already activated and is no longer limited to the testing network. Z-NOMP pools are currently unable to create blocks.

Is there any description of the mentioned "Overwinter ruleset"? So I could perhaps try to patch z-nomp for that?

**Comment by Tomas-M** [comment]
This pull request explains what to do in order to fix things with z-nomp for Overwinter:
https://github.com/karel-3d/bitcoinjs-lib/pull/3

**Comment by hellcatz** [comment]
@Tomas-M Thanks for tagging the PR to this issue.

**Comment by mms710** [comment]
Thanks for the work on this! Since the associated PR was merged I'll go ahead and close this.
