### ISSUE TITLE
Use batch SNARK (Groth16) verification

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#320]
Determine if batch SNARK verification is a feasible time-efficiency improvement we can use.

Also, what's the protocol upgrade story for this? Presumably, we can deploy 1.0, then later make a code change to the block verifier with no change to consensus rule or protocol changes.

(Note: I added `zkSNARK circuit`, but this change doesn't actually affect the circuit.)

**Comment by daira** [comment]
See also #2106 and https://github.com/zcash/libsnark/pull/9 .

**Comment by daira** [comment]
See my comment on how to do batch verification for Groth16: https://github.com/zcash/zcash/issues/2465#issuecomment-310745119

**Comment by daira** [comment]
This is fully described in Appendix B.2 of the protocol spec.

**Comment by daira** [comment]
zcash/libsnark#9 had a lot of bikeshedding / loud agreement on the idea that it would be risky to directly switch from unbatched to batched verification, since any difference could cause a chain split. The Appendix B.2 algorithm has been carefully designed not to have any such differences, but I agree that it's still risky. We should use a staged approach:

1. Implement batch verification as an experimental feature and run it on a detector for a while, so that we can verify that the detector doesn't diverge from the consensus chain.
2. Enable combined unbatched and batched verification by default. If they differ then the tx is rejected and the node reports this loudly.
3. Switch to unbatched verification by default.

At step 2, if there is a side-branch of blocks containing a transaction that was allowed by unbatched verification but not by batched verification, then the consensus will converge to orphaning the side-branch. At this stage there is no risk that unbatched verification could allow a transaction that should not have been allowed. So the transition 1->2 is at most a soft fork.

The transition 2->3 could be an expanding fork if there is a bug, but we've minimized the risk of this by running stages 1 and 2 for a while.

Also, the alternative Zcash node implementation being developed by Parity should IMHO be encouraged to use batch verification from the start.

**Comment by str4d** [comment]
This was implemented for Sapling in #6048.

Sprout proof verification is still unbatched, but the number of Sprout proofs on the network (particularly Groth16 proofs post-Sapling) is very low, so it's unlikely we would spend the engineering resources to implement this before Sprout is fully deprecated. If the Sprout proof verification becomes a performance issue, we can reopen this issue (or more likely create a new one).
