### ISSUE TITLE
Equihash vulnerability - fix info?

### ISSUE THREAD

**Issue by attritionorg** [zcash/zcash#3256]
Regarding this disclosure: https://github.com/edwardz246003/misc/blob/master/Attackers%20Fake%20Computational%20Power%20to%20Steal%20Cryptocurrencies%20from%20Mining%20Pools.md

"_Other major crypytocurrencies and mining pools like Zclassic, BTG and Zcash also took actions to resolve the vulnerability._"

Can one of the developers link to the fixing commit and/or version that resolves this? Thanks!

**Comment by str4d** [comment]
The Zcash codebase (and codebases derived from it, assuming they still use our validator) was never vulnerable to this bug. It was specifically in third-party open source mining pool software (and possibly closed-source mining pools as well, but I have no knowledge or insight there). The bug was caused by the mining pool software using an incorrect implementation of an Equihash validator which left out several checks; thus shares containing invalid Equihash solutions, that met the pool's difficulty (but not the network difficulty), could be submitted and would be accepted. If any of those shares happened to meet the network difficulty, they would have been rejected as invalid by the `zcashd` node's Equihash validator.

**Comment by attritionorg** [comment]
Great, thank you for the details @str4d!

**Comment by michaelotis** [comment]
This was an issue with equihashverify that many pools used with predominately, z-nomp. There has been a fix deployed, pool owners can upgrade their z-nomp pools which will build a new copy of equihashverify or you can find the source here:  https://github.com/ZencashOfficial/equihashverify
