### ISSUE TITLE
Add RPC for migrating funds from Sprout to Sapling

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#3268]
We decided elsewhere that #3215 would not allow users to create transactions that have Sprout addresses as input and Sapling addresses as output, or vice versa. This is because users may not expect that any information is leaked if a transaction only involves z-addresses, when in fact the value being transferred is exposed (for auditing).

We need a new RPC method that creates transactions specifically for these migrations, that reduces information leakage as much as possible (e.g. using bucketed amounts). It should also have the ability to return the transactions without broadcasting them to the network, so that the user can leverage a third-party avenue to hide additional metadata.

**Comment by bitcartel** [comment]
One alternative is a script that uses z_sendmany in conjunction with t-addresses to move funds from Sprout shielded to Sapling shielded via t-addresses.

**Comment by bitcartel** [comment]
In scrum of scrums it was noted that implementation can target v2.0.3 to provide more time for design work.

**Comment by adityapk00** [comment]
I've added a UX proposal (for zcash-qt-wallet) for the turnstile migration that I'd love some official feedback on. 
https://forum.zcashcommunity.com/t/1-click-sapling-turnstile-migration-proposal-for-zcash-qt-wallet/31654

**Comment by zookozcash** [comment]
related: https://github.com/adityapk00/zec-qt-wallet/pull/20

**Comment by adityapk00** [comment]
Outline and screenshots for how zec-qt-wallet does automatic sapling turnstile migration: https://github.com/adityapk00/zec-qt-wallet/releases/tag/v0.2.5

**Comment by SamsungGalaxyPlayer** [comment]
# Metadata Considerations for Zcash Turnstile Process

Zcash has decided to make a privacy tradeoff to increase the auditability of the Zcash blockchain. Zcash prohibits transactions moving directly from the shielded, legacy "Sprout" pool to the new, more efficient "Sapling" pool. Instead, users need to send funds in two or more partially-shielded transactions: Sprout to transparent, and transparent to Sapling. This intermediate transparent process allows people to determine how much money is transferred from the private pool and confirm this does not exceed the amount placed into the private pool. However, this transparent pool is (by definition) transparent. Some tools could be used to mitigate metadata leakage when performing a turnstile migration.

It is important to note that any interaction with the transparent pool places transaction data at risk. It is impossible to build a tool that can anticipate every possible heuristic that can be devised to trace funds. However, this tool can nevertheless address predictable, simple heuristics in a way better than most users can do alone.

## Current Implementations

There is no current turnstile migration tool included in current releases, but a few ideas have circulated. These are listed below:

https://github.com/adityapk00/zec-qt-wallet/releases/tag/v0.2.5

https://github.com/adityapk00/zec-qt-wallet/pull/20

https://forum.zcashcommunity.com/t/1-click-sapling-turnstile-migration-proposal-for-zcash-qt-wallet/31654

The three previous recommended privacy options are listed below:

    “Good - 3 tx over 3 days”
    “Excellent - 5 tx over 5 days”
    “Paranoid - 10 tx over 7 days”

## Types of Metadata

These are partially addressed in [this comment](https://github.com/zcash/zcash/issues/3268#issuecomment-433777727). Note that this is not a full, verbose list; however, it covers many of the important considerations. A user's specific metadata needs vary on a case-by-case basis.

### Transaction Amounts

Visible transaction amounts create links between otherwise obfuscated sender and receiver identities. The effects of these for partially-shielded transactions have been documented in at least 2 other research papers, and the same principles apply here. Normally, the best solution is to encourage use of fully-shielded transactions to obfuscate the amount, but this is not possible in this scenario. Thus, users need to live knowing that their transaction amounts are visible under any circumstance. However, there are a number of methods that Zcash users and software can take to mitigate the amount of leaked amount metadata.

#### Denominations

Several cryptocurrency projects use (or previously used) denomination processes for partially hiding the amount sent in transactions. These include the following and their denomination processes:

* Dash: Dash follows a CoinJoin mixing approach where it allows 10, 1, 0.1, and 0.01 denominations. These are roughly $1500, $150, $15, and $1.5 at today's prices. They [recently expressed interest](https://github.com/dashpay/dash/issues/2198) in dropping the 10 DASH denomination and adding a 0.001 denomination. The 10 DASH denomination was used marginally until early 2017, when the 0.01 denomination moved from the least-used to the most-used. This likely comes from the increased value of DASH over 2017. [Currently](https://dashradar.com/charts/mixing-transactions-per-day-by-denomination), about 70 transactions per day use the 10 DASH denomination, and approximately 530 use the 0.1 DASH denomination.

![Dash denomination use](https://i.imgur.com/81HVnHa.png)

* Monero: Monero previously used a denomination process for pre-RingCT outputs. A [study found](https://books.google.com/books?id=waUzDwAAQBAJ&pg=PA157&lpg=PA157&dq=monero+denominations&source=bl&ots=xKhpl__0oP&sig=e4y1Gna11_dGGNpGXGxBZ46OYT8&hl=en&sa=X&ved=2ahUKEwiRxqeK4b7eAhUq8IMKHQSpDG4Q6AEwB3oECAIQAQ#v=onepage&q=monero%20denominations&f=false) that there were 1,339,733 possible denominations with a maximum of 500,000 XMR (~$50 million in today's prices). They found ~85% of outputs were less than 0.01 XMR (~$1), and 93% of denominations had a frequency of 1 (likely due to the wide possibility for unique values). They also found a significant amount of denomination noncompliance. This suggests that denominations should be enforced on the protocol level.

* Zcoin: [Zcoin](https://zcoin.io/how-to-use-zerocoin-in-zcoin-xzc/) can only be minted and spent in fixed denominations of 1, 10, 25, 50, and 100. 1000 is planned. You can only spend one denomination at a time.

* PIVX: PIVX [uses fixed denominations](https://github.com/PIVX-Project/PIVX/blob/master/doc/release-notes/release-notes-3.0.0.md#zpiv-denominations) of 1, 5, 10, 50, 100, 500, 1000, and 5000 zPIV. You can spend more than one denomination at a time. PIVX transactions allow the leftover change less than 1 zPIV to be burned or returned to the user as transparent change.

* CoinJoin for Bitcoin: CoinJoin needs fixed denominations without CT.

* TumbleBit for Bitcoin: [TumbleBit needs fixed denominations without CT](https://medium.com/@nopara73/tumblebit-vs-coinjoin-15e5a7d58e3) like CoinJoin.

The fewer denomination options, the better for privacy in a strict sense. However, this unfortunately comes at the cost of lost convenience. Furthermore, small allowed denominations (especially <$1) allow the tracking of highly-specific amounts more easily.

I generally recommend a denomination system for Zcash in denominations of 0.01, 0.1, 1, and 10 Zcash (~$1.2, $12, $120, $1200). Furthermore, the wallet should prevent sending from more than one denomination. While this means that many users will need to make many transactions to move sizeable amounts of Sprout shielded Zcash, it will reduce the amount of visible metadata in each transaction. Someone moving 10 Zcash will look more similar to someone moving 1000 Zcash if the second person moves funds across several transactions.

Any allowed smaller amounts would allow an attacker to more easily determine the origin of deposited funds, and any larger amounts likely have low anonymity sets from what we have seen from other cryptocurrencies (including those with optional privacy solutions). I generally recommend that the tool prevents people from spending amounts smaller than the 0.01 ZEC.

### Timing Analysis

This one is extremely complex with dozens/hundreds of considerations, but here are some of the main ones:

1. Associating transactions to others sent over a similar time period.
2. Using outside information to learn more about transactions sent over a specific period.
3. Spending from the shielded Sprout pool will stick out now and even more in the future as this behavior becomes increasingly uncommon. A month from the tool release, it is unlikely that users will move funds from this pool at the same time as other users.

#2 is an issue even for fully-shielded transactions and is mostly out-of-scope for this discussion. There are too many considerations to properly address for the initial implementation of this tool.

#1 and #3 are more manageable. If someone sends 12 transactions within 5 minutes, then this likely would not fit other users' spending patterns and could trivially be assumed to be associated. The actual effectiveness of this heuristic would vary in practice, but this is nevertheless an important consideration.

The initial implementation of this tool which uses three different "grades" of privacy shown as the following partially addresses this concern, but it addresses it in a relatively ineffective way. It is shown again below:

    “Good - 3 tx over 3 days”
    “Excellent - 5 tx over 5 days”
    “Paranoid - 10 tx over 7 days”
	
It is incorrect to place the wide variety of Zcash amounts people hold into a set number of transactions. It is MUCH better to instead separate them into the denominations as described earlier. So if someone has 100 ZEC, they would send 10x10ZEC transactions. If they had 1.2 ZEC, they would send 3 (1x1ZEC + 2x0.2ZEC) transactions. The number of transactions isn't nearly as important as getting the denominations correct.

Now, there is an argument to be made that it could make sense to break up transactions into more than 1 denomination for the sake of adding more transactions and thus (in a way) more apparent entropy. However, I argue this does not make a considerable impact in practice. Shortly after the initiation of a turnstile process or a tool release, the number of these transactions will be relatively large where the provided benefit is small. Any other times will still stick out regardless. For example, if the minimum is set at x, then any transactions made during a period of low turnstile use would still clearly stick out. I believe the additional computational cost, blockchain space/verification bloat, and little to no measurable benefits mean that forcing a specific number of transactions will have a net negative impact.

The day window generally makes sense, though it is again applied incorrectly. Zcash users need to make sure their transactions are not associated with each other, and this means separating transactions over a period where there is the possibility for more entropy. However, this depends on the number of necessary denominated-transactions. Of course, it should go without saying that there needs to be some entropy in the actual selected time over a selected set of days.

I unfortunately do not know the exact window to recommend here, but generally, bigger is better. However, no specific time period is better than a short window where many of these transactions take place in a coordinated fashion. I understand this is likely not especially realistic for the migration discussed here, but it could make sense to encourage a tool to make transactions over a coordinated 1-hour window, for instance. Of course, this would have to be weighed against the possible negative contributing factors as well, including the higher rewards of concentrated sybil attacks. Nevertheless, I believe it is worth mentioning, especially if IP metadata is well-protected throughout this process.

The setting should instead recommend several time intervals between transactions. Honestly, it may make sense to allow a user to add their own values here, since it would encourage tool use and could add additional, human-generated entropy. If someone is able to wait a month, it likely makes sense to allow them to set the interval to 30 days. If they only can wait half a day, it's better for them to use this tool for a half day interval than to go without it. Of course, the wallet should recommend a sensible minimum. Unfortunately, this area of metadata is extremely difficult to devise protection tools for. There are just too many considerations.

I strongly advise against using terms like "Good," "Excellent," and "Paranoid." This is misleading in several ways. First, the privacy protections are more determined by the number of other users also sending transactions around the same time, and this is only one small component. Furthermore, sending a transaction with the "Good" setting during a good time provides a lot better privacy than sending a "Paranoid" transaction during a bad time.

It's important to note that a user sending multiple 10 ZEC transactions over time period is easier to identify than users sending smaller denominations. It may make sense for the tool to take migration processes handling 3+ 10 ZEC transactions by making more transactions with smaller outputs to more closely follow other migration patterns. Again, this is difficult to say. I need more data on this to give better insight, but it's another thing to look out for.

### IP Address / Network Analysis

Transactions sent from a user can be identified to the user or grouped together by investigating the network metadata. The tool should strongly encourage the use of Tor when sending these transactions. While VPNs help break the association to a specific person, they do nothing to help prevent transactions from being associated to each other. The wallet should force the user to acknowledge the network risk and encourage or force them to run in Tor mode. VPNs and coffee shops probably don't cut it, especially for several transactions over short windows.

Users should consider connecting to a small set of peers, perhaps fewer than default. This reduces the number of participants who are exposed to the network metadata. Users should connect to different peers for each transaction.

It goes without saying migrating with SPV/lightweight wallets is a terrible idea.

## Recommendations / Conclusion

There are so many considerations here it's crazy. This tool has a literal impossible task to accomplish, so we need to live with the consequences of something that's "good enough" while openly sharing the limitations.

I recommend the following features in a turnstile migration process:

1. Using set denominations of 0.01, 0.1, 1, and 10 Zcash (~$1.2, $12, $120, $1200). It would be great if these are network-enforced.

2. Allowing only one denomination per transaction.

3. Dropping the "Good" "Excellent" "Paranoid" wording. It's misleading at best, dangerous at worst.

4. Setting the transaction time period to focus on spreading transactions apart from each other. For instance, setting a 2 day window would select a 2 day window for one transaction and 1 day windows for 2 transactions. This user-facing approach is easier for a user to understand.

5. Consider setting periods where people migrate en masse. This could be a set time, such as the approximate block time at 1:00 UTC on the first of every month. I'd love to hear your thoughts here, since I do not know of any other discussions about this.

6. Require or strongly recommend Tor, and clearly explain why even VPNs are likely insufficient for many threat models.

7. Connect to few participants, and connect to new peers for each transaction. This helps mitigate the VPN risks.

Hopefully this long wall of text is helpful to at least show the difficulty of this task. I'm happy to toss additional thoughts back and forth and to explain things further.

**Comment by braddmiller** [comment]
@adityapk00 Thanks so much for the write up in the forum and implementing this feature. We'd love any additional input you have in the design, the Zcash Co is going to implement a migration tool and we would like all of the tools used in the community to follow the same rules, any input here would be great.

@radix42 Would also love to get some input from your perspective for implementing on WinZEC

@SamsungGalaxyPlayer amazing write up, thanks for doing that

**Comment by adityapk00** [comment]
@SamsungGalaxyPlayer Thanks for the detailed writeup.

From the perspective of a UI developer, I'd rather use a migration RPC call that zcashd provides, because implementing it in the UI has been a pain. I agree with most of your recommendations, with a few comments:

### 1. "Good", "Excellent" and "Paranoid" 
I added these because from a UX perspective, we need some words to connect what's happening to what the users are familiar with. "Turnstile" is not a good UX word since (1) It doesn't explain what's happening underneath, and (2) It's not a concept users are familiar with in the crypto space. 

There's two ways to think about the sapling turnstile migration from a UX perspective. 

- It is an "**upgrade**", where the wallet will take care of doing everything needed and the user doesn't have to spend any time thinking about it. We don't need the user's attention. Kinda like a database upgrade or a backend upgrade. 
- It is a "**migration**", where the user is actively involved in doing the migration. The wallet can facilitate the migration, but we need the user's attention. 

I would have preferred to do it as an "upgrade", but unfortunately, we need the users's attention because we need for the user to backup the wallet to save the private keys of the intermediate t-addresses if something goes wrong. If zcashd had HD wallets for z-Addrs and t-Addrs, then we could have done everything automatically without needing the users attention. 

Since "upgrade" is out, we need to do it as a "migration", with the users attention. Now, if we're asking for the user's attention, we also need to provide context and control. The user has several questions, two of which we need to directly address

1. How much is this going to cost me?
2. How long is this going to take? 

The "Good"/"Excellent"/"Paranoid" is an attempt to capture answers to this question in an understandable way. 

The user also has several auxiliary questions that they are implicitly trusting the wallet will take care of. 

1. Do I need to keep the wallet open the whole time? 
2. What if something crashes? 
3. Are my funds at risk? 
4. Can I spend funds while the migration is in progress?

zec-qt-wallet tries to do the "Right Thing™" for these, but it is not great UX experience. 

### 2. Setting a period where people migrate en masse.
In my opinion, this is not good UX. Requiring a user to perform an action at a given time asks too much of the user. Even if we don't ask the user for this (and do it automatically), the user is still going to be annoyed. What if the migration date/time is in the middle of the night in my timezone? What if I'm traveling? Do I need to be physically present in front of my computer? What if it crashes and I miss the migration window?

If there are multiple dates/times where the migration window is open, then there's additional UX overhead of choosing one. This is cognitive overload for a user that's casually using ZCash.

We have to remember that the turnstile migration UI is for a casual/non-paranoid user. Sophisticated users already know how to do it properly, and they are going to likely do it manually. The UI is for people that want the UI to help them do it without too much cognitive overhead in a privacy safe way. 

Of course, this is all a UI developer's perspective, and I recognize that from zcashd's perspective, things look very different. 

### Conclusion
All this being said, I think it would be great if there was a standard way of doing this, implemented through an RPC call. From a UI developer's perspective, the details (what denominations, time period of migration, how many Txs) matter less than the cognitive load presented to the user. 

If we ask too much of the user, they're just going to ignore us and send everything in one Tx, because that's the path of least resistance.

**Comment by SamsungGalaxyPlayer** [comment]
@adityapk00 thanks for the comments regarding the UX.

I still vehemently argue that the "Good", "Excellent" and "Paranoid" wording is highly inaccurate for the reasons I argued above. I understand that you want to simplify the user experience, but this should be done by instead clearly communicating the time to the user. The tool should not make claims relating the privacy offered to specific threat models. I understand the desire for simplicity, but frankly with this wording, it is false advertising.

Instead, I strongly recommend some UI/UX features I explained above. **Let users select the total time they would like to spend migrating, and then the wallet can sort the transactions out from there.** I cannot think of something simpler and more accurate from the user's perspective. They clearly understand the approximate time, and the wallet doesn't oversell the tool's effectiveness. It may be simple for the user to understand these three terms, but it communicates *dangerously incorrect* information.

This way, users can even specify shorter time periods than default if they wish. This should help increase utility and use. In my opinion, it leads to a better UX.

By all means, wallets should attempt to answer these other questions you mentioned for the user, but this is entirely a UI/UX feature, not directly related to the privacy offered.

I acknowledge the UX issue in recommending that users send transactions at specific times. I do not expect every user to perform this migration at this time, but perhaps the UI can communicate that this process is recommended. Users with a high desire for privacy will follow these recommendations, and users who don't really care won't. I agree any sort of consensus rule around this would be difficult to work around and bad UX.

Frankly, the "send at specified time" recommendation is only effective when multiple people are in the process of migrating, likely shortly after the fork. Most of the time, it will not provide any substantial protection.

> Sophisticated users already know how to do it properly, and they are going to likely do it manually

I disagree, especially since there are still no guidelines (minus this GitHub issue) regarding the correct way to handle this process. This tool is the best chance users have. Even if your specific implementation of the wallet does not follow best practices, this is the best tool people will have to protect themselves, and the RPC call should be able to handle the best-practices we come up with here.

**Comment by adityapk00** [comment]
Ok, you've convinced me. I made the change to remove the labels, and let the users pick the duration/number of transactions.

https://github.com/adityapk00/zec-qt-wallet/commit/82675c7e47b4bb40c85149afebc0cea01564a8c5

I'll look forward to the RPC call in zcashd.

**Comment by SamsungGalaxyPlayer** [comment]
@adityapk00 great! One small point of recommendation: users shouldn't specify the number of transactions they will make. Instead, they will simply give a time period, and ideally the wallet would separate their Sprout outputs into different transactions per output automatically.

**Comment by adityapk00** [comment]
Yup. That’s how it works in zec-qt-wallet today. Users pick the time period, the wallet calculates the number of transactions based on the amount and the time period and executes the turnstile migration.

**Comment by SamsungGalaxyPlayer** [comment]
The Zcash Company added some thoughts in their docs resource two days before the fork, quoted below. I assume the tool should follow similar behavior, though adjusted for my recommendations:

> Alice has a shielded balance of 14.6727 ZEC and doesn't want to reveal that a single address holds that exact value as she migrates to a new Sapling shielded address. She decides that paying six transaction fees to migrate is worth the cost to not reveal the total balance.
> 
>    She waits a couple of hours before initiating the second transfer, revealing 4.0001 ZEC in address ``t1def...``. This leaves 0.6724 ZEC in the legacy address accounting for the third transaction fee. Once confirmed, she finishes the second transfer by sending 4 ZEC (accounting for the fourth transaction fee) to the same Sapling address. The balance in the shielded Sapling address is now 13.999 ZEC.
> 
>    She waits for the next day to initiate the third and final transfer, revealing 0.6723 ZEC (accounting for the fifth transaction fee) in address ``t1xyz...``. Once the transaction is confirmed, the legacy Sprout address is now empty and a may be discarded. She finishes the final transfer by sending 0.6722 ZEC (accounting for the sixth transaction fee) to her Sapling address which now has a balance of 14.6721 ZEC (the original balance minus six transaction fees).
> 
> Note
> 
>    If fees are not a concern, users are advised to split balances transactions which send values in powers of ten (.001, .01, .1, 1, 10, 100, 1000, etc.). A user with a balance of 139.34 ZEC using this method would migrate 100 ZEC once,10 ZEC three times,1 ZEC nine times,.1 ZEC three times and .01 ZEC four times. This adds up to 20 migrations and 40 transactions. At the default fee rate (.0001 ZEC per transaction) this would cost .004 ZEC.
> 
>    If time is not a concern, users are advised to delay migrating their split balances over intervals of time that are sufficiently random (between 2 and 100+ hours). A user with 40 transactions to complete their migration of 20 balances using this method could pick 40 random hour intervals in which to send the transactions.

It should go without saying that these transparent addresses should be one-time use.

**Comment by Eirik0** [comment]
This has been implemented v2.0.5
