### ISSUE TITLE
Zcashd v1.0.15 and below into safe mode a few days before Overwinter activates

### ISSUE THREAD

**Issue by mdr0id** [zcash/zcash#3328]
Per discussion in Zashd sprint planning meeting on 6/7/2018

**Comment by bitcartel** [comment]
To send or not to send?  A few points:

1. Ancient clients that existed before EOS Halt (auto-senescense/deprection) were introduced.
- will fork off from Overwinter.
- an alert might prompt those users to upgrade prior to Overwinter

2. Recent clients used the config option to disable EOS Halt.
- potentially many Zcash4Win users did this and they might fork off (Zcash4Win was the former name of Winzec.)
- Overwinter compatible Winzec 1.1.0 is available for users to upgrade to

3. The ecosystem may have its own schedule for upgrade (i.e. just before Overwinter activates, but not three days before) so shutting down their wallet may interfere with any migration or upgrade plan.

4. A policy of sending out alerts before a network upgrade does not work when there are multiple client implementations, since not all of them will support the alert system.

5. Overwinter was designed as a fairly simple upgrade so we can learn.  If we use the alert system as a crutch, we will do the same for Sapling.  If we don't use the alert system, and the upgrade is successful, we know we probably don't need it.  If we do run into problems, we can identify what those are and determine if an alert would have helped or not.

6. What happens to users who do happen to follow the old Sprout chain?  There will be little hashpower on the chain, meaning few or no blocks mined, and any transactions submitted will take a long time to confirm.  Ideally there should be no economic activity on the old chain, and sending out an alert would almost guarantee this, however if there are people who do want to use the legacy chain for whatever reason, shutting down their software via an alert could be contentious.  In the case of Sprout->Overwinter, it is unlikely to be an issue, but in future there could be a legacy chain with a decent share of hashpower that does not want to follow a network upgrade.

**Comment by bitcartel** [comment]
To send or not to send?  Please vote with thumbs on this comment.
- thumbs up (and reply with when to send out e.g. 3 days before, x hours before, after Overwinter activates.)
- thumbs down

**Comment by arielgabizon** [comment]
It's not clear from the title what you want a vote on exactly, please edit (it seems to start mid sentence)

**Comment by ebfull** [comment]
I think we should have @nathan-at-least vote and his vote should count as 10 billion votes. :)

The fact is, nobody notices these alerts (or cares to do anything about them) until they're disruptive. We should issue a safe-mode alert prior to activation which gives enough people to do something about it before the network upgrade. 5 days?

**Comment by zookozcash** [comment]
Fantastic summary of the facts and options in the initial post, Simon! ❤

**Comment by tromer** [comment]
@ebfull:
> issue a safe-mode alert prior to activation which gives enough people to do something about it

What's the disadvantage if we send the safe-mode alert just 10 minutes before activation?

From the user's perspective, things looks the same regardless of when safe-mode is triggered (as long as it's before Overwinter activation): their node stops working until they upgrade. So might as well give them the few more days to do it voluntarily.

**Comment by ebfull** [comment]
@tromer I think we're in agreement!

**Comment by zookozcash** [comment]
By the way, for those following along at home, Zcash Overwinter is going to activate, rendering old nodes incompatible, in 13 days! https://z.cash/upgrade/overwinter.html Perhaps fewer by the time you read this.

**Comment by saleemrashid** [comment]
This may be detailed elsewhere, but it's not clear from this thread how easy it is for a node operator to override/disable safe mode.

If an alert is sent out a few days before, and the node operator can override it, the downtime is minimized (as bringing the node back up is not contingent on successfully upgrading until Overwinter activates, and there would be a few days until that happens)

On the other hand, if it cannot be easily overriden (i.e. without recompiling), it should be done as close to the activation time as possible. Doing it in advance would be disruptive as there would be an unavoidable, prolonged period of downtime while the node is upgraded.

**Comment by garethtdavies** [comment]
Regarding Zcash4Win users (which I anticipate being a significant % of these non-upgraded nodes) - would any alert be visible to them or would it just stop working without any indication? Does the Swing Wallet GUI echo these alerts?

**Comment by bitcartel** [comment]
@garethtdavies @radix42 knows the answer to that question...

**Comment by daira** [comment]
There's a `-disablesafemode` config option. It requires a restart.

**Comment by daira** [comment]
In my opinion: the safe mode alert is necessary to prevent economic harm to users who would otherwise mistakenly transact on the forked-off chain without intending to.

**Comment by bitcartel** [comment]
We know of folk in the ecosystem who are running older versions of zcashd.  We don't know if they are using `disablesafemode`.  We don't know what their upgrade schedule looks like.  Thus I think sending out an alert a few days beforehand could result in the alert itself being a disruptive event with unforeseen consequences.

Sending an alert a few blocks before Overwinter activates (10-30 mins) would suffice and help prevent users from mistakenly trying to transact on the soon-to-be forked-off legacy chain.  Also the ecosystem already expects some level of disruption when Overwinter activates.

From a communications perspective, this is also less confusing to users than trying to remember two different dates.

I would prefer not to send out any alerts and would like to see the alert system removed from Zcashd as soon as possible, for the purposes of security and decentralization, but given this is the first network upgrade and there are still a large number of non-Overwinter nodes, this may be a necessary action for the time being.

**Comment by bitcartel** [comment]
@daira You mentioned that some non-Overwinter nodes might not receive the alert as they may have partitioned away due to the network preference code.  The code does not guarantee a partition will happen so they could still receive the alert.

In any case, it looks like v1.1.1 nodes will stay connected to non-Overwinter compatible nodes due to this commit: https://github.com/zcash/zcash/commit/d670db7164c9c49eb43f10b40efc2adaa473422f#diff-9a82240fe7dfe86564178691cc57f2f1

This is unintended but does increase the likelihood that the alert will propagate to reach its intended targets.  Also, for those nodes which are not reached, with or without the alert, those old nodes would face service disruption at Overwinter activation anyway, per the comment above.

**Comment by daira** [comment]
Eek, how did that commit (d670db7) get past review? I would have NACK'd it, since we didn't agree to make that change to the connection logic as far as I know (unless it was in a meeting I wasn't present at).

**Comment by daira** [comment]
In any case, I agree that it's okay to send the alert half an hour before activation. We should have the alert PR ready and reviewed well before then.

**Comment by radix42** [comment]
No, none of the Swing UI Wallet variants, regardless of coin, that I know about surface alerts in the UI in any way, and legacy zcash4mac and zcash4win users will indeed be on the old chain/baffled.

The current WinZEC.com release is straight up zcashd 1.1.0, without any disable deprecation patches or settings and the stock ClientID of MagicBean (@str4d and I have branches that are Almost Ready for upstream merging for Windows builds).

As far as the future of WinZEC post-Overwinter, and the still a theoretical scenario of there being MacZEC (its just a registered domain), I'd need funding for all that....especially since address formats are changing and there are numerous patches that need to be incorporated from more recent Swing UI forks for other coins (the ZenCash variant is the one under most active development and it'd need to be backported to zcash and tweaked for Sapling).

I'll be making a forum post on all this and the possible futures from here with this wallets shortly, which I'll cross link from here when its up.

**Comment by radix42** [comment]
The above-promised forum post for broader community input in re: the future of legacy Windows nodes that will chain fork with Overwinter activation and auto-senesence of current WinZEC, etc:
https://forum.z.cash/t/winzec-zcash4win-mac-overwinter-and-sapling-an-uncertain-future/29769
