### ISSUE TITLE
some question about Elliptic Curve

### ISSUE THREAD

**Issue by NickyYangYang** [zcash/zcash#3352]
Hello , I want to know why you choose BN128 Curve in your code ? Why not BLS?
And why you want to change the Curve to BLS12-381 , why not BN254 or other BN Curve?

**Comment by str4d** [comment]
- BN128 and BN254 are the same curve (BN128 was the earlier name that described its desired security level, which it doesn't meet any more; BN254 describes it in terms of the field size).

- I don't know why we used BN254 for Sprout rather than a BLS curve; someone else could answer that.

- We are switching to BLS12-381 for several reasons:
  - It is closer to the 128-bit security level than BN254.
  - It has much better performance than the larger BN curves with similar security / field sizes.
  - It has an embedded twisted Edwards curve (which we named Jubjub), which enables us to implement elliptic curve in the circuit much more cheaply than with BN254 (six constraints for a point addition instead of hundreds).

**Comment by NickyYangYang** [comment]
Ok, thank you very much.

I hope someone else could answer  why you used BN254 for Sprout rather than a BLS curve.

**Comment by ioptio** [comment]
@daira or @ebfull might know?

**Comment by arielgabizon** [comment]
The point when Sprout was developed was before some developments in NFS algorithms, when it was more widely believed that BN254 had 128 bit security

**Comment by mdr0id** [comment]
@NickyYangYang Please let us know if you have other questions. @arielgabizon  and @ebfull have provided answers to your original questions.
