### ISSUE TITLE
Upgrade testnet faucet

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#3364]
On faucet.testnet.z.cash it shows the currently running version as 1.0.15. I assume it still works fine since Overwinter activated on testnet via 1.0.15?

**Comment by skyl** [comment]
I'm running 1.1.1 testnet and was recently unable to get any coins from the faucet. I just now tried `tmGZf4dhe99VuNe5NZYULReVkofJbtybzxt` and am unable to detect any evidence that I have coins there.

Also, https://explorer.testnet.z.cash/blocks seems to not be compatible - right now my node has height 263199 and the explorer has 260358.

**Comment by garethtdavies** [comment]
The issue is there are two testnet chains running Overwinter and Sapling. On v1.1.1 Sapling has activated on the testnet so this faucet is running on the Overwinter testnet chain. Anyone who needs to use this faucet on the Overwinter chain needs to use the v1.1.0 release of zcashd.

The same is true of the block explorer.

There was some discussion of firing up a faucet and explorer on the Sapling testnet chain but I am not sure if they are working.

**Comment by ianamunoz** [comment]
Resolved now. The faucet is running sapling now and we have deprecated the Overwinter fork.
