### ISSUE TITLE
Some question about shielded transaction

### ISSUE THREAD

**Issue by NickyYangYang** [zcash/zcash#3428]
Hi,
    I get the Zcash transaction format from [Zcash Protocol Specification].
    Now, I have some question about  transaction format when shielded transaction. If there is a transaction from shielded address to shielded address, is there input and output in the transaction( tx_in_count and tx_out_count is zero) ? If there is input and output in the transaction, the strcuture of input and output is same  with Bitcoin?

**Comment by str4d** [comment]
If the transaction only involves shielded addresses (Sprout, Sapling, or both), then `tx_in_count` and `tx_out_count` will both be zero, meaning that `tx.vin` and `tx.vout` are both empty. You can expect to see a non-zero `vpub_old` or `vpub_new` if Sprout addresses are involved, and a non-zero `valueBalance` if Sapling addresses are involved. The value sum inside the transaction is:

    sum(tx.vin nValue) - sum(tx.vout nValue) + sum(tx.vjoinsplit vpub_new) - sum(tx.vjoinsplit vpub_old) + tx.valueBalance = fee

The structures of `CTxIn` and `CTxOut` are unchanged from Bitcoin, correct.

**Comment by NickyYangYang** [comment]
OK，thanks for your answer.

**Comment by NickyYangYang** [comment]
Hi，
I have other new questions about shielded transaction. 
1、Why the Nold and Nnew equal 2 ?
2、 In  JoinSplit description , 'vpub _ old' and 'vpub _ old' must be 0 , I think tis for shilded the value. Then , why still leave these in the JoinSplit description ?
3、In JoinSplit description ,  includes input node and ouput node. Why  the count of  JoinSplit is 'n' but not only one?

**Comment by daira** [comment]
@NickyYangYang wrote:
> 1. Why [do] N<sup>old</sup> and N<sup>new</sup> equal 2 ?

The zk-SNARK circuit has a fixed size, and the maximum number of inputs and outputs per JoinSplit must be fixed in order to achieve that. 2 inputs and two outputs are the minimum needed in order to be able to join and split shielded notes (hence the name "JoinSplit"). This is the same as in the Pour proofs of the original Zerocash design.

This does not quite mean that the minimum is optimal for performance; in particular we considered increasing the number of outputs, as discussed in #237 and #426. However, limiting the number of outputs to 2 meant that we were able to keep the number of constraints in the circuit below 2<sup>21</sup>. Since there is a step increase in the cost of proving at each power of two in the number of constraints, this choice turned out to be optimal given the techniques we had then (and time available to make changes before the Zcash launch was also a limiting factor). This decision was also informed by the fact that most Bitcoin transactions have few outputs.

Sapling makes use of a different technique, with homomorphic value commitments, which circumvents the requirement to be able to join and split notes in a single proof. This allows us to use one proof per input and one per output, which makes the construction of partially shielded transactions that leak the minimum amount of information much simpler.

> 2. In JoinSplit description, `vpub_old` and `vpub_old` must be 0, I think this for [shielding] the value. Then, why still leave these in the JoinSplit description?

At most one of them must be non-zero. `vpub_old` is the amount being shielded, and `vpub_new` is the amount being deshielded, by this JoinSplit.

> 3. In JoinSplit description, includes input [note] and output [note]. Why the count of JoinSplit is 'n' but not only one?

Multiple JoinSplits can be needed for several reasons:
* there may be more than 2 input z-addresses, or more than 2 output z-addresses;
* each input can only spend a single note, and more than 2 notes may need to be spent to reach the specified amount to be sent from a given z-address;
* one of the outputs from each JoinSplit may be used for change. In fact [for privacy](https://github.com/zcash/zcash/pull/2440), zcashd always constructs JoinSplits with one output for change, when change is needed. (This may be "internal" change directed to an input of the next JoinSplit rather than back to a z-address.)

**Comment by NickyYangYang** [comment]
Hi,
A note is spent by proving knowledge of (ρ, ask) in zero knowledge while publically disclosing its nullier nf ,allowing nf to be used to prevent double-spending. 
   nf = SHA256Compress(1110 || ask || ρ)
When receiving the transaction, receiver verify that: nf does not appear on the current ledger.
1、 Can the nf be unique?
2、 If the nf has appeared on the current ledger, how to do?

**Comment by ioptio** [comment]
@NickyYangYang can you bring up future protocol questions in the community chat which is a better channel for devs to answer and others to see and engage with as well? https://chat.zcashcommunity.com

**Comment by NickyYangYang** [comment]
OK

**Comment by daira** [comment]
@NickyYangYang nf is almost certainly unique to a given note, because it's derived using a collision-resistant PRF applied to ρ and ask, and ρ is also almost certainly unique as described in the section "Faerie Gold attack and fix" of the protocol spec.

If any of the nf values revealed by a transaction have already appeared then the transaction should be rejected.

**Comment by NickyYangYang** [comment]
I see.

**Comment by NickyYangYang** [comment]
@daira  The nf values computed by the receiver when the transaction has been packaged into block .  If the reveiver reject the transaction, how to do about the block?

**Comment by daira** [comment]
Blocks that contain invalid transactions (for whatever reason) won't be accepted into the block chain.

**Comment by ioptio** [comment]
Let's take this conversation to the community chat: https://chat.zcashcommunity.com

**Comment by jotto** [comment]
FWIW this Github issue is one of the few places discoverable from search engines for context on vjoinsplits, vpub_new, and vpub_old beyond the whitepaper.

Are the chat archives indexed anywhere?
