### ISSUE TITLE
why t_addr balance is not showing on testnet Explorer.

### ISSUE THREAD

**Issue by VtpVlan-oo7** [zcash/zcash#3437]
When Blockchain is fully synced. I blockchain is running on testnet.
i am checking t_addr balance on this explorer https://explorer.testnet.z.cash/

**Comment by garethtdavies** [comment]
See my reply here: 
https://github.com/zcash/zcash/issues/3423. Assuming you are running v1.1.1 or later you will be on the Sapling testnet and the explorer for that is here: 
https://explorer.beta.z.cash/ (it is known to not be working properly)

**Comment by ioptio** [comment]
@VtpVlan-oo7 the testnet explorer is still being upgraded to support Sapling. Ping @ianamunoz for clarity on which explorer users can use right now.

**Comment by ianamunoz** [comment]
So testnet is forked right now because of the way our upgrade schedule occured:

There are two forks currently:

Fork 1-
v1.1.0 is running on testnet.z.cash, explorer.z.cash & faucet.z.cash 

Fork 2-
v1.1.1 is running on https://explorer.beta.z.cash which has a bug on one of it's api requests but you can still search transactions or blocks. It just has a bug displaying the list on the load page
stagenet.z.cash, and sapling-faucet.z.cash are also v1.1.1 and you can get testnet funds on this fork with the sapling-faucet. (the atrocious naming is my fault. )

We have an RC candidate coming out this week for 2.0.0 so upon the release of 2.0.0 this will all change to something more consistent.

**Comment by ioptio** [comment]
Try 2.0.0 testnet and reopen if you still have issues.

**Comment by ztlovemst11** [comment]
@garethtdavies @ioptio @ianamunoz 
Although I read your answer, I still feel confused. How can I get a useful testnet exploer? Although I found  [](https://chain.so/testnet/zcash), I got the test coins from [](https://faucet.testnet.z.cash/), but it's not applicable.What is the release of 2.0.0 you are talking about?

**Comment by garethtdavies** [comment]
@ztlovemst11 2.0.0 is the latest Zcash release see here: https://z.cash/download.html

This release is compatible with the faucet here: https://faucet.testnet.z.cash/ and the explorer here: https://explorer.testnet.z.cash/. As Sapling has activated on testnet (at block 280000) no block explorers currently work correctly to display all data (to my knowledge) as none have been upgraded to support Sapling.

**Comment by ztlovemst11** [comment]
Sorry,I just want to query the balance of the address and the transaction list information through an testnet api, and I don't want to build a zcash node for myself...

**Comment by ztlovemst11** [comment]
Can you send me a test coin to this test address? 
tmP2iiqKR6bQmQWALTXtjsXcC5hvJDWY8Wb
Don't need too much.
I need to test the code for the broadcast transaction.
Thankx very much.

**Comment by ianamunoz** [comment]
@ztlovemst11  go to faucet.testnet.z.cash and you can get testnet funds.

**Comment by ztlovemst11** [comment]
@ianamunoz As I said before, although I go to faucet.testnet.z.cash to get some test coins, But I can’t use it because [](https://explorer.testnet.z.cash/) can’t work normally.
