### ISSUE TITLE
Ask amiller to summarize how to integrate lightning.network and Zcoin.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#345]
@amiller to close this ticket, send us an explanation about potential ways to integrate lightning.network with Zcoin, with tradeoffs and recommendations.

**Edit:** Removed 'whitepaper', a more-or-less meaningless term.

**Comment by daira** [comment]
@amiller got unassigned unintentionally in the org change.

**Comment by amiller** [comment]
Sorry I've dropped this ticket! I'm just going to briefly summarize some of the thinking and discussion's we've had.
There are broadly speaking two approaches to doing lightning in zcash. Option (1) is to support payment channels established using "protected" coins as collateral. Option (2) is to support payment channels with unprotected/plaintext coins.

Option 2 is simple to support. If Bitcoin core is modified upstream to support lightning, then we'll simply get this capability as well. 
Option 1 is more technically interesting. My analysis is it would require changes to the circuit (or potentially an additional payment-channels-specific circuit). At minimum the circuit would need to be modified with the equivalent of `OP_CHECKTIMELOCK`, to enable a payment channel to be shut-down if one of the parties aborts. For some purposes (especially for micropayments), it would be infeasible to have to compute a SNARK proof for each payment. A clever solution is to simply create a public key signature for each payment, and then only a single SNARK proof when it is time to settle and close the channel. This would likely require a more expensive modification to the circuit. I haven't thought of a lighter-way to do this without public key cryptography. We have not invested much effort in spec'ing this out because it would require changes to the circuit.

There are other concerns about the privacy of lightning. It's expensive (in terms of collateral) to establish a channel. It's not clear whether the resulting collateral graph would look oligopolistic / hub-and-spoke, or more like a random network. Sending a payment along a channel is somewhat like sending along a Tor circuit (except that Tor circuits are sampled mostly randomly rather than along preestablished links).
