### ISSUE TITLE
sapling; z_sendmany default memo is zeros, should be 0xF6

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#3604]
### Describe the issue
Sending to a Sapling output using `z_sendmany` without specifying a memo results in the memo being set to all zeros. It should be "no memo"; see section 5.5 of the protocol specification.

@str4d recently fixed this for `change` transactions here: https://github.com/zcash/zcash/pull/3518/commits/ba63dacbbbc647e4a84824a7aee5838c5bcabab4

### Can you reliably reproduce the issue?
Yes, it's easy to reproduce manually using the cli on testnet (not mainnet, as Sapling has not yet activated on mainnet). It is also easy to reproduce using the rpc tests.

#### If so, please list the steps to reproduce below:
1. Start `zcashd` on testnet
1. Create a Sapling address (`src/zcash-cli z_getnewaddress sapling`)
1. Send a payment to this Sapling zaddr without specifying a memo
1. Wait for the transaction to complete
1. Display the transaction using `z_listunspent` or `z_listreceivedbyaddress`

### Expected behaviour
The first byte of memo field of the transaction should be 0xF6 followed by 1023 bytes of zeros. This works correctly for Sprout output addresses.

### Actual behaviour + errors
The memo field shows as all zeros. (No errors are reported.)

### The version of Zcash you were using:
v2.0.1-rc1

**Comment by str4d** [comment]
Darn, I thought I'd fixed it everywhere in that commit. I've dug in, and I found the actual cause [here](https://github.com/zcash/zcash/blob/master/src/wallet/asyncrpcoperation_sendmany.cpp#L1336): the function I used to get the hex memo (which has been there since launch) uses the wrong memo. It doesn't affect the Sprout usage because there, [the string memo is checked to see if it is non-empty](https://github.com/zcash/zcash/blob/master/src/wallet/asyncrpcoperation_sendmany.cpp#L642-L644), and only then is the function called.

**Comment by LarryRuane** [comment]
@str4d, thanks; I was just about to create a PR for this, but maybe my solution isn't the best: https://gist.github.com/LarryRuane/c4b64a8e452fab5eb0d6076ecdf9468a

Should I go ahead and make a PR with that proposed change, or fix it in the lower-level function you referred to, `AsyncRPCOperation_sendmany::get_memo_from_hex_string()`? (I thought of that too but wasn't sure.)

I could push both as separate commits, so people can review both and decide which is better.
