### ISSUE TITLE
Request to maintain transaction version compatibility with the previous version on every future network upgrade, regardless of the upgrade goals or technical requirements

### ISSUE THREAD

**Issue by acityinohio** [zcash/zcash#3655]
I'm not sure if this is the right way to submit this issue, but I'm going to try here. Feel free to modify/triage accordingly!

### Describe the issue

Based on feedback from chatting with @str4d, @nathan-at-least, and @zookozcash, I decided to parlay my feedback from a recent meeting with some hardware wallet developers. They raised the issue that during hardfork upgrade cycles, the lack of backwards compatibility for transactions can cause unforeseen problems with their Zcash support—even with well prepared upgrades, testnet behavior can diverge from mainnet behavior, and it puts them in the unenviable position of having to rush to get firmware updates to users. Depending on the update, users may have to re-enter their seed phrase, which for many has a rather involved recovery process. Users tend to blame them, which is subpar experience for them and also makes supporting coins with frequent, backwards-incompatible hardforks a more difficult business decision. I speculate that this affects every hardware wallet manufacturer, though I have only received feedback from one.

### Proposed solution

For every future hardfork, where feasible, it would be great to have compatibility with the _last_ network upgrade, and only the _last_ network upgrade.

As an example, and apologies for the bad hardfork code names:

Sapling: v4 txs
Super-sapling: v4, v5 txs valid
Ultra-mega-super-sapling: v5, v6 txs valid (_v4 transactions no longer valid and rejected by the network_)

Anyway just thought I'd relay the feedback; I think this would be a good norm to set and would make hardware support potentially more tenable.

**Comment by daira** [comment]
I don't think that we should commit to maintaining compatibility with the previous tx version in each upgrade.

There already *should* be at least 6 months between upgrades. The ~4 months between Overwinter and Sapling was a mistake that will not be repeated.

We don't break compatibility with the previous tx version gratuitously, In fact, we paid particular attention in the network upgrade design to making sure that tx version upgrades were decoupled from consensus upgrades. However, there were *good* reasons to do so for both Overwinter and Sapling. (In Overwinter it was necessary to achieve the security/robustness goals. In Sapling it was entailed by the decision to switch to Groth16 proofs for JoinSplits.) There might be equally good reasons to do so in future upgrades.

**Comment by daira** [comment]
Incidentally, yes this was the right place to submit this issue.

**Comment by nathan-at-least** [comment]
One primary goal of our network upgrade design is to provide strong replay protection. AFAIK that *requires* ensuring that a `v<N>` transaction is not valid for exactly the range of time that the `v<N+1>` transactions become valid.

There are two motivations for strong replay protection:

First, to protect users in the event of a non-chain-splitting upgrade, even in the face of malicious actors (including some amount of miners). If a product fails to work after the upgrade activates, the harm is a lack of availability for the user. By contrast, if we err in the other direction to allow products to work more seamlessly, we *might* allow some users to lose funds to malicious actors (or just incompetence). We feel the "fail-safe" side of the fence is best. (Though, I want to acknowledge an availability failure can cause economic harm, such as to traders or even normal users who have deadlines, as well as the reputation/customer loyalty harm to the product vendors.)

Second, in the event of a chain-splitting upgrade, such as a contentious split or a "friendly fork" we want to ensure all products and users are 100% unambiguously clear as to which side of a split they are operating on.

Given those motivations, it *may* be possible to change the consensus rules for future upgrades to somehow meet those goals while also addressing the pain point for vendors. Any ideas there?

Until diving into that, however, I'd really like to improve our support for testing. I believe the ideal for production testing would be the ability to run a device or product on a "mainnet-in-a-vat" using the device's full production configuration and codepaths. In other words, it should be impossible for a device to distinguish whether it's in "mainnet-in-a-vat" versus the true mainnet. There are a few hurdles to achieving this ideal. The main one is that if you want to test around activation heights, then PoW requires prohibitive costs to set up the test environment. (This is another reframing of a key PoW security property!) Another reason might be that you want to test in a rich heterogeneous environment with many different events propagating through your test apparatus.

So before we explore changing the consensus rules, I'd like to explore what's the most effective and useful we could make a test environment tool to allow testing. Another line of inquiry: why isn't testnet already good enough? (One answer: it uses different address encodings for example, therefore the device codepaths are necessarily different.)

**Comment by nathan-at-least** [comment]
More thinking about mainnet-in-a-vat: if it is initialized with true mainnet snapshots, then running tests on it requires using real mainnet private keys. This could be operationally dangerous for theft, and also it may violate privacy guarantees. Do we already have a ticket about analyzing privacy guarantees in the case of a chain-split?

**Comment by daira** [comment]
@nathan-at-least Transactions are not replayable across branches regardless of whether the previous transaction version is supported. This uses the fact that the sighash algorithm is dependent on the consensus branch id. It is not necessary to avoid supporting previous tx versions for this reason (but the other reasons I gave above for not *committing* to supporting them, still apply).

**Comment by daira** [comment]
I argued strongly for not committing to maintaining tx compatibility. Frankly, we *can't* do so if we want to be able to make the kinds of changes that occurred in Overwinter and Sapling in future. Unless there is a counterargument, we should close this ticket.

**Comment by acityinohio** [comment]
Thanks for the feedback @daira and @nathan-at-least — all of your arguments make sense to me, as does the prospect of making a better testing environment to meet the needs of these manufacturers.

However before closing the issue entirely, I'm going to forward this discussion to the folks I chatted with earlier. I fear I may not have done justice to their feedback and hope they may provide additional context here.

**Comment by slush0** [comment]
While I understand arguments of replay protection, coupling replay protection with breaking changes in the protocol itself makes very hard for us to commit to timely updates to our users. The fact that *you* define when *we* have to be ready (at exact hour) with release of our whole stack is unbearable in long-term and I suggest to think more about how such backward incompatible changes should be rolled out. Thay may have dramatic effect on whole Zcash infrastructure.

**Comment by prusnak** [comment]
It would still be a problem even if they were not close together.

**Comment by daira** [comment]
Replay protection is a red herring because the network upgrade mechanism ensures it regardless of tx version compatibility.

@slush0 wrote:
> The fact that *you* define when *we* have to be ready (at exact hour) with release of our whole stack is unbearable in long-term and I suggest to think more about how such backward incompatible changes should be rolled out.

Well, that's how it works. Activation based on anything other than block height wouldn't improve the issue; you still wouldn't be in control of when the upgrade happens. Committing to always allowing the previous tx version is not feasible, because it would rule out important classes of consensus changes that we've needed in previous upgrades.

**Comment by prusnak** [comment]
> Well, that's how it works. 

Well, in that case, I suggest your company allocates more people to work on Trezor so the firmware update is ready before the next hard fork happens. Your project managers should also include patching the whole ecosystem into their planning. Zcash is not just zcashd.

**Comment by daira** [comment]
This ticket is not about general ecosystem support. It made a very specific request: that we should commit in advance that every future network upgrade will always support the transaction version defined in the previous upgrade. The answer is: no, we are not going to make that commitment for all future upgrades.

If you have other complaints or requests, please file another ticket.

**Comment by zookozcash** [comment]
I don't think this decision has been made yet. This decision would need to be made by Nathan, not by Daira.
 
I have a proposal and then I'll scan through the comments above for pros/cons and see how each one matches up to this proposal:

Proposal: We could commit to a plan where in each Network Upgrade, we introduce a new, backward-incompatible transaction format. (This is what we've already done with Overwinter and with Sapling.) At the same time, the consensus rules continue to allow the previous transaction format, but they simultaneously disallow the previous-previous transaction format.

For example:

NU 2019-10 (“Blossom”): add tx format v5, maintain acceptance of tx format v4
NU 2020-04 (“New Arboreal Codename Goes Here”): add tx format, v6, maintain acceptance of tx format v5, end acceptance of tx format v4
NU 2020-10 (“Even Awesomer Codename”): add tx format v7, maintain acceptance of tx format v6, end acceptance of tx format v5

(This is the same example that Josh Cincinnati gave [in the OP](https://github.com/zcash/zcash/issues/3655#issue-376192466).)

Here are all the pros/cons I can find in this thread about this issue:

1. This would make it so that implementors like Trezor have a six month window ("grace period") during which their product continues to work for their customers (but does not support new features introduced by the most recent upgrade). They say that this is a major factor for the difficulty of supporting Zcash and we should take them at their word. They are experienced professionals, Zcash supporters, and have a long track record of doing a lot of excellent work on this stuff, and if they say this makes a big difference to their jobs, then I'm going to assume they are correct about that. _Pro_
2. This would be incompatible with ending backward-compatibility as soon as possible. Daira [gives the example](https://github.com/zcash/zcash/issues/3655#issuecomment-434994537) of how NU 2018-10 (“Sapling”) ended backward-compatible support for old-Sprout (Sprout-BCTV14/bn128/libsnark) and replaced it with new-Sprout (Sprout-Groth16/BLS12-381/bellman). If we had this policy in place then we either would have had to leave old-Sprout in place for another NU cycle (which in this case would have been 12 months but in the future it should be 6 months every time), or else we would have had to make an exception to this policy, telling everyone "Hey, normally you get a full NU cycle's worth of backward compatibility with tx v3 and old-Sprout, but in this case we're making an exception and ending backward-compatibility with tx v3 and old-Sprout early". _Con_
3. Would this put users at risk during a chain-split due to weakened replay protection (suggested [here](https://github.com/zcash/zcash/issues/3655#issuecomment-435085018), contradicted [here](https://github.com/zcash/zcash/issues/3655#issuecomment-435373714). Apparently not, so this is neither a _pro_ nor _con_.
4. Would this add complexity into the network protocol? Taking the old-Sprout-to-new-Sprout change as an example, since new-Sprout came into effect at the same time as old-Sprout became obsolete, we never had to implement consensus rules that could accept _either_ old-Sprout or new-Sprout transactions. It is much simpler in the consensus protocol if you have to implement "accept only old-Sprout up until blockheight `H`, and accept only new-Sprout after blockheight `H`" instead of implementing "accept only old-Sprout up until blockheight `H`, then accept either old-Sprout or new-Sprout up until blockheight `H+105192`, then accept only new-Sprout starting from blockheight `H+105192`" .

Okay, now here's my personal evaluation.

Item 1 is super-important. Making implementors lives easier is very important, not only for wider and better-quality adoption, but also to protect users! I'm very skeptical when I see someone who does this as their day job, very successfully, for years saying "This is really important to my job." and other people who don't have that experience saying "I don't see why.".

Item 3 was a mistake. A one-NU backward-compatibility cycle on mainnet would not harm replay protection.

Item 4 is the added complexity in the network protocol of supporting 

Item 2 is the tricky one. It's a classic trade-off between innovation and stability. It was great that we were able to end old-Sprout in 2018-10 instead of having to wait til 2019-04 (pretending for a minute that we were already on our intended every-6-months NU cadence).

However, it is also not great that people like Trezor couldn't schedule their Sapling-support upgrade to happen in 2019-01. With the 6-month backward-compatibility window on mainnet, they would've been able to schedule that themselves (within the window).

A big question is how often we will _need_ to end backward compatibility six months earlier vs six months later. I think it is super great that we replaced old-Sprout (Sprout-BCTV14/bn128/libsnark) with new-Sprout (Sprout-Groth16/BLS-12-381/bellman) in 2018-10. It would have been a substantial risk (because old-Sprout is a much riskier cryptographic construction, and maintaining it would have maintained [two attack surfaces instead of one](https://github.com/zcash/zcash/issues/3071#issuecomment-371341766) and a burden on core consensus engineers to maintain old-Sprout for another 6 months. But, how often will it be a major cost to maintain backward compatibility for an extra six months? My intuition is that in the future we'll be increasingly willing to pay the cost of maintaining backward-compatibility for an extra six months. (Because there are more and more users, more value, and a more diverse user base, and so it just becomes more and more costly to innovate fast and more and more desirable to innovate slowly.)

Finally Item 4. I think it is super important — comparably important to Item 1. Nathan and Daira and Str4d are the professionals who spend their entire lives, with excellent success, doing core consensus protocols, and so if they say that having a period of overlap between old and new makes their jobs a lot harder, I'm going to believe them. Just like we don't want to make Trezor's job harder because doing so increases the chances of something going wrong that puts users at risk, likewise we don't want to make the core consensus protocol maintainers's jobs harder for the exact same reason.

Nathan: over to you! You've gotta input your own weightings of these three issues and come to a decision. If I were calling this right now I would say that starting next year Item 1 is going to become more important than Items 2 and 4 so I would be in favor of this.

I hereby propose this ticket as a Goal for Blossom (NU 2019-10)!

What: institute a policy of maintaining backward compatibility for one NU cycle after mainnet activation
Who is effected: third party implementors like Trezor and Bitgo, ecosystem partners like Gemini and Bithumb, all users
Why: Give implementors, ecosystem partners, and users assurance that they can schedule their Zcash upgrade projects at any time during the 6-month window, and that they can test their new product on mainnet before their old product gets broken by backwards-incompatibility.

**Comment by daira** [comment]
@zooko: that's what was originally proposed, and what I said we can't do: both Overwinter and Sapling would have violated it and we want to be able to have the same kind of flexibility in future.

**Comment by daira** [comment]
Also: it is not true that the proposed policy would mean that third party devs don't have to update their code for the new tx version on every upgrade. In most cases, they would still have to be updated to *parse* the new tx version.

Please note: I am not saying that we shouldn't strongly consider supporting the previous tx version for *each* upgrade. Just that we can't commit in advance to doing that for *every* upgrade.

**Comment by daira** [comment]
Here's the full list of things we couldn't have done if this policy had been in place for Overwinter and Sapling (@zookozcash mentioned only one of them above):

* We couldn't have implemented replay protection between Overwinter and the previous chain. (Overwinter would still have laid the groundwork for replay protection in subsequent upgrades, but it wouldn't have had replay protection itself.)
* We couldn't have solved the quadratic hashing problem completely with Overwinter activation. Denial of service attacks based on quadratic hashing (and accidental ones from users using the old tx version) would still have been possible until the Sapling activation.
* We couldn't have replaced the Sprout parameters completely with the Sapling ones. Until the next activation, forgery would be possible if *either* the Sprout or Sapling cryptography or parameters were compromised. The 2x performance improvement for JoinSplits would not have been realised.

**Comment by daira** [comment]
At Note that the design above forces a tx version update. It is possible to allow the special case of the previous tx version where there are no JoinSplits, or alternatively we can prohibit the previous version.

**Comment by daira** [comment]
Zooko asked me to reopen this, but I have not yet seen any valid argument in favour of this as a hard policy (as opposed to avoiding breaking version compatibility *if we can*, which no-one disputes is desirable when the changes being made in an upgrade allow it).

It is *already* the case that third parties will have at least 6 months of notice under the new NU schedule timeline, so this policy is not required for that.

**Comment by zookozcash** [comment]
I was helping someone use Zcash recently and I found out that Zcash is no longer supported by the standard (supported) Trezor wallet. Now you have to opt in to the _beta_ wallet if you want to continue using Zcash. This is a substantial cost, making Zcash less attractive and less safe for normal users.

**Comment by daira** [comment]
There's no evidence that Trezor's decision to not support Sapling for the previous wallet iteration would have been made differently if this policy had been in place. They would still have had to update the previous wallet in order to support it.

**Comment by daira** [comment]
I renamed the ticket to more accurately reflect the actual proposal. At least 6-month notice of a compatibility break is guaranteed anyway with the proposed schedule for future upgrades.

**Comment by daira** [comment]
I have a compromise proposal: set a point in the NU schedule timeline by which to make a decision whether the upgrade will preserve transaction version compatibility. If it is decided that it will, then that decision can't subsequently be changed. (It can however be changed in the other direction, before spec freeze.)

**Comment by daira** [comment]
Note that this compromise policy would probably have prevented the compatibility break for Sapling, because the "hybrid Sprout" proposal that needed it would have come too late in the NU cycle. It would not have prevented the compatibility break for Overwinter, which was planned well in advance.

**Comment by daira** [comment]
Refining the above proposal, I suggest that the above version compatibility decision should be made no later than the "Specification Pre-Audit Freeze" (see https://docs.google.com/drawings/d/1oUh7vnaulUoUYX9q4wxcO5XqPhbZB6DDD7V57EKPFPE/edit ; not sure whether that is publically visible but I think it is).

**Comment by nathan-at-least** [comment]
Hi all,

First of all, Blossom is the first upgrade which, according to current goals, does not necessitate any notable impact on transaction semantics or format, except for the [new consensus branch id](https://github.com/zcash/zcash/issues/3655#issuecomment-435373714) which alters signature values (which in implementations is hopefully a single easily update-able and testable parameter).

So, without saying anything about a permanent *policy*, let's support old and new transaction format versions after Blossom activates up until the next network upgrade. That's tracked in [https://github.com/zcash/zcash/issues/3739](#3739).

As for the policy *if* we instituted it, this would push back all "deprecation"-style changes by at least one release. Additionally, it requires "simultaneously active distinct transaction semantics", the best example being if NU1-Sapling upgrade supported both Sprout-on-PGHR and Sprout-on-Groth proofs. This means more complexity and more attack surface to reason about.

So a middle ground policy might be "Don't disable backwards compatibility generally, but do so if there is a compelling reason to do so." and I think that's [equivalent to Daira's proposal](https://github.com/zcash/zcash/issues/3655#issuecomment-441510484).

**Comment by nathan-at-least** [comment]
In [this earlier comment](https://github.com/zcash/zcash/issues/3655#issuecomment-436224528) @slush0 wrote:

> The fact that _you_ define when _we_ have to be ready (at exact hour) with release of our whole stack is unbearable in long-term and I suggest to think more about how such backward incompatible changes should be rolled out. Thay may have dramatic effect on whole Zcash infrastructure.

I hear this and agree it's a big ask for vendors. As I understand it, this kind of backwards incompatible upgrade may occur in other chains, but only in "emergency" cases.

@slush0, are there other precedents where blockchains that Trezor supports deprecated functionality that has worked better for Trezor? What about urgent/emergency cases?

**Comment by nathan-at-least** [comment]
Another question for @slush0: As I understand the current plan for NU2-Blossom, the consensus branch id will change right at the activation height. This means that even for transactions which maintain the older version 4 format, the signature generation and verification code must account for the new activation.

Does this still meet the request from Trezor to maintain backwards compatibility for some time after the upgrade?

**Comment by prusnak** [comment]
Well, not really. We'd still need to coordinate the firmware update and our web wallet update around your network upgrade. So while these reduces development time (because the only change needed is the change of the constant), it does not reduce maintenance cost at all.

**Comment by str4d** [comment]
> This means that even for transactions which maintain the older version 4 format, the signature generation and verification code must account for the new activation.

To be crystal clear: the signature generation and verification code does not itself need to change (i.e. ZIP 243 will continue to be valid after Blossom activation). The implementations just needs to not hard-code the consensus branch ID, and instead pass it into the signature generation function. If that has not already been done, it is a one-time change to the call-path, that can be trivially tested on mainnet (because it should be a no-op when passing the correct consensus branch ID, and create a transaction that is rejected by the network when passing anything else).

**Comment by prusnak** [comment]
I reworked our firmware stack so it does not hardcode the branch ID but rather takes it from the outside as a parameter from the caller.

**Comment by daira** [comment]
It's worth pointing out, in light of the BCTV14 soundness flaw, that a policy to maintain transaction version compatibility with the previous version would have prevented *covertly* fixing that flaw in Sapling. The people who knew about the flaw could have overridden the policy, but that would have raised significant awkward questions.

As it happens, fixing the soundness flaw would also have violated [my proposed policy](https://github.com/zcash/zcash/issues/3655#issuecomment-441510484) of deciding whether to require a new transaction version no later than 10 months before activation (if the decision then had been not to require a new version, as it very likely would have been). The flaw was found in March 2018, which was only ~7 months before Sapling activation.

**Comment by nathan-at-least** [comment]
@prusnak IIUC, your change simplifies the code release process so that you no longer need to release a code update right around activation. Is that true?

However, is it still true that there is a deployment issue that makes Zcash network upgrades more difficult than alternatives? How onerous is that remaining deployment issue? Also, do you also maintain the caller code that will need to pass this new parameter conditional on block height? Is testing that layer now more complex?

What are some close-ish alternatives for comparison that are roughly Bitcoin-like yet do fairly regular hardfork ugprades?

**Comment by prusnak** [comment]
> your change simplifies the code release process so that you no longer need to release a code update right around activation.

Sort of. We don't need to update the firmware anymore. But every wallet interacting with Trezor needs to change to provide the new branch_id. 

There are not a lot of networks that do a hard-fork every couple of months. So it's hard to compare to anything. Closest comes Monero, but for example the next HF will allow tx of ver 9 and ver 10 coexists at the same time.

**Comment by daira** [comment]
We will do hard forks every 6 months at the most often. Overwinter and Sapling were exceptional (and that was still 4 months).

**Comment by daira** [comment]
I wrote:
> Refining the above proposal, I suggest that the above version compatibility decision should be made no later than the "Specification Pre-Audit Freeze" (see https://docs.google.com/drawings/d/1oUh7vnaulUoUYX9q4wxcO5XqPhbZB6DDD7V57EKPFPE/edit ; not sure whether that is publically visible but I think it is). That is 10 months before activation.

Is there any dissent to this proposal? We need to settle this question for NU4.

@nathan-at-least @acityinohio

**Comment by daira** [comment]
Neither NU3 (Heartwood) nor NU4 require a transaction version increment. For NU3 we had the option to do a block version increment but [decided against it](https://zips.z.cash/zip-0221#header-format-change).

However, this may be an issue again for NU5. If NU5 activation is scheduled to occur in April 2021, then 10 months before that would be June 2020, which is coming up fast. It seems like the original network upgrade timeline is no longer being adhered to, though; it's highly unlikely that we'll be ready for an NU5 specification pre-audit freeze in June.

**Comment by daira** [comment]
NU5 is almost certainly going to require a transaction version increment, based on current plans.

**Comment by daira** [comment]
Shall we close this issue? My position is that we can't decide whether an upgrade that defines a new transaction version will be able to support the previous version until we actually design the upgrade. This has been true for all upgrades up to and including NU5, and I'm pretty sure it will continue to be the case.

**Comment by nuttycom** [comment]
In NU5 we did indeed continue to support v4 transactions, and the removal of v4 support in the future will follow a systematic deprecation process, so I think that we can consider this resolved.
