### ISSUE TITLE
[ZIP 207] Split Founders' Reward

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3673]
From [Announcing Zcash Blossom and proposed feature goals](https://forum.zcashcommunity.com/t/announcing-zcash-blossom-and-proposed-feature-goals/31891):

> # Split Founders' Reward
>
> - **What is it?** Alter the consensus rules so that there are distinct FR addresses for the Zcash Foundation, Zcash Company *Strategic Reserve*, and the remainder.  
> - **Who does this affect?** FR Recipients and Governance/Transparency focused public
> - **Why is this a goal?** This decouples these three funding streams organizationally, legally, and operationally. It further reinforces transparency as to the structure of the Founders' Reward.

**Close Criteria:** Close this ticket when there are well-specified precise requirements for this feature goal.

**Comment by nathan-at-least** [comment]
The feature requirements for this are fairly simple:

At the activation height, transition from the Sprout/Overwinter/Sapling FR consensus rules to new similar rules.

The current, initial rules require a portion of block reward be sent to an *FR Address* which rotates on a regular block interval, which I'll call a *period* in this ticket. The new rules should require portions of the block rewards are assigned to multiple specific *FR Addresses* per period, one for each of:

- the *Zcash Foundation Fund*,
- the *Zcash Company Dev Fund*, and
- the *Reward Fund*.

**TODO:** Define the proportions required to be sent to each address category.

**Comment by daira** [comment]
If we're changing the FR addresses, then I would like to take the opportunity to make them Sapling addresses, and to allow directing mining rewards to Sapling addresses.

**Comment by mms710** [comment]
We did a first pass of RICE scoring without the full engineering team (eg we will need to do another pass) and the score for this item was 21.0.

**Comment by mms710** [comment]
Sorry, it took me a while to get back to this. Some context on the RICE scoring method: the RICE score is supposed to help provide a guideline for rough prioritization of various ideas (in this case, various possible Blossom goals). While it will be used as a guideline, it is not a hard and fast rule that something with a higher RICE score will always be worked on first or have a higher priority. The most useful way RICE scores can impact the Zcash selection process is by providing an indication of which items are "low-hanging fruit". You'll notice that some of the higher scored items have low effort associated with them.

In addition, it's important to know that this is an _initial_ RICE score. After the goal is fully detailed and specified, we will perform the RICE scoring again because we will have gained more information that will make the RICE scores more accurate.

We calculate our RICE scores using the following formula:
(Reach * Impact * Confidence)/Effort.
**Reach:** How many users will this change/feature impact, or how many new users will this gain? Alternately, you can think of this as roughly what % of our user base this change will reach. Give this a 1-10 score, 1 being the least amount of reach and 10 being the most. Generally, items with a 9 or 10 score will gain new users.
**Impact:** How large of an impact will this change/feature have on users? Will it increase their usage of Zcash, or of shielded transactions? Give this a 1-10 score, 1 being the least impact and 10 being the most.
**Confidence**: How confident are you that this change will reach the amount of users you said and impact users as much as you said? Please express this in a % form between 1-100% (typically in increments of 10), 10% meaning not at all confident and 100% being very confident.
**Effort**: How many person months will this work take to complete? This should be an estimate and you can use portions of person months in the calculation. For example, 2 weeks = .5 months.

**RICE Score for this Item:**
Reach: 9 - this will impact all of our users and may help us gain new users
Impact: 10 - we expect this to have a high impact on the users this will effect
Confidence: 70% - we're somewhat confident about our reach and impact numbers
Effort: 3 - we think this will take 3 person months to complete

Calculation: (9* 10 *.7)/3 = **21.0 RICE Score**

**Comment by daira** [comment]
I'm confused about the estimate of 9 for Reach. This change only *directly* affects the Zcash Foundation: roughly speaking, it allows the Foundation to rely on receiving their portion of FR directly rather than relying on ZcashCo passing it on to them. (More precisely it replaces, for that portion of the FR for the year after Blossom activation, the FR keyholders at ZcashCo with the FR keyholders at the Foundation.) It's unclear to me who is proposed to hold the keys to the Reward portion, but if it's either the Company or the Foundation then that part amounts to a no-op in terms of trust and security requirements.

It's true that, to the extent to which users perceive this change as being part of an increase in transparency, that might have political advantages that could indirectly increase adoption. But if I understand correctly, it is not intended to actually change the distribution of FR funds at all, or if it is then that is independent of the consensus change being proposed here. So it's unclear to me how confident we can be in this effect.

**Comment by mms710** [comment]
Clarification on this ticket: This is going to be implemented using t-addresses for now.

To respond to Daira's question about risk above: The way in which this reduces risk is that it reduces the blast radius if either Zcash Company or the Zcash Foundation are compromised.

**Comment by mms710** [comment]
We very much want to do this but we don't believe Zcash Company will have time to do this in Blossom. Instead we will put it on deck for NU3.

**Comment by mms710** [comment]
Due to the removal of the counterfeit detection turnstyle from the Blossom upgrade list and due to the fact that some other Blossom goals (Sprout address retirement, rollback protection and shielded support custodian reinforcement) could probably be partially or fully done without a network upgrade, we can slot this back into the Blossom upgrade.

**Comment by str4d** [comment]
Using t-addrs for this, we need to write up a specification that covers the following points:

- The Founders' Reward consensus rule in `ContextualCheckBlock()` will be gated on Blossom activation.
- Prior to activation, the current logic applies (there must be a single output with value `GetBlockSubsidy(nHeight) / 5` payed to address `GetFoundersRewardScriptAtHeight(nHeight)`).
- From activation:
  - There will be three sets of FR addresses, each containing 12 addresses (creating a roughly-monthly sequence of FR periods between Blossom activation in October 2019 and the block reward halving around October 2020).
    - Constraint: we should pick the height transitions to be nice block height multiples, to simplify the implementation logic for miners and mining pools. Ideally we would also pick the Blossom activation height to be near that multiple, but this isn't a requirement.
      - To-do: pick the height transitions, taking #3672 and #3690 (both reducing block times) into account.
    - To-do: will the existing FR addresses be used for either the Zcash Company strategic reserve or the remainder, or will fresh addresses be used for all three?
    - To-do: specify the sets of FR addresses (this does not need to happen until the specification freeze at the end of February).
  - Each set of FR addresses will have an associated value (specified as exact constants in zatoshis, rather than relying on the division operation, as we don't have to deal with the slow-start).
    - To-do: specify the values (placeholder constants are necessary for the specification pre-audit freeze, while final values can wait until the specification freeze, as their sum can be trivially audited to add up to the intended FR total).
  - The coinbase in each block MUST contain three outputs corresponding to the three sets, that each pay the correct value to the FR address for that height.

**Comment by mms710** [comment]
Zcash Company has decided to move forward with pursuing splitting the founder's reward for Blossom. As a note, there are three more points along the network upgrade timeline below where we may need to abort this goal if we find significant issues with our approach as a result of issues that come up in specification auditing (end of Feb) inability to finish the code in time (end of March) or issues that come up as a result of code auditing or testing (end of May).

![image](https://user-images.githubusercontent.com/25780612/50850865-5f54cc80-1338-11e9-9ad1-0867a145e89d.png)

In addition to this goal, Zcash Company will be pursuing Harmony Mining (https://github.com/zcash/zcash/issues/3672) and Shorter Blocktimes (https://github.com/zcash/zcash/issues/3690) while maintaining transaction version 4 (https://github.com/zcash/zcash/issues/3739).

**Comment by mms710** [comment]
@str4d would we need to make changes to the specification if we wanted to have more than three funding streams? For example, if we wanted to make more granular levels of funding to multiple different addresses for the Company, Foundation and various other projects.

**Comment by str4d** [comment]
@mms710 the only necessary change to the ZIP would be modifying the list of funding streams. The ZIP is specified in such a way that the implemented logic would be agnostic of the funding streams themselves; the only restriction is that the total value of all active funding streams at a given height MUST NOT exceed the block reward (because mathematics). Any restrictions or splits beyond that are social decisions, not technical ones.

**Comment by mms710** [comment]
Got it. @nathan-at-least Do you and Zooko have an idea yet of what the list of funding streams will be if you wanted to split them more granularly within Foundation, Company and remainder?

**Comment by acityinohio** [comment]
From the Foundation perspective all the pledged ZEC can all be sent to a single address (ideally t-addr within our current set-up but could do Sapling in the future)

**Comment by daira** [comment]
This ZIP has been withdrawn for NU3, as per https://forum.zcashcommunity.com/t/ecc-will-cancel-the-split-fr-feature-from-nu2-blossom/33245 . The ZIP has been merged with a Withdrawn status.

**Comment by mms710** [comment]
Closing because the ZIP was withdrawn.
