### ISSUE TITLE
improve test code clarity: one argument to z_getnewaddress is not too many

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#3687]
In `src/test/rpc_wallet_tests.cpp`, at or near line 629:
```
// Check if too many args
BOOST_CHECK_THROW(CallRPC("z_getnewaddress toomanyargs"), runtime_error);
```
This check, while functionally correct, is confusingly worded; this rpc _can_ take one argument, but it must be either `sprout` or `sapling`. (Zero arguments generates an address of the default type; issue #3671 changes the default type from `sprout` to `sapling`.)

Originally, this rpc did take (only) zero arguments; this was changed in https://github.com/zcash/zcash/commit/eec85c4388691da0fa5950217c158bb87bf59cd4.

The suggested change is to add a second argument (that would indeed be too many), and also consider testing that this rpc fails with any argument other than `sprout` or `sapling`.

Please also look for other instances of the same problem in this test file, or all test files.

**Comment by Eirik0** [comment]
@LarryRuane I may have jumped the gun. Is this issue superseded by #3685 ?

**Comment by LarryRuane** [comment]
#3685 is much more general than this one (and I really like it, by the way), but I think this one could be used to make sure `z_getnewaddress` fails if given more than two arguments, or is given a nonsense argument. I think I'd like to leave this as a _good first issue_ for someone just learning the dev process. Or we could close this, I don't feel strongly either way.

**Comment by Eirik0** [comment]
@LarryRuane 
The only thing is that we will have to remember to close this ticket too if we do the other one before this, the two tickets reference each other, so that should not be a problem. I think adding the utility method referenced in the other will make it easier to fix this issue, but that the other issue is very broad and could be done in smaller bite sized chunks (this being one). Regarding closing this/leaving it open, I am happy with whatever you decide. :)
