### ISSUE TITLE
add time-locking-of-mining-rewards for Equihash-200,9 miners

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#3774]
Let's add time-locking-of-mining-rewards (50 rewards, each one paid out once a week, for 50 weeks) for the current Equihash-200,9 PoW, in addition to the plan in NU2 Blossom to introduce new _alg-B_ with that same time-locking-of-rewards attached. If we start talking about this now, and commit to it in time for NU3 Feature Selection (end of May, 2019), then miners currently running Equihash-200,9 will have about a year to prepare for that, so it won't be a nasty financial surprise for them.

This is an NU3 Wishlist Item (but I can't add labels to github items, so could someone else please do that?). Draft-ZIP-Needed

**Comment by zawy12** [comment]
The only reason I saw for time-locking is:

> miners are incentivised to be guardians of the long-term health of the network and value of the coin. This protects all users of the network against 51% attack

It has the opposite effect because it gives a reward to stakers (dedicated miners who will benefit from lower difficulty) but does not use a risk of loss of that stake to increase security. Stakes to align interests is a good starting point, but PoS can be done badly.  This will reduce the number of willing miners while giving a short term boost to price.  As the 1st 50-week periods, most of the price-boost effect will end. By increasing the price and decreasing difficulty, the price-to-difficulty ratio increases which increases the chances of a 51% double-spending attack that does not hardly care about rewards.  

It might increase stability in hashrate and price which is needed because using 2 POWs forces a decision in the difficulty algorithms to respond 1/2 as fast to price changes or have 1-SQRT(2) = 41% more instability from random variation (changing N=17 to N=8 or 9).  

Just changing POW is the safe route.

**Comment by daira** [comment]
The dual PoW does not make a rollback ("51%") attack harder, as demonstrated in https://github.com/zcash/zcash/issues/3672#issuecomment-451640113 .

**Comment by zawy12** [comment]
Yes, I had a thought snafu and was reading your comments there.  I meant to delete that earlier.

**Comment by daira** [comment]
We're never doing this. It was a terrible idea to start with.
