### ISSUE TITLE
RPC Interface Undefined Behavior - Finding B from 2018-12

### ISSUE THREAD

**Issue by zebambam** [zcash/zcash#3792]
Description

Shifting a signed 32-bit integer representing the number 1, to the left by 31 bits is undefined. This is a bug. However It does not appear to impact security.

src/arith_uint256.cpp: base_uint<BITS>::bits()​: Line 177
```
for (int bits = 31; bits > 0; bits--) {
    if (pn[pos] & 1 << bits)
    return 32 * pos + bits + 1;
}
```
``pn[]`` is ``uint32_t``. ``bits`` is an integer (loop variable). ``1 << bits`` is a signed number (i.e. ``1``) shifted by 31 bits, which is undefined behaviour, because ``1 << 31`` = 2​<sup>31</sup>. ​However, a signed 32-bit number can only represent a number in the range -2<sup>31</sup>​ to 2<sup>​31</sup>​ - 1.

Remediation

Suggest the following code:
```
for (​size_t​ bits = 31; bits > 0; bits--) {   
    if (pn[pos] & ​1U​ << bits)
    return 32 * pos + bits + 1;
}
```

**Comment by daira** [comment]
Language-lawyering follows; please skip if you have anything better to do :-p

The language is C++11 or later. Since ``bits`` is ``size_t`` which is unsigned, the ``1`` in ``1 << bits`` is first converted to ``size_t`` via the *[usual arithmetic conversions](https://en.cppreference.com/w/cpp/language/operator_arithmetic)*. The final standard isn't online so I will quote the [N3337 draft](https://stackoverflow.com/questions/30488777/what-does-rank-mean-in-relation-to-type-conversion) [*]:
> — If both operands have the same type, no further conversion is needed.
>
> — Otherwise, if both operands have signed integer types or both have unsigned integer types, the operand with the type of lesser integer conversion rank shall be converted to the type of the operand with greater rank.
>
> — Otherwise, if the operand that has unsigned integer type has rank greater than or equal to the rank of the type of the other operand, the operand with signed integer type shall be converted to the type of the operand with unsigned integer type.
>
> [...]

The first two rules do not apply. The third does, because the "conversion rank" of ``size_t`` is greater than or equal to ``int``, according to [this rule](https://stackoverflow.com/a/30488911/393146):

> — The rank of any unsigned integer type shall equal the rank of the corresponding signed integer type.

The signed integer type corresponding to ``size_t`` is ``ssize_t``, which is no smaller than ``int`` on all reasonable platforms. (I'm pretty sure that's guaranteed by the standard, but if not then it is an oversight, because a lot of things would break if it were not true.) Also,

> — The rank of a signed integer type shall be greater than the rank of any signed integer type with a smaller size.

So, ``ssize_t`` has rank greater than or equal to ``int`` (because ``int`` is not larger than ``ssize_t`` and ranks are totally ordered), and so does ``size_t``.

Therefore the expression ``1 << bits`` is equivalent to ``((size_t) 1) << bits``. The [conversion rule](https://en.cppreference.com/w/cpp/language/implicit_conversion#Integral_conversions) is:

> If the destination type is unsigned, the resulting value is the smallest unsigned value equal to the source value modulo 2<sup>n</sup> where n is the number of bits used to represent the destination type. [...]

We're assuming that ``size_t`` is at least 32 bits. The behaviour is therefore well-defined, and as intended.

I suggest changing it to ``pn[pos] & (1U << bits)`` anyway, just because it's clearer.

[*] Standards bodies: if you want people to actually use your standards, they need to be freely available. Otherwise people will use drafts.

**Comment by str4d** [comment]
This code is [inherited from upstream Bitcoin Core](https://github.com/bitcoin/bitcoin/blob/4d661baf1aca4226d1c4ec89fe7e44c1f93f04da/src/arith_uint256.cpp#L178-L181), and any changes we make should be pushed upstream to them.

**Comment by Eirik0** [comment]
@str4d The code you referenced already has the fix in it: https://github.com/bitcoin/bitcoin/pull/14510
