### ISSUE TITLE
Add an indexable build target to the Protocol specification compilation

### ISSUE THREAD

**Issue by zebambam** [zcash/zcash#3958]
One of the tickets for #3957.

In order to be able to use comments in code to link the relevant code sections that implement a consensus or protocol rule back to the protocol in a way that is usable for auditors, we need some way to be able to link into the protocol specification.

HTML might be a candidate, if we can link into a bookmarked location.

I'd like to be able to provide cross-links back to the code via some view of the protocol specification as well, which seems like the easy part once we can reference from the code to the protocol specification.

**Comment by daira** [comment]
There's already a build target (`html`) for an HTML version of the spec, but unfortunately there's a bug in [pdf2htmlEX](http://coolwanglu.github.io/pdf2htmlEX/) that [causes links into the document to fail to work](https://github.com/zcash/zips/issues/127#issuecomment-333092114) (internal links do work). pdf2htmlEX [hasn't been actively developed since ~2015](https://github.com/coolwanglu/pdf2htmlEX/graphs/contributors); nevertheless, I think the best option is probably to fork it and fix that bug.

Direct LaTeX-to-HTML is not practical: the source LaTeX is too dependent on `pdflatex`isms.

**Comment by daira** [comment]
Apparently https://github.com/pdf2htmlEX/pdf2htmlEX is the new home; I will check whether that version fixes the linking bug.

**Comment by daira** [comment]
[Fixed in 2019.0.2](https://github.com/zcash/zips/commit/a1cb36a19a975de7420d4b3edb98eac035d1868f).

**Comment by zebambam** [comment]
This is great!! Thank you! Taylor and I have been pairing on what different components are needed to provide auditors with a guide to trying to understand where we think controls are implemented, and doing it in a way that is minimally-invasive. An anchoring scheme into the protocol document is absolutely necessary for that, as is one into the code, along with ways to connect the two documents. We've come up with a scheme that we think is workable but we're going to write some proof-of-concepts before bringing it to the rest of the ECC engineers for consideration. Thank you so much for your help so far. I think that Taylor and I can handle the other components until we're ready to try to convince you all that what we've done is useful.
