### ISSUE TITLE
DoS: Filling blocks with useless transactions is straightforward and cheap

### ISSUE THREAD

**Issue by daira** [zcash/zcash#3983]
Currently it is relatively easy to deny service simply by submitting many large transactions. The standard fee of 0.0001 ZEC is not dependent on transaction size, and miners using zcashd's `getblocktemplate` to prioritize transactions will not take size into account for transactions containing JoinSplits or Sapling Spends/Outputs. Note that Sapling Output proofs can be reused for multiple output notes, allowing transactions to be inflated to any desired size at low computational cost. This also increases the effectiveness of the attack for DoS, because legitimate users will have to scan all of those outputs to detect incoming payments. #3229 is a related ticket.

It is unclear whether basing fees on transaction size would be sufficient, but it would help somewhat against non-mining DoS attackers. A mining attacker can already just mine empty (i.e. coinbase-only) blocks.

It is essential that any solution to this problem does not end up charging excessive fees to legitimate users.

**Comment by zebambam** [comment]
I agree on the excessive fees part. I'm glad we decided to add this to the pile. Let's talk about possible generic defenses on Monday. I'm currently thinking that the concerns about a fee market could be put aside since our blocks are nowhere near completely full legitimately yet, so it's less about a "fee market" and more about "pricing DoS attackers out of the market". But let's save the solution enumeration till Monday, see you then.

**Comment by domenkozar** [comment]
Note how we've solved that in Cardano: https://cardanodocs.com/cardano/transaction-fees/

**Comment by zookozcash** [comment]
Thanks for the note, domenkozar!

**Comment by zookozcash** [comment]
In the long run, I think a great solution to this sort of DoS is the "consensus rules set fees" design: https://github.com/zcash/zcash/issues/3473

**Comment by prestwich** [comment]
> In the long run, I think a great solution to this sort of DoS is the "consensus rules set fees" design: #3473

Side markets and rebating can't be prevented. In-protocol rebates can be enforced via sighash anyonecanpay for broad classes of transactions. So real fee-rate is divorced from protocol-established fee rate. Without that connection, adjustable block sizes are likely to become a tool for miner manipulation of real fee rate, rather than a mechanism for meeting demand

That aside, zcash is currently processing about 0.05  tps, and has never averaged more than 0.1 tps. A protocol-set fee rate won't function at all in these conditions. It'll be pegged to minimum value, and fail at preventing a DoS. Lack of demand for backspace strongly implies that a DoS is minimally harmful

**Comment by ravibhojwani** [comment]
The ADA Lovelace was a nice touch .. overall it seems that constants will change as state changes with scaling occurs however the basic sandbox seems lighting fast ..

**Comment by ravibhojwani** [comment]
https://github.com/zcash/zcash/issues/3983#issuecomment-489673872  

Has there been any mining pool viruses or other manipulations that have altered the Development

**Comment by zebambam** [comment]
This ticket is a splitting out of the issues first described in the epic ticket here: https://github.com/zcash/zcash/issues/3983

**Comment by zebambam** [comment]
@daira are we confident enough in the code that was deployed last year to close this?

**Comment by daira** [comment]
Will have a look at this again tomorrow.

**Comment by nuttycom** [comment]
This is associated with (and should be considered fixed by the resolution for) #6344
