### ISSUE TITLE
Block version number triggers incorrect warning that the software is obsolete 

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#3992]
@garethtdavies wrote in community chat:

> I am running the latest commit on testnet and see `"errors": "Warning: This version is obsolete; upgrade required!"` in `zcash-cli getinfo`. `zcash-cli --version`  is `Zcash RPC client version v2.0.5-5347f6e6c`

This issue is currently reproducible on testnet as a miner is producing many blocks with an incorrect version number.  Instead of setting a block version of 4, the miner is setting a block version of 536870912 (0x20000000) which in `UpdateTip()` triggers the following condition:

        if (nUpgraded > 100/2)
        {
            // strMiscWarning is read by GetWarnings(), called by the JSON-RPC code to warn the user:
            strMiscWarning = _("Warning: This version is obsolete; upgrade required!");
            CAlert::Notify(strMiscWarning, true);
            fWarned = true;
        }

This warning message could be changed given that zcashd uses block height constants `RELEASE_HEIGHT` and `DEPRECATION_HEIGHT` to determine if the software has reached end of support (EOS) and should halt (become obsolete).

Note that according to the [Sapling Spec 2019.0.0](https://github.com/zcash/zips/blob/master/protocol/protocol.pdf)

- The current and only defined block version number for Zcash is 4.
- **Consensus rule: The block version number MUST be greater than or equal to 4.**
- The semantics of blocks with block version number not equal to 4 is not currently defined. Miners MUST NOT create such blocks.
- The exclusion of blocks with block version number greater than 4 is not a consensus rule; such blocks may exist in the block chain and MUST be treated identically to version 4 blocks by full validators.

Therefore, blocks with an undefined version number of 536870912 (0x20000000) are treated and parsed as version 4 blocks.

**Comment by daira** [comment]
Because we would only change the block version number as part of a network upgrade, and the timing of network upgrades is set so that all out-of-date nodes will have EOS-halted by the activation, it's entirely redundant and obsolete to have this warning as well. It can only cause false alarms, and therefore we should remove it.

Note that the plan for when we do need to bump the block version, is to make the same change we made for the transaction version in Overwinter; i.e. to replace the sign bit of the version with a flag, and to require exact version matching (as a consensus rule) subsequently. In that case the warning would never activate because the exact version matching would prevent it from doing so.
