### ISSUE TITLE
Why not BLS12-461 with equivalent performance?

### ISSUE THREAD

**Issue by kamel78** [zcash/zcash#4065]
I have Benchmarked your implementation of the BLS12-381, and it is really a great and fast implementation. However, according to recent researches (https://eprint.iacr.org/2017/334.pdf), 381 is not enough secure for 128bit level security. Instead, one have to use at less 460 bit for the base field in order to achieve such security level. I Have implemented  the proposed BLS12-461 curve with Rust (i have modified your proposed code accordingly), and i have reach very efficient performances (3 ms only for full pairing, so less than one millisecond of gap with respect to the BLS12-381 runtime  ), so that we can get guaranteed security level with negligible supplementary run time.

If you project team is interested i can share my code with you so that you can use it instead of the BLS12-381 and get much better security level with equivalents performances. I have implemented several optimization tricks, and revised several code parts (Miller Loop, Exponentiation and Frobenius).

 

Kind Regards

**Comment by rex4539** [comment]
As a general rule, I would say that if you could open an easily reviewable pull request with your changes, it will raise the chances of it being merged.

**Comment by daira** [comment]
Realistically, there's no chance of such a PR being merged. It would require a year of planning and security review to change the curve, and there's nothing wrong with the security of BLS12-381.

**Comment by daira** [comment]
Note in particular that https://eprint.iacr.org/2018/1017.pdf supports the assertion that, as far as is currently known, BLS12-381 meets the 128-bit security level.

(Strictly speaking, the design strength of Sapling is 125.5 bits, limited by square root attacks against ivk.)

**Comment by kamel78** [comment]
Thanks for the note,
Unfortunately, results that are more recent show that BLS-381 is no longer secure for the 128bit security level.  https://eprint.iacr.org/2019/485.pdf  .
I worked with the authors of the paper, and they really show details of the attacks on BLS12-381 and gives corresponding conclusions “381 is no longer sufficient fo 128bit level”, one may move to 461bit.
The advantage of BLS-461 is that hamming weight of the X parameter (in NAF representation) is only 3! Hence, when implemented (and with little optimization techniques), performances are equivalents to those of BLS-361 with and advanced security level (use of Karabina Squaring,    Miller with NAF, optimized Frobenius…….). In the following, obtained benchmarking results when I implemented BLS-461 using Rust (adapting and optimizing your code for BLS-361):

test bls12_461::bench_pairing_final_exponentiation ... bench:   **1,649,969 ns/iter (+/- 66,215)**
test bls12_461::bench_pairing_full                 ... bench:   **3,241,015 ns/iter (+/- 110,393)**
test bls12_461::bench_pairing_g1_preparation       ... bench:      19,321 ns/iter (+/- 1,251)
test bls12_461::bench_pairing_g2_preparation       ... bench:     410,145 ns/iter (+/- 18,456)
test bls12_461::bench_pairing_miller_loop          ... bench:   1,146,517 ns/iter (+/- 32,982)
test bls12_461::ec::g1::bench_g1_add_assign        ... bench:       2,171 ns/iter (+/- 70)
test bls12_461::ec::g1::bench_g1_add_assign_mixed  ... bench:       1,594 ns/iter (+/- 73)
test bls12_461::ec::g1::bench_g1_mul_assign        ... bench:     675,999 ns/iter (+/- 75,783)
test bls12_461::ec::g2::bench_g2_add_assign        ... bench:       6,958 ns/iter (+/- 414)
test bls12_461::ec::g2::bench_g2_add_assign_mixed  ... bench:       5,091 ns/iter (+/- 255)
test bls12_461::ec::g2::bench_g2_mul_assign        ... bench:   2,077,617 ns/iter (+/- 224,381)
test bls12_461::fq12::bench_fq12_add_assign        ... bench:         222 ns/iter (+/- 19)
test bls12_461::fq12::bench_fq12_inverse           ... bench:      37,014 ns/iter (+/- 1,758)
test bls12_461::fq12::bench_fq12_mul_assign        ... bench:      10,554 ns/iter (+/- 535)
test bls12_461::fq12::bench_fq12_squaring          ... bench:       7,285 ns/iter (+/- 377)
test bls12_461::fq12::bench_fq12_sub_assign        ... bench:         190 ns/iter (+/- 11)
test bls12_461::fq2::bench_fq2_add_assign          ... bench:          31 ns/iter (+/- 1)
test bls12_461::fq2::bench_fq2_inverse             ... bench:      19,551 ns/iter (+/- 572)
test bls12_461::fq2::bench_fq2_mul_assign          ... bench:         472 ns/iter (+/- 22)
test bls12_461::fq2::bench_fq2_sqrt                ... bench:     383,429 ns/iter (+/- 104,592)
test bls12_461::fq2::bench_fq2_squaring            ... bench:         355 ns/iter (+/- 28)
test bls12_461::fq2::bench_fq2_sub_assign          ... bench:          28 ns/iter (+/- 4)
test bls12_461::fq::bench_fq_add_assign            ... bench:          15 ns/iter (+/- 0)
test bls12_461::fq::bench_fq_from_repr             ... bench:         144 ns/iter (+/- 6)
test bls12_461::fq::bench_fq_into_repr             ... bench:          68 ns/iter (+/- 2)
test bls12_461::fq::bench_fq_inverse               ... bench:      18,903 ns/iter (+/- 1,013)
test bls12_461::fq::bench_fq_mul_assign            ... bench:         130 ns/iter (+/- 14)
test bls12_461::fq::bench_fq_negate                ... bench:          14 ns/iter (+/- 1)
test bls12_461::fq::bench_fq_repr_add_nocarry      ... bench:          12 ns/iter (+/- 0)
test bls12_461::fq::bench_fq_repr_div2             ... bench:           7 ns/iter (+/- 0)
test bls12_461::fq::bench_fq_repr_mul2             ... bench:          12 ns/iter (+/- 0)
test bls12_461::fq::bench_fq_repr_num_bits         ... bench:           4 ns/iter (+/- 0)
test bls12_461::fq::bench_fq_repr_sub_noborrow     ... bench:          12 ns/iter (+/- 0)
test bls12_461::fq::bench_fq_sqrt                  ... bench:      75,184 ns/iter (+/- 2,594)
test bls12_461::fq::bench_fq_square                ... bench:         107 ns/iter (+/- 6)
test bls12_461::fq::bench_fq_sub_assign            ... bench:          15 ns/iter (+/- 0)

I have only to implement fixes for Side-Channel attacks (having negligible runtime coast).

Regards

**Comment by daira** [comment]
That paper is very clear about the ways in which its analysis is conservative (section 3.4):

> We keep the model of security of Barbulescu and Duquesne [[BD18](https://eprint.iacr.org/2017/334)] which is conservative in that it assumes perfect conditions for an attacker (sieving in TNFS for which no computation record is available, perfect matrix reduction in the filtering step, no memory limitation, ECM having the same performances for slightly larger smoothness bounds).

**Comment by yelhousni** [comment]
The is also this recent paper [[FM19](https://eprint.iacr.org/2019/555.pdf)] that suggests new recommendations for elliptic curves which target "conservatively" 128-bit security level. The recommendations are based on Brezing-Weng family. I have implemented [here](https://github.com/EYBlockchain/zk-swap-libff/tree/djo/libff/algebra/curves/bw12_446), based on *libff*, the curve `BW12-446` which refers to Family 17 choice (b) in the paper. It should have performances not too far from `BLS12-381` and it is highly 2-adic (the subgroup polynomial is the same as `BN`).

**Comment by yelhousni** [comment]
This new [[Guillevic19]](https://hal.inria.fr/hal-02396352/document) paper revises all the recent security estimations with respect to the *Special* TNFS attack on pairing-friendly elliptic curves due to Barbulescu, El Mrabet et Ghammam [[DEG19]](https://eprint.iacr.org/2019/485), Fotiadis and Konstantinou [[FK18]](https://eprint.iacr.org/2018/1017) and Fotiadis and Martindale [[FM19]](https://eprint.iacr.org/2019/555). It concludes that for 128-bit security with the fastest pairing one should consider BLS12 over 440 to 448 bits or or a Fotiadis–Martindale curve of embedding degree 12, discriminant 3 and twist of degree 6 over a 446-bit prime. This latter curve is what I refer to in my previous comment as `BW12-446` (implemented [here](https://github.com/EYBlockchain/zk-swap-libff/tree/ey/libff/algebra/curves/bw12_446))

**Comment by ebfull** [comment]
BLS12-381 was designed for Zcash in mind. We have specific needs and preferences so we picked a point on the space of security-performance trade-offs that worked for us; it just turns out that this balance is acceptable to many other projects as well. We wanted to be more conservative than BN254 (which we had previously been using) but we recognized that these newer attacks were not really practical, so we didn't aspire to be _at least_ 128-bit secure against _every_ attack. We just wanted to be close without going overboard.

Pairing performance was not really a huge concern for us. The biggest concerns were multiexp performance and scalar field size. For example, scalar fields larger than 2^255 are irritating from a design perspective and have impacts on usability, since we use the embedded curve for keying material (Jubjub). Switching to a 461-bit BLS12 curve would net us an almost meaningless improvement in security (I think from roughly 117-120 bits to 128?) at the cost of unnecessarily large scalars and slower multiexp. And slower pairings. (All under the assumption that an attack is possible which is [not known to be feasible yet.](https://github.com/zcash/zcash/issues/4065#issuecomment-509441461))

In general there seems to be diminishing returns as we approach 128-bits of security... KSS16 curves might be the only candidates that can lead to meaningful security improvements without burdensome performance/usability impacts on our protocol, but I haven't looked into it.

**Comment by yelhousni** [comment]
KSS16 have also a nice property when it comes to computing products of pairings (which is the case for proof verification). As suggested in [[Ghammam16]](https://eprint.iacr.org/2016/472.pdf) (Table 7), computing `n>=3` Ate pairings is cheaper on KSS16 compared to BLS12 for 192-bit security. I think this is mainly because the big final exponentiation is factored and the Miller loop is smaller (the smallest ?). I need to check however how this translates for 128-bit.

**Comment by daira** [comment]
I think previous work comparing KSS16 and BLS12 has not fully taken into account that the comparable field sizes for conservative 128-bit security are 330 bits and 446 bits respectively. (Much of this work predates Kim–Barbulescu.)

**Comment by kamel78** [comment]
BLS16 Are slow, there is no sextic twiste for the patirings, only quartic. So the final exponentiation can't be optimized.
    Le jeudi 9 janvier 2020 à 13:57:07 UTC+1, Daira Hopwood <notifications@github.com> a écrit :  
 
 
I think previous work comparing KSS16 and BLS12 has not fully taken into account that the comparable field sizes for conservative 128-bit security are 330 bits and 446 bits respectively. (Much of this work predates Kim–Barbulescu.)

**Comment by daira** [comment]
I'm aware that there is only a quartic twist, but that doesn't imply that KSS16 is excessively slow compared to BLS12. The comparison in [Guillevic, Masson, and Thomé 2019, Table 10](https://eprint.iacr.org/2019/431) already took into account that the curve arithmetic for the Miller loop is done over F<sub>p</sub><sup>4</sup>. Although the overall number of multiplications is larger, the wall clock time estimate is quite comparable:

![image](https://user-images.githubusercontent.com/643204/72086493-ed261780-32fe-11ea-8d6c-b57e507b1900.png)

Bear in mind here that much less effort has been put into optimizing KSS16 relative to BLS12 and BN so far, so all we can say is that it's in the range where further effort might be fruitful.

**Comment by jon-chuang** [comment]
According to https://eprint.iacr.org/2019/485.pdf, BLS24-319 has similar optimal ate pairing complexity to BLS12-461, which has been argued to be of similar performance to the <400 bit BLS12 curves.  5 instead of 6 64-bit words, and 10 instead of 12 32-bit words, we get a theoretical (6/5)^2 ~ 1.44 times speed up for G1 computations.

I am not sure how to do the analysis if scalar multiplication optimisations like GLV/GLS applies (and not sure where they apply).

![image](https://user-images.githubusercontent.com/9093549/77838232-8fd68f80-71a4-11ea-9044-a6eb4903f2bc.png)

**Comment by daira** [comment]
Oh that's interesting, I'd forgotten that BLS24 has ρ ≈ 1.25.

Bear in mind that [Cheon attacks](https://ethresear.ch/t/cheons-attack-and-its-effect-on-the-security-of-big-trusted-setups/6692) also need to be considered: for a curve with ~256-bit r and powers of tau up to τ<sup>~2<sup>29</sup></sup> (like the Sapling setup), we would get (256 - 29)/2 ≃ 113.5-bit security. I think we would want to use something like BLS24-352 to compensate for that, for a security of (352/1.25 - 29)/2 ≃ 126.3 bits. In that case F<sub>q</sub> would need to occupy 11 32-bit words, so you would lose a factor of 1.21 in speed relative to BLS24-319 for a 32-bit-limb implementation.

GLV, and other endomorphism-based optimizations (like the ones described in the Halo paper), definitely apply to prime-order CM curves with |D| = 3. I can't remember whether they also apply to non-prime-order curves with |D| = 3.

**Comment by daira** [comment]
It's also worth pointing out that the final exponentiation is only done once per batch for batched Groth16 verification (or once per proof for unbatched). Therefore the more expensive BLS24 final exponentiation is not necessarily an impediment relative to BLS12; it's the cost of the Miller loop (table 21 of https://eprint.iacr.org/2019/485.pdf) that is most important. (Actually the cost of a multi-Miller loop, but the paper doesn't have those figures.)

![image](https://user-images.githubusercontent.com/643204/77929869-11601780-72a2-11ea-93a6-ce9aeaf737e5.png)

**Comment by jon-chuang** [comment]
Considering Cheon's attack, then, one should pit BLS24-351 against a curve like BLS12-446.

Is the idea to update the trusted setup just in the nick of time an acceptable idea? Since old proofs are commited to a chain, are there still any retrograde attacks? To verify, then, one should only accept proofs made under a certain tau before a certain block id, when tau is changed, it seems. Consensus seems to be enough to ensure this will work.

There should be a study of pairing curves used in trusted setups at the 128-bit level security under Cheon's attack, using a conservative circuit size of up to 2^30. I would be interested in writing scripts to do such a search - partly out of academic interest.
****
What you say about batching seems to suggest the following approach:
- If aiming for scalability and value privacy, where end-user provers send proofs to a full node for aggregation, using a curve like BLS27 may yet prove to be a good idea. In terms of arithmetic complexity, its miller's loop has the lowest complexity, so if one amortises its final exponent cost across 100 inner-curve proofs, one gets both small G1 (~330 taking into consideration Cheon's attack) and smaller outer-curve circuit sizes = more inner proofs/outer proof. I am not sure if this batching technique can be applied to PLONK, which is of interest to me. I would like a reference on this batching.
- If aiming for functional privacy a la Zexe, something else might apply.

**Comment by daira** [comment]
It's very unlikely that we will switch to a different pairing-based curve. Our focus now is on Halo, which doesn't require pairings.

**Comment by daira** [comment]
It's also worth pointing out that BLS12-381 is estimated (using [code](https://gitlab.inria.fr/tnfs-alpha/alpha) by Guillevic and Singh, consistent with [[GS2021]](https://eprint.iacr.org/2019/885)) to have an STNFS security level of 126 bits. So there is no motivation to switch away from BLS12-381 on grounds of security against STNFS attacks (as opposed to other security motivations like preferring untrusted setup and no pairings).

The security against Cheon attacks of the Sapling setup is 2<sup>124.6</sup> scalar field operations, estimated [here](https://ethresear.ch/t/cheons-attack-and-its-effect-on-the-security-of-big-trusted-setups/6692/16).
