### ISSUE TITLE
About extending Zcash implementation

### ISSUE THREAD

**Issue by yytasbag** [zcash/zcash#4070]
Hello.
I have recently opened up a thread on the zcash community forums which was the following.

> As a project I want to extend both the Zcash protocol and implementation such that a new type of unshielded transaction is added which uses a different signature algorithm. Protocol design is complete but when it comes to the implementation I have problems finding out which parts should I change. I want to change both mining part to allow miners to accept this new kind of transaction and the client part so that users can make such transactions. Could you help me by pointing out the functions/classes to be modified in a general or a specific way?

My first approach was to add a new bitcoin script opcode so that the new signature scheme can be invoked on demand. note that I would like to preserve the current signature scheme as well and the new scheme that I want to add is used for public transactions. But EvalScript used a class called TransactionSignatureChecker / CachingTransactionSignatureChecker which used CPubKey. Creating a new class that extends CPubKey appears to be the logical approach for me but from what I understand the signature size and key size are restricted. Also the signature scheme that I want to add is not standardized since it does not have a "serialized OpenSSL private key data" structure which is used in "key.h".  Is my understanding of the code is correct? Since I would like to implement the signature scheme without breaking anything how should I approach?

Thanks.

**Comment by daira** [comment]
I suggested in the AMA to look at src/pubkey.cpp, which is where the main code calls into libsecp256k1. Also, I just found out that [Bitcoin Cash/ABC has added Schnorr signatures](https://blog.bitcoin.com/coming-soon-to-bitcoin-cash-schnorr-signatures/). It's not easy to find things in the Bitcoin ABC repo because they don't use GitHub PRs, but here's one relevant commit, for example: https://github.com/Bitcoin-ABC/bitcoin-abc/commit/a8fdf6bf4c9e48fed1689db2c758d5488144d3d9

**Comment by Eirik0** [comment]
Please reopen this ticket if you have further questions on this subject.
