### ISSUE TITLE
Change Addresses are reused

### ISSUE THREAD

**Issue by adityapk00** [zcash/zcash#4077]
When using taddrs, change addresses get unexpectedly reused in various scenarios, including:
 - A used change address is returned when calling `getnewaddress`
 - Sending 2 separate t-addr Txns results in the same change address getting used for both transactions
 - Sending ZEC from a change address causes the change from the new Tx to go back to the same taddr

### Reproduce:
1. Create a new address with `getnewaddress` and fund it
2. Send a Txn from the new address using `z_sendmany` to a sapling address (Make sure the Txn generates some change
3. After the Txn is confirmed, call `getnewaddress`, which will return the change address from the previous Txn

### Expected behaviour
`getnewaddress` should return a new, unused address

### Actual behaviour + errors
`getnewaddress` returns an existing, used address that was the change address in the previous transaction

### The version of Zcash you were using:
2.0.6, but affects all zcashd versions

### Root cause
The main problem is [`AsyncRPCOperation_sendmany::add_taddr_change_output_to_tx` ](https://github.com/zcash/zcash/blob/master/src/wallet/asyncrpcoperation_sendmany.cpp#L1296) doesn't remove the change address from the keypool, making it eligible to be returned from the next `getnewaddress` call.

### Fix
[`AsyncRPCOperation_sendmany::add_taddr_change_output_to_tx` ](https://github.com/zcash/zcash/blob/master/src/wallet/asyncrpcoperation_sendmany.cpp#L1303) needs to call `GetKeyFromPool` instead of `GetReservedKey`

Fix in PR: https://github.com/zcash/zcash/pull/4078

**Comment by str4d** [comment]
We had already planned to address this in #4035 by having `z_sendmany` call `CommitTransaction` instead of `sendrawtransaction`. I think I prefer that way to what is proposed in #4078 because it matches the existing workflow inherited from Bitcoin Core for transparent addresses:

https://github.com/zcash/zcash/blob/0ba07d5842dcafedb35097accb7204e7a0bee8f0/src/wallet/rpcwallet.cpp#L394-L408

In the code snippet above, the `CReserveKey` is allocated, used in `CreateTransaction`, and then `CommitTransaction` calls `KeepKey`.

If `GetKeyFromPool` is necessary to prevent the outlined problem, then all RPC methods inherited from Bitcoin Core that send funds via `SendMoney` suffer from the same issue. It would be great to confirm this!

**Comment by defuse** [comment]
`SendMoney` looks fine to me. `CReserveKey::GetReservedKey` will call `CWallet::ReserveKeyFromKeyPool` to reserve a key and then `CReserveKey::KeepKey` calls `CWallet::KeepKey` to remove the key from the pool. `GetKeyFromPool` does the same thing, calling `CWallet::ReserveKeyFromKeyPool` and then `CWallet::KeepKey` immediately after.

I think there is a similar problem in `fundrawtransaction` / `FundTransaction`. It uses a `CReserveKey` to get a change address (inside `CreateTransaction`) and returns the transaction to the user without ever calling `KeepKey`. If you grep for `CReserveKey` you might find more occurrences of the same bug.
