### ISSUE TITLE
spentindex.py test fails with `--enable-debug` flag

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#4223]
### Describe the issue
`spentindex.py` test fails with `--enable-debug` flag.

### Can you reliably reproduce the issue?
`Always`
#### If so, please list the steps to reproduce below:
1. `CONFIGURE_FLAGS='--enable-debug' zcutil/build.sh`
2. `./qa/pull-tester/rpc-tests.sh spentindex.py`

### Expected behaviour
Test passes.

### Actual behaviour + errors
Test fails and `zcashd` crashes.

### The version of Zcash you were using:
`Zcash Daemon version v2.1.0-1-f859ae006`

### Machine specs:
- OS name + version: `macOS 10.15.2 (19C32e)`
- CPU: `6-Core Intel Core i7 2,6 GHz`
- RAM: `16 GB`
- Disk size: `498,89 GB`
- Disk Type (HD/SDD): `SSD`
- Linux kernel version (uname -a): `Darwin Kernel Version 19.0.0: Thu Oct 31 00:49:29 PDT 2019; root:xnu-6153.60.56~31/RELEASE_X86_64 x86_64`
- Compiler version (gcc --version): `Apple clang version 11.0.0 (clang-1100.0.33.12)`
- Linker version (ld -v): `@(#)PROGRAM:ld  PROJECT:ld64-520`
- Assembler version (as --version): `clang version 9.0.0 (tags/RELEASE_900/final)`

### Any extra information that might be useful in the debugging process.

[spentindex.log](https://github.com/zcash/zcash/files/3839664/spentindex.log)
[spentindex.zip](https://github.com/zcash/zcash/files/3839665/spentindex.zip)
[zcashd_2019-11-13-025636_MacBook-Pro-2018.log](https://github.com/zcash/zcash/files/3839666/zcashd_2019-11-13-025636_MacBook-Pro-2018.log)

**Comment by rex4539** [comment]
```
Assertion failed: lock cs_main not held in main.cpp:1662; locks held:
Unexpected exception caught during testing: [Errno 61] Connection refused
```

**Comment by LarryRuane** [comment]
Thank you for reporting this bug! I can reproduce this failure on Linux by enabling `DEBUG_LOCKORDER`, but I also had to disable `potential_deadlock_detected()` because otherwise it asserts earlier in the test. The fix is very simple, so I'll create a PR. (But I also want to do a systematic search for other occurrences of this bug.)

**Comment by pacu** [comment]
Hi @rex4539! I'm Pacu, iOS developer of ECC's wallet team. I'm trying to reproduce this issue on my Mac, which happens to be running the same os version as yours, so that me and @LarryRuane can verify any fix we produce works on Mac.  

thing is that I'm not being able and I'm wondering what I'm missing. 

I'm running  `Zcash Daemon version v2.1.0-1` which on tag `253fcaa997d3d5e30c3789c825a82e1ed3e7a3fe (HEAD, tag: v2.1.0-1`

regarding python, it's probably what's out of the box for Mac. `Python 2.7.16`

**Comment by rex4539** [comment]
I'm compiling `zcashd` with `CONFIGURE_FLAGS='--enable-debug' zcutil/build.sh` if that makes any difference.

**Comment by LarryRuane** [comment]
Okay, this is not a macOS-specific problem; it's revealed by `--enable-debug`. Thanks.
