### ISSUE TITLE
[Orchard] EC scalar multiplication using PLONK / Halo 2 custom gates

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4254]
How many PLONK gates per bit does it take to do variable-base scalar multiplication? Using custom Montgomery/short Weierstrass addition gates together with the technique in #3924, we expect it to be at most 3 gates/bit (compared to 6 R1CS constraints/bit), but the details need to be worked out.

As I wrote in https://github.com/zcash/zcash/issues/3924#issuecomment-530072208 :
> ``multiply_fast`` in https://github.com/ebfull/halo/blob/master/src/gadgets/ecc.rs implements this algorithm for short Weierstrass curves (in Sonic/Halo-style constraints, not bellman/R1CS).

This was fairly straightforward and gave a 6 multiplication gates/bit implementation in Halo's circuit model (which is roughly similar to PLONK's if you squint at it right); the question is how much of an improvement the custom gates give us.

**Comment by daira** [comment]
It would also be nice to simultaneously boolean-constrain the scalar bit.

**Comment by daira** [comment]
Another interesting question is whether you can get down to ~2 gates per bit for multiplication by a random challenge scalar, using the automorphism optimization from Halo (on suitable curves).

**Comment by daira** [comment]
The best description so far of custom gates is this talk, starting at 22:00 :– https://youtube.com/watch?v=ty-LZf0YCK0&t=22m

**Comment by daira** [comment]
As a reminder, the per-bit logic for computing

    Q := r ? T : −T
    R := P + Q
    S := R + P

in #3924 is:

    let x<sub>Q</sub> = x<sub>T</sub>
    (y<sub>T</sub>) × (2·r - 1) = (y<sub>Q</sub>)
    (x<sub>Q</sub> - x<sub>P</sub>) × (λ<sub>1</sub>) = (y<sub>Q</sub> - y<sub>P</sub>)
    (B·λ<sub>1</sub>) × (λ<sub>1</sub>) = (A + x<sub>P</sub> + x<sub>Q</sub> + x<sub>R</sub>)
    (x<sub>P</sub> - x<sub>R</sub>) × (λ<sub>1</sub> + λ<sub>2</sub>) = (2·y<sub>P</sub>)
    (B·λ<sub>2</sub>) × (λ<sub>2</sub>) = (A + x<sub>R</sub> + x<sub>P</sub> + x<sub>S</sub>)
    (x<sub>P</sub> - x<sub>S</sub>) × (λ<sub>2</sub>) = (y<sub>S</sub> + y<sub>P</sub>)

where r is assumed to be boolean-constrained.

We arrange the variables of the scalar multiplication in 3×3 groups as follows:

| Row | A | B | C | Gate |
|:------:|:--:|:--:|:--:|:-------:|
| ⁝       | ⁝ | ⁝ | ⁝ | ⁝ |
| i       | x<sub>T</sub> | b | y<sub>T</sub> | ECC1 & BoolB |
| i+1   | x<sub>P</sub> | λ<sub>1</sub> | y<sub>P</sub> | ECC2 |
| i+2   | x<sub>S</sub> | x<sub>T</sub> | y<sub>S</sub> | — |
| i+3   | x<sub>T</sub> | b' | y<sub>T</sub> | ECC1 & BoolB |
| i+4   | x<sub>S</sub> | λ'<sub>1</sub> | y<sub>S</sub> | ECC2 |
| i+5   | x'<sub>S</sub> | x<sub>T</sub> | y'<sub>S</sub> | — |
| ⁝       | ⁝ | ⁝ | ⁝ | ⁝ |

BoolB: b<sup>2</sup> = b
ECC1: (x<sub>T</sub> - x<sub>P</sub>) × λ<sub>1</sub> = (y<sub>T</sub> × (2·b - 1)) - y<sub>P</sub>
ECC2: let x<sub>R</sub> = B·λ<sub>1</sub><sup>2</sup> - A - x<sub>P</sub> - x<sub>T</sub>
             and t = x<sub>P</sub> - x<sub>R</sub>
             and u = 2·y<sub>P</sub> - t × λ<sub>1</sub>          // λ<sub>2</sub> = u/t
             and B·u<sup>2</sup> = t<sup>2</sup> × (A + x<sub>R</sub> + x<sub>P</sub> + x<sub>S</sub>)
             and (x<sub>P</sub> - x<sub>S</sub>) × u = t × (y<sub>S</sub> + y<sub>P</sub>)

Notice that each gate only accesses variables in its row and the next row, as required. The point with affine coordinates (x<sub>S</sub>, y<sub>S</sub>) becomes (x<sub>P</sub>, y<sub>P</sub>) for the next scalar bit.

Thus we can implement one round of the scalar multiplication in 3 gates, including boolean-constraining the scalar bit.

**Comment by daira** [comment]
This does not include unpacking the scalar to bits if it is given as an integer. That would take 1 gate per 2 bits for the unpacking, i.e. 3.5 gates/bit in total.

**Comment by daira** [comment]
BTW there is a limit on the complexity of a custom gate needed to avoid an increase in the degree of t(x). The above implementation exceeds that limit; at the risk of oversimplification, B·u<sup>2</sup> is of degree 6 in λ<sub>1</sub>, and all terms used in custom gate checks should be kept at total degree 4 or less in any variable. I'll try to fix it when I get time (probably after Christmas, unless I end up retreating into math over Christmas to avoid social stress :-p ).

**Comment by daira** [comment]
PLONK actually turns out to be much more flexible than I thought when I wrote the above comments:
* you can use 4 (or n, but 4 seems to work out nicely) wires per row;
* you can access an arbitrary number of nearby rows reasonably cheaply;
* there's no hard limit on the degree of t(x), and it can work out well to increase the degree relative to PLONK as described in the paper, as long as it allows reducing the cost in number of gates by enough to compensate.

**Comment by imeckler** [comment]
@daira I also think it should be possible (haven't thought it through fully) without too much trouble to have custom gates of various arities, so that you don't have to pay for the maximal arity on the witness commitment for all gates 

I think you will still have to pay for the maximal arity on the quotient polynomial, unless you split those up as well which increases the proof size but probably helps proving time a lot.

**Comment by vanishreerao** [comment]
@daira A few clarifications about your design, please:
1. Since we are having a gate access two rows, we need to have openings of the wire polynomials a(X), b(X), c(X) at zw also, right? (Using notations in the PLONK paper - z is a pseudorandom element and w is the n-th root of unity in F.)

2. Is the reason your design uses two rows for a gate is PLONK already has an opening at zw and you can fold proofs of these further openings with the existing one's proof?

**Comment by vanishreerao** [comment]
If the above understanding is correct, then to further concretize the implementation details of custom gates for Poseidon - https://drive.google.com/file/d/1bZZvKMQHaZGA4L9eZhupQLyGINkkFG_b/view, I am thinking the following: 
Have the wire polynomials [a(X), B(X), C(X)] subsume [f_1(Y), W(Y), C(Y)] (where the latter C is as in the linked doc), then subsume [f_2(Y), W(Y), C(Y)],..., [f_{w-1}(Y), W(Y), C(Y)], and finally [f_{w}(Y), *, *], (checking f_{w} doesn't need W or C). This should be ok since here also we need openings for just f_i(z) and f_i(zw). 

Please correct me if I'm wrong anywhere, still trying to wrap my head around all the details :)

**Comment by daira** [comment]
The designs for fixed-base and variable-base scalar multiplication used in the Orchard circuit are described in the Orchard book (the three sections under https://zcash.github.io/orchard/design/circuit/gadgets/ecc.html ). We handle one bit per row for variable-base and 3 bits per row for fixed-base, in a 10-advice-column circuit.
