### ISSUE TITLE
Use empirical data to decide how many inputs and output buckets a Pour should have

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#426]
Currently, a pour has two bucket inputs and two bucket outputs. Before marching ahead with that decision, we should evaluate it empirically. There's a really great way to do that: Look at the current Bitcoin, Litecoin, etc. blockchains and "simulate" what would have had to happen if they were all pours and buckets. We might find out that `90%` of transactions have 3 inputs, and so it would be much more efficient to make a pour have 3 inputs and 2 outputs, or something like that.

**Comment by daira** [comment]
I closed #237 as a duplicate. Its description was:
> The newest versions of libzerocash+libsnark support Pour transactions with arbitrary numbers of inputs and outputs (but fixed as part of the circuit, and the same for all Pours).

Increasing the number of inputs is probably not desirable because the circuit size --and therefore proving time-- scales linearly with the number of inputs (since it's necessary to prove that each input is in the coin commitment tree). However increasing the number of outputs may be useful because this only has a small effect on the circuit size -- it is linear but with a much smaller constant factor.

**Comment by daira** [comment]
The number of hashes in the circuit, with Faerie Gold fix, is:
* Nold*d<sub>tree</sub> commitment tree hashes, to prove that the old coins were committed to
* Nold*3 hashes to prove that the old coin commitments are validly constructed
* Nold*3 hashes to prove non malleability, knowledge of the old coin spend authority secrets, binding between public and private spend authority keys, and valid serial number construction
* Nnew*4 hashes to prove that the new coin commitments are validly constructed.

Let C1 be the cost of a commitment tree hash and let C2 be the cost of the other hashes.
Then the total cost of hashing in the circuit is Nold*(C1*d<sub>tree</sub> + C2*6) + Nnew*C2*4.

With #704, this becomes Nold*(C1*d<sub>tree</sub> + C2*5) + Nnew*C2*3.

With #647 and #704, this becomes C1*d<sub>tree</sub> + C2*7 + Nnew*C2*3 (assuming that we only need two hashes to prove the input and output vpub commitments, which I think is the case).

d<sub>tree</sub> is ceiling(log<sub>A</sub>(limit on total number of Pours * Nnew), where A is the arity of the coin commitment tree.

**Comment by daira** [comment]
I decided to use the table in https://docs.google.com/spreadsheets/d/1GCZEHqpf3PPDfqujNXgD46RpckJO3_hOczsNB-gTnGc/edit#gid=0 to calculate relative costs for a subset-sum hash function.

First a sanity check:
* 3524620/128 ~= 27536 (number of constraints per SHA-256 hash based on commitment tree depth of 64)
* 493611/18 ~= 27423 (number of constraints per SHA-256 hash based on 18 extra hashes in the original paper's circuit)

which approximately match the extended paper's statement of 27904 constraints for each SHA-256 hash in Figure 4.

Now, 246080/3524620 ~= 0.0698, i.e. a sumset-sum hash of dimension 5 costs in terms of constraints about 7% of a SHA-256 hash: C1 = C2*0.0698.

**Comment by ebfull** [comment]
We've decided to stick with 2 input coins and 2 output coins in 1.0.

**Comment by nathan-at-least** [comment]
Note: I've just moved this into the Payment API milestone because exchanges may often rely on the ``sendmany`` call.

If:

a. we can get solid empirical evidence from one or more high-volume exchanges about their output-arity distribution,
b. and we believe adjusting the output-arity to capture a good chunk of that curve is simple to implement and does not have a high performance cost,

then:

We *might* put this into 1.0. This depends on step a and @nathan-at-least will be in charge of getting that data. (Until we have that data, let's continue to assume no change in output-arity.)

**Comment by nathan-at-least** [comment]
I moved this ticket into the Payment API milestone, then I realized it's too broad, so I removed it from that milestone (thus out of the 1.0 schedule) and instead placed a more focused #900 ticket into that milestone.

**Comment by daira** [comment]
In Sapling we are likely to have separate input and output circuits (handling one input or one output), which I think makes this ticket obsolete.
