### ISSUE TITLE
implement two-stage pour proofs.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#43]
<a href="https://github.com/nathan-at-least"><img src="https://avatars.githubusercontent.com/u/4369700?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nathan-at-least](https://github.com/nathan-at-least)**
_Tuesday Dec 02, 2014 at 18:17 GMT_
_Originally opened as https://github.com/Electric-Coin-Company/libzerocash/issues/6_

---

The prove time is large enough that users may perceive this as a drawback compared to competing cryptocurrencies.  It may be possible to split the proof into two stages, where the early stage can be computed immediately upon receipt before the subsequent send details are known.

_If_ this is possible _and_ the early stage is a large enough fraction of the total proof time, _then_ it would be a major usability improvement to compute the first stage immediately upon receipt.  This early stage would overlap with block confirmation time, which users already understand and expect.  Additionally, this would mean the delay to spend would be perceptually close to other bitcoin-likes.

**Comment by daira** [comment]
There's a way to do this in conjunction with #2171:

Separate the note commitment Merkle tree into a "large" tree and a "small" tree. The small tree is used cyclically; when each half of it has been used, that branch is transplanted to the large tree (this would happen moderately often, say every few hours). So it is always the case that a given commitment can be found in either the small tree or the large tree. All nodes keep track of the current large and small trees. We aim to make it indistinguishable which tree a given JoinSplit is using. Note that the large tree root only changes when a branch is transplanted.

Also split the Merkle tree proof into stages as per #2171, such that the path height proven by one of the stages is the height of the small tree d<sub>small</sub>, and the other stage(s) make up the remaining height of the large tree, i.e. they prove a path of height d<sub>large</sub> - d<sub>small</sub>.

Each proof is tied to a "proof-linking commitment". Some commitments in the large tree will be old enough that the leafmost subtree of height d<sub>large</sub> - d<sub>small</sub> containing them is stable, i.e. its internal root will not be affected by further additions to the large tree. In that case, the proof for that subtree can be cached indefinitely (together with the opening of its proof-linking commitment). Note that these cached proofs are not dependent on the current overall root of the large tree.

In other cases, a commitment will be new enough that it is contained in the small tree. In that case it is sufficient to use a proof that it is in the small tree combined with unique *dummy* proof(s) (which can be used for any commitment), for the other stage(s).

The input stage of the proof (per #2171) controls which other proofs are needed. To link itself to a particular proof, it proves knowledge of the opening of the corresponding proof-linking commitment. So, to perform a JoinSplit, we always need the input stage and the small-tree stage (these are dependent on the current small-tree root which changes frequently), but we can often use a cached or dummy proof for the other stage(s).

**Comment by daira** [comment]
Suppose for example that the small tree has height 15, and the large tree has height 29. Every 2<sup>14</sup> commitments, we transplant that many commitments &ndash;half of the small tree&ndash; into the next subtree of the large tree, and update the large tree's root.

One Merkle tree proof stage either covers the leafmost 14 layers of a path in the large tree, or is a dummy. Since leafmost subtrees of size 2<sup>14</sub> in the large tree have a stable root, these proofs are also stable, and can be cached indefinitely with the witness for each commitment in the large tree.

The other Merkle tree proof stage covers either the rootmost 15 layers of a path in the large tree, or the whole path in the small tree. It is given both tree roots as public input, but the choice of which tree to use is a private input. In the case where it is proving a path in the small tree, it is paired with a dummy proof for the other stage.

Since each shielded transaction uses two commitments as a lower bound, and taking the current rate of shielded transactions according to explorer.zcha.in, it would take at least 10 days between each update of the large tree. If clients use the *next*-to-last large tree root in their anchors, then this anchor will be stable across reorgs, and they are still guaranteed that a given commitment can either be referenced by that anchor, or is still in the small tree. (This is the motivation for only transplanting half of the small tree at once.) They also have plenty of time to build up a buffer of dummy proofs with the right large-tree anchor, since it is known in advance of being needed.

If the note commitment usage rate were 1000 times higher, the large tree anchor would still only change every ~14 minutes, which is a little short but still workable. (There is no correctness problem no matter how high the commitment usage rate; it's just that dummy proofs are not valid for very long in that case.)

**Comment by daira** [comment]
Credit to [Sander and Ta–Shma 1999](http://www.cs.tau.ac.il/~amnon/Papers/ST.crypto99.pdf) for the inspiration to use multiple roots (section 3.2 of that paper, although the details are somewhat different).

**Comment by daira** [comment]
I wrote:
> The input stage of the JoinSplit (per #2171) controls which other proofs are needed.

It's actually better for the input stage to only control which note commitment is selected (i.e. to make a commitment to cm<sup>old</sup>). This is sufficient for security but may allow the input stage to be precomputed in some cases.

**Comment by daira** [comment]
The number of hashes needed is 14 for the I/O stage and 16 for each of two Merkle tree stages, giving 46, an overhead of 4 hashes over #647 alone. For this (and 592 bytes overhead in JoinSplit description size for the two extra proofs), we get stage circuits about 16/42 = 38% the size of a #647 circuit, drastically cutting down on the memory usage. The two Merkle tree stages can share the same circuit, so the total proving key size is reduced by about 30% relative to #647. Also we can cache one and possibly two of the three stage proofs for each JoinSplit.

**Comment by arielgabizon** [comment]
@daira : you wrote 
`We aim to make it indistinguishable which tree a given JoinSplit is using. `
Is there a method to do this such that we still always gain something? It seems in the case the transaction is in the large tree we do not.
Can you perhaps summarize what we gain and what we pay in return using this method? (I'm guessing we need more than one SNARK proof?)

**Comment by daira** [comment]
@ariel: We do gain in that case, because we cache the proof for the leafmost half of the large Merkle tree.

What we pay:
* There are three zk-SNARK proofs instead of one. So we pay 592 bytes per JoinSplit on proof size (with the current encoding and proof system), plus 96 bytes for the extra proof commitments and 32 bytes for the extra Merkle tree root. The JoinSplit description size for #647 is 1786 bytes, so this is an overhead of (592 + 96 + 32) /  1786 = 40.3% for a JoinSplit (less proportionally for a transaction).
" We pay a small overhead (5 SHA256Compress hashes) in the *total* circuit size &ndash;and therefore proving effort&ndash; per JoinSplit, and we pay in engineering complexity of linking the proofs, caching them, and security analysis.

What we gain:
* The two Merkle tree stages are the same, so the proving key size is reduced by about 26% (assuming it is proportional to the total size of unique proof circuits).
* The size of the proving key *per proof stage*, which currently accounts for most of the proving-time memory usage, is reduced by about 62%. So even without streaming, the memory usage for each proof is reduced accordingly. Note that streaming would introduce its own overheads and complexity. (More capable machines with a lot of parallelism and memory could still do the proofs in parallel if that helps.)
* About a third of the JoinSplit proof effort can always be precomputed. Once a commitment enters the large tree, then a proof can be cached with its witness, and then never has to be updated. If a commitment is used while it is still in the small tree, then it is possible to use a precomputed dummy proof, from a pool of such proofs that do not depend on the anchor or the commitment.
* A further third of the JoinSplit proof effort *may* be easier to precompute, because it does not depend on an anchor that changes every block. This depends on whether the parameters of the JoinSplit are known in advance.

The discussion above assumes that the input and output stages are not further split (which is compatible with the shielded multisig proposal in #782).

**Comment by daira** [comment]
Since memory usage of proving is no longer a serious issue after Sapling, the complication of this approach seems unnecessary.
