### ISSUE TITLE
Later arguments to gcc/g++ override the intended earlier arguments set by --enable-debug

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4317]
#4222, specifically a8780a982e6ec6b5cf65891c2db582519c63e480, intended to set `-ftrapv` (trap on arithmetic overflow) for debug builds, i.e. when `--enable-debug` is set. However Zcash compile flags already set `-fwrapv` (disable ill-advised "optimizations" that tend to make integer overflows more likely to be exploitable [*]):

https://github.com/zcash/zcash/blob/8e8a9350c32983a3835c403174eb8bc84973bad3/configure.ac#L816

(There's also a reference [in gitian-linux.yml](https://github.com/zcash/zcash/blob/b8ca7131c75f74973e9bc6322c2cfd613a5d82ba/contrib/gitian-descriptors/gitian-linux.yml#L40-L41) but I think it only affects the host flags for cross-compiles.)

`-ftrapv` and `-fwrapv` are conflicting and the last one on the command-line [takes precedence, roughly speaking](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html).

It's quite reasonable to set `-ftrapv` instead of `-fwrapv` for debug builds, and that is what I think we want to do. However, the current order has `-fwrapv` last:

@str4d wrote:
> We add `-fwrapv` to `CXXFLAGS` pretty far down
> Meanwhile `-ftrapv` is added to `DEBUG_CXXFLAGS`, which is then merged into `AM_CXXFLAGS` in `src/Makefile.am`
> I can't see where `CXXFLAGS` is added to automake lines; I assume it's automatic
> That means the order they are applied depends on the order in which Automake combines `libname_a_CXXFLAGS` and `CXXFLAGS`
> [...]
> This looks somewhat useful! Almost like they've had this question many times before...
> https://www.gnu.org/software/automake/manual/html_node/Flag-Variables-Ordering.html
> Okay, the order will be `AM_CXXFLAGS CXXFLAGS`
> So with `--enable-debug` we [will] see `... -ftrapv ... -fwrapv`

A similar problem also affects `-g` and `-O` options:
> Also ... the enable-debug logic also is partly-broken by `zcutil/build.sh` specifying `CXXFLAGS=-g` internally...
> Because it is set, the default `-O1` from the depends system is not erased, so we currently get `-O0 -g3 -ftrapv  ... -pipe -O1 -g -fwrapv ...`

I don't know whether there are further instances of this problem, and we should probably choose a solution that makes it easier to verify that there are not.

[*] Please let's not get into an argument about the use of `-fwrapv` here; the place for that would be #1832.

**Comment by str4d** [comment]
You can in fact see the configured flags in the output of `./configure`, but because a) that's in the middle of `build.sh` output, and b) we default to verbose output, we never actually look at it. I'm making a PR that disables verbosity by default in addition to fixing the above two issues (we are far more likely to spot this in the `./configure` output than the verbose output, which I expect everyone glazes over, and is only really useful for CI).

**Comment by str4d** [comment]
#4318 fixes two of the above issues. `-O0` from `--enable-debug` is still being clobbered by `-O1` from the depends system, but that can be fixed by having the depends system set a custom env variable like `DEPENDS_CXXFLAGS` instead of setting `CXXFLAGS` directly. Then we can add a specific `DEPENDS_OPT_CXXFLAGS` variable just for the `-O1`-ish options, which `--enable-debug` can clear. I think this might block on #58 however.

**Comment by superbaud** [comment]
i think this was closed by https://github.com/zcash/zcash/pull/4754
