### ISSUE TITLE
Add new state for the process of loading the zcash parameters

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#432]
While it's loading the proving key, we see this:

```
2015-11-13T11:25:22+0000  INFO check_call | Running ('./bitcoin-cli', '-datadir=/home/firexware/Data-1/Documents/FireXware/la/zerocashd/.zc-system-test/0', 'getwalletinfo')
error: {"code":-28,"message":"Verifying blocks..."}
```

**Comment by ebfull** [comment]
This may not be necessary when #783 lands?

**Comment by str4d** [comment]
Is this relevant at all now?

**Comment by str4d** [comment]
Is this still relevant?

**Comment by nathan-at-least** [comment]
I believe it is relevant.

We have some design disagreement in the team about how to treat the zksnark parameters and there are at least three options floating around:

a. require explicit up-front loading of proving parameters
a.1. always do this when the wallet boots
a.2. require an explicit RPC API to do this
b. load proving parameters lazily when generating the first pour
c. load the proving parameters in a streaming fashion for every pour

These options are trading off these important considerations:

1. how long does a user have to wait after loading the wallet before their first JoinSplit can be generated?
2. how long does a user have to wait for subsequent JoinSplit generations?
3. how much memory does the wallet require when "idle"?
4. how much memory does the wallet require when generating a JoinSplit?
5. how much control do RPC consumers have over resource usage? (Do they need low latency JoinSplit generation, low memory, or fewer RPC calls?)

**Comment by nathan-at-least** [comment]
My opinion on the above tradeoffs comes from these desires and assumptions:

I assume wallets already have a slow start time because they need to sync the blockchain. (That's been my experience with Bitcoin because I only start my wallet rarely.)

I assume nodes in exchanges, API services, and other "infrastructure" nodes will start rarely compared to their runtime.

I assume wallet end-users and infrastructure node users want low-latency transfers, rather than low memory.

I assume wallet designers and infrastructure developers can handle more explicit RPC interfaces rather than implicit/automatic ones.

I assume infrastructure operators that scale up want to have predictable / controllable resource provisioning.

So because of these assumptions, I want the parameter loading to be "up front" and more-or-less explicit.

**Comment by daira** [comment]
This interacts with #890.

**Comment by nathan-at-least** [comment]
It would be interesting to get feedback from wallet, exchange, CLI-end-users, and other infrastructure engineers on this. I'll ask around.

**Comment by ebfull** [comment]
@nathan-at-least Assigning this to you.

**Comment by daira** [comment]
I think this may be obviated by #2243.

**Comment by daira** [comment]
Actually the reported symptom went away when #783 landed before launch, and I think this ticket should have been closed then. In any case it is definitely obviated by #2243, and we're not going to add an additional state reported by the RPC interface.
