### ISSUE TITLE
UX: Is dependency fetching mandatory?

### ISSUE THREAD

**Issue by 3DA4C300** [zcash/zcash#4436]
## What were you trying to do
I was building ZCash and I noticed that the build script download dependencies even if they are satisfied from the system, is this a normal behavior? I'd expect that the build uses system libraries if they are available, to avoid useless traffic.

**Comment by rex4539** [comment]
The short answer is yes. Zcash requires to be built with very specific dependencies that have been tested.

Some dependencies should be allowed to come from the system and this is [a long-standing issue](https://github.com/zcash/zcash/issues/209).

**Comment by str4d** [comment]
Yes, dependency-fetching is mandatory for our codebase. We made the decision back before Zcash launched that we would use pinned dependencies with fixed versions. Among other things, this helps to avoid accidental consensus divergence due to consensus-breaking differences between dependency versions, such as the libsodium issue described in #2872.
