### ISSUE TITLE
zcashd should detect duplicate zcash.conf options and refuse to start if there are any

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#4495]
Backstory:

```
This experience I just had conveys how I feel about zcashd's usability really well:

    1. I start a testnet node, since Heartwood activated today, I want to play around with it.
    2. I wait 6ish hours for it to download the blocks. I realized the hashrate on testnet is low and I decide I want to mine some blocks and try the shielded coinbase. So I Ctrl+C out of zcashd and append "gen=1" to my zcash.conf.
    3. I get - : Error loading block database. Please restart with -reindex to recover. , no idea why.
    4. I restart with -reindex and wait another 1-2 hours for it to reindex. Then I realize it's not mining. I open my zcash.conf and realize there was already a gen=0 in there, the gen=1 I appended wasn't taking affect.
    5. So I fix my zcash.conf, press "up arrow", "enter" to restard zcashd. But damn it! I left the -reindex flag in there. I quickly ctrl+c but it's too late, now it has to reindex. Maybe in another 2hrs I'll get to play with Heartwood :-(
```

Aside from inconveniences like that, this could potentially create security/privacy issues if people's zcashd's are running with different settings than they expect because of duplicated `zcash.conf` lines.

**Comment by LarryRuane** [comment]
I was just curious what `bitcoind` does, so I started it with these two lines in `.bitcoin/bitcoin.conf`:
```
testnet=1
testnet=0
```
(they don't have a `gen` option), and it started in mainnet mode. I also tried reversing those lines and it started in testnet mode. So it seems that the _latest_ option listed wins. It's interesting that for `zcashd`, the _earlier_ `gen` line wins (I verified this too). That seems strange.

Do you think it would be preferable if the _latest_ option wins, as opposed to disallowing conflicting options? I'm not sure I think so, probably not, but just want to raise it as a possibility (that would have worked in your experience).

The other thing I'm concerned about in making this change is that there could be many now-illegal config files out in the world, and node operators may be annoyed that their nodes no longer start. This is a hack, but would it perhaps be preferable to print a warning that there are conflicting options, sleep for 5 or 10 seconds, then proceed to startup? That would give the user the chance to control-C and fix it. Again, I'm not at all sure I like this, but just a thought. Maybe after warning for a few releases, then disallow conflicting options.

Going back to my suggestion that the latest option wins, that could change the behavior of existing nodes too! Well, maybe with good release notes, any of these changes would be okay.

**Comment by oxarbitrage** [comment]
By the discussion i see here in my opinion the best thing to do is to not allow duplicated options that are not hardcoded. If we are going to make changes i think this is better than make the second wins just because bitcoin works like that. 

Implemented this approach at https://github.com/zcash/zcash/pull/4583 , can be changed to a warning instead of a `throw` if we want to have that for some time before actually doing it.

**Comment by str4d** [comment]
@LarryRuane:
> I was just curious what `bitcoind` does... it seems that the latest option listed wins. It's interesting that for `zcashd`, the earlier gen line wins (I verified this too). That seems strange.

This is due to the way in which arguments are parsed, which has been overhauled upstream. Specifically, the following two sections, inherited from upstream, give rise to `zcashd`'s config behaviour:

- First `ParseParameters` is called, to parse `zcashd` arguments. Later parameters overwrite earlier ones in `mapArgs`, so the last CLI parameter wins.

  https://github.com/zcash/zcash/blob/3f4a5325887410977692ff57b83943338500b251/src/util.cpp#L391-L392

- Then `ReadConfigFile` is parsed (necessarily second, in case the user passes `-conf` on the CLI). It writes into the same `mapArgs` and `mapMultiArgs`, but explicitly will not overwrite existing parameters so that the CLI args take precedence. However, this also means that later parameters in `zcash.conf` do not overwrite earlier ones, so the first `zcash.conf` parameter wins.

  https://github.com/zcash/zcash/blob/3f4a5325887410977692ff57b83943338500b251/src/util.cpp#L635-L637

We could look at upstream's PR / release notes for when they overhauled config parsing, to see how they handled this issue.

**Comment by daira** [comment]
I don't think that refusing to start when `zcash.conf` has conflicting options is a serious compatibility problem. It's trivial to fix, if it is correctly reported.
