### ISSUE TITLE
z_importviewingkey should return address even if imported

### ISSUE THREAD

**Issue by NorbertBodziony** [zcash/zcash#4536]
## Is your feature request related to a problem? Please describe.
Right now if node already contains viewing key for address rpc call returns error, so we cannot retrieve address connected with key

## Describe the solution you'd like
`z_importviewingkey` will return address in error.

**Comment by str4d** [comment]
Could you confirm exactly what error message you see? From what I can tell, `z_importviewingkey` should already return the default address for a viewing key if the viewing key has previously been imported into the wallet.

It _does_ return an error if the spending key for that viewing key is already in the wallet. This usage seems generally invalid to me, as a user importing a viewing key likely thinks that the wallet doesn't contain any key material related to the viewing key - unless `z_importviewingkey` is being used specifically for the side-effect of deriving the default address, in which case it seems more appropriate to have a separate derivation method (which e.g. the Rust code has).

**Comment by holmesworcester** [comment]
We're moving on to light wallet land, so I think fixing this will be of little value to us. 

That said, the current behavior did create a hiccup, so I'll describe what the hiccup was, so that you can decide if this is worth fixing for others.

We were using zcashd as a source of truth, so when it returned an error, we didn't know how to reflect that in our state or tell the user what had happened. 

The user should see a message like "Error: you've already imported viewing key XXXXXXXXXXX and can already view transactions to it" and not just "We could not import that viewing key" because those are two different things from the user point of view. Really what's happening is success. The user has access to whatever they want access to. Just telling the user there was an error seems like failure.

And the user might have removed a viewing key from whatever app is using zcashd as a source of truth. I don't think it's possible to remove keys from zcashd currently, so the app couldn't remove them there. If a user removes a viewing key and adds it again, the app doesn't have a good way of knowing what the error was or what to do, unless it itself saves all removed viewing keys or some descriptor of them forever. 

Including the viewing key in the error message solves this.
