### ISSUE TITLE
Fix DecrementNoteWitnesses processing, and flush the wallet db on a clean shutdown

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4596]
From https://github.com/zcash/zcash/pull/4573/commits/872af58d592247146ad565cb7b05a220539fa7bb#r451937051 :

> The test partitions one node (0) from the other two nodes (1 and 2). Node 0 mines one block, and the two-node partition mines two blocks. The test then stops, restarts, and reunites the 3 nodes. Because of this call to SetBestChain() as part of node 0's clean shut down, node 0 does not go through a "Rescanning..." phase when it starts up. During its startup, node 0 discovers that there is a better chain, and reorgs away the block it mined itself, and part of this calls DecrementNoteWitnesses(). But the new block's indexHeight is one greater than the witness data height (nd->witnessHeight), tripping the asset that they should be equal. This assert is most certainly wrong, because this is a perfectly legitimate, although rare, sequence of events.
>
> Without this flush-on-clean-shutdown code, node 0 goes through the "Rescanning..." phase, and that retrieves the best chain blocks from the network (resynchronizes). Although DecrementNoteWitnesses() is called, the inequality doesn't occur and so no assert happens.
>
> We'll have a separate PR that will fix this DecrementNoteWitnesses() processing, and that will allow this flush-on-clean-shutdown code to be restored. But for now, leaving it out does no harm in the sense that this has been wrong for a very long time. After all, it's certainly possible for the witness data to be flushed (which happens once per hour) just before shutdown, even without this code. So we definitely should fix this, but not in this PR.

**Comment by LarryRuane** [comment]
After an investigation with the help of @therealyingtong, it seems I had this wrong. `DecrementNoteWitnesses()` is working correctly. The failure was caused by an invalid test, `wallet_anchorfork.py` (which is the test referred to in the comment that Daira quoted above). After the nodes are partitioned into two groups or partitions, each mines blocks but neither calls `self.sync_all()` before shutting down and restarting. It's actually not possible to call `self.sync_all()` in this context, because the nodes are partitioned and the syncing will never complete. But it is possible to sync the two partitions separately. [This commit](4811dcc426ef3e20a3ddac7bc392d64be583a704) (which is now in master), does this syncing, but only for the node 1,2 partition. And rather than that test change making the problem reproduce reliably, as I thought (see the comment at the top of this issue), it does the opposite -- it makes the problem not reproduce at all. 

It turns out that the syncing that was added by that commit usually introduces sufficient _delay_ to allow node 0 to flush its newly-generated block to disk before shutting down. If that syncing is removed from the test, node 0 will often not have enough time to flush its new block to disk, and then the assert occurs on its next restart. I verified that just sleeping for a couple of seconds instead of syncing makes the test pass reliably too. (The functions `sync_all()`, `sync_blocks()`, and `sync_mempools()` don't actually force any syncing; they simply wait for the syncing which happens anyway to occur.)

So, all that needs to be done to fix this ticket is to make the node 0 partition sync before shutting down. I'll create a PR to do that in a moment. It may be worth systematically examining all of the RPC tests for similar problems; such problems can make tests flakey.

The reason this test bug wasn't seen earlier is that, until #4573, `zcashd` wasn't flushing witness data on clean shutdown, causing at least several blocks to be rescanned on subsequent startup, thus hiding the problem with the test.

During the days I was investigating this ticket, when I believed there was a bug in `DecrementNoteWitnesses()`, I thought (and still do) there may be some problems with it (and related code; the overall way the witness updates are done in `wallet.cpp`). At the very least, I think it's far from written in the simplest, most obviously correct way. I've got a patch that's all simplification, and it may be worth my spending more time seeing if it's worth merging. But it's low-priority since the existing code has been unchanged for a long time. It's also possible my patch simplifies _too_ much due to my lack of understanding. But that will possibly be the subject of a different PR.
