### ISSUE TITLE
The -loadblock command only reads the first few blocks from the file, but not all.

### ISSUE THREAD

**Issue by bigbrain** [zcash/zcash#4679]
### Describe the issue
The **-loadblock** command only reads the first few blocks from the file, but not all. At the next start with the same file, it takes the next few blocks, but also not all.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Prepare new server for testnet (no blockchain, no database, no indexes)
Disconnect from the network for the purity of the experiment (maxconnections=0 into zcash.conf)
2.  Start the server with the command: zcashd.exe -stopafterblockimport -loadblock="D:\ProgramData\Zcash\testnet3\blocksBak\blk00000.dat" The server loads blocks 1-640 and shuts down. Recorded in the log file.
3. Start the server with the same command: zcashd.exe -stopafterblockimport -loadblock="D:\ProgramData\Zcash\testnet3\blocksBak\blk00000.dat" The server loads blocks 641-657 and shuts down. Recorded in the log file.
4.  Start the server with the same command: zcashd.exe -stopafterblockimport -loadblock="D:\ProgramData\Zcash\testnet3\blocksBak\blk00000.dat" The server loads blocks 658-661 and shuts down. Recorded in the log file.

Without -stopafterblockimport, the same happens, only the server continues to work.

### Expected behaviour
The server should load **all** blocks from the specified file.

### Actual behaviour + errors
There are no errors in the console. It's okay.

### The version of Zcash you were using:
Zcash version v3.1.0-rc2-d058568e0

### Any extra information that might be useful in the debugging process.
[debug.log](https://github.com/zcash/zcash/files/5111386/debug.log)

**Comment by bigbrain** [comment]
Hello.
I think I have the same problem with -reindex, so I cannot use it. I think -reindex also breaks before indexing all the blocks in the file. But it's hard for me to prove it. When I ran -reindex my blockchain was corrupted as a result. Because -reindex stopped working after processing some files and started downloading data from the network. This corrupted the already downloaded data. I wanted to restore the blockchain using -loadblock, but it has also become a problem and I have create this issue.

I also find it difficult to sync again with the network because [https://github.com/zcash/zcash/issues/4624](https://github.com/zcash/zcash/issues/4624)

**Comment by bigbrain** [comment]
```
--- a/src/init.cpp
+++ b/src/init.cpp
@@ -639,16 +639,24 @@ void ThreadImport(std::vector<boost::filesystem::path> vImportFiles)
     }
 
     // -loadblock=
-    BOOST_FOREACH(const boost::filesystem::path& path, vImportFiles) {
-        FILE *file = fopen(path.string().c_str(), "rb");
-        if (file) {
-            CImportingNow imp;
-            LogPrintf("Importing blocks file %s...\n", path.string());
-            LoadExternalBlockFile(chainparams, file);
-        } else {
-            LogPrintf("Warning: Could not open blocks file %s\n", path.string());
+    // Because blocks can be out-of-order (not just within one file but across
+    // the multiple files specified here), it may take several passes over the
+    // files to process all of them, or, strictly speaking, as many of them as
+    // possible (since some may have parents that aren't in any of these files).
+    bool progress;
+    do {
+        progress = false;
+        BOOST_FOREACH(const boost::filesystem::path& path, vImportFiles) {
+            FILE *file = fopen(path.string().c_str(), "rb");
+            if (file) {
+                CImportingNow imp;
+                LogPrintf("Importing blocks file %s...\n", path.string());
+                progress |= LoadExternalBlockFile(chainparams, file);
+            } else {
+                LogPrintf("Warning: Could not open blocks file %s\n", path.string());
+            }
         }
-    }
+    } while (progress);
 
     if (GetBoolArg("-stopafterblockimport", DEFAULT_STOPAFTERBLOCKIMPORT)) {
         LogPrintf("Stopping after block import\n");
```
Hello.
I compiled and used your fix and it works for me. Unfortunately, due to the slow speed, this fix is not very useful. Since the blocks are not sorted, 1-5 blocks are obtained at each iteration. After 1 hour of work, the first block file is still not formed. And there are a lot of these files.

**Comment by LarryRuane** [comment]
> Unfortunately, due to the slow speed, this fix is not very useful.

Yes, this was my experience as well; that's why I said it's not a good fix. I actually have an open [upstream PR](https://github.com/bitcoin/bitcoin/pull/16981) that would improve the speed somewhat, but it's still not the right fix.

I think fixing `-loadblock` should be considered low priority, because it seems you are trying to use it as a workaround for `-reindex` not working. If reindexing is broken, that's definitely a big problem. There should be a ticket for that (or modify this ticket to say that reindex is broken). 

I don't think `-loadblock` makes sense at all. I just found this interesting [commit](https://github.com/zcash/zcash/commit/7fea48467442079cd0b4021b580761d7e33fa8a1) where `-reindex` was added and `-loadblock` already existed -- so `-reindex` was a nicer way to do what people used `-loadblock` to do previously. That strengthens my opinion that `-loadblock` isn't worth fixing. My guess is that back in 2012, the "headers-first" block download hadn't been implemented and merged yet, so blocks were in height order in the `blk?????.dat` files, so `-loadblock` worked well. Headers-first download broke it, but there's been no strong reason to fix it since `-reindex` existed by then.

**Comment by bigbrain** [comment]
I understand. Then this issue can be low priority or closed at your request.

For myself, I can use the above fix, having previously sorted the blocks inside each backup file. After that, I can quickly restore my damaged blockchain. Thanks for helping me with this fix.

I'm not sure if `-reindex` is broken. I can neither prove nor disprove it. Perhaps my blockchain was corrupted in some place before `-reindex` discovered this corruption. I cannot verify this. But the attribute of the damaged file _blk?????.dat_ `"Modified"` did not change before reindexing. Therefore, I believe that the file was not damaged before.

**Off-topic:**
When I looked at the `LoadExternalBlockFile` method of the `main.cpp` file, I saw the magic number 80. Why 80? Maybe 80 is the size of the _bitcoin_ block header. But _zcash_ has a different header size. Perhaps this is something else and I was wrong.
```c++
            try {
                // locate a header
                unsigned char buf[MESSAGE_START_SIZE];
                blkdat.FindByte(chainparams.MessageStart()[0]);
                nRewind = blkdat.GetPos()+1;
                blkdat >> FLATDATA(buf);
                if (memcmp(buf, chainparams.MessageStart(), MESSAGE_START_SIZE))
                    continue;
                // read size
                blkdat >> nSize;
                if (nSize < 80 || nSize > MAX_BLOCK_SIZE)
                    continue;
            } catch (const std::exception&) {
                // no valid block header found; don't complain
                break;
            }
```

**Comment by LarryRuane** [comment]
> Why 80?

You're right, good catch! As you say, that's leftover from Bitcoin. It doesn't do much harm, because it's only a basic sanity check on the size field. Most likely file corruption here would cause the value to be greater than `MAX_BLOCK_SIZE` or zero, so the corruption would be detected.

This bug could cause the code to not detect data corruption in the byte stream here, but the subsequent attempt to deserialize the block would almost certainly fail. Please feel free to write a ticket for that, or I can if you'd prefer.

Yes, I'll close this ticket, but please reopen a new one if you believe (even if you're not sure) that `-reindex` is broken or that the `blk.dat` files are being corrupted somehow, thank you.

**Comment by LarryRuane** [comment]
@bigbrain, I created an [upstream PR](https://github.com/bitcoin/bitcoin/pull/20331) to fix this problem there; if it gets merged (or maybe even if it doesn't), I'll cherry-pick it to here.
