### ISSUE TITLE
Choose a name for Sapling-on-Halo-2

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4718]
We've consistently regretted conflating Sapling the shielded protocol, with Sapling the network upgrade. So we should choose a name for the Sapling-on-Halo-2 shielded protocol now, independent of which network upgrade (if any) it will go into.

**Comment by zebambam** [comment]
Lillypad.

**Comment by nathan-at-least** [comment]
No good ideas yet, but I ran across a bunch of fun stuff while searching for "halo" and trees/botany:

- [Hollyhock, the "Halo Blossom"](https://www.pinterest.com/pin/220817187957819411/) - couldn't find any other references to this nick-name.
- [a cactus flower halo](https://www.pinterest.com/pin/462041242994162623/)
- [The Halo Trees](https://thehalotrees.com/) - a band.
- Some visual art I like: [Suit (Forest Halo)](https://danhillier.com/products/suit-forest-halo-left) & [Halogen Forest](https://mattw.art/experiments/halogen-forest/)
- Apparently [Halo Merge Trees](https://arxiv.org/pdf/1906.09382.pdf#:~:text=A%20halo%20merger%20tree%20describes,merger%20history%20of%20DM%20halos.) are apparently a way to model galaxy formation.

;-)

**Comment by nathan-at-least** [comment]
Thematic metaphor-wise: [secondary growth](https://en.wikipedia.org/wiki/Secondary_growth) can transform a soft sapling to have a sturdy wooden base. Feels relevant, but "secondary growth" is a terrible name. 😂

**Comment by daira** [comment]
I quite like "Pole".

![Illustration of trees, with the pole stage marked.](https://user-images.githubusercontent.com/643204/92575875-be42b580-f280-11ea-84c1-c7170851351f.png)
<img alt="Slide titled 'Classification of even-aged stands by size'. A pole is the stage up from sapling, defined as a tree 4-10 inches in diameter." src="https://user-images.githubusercontent.com/643204/92576048-f21ddb00-f280-11ea-8dc0-2f872c7d5177.png" width=400>

**Comment by daira** [comment]
We need to consider that this will be a user-facing name for an address type. I.e. "Sprout address", "Sapling address", "Pole address". Does that sound ok?

**Comment by daira** [comment]
<img alt="Photo of a pole-stage forest stand." src="https://user-images.githubusercontent.com/643204/92578526-dbc54e80-f283-11ea-88f6-1634294985c1.png" width=400>
"A view of the 28-year-old forest stand at plot H (pole stage stand), photo: E. Luptáková."

Figure 1 of https://www.mycosphere.org/pdf/MYCOSPHERE_9_6_1.pdf

**Comment by jswihart** [comment]
I wonder if it'll be too confusing to use our NU naming pattern for the protocol. If we want to avoid conflating the two and not confuse people, we should name the shielded protocol something independent of botany.

**Comment by gojomo** [comment]
'Pole' collides with a demonym (for a Polish person), which could be awkward. 

This pool & address-type may be more durable & mass-market than its predecessors – by virtue of having resolved both the performance bottlenecks and trusted-setup concerns that limited earlier generations. So, thematic continuity (with Sprout, Sapling, etc) may be less important than usability & marketing goals, such as memorability & positive/relevant connotations.

If willing to go into the "Z-words" well once again, I did a quick scan through words-starting-with-z, filtering for some combo of easy to speak/spell or interesting-enough-to-risk-issues. Some 

* zebu (a humpback ox)
* zedonk (zebra-donkey)
* zeta
* ziggurat (could be abbreviated 'zig' for 'zig address')
* zest/zesty (but debian collision)
* zephyr
* zimbi (cowrie shell used as money!)
* zinc
* zocalo (plaza in mexico)
* zooks (exclamation
* zoon (organism-from-egg)
* zorilla (skunklike striped polecat)

A made-up word could also be beneficial, but the otherwise attractive "Zalo", for Z(cash-H)alo is already the name of a popular WhatsApp competitor in Vietnam.

**Comment by hdevalence** [comment]
I'm not sure I understand the rationale here.

Sapling the shielded protocol and Sapling the network upgrade are already conflated.  Similarly, Sprout the shielded protocol and Sprout the network upgrade are conflated.  Because Sprout (the protocol) is now performed on Groth16 rather than BCTV14, it's already necessary to talk about:

- Sprout-on-BCTV14
- Sprout-on-Groth16
- Sapling(-on-Groth16)

Isn't

- Sprout-on-BCTV14
- Sprout-on-Groth16
- Sapling-on-Groth16
- Sapling-on-Halo2

a more consistent extension of the already-existing nomenclature than

- Sprout-on-BCTV14
- Sprout-on-Groth16
- Sapling (= Sapling-on-Groth16)
- Pole (= Sapling-on-Halo2)

especially since Sapling-on-Halo2 provides the same functionality as Sapling-on-Groth16?

**Comment by str4d** [comment]
> Because Sprout (the protocol) is now performed on Groth16 rather than BCTV14, it's already necessary to talk about:

This is true from a technical or protocol implementor perspective. However, it does not make sense from a user perspective, as it exposes a level of detail that they do not need to care about.

> especially since Sapling-on-Halo2 provides the same functionality as Sapling-on-Groth16?

But crucially, not the same addresses; at a minimum, the curves are different, and thus these are not the same concrete instantiation of the generic Sapling-like protocol.

By contrast, Sprout-on-BCTV14 and Sprout-on-Groth16 may use different proving systems and different verification circuits, but they are still the same concrete instantiation of the protocol, with the same addresses. Users had to update their software to continue using Sprout addresses after the Sapling NU, but they did not need to change anything about their spending key backups, for example.

**Comment by daira** [comment]
Right, the user-facing thing that we're naming here is effectively the address type. We would not change this name if we made a change analogous to moving Sprout from BCTV14 to Groth16, *provided* the addresses were compatible.

**Comment by daira** [comment]
I take the point that Pole in English is also a demonym for a Polish person, but it's that actually a problem? It seems unlikely to cause any confusion in context. (There's no ambiguity *in Polish*; I believe the forestry term in Polish would be "drągowina", while the demonym would be "Polak".)

**Comment by daira** [comment]
Soaking of demonyms, Urban Dictionary claims that zimbi is slang for a person from Zimbabwe. Also if you Google it then most of the hits are for a South African gun store of that name.

**Comment by gojomo** [comment]
My concern would be that while 'pole' has many meanings in English - most prominently of course those tubes, usually wood or metal, for extending/reinforcing something - I'd expect most English speakers to primarily parse "pole address" as "address of a Polish person", then maybe "address where some pole is installed". 

Sure, extra context that's usually present would remedy most confusion, eventually making it clear to readers/listeners that *this* use of 'pole' refers to a somewhat-arbitrary tech release codeword. But why create any momentary dissonance, or "huh?" double-takes, unless such undertones have been specifically chosen for *helpful* connotations? 

I'd never heard the sense of 'pole' meaning "small tree" before this thread, so that sense seems bereft of generally-positive or memorable associations. Only those who know the Sprout->Sapling progression, *and* the sense of 'pole' that continues that theme, get any benefit from the word. Even with some idea of the crypto domain, my 1st guess seeing "pole address" would probably be that the word was chosen to connote some sort of "tentpole" address around which others a built - like perhaps a root key attesting-to, or providing shade/shielding-for, other ("non-pole") addresses. 

Given charged emotions around nationalities/ethnicities, and the vagaries of how those emotions change, I'd consider demonym collisions more risky than other word-collisions. (Is that country still in the same co-prosperity spheres as my country this decade, or have they gone back to some rival bloc? Are the stereotypes of that nation/nationality trending positive or negative? Etc.) Also, if 'pole' seems harmless enough to you, would you say the same about other monosyllabic demonyms? For example, 'scot' has an archaic meaning related to assessed fees; would 'scot address' be a safe choice for naming a new kind of crypto-address? Demonym 'brit' also can mean some tiny marine mammals – kinda like tardigrades. But wouldn't 'brit address' carry distracting connotations for many potential users?

If 'zimbi' is truly recognized as a nickname Zimbabwean, it has the same problems. (I find Urban Dictionary very hit-and-miss on whether the definitions there have real currency.)

Of the other z-words I threw out: 

I *would* like 'zeta' for its mathiness & seeming-like-it's-a-final-letter (though in truth it's not)... but the collision with the name of a notorious crime syndicate is bad news. 'Zebu', 'zedonk' and 'zorilla' have goofy appeal, which makes them somewhat memorable and generative of discussion or cartoon mascots – but the underlying animals don't necessarily suggest qualities we'd want associated with a new address type/value-pool.

My sense of most workable from that list would be:

* 'zest' - positive word, one syllable, rhymes with "best", "zest address" has consonance
* 'zinc' - history of usage in coins & rust-resistant alloys, one syllable, "zinc address" hints of metallurgy/science
* 'ziggurat' - evokes ancient/imposing structures built over generations, abbreviates well into "zig address" with 'sig[nature]' undertones
* 'zephyr' - a soft breeze, pleasant but invisible, abbreviates ok as "zeph address" 
* 'zocalo' - evokes friendly public plaza or place-of-commerce, but probably too many syllables

**Comment by daira** [comment]
I also quite like @zebambam's suggestion Lilypad (note that the correct spelling has one 'l').

**Comment by lindanlee** [comment]
> Lillypad.

![Collage 2020-09-15 13_24_05](https://user-images.githubusercontent.com/6580269/93469008-78f03a80-f8b5-11ea-9d98-8dcf87fb7202.jpg)

Upon request 🌿

**Comment by charlieok** [comment]
My wife lately got really into propagating pilea plants, and suggested that the idea of 'propagation' or some derivative might fit nicely somewhere into our plant naming scheme. I agreed, so adding it for consideration, for either this or something else in the future.

https://en.wikipedia.org/wiki/Plant_propagation

![plant-propagation](https://user-images.githubusercontent.com/7226/93469658-062f9100-f8ae-11ea-81b6-5b4fd09b6d82.jpg)

**Comment by nuttycom** [comment]
What about 'coppice'? @daira this is related to your 'pole' term, but it's particularly apt in this scenario - it's a stump that is repeatedly felled to produce pole-stage trees, for the production of things like fence posts and gates: https://en.wikipedia.org/wiki/Coppicing

**Comment by jswihart** [comment]
A slightly different direction: Patina - which is "a special quality or impression about something," also synonymous with Halo, has organic tones (wood patina) and is a sort of an interplay between a surface and application that yields even something more rich and interesting.

**Comment by daira** [comment]
I like that Coppice is only two syllables, and the derivation seems appropriate. "Coppice address" also sounds good to me.

**Comment by gojomo** [comment]
Not previously being familiar with the word/place 'Coppice', it's unclear from sight whether it's said like "Cop-Ice", "Cop-Iss", or perhaps "Cop-Eeze". Having looked up the proper pronunciation ("cop-iss"), I'm not sure hearing it would lead me to the right spelling (as opposed to 'copis', 'copiss', 'kopis', etc). 

The words that I know that 'coppice' is most-similar to, and thus at risk of confusion with, are "capeesh" (aka 'capish' or 'capiche', slang for "do you understand?" derived from something in Italian) and 'codpiece'. 

None of these qualities of the word seem useful for user communications. 

If the name is for official developer communication, a precise synthetic word/abbreviation could work well, like 'SoH2' or 'SapH2'.  But if the name is intended for things like user interfaces, user tutorials, explainers, error/warning dialogs, and so forth, a word that's short, clear, and resistant to implying either too much or too little into it should be a priority. 

Consider user help pages with titles/subtitles like:

* "Benefits of X Addresses"
* "Considerations when sending from your X address to a Sprout or Sapling Address"
* "How to ensure privacy when migrating funds to your X Address"
* "How to tell if your Zcash address is an X Address"

Or, potential future software warnings/errors like:

* "Your funds are in a X Address, and sending to Sprout Addresses is no longer supported"
* "Error: You've requested a send to a Sapling Address, but this mobile Zcash wallet only supports X Addresses"
* "Warning: your funds are in a Sapling Address, and you've requested a send to a X Address, which risks revealing the amount sent. (_More Info_) Are you sure you want to proceed?"

Or, a columnar or JSON report from a multi-address wallet that labels each address with its type name.

**Comment by daira** [comment]
I think that unfamiliarity with the word could be mitigated to some extent by briefly explaining its original meaning when we announce it, and including the pronunciation in docs. E.g. something like "The next upgrade will introduce Coppice addresses (pronounced 'copp-iss'), which use the Halo proving system. We choose the name Coppice because ..."

**Comment by gojomo** [comment]
I see 'coppice' starting to be used as a label in Github issues. By most of what I've ever observed about names, it's a poor choice: can't tell the pronunciation from the spelling, can't guess the spelling from hearing it, lacks positive or domain-relevant connotations, and sounds a bit naughty ("cop-piss"). I hope before it is formally adopted, or starts to appear in user-communications, it could be run by a larger audience for feedback, including those with special responsibility/expertise for user-education/marketing. (Sapling-on-Halo-2 is a breakthrough that should get a lot of positive buzz, and in my opinion, deserves a buzz-worthy name.)

**Comment by steven-ecc** [comment]
Thanks for the feedback @gojomo. We've actually passed on using Coppice for some of the same reasons you mentioned. Easily misspelled, doesn't really roll off the tongue (coppice address vs. sapling address). We're also looking for words that don't start with c or s as that would conflict with prior address types (zc*, zs).

**Comment by steven-ecc** [comment]
Pollard it is!

**Comment by daira** [comment]
![image](https://user-images.githubusercontent.com/643204/96739212-73f04080-13b7-11eb-8db8-4e9a8263d55a.png)

**Comment by daira** [comment]
We're reconsidering this name. Another candidate is "Orchard".

**Comment by gojomo** [comment]
If "Orchard' is being considered to be the name-label for this tech's value-pool, and the addresses to send value into that pool, I'd again urge the choice of a name that (1) contracts/abbreviates well; (2) meshes well with outreach messages about privacy, speed, modernity, etc. 

To my ears 'Orchard pool' or 'Orchard address' don't do that. Too many syllables, the hard-d doesn't roll into the 'p' or 'ad' following, bring up images/connotations of agriculture, outdoors, gardening, geocaching, and so forth rather than privacy/security/speed/commerce. The obvious contractions to a letter or monosyllable - "O address" or "Orc address" or "Orch address" – each have issues. 'O', especially, often signifies 'open' in tech domains and thus even becomes a little confusable with 'T'ransparent. ('Orc' could be a daringly memorable choice, but in the world of cybercoins, Zcashers have always seemed a bit more elfin/ethereal, leaving the orcishness to other communities. :)

**Comment by steven-ecc** [comment]
Orchard it is!
