### ISSUE TITLE
Incorrect configure file generated.

### ISSUE THREAD

**Issue by kinnefix** [zcash/zcash#4867]
Hi, I was trying to build zcash on ubuntu x86_64.
I missed the description and did not have libboost-program-options-dev installed.
Running ./configure gave me error message like : 
"Could not link against -lboost_filesystem"
But my system was correctly configured so that lboost_filesystem was available to gcc.

The solution however was simply to install libboost-program-options-dev using apt.
So, I'm guessing configure file was not generated correctly.
I can't point out where to fix, but autogen.sh should be generating configure file in a manner that ax_lib is properly set to value libboost_program_options before check for availability of boost-program-options is performed.

**Comment by str4d** [comment]
You need to build the `depends/` subsystem in order to get the vendored Clang and correct dependencies, which are then statically linked into `zcashd`. Neither GCC nor dynamic system Boost libraries are supported (though they may still happen to be usable at present - we only just migrated to requiring Clang in v4.1.0, and don't yet require Clang-specific features, but we will soon).

The easiest way to run a full build is with `./zcutil/build.sh`. You can look there for how the `depends/` subsystem is integrated into the main build (specifically via a `config.site` file).

**Comment by kinnefix** [comment]
Oops, it seems I did not read description carefully.
Using ./zcutil/build.sh was clearly instructed right on the description.

Attempt to build with ./configure failed for some reason, I'll use above method this time.
Closing with comment.
