### ISSUE TITLE
[Orchard] Decide on memo changes, if any

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4960]
Keep ZIP 302 in mind.

**Comment by str4d** [comment]
Background: In Sprout and Sapling, each output has an encrypted note plaintext that contains the note data, along with a 512-byte memo field.

The minimum we plan to change for Orchard is:
- The memo field will be encrypt separately in order to provide note ciphertext authentication to light clients that aren't fetching memos or signatures.
- The note plaintext will include the first byte of the memo as an indicator of whether the memo contains anything.
  - TODO: Should that byte be duplicated? Having it split into 1 + 511 bytes in separate ciphertexts could be rather annoying for text memos (but then again, you already have to decrypt the ciphertexts, so another copy isn't too bad).

The motivation for considering a larger change than this, is that the Halo 2 proofs used by Orchard are an order of magnitude larger than Groth16, so we want to consider the possibility of instead having a single memo field per transaction. This enables transaction sizes to be kept down when empty memos are not required, but it prevents transactions from having multiple recipients with independent memos. We would also need to decide whether only one recipient can decrypt the memo, or whether any/all should be able to (in which case each output needs to contain a symmetric decryption key).

Finally, we could decide to allow the number of memos to be in the range `[1..N]` (where `N` is the number of outputs in the transaction); perhaps only allowing either `1` or `N`, or allowing some or all of the range in between. This option would leak some amount of information about the number of recipients, so it makes sense that if we did implement this, it should be bucketed in some fashion.

Summarising the possible designs (`M` is the number of memos if variable, and the split CT and indicator byte from above are assumed):

| Design | Cost relative to Sapling (bytes) | 2-output tx | 10-output tx |
|---|---|---|---|
| N memos per tx | 17N | 34 |170 |
| M memos per tx, some recipients can decrypt | 33N - 512(N - M) + 16M = 528M - 479N | -430 to 98 | -4262 to 490 |
| 1 memo per tx, some recipients can decrypt | 33N - 512(N - 1) + 16 | -430 | -4262 |
| 1 memo per tx, one recipient can decrypt | N - 512(N - 1) + 16 | -494 | -4582 |

**Comment by str4d** [comment]
Beyond the transaction size considerations, there are also UX considerations:
- Having one memo per transaction shouldn't need to be represented in UIs any differently than a Sapling transaction that includes no memo (i.e. `0xf60000..`). Similarly for "one memo that some or all can decrypt": if an output's symmetric key fails to decrypt the memo, then it is represented as having no memo.
- Having `M` memos per transaction that a subset of recipients can decrypt opens up the possibility that more than one memo might be decryptable by a single recipient. We would then need to decide whether to only display the first memo, or allow several distinct memos (treated independently), or use some multi-memo encoding to allow logically-larger memos. This gets complex fast...

**Comment by str4d** [comment]
@daira, @nuttycom and I discussed this, and decided that we would specify the more general design (memos are disjoint from outputs, and M may be any value unrelated to N), and then we can decide whether we want to apply more specific restrictions (`M == N`, `M == [1, N]`, `M <= N` etc) in the consensus rules, balancing the potential use cases and the metadata leakage (or lack thereof).

**Comment by nuttycom** [comment]
Some use case considerations:

- If M <= N, M memos may be decryptable by different subsets of the N recipients
- If M > N, this gives a mechanism for "broadcast" type usage for larger payloads. This seems useful for, say, shielded newsletters. I think there's really interesting design space here, and I think that it would be necessary to impose block fees based on transaction size if this case is permitted (I think that block fees being based on transaction size is a desirable change anyway.)

**Comment by ebfull** [comment]
We shouldn't do any further changes to things like this in the Orchard design we're working on; there are too many potential decisions about the design of memo format changes, and the fewer changes we make from Sapling the better (in this upgrade). We can revisit this in another network upgrade.

**Comment by nuttycom** [comment]
@ebfull Can you identify what you see as the "default" scenario? In Sapling we have one memo per output, but we don't have an equivalent in Orchard; at best we have one-memo-per-action. But this wastes a lot of space in transactions that are merging a bunch of small notes, which are going to be relevant for folks like ZecPages - Michael gets a ton of 0.001 inputs, and presumably if he wants to spend or transfer any nontrival amount it's going to end up with hundreds of inputs.

As I see it, adding a symmetric key to each action, and then having a separate list of M <= N memos is the simplest possible change that we could make that avoids this kind of pathology.

**Comment by ebfull** [comment]
Default scenario will be that every action has a memo that corresponds with the output of the action.

I know this is wasteful -- I support a more efficient memo arrangement in a future network upgrade. I don't think in the near term it's a major issue and trying to address it now is unnecessary and makes the delta between sapling and orchard too large.

**Comment by nuttycom** [comment]
@ebfull I guess. I'm a little disappointed by this whole thing, because I've been asking about this ever since the very start of Orchard design, and the answer was always "we'll decide later." Now it's later and the answer is "it's too late to change."

**Comment by nuttycom** [comment]
Could we at least make the change to the transaction format where there are N memos stored separate from the actions, and a symmetric key as part of each action, with a 1:1 relationship between memo and action? Then at least we can have the transaction identifier and signature hash functions remain stable between this network upgrade and a future network upgrade that relaxes the strict 1:1 requirement. Otherwise we're going to be causing churn in the orchard transaction format that is readily avoided.

**Comment by daira** [comment]
The main argument for addressing it now is that transaction sizes will be increasing in Orchard, and allowing fewer memos than outputs partially mitigates that (by a significant amount).

OTOH I don't think that we should take a middle road where we include the complexity of having separate memo ciphertexts in the protocol but don't gain any immediate advantage from it. The change from Sapling's approach to the more general one would not be difficult to do later (perhaps at the same time as another tx format change, like TZEs). That said, I think it should be done now.

I will specify both options and then we can see the complexity/size/privacy trade-offs more clearly.

**Comment by steven-ecc** [comment]
Memo changes are out of scope for Orchard.
