### ISSUE TITLE
[Orchard] Decide how to handle shielded Orchard coinbase outputs

### ISSUE THREAD

**Issue by daira** [zcash/zcash#4974]
From Heartwood activation onward, we allow shielded Sapling coinbase outputs. We have never allowed spends of any kind in coinbase transactions.

In Orchard, shielded Spends and Outputs are combined into Actions. It therefore isn't obvious how to restrict spends. Requiring the nullifier to be a fixed, invalid value does not work, because Orchard relies on the nullifier of an Action description being unique in order to ensure that the corresponding output note's ρ value is unique.

We did not have this problem for JoinSplits (which also combine spends and outputs) because we do not allow JoinSplits at all in coinbase transactions. We do definitely want to support shielded Orchard coinbase outputs, though.

**Comment by str4d** [comment]
If we continue to require all note ciphertexts in coinbase transactions to be decryptable, then there is no problem: we simply require that `sum(OrchardOutputs) - orchardValueBalance = 0`. Since the Orchard balancing equation is `sum(OrchardSpends) - sum(OrchardOutputs) = orchardValueBalance`, this constrains `sum(OrchardSpends) = 0`.

**Comment by daira** [comment]
We added `enableSpendOrchard` to restrict coinbase spends. Otherwise everything here is the same as Sapling.
