### ISSUE TITLE
If I backup ancient wallet.dat ?

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#4982]
Can I restore the zaddress created after the back up, only with it ?

I try to import the wallet backup, but it did not work

**Comment by ucwong** [comment]
It seems the zaddress is not mine

**Comment by str4d** [comment]
Is this a Sprout or Sapling address?

- If it's a Sapling address, and the wallet was either new or used after Sapling activation before the backup was created, you'd then you could recover it by just calling `z_getnewaddress sapling` until you see it, because all Sapling addresses are derived deterministically from a seed.
- If it's a Sprout address (or a Sapling address created after a Sprout-era backup), then addresses generated after a backup was created cannot be recovered from that backup.
