### ISSUE TITLE
Implement new PRF layouts that don't truncate hash outputs

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#500]
All PRFs are constructed from the SHA256 compression function by, in some cases, truncating one of the input arguments, and using those bits to differentiate the PRFs. This might create a vulnerability (or proof failure), where for example when 3 bits are used to differentiate the PRFs, there will always be 8 input values that will produce the same result. If the security proof ever relies on a variable being the *unique* known input that would satisfy the PRF, then the security proof fails for the implementation.

One possible solution is make sure that all PRF input variables are truncated the same way every time they are used (or, better, never generate/keep those truncated bits in the first place).

**Comment by daira** [comment]
I was looking at this today. I don't like the security effect of the truncation at all.

In the original Zerocash protocol (without the proposed Faerie Gold fix), suppose that an attacker creates two coins with ρ differing only in the 3 bits that are truncated in the input to PRF<sup>sn</sup>. Then the coins will have the same serial number. This yields an attack with the same effect as Faerie Gold.

The currently proposed Faerie Gold fix (that requires ρ = CRH(φ, pourid)) happens to also block this variant provided it is infeasible to find collisions for trunc<sub>253</sub> . SHA-256. However that's a matter of luck: other variations of my [original proposed fix](https://groups.google.com/d/msg/zdep/IA1t2mKgKJE/fZlxHOfcKJ0J) might not have blocked this.

This also invalidates parts of the security proof. For instance, it is simply incorrect to assume that PRF<sup>sn</sup><sub>x</sub> is collision-resistant (as a function of the untruncated ρ).

Suppose the truncation had been the other way round, i.e. that ρ had been truncated in the input to CRH for InternalH, but not in PRF<sup>sn</sup>. In that case there would have been a double-spend attack: Create a coin c = (a<sub>pk</sub>, v, ρ, r). Spend it. Now spend it again, but in the computation of sn, flip one of the bits of ρ that is truncated for InternalH but not PRF<sup>sn</sup>. This transaction will be accepted because the coin commitment does exist in the commitment tree, but the serial number is different.

In general it is dangerous to have any variable truncated differently in different parts of the protocol, because there might be a tendency to view a value truncated by "only a few bits" as "almost as good as" the original value. Indeed this is encouraged by the notation which hides the fact that a truncation has occurred unless you dig into how the functions are instantiated. What we want is to reduce the cognitive load in analysing the higher level of the protocol by abstracting these functions as ideal hashes or commitment schemes, but we can't safely do that if they use different truncation.

**Comment by daira** [comment]
Note that the collision-resistance of trunc<sub>k</sub> . H cannot be proven from the collision-resistance of H, even when k is 1 bit. Counterexample:

  H(x) = firstbit(x) || CRH(trunc<sub>1</sub>(x))

(where trunc<sub>1</sub> drops the first bit). This is obviously collision-resistant if CRH is, but it trivially has collisions if the first bit of the output of H is truncated.

**Comment by daira** [comment]
I intend to change the spec to make sure that variables are always truncated in the same way. In practice this only results in a circuit change for the computation of InternalH from a<sub>pk</sub> and ρ.

**Comment by defuse** [comment]
Here's an illustration of the type of problem I had in mind:

> InternalH = CRH(256 bit a<sub>pk</sub> || 256-bit ρ)

> sn = PRF<sup>sn</sup><sub>a<sup>sk</sub></sub>(ρ) = CRH(256 bit a<sub>sk</sub> || 01 || Leading254(ρ))

If ρ = 01 || Leading254(ρ) (not sure how likely that is, but the sender could choose it to be such) then these look awfully similar and both a<sub>sk</sub> and a<sub>pk</sub> are getting hashed alongside the same thing. I'm not sure what the consequences of the above are, but it makes me worry we don't have good enough domain separation in our construction of primitives.

**Comment by zookozcash** [comment]
If we use BLAKE2 we can use its personalization input to guarantee domain separation for all domains. (If we use SHA256 we can add on an equivalent feature at a cost in performance and/or complexity and/or safety.)

**Comment by daira** [comment]
I propose that instead of truncating the right-hand side of each PRF input, we should be truncating the left-hand side (i.e. a<sub>sk</sub> or φ). The left-hand sides are just random values, not CRH outputs, and therefore there is no issue with having to assume collision resistance for truncated hashes.

**Comment by defuse** [comment]
+1 to truncating a<sub>sk</sub> and φ instead of the other things.

**Comment by daira** [comment]
https://github.com/zcash/zips/blob/406.viewing-keys.1/protocol/protocol.pdf includes a change to reduce the size of the left-hand side of the PRF inputs (a<sub>sk</sub>, a<sub>vk</sub>, or φ), rather than the right-hand side. Together with the fix for #738 (which is also on that branch), this removes all of the truncation of hash outputs, meaning that we only have to assume collision-resistance of the untruncated compression function.

**Comment by defuse** [comment]
I'm really happy with the changes @daira made, I think it's a big improvement.

**Comment by daira** [comment]
The proof failure will be documented in the next version of the protocol spec. (There were two errors related to this in the Ledger Indistinguishability proof for Zerocash.)
