### ISSUE TITLE
Design domain-separated hash for Merkle tree

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#501]
The zerocash protocol constructs PRFs from the SHA256 compression function. Those PRFs are independent from each other because some bits of the input are used to separate them ~~(or maybe not, see #499)~~. However, the Merkle tree uses the entire SHA256 compression function. So it's conceivable that the same SHA256 compression function input could arise in both a Merkle tree hash calculation and a PRF calculation.

Does this invalidate the security proof? What are any other security consequences?

**Comment by daira** [comment]
I believe this is fine provided that the Merkle tree is constant-depth. If we went to a variable-depth tree (#649) we would be have to be careful about how leaves are distinguished.

**Comment by defuse** [comment]
The Merkle tree needs to be proved secure when using just the compression function. That's probably trivial assuming the SHA256 compression function is collision resistant. See #792. Assuming it is, then I don't think the re-use of SHA256compress is a problem because no secrets are involved in the computation of the Merkle tree. Even if we used a totally different hash function for the tree, everyone can still compute the SHA256compress-based Merkle tree on their own if it would help them attack the system in any way. Also, the only things that are ever input to SHA256-compress by honest users are SNARK-verified commitments and SHA256-compress outputs. It's logically possible that there are interactions, but I highly doubt it, so we can close this issue.

**Comment by zookozcash** [comment]
There is discussion of this over on https://github.com/zcash/zcash/issues/792#issuecomment-204619370

**Comment by zookozcash** [comment]
In the course of arguing about [something else](https://github.com/zcash/zips/issues/36#issuecomment-204749715), I was reminded of a few things that bother me about this. This comment is not exactly a request to reopen this ticket, as much as an attempt to:

a. document my concerns for future reference,
b. motivate intense, focused crypto review of these specific parts of our current protocol, 
c. urge us to try to "steer further away" from these sorts of risks in _future_ versions of our protocols.

Okay, so there are two different — but potentially related — things that make me uncomfortable with this design.

1. Relying on the fixed-height of the tree to prevent "grafting/extension/leaf-node-pun"-type attacks. There are two problems with this:
  a. The vast majority of all Merkle Trees ever designed by first-timers have suffered critical vulnerabilities in practice, including the one designed/implemented by Satoshi in Bitcoin. The specific flaws that have killed all of those appear to be absent from our current construction to me, but I'm not 100% sure of that, because the current design imposes high cognitive load on me (see below). IMHO we are still "driving close to the edge of the cliff" with this design, even though I currently believe we're on this side of the line between survival and death.
    In contrast, when Brian Warner and I designed Tahoe-LAFS, we used explicit domain-separation for the [Merkle Tree](https://github.com/tahoe-lafs/tahoe-lafs/blob/40c78297e897bd38b389b7870f9d18f368035996/src/allmydata/hashtree.py) as well as for every other use of any secure hash function. This imposed a (tiny) performance penalty, but it made reasoning about hash function properties — including "grafting attacks" on Merkle Trees — easier to reason about. In other words, it imposed a performance penalty in return for imposing less of a cognitive load penalty.
  b. Cognitive load required for analysis. Kohno, Ferguson, and Schneier wrote in [Cryptography Engineering](http://www.amazon.com/Cryptography-Engineering-Principles-Practical-Applications/dp/0470474246/ref=sr_1_1?s=books&ie=UTF8&qid=1459654398&sr=1-1&keywords=cryptography+engineering) that *“security must be a _local_ property”*. In Tahoe-LAFS, the abstraction of domain-separated hash functions, and the fact that we _never_ used any _other_ abstraction in the design, means that we can conclude that our tree is safe from grafting attacks using very _local_ reasoning: simply based on the properties of the hash function. In contrast, in the current design of the Zcash Merkle-Tree, to be sure that we're safe from grafting attacks requires bringing in facts from slightly further afield — namely the fact that the Merkle Tree is fixed-height. Even if that's correct (I believe it is), and even if we remember to revisit this assumption if we change it (I believe we will), it still means that it imposes higher cognitive load on me to think about this, and it makes me worry that while my brain was busy keeping _two_ different facts in my head at the same time, I thus overlooked some other critical issue in this scheme. The way to overcome this (without changing the design), is for me and people like me to exert more cognitive effort and study the entire design closely. (And write analyses/reductions/security-proofs.) So this is why I'm writing a long comment about this tiny detail: I feel that the way we've done this is dangerous, based on empirical evidence about other similar designs having failed and based on my heuristics about crypto design, and now I think we have to compensate by that danger by more and more and more analysis.

2. Relying on the SHA-256-compression-function. This makes me uncomfortable. There is a way of thinking about this which is tempting but wrong, which is to think that full-SHA-256 is believed to be strong, and full-SHA-256 is closely related to SHA-256-compression-function, so SHA-256-compression-function is probably strong. I have related three concerns about this:
  a. In fact, part of the believed strength of full-SHA-256 comes from inputs outside of the attacker's control, including the leading IV, and SHA-256-compression-function is known to be weaker than full-SHA-256 (see e.g. http://eprint.iacr.org/2015/350, which for all I know is not even the state of the art in this sort of analysis).
  b. It's not clear to me that cryptographers have really spent a lot of effort attacking SHA-256-compression-function. Perhaps they have, but it is hard to be sure. The one or two papers I've seen on that subject (like the one above) might be outliers. Certainly in the SHA-3 era attacks on naked compression functions was de rigeur, but I'm not sure that tradition was ever — before, during, or after the SHA-3 contest — focused on SHA-2.
  c. SHA-256 itself doesn't seem to have that great of a security margin. I saw Bart Preneel speak at RSA Cryptographers Track in 2010, where he said that once the SHA-3 contest was concluded, cryptographers would return their attention to SHA-256, and then watch out! because they might break it. That hasn't happened yet. Is it because SHA-256 turns out to stronger than he was intimating, or because most of the cryptographers didn't actually focus their attention on SHA-256 after all? I wouldn't be surprised if, from the perspective of cryptographers, SHA-256 is old news that isn't that interesting to attack, because they don't imagine new designs would use it, much less use its compression function.

Here are a couple of related comments:
* https://github.com/zcash/zcash/issues/706#issuecomment-187807410
* https://github.com/zcash/zips/issues/36#issuecomment-204603515

To be clear, I do _not_ want to revisit [the decision to use SHA-256 (instead of e.g. BLAKE2)](https://github.com/zcash/zcash/issues/706) in this version of the protocol, but I want to:

a. Cause us and our security reviewers to view these designs as dangerous designs, charting a path through a field littered with the corpses of our forerunners. (Even though I believe this path is safe.)
b. Motivated future work to evolve the Zcash protocol and upgrade these crypto designs.

**Comment by zookozcash** [comment]
P.S. Yes, holding _two_ simple things in my mind at once counts as "high cognitive load" for me. Others perhaps have higher cognitive strength than I do, and they can hold more things in their heads at once before they start losing track of things. Even though we have a great advantage in having many such cognitively-strong people designing and reviewing this protocol, it is still safer the fewer things the protocol requires you to remember at once.

**Comment by daira** [comment]
I'm reopening this to spec out (as agreed in today's engineering meeting) a possible design that would add domain separation to the Merkle tree. We may or may not end up using it for 1.0.

**Comment by daira** [comment]
We should reconsider this if we move to Pedersen hashes (#2234) or a MiMC-based hash (#2233) for Sapling, especially if both the Merkle tree and the commitments switch to the new hash.

**Comment by daira** [comment]
We get this for free with Pedersen commitments, since we can use different generators for the different sets of hashes/commitments (and potentially also for levels of the Merkle tree).

**Comment by daira** [comment]
@zooko wrote:
> In fact, part of the believed strength of full-SHA-256 comes from inputs outside of the attacker's control, including the leading IV, and SHA-256-compression-function is known to be weaker than full-SHA-256 (see e.g. http://eprint.iacr.org/2015/350, which for all I know is not even the state of the art in this sort of analysis).

The Sprout circuit uses only SHA256Compress with the standard IV; free-start attacks are not possible.

**Comment by daira** [comment]
Using different domain separation for layers of the tree would clearly prevent hash-for-data substitution. On the other hand, for a constant-depth tree this shouldn't be necessary. Do we want to do this for Sapling?

**Comment by zooko** [comment]
I would feel better about explicit and systematic domain separation. To me,
that's the right way to do things. The only reason not to do it is if you
don't have time to do things the right way or if (rarely) there are
substantial performance costs.

**Comment by daira** [comment]
Well, using distinct domain separation for each layer of the tree does have a measurable cost in memory usage, when computing the tree hashes outside the circuit. You need to store 127 generators per layer, so for 29 layers that would take 32 \* 127 \* 29 = 117856 bytes. This also makes it less practical to fully precompute all of the window entries, because then the table size would be multiplied by 8 in the case of 4-bit windows with the negation trick. That is, fully precomputed window tables for the whole tree of depth 29 would take 8 \* 32 \* 127 \* 29 = 942848 bytes. This compares with 8 \* 32 \* 127 = 32512 bytes for fully precomputed window tables when there is no per-layer domain separation.

For a memory-constrained platform, we'd much prefer to have a table size of ~3.97 KiB (minimal) to 31.75 KiB (fully precomputed) than a table size of ~115 KiB (minimal) to ~921 KiB (fully precomputed).

**Comment by ebfull** [comment]
Can we not achieve domain separation by adding a different but fixed point to the result of the hash depending on its depth? (Perhaps a partial evaluation of the hash function.)

**Comment by daira** [comment]
That's a good point. There are two ways of doing this:
1. Reserve a prefix that is a multiple of the window size (say 8 bits which is 2 windows) to encode the layer number.
2. Apply GH to an encoding of the layer and add that to the hash output.

These both have zero cost in the circuit, because the fixed point can be added to every entry of the first window. Cryptographically there isn't much to choose between them; 1. might be slightly easier to analyse since it's not actually changing the underlying hash.

**Comment by daira** [comment]
I'm going to specify the first option, unless there's any objection. The layer number, counting from zero at the root (as in section 3.6 of the protocol spec), will be expressed as an 8-bit big-endian bit string and prepended to the hash input.

**Comment by daira** [comment]
For a constrained-memory implementation you could also store the generators in Montgomery form (with z = 1) and recover the y-coordinate using the [Okeya–Sakurai](https://github.com/zcash/zcash/issues/2277#issuecomment-346850979) method. Regardless, the memory usage is fine with the prefix approach.

**Comment by ebfull** [comment]
> These both have zero cost in the circuit, because the fixed point can be added to every entry of the first window.

Can we really do this with conditional negation involved?

**Comment by daira** [comment]
@ebfull wrote:
> Can we really do this with conditional negation involved?

You're right, that introduces an annoying wrinkle. We can add a constant point instead (adding it inside the first segment costs 3 constraints).

**Comment by daira** [comment]
Since we're likely to be using 3-bit rather than 4-bit windows (for efficiency), we'll use a 6-bit prefix. This still allows for 64 layers which is more than sufficient.

**Comment by daira** [comment]
The layer input is numbered starting with 0 at the leafmost layer, which might make transplanting the tree into a deeper tree easier.

**Comment by daira** [comment]
This is designed and included in the 2018.0-beta-14 Sapling spec.
