### ISSUE TITLE
Some ConnectTip() "bench" log prints (LogPrint()) are incorrrect

### ISSUE THREAD

**Issue by LarryRuane** [zcash/zcash#5164]
This is a low-priority bug.

PR #4427 slightly broke one of the `bench` (benchmarking, timing) debug prints. This commit https://github.com/zcash/zcash/commit/2013b35e3ef1588547a35825dcdf73e202d135b2 from that PR moved the call to `ReadBlockFromDisk()` out of  `ConnectTip()` (to the caller) but left the benchmarking time measurements around that call unchanged. As a result, we now have:
```
    int64_t nTime1 = GetTimeMicros();
    // Apply the block atomically to the chain state.
    int64_t nTime2 = GetTimeMicros(); nTimeReadFromDisk += nTime2 - nTime1;
```
It's unclear (to me) what's the best way to fix this. It's easy to also move the time measuring code (which sets `nTime1` and `nTime2`) and associated `LogPrint("bench", ..)`  to the calling function, but the rest of `ConnectTip()` references `nTime1` and `nTime2`. Passing them as arguments to `ConnectTip()` is too messy a solution, IMO.

**Comment by str4d** [comment]
The only places that `nTime1` is used are to calculate the time to read a block from disk, and the total block connection time. Since we only call `ConnectTip` from `ActivateBestChainStep`, I think we can just move those two benchmarking measurements into the caller. In particular, I think it's fine for the total measured time per block to be slightly longer than the sum of its listed parts.
