### ISSUE TITLE
How can I delete the created wallet and restore the wallet from mnemonic phrase ?

### ISSUE THREAD

**Issue by zababurinsv** [zcash/zcash#5249]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Example: 
I am download Zecwallet.Fullnode-1.6.2  and node.
I have mnemonic phrase for restore wallet.
But when I launch the wallet.
I immediately have a new wallet created.

## Describe the solution you'd like
How can I delete the created wallet and restore the wallet from mnemonic phrase ?

## Alternatives you've considered
I have 3 directories.
.zcash
zcash
.zcash-params

I removed wallet.dat from the .zcash directory but it didn't help.

**Comment by nuttycom** [comment]
This would be a better issue for https://github.com/ZcashFoundation/zecwallet - zcashd itself does not perform key derivation based upon a mnemonic phrase; the ZIP-32 functionality is only implemented for light wallets. You might want Zecwallet-Lite instead of the full-node Zecwallet, if you have a mnemonic phrase you want to restore from?

**Comment by zababurinsv** [comment]
Yes. I have a mnemonic phrase.
I'll ask them now.
But I took another wallet and got a private key.

How can I use it to connect to a wallet instead of another ?
