### ISSUE TITLE
UX: How get information from zcashd ?

### ISSUE THREAD

**Issue by zababurinsv** [zcash/zcash#5250]
I try get balance and info about address 

```
 t1gyJeWownZrpstwETf9R7GYSsQGUs93X7r 
```
In explorer i see what there is money on the address
[Explorer](https://explorer.zcha.in/)

i have zcashed on local machine.

I want get this balance and information that i see in the explorer but from my node

```
    "zcash:getaccount": "/home/zb/zcash/src/zcash-cli getaccount \"t1gyJeWownZrpstwETf9R7GYSsQGUs93X7r\"",
    "zcash:getinfo": "/home/zb/zcash/src/zcash-cli getinfo",
    "zcash:getbestblockhash": "/home/zb/zcash/src/zcash-cli getbestblockhash",
    "zcash:z_getbalance": "/home/zb/zcash/src/zcash-cli z_getbalance \"t1gyJeWownZrpstwETf9R7GYSsQGUs93X7r\"",
    "zcash:getaddressmempool": "/home/zb/zcash/src/zcash-cli getaddressmempool '{\"addresses\": [\"t1gyJeWownZrpstwETf9R7GYSsQGUs93X7r\"]}'"

```

I use [Zcash 4.4.0 RPC docs](https://zcash-rpc.github.io/getbalance.html)

How can i see info with zcashed?

**Comment by nuttycom** [comment]
The answer to this depends upon exactly what your setup is and what you're attempting to do. Zcashd contains an embedded wallet, but it does not provide full explorer functionality, so the answer here will depend upon whether the address you're wanting to obtain a balance for is controlled by the zcashd embedded wallet or not. 

If the wallet controls the address, you can obtain a balance by summing the unspent outputs received by that address, which you can obtain using the `listreceivedbyaddress` RPC call. There is not a direct mechanism to obtain a balance on a per-address basis, because the wallet (as with the Bitcoin embedded wallet) only provides balance information at an account level, not an individual address level. So it's a bit of work to obtain the balance.

If the wallet does not control the address, you will need to run the node and sync the chain using the these flags:
```
./src/zcashd -insightexplorer -experimentalfeatures -txindex
```
