### ISSUE TITLE
zcashd 4.5.0 getbalance inconsistent with listunspent

### ISSUE THREAD

**Issue by yaccz** [zcash/zcash#5325]
[zec_getbalance_4.5.0.txt](https://github.com/zcash/zcash/files/7231164/zec_getbalance_4.5.0.txt)
[zec_zec_getbalance_4.4.1.txt](https://github.com/zcash/zcash/files/7231165/zec_zec_getbalance_4.4.1.txt)
See the attached sscce test reports.

Additional information:
- the getbalance call seems to return correct information after one more block is mined
- the utxo listed by listunspent that does not contribute to the getbalance value is spendable via z_sendmany as usual with minconf=0 without the additional block mined.
- z_getbalance does not seem to be affected

**Comment by daira** [comment]
Just to check, are you overriding the default (true) value of `-spendzeroconfchange`?

**Comment by str4d** [comment]
We have identified the bug. In 4.5.0 we backported upstream Bitcoin Core's PRs to remove accounts from the RPCs. As part of that, `getbalance` was changed to use `CWallet::GetBalance` instead of `GetAccountBalance`. `CWallet::GetBalance` calls `CWalletTx::IsTrusted` (which `getbalance` was not previously calling via any pathway), and _this_ exposed a bug in the wallet that I think has existed since before Zcash launched: `CWallet::IsFromMe(CTransaction)` was updated to check for Sprout and Sapling spent notes, but `CWalletTx::IsFromMe` was not.
