### ISSUE TITLE
Question, disk space needed?

### ISSUE THREAD

**Issue by tongokongo** [zcash/zcash#5425]
Hey, if I'd like to run a zcash node (full), how much disk space would I need? For example, the current bitcoin size with tx index enabled is about 470GB.

I'd assume to check: 
`du -dh 1 .zcash`

**Comment by LarryRuane** [comment]
Those command-line options didn't work for me (running Ubuntu), but I think this answers your question:
```
$ du -sh ~/.zcash
63G	/home/larry/.zcash
```
To be a little more accurate, we should subtract the testnet space:
```
$ du -sh ~/.zcash/testnet3
8.1G	/home/larry/.zcash/testnet3
```
So, for me, it's around 63G - 8G = 55 GB. But this is an overstatement, because I do have `txindex` enabled, plus another option that allows the node to support the Insight block explorer, `insightexplorer`, which stores more, similar to but beyond `txindex`. I don't know how much more space that option uses, but I do have notes from a couple of years ago saying that `txindex` and `insightexplorer` together approximately double the size of the data directory (compared with not having either of those). So maybe around 28 GB (?). My guess is it's a little more than that, maybe 35 G.

@mdr0id, do you have some better numbers?

By the way, just for another data point, I happen to have a bitcoin full node running with `txindex`, and its data directory size is 441GB, so slightly less than yours.

**Comment by tongokongo** [comment]
Thanks, it's all I needed, I assume txindex by default :)
