### ISSUE TITLE
Restrict number of PourTx in a transaction or block

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#544]
To avoid CPU exhaustion attacks.

**Comment by nathan-at-least** [comment]
This is good to track.

FWIW: I'm interested in the potential for a more general "validation cost" cap, rather than many piecemeal DoS limits, but we don't have a ticket or relevant proposal yet.  Until there's something tangible, we do need some kind of limits such as proposed here.

**Comment by ebfull** [comment]
See also #765.

**Comment by nathan-at-least** [comment]
We've generally decided that the "incidental" limit of ``MAX_BLOCK_SIZE`` will be sufficient, so we'll rely on that instead of introducing a new protocol-level resource constraint.

Note that this decision means if we ever increase ``MAX_BLOCK_SIZE`` there's a new resource scaling issue that upstream Bitcoin does not have, so we need to remember that.
