### ISSUE TITLE
Make PARAMS_DIR of fetch-params.sh configurable from CLI

### ISSUE THREAD

**Issue by utdrmac** [zcash/zcash#5503]
When using fetch-params.sh the download location is **hardcoded** and cannot be changed without modifying the script. Please allow the download location of the parameters to be changed by flag to script, or via env variable. Can't the script simply check first if the env $PARAMS_DIR is set and if not, then use the defaults?

**Comment by sellout** [comment]
I think this is a good idea. However, I think it should be done with/after #4491 (which folds fetch-params into zcashd, rather than a separate step to run). That way we don’t have to use an environment var to keep in sync between the apps, but can implement this as a `zcashd` config file entry and/or command-line option.

**Comment by daira** [comment]
This would be mostly obviated by #3933 / #6661. For the remaining optional use of `sprout-groth16.params` there is not sufficient justification to implement this issue.
