### ISSUE TITLE
If a legacy mnemonic seed is present in a zcashd wallet, derive the mnemonic seed using the legacy seed as entropy.

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#5572]
Previously, we have made the guarantee that if a user has backed up the legacy HD seed, that all Sapling and later addresses produced by the wallet could be recoverable based upon that seed. Currently we are always producing the mnemonic from system randomness, but we can maintain our previous guarantee by simply using the legacy seed as entropy instead if it exists.

**Comment by str4d** [comment]
@nuttycom noted that HD derivation for accounts is fallible (both because BIP 44 derivation is fallible due to how BIP 32 is defined, and Orchard spending key derivation is fallible due to how the Orchard key tree is defined). This means we can't assume the legacy HD seed will always produce an account 0.

In a pairing (that also led to us discovering https://github.com/zcash/orchard/issues/294), @daira and I went through the constraints we have:
- The legacy HD seed was always generated by `zcashd` to be 32 bytes (and required it to be at least 32 bytes).
- BIP 39 requires that entropy is at most 32 bytes.
- What we want to ensure is that someone who backed up the legacy seed, continues to receive the guarantee that Sapling spending keys generated via `z_getnewaddress` will be derived from that legacy seed.
- It would also be nice to ensure that someone who backed up the legacy seed, and then heard "all you need to back up is this mnemonic phrase" and thinks "great, I can forget about my legacy seed backup", continues to be able to re-derive their older Sapling spending keys.

In order to achieve all these properties, we propose the following approach:
- If the legacy seed is not 32 bytes, abort the node.
  - This would only occur if someone manually rebuilt `zcashd` to use a larger seed size. We never exposed a config option for this, and do not need to support it; it's fine to require that user to create a new wallet.
- Take the legacy seed as entropy, derive the mnemonic phrase, derive the new seed from it, and check we can derive the accounts we want to always exist.
- If the accounts we need don't exist, increment the first byte of the legacy seed by 1, and retry.
  - This is equivalent to interpreting the legacy seed as the little-endian encoding of a 256-bit integer, and adding `counter % 256` to it.
  - If we increment 255 times and still cannot derive the accounts we want to always exist, tell the user they should buy a lottery ticket (they just hit a negligible case 256 times in a row!) and abort the node.

This is a bit ugly, but satisfies all the desired properties. If a user wants to recover their legacy Sapling spending keys, they take the mnemonic phrase, convert it back into entropy, and then trial-derive Spending keys from it. If the Spending keys don't have the expected chain history, decrement the first byte and retry.

**Comment by daira** [comment]
> This is equivalent to interpreting the legacy seed as the little-endian encoding of a 256-bit integer, and adding counter % 256 to it.

No it isn't. The first byte wraps at 256, so sometimes you'll end up decreasing the 256-bit integer; that's not equivalent to addition of a non-negative value.
