### ISSUE TITLE
[Sapling] diversified addresses

### ISSUE THREAD

**Issue by daira** [zcash/zcash#570]
It is an advantage of Zerocash that even when a payee uses a single address public key, some level of payer anonymity is retained. However the payers can compare the public keys they were given and determine that they are paying the same entity.

It would be nice if there were a way to diversify public addresses so that they cannot be linked, but retain a single private key for ease and efficiency of address management. In particular, the key-private decryption key would be the same for a given set of diversified addresses, so that it would be possible to scan the blockchain for buckets encrypted to any of the addresses in that set, simultaneously.

One way of doing that is:

Let S<sub>id</sub> be a diversifier, which must be long enough that it is unlikely to collide between two diversified addresses _in the same set_ when chosen randomly.
Let GH ("group hash") be a hash function that takes a diversifier into a random element in an elliptic curve group (with unknown exponent). Let CRH be a collision-resistant hash. 
Let a private key be (a<sub>sk</sub>, sk<sub>enc</sub>) generated as in the current Zerocash protocol.
Let a public address be (S<sub>id</sub>, a<sub>pk,id</sub>, pk<sub>enc,id</sub>) where  pk<sub>enc,id</sub> = sk<sub>enc</sub> . GH(S<sub>id</sub>) and a<sub>pk,id</sub> = CRH(S<sub>id</sub>, a<sub>sk</sub>).

Other changes are obvious: we use GH(S<sub>id</sub>) in place of the base point of the curve, and we include S<sub>id</sub> in a note plaintext so that we can check the corresponding a<sub>pk,id</sub> when given a<sub>sk</sub>.

Assume that GH is an ideal "random" hash into the group; then, the security is dependent on being unable to find sk<sub>enc</sub> even when given multiple pairs (G, sk<sub>enc</sub> . G) for random group elements G. This is a nonstandard assumption, but may be reasonable and is certainly not obviously bad.

[Edit: it actually depends on not being able to link such pairs, which is a stronger assumption than being unable to find sk<sub>enc</sub>, and at least as strong as DDH.]

**Comment by zookoatleastauthoritycom** [comment]
`It is an advantage of Zerocash that even when a payee uses a single address public key, some level of payer anonymity is retained.`

Instead of writing "some level" here, let's be specific about what kind of privacy is provided. (Also, could we avoid the word "anonymity". I know it is a standard jargon term in our particular niche of cryptography/computer-science, but it is technically incorrect and pejorative when interpreted as normal English.)

The specific privacy I mean is: it is an advantage of Zcash that even when a payee re-uses a single address public key, no information linking separate transactions to that address is publicly visible in the blockchain.

Now the issue that this ticket is about can be clearly seen as: "What about linkage from other sources than what is publicly visible in the blockchain? For example, two different payers were provided with the same recipient address, they compare notes and realize they're both paying the same person. Or, an auditor who is granted view-keys enabling them to see multiple (not publicly visible) transactions in the blockchain can identify that they went to the same public key."

This is definitely not a feature for Zcash 1.0.

The main concern I have about the proposed solution is that I think it complicates UX. Daira thinks otherwise, and she suggested in email that we move the discussion about the UX consequences of this to here so over to you, Daira!

**Comment by daira** [comment]
I still intend to get around to the UX discussion, but for now I just want to not that this doesn't conflict with viewing key support. There would be one viewing key and an arbitrary number of payment addresses for each spending key.

**Comment by daira** [comment]
Note that this is compatible with collapsing the (a<sub>sk</sub>, a<sub>pk</sub>) and (sk<sub>enc</sub>, pk<sub>enc</sub>) key pairs into one key pair, if Pedersen commitments are used in the circuit.

**Comment by ebfull** [comment]
We need something like this to solve a performance bottleneck in our system -- for every incoming transaction, we run `Receive` for each spending key.

**Comment by daira** [comment]
I thought there might be a conflict between key diversification, key privacy, and partial quantum-resistance (see #805), but it turns out not to be a problem.

Our note current encryption has the nice property that if the address is kept secret, the encryption scheme is (conjectured to be) post-quantum secure. Informally, we can argue this as follows: the public key pk<sub>enc</sub> is an input to the KDF &mdash; so if an attacker does not know the public key (which is part of the address), they cannot calculate the KDF output, even if they can break Curve25519. Nor can they obtain information about pk<sub>enc</sub> from the ciphertext(s), because the overall encryption scheme is post-quantum key-private, when considered as a *symmetric* encryption scheme with key pk<sub>enc</sub>. Note that the output of the Curve25519 key exchange is only used via the KDF. So if the KDF hides its unknown inputs, then it doesn't reveal any useful information about which pk<sub>enc</sub> has been used. This assumes that public keys have sufficient entropy.

However, it turns out that including the public key in the KDF input is not essential to get this property. Suppose that pk<sub>enc</sub> were not included in the KDF input, and consider the position of an attacker who can break Curve25519 but not the KDF. The only unknown input to the KDF is sharedSecret, which is Curve25519(esk, pk<sub>enc</sub>). The attacker can find esk as the discrete logarithm of epk. However, Curve25519<sub>esk</sub> acts as a permutation on the space of valid public keys. So under plausible assumptions about the KDF (specifically that it acts as a PRF keyed by sharedSecret), when pk<sub>enc</sub> is not known, the attacker still cannot gain information about it nor break the encryption.

(The recipient calculates sharedSecret as Curve25519(sk<sub>enc</sub>, epk), not as Curve25519(esk, pk<sub>enc</sub>). However, chosen ciphertext attacks that manipulate epk also fail provided that the KDF acts as a PRF keyed by sharedSecret.)

**Comment by daira** [comment]
There unfortunately *is* a conflict between key diversification and forward security as described in #2044 (or at least the proposed way of achieving it using Hierarchical Identity-Based Encryption).

HIBE schemes like [Gentry–Silverberg](https://eprint.iacr.org/2002/056) can, at first sight, be adapted to use key diversification. (In the case of Gentry–Silverberg, if P<sub>0</sub> is set to GH(S<sub>id</sub>) ∈ G<sub>1</sub>, the scheme still encrypts and decrypts correctly with the same private keys.)

However, the existence of the pairing means that the assumption of unlinkability between keys (G, sk<sub>enc</sub> . G) cannot hold. Indeed we can test whether (P<sub>1</sub>, Q<sub>1</sub>) and (P<sub>2</sub>, Q<sub>2</sub>) are equivalent keys just by checking whether e(P<sub>1</sub>, Q<sub>2</sub>) = e(Q<sub>1</sub>, P<sub>2</sub>), since both sides are e(P<sub>1</sub>, P<sub>2</sub>)<sup>sk<sub>enc</sub></sub>.

**Comment by daira** [comment]
It might be possible to get a secure scheme based on a variant of the [XDH assumption](https://en.wikipedia.org/wiki/XDH_assumption), but I'd be wary of that: XDH is clearly necessary but may not be sufficient.

**Comment by burdges** [comment]
I haven't looked at the context here, so I should probably keep quite, but..  

I donno if you need to think in terms of HIBE here, maybe you just want that BLS signatures can be deformed by multiplying the public key and either the signature or the base point by a secret.  Deformed BLS signatures have exactly the same problem though.  

XDH cannot help if you need to deform the signature, as the the deforming scalar appears on both sides of the pairing, but if deforming the base point suffices then that should work, as the base point lives on the same side as the public key in a BLS signatures. 

Also, a quantum computer can free move scalars from one side of the pairing to the other, breaking XDH.

**Comment by daira** [comment]
@burdges We need to deform the public keys themselves, because we're giving out public keys corresponding to a given spending key in multiple contexts that should not be linkable. This is for ECIES-style encryption, not signatures.

I know that quantum computers would be able to break this unlinkability. (The partial resistance to quantum attacks referred to above is only for the case where none of the public keys corresponding to a spending key are known.)

**Comment by daira** [comment]
Aha, this paper by Boyen and Waters seems to discuss the issues: [https://eprint.iacr.org/2006/085](Anonymous Hierarchical Identity-Based Encryption
(Without Random Oracles))

**Comment by nathan-at-least** [comment]
We want to review many use cases and their usability, as well as which other features interact. Here's a quick brainstorm:

- how is this similar or different from payment requests?
- how does this impact forward secrecy?
- what does this mean for backup/restore?
- how can users tell 'how many root secrets' are in a wallet? (ie: what if they create K diversified public keys with a wallet, and then later import a new private keys that has J different diversified public keys? How do we explain or represent that to users?)
- does it make keys larger (or smaller)?

**Comment by nathan-at-least** [comment]
@str4d pointed out in a meeting that this UX might be similar to 'stealth addresses' which are adopted elsewhere in cryptocurrency space, so we should look into how well those work out.

**Comment by nathan-at-least** [comment]
@ebfull points out in a meeting that if 1-secret-to-N-addresses is confusing UX, then even if the protocol supports it, we could make our 'basic user-friendly wallet' maintain a 1-1 mapping for cognitive simplicity, leaving the advanced feature for advanced users.

**Comment by tromer** [comment]
Which of the use cases would be adequately solved by keeping the current 1:1 mapping, and introducing a convention that Zcash address `zc123...789#ticket2572` means "send to address `zc123...789` with encrypted memo saying `ticket2572`"? Coupled with suitable selective disclosure.

**Comment by ebfull** [comment]
@tromer One remaining use case is the ability to effortlessly separate psuedonyms (your payment addresses) without additional spending keys -- which adds performance and operational security overhead, as well as UX complexity due to the need to send payments from multiple spending keys to compensate (which themselves may be distinct balances intended to be kept separate).

**Comment by tromer** [comment]
@ebfull: if you use a single spending key, and publish same address with different `#` decorations as above, then those problems don't arise. And this looks adequate for some use cases, like exchanges. Of course, your payment addresses are then trivially linkable, so the question is, when is address linkability (not transaction linkability!) a problem?

**Comment by nathan-at-least** [comment]
@tromer the feature you described is distinct, and I call that 'payment request': #2278. (Tangential: #1344)

I think the similarities and differences between diversified pubkeys (DPK) and payment requests (PR) are:

- A PR is distinguished from an address (unless we also do #1344). Software that handles addresses can't necessarily handle PRs. By contrast DPK implies a new address format, all compliant address-handling software would handle them.
- Multiple PRs for the same address are linkable to each other, whereas multiple DPK addresses for the same secret key are unlinkable.
- A PR is linkable to the associated address.
- PR only requires coordination between payer/payee, and doesn't need any blockchain protocol support whatsoever. Thus very flexible, but also different clients may not support different extensions. I actually don't know if DPK has any observable impact on the consensus protocol, yet.
- Given the last bullet, PR can be deployed today, even without our awareness (eg: by a wallet vendor), whereas (I assume) DPK requires protocol changes and thus visible to all conforming wallets.
- Both would improve scan performance, since they both would rely on a single viewing key.

**Comment by tromer** [comment]
Agreed.
The most essential difference is address linkability, so I still wonder about use cases that need address linkability _and_ so many addresses that performance/opsec are an issue. If none come up, then it's tempting to hold off on the delicate DPK crypto, and focus on payment requests (which are needed for other uses too).

**Comment by daira** [comment]
Note that a necessary condition for unlinkability of diversified addresses in this scene is that the curve has [very high embedding degree, close to the same bit length as the curve order](https://safecurves.cr.yp.to/transfer.html). Otherwise, you can use a pairing on the curve to recognize when two (GH(d), pk<sub>enc,d</sub>) pairs are in the same discrete-log relation, and therefore have the same private key. (Pairings are not only defined for "pairing-friendly" curves; mathematically they're always defined, just hopelessly infeasible to compute if the embedding degree is large enough.)

**Comment by ebfull** [comment]
I think this should be included in Sapling, and here's why.

There is currently a fundamental performance/privacy tradeoff in our system: users that wish to receive on multiple addresses end up paying quadratic cost in the number of transactions on the blockchain.

Why do users want to receive on multiple payment addresses?

1. Some users _need_ to use different addresses to protect their privacy. I don't want to give business A the same address that I give business B. If they collaborate, they link my identity.
2. Enterprise users (for example, exchanges) desire the ability to separate depositor funds into different payment addresses, so that there are no questions about custody or liability. One enterprise partner told us explicitly that when senders need to place the depositor's account in the memo/label field, they sometimes fail to do so or enter in the wrong information, leading to support headaches. I can imagine this becomes a _legal_ problem in other enterprise contexts.
3. Having the ability to receive on multiple addresses with one common spending key may be of security benefit to some users. Having the ability to receive on multiple addresses with one common viewing key may be a crucial accounting and auditing tool.
4. Some users will try to make multiple addresses because that's what they're used to in other systems. We need to educate users that this comes at a performance cost, or take away their ability to do it.

I agree that we should be methodical in our feature selection to reduce complexity and risk.

However, (1) and (4) above are not speculative. These are things we already know are problems. We're generally conservative about privacy: we don't need to do use-case analysis to justify encrypting transaction values. Solving the above privacy problems should be a priority unless we have evidence that they aren't significant.

Address diversification accomplishes all of these goals, and is the only thing that we know of that does. And it is one of the least expensive and least complicated things we can add to the protocol. Currently, you cannot solve all of the above problems without paying:

* a performance penalty
* a UX penalty (you now need the ability to spend "from" multiple payment addresses or coalesce funds)
* a security penalty (you currently need to have custody over multiple secrets to have multiple payment addresses)

Users that are currently giving the same address to multiple parties could be doing so for performance reasons (bad) or because they don't even realize the privacy risk (worse). Thus there is sufficient justification that the ability to have multiple payment addresses for a given spending key should be part of our users' mental model.

Speaking of which, it looks trivial to change our [concepts](https://github.com/zcash/zcash/wiki/Concepts-in-Zcash) so that there isn't a 1:1 mapping and honestly the explanation seems simpler to me when you do it. If you disagree, remember that we can make this available to power/enterprise users without disturbing the existing mental model, since it is an entirely local effect.

**Comment by radix42** [comment]
I have encountered instances of all of items 1-4 above in various numbers, and am completely behind this line of argument in favor of them asap.

**Comment by daira** [comment]
A recent Monero report describes a similar feature, which they call subaddresses: https://www.reddit.com/r/Monero/comments/766h0y/monero_research_lab_whitepaper_subaddresses/

Their scheme relies on unlinkability of (r.A, r.B) for random scalars r in the same way that ours does. Unlike our scheme it does not use hashing into the group (it's similar to what I first came up with at the summit at the Tor offices in Berlin in January 2016), and as a result it requires addresses that are two group elements in length, rather than one plus a short diversifier.

**Comment by daira** [comment]
I considered renaming these to "subaddresses" to match Monero. However, there's no real sense in which these are subordinate to a some master address: in Sapling, all addresses are diversified addresses and they are all at the same level.

**Comment by daira** [comment]
I'm reconsidering what length we need for the diversifier. The [current definition of GH](https://github.com/zcash/zcash/issues/2635#issuecomment-361263282) returns non-⊥ for a proportion 8.s / 2<sup>256</sup> of diversifiers. This subtracts ~1.14 bits from the effective diversifier space, e.g. if ℓ<sub>d</sub> is 80 bits then the effective diversifier space is ~78.86 bits.

The number of diversifiers R needed for the collision probability to reach p, is bounded below by sqrt(2.p.R). E.g. for p = 2<sup>-25</sup>, sqrt(2.p) is 2<sup>-12</sup>, so we can generate 2<sup>78.86/2 - 12</sup> ~= 2<sup>27.4</sup> addresses before the collision probability exceeds p. (Adjust according to your opinions on acceptable collision probabilities.) This is not quite as conservative as I'd like; maybe we should bump the diversifier length up to 96 bits?

Note that a Bech32 Sapling z-address with 80-bit diversifier only just fits under an 80-character line length ([78 characters](https://github.com/zcash/zcash/issues/2528#issuecomment-317168012)). A 96-bit diversifier would put it up to 81 characters. On the other hand we could drop the version byte, relying on the human-readable prefix for versioning instead; that would allow a 88-bit diversifier in 78 characters.

**Comment by daira** [comment]
We (@sean, @str4d and I) decided to drop the internal version byte and make diversifiers 88 bits.

**Comment by daira** [comment]
For exchanges that use this feature to distinguish user addresses while reducing scan overhead, they can keep track of distinguishers in a database and make sure they don't repeat, regardless of the birthday bound.

**Comment by daira** [comment]
Diversified addresses are fully designed and included in the Sapling spec. We'll need an implementation ticket, but this one can be closed.
