### ISSUE TITLE
`mapSaplingIncomingViewingKeys` is not being filled correctly on startup

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#5735]
@daira started a fresh 4.6.0 testnet node to generate a legacy Sapling address (bound to a legacy HD seed), and upon restarting with 4.7.0-rc1 discovered that the address did not show up in `z_listaddresses`, `listaddresses`, or `z_exportwallet`. We dug into this in a pairing, and established that the cause was `mapSaplingIncomingViewingKeys` not being populated on startup. `mapSaplingFullViewingKeys` _was_ being populated, enabling a received transaction to be detected, and once that had occurred, the address started appearing in the RPCs, and continued to appear after restart.

When @nuttycom added UA Sapling storage support, he removed the legacy "always add the default Sapling address to the keystore" logic, because we don't want that behaviour for UAs. For UAs this works out fine, because for every generated address we store a UA metadata entry in `wallet.dat`. However, for legacy Sapling addresses, we were relying on two implicit sources:
- The default-added default address.
- Any address detected via a transaction (logic we added back when we added Sapling, to ensure that even though we didn't support generating diversified Sapling addresses, we ensured that we handled detecting them correctly).

By removing the default mapping, we removed the ability for the wallet to list legacy Sapling addresses until at least one transaction was found. We need to re-introduce this behaviour, gated on the corresponding Sapling IVK not being part of a UFVK.

**Comment by nuttycom** [comment]
The issue here appears to stem from the fact that in 4.6.0 and earlier, `WriteSaplingZKey` was being called on generation of a new address, but `WriteSaplingPaymentAddress` (which we now depend on) was not - this was only called on IVK import. I think the fix will be, in LoadCaches:
* for each Sapling key associated with the legacy HD seed, if no corresponding address exists in the keystore, add it using `AddSaplingPaymentAddress`. This will cause it to be properly persisted to the wallet database.

**Comment by daira** [comment]
Fixed by #5742.
