### ISSUE TITLE
Remove `zcutil/build.sh` and incorporate those changes into autoconf/automake system.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#58]
Right now in the [`get_being_strange`](https://github.com/Electric-Coin-Company/zerocashd/tree/get_being_strange) branch of `zerocashd` we've added a [`build.sh`](https://github.com/Electric-Coin-Company/zerocashd/blob/get_being_strange/build.sh) script.

This is a hack since we don't understand the Gnu autoconf/automake layer well yet.  Instead, let's learn how that build system works and incorporate the changes of `./build.sh` into it.

Note, the issue in #57 may be addressed before or after this ticket is closed, regardless of where the solution lives (autoconf/make or `./build.sh`).

**Comment by ebfull** [comment]
@nathan-at-least Can you confirm that this ticket is obsolete?

**Comment by daira** [comment]
This is still an issue.

**Comment by daira** [comment]
> Right now in the get_being_strange branch of zerocashd we've added a build.sh script.

Ah, nostalgia. (Of-topic: did we ever work out what "get being strange" referred to?)

**Comment by daira** [comment]
The existence of a ``Makefile`` that doesn't Just Work, is an attractive nuisance: https://github.com/zcash/zcash/issues/2330#issuecomment-297870285

**Comment by radix42** [comment]
I think that this ticket isn't that far away, adding a target "depends" to the toplevel Makefile that is invoked when you "make all" that builds dependencies will help a lot (that's on my TODO now)

**Comment by str4d** [comment]
Steps that need to happen:

- [ ] Move our standard `CXXFLAGS` into `configure.ac`
- [ ] Move our default `HOST`, `BUILD` and `PREFIX` into `configure.ac`
- [ ] Add a `depends` target to the top level `Makefile`.
- [ ] Ensure that all existing `build.sh` have corresponding `./configure` flags (ie. `--disable-mining` instead of `--enable-mining=no`, so flags reflect the defaults)
- [ ] Replace `build.sh` with a simple wrapper for backwards-compatibility.

**Comment by str4d** [comment]
Most of this has been completed over the last few years. There are some more changes that I will make after #4222 is merged.

The one annoying piece still to figure out is how to reliably pass the `config.site` from the depends system through to `./configure`. Upstream doesn't have anything for this because they only use the depends system for Gitian builds (in which they hard-code the path). We use it all the time to ensure that all users are building from the same dependencies, and ideally it should be used when users build without `build.sh`. The two places we need to pass it in are:

- when the user manually runs `./configure` (we could have the build instructions specify `CONFIG_SITE`, but that's not very usable).
- during [automatic rebuilding of build system files](https://www.gnu.org/software/automake/manual/html_node/Rebuilding.html) (hopefully the solution to the first part addresses this as well, but if not then we need to hide the environment variable somewhere in either `config.status` or the Makefiles).

**Comment by str4d** [comment]
As of now, `build.sh` is effectively:
```bash
BUILD="$(./depends/config.guess)"
HOST="$BUILD" # If not cross-compiling
HOST="$HOST" BUILD="$BUILD" make -C ./depends/
./autogen.sh
CONFIG_SITE="$PWD/depends/$HOST/share/config.site" ./configure
make
```

So the only thing that `build.sh` uniquely does in our build system is pass `CONFIG_SITE` through correctly. It's not clear to me whether we can actually eliminate this interaction, or if it's worth trying to do so at this point.

**Comment by nathan-at-least** [comment]
What if we drop support for the (very common) autotools practice of allowing builders to provide their own dependencies?

Pros:

- This (might?) make it possible to delegate to the `./depends` system from the top-level autotools system. Is this true?
- Builds following this standard flow would help ensure all builders are getting dependency pinning / reproducible build.

Cons:

- This may introduce a hurdle for some porting to new platforms or other experiments. However, I think in this case, the dev can/should modify `./depends` to suit. Are there valuable cases where modifying `./depends` wouldn't be possible?

**Comment by nuttycom** [comment]
Closing as complete. `build.sh` now performs a clean, because it's the right thing for most users to do when they're trying to rebuild a new version from an existing checkout, and that's not an appropriate role for a bare `make`.
