### ISSUE TITLE
Extraneous CompactSize encoding in transaction SIGHASH preimage

### ISSUE THREAD

**Issue by buck54321** [zcash/zcash#5842]
The crux of the issue is this line here

https://github.com/zcash/librustzcash/blob/43c18d000fcbe45363b2d53585d5102841eff99e/zcash_primitives/src/transaction/sighash_v4.rs#L253

which leads to

https://github.com/zcash/librustzcash/blob/43c18d000fcbe45363b2d53585d5102841eff99e/zcash_primitives/src/legacy.rs#L42

`Vector::write` prefixes the `CompactSize` encoding. From what I can tell, ZIP-143 doesn't call for it, and it's not cryptographically necessary. [Test Vector 3 in ZIP-243](https://github.com/zcash/zips/blob/main/zip-0243.rst#test-vector-3) also doesn't encode it.

See also https://github.com/zcash/zips/issues/196

**Comment by str4d** [comment]
When ZIP 154 says "serialized as scripts inside CTxOuts", what it is referring to is this code inherited from Bitcoin Core:

https://github.com/zcash/zcash/blob/2c13a413347d7aacfc339235f24f9d14449e9c2f/src/script/script.h#L383-L386

https://github.com/zcash/zcash/blob/2c13a413347d7aacfc339235f24f9d14449e9c2f/src/serialize.h#L650-L659

Whether or not this is cryptographically necessary, it is definitely required for consensus, as that is what is deployed.

And Test Vector 3 in ZIP 243 indeed does encode it:

```
[snip]
  Input:
    prevout:    a8c685478265f4c14dada651969c45a65e1aeb8cd6791f2f5bb6a1d9952104d9 01000000
    scriptCode: 1976a914507173527b4c3318a2aecd793bf1cfed705950cf88ac
[snip]
```

```
 25 in hex -.  ,------------------- 25 bytes -------------------.
scriptCode: 19 76a914507173527b4c3318a2aecd793bf1cfed705950cf88ac
```

Test Vector 3 is a real transaction from (IIRC) mainnet (vs the others which are from our test vector generator that produces semantically-invalid but structurally-correct test vectors). In the `zcash/zips` issue you reference, I gave the `getrawtransaction` listing for that transaction, in which you can see the hex-encoded script. There, it does not include the `19` prefix, because that is printing out the raw script opcodes as hex bytes in a JSON output where the length can be implied, rather than encoded as in a `CTxOut` in a transaction (where the size prefix is necessary, as with all variable-length fields).

I'm wondering if maybe the way ZIP 243 presents the test vectors is what is confusing? If the `scriptCode` line is being interpreted as the raw script, then I can understand why someone may think it is missing a `1a` CompactSize prefix. But in ZIP 243 I was merely breaking apart the transaction's hex bytes to show how the pieces were constructed and appended; my intent was for every single byte that feeds into the digest algorithm to be present and visible, rather than implied as with JSON output. If making that clearer in the ZIP would help, we can do so.

**Comment by buck54321** [comment]
Closing, as apparently it is supposed to be there.
https://github.com/zcash/zips/issues/196#issuecomment-1093353840

**Comment by buck54321** [comment]
> If the scriptCode line is being interpreted as the raw script, then I can understand why someone may think it is missing a 1a CompactSize prefix

That's exactly what I was doing
