### ISSUE TITLE
ERROR main: CheckTxShieldedInputs(): shielded requirements not met

### ISSUE THREAD

**Issue by vwas2** [zcash/zcash#5921]
linux v4.7.0 zcasd reports
```
2022-05-03T09:36:16.238416Z ERROR main: CheckTxShieldedInputs(): shielded requirements not met txid=232116b5515767934b65c89cb7c5f8f86335d184c10083098612a074a7068a6f reason=bad-txns-sapling-duplicate-nullifier
```
On explorer it says https://blockchair.com/zcash/transaction/232116b5515767934b65c89cb7c5f8f86335d184c10083098612a074a7068a6f

similar issues
https://github.com/ZcashFoundation/zecwallet/issues/331  
https://github.com/zcash/ZcashLightClientKit/issues/212  
https://github.com/adityapk00/zecwallet-light-cli/issues/55

please shed light

**Comment by str4d** [comment]
This means that the transaction couldn't be added to the mempool because it was trying to double-spend, which can mean one of several things:
- Your full node correctly rejected a double-spend from someone else.
- Your wallet tried to spend the same notes twice (e.g. creating two transactions in parallel, and they end up selecting the same notes).

In this case, what might have happened is that two competing transactions were submitted to the mempool, and one got mined (so the other caused the above error), but then a reorg happened and the above transaction was mined on the side that won.
