### ISSUE TITLE
Improve website monitoring and alerts.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#603]
Easier to discover stats about hits-per-time-per-page, etc… would be nice.  (eg; "web analytics", except that term sounds like overkill for our first step, IMO.)

Also, basic alerts such as TCP connection failures, unexpected HTTP 500s, etc… are important.

**Comment by ageis** [comment]
I also like Pingdom and suggested it in another infrastructure ticket. However, Nagios is already doing the same thing for us. We're monitoring all of our sites, the testnet server, plus the proving keys for availability. Alerts are going to Slack but we may add SMS via email to mobile carrier gateways.

Are you still interested in analytics for the website? I've set up [Piwik](https://piwik.org/) for a bunch of projects before. It's an open source website analytics platform and it's pretty solid, and I have automated code to set it up. It looks like we already set up Google Analytics at some point after this was last updated, though.

If we're not interested in a self-hosted/FOSS analytics solution, then I think this ticket can be closed, since further discussion on this topic will be tied to the infrastructure repository.

**Comment by daira** [comment]
We used Piwik for the LeastAuthority.com analytics. I didn't like it. It's written in PHP; it was finicky to set up and maintain and almost impossible to secure. I would not trust it to be running on the same host as anything important.

**Comment by ageis** [comment]
@daira I definitely hear where you're coming from on that. I had an experience with their security team/process, and I wasn't at all impressed. Someone reported a (what turned out to be hoax) vulnerability in the Piwik instance I maintained and Snowden tweeted about it, haha: https://twitter.com/snowden/status/719263028345192449

**Comment by ageis** [comment]
This belongs under internal infrastructure, and we have analytics and webserver log aggregation set up since this ticket was created.
