### ISSUE TITLE
Very slow sync and `-reindex` after 28.16.2022

### ISSUE THREAD

**Issue by freebeego** [zcash/zcash#6049]
What is wrong with zcashd syncing?
After 28.16.2022 it takes 100% cpu and syncing very slow
All my nodes behind now

**Comment by inkbx** [comment]
same issue now ~

**Comment by steven-ecc** [comment]
We've identified the problem and are working on a fix.

**Comment by gernoox** [comment]
rescanning NU5 era is a torture ;)
![rescann_NU5](https://user-images.githubusercontent.com/23701805/177408794-0ba1afa2-0b5c-436b-aa05-249a7d46a7ab.JPG)

**Comment by freebeego** [comment]
rescanning and syncing NU5 is fucking shit.
Please Do something! Fix it.

**Comment by gernoox** [comment]
hopefully our rescanning will be finish just before building release 5.1.0 next week :D

**Comment by steven-ecc** [comment]
We have a update merged into master that reduces Orchard and Sapling transaction verification times if you'd like to build from source. We'll have release 5.1.0 coming out later this week if you prefer an official release.

**Comment by gernoox** [comment]
I had rebuilt 11h05 ago, here we go again :)
Ty Steven, I'll test it now

**Comment by freebeego** [comment]
@steven-ecc, Thank you
I have Built it already. I trying sync now = )

my previous log from 5.0.0+9d93dff4c build

@gernoox Amen = ))

**Comment by str4d** [comment]
This issue is about slow sync performance (which also affects `-reindex`). I've opened #6052 for slow `-rescan` performance.

**Comment by str4d** [comment]
To answer the original question, the reason sync slowed down after that date is because the chain has been filling up with many shielded transactions. Initially blocks were full of Orchard proofs, and we implemented #6023 to address this. Around when that was merged, blocks started being filled with Sapling proofs, and we spent the weekend implementing #6048 to address it, which just merged.

> @steven-ecc, why does the sync process use just 1 thread? and rescan

@freebeego The sync process has always used threads for transparent validation. As of the above two PRs, it also uses threads for Sapling and Orchard validation. Rescanning does not use threads because due to how shielded detection works in `zcashd` we currently need to scan the chain linearly.

**Comment by dismad** [comment]
![Screenshot_2022-07-06_12-33-08](https://user-images.githubusercontent.com/81990132/177628926-8da435d8-6509-4b86-904c-0c9f7ba70b1f.png)

Seems to be getting stuck here

**Comment by dismad** [comment]
> 



> @dismad, look in debug.log I suppose that it's ok

Seeing a lot of these:
![Screenshot_2022-07-06_12-50-48](https://user-images.githubusercontent.com/81990132/177631658-34f6edd9-eb81-4aa5-8acf-262cabfa9cc5.png)
![Screenshot_2022-07-06_12-50-15](https://user-images.githubusercontent.com/81990132/177631667-d2cf7887-2671-46b0-92e2-da333d162947.png)

**Comment by freebeego** [comment]
I'm still trying syncing my node. Rescan ended, but now I always behind about 1 day. The sync process is very slow.

Help

**Comment by Crypto2** [comment]
Any updates on this? We're still lagging behind by about a day, syncing and rescans are slow af.

**Comment by str4d** [comment]
@Crypto2 [as I said earlier](https://github.com/zcash/zcash/issues/6049#issuecomment-1175489124), rescan performance is being tracked in #6052.

5.1.0 sped up initial chain sync (catching up to the chain tip after starting a node) about as much as is feasible. There's not much more we can do to improve the asymptotics for Sapling and Orchard, other than improving the performance of the underlying field arithmetic if possible, due to how the chain state update system we inherited from Bitcoin Core is structured (linear and synchronous).

For steady-state chain sync (keeping up with the chain tip once the node reaches it), I've just finished #6073 which caches Sapling and Orchard bundle validation (if a transaction is verified going into the mempool, we won't re-verify the Sapling and Orchard proofs and signatures when it appears in a block). On my Ryzen 9 5950X it appears to decrease block validation times by 50-80%.

**Comment by freebeego** [comment]
@str4d NO!
if in a wallet has transactions and addresses sync is very slow
it works good with a new empty wallet. Seems like good.
But then you generate addresses and make transactions and it becomes slow slow slow ... at the end you are behind of real current block and you can not use your wallet.

when are you fix it?

**Comment by Crypto2** [comment]
Yeah it's getting ridiculous at this point, been waiting days for it to catch up and on pretty decent hardware. Hope you aren't going the SOL route and thinking we need a beast of a machine just to run a node.

**Comment by freebeego** [comment]
rizen 2700x
32gb ddr4
512 gb nwme pci ssd (very fast)

... Help

**Comment by freebeego** [comment]
The RPC interface answers 500 half of requests.

**Comment by freebeego** [comment]
nodes which are synced are process very slow every new block. And while it in progress rpc is not responding

**Comment by Crypto2** [comment]
What's weird is it will be doing nothing and locked up for a long time, do a flurry of blocks quickly, then back to locked up. So I'm not even sure if it's the actual block processing/scanning code efficiency that's the problem but some huge mutex lock that's getting hung up or something.

**Comment by freebeego** [comment]
Yes it definitely works this way!

**Comment by str4d** [comment]
@freebeego I have said repeatedly that rescanning performance issues are being tracked in #6052. In particular, there is a PR listed there which will likely help rescan performance significantly, which you are welcome to test..

To all: Any further comments in this issue that are not about either `-reindex`, Initial Block Download, or steady state node chain synchornization (i.e. the node, rather than the wallet) will be deleted, instead of being hidden as off-topic.

**Comment by str4d** [comment]
We implemented the remaining improvements we have for this in 5.2.0.
