### ISSUE TITLE
Don't rename main thread it should be zcashd

### ISSUE THREAD

**Issue by gades** [zcash/zcash#6066]
### Describe the issue
main thread is showing as zc-wait-to-stop  instead of zcashd

#### If so, please list the steps to reproduce below:
1.  run zcashd
2. check name process 

### Expected behaviour
I'm expecting original name zcashd  instead of zc-wait-to-stop

### Actual behaviour + errors
ps ax | grep zcashd
  37137 ?        SLsl   3:56 zcashd
cat /proc/37137/task/37137/comm 
zc-wait-to-stop

### The version of Zcash you were using:
Zcash Daemon version v5.1.0

### Machine specs:
- Ubuntu 20.04.4 LTSca
- CPU: Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
- RAM: 128GB
- Disk size: 1 TG
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux mn-template 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc --version): gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- Linker version (ld -v): GNU ld (GNU Binutils for Ubuntu) 2.34
- Assembler version (as --version): GNU assembler (GNU Binutils for Ubuntu) 2.34

**Comment by daira** [comment]
This happens after the node is requested to shut down and was added in #5959:
https://github.com/zcash/zcash/blob/050133358b9cf7ce64462cc998305b2315531b64/src/bitcoind.cpp#L44-L48

We could change it to `zcashd-shutting-down` or similar, or leave it as-is, or not rename. @str4d, what's your preference here?

**Comment by gades** [comment]
it's not correct because daemon is in sync process and that's why I did ticket 

<img width="795" alt="Screenshot 2022-07-09 at 1 12 27 PM" src="https://user-images.githubusercontent.com/4200730/178101390-87837223-17e2-4863-818b-3ab5113f9107.png">

**Comment by gades** [comment]
Looks like it's related to clone commits from bitcoin and please check this one

https://github.com/bitcoin/bitcoin/pull/17038

**Comment by daira** [comment]
I had a look at backporting bitcoin/bitcoin#17038, but it depends on 3 other PRs that introduced `util/threadnames.{h,cpp}` (see https://github.com/bitcoin/bitcoin/commits/master/src/util/threadnames.cpp):
* bitcoin/bitcoin#15849
* bitcoin/bitcoin#15968
* bitcoin/bitcoin#16984 (which @str4d effectively already did in 6aa7c187d19b8537040fbb4debfad94845775c91)

Overall it doesn't seem worth the hassle compared to #6067.

**Comment by gades** [comment]
right, but I think you can also port those commits for preventing same issues in future releases because I saw that your team is doing  update core from bitcoin last time

**Comment by daira** [comment]
Yes, in general it is often a good idea to backport even if it's more complicated. I personally don't think the tradeoff is worth it in this case (partly influenced by the fact that #5959 was also not a direct backport, so any future changes to thread naming are going to conflict anyway). But I'll defer to @str4d's opinion since it may interact with some of his other backports.

**Comment by str4d** [comment]
My reasonable for renaming was solely for debugging purposes (as otherwise it's hard to distinguish between threads in backtraces), and then name I chose is accurate (since at the time the main thread is renamed, it is literally in a waiter loop waiting for the shutdown signal). I was completely unaware however that UNIX tools interacted with the main thread name, not the process name, but the upstream PR makes sense in that context.

I'll look at the backports related to this at some point, but in the meantime just undoing that one rename should be sufficient to close this issue.

**Comment by gades** [comment]
I did some improvement for debugging purposes and code refactoring
