### ISSUE TITLE
Cryptographically sign releases

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#609]
We should decide how we'll sign release tarballs and git tags, as well as how we'll distribute the public keys.

**Comment by petjal** [comment]
FWIW, in a prior life, I did this:
http://sourceforge.net/projects/tikiwiki/files/Old%20Stuff/Tiki_10.x_Sun/10.4/Verification/

**Comment by paragonie-scott** [comment]
I'm growing rather fond of [Minisign](https://github.com/jedisct1/minisign).

**Comment by petjal** [comment]
Tried to build minisign, 

>$ make
>[ 25%] Building C object CMakeFiles/minisign.dir/src/minisign.c.o
>.../jedisct1-minisign-eb13b0a/src/minisign.c:14:20: fatal error: sodium.h: No such file or directory
> #include <sodium.h>
                    ^
>compilation terminated.
>make[2]: *** [CMakeFiles/minisign.dir/src/minisign.c.o] Error 1
>make[1]: *** [CMakeFiles/minisign.dir/all] Error 2
>make: *** [all] Error 2

Tried  to install  libsodium-dev 

>$ sudo apt-get install libsodium-dev

but failed with 

>E: Failed to fetch http://deb.bitmask.net/debian/pool/main/libs/libsodium/libsodium-dev_1.0.0-1+0~20141111175508.17+trusty~1.gbp09170c_amd64.deb  404  Not Found

That .deb not found here:
>http://deb.bitmask.net/debian/pool/main/libs/libsodium/

Not smart enough to figure it out.

**Comment by sampablokuper** [comment]
Signing release tarballs and git tags is crucial if Zcash is to be trustworthy.

Ideally, Git commits should be signed too. See: https://mikegerwitz.com/papers/git-horror-story

Please can this issue therefore be renamed from "Cryptographically sign releases" to "Cryptographically sign commits, tags, and releases"?

As for how to go about signing commits, try these guides:

- https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
- https://help.github.com/articles/signing-commits-using-gpg/

Personally, I don't see any need for minisign. It seems to me that GnuPG\* and Git should be adequate to handle Zcash's signing needs.

\* For improved security, GnuPG should be used in conjunction with an [offline master signing key](1381). That key's signing subkey should be kept in an [OpenPGP Card](https://lwn.net/Articles/696078/)-compliant hardware token (e.g. an [FSFE card](https://fsfe.org/fellowship/card.en.html), a [Nitrokey](https://lwn.net/Articles/695067/), a [Yubikey](https://old.lwn.net/Articles/687676/), or [Gnuk on an FST-01](http://wiki.seeedstudio.com/wiki/FST-01)) or a [Qubes "split GPG"](https://www.qubes-os.org/doc/split-gpg/) VM.

**Comment by ageis** [comment]
AFAIK, a few of the developers commented that they were not a fan of GPG-signing commits because it makes squashing or merging more complicated (or something to that effect).

**Comment by sampablokuper** [comment]
> it makes squashing or merging more complicated

Yes, accountability takes effort :)

Something in which people are expected to place as much trust as Zcash is something that should be built *very* accountably, IMO.

If accountability can be made less effortful, great; but in the meantime, the gain in accountability would still be well worth the extra effort of signing commits over simply signing tags and releases. The Git Horror Story linked above explains why.

**Comment by str4d** [comment]
@ageis is working on this AIUI, and I need to know about the process for the next release.

**Comment by ageis** [comment]
As I see it, the details of the binary building process are prerequisite to signing and dictate some of the decisions to be made. As @defuse said there's no widely-used standard process.

e.g. build machines: who performs the release builds, and where do they happen? The DevOps engineer could be responsible for this, or one of the Zcash core developers.

As maintainer of the website and infrastructure where releases will be posted, I'm comfortable with receiving a binary package from one of the developers, signed by their personal key, and signing it across the air-gap with a Zcash master key in cold offline storage. If deemed appropriate, I could also be the one to do the build and set aside a secure build machine for that purpose, since I've already automated that process. I can fully document how this would work; it would be similar to the process used by SecureDrop, involving CD-ROMs/DVDs to transfer files to the air-gap, and QR codes to read the signatures back.

@sampablokuper comments on the importance of accountability—IMO we don't necessarily need to be fully transparent about all aspects of our building and signing process, because that provides information to attackers. You'll find that most projects aren't publishing that kind of information.

My main point for this comment is that signing releases is getting ahead of ourselves since we definitely need Gitian (#540) and reproducible builds first, not to mention the packaging problem (#1034). I've been taking the initial steps towards that this week, but helping hands are always welcome.

What do we intend to _initially_ sign and post, anyway? A tarball simply containing the Zcash x86-64 ELF binaries and the fetch-params.sh utility? Or a Debian jessie package and repository? I can't make these kinds of big decisions without input from other engineers.

**Comment by sampablokuper** [comment]
> I'm comfortable with receiving a binary package from one of the developers, signed by their personal key, and signing it across the air-gap with a Zcash master key in cold offline storage.

I'm puzzled by this. What is the problem to which this is the solution?

**Comment by ageis** [comment]
@sampablokuper I'm merely throwing ideas out in brainstorm, since I haven't been present for any previous open discussion of this. In reality, the binary that ultimately gets signed will be that which is uploaded by the Gitian builder, and signed by multiple developers, verified to have been produced deterministically.

**Comment by ageis** [comment]
To elaborate on why this is so important: we have good reason to be
concerned about so-called "watering hole attacks", where the software
development and build processes themselves are attacked in order to deliver
malicious code to thousands of users at once; any malicious code delivered
at any point which could backdoor or provide a way to exfiltrate coins. Of
course, we are bootstrapping a block chain upon which real-world value is
placed, so it's important that we get this right.

There is a chain of trust that gets verified at each step. There is a git
tag for the release of the source code. It should probably be signed. It's
possible to use an offline key to make the git tag signature, it just
involves manual manipulation of the files in `.git`.

However, I'm not the one who tags releases as yet. We cycle through
different release managers. So, we have to trust what's in the git tag to
begin with.

If possible the Gitian builds should even verify the git tag signature if
present, before building. Then multiple builder VMs will return multiple
signatures for the same, identical binary. That exact binary will then be
packaged and/or uploaded to our website, via secure/hardened or air-gapped
machines machines that are exclusively meant for packaging + signing. There
are multiple possible ways to transfer data across the air gap, USB being
the least desirable. The last steps of all this are significantly manual.

That's an obvious outline at only a high level. I am only just starting to
think about and attempt to build it in detail.

On Sep 22, 2016 5:42 AM, "modem_down" <notifications@github.com> wrote:

I'm comfortable with receiving a binary package from one of the developers,
signed by their personal key, and signing it across the air-gap with a
Zcash master key in cold offline storage.

I'm puzzled by this. What is the problem to which this is the solution?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zcash/zcash/issues/609#issuecomment-248892625>, or mute
the thread

**Comment by nathan-at-least** [comment]
Here's what I propose:

- we use a reproducibile build system (in our case gitian),
- a release manager tags a git revision, signed with their personal dev key,
- if it's possible for other parties to sign the same git tag, we could have multiple devs stake their reputation on the line as attesting to the correctness/safety/goodness of the tag,
- multiple people run the reproducibile build system and sign the result,
- operations/deployment role only has to verify the tag and build each have required signatures (maybe 3 or 5 signatures, with no discrepancies, eg: signatures of different binaries for the same tag), in which case they automatically host the packages for download.

The last step could even be automated and it removes the deployment/operations team from making any claim about the binaries. The one security responsibility they would have is ensuring the hosted binaries aren't tampered with. For that we should post the same build sigs next to the downloads so anyone may verify those.

This process could even incorporate signatures from contributors outside of the ZcashCo which is the direction we need to move (away from ZcashCo centralization).

Signing a build is lower risk/responsibility than signing a tag, because the former if just attesting to running a program and can be almost completely automated, whereas the latter is a human attestation as to the "goodness" of a tag.

For this ticket, let's narrow the scope to just this:

* ensure that the gitian process signs the resulting binary (with appropriate config / options).

For the other needs (signing git tags, hosting packages, etc...) let's use separate tickets, and we'll get to those steps maybe after beta 2 release.

**Comment by paragonie-scott** [comment]
> This process could even incorporate signatures from contributors outside of the ZcashCo which is the direction we need to move (away from ZcashCo centralization).

Count me in on this point, should your proposal be adopted.

**Comment by ageis** [comment]
@nathan-at-least That sounds great. 

Ok, so #1381 will come later, when there are signed tags and packaging. For the present time / beta2 we will focus on achieving multiple build signatures from multiple developers on a deterministic binary.

**Comment by nathan-at-least** [comment]
This ticket is ambiguous, because we want different kinds of signatures which provide different kinds of assurances:

* signing git tags - #1434 
* signing reproducible build outputs - ???
* signing installable packages - ???
* signing each git commit (optional / bonus) - ???

**Comment by bitcartel** [comment]
Signing git tags was completed and ticket closed.

Signing each git commit is out of scope.

This ticket can be closed when we are able to sign:

- reproducible build outputs
- installable packages

**Comment by ageis** [comment]
* We sign our git release tags.
* We sign our Gitian build assertions: https://github.com/zcash/gitian.sigs
* We sign the .deb package repository Release file: http://apt.z.cash/dists/jessie/Release (.gpg)

I'm working on making it so [zcash-gitian](https://github.com/zcash/zcash-gitian) verifies the tag when it fetches the source for the Gitian build, but this issue is done.

**Comment by radix42** [comment]
Do you have a guide to setting up vagrant/gitian to releases and then publish build assertions? I'd like to set that up on my fork to do for your releases

**Comment by petjal** [comment]
This?:  https://github.com/zcash/zcash-gitian

**Comment by radix42** [comment]
Yes, the question got answered in another ticket as I was asking it in this one :-)
