### ISSUE TITLE
Implement ZIP 317 wallet fee logic

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#6345]
https://zips.z.cash/zip-0317#fee-calculation

**Comment by nuttycom** [comment]
Also, we should make sure to look at #5984 in the process.

**Comment by nuttycom** [comment]
As part of this implementation, we will need to make it possible for each RPC method that currently takes a fee amount as an argument to take that argument in a fashion that means "compute the correct value for the transaction." Ideally we'd be able to specify RPC arguments via key/value pairs for this scenario, but we might also need to simply choose a sentinel value (like `-1`) that will be interpreted as an instruction to compute & use the correct conventional fee.

**Comment by sellout** [comment]
> Also, we should make sure to look at #5984 in the process.

`estimatefee` is confusing – the documentation (and Bitcoin usage, of course) specifies that it’s meant to estimate the fee you should use for a tx to be mined within `n` blocks. For us, regardless of ZIP 317, that question is nonsensical, since our fees aren’t size-based. The best we could do is some kind of weighted average based on the expected (or maybe historical) sizes of various logical actions. But that still doesn’t tell the user what fee they should expect to pay.

We could alternatively rename this to something like `averagefee` and return the average fee/kb we’ve seen without tying it to something the user should add to a transaction.

Or we could make `estimatefee` a sort of “dry run” operation that builds the transaction and returns the fee calculated in that process. When we split Prepare/Approve into a two-phase operation, that would subsume this usage.

But otherwise, I don’t see why we haven’t deprecated that call.
