### ISSUE TITLE
asOfHeight wallet optional argument never gets past argument parsing, always rejected as not an integer

### ISSUE THREAD

**Issue by sabcha87** [zcash/zcash#6429]
### Describe the issue
Please provide a general summary of the issue you're experiencing
The "asOfHeight" wallet option, introduced in 5.3.1, sounds like a great boon to keeping track of one's past wallet activity.  Unfortunately, as of now (in Debian Bullseye gitian build binaries of 5.3.1, 5.3.2, 5.4.0 anyway), the argument parser always rejects the optional integer command-line argument as "not an integer", and thus the functionality is unreachable.

#### If so, please list the steps to reproduce below:
Run Debian Bullseye gitian build binary (5.3.1, 5.3.2 or 5.4.0)
e.g.
zcash-cli getwalletinfo 1900000

### Expected behaviour
Tell us what should happen
The advertised functionality, e.g. wallet info, as of the requested block height (1900000 in example above).

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)
The asOfHeight functionality is not reachable - the argument parser complains, with these 2 lines:
"
error message:
JSON value is not an integer as expected
"

### The version of Zcash you were using:
Run `zcashd --version` to find out
Most recently 5.4.0, but the same happens on 5.3.1 and 5.3.2.  (I am actually quite surprised, to be the first to report this!)

### Machine specs:
- OS name + version: Debian Bullseye

**Comment by daira** [comment]
It appears that #6122 only included RPC tests for `listunspent` and `listtransactions`. There are also tests for internal APIs, but nothing in that PR that would test argument parsing for the other RPC methods to which an `asOfHeight` argument was added.

**Comment by sellout** [comment]
The bug here is on the `zcash-cli` side  – it isn’t converting some arguments to JSON values (to integers, in the `asOfHeight` case), but sending them as JSON strings. I’m making a change that should make it harder for the client to get out of sync with the server in future.

The Python RPC interface (and thus the RPC tests) aren’t affected by this.

@sabcha87 – if you’re using `bitcoin-cli` (as the issue states) rather than the zcash-provided `zcash-cli`, then this won’t work for you. `asOfHeight` isn’t offered by `bitcoind`, so their client won’t handle the call correctly. You’ll have to use `zcash-cli` (once my fix is in).

**Comment by sabcha87** [comment]
@sellout  Sorry I mistyped "zcashd" as "bitcoind" in my initial message, I can only blame brain fog (I could not mouse-copy the command as I was writing the bug report on another machine).  Please rest assured, my testing was of "zcashd", I only have Zcash (and Monero) installed on that machine, not Bitcoin.  Apologies, I have edited my initial message to correct that mistyping!
