### ISSUE TITLE
single pour input, value commitment scheme

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#647]
This is a sort of "beautiful" unification of Pour which I've been thinking about. It splits the current cost in half ~~(at least!)~~ for the most common case. See #426 and #237 for more discussion about the "number of pour inputs and outputs."

If we wanted a pour with one fixed input, we would need to carry value commitments between each pour to avoid leaking value within the pour operation. At the ends the trapdoor of the commitment would be null so we could verify that the overall operation is balanced.

This requires a kind of signed arithmetic in the circuit.

Here's how a `CPourTx` would look:

```
{
    vpub_old: u64,
    vpub_new: u64,
    scriptPubKey: CScript,
    scriptSig: CScript,
    anchor: u256,
    pours: [
        {
            h_mac: u256,
            serial: u256,
            ciphertexts: array<vector<unsigned char>, NUM_POUR_OUTPUTS>
            commitments: array<u256, NUM_POUR_OUTPUTS>,
            zkSNARK: vector<unsigned char>,
            vpub_out_commitment: u256
        },
        ...
    ]
}
```

The `vpub_out_commitment` for the last `pours` object doesn't need to be serialized since it can be inferred. As a result, not only is the zkSNARK smaller, verification time is faster, and the transaction saves a serial for the base case of a 1-input-2-output pour.

Oh, and pours take half as long to generate!

**Comment by ebfull** [comment]
The weird part is that this effectively replaces chained pours when you're trying to combine more than 2 inputs in our current scheme.

**Comment by ebfull** [comment]
@kefkius wrote a script to scrape blockchain.info for this data. Coinbase transactions are omitted since they would skew the results.

```
For blocks 394600 - 394700:
Input Count     Tx Frequency
----------------------------
1           77328
2           22589
3            5050
4            1819
5            1070
6             755
7             467
8             344
9             255
10             240
11             143
12             109
13             980
14              90
15              95
16              91
17              95
18              98
19              97
20             170
21              52
22              52
23              47
24              38
25              70
26              11
[snip]
```

```python
import requests
from collections import defaultdict

START_BLOCK = 100000
END_BLOCK = 100005

def download_block(height):
    url = 'https://blockchain.info/block-height/%s?format=json' % height
    r = requests.get(url).json()
    if len(r['blocks']) > 1:
        print('Note that blockchain.info has more than one block %d' % height)
    return r['blocks'][0]

# dict of {vin length: tx frequency}
input_counts = defaultdict(int)

def count_inputs(blockjson):
    assert len(blockjson['tx'])
    for i, tx in enumerate(blockjson['tx']):
        if i == 0:
            continue
        txins = len(tx['inputs'])
        input_counts[txins] += 1

for height in range(START_BLOCK, END_BLOCK + 1):
    blockjson = download_block(height)
    count_inputs(blockjson)

print('For blocks %d - %d:') % (START_BLOCK, END_BLOCK)
print('Input Count' + (' ' * 5) + 'Tx Frequency')
print('-') * 28
for k, v in input_counts.items():
    print('%d % 15d' % (k, v))
```

**Comment by Kefkius** [comment]
@ebfull huh, I didn't know I was helping out this project. If necessary, I can do something fancier to collect the data. I know that the above script takes a while to run due to this being an IO bound task.

**Comment by ebfull** [comment]
@Kefkius Shouldn't be a problem, I was pretty confident single-input transactions were more common anyway.

**Comment by zookozcash** [comment]
Thanks for the idea and data, @Kefkius and @ebfull!

**Comment by ebfull** [comment]
I disagree with making this "not in 1.0" until there's evidence to suggest this wouldn't substantially help our circuit costs. The engineering costs are not that high compared to the benefits.

**Comment by ebfull** [comment]
If a knapsack hash function and #704 are implemented, the argument for this change before 1.0 is diminished significantly, as the benefit of reducing an input is only barely justified by the performance hit we take for the value commitments.

**Comment by daira** [comment]
We might not be able to use a subset-sum hash because of concerns about its collision resistance security. I'm pretty sure I understand this idea and its performance implications now, and I agree with @ebfull in https://github.com/Electric-Coin-Company/zcash/issues/647#issuecomment-174757279 that this should still be potentially in scope for 1.0. (I don't think that the cost of the value commitments is much of a problem.)

I intend to write up a protocol spec change for this for the February 15 milestone, so that we can work out the details (without committing to including it yet).

**Comment by daira** [comment]
Assuming #704 is also implemented, this ticket reduces the number of circuit hashes from 112 to 61 given a commitment tree depth of 48, i.e. by 45.5% (neglecting constraints that are not associated with hashes).

**Comment by daira** [comment]
Again assume a commitment tree depth of 48. Let's recompute the relative saving based on also switching to a subset-sum hash of dimension 5 for the commitment tree (but staying with SHA-256 for the other hashes in the circuit). From https://github.com/Electric-Coin-Company/zcash/issues/426#issuecomment-179296593 we have that the subset-sum hash costs 0.0698 times the number of constraints of SHA-256. So, the reduction in total hash cost is from (96*0.0698 + 20) to (48*0.0698 + 13), or from 26.70 to 16.35, which is a saving of 38.8%.

Conclusion: switching to a subset-sum hash (#40) would not obviate this ticket as a significant optimization.

**Comment by daira** [comment]
As @ebfull has pointed out elsewhere, this is still a useful optimisation even if we always do two Pours where we would otherwise have done one &mdash; because those Pours can be done either in parallel, or sequentially with less memory usage.

**Comment by daira** [comment]
I'm very concerned that mitigating the attacks mentioned on #714 will increase the cost of proving to the point that we *have* to do some of the performance enhancements we've talked about (#896, #750, this ticket) before launch.

**Comment by daira** [comment]
I'm even more enthusiastic about this idea given the issue with hiding intermediate ``vpub_out``s in #1360, since solving that issue requires that when we combine N input notes, we use at least min(1, N-1) JoinSplits. This makes it N JoinSplits, but each one is almost half the cost.

I'm itching to write a ZIP -- I see exactly how it would work. The circuit overhead of the commitments is two SHA256Compress evaluations (one for the input and one for the output commitment). You need independent randomness for each commitment, but this can be set to zero for the initial input and final output (since you don't need to hide the overall ``vpub_old`` and ``vpub_new``).

**Comment by tromer** [comment]
I like this idea. Significant reduction in shielded transaction memory cost in _all_ cases, and significant reduction in time in _most_ cases, at very mild cost in protocol complexity and no extra cryptographic assumptions.

**Comment by daira** [comment]
Here is the proposed JoinSplit statement. For N<sup>new</sup> = 2 it has 13 + d<sub>Merkle</sub> hashes.

"≛" means "is constrained equal to".

statement JoinSplit(
    rt ⦂ 𝔹<sup>[ℓ<sub>Merkle</sub>]</sup>,
    nf<sup>old</sup> ⦂ 𝔹<sup>[ℓ<sub>PRF</sub>]</sup>,
    cm<sup>new</sup><sub>1..N<sup>new</sup></sub> ⦂ COMM.Output<sup>[N<sup>new</sup>]</sup>,
    h<sub>Sig</sub> ⦂ 𝔹<sup>[ℓ<sub>hSig</sub>]</sup>,
    h ⦂ 𝔹<sup>[ℓ<sub>PRF</sub>]</sup>,
    cv<sup>pub</sup><sub>old</sub> ⦂ COMM.Output,
    cv<sup>pub</sup><sub>new</sub> ⦂ COMM.Output,
    private path ⦂ 𝔹<sup>[ℓ<sub>Merkle</sub>][d<sub>Merkle</sub>]</sup>,
    private **n**<sup>old</sup> ⦂ Note,
    private a<sup>old</sup><sub>sk</sub> ⦂ 𝔹<sup>[ℓ<sub>a<sub>sk</sub></sub>]</sup>,
    private **n**<sup>new</sup><sub>1..N<sup>new</sup></sub> ⦂ Note[N<sup>new</sup>],
    private φ ⦂ 𝔹<sup>[ℓ<sub>φ</sub>]</sup>,
    private enforceMerklePath ⦂ 𝔹,
    private v<sup>pub</sup><sub>old</sub> ⦂ {0..2<sup>64</sup>-1},
    private v<sup>pub</sup><sub>new</sub> ⦂ {0..2<sup>64</sup>-1},
    private r<sup>pub</sup><sub>old</sub> ⦂ COMM.Trapdoor,
    private r<sup>pub</sup><sub>new</sub> ⦂ COMM.Trapdoor,
) {
    let (a<sup>old</sup><sub>pk</sub>, v<sup>old</sup>, ρ<sup>old</sup>, r<sup>old</sup>) = **n**<sup>old</sup>

    // Input commitment integrity.
    cm<sup>old</sup> ≛ NoteCommitment(**n**<sup>old</sup>)

    for i ∈ {1..N<sup>new</sup>} {
        let (a<sup>new</sup><sub>pk,i</sub>, v<sup>new</sup><sub>i</sub>, ρ<sup>new</sup><sub>i</sub>, r<sup>new</sup><sub>i</sub>) = **n**<sup>new</sup><sub>i</sub>

        // Output commitment integrity.
        cm<sup>new</sup><sub>i</sub> ≛ NoteCommitment(**n**<sup>new</sup><sub>i</sub>)
    }

    // Merkle path validity. (For simplicity we don't include #2171 or #43 here.)
    rt ≛ MerkleRoot(path, cm<sup>old</sup>)

    // Merkle path enforcement.
    if (v<sup>old</sup> ≠ 0) {
        enforceMerklePath ≛ 1
    }

    // Balance.
    v<sup>pub</sup><sub>old</sub> + v<sup>old</sup> ≛ v<sup>pub</sup><sub>new</sub> + ∑[v<sup>new</sup><sub>i</sub> for i from 1 up to N<sup>new</sup>]

    // Nullifier integrity.
    nf<sup>old</sup> ≛ PRF<sup>nf</sup><sub>a<sup>old</sup><sub>sk</sub></sub>(ρ<sup>old</sup>)

    // Spend authority.
    a<sup>old</sup><sub>pk</sub> ≛ PRF<sup>addr</sup><sub>a<sub>sk</sub></sub>(0)

    // Nonmalleability.
    h ≛ PRF<sup>pk</sup><sub>a<sup>old</sup><sub>sk</sub></sub>(hSig)

    // Uniqueness of ρ<sup>new</sup><sub>1..N<sup>new</sup>.
    for i ∈ {1..N<sup>new</sup>} {
        ρ<sup>new</sup><sub>i</sub> ≛ PRF<sup>ρ</sup><sub>φ</sub>(i, hSig)
    }

    // Commitment to incoming value.
    cv<sup>pub</sup><sub>old</sub> ≛ COMM<sub>r<sup>pub</sup><sub>old</sub></sub>(v<sup>pub</sup><sub>old</sub>)

    // Commitment to outgoing value.
    cv<sup>pub</sup><sub>new</sub> ≛ COMM<sub>r<sup>pub</sup><sub>new</sub></sub>(v<sup>pub</sup><sub>new</sub>)
}

**Comment by daira** [comment]
Another advantage of this approach is that you can potentially use the value commitments to link to arbitrary other zk proofs. I.e. if we added a new kind of proof to support a specific application, then that proof could provide input to, or take output from, a JoinSplit in order to conceal the amount being processed.

**Comment by zookozcash** [comment]
If I understand correctly, this gains substantial CPU advantages, i.e. 50% as costly when you have only a single input to spend, but it exposes more information, i.e. exposes the fact that you had only one input to spend.

I'm reluctant to approve something that adds a privacy leak, because it is hard to be sure the consequences of a privacy leak, and because different kinds of privacy leak compound with one another (even from completely different parts of the system, for example one privacy leak in the blockchain combined with one privacy leak in the network layer (https://github.com/zcash/zcash/issues/12) ).

I'd like first to answer the question "How good can we get performance _while keeping privacy maxed out_, i.e. while keeping privacy leakage clamped to a bare minimum. Various techniques (starting with a [more efficient-inside-the-SNARK collision-resistant hash function](https://github.com/zcash/zcash/issues/40)) may make the answer to this good enough!

**Comment by daira** [comment]
@zookozcash: our current construction already leaks information about the input and output arity. The performance increase enabled by this change gives about as much help with arity-hiding as it takes away, since it allows you to afford more JoinSplits within a given performance budget. It also makes it more likely that shielded transactions will actually be used. Also note that none of the anonymity technologies Zcash is competing against (CT, Monero, mixers, etc.) attempt to hide this information at all.

**Comment by daira** [comment]
In addition, the performance gains of this change and of the Pedersen commitment change are multiplicative; they don't interfere with each other at all. So it's a matter of "why would you not do both?" Based on some back-of-the-envelope calculations (I'll fill in more detail when I a chance), I think it's quite unlikely that we would not still consider shielded transactions to be a bottleneck if we only did either one.

**Comment by daira** [comment]
By the way, using value commitments to carry change between JoinSplits is actually orthogonal to using an input arity of 1. But I recommend doing both; it's simpler and it addresses the performance bottleneck that we currently have, and will probably still have to some extent if we use Pedersen commitments. Note that Pedersen commitments also have higher costs in terms of the complexity of supporting two commitment types, migrating the commitment tree, implementing new ECC crypto in the circuit, analysing that crypto and its implementation, etc. This change is straightforward in comparison.

**Comment by daira** [comment]
If we were to use Pedersen commitments without #647 in place of all of the SHA256Compress instances in the circuit (which might not be possible, but for the sake of argument), it would still take ~4 seconds on our benchmark machine to generate a proof. Using [LongsightF-322/p/3](https://github.com/zcash/zcash/issues/2233#issuecomment-291854536) it would still take ~1 second. (In both cases this is neglecting any improvement from using the Groth16 proving system, or any other changes to the circuit.) With #647 as well, proving would take ~2.3 seconds or ~0.6 seconds respectively.

[Note to anyone getting excited about these performance estimates: they are very preliminary and make lots of assumptions; we're certainly not making any commitment that the actual performance of Sapling will look like this.]

**Comment by daira** [comment]
This is included in the Sapling circuits which are fully designed, so this ticket can be closed.

My performance estimate from April 2017 turned out to be pretty much on-the-money :-)
