### ISSUE TITLE
Wallet operation disabled while reindexeing

### ISSUE THREAD

**Issue by anurag-iitk** [zcash/zcash#6736]
### Describe the issue
Please provide a general summary of the issue you're experiencing
I want to connect my zecWallet with the running node, But when I connected they show some error regards reindexing. I tried multiples time but same error shown again and again.

#### If so, please list the steps to reproduce below:
1. Make a other node
2. Run the node
3. Connect wallet with running node

### Expected behaviour
Tell us what should happen
Terminal shown wallet operation is disabled because of reindexing.

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

### The version of Zcash you were using:
Run `zcashd --version` to find out
Zcash Daemon version v5.6.0-gitian

### Machine specs:
- OS name + version: Ubuntu
- CPU:
- RAM: 8GB
- Disk size: 500GB
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a):
- Compiler version (gcc --version):
- Linker version (ld -v):
- Assembler version (as --version):

### Any extra information that might be useful in the debugging process.
This includes the relevant contents of `~/.zcash/debug.log`. You can paste raw
text, attach the file directly in the issue or link to the text via a pastebin
type site. Please also include any non-standard things you did during
compilation (extra flags, dependency version changes etc.) if applicable.

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
- Backing up / making a copy of the `~/.zcash` directory might help make the
  problem reproducible. Please redact appropriately.
- Taking a VM snapshot is really helpful for interactively testing fixes

**Comment by str4d** [comment]
This is intentional behaviour. `zcashd` is a full node, and its wallet assumes full node behaviour. What this means is that if the node is reindexing, its view of the chain is months or years behind the current tip, and any of the wallet operations that require accurate chain state (such as `z_getbalance` and `z_sendmany`) are disabled.

What ZecWallet should be doing is detecting that a reindex is occurring (which it can do by checking the `initial_block_download_complete` field of `getblockchaininfo`, which will be `false` until the node's view of the chain tip is within 24 hours of the current time), and showing a minimal UI until it is complete.
