### ISSUE TITLE
Remove the default unpaid action limit

### ISSUE THREAD

**Issue by daira** [zcash/zcash#6899]
The allowance for unpaid actions was not intended to be useful long-term. It was just a stopgap to allow us to deploy partial enforcement of ZIP 317 fees sooner, without that being blocked by "all" wallets supporting them for transaction creation.

It was understood when designing this mechanism that attackers would adapt to it, which they have, making the allowance essentially useless to the few legitimate users using wallets that are not paying these fees.

To avoid spending time on the changes to zcashd, I suggest just making `DEFAULT_BLOCK_UNPAID_ACTION_LIMIT` zero, which is a one-line change [1]. My impression is that mining pools do not override the default.

[1] with ~1300 lines of test changes (#6900). 😭

**Comment by str4d** [comment]
Mempool metrics from `zcashd` for the past 4 days show a resumption in this behaviour:

![image](https://github.com/zcash/zcash/assets/4993799/93d4e30b-4e9f-401b-9ec3-b30d83cbb9c5)

Spot-checking the contents of the mempool just now, every spam transaction has 50 logical actions:
- 48 transparent outputs.
- 1 Sapling spend funding the transaction.
- 2 Sapling outputs (probably because the transaction builders force this).

So yes, they are directly targeting the current default unpaid action limit, and dropping the default to zero would resolve this.

**Comment by gades** [comment]
Will reject it accepting tx to mempool and don’t do relay tx? Looks like no

**Comment by zerodartz** [comment]
hey. are most transparent wallets going to break after this change in fee? like trezor, ledger, coinomi, trust wallet, exodus etc? do they know they need to implement it? are they working on adding the ZIP317 support? 

if not, there will be probably many users who cant transact on their wallets without restoring in wallets that support it.
