### ISSUE TITLE
Evaluate error handling in libsnark and zcash

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#69]
``libsnark`` may abort/exit on certain classes of error which should be recoverable by the application.  If so, identify where those cases are and consider how we want to address them.

Let's track the work of fixing those cases, and handling them within ``libzerocash`` or ``zerocashd`` as separate tickets.

**Comment by ebfull** [comment]
This has security implications and so should be considered as in 1.0.

**Comment by ebfull** [comment]
#520 has some additional information.

**Comment by daira** [comment]
+1 for 1.0. The existing asserts are pretty clearly unacceptable and a serious DoS hazard.

**Comment by bitcartel** [comment]
Equihash.cpp has some asserts which can be triggered by an invalid solution.

**Comment by str4d** [comment]
@bitcartel can you give examples? The validation code should be set up so that the asserts are already satisfied by the time they are called, ie. their condition is enforced earlier and validation will have failed before the assert could trigger.

**Comment by str4d** [comment]
(If it isn't set up that way, that is a bug that I need to fix.)

**Comment by bitcartel** [comment]
Hi @str4d. I think it might be safer for the asserts to be replaced with exceptions and return values, just in case some edge conditions creep in over time.

Regarding the asserts:

Could this assert be triggered if a future developer changes the typedef of eh_index and/or chain params set n, k to unexpected values?
`assert(CollisionBitLength() + 1 < 8*sizeof(eh_index));
`

Seems simpler to return false since the solution is invalid.
```
assert(X.size() == 1);
return X[0].IsZero();
```

**Comment by str4d** [comment]
> (1) `assert(CollisionBitLength() + 1 < 8*sizeof(eh_index));`

 > Could this assert be triggered if the typedef of eh_index is changed and/or chain params set n, k to unexpected values?

Yes, but the assert is behaving as expected, informing the developer of code they need to examine as part of their changes. It is then the developer's problem if they ignore the assert.

>(2) `assert(X.size() == 1); return X[0].IsZero();`

> Seems simpler to return false if the solution is invalid.

I disagree. This assert will always be true assuming two things:

- The solution has the correct number of indices.
- The validation code is correct.

The first condition is checked at the start of the validator, and can only be false at the assert if there is a code bug. The second condition will be false when there is a code bug. Therefore the assert is informing the developer when there is a problem, as expected.

Think of each assert as checking an invariant. That is, the condition it checks should always be true at that point for all conceivable inputs. Therefore, if the assert failed it indicates that the invariant has been broken, either due to a change in the code or a change in the build system, or some other change outside the expected behaviour.

**Comment by str4d** [comment]
Not how the concept of invariant checking is different from what the OP raised in this issue, which is that some recoverable errors are not handled as such. Those errors do not arise from invariants, but from invalid input or foreseeable problems.

**Comment by bitcartel** [comment]
There was a discussion a while ago on bitcoin-dev about why asserts are not disabled in production: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2014-June/thread.html#5944

So perhaps the answer here is to have two types of asserts:

- One is enabled only in debug builds to catch developer bugs, enforce design by contract, etc.
- Another is enabled in both debug and production builds, to catch critical run-time errors where the application should stop execution.

Exceptions could be used to replace any existing use of assert() where the error is recoverable / non-critical.

**Comment by daira** [comment]
There shouldn't be asserts that are only enabled in debug builds. I don't believe in the concept of switching off assertions in production builds; it just reduces reliability and dies not significantly improve performance. (It also threatens concensus if there are a significant number of debug nodes on the network.)

However, the distinction between "should never fail" consistency assertions and input validity checking is still valuable. The former just should not be spelled "``assert(...)``, because some people expect that to be disabled in production (and their they may include things that are unsuitable for anything other than debugging).

**Comment by daira** [comment]
Also see https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2014-June/005988.html , which I think we should follow.

**Comment by bitcartel** [comment]
Sounds like a good idea.  Perhaps 'expect' and 'ensure' to share consistent language with a C++17 proposal? [stackexchange](http://stackoverflow.com/questions/31317155/what-are-contracts-in-c17), [pdf](http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4415.pdf)

> * [[expects: condition]] for saying that an operation expects condition to hold for a call to
complete successfully
* [[ensures: condition]] for saying that an operation guarantees condition to hold after a
successful call

**Comment by bitcartel** [comment]
Btw, I don't think there is any signal handling to catch abort(), which means bitcoind/zcashd will core dump.  Security issue?

**Comment by daira** [comment]
Preconditions aren't locally verifiable as "cannot happen"; to verify them you would have to verify all code that called that function. This means that they shouldn't be treated as assertions that terminate the program; instead they should cause an exception to be thrown. Postconditions, on the other hand, *may* be locally verifiable (it depends what global state they depend on). I don't think there's much need to distinguish between assertions and postconditions to be honest.

**Comment by zookozcash** [comment]
Hold on, why does not locally verifiable mean we shouldn't terminate the program? I think terminating the program is the safest thing to do in a case like that.

**Comment by ebfull** [comment]
@zookozcash If some invariant is broken based on specially crafted inputs you could turn it into a remote-DoS.

**Comment by zookozcash** [comment]
Things would probably be just as bad and potentially worse if we raised an exception in that case.

**Comment by daira** [comment]
@zookozcash I disagree. Most such cases occur when processing a particular transaction or RPC call. So, the exception can be caught and the transaction treated as invalid, or the RPC call failed with an error. This should not result in any corruption of global state.

**Comment by zookozcash** [comment]
I dunno. It seems to me that most or all such things fall into one of two categories: 

1. The incoming message (transaction or RPC call) is invalid and we can _tell_ that it is invalid. There is no suspicion that our code or our state is at fault.

2. Something else, unexplained, is going on. Maybe our state is inconsistent/corrupt, maybe our code is wrong about the rules of message validity, or maybe the message is invalid but in a way that our validity checks don't detect. We're not sure what exactly happened, only that there is something inconsistent.

To me, case 1 should obviously be handled by rejecting the message. And we have to be very careful that we don't make changes to our state assuming the validity of the message and then forget to revert those changes if we later decide the message is invalid. Of course the best way to do this is to make no changes to the state until the message has passed all validity checks, but when that's not possible, then we at least should have a clear and principled separation of the stages of validation -- i.e. up until here, our code must never assume the validity of xyz, and after this point our code must _always_ assume the validity of xyz. (No double-checking! Double-checking is just giving more opportunities to the attacker, especially if the two checks diverge under code maintenance.)

So, from this perspective, how should we handle case 2? That is, the message has already passed validity checks (or this would be case 1), but something else is inconsistent. From my perspective, this could be part of an attack, and raising an exception is giving the attacker more chances to push the attack further. The safest thing to do is kill the process, which will summon a human and inform the human that an unexplained inconsistency was detected.

I really think we shouldn't follow the traditional adhocery of one programmer coming along and saying "huh, this would be inconsistent, let's raise an exception" and another programmer coming along at a different time and saying "oh, we've already verified the xyz, so we can update the qrs state now".

**Comment by daira** [comment]
Case 2 is more complicated than the message already having passed validity checks. Suppose that an assertion fails while checking a message (indeed, the majority of our assertion checks, including those in libsnark, happen when checking messages -- either incoming transactions and blocks when verifying, or RPC requests when creating a transaction). What should we do about it?

Just halting the node is handing the attacker an easy denial of service. Moreover it probably doesn't help. It *can only* help in the following situation:
* The corruption was ephemeral, i.e. in data structures that are not persisted to disk. If it is persistent, then the same corrupt state will be recreated when the user restarts the node, which is the obvious thing for them to do.
* The corruption was either unintentional, or it was triggered by an attacker but the attacker is constrained in some way that prevents them from just exploiting it immediately to maximum effect.

Remember, if the assertion will always trigger for any transaction/block that attempts to exploit a corruption, then the corruption will be unexploitable *regardless* of whether we discard the transaction or we halt the node (ignoring the denial of service attack from the latter). So that case does not present an argument for halting the node. In order for there to be an advantage from halting the node on detection of possible corruption, it would have to be the case that it halts before an attacker has any opportunity to exploit the corruption. I do not find it very plausible that, for most potential security flaws, avoiding this would be anything other than another minor hoop for the attacker to jump through in making an exploit reliable. Probably, if the corruption is exploitable at all, they can jump through that hoop by putting the corruptor and the payload in the same message. If, on the other hand, we are talking about robustness against non-malicious failures, then discarding messages is probably sufficient and a more robust policy in most cases anyway (taking into account that Bitcoin is designed to be a flooding network in which some messages will be discarded, and some transactions will not verify).

Your point about double-checking is also an oversimplification. The kind of double-checking where there are two ways in to a particular state or functionality, and you have parallel checking for each way in, is clearly bad. For redundant checking (i.e. where something always gets checked more than once -- which we certainly have some instances of in our current code) the situation is more complex. Such checks:
* sometimes result in code being more locally reviewable, and sometimes the opposite;
* increase the total amount of code, which *can* introduce bugs, but rarely (since checking code *should* be side-effect-free);
* can reduce performance, but more often the performance impact is negligable.

So I think they can only be assessed (or distinguished from parallel checking) on a case-by-case basis.

**Comment by daira** [comment]
Note that in a memory-safe language, and especially a language with state rollback on exceptions, my argument would be much stronger still. Obviously you know my biases towards that approach, but I don't think I've relied on them in the above comment, given that we're using C++.

**Comment by daira** [comment]
BTW, please read the first half of my presentation at https://github.com/noether-lang/noether/blob/master/doc/presentations/StrangeLoop2014/handling.pdf for why other error handling approaches (that are available in C++) are typically much more error-prone than exceptions.
