### ISSUE TITLE
Replace SHA256 with BLAKE2s or Skein in the circuit

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#705]
Places in our circuit where we need a secure one-way hash function, which is collision resistant, currently use SHA256. We'd like to replace SHA256 with something which reduces to a smaller QAP whenever possible. I'm unsure if BLAKE2s is truly better than SHA256 in the circuit, but it may match up closely. Skein may even be better. Let's investigate.

**Comment by daira** [comment]
See also #40 (not a duplicate because it is focused on subset-sum hashes, but an alternative).

**Comment by ambiprofin** [comment]
In my honest opinion, choose a GPU/ASIC resistant algo like Argon2(Blake2)

**Comment by daira** [comment]
@ambiprofin This ticket is not about the Proof of Work/mining algorithm. For that see #27.

**Comment by ambiprofin** [comment]
I am aware that this is not about the PoW Algo, This is about the circuit algorithm.

**Comment by ebfull** [comment]
@ambiprofin Why do you think we should use a memory-hard algorithm inside the circuit?

**Comment by ambiprofin** [comment]
NOTE: I am not a cryptologist so please do not laugh or swear if I make mistakes.

1) The same reason why Scrypt was created (http://www.tarsnap.com/) - for the security paranoid
2) There might be lesser chance of collision
3) Any attack methods that involve finding the hash through brute forcing - it will be too expensive on resources

Some notes if choosing memory hard algorithm:

1) No daisy chain! At all, it's basically security through obscurity
2) The algorithm must be memory hard but light on CPU
3) Most importantly, it must work on mobile applications.

**Comment by daira** [comment]
@ambiprofin The purpose of choosing a memory-hard algorithm for PoW would be to avoid mining centralization (which introduces security vulnerabilities to attacks who control a substantial portion of the hash power). The purpose of choosing a memory-hard algorithm for passphrase hashing (the original motivation of scrypt) is that passphrases are typically human-memorable, and humans often find it extremely difficult to remember things with sufficient entropy to resist dictionary and/or rainbow table attacks.

For applications where the input to a hash is chosen randomly and need not be memorable, there's no reason to make the hash expensive, in memory usage or otherwise. All of the hashes used in the Zerocash protocol have an input entropy of at least 256 bits. The hashes used in the circuit in particular need to be very efficient when expressed in the form needed for the zkSNARK proof/verification (a Quadratic Arithmetic Program), and making them memory-hard would be totally impractical in that respect, even if there were a reason to do so.

**Comment by zookozcash** [comment]
I hope that BLAKE2s will have good enough performance inside-the-SNARK-circuit, because I want to use BLAKE2s everywhere else (i.e. outside the circuit — see #706), and I'd like to have only one secure hash algorithm anywhere in our codebase.

Also, I feel very confident about the security of BLAKE2 (see https://blake2.net/acns/slides.html and https://blake2.net/#cr) and I feel very confident that BLAKE2 will be widely understood and accepted by programmers. I'm a teeny tiny bit less confident of that with Skein. Don't get me wrong — Skein is beautiful and I believe it is secure, and it is very well-known among symmetric cryptographers, but won't necessarily be that well-known among random programmers in the coming years. Anyway, I would kind of want to spend a few minutes pondering the consequences in terms of simplicity and familiarity using two different functions in different places, or of using Skein exclusively instead of BLAKE2 throughout or system.

Hm.

So, I hope BLAKE2s comes out to be faster or about as fast as Skein inside the SNARK circuit!

**Comment by ambiprofin** [comment]
Well. in that case Skien512 should do the job

**Comment by ebfull** [comment]
The blake2s compression function is around 26390 constraints, give or take a few. This puts it on par with SHA256, and so the time-performance tradeoff doesn't work in BLAKE2's favor here. (I don't generally believe in performance-security tradeoffs so I defer to others on this subject.)

**Comment by ambiprofin** [comment]
For me, honestly - Security First, Performance Slight Later

**Comment by daira** [comment]
Agreed that blake2s isn't a good tradeoff. Does blake2b have fewer than double the number of constraints as blake2s? If it does, then we could truncate the blake2b output to 256 bits and use a tree arity of 4, or to 204 bits and use a tree arity of 5, given that the blake2b core block transformation has a 1024-bit input.

**Comment by ebfull** [comment]
blake2b has around double the amount of constraints since the state is so large, and it has two extra rounds. :(

**Comment by daira** [comment]
OK. We'll consider this ticket at the engineering meeting today, where I suspect we'll decide to close it.

**Comment by ebfull** [comment]
I haven't tested skein, and zooko is apparently comfortable with that if it helps enough and is worth our time. Since it doesn't change the fundamental crypto much, we could even leave it to much later in our development to consider. So "maybe in 1.0" is my recommendation.

**Comment by ebfull** [comment]
I wasn't able to prototype skein unfortunately, but I suspect it has good performance. Either way, not in 1.0.

**Comment by daira** [comment]
I suggest closing this, because of the options for SNARK-friendly Merkle tree hashes, the other alternatives (Pedersen hashes #2234, MiMC #2233, or a subset-sum hash #40) are all likely to outperform "bit-twiddling" hashes like BLAKE2s and Skein.

**Comment by tromer** [comment]
While algebraic hash functions are attractive for the Merkle tree, there's still the matter of the PRFs in the note.

For example, consider PRF_^addr:
Even if both the zkSNARK and the Merkle hash succumb to progress in discrete log, _destroying_ or _stealing_ notes (making them unspendable by the intended holder) remains infeasible. Such an attack requires the attacker to publish the "true" nullifier, and to compute that the adversary needs a_sk, which is protected by PRF^addr (and the SNARK's statistical zero-knowledge). But if you implement PRF^addr using an algebraic hash function instead of SHA-256 with, you risk opening those additional new attacks.

**Comment by zookozcash** [comment]
@tromer: I believe MiMC is a bit-twiddling hash that wouldn't introduce [this risk](https://github.com/zcash/zcash/issues/705#issuecomment-292384999). (I also believe that risk might be worth tolerating in return for other benefits, but that's a topic for another topic.)

**Comment by zookozcash** [comment]
Closing this ticket because BLAKE2s and Skein wouldn't have any advantage over [the other alternatives](https://github.com/zcash/zcash/issues/705#issuecomment-291163263), when running inside a SNARK prover.

**Comment by daira** [comment]
@zookozcash MiMC is kind-of intermediate between a traditional bit-twiddling hash and an algebraic hash; it's algebraic structure is simpler than most other hashes, but it is using the cubing function in the field effectively just as a nonlinear function, rather than for that structure, and has sufficient rounds that attacks based on the structure should be infeasible.

**Comment by daira** [comment]
The circuit performance of Skein (which is terrible) is discussed in https://github.com/zcash/zcash/issues/2630#issuecomment-341071820
