### ISSUE TITLE
refuse to roll-back past a certain depth prior to the local best tip

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#713]
So thinking about https://twitter.com/zooko/status/683215080859680768 again, makes me think of something else that we could potentially put into Zcash-1.0:

Once there are six 10-minute blocks (or, if we do 2.5-minute blocks, once there are twenty-four, or twenty, or whatever, 2.5-minute blocks), then the node/wallet/miner refuses ever again reorg past the sixth-deepest block.

If there is a re-org deeper than that, there will instead be a hard fork.

**Comment by zookozcash** [comment]
Please read the discussion in https://github.com/zcash/zcash/issues/952.

**Comment by mcelrath** [comment]
Note that such a rule is a strong assumption about the appearance of network partitions.  What happens to the users inside China when the great firewall suddenly stops passing Zcash traffic?

Ideally a coin could heal from such a fork...

**Comment by zookozcash** [comment]
No, it's an assumption about the _desired behavior_ in the case of a long-running network partition.

I posit that there is some depth _K_ such that if the network partition heals after a _K_-block-deep blockchain fork then the desired behavior is for the coin to retain two separate branches.

Let's take your example of China and rest-of-the-world being partitioned. And, let's imagine that Zcash is actually an important medium of exchange, used for wages, purchases, loans, investments, savings, etc.

Now in that scenario, if the partition persists for long enough, then the transactions executed on one blockchain fork get woven into the economy -- people trade other resources for them, make contacts involving them, etc.. Once the network partition ends, throwing away one of the forks would mean blowing away the entire economy on that side -- eliminating everyone's financial state and transferring ownership of everything to whoever owns it on the other side of the partition.

Here's another way to look at it. Suppose there's a shared blockchain between Earth and Mars, and then some cosmic event regards it impossible to communicate between the two planets. We can all tell that the cosmic event is going to last two earth years, and then normal communication will be restored. We all know that Earth has a lot more mining power than Mars. But, you live in Mars. What do you do?

**Comment by mcelrath** [comment]
FWIW @zookozcash I would like to see a coin capable of healing a long-running network partition.  One would expect to see the number of double-spends be small in such a case, but one could build an algorithm to select one side or the other, while retaining the vast majority of non-double-spend transactions, and merge into a single chain.

**Comment by zookozcash** [comment]
Yes! I find that to be a fascinating idea.

**Comment by daira** [comment]
If you retain both forks, then you've duplicated all the notes that existed at the split. This will in practice lead to a collapse in perceived value of those notes on *both* forks, unless there is clear consensus on one of them as the "correct" chain. The latter is what happened for Bitcoin in the March 2013 fork.

**Comment by zookozcash** [comment]
I disagree with that, Daira. In the scenario I'm imagining, both forks have value (on their respective planets, at least). In any case I disagree with "This will in practice lead to a collapse in perceived value of those notes on both forks".

**Comment by daira** [comment]
We don't have two planets. Suppose, for the sake of argument, that we continue to have exchanges from each of the forked currencies to the same fiat currencies. Those exchange rates *will* collapse unless the split is quickly healed. Why would anyone continue to trade a currency at the same fiat value if everyone who previously held it can now trade their coins twice? (If, OTOH, essentially all of the exchanges from one of the forked currencies to fiat shut down, then the other fork has effectively been chosen as "correct".)

**Comment by daira** [comment]
BTW, a shared block chain between Earth and Mars with a 2.5 minute or 10 minute block target is impossible using Bitcoin's protocol, since the speed-of-light communication delay varies between 4 and 24 minutes: http://blogs.esa.int/mex/2012/08/05/time-delay-between-mars-and-earth/

**Comment by ebfull** [comment]
> Why would anyone continue to trade a currency at the same fiat value if everyone who previously held it can now trade their coins twice?

They wouldn't be able to trade their coins twice with the same subset of the population due to the split.

**Comment by ebfull** [comment]
This hypothetical is interesting because it's proving another point entirely.

China can't realistically partition the network even with its great firewall. They would have to go as far as eliminating Zcash networking *domestically* to prevent leaks of the outside network state through covert channels. If they're willing to go that far, network partitioning is the least of our concerns.

**Comment by daira** [comment]
I don't find this a remotely realistic scenario. We're deciding on what Zcash should actually do in the real world, right, not in some science fiction apocolypse?

**Comment by nathan-at-least** [comment]
Here's another angle for consideration which seems realistic to me, the split is permanent (merging isn't apparently feasible), and the value of the two sides may not plummet:

Instead of a communication partition, there's a consensus partition *driven by different desired design goals*. So historical chain, A, splits into B and B', where a sufficient number of participants support each of B and B'.

In the blocksize spectacle, a lot of noise on comment threads seems to pit the potential B and B' as antagonistic camps, but I argue that's clearly not what would happen. Suppose B is "make it more scalable, secure, and decentralized without changing fundamental transaction rules" and B' is "add new fangled privacy preserving smart contracts".

As a holder of A, I *personally value both* of B and B', and will hold both. Maybe I'm a bit more risk averse, so I want to sell some B' for B, and more adventurous DAO-fanatics go all in for B', but keep a bit of B just in case.

If designers worry about miners of each side attacking the other with their resources, we might suppose one fork has a new PoW algorithm, or they both cooperatively select a merged mining system where a single monolithic mining network pays out both B and B' units.

So in this scenario it may be the case that 10 units of A is worth X USD and it turns into 10 units of B *and* 10 units of B' which together are worth more than X USD.

Ok, that was fun, but I'm not sure how it affects this ticket topic, because in such a benevolent fork which sounds consensually planned, there'd probably be special rules around the fork-height which may be an exception to this "don't roll-back past H blocks" rule. Right?

**Comment by nathan-at-least** [comment]
@daira, after https://github.com/zcash/zcash/issues/713#issuecomment-222057446 I looked for an "Interplanetary Use Case" label, but didn't find one. ;-)

**Comment by zookozcash** [comment]
@daira, re https://github.com/zcash/zcash/issues/713#issuecomment-222056946

I don't understand why you mention "the same fiat value". What we're talking about here is the desired behavior of the consensus protocol in the case that a long-running blockchain fork has the option of coming to an end. There are basically two reasons why a long-running blockchain fork could exist:

a) divergent evolution (per @nathan-at-least's https://github.com/zcash/zcash/issues/713#issuecomment-222202198)

b) limitations on communication prevent two sets of nodes from staying in sync (per @mcelrath's China-and-Other in https://github.com/zcash/zcash/issues/713#issuecomment-221997822 or my Earth-and-Mars example in https://github.com/zcash/zcash/issues/713#issuecomment-222044394)

My claim is that in either case, the default behavior of the software should _not_ be to throw away one of the branches, but instead it should be to preserve both branches, because more than likely the humans _want_ to keep both branches at that point, at least until they decide otherwise. If they decide that they _want_ to throw away one branch, they can easily do that simply by switching to some software that ignores the other branch.

My stronger claim is that for a sufficiently long-running blockchain fork, there is a community of people who value and depend on _each_ branch separately, and who would refuse to run software that threw away their economic state. (Unless there isn't, in which case no-one cares and it doesn't matter what the software does.)

**Comment by mcelrath** [comment]
@zookozcash Step one on the path you indicate is to allow a block to have multiple parents.  This could be merging an orphan which contains no conflicting transactions so doesn't need to be discarded, or it could be re-merging a week-long fork.

Beyond some window that is about 2*(network latency or block time), one must consider them separate chains, because otherwise you have a DoS attack (The DoS comes from the graph analysis algorithms which are polynomial in the number of nodes to be considered).  For a large graph that is disconnected like this, my braid algorithms would consider the two sides to be siblings, and the entire network split is one cohort (=block), because you can't tell whether transactions on one side can be time-ordered with respect to a double-spend on the other side.  So an appearance of a double-spend cannot be resolved by ordering.  I suspect there is a better cohort-finding algorithm that considers sub-graphs, which would make this algorithm at best n*log(n).  But, for the number of nodes expected (1-10) even an O(n^3) algorithm is not a huge deal.  A week long split and merge is a DoS vulnerability though without another algorithm...

FYI the algorithm I'm referring to is the one that finds cohorts: defined as a subset of nodes such that all nodes in it are ancestors of all descendants, and all nodes in it are descendants of all ancestors.  A blockchain is an example, and the first nontrival example is a diamond; the two nodes on the sides form a cohort.  These sets of nodes are the points at which *all* nodes can agree on the UTXO set.

So one needs an entirely different algorithm to resolve a split like this, other than simply allowing a block to have multiple parents.  One can decide an ordering by creating a PRNG from data in both chains, but this can also be an attack vector since miners and/or transactors have control of the inputs to your PRNG. (Ethereum uses the low bits of the last block hash as "entropy" and it's wrong -- don't do it)

@amiller and I had an interesting conversation about using oracles and threshold signatures to provide a random source to the chain, which could be used as part of the consensus algorithm.

I really want to bring git fork/merge sematics to blockchains.  I'd like it to be fast and automatic, resolving orphans in the same way it resolves week-long split, quickly, robustly, and fairly.

**Comment by daira** [comment]
@zooko: Six blocks, as mentioned in the description, is *not* a long-running fork. Six blocks is orders of magnitude more likely to be due to a bug, network partition, or attack, than a long-running fork of the kind you're describing. The policy under consideration here would essentially force it to *become* a permanent fork when it would otherwise have had a good chance of healing.

If the threshold were, say, 600 or even 60 blocks, that would be completely different. The Bitcoin fork of 2013, which is the nearest instructive example we have of a fork that was healed, [lasted 24 blocks](https://freedom-to-tinker.com/blog/randomwalker/analyzing-the-2013-bitcoin-fork-centralized-decision-making-saved-the-day/) (at a 10 minute block target time).

**Comment by zookozcash** [comment]
Ok, so if I understand correctly, you agree with my statements about "sufficiently long-running forks", but you don't think 6 blocks (~15 minutes) is sufficiently long-running. I don't either! So we're on the same page again.

**Comment by mcelrath** [comment]
FWIW, I don't like the distinction between "long-running" and "not-long running".  The distinction is a timing assumption, in a system that will be more robust if we remove timing assumptions.  I propose they be handled in *exactly* the same way.

**Comment by zookozcash** [comment]
But Bob, that's the way humans roll! If your software automatically merges a 15-minute fork, everybody will thank you. If it tries to automatically merge a 2-year fork, everybody whose assets and economies would thereby be devastated (which is probably the vast majority of users, if the currency is actually serving as money and not just as a token for gambling) will refuse to run your software and will instead run alternate software that preserves their economy.

Note that if I'm right (which I am), this suggests that the software could estimate the impacts on its user of honoring one fork or the other, or of merging certain forks. This probably sets us out on a path in the general direction of Proof-of-Stake, but I can't see very far ahead on this path and I don't know where it ultimately leads.

**Comment by mcelrath** [comment]
The impending merge of a 2-year fork under well-known rules will cause political action (modification of consensus rules) to prevent it from happening.  I contend this is something you needn't consider.

**Comment by mcelrath** [comment]
The major considerations for the ability to automatically merge chains is that *asset creation is proportional to difficulty*.  That way no miners lose in the merge, their coins are safe.  This is quite different from Satoshi's scheme which attempts to make asset allocation proportional to time, but at a deep level, the value of a crypto-currency is the value of the real-world assets sacrificed to create the cryptographic PoW.

If you accept that, the "only" remaining problem is resolving double-spends...

**Comment by zookozcash** [comment]
Ah yes, I see that we're more-or-less on the same page. I look forward to turning the page with you -- your idea in https://github.com/zcash/zcash/issues/713#issuecomment-222390099 is intriguing but I haven't grokked it yet. However, first I have to go catch a plane...

**Comment by daira** [comment]
@zookozcash I said that I disagreed with the premise of this ticket for forks on the order of 6 blocks. I didn't say I agreed with it for longer forks! One reason not to add such a threshold is precisely the difficulty in defining what value it should have.

Furthermore, consider #171 (disable the RPC interface if you detect you are on the short side of a fork), which is labeled as "in 1.0". If that is implemented, and if the fork is not due to a total communication partition (i.e. nodes on the shorter chain can see the longer chain but don't consider its blocks valid for whatever reason), then that precludes being able to use both chains for transactions unless you're using a modified client. So the argument about both chains having independent economies cannot hold -- there would have to be an explicit new software version for the shorter chain in order for that to happen. (For SPV clients, it would depend what full node(s) they were connected to.)

**Comment by MeniRosenfeld** [comment]
It's an old idea and, while tempting, it's extremely dangerous. You might be interested in my comment from 2012 (https://bitcointalk.org/index.php?topic=130222.msg1392450#msg1392450):

"I call this practice "cementing" and it has some problems, similar to what we would have if there was no blockchain at all. The basic idea is that a node could be stuck on "the wrong version" after being isolated and fed bad data from an attacker, and would have no way to recover even after being exposed to the honest network."

The whole reason we use a blockchain at all is that "most proof of work" is considered more reliable than any other synchronization signal. If a node gets wrong data, it *needs* to have the ability to recover by being exposed to the honest network which has more proof of work (or stake, or whatever). Denying it this ability is just asking for trouble, and diminishes the reliability and robustness of the system as a whole.

Not that the idea can't be worked with, but it's far from a simple patch. For starters, you'd want it to only work on much longer time scales.

**Comment by mechanikalk** [comment]
@daira has an extremely good point here. First, that the economics of having a algorithm driven fork would be catastrophic to the value and usefulness of the coin because of the immediate doubling of supply and the lack of interchangeability.  Second, that determining a time to prevent roll backs from taking place is completely arbitrary, so you shouldn't try and do it. Finally, @zookozcash should be designing Zcash with a maximalist mentality because it will deliver the most utility and value to its users.

**Comment by alfiedotwtf** [comment]
If merging forks is a possibility, how will you prevent "difficulty arbitrage":

When difficulty gets high:

    1. Detach from the global network
    2. Wait for the local difficulty to adjust down
    3. Mine at this lower difficulty
    4. Join the global network with low-difficulty coinbase

**Comment by daira** [comment]
Re: https://github.com/zcash/zcash/issues/713#issuecomment-224859325 , my understanding of the proposal is that an attacked node would, as soon as it sees the much-longer chain, notify its operator and go into a safe mode (it isn't yet clear precisely what safe mode would disable, but it would at least disable submitting new transactions). The issue to be resolved is then how to restart it on the consensus chain. I don't think anyone was suggesting that there should be no way to restart it.

**Comment by mcelrath** [comment]
Imagine a block can name multiple parents.  Then, establish clear rules for merging a minority chain with a majority one.  Any double-spends on the minority chain have to be rejected, and you have to fix-up the allocated coins so that the sum of rewards on both chains matches the expected schedule, perhaps by altering the near-term reward schedule so as not to punish miners on the minority chain.

Difficulty arbitrage (re: @alfiedotwtf ): one must create a reward schedule that doesn't increase the reward/difficulty when the difficulty drops.  One way is to have a "high water mark", (the maximum hashrate ever seen) and that sets the reward schedule, regardless of the actual hashrate.  When a network split occurs, miners on both chains can still be compensated.

I'm glossing over a lot of details here, but I've figured out how to do it and will have it written up in a week or two.  For those interested, I'm talking about it next week: http://onchainscaling.com/presentations.html (it will be an online conference)

**Comment by alfiedotwtf** [comment]
> When a network split occurs, miners on both chains can still be compensated.

Compensating a miner who disconnected on purpose to mine without competition is an attack.

> One way is to have a "high water mark", (the maximum hashrate ever seen) and that sets the reward schedule, regardless of the actual hashrate

You've now created a DoS attack. If a malicious miner pushes up the hashrate locally beyond the global high water mark, you'll lock out the real market at merge time

**Comment by mcelrath** [comment]
@alfiedotwtf A miner who is disconnected due to network delays is not "attacking".  In such a circumstance I'm proposing that his PoW hashes still receive a reward, when reconnected.  But any double spends appearing on his chain would be decided in favor of the main chain.

Re: High water mark.  If you've ever seen a hashrate larger than 200% of the current hashrate, then your coin is insecure, and transactions should never confirm, because an attacker could be building a hidden majority chain.  We can continue adding to the chain in a timely manner, however.  Deciding to have transactions confirm again without reappearance of that extra hashrate is a political decision (that could only come by analyzing where that hashrate came from and whether it's coming back), it shouldn't be a protocol decision.

If an attacker controls 51%, you're screwed no matter what.

**Comment by alfiedotwtf** [comment]
@mcelrath : You seem to be thinking in terms of only preventing the double spend. See Daira's original comment (https://github.com/zcash/zcash/issues/713#issuecomment-222053995). What's the point of worrying about double spending if minting is essentially free?

**Comment by daira** [comment]
@alfiedotwtf That comment was not referring to the same situation. In @mcelrath's proposal, there is a well-defined "majority" chain, and no duplication of coins.

**Comment by effectsToCause** [comment]
Hi I'm the VeriCoin Creator and Lead Developer,

I happened to see this conversation via a github link, and thought this was a quite interesting posit but I do see problems with this.  Largely I suspect the effect in the case of a long fork due to communication loss, would be an increase in the probability of a non-majority fork existing in perpetuity.  This increased probability is now an incentive to manipulate the system.  For instance in the early stage of the network one could attempt to DOS one or some of the supernodes, and on a immature network fracture communication sufficiently long for those nodes over dependent on the supernodes for connection to the network.  Then just mine on a relatively weak consensus network earning significant rewards and potentially holding 51% or greater of the power.  If you could maintain this long enough, you could profit considerably while seeming to just follow the rules for a reorg proof chain.

**Comment by zookozcash** [comment]
I'm thinking about this idea again, because of http://cryptohustle.com/51-attack-crew-extorts-and-hijacks-blockchains-for-ransom .

Attackers defrauded an exchange named Bittrex by depositing their Krypton to that exchange, selling it for BTC, withdrawing the BTC, and then revealing that they had computed a longer fork of the Krypton blockchain which branched from before they deposited the Krypton. That's a classic double-spend attack.

Now, imagine that you are an exchange, and somebody deposits a million dollars worth of ZEC into their account, then sells it for BTC, then asks to withdraw the BTC. What do you do?

My answer is that you wait a certain number of confirmations, `K`, for the deposit of their ZEC, and then you send them the BTC, _and then you support (if necessary) a hard-fork of the Zcash blockchain to blacklist any branch which rolls-back that million-dollar deposit_.

If you have a different answer to what you would do in this situation, I'd like to hear it! If your answer is "I eat the million-dollar loss and go out of business", that's fine with me if that's your choice, but by the rule of natural selection, we can assume that eventually all the businesses that are still in business did not choose that answer.

My contention (in contradiction to a lot of the other comments above on this ticket) is two-fold:

a. Exchanges (and all other sorts of businesses who deal in irreversible transactions) _will do this_ whether we protocol-designers like it or not, and 

b. They _should_ do this. It is correct and beneficial behavior, both for them selfishly and for the community and ecosystem as a whole.

Now how could we change the Zcash protocol to support or deter or modify or guide this behavior?

If we focus our attention as protocol designers on the million dollars, then this leads us in the direction of proof-of-stake. The exchange's willingness to support a hard-fork up to a million-dollars-worth of support can be reified into the protocol using some kind of proof-of-stake-like mechanism.

But for now (especially since a lot of others, notably Ethereum, are pioneering proof-of-stake right now and I kind of want to wait and see what they learn), I'd like to instead focus my attention on the choice of `K`.

I assert that _there exists some number K_, for each victim or for each incoming transaction, whether we protocol designers like it or not, after which the victim will support a hard-fork to roll-back the double-spend attack. We protocol designers cannot cause `K` to be infinite, because we cannot control the users choice to support a hard-fork. (Thank goodness.)

We _can_ leave `K` out of the protocol, so that the explicit function built into the protocol is effectively infinite, and a different kind of coordination and negotiation has to happen outside of the protocol for people to agree on a shared `K` and organize a hard-fork.

But I would like to explore the alternative to that: we _pre-coordinate_ a shared, system-wide default for `K`, where everyone can assume that everyone else will probably go along with a hard-fork if a roll-back exceeds `K`, and can assume that everyone will probably not go along with a hard-fork if a roll-back is shorter than `K`.

Note that _in either case_ the community can subsequently override this by changing the protocol! If we leave `K` as effectively infinite, people can override this by organizing a hard-fork (such as the anti-DAO-attack hard-fork in Ethereum). If we establish a default `K` which is finite, and it gets triggered by a sufficiently long roll-back, and people don't want that, then they can override it by organizing a hard-fork to switch to the new longest chain.

But defaults matter.

**Comment by zookozcash** [comment]
P.S. Frankly, I'm a little bit frustrated with some of the conversations I've had around this topic, in which some people seem to be coming from a theoretical or even ideological perspective, which I think is an insufficient grounding for designing this part of the protocol. Therefore, I have a simple request: _please answer the question_ that I asked in the previous comment, before you tell me your opinion of what the protocol ought to do. The question is: what do you do when you're running a business, and someone sends you a million dollars worth of ZEC, and then asks you to give them something worth a million dollars, irreversibly? _What do you do?_

**Comment by daira** [comment]
What I'm concerned about is that the risks arising from an attacker deliberately provoking the block chain split that occurs instead of a more-than-K-block reorg. @zooko: your assessment of the risks of block chain splits is *fundamentally different* from the people you're arguing with, and I suspect that's part of the cause of your frustration.

**Comment by zookozcash** [comment]
@daira: You didn't answer the question!

You have a million dollars worth of BTC. Someone sends you a payment of a million dollars worth of ZEC (plus a transaction fee incentivizing you to do this) and asks you to send them a million dollars worth of BTC. _What do you do?_

**Comment by daira** [comment]
You require how ever many confirmations you need to be confident that the risk of rollback is negligable.

**Comment by zookozcash** [comment]
Okay, how do you know how many that is?

**Comment by zookozcash** [comment]
I think that answer might lead to a solution to this problem, but not if we stop here! We need to keep going.

**Comment by daira** [comment]
You guess. What other alternative is there?

**Comment by zookozcash** [comment]
There are several alternatives. One is publicly declare that you will blacklist any blockchain fork that rolls back the million dollar payment to you. Additionally, you can offer a reward of up to a million dollars to other people to support your blacklist.

Another might be that we develop a more objective procedure for determining required-confirmations than "you guess".

Another might be that you and a bunch of other people enter into a mutual agreement that you will _all_ blacklist any fork which rolls-back any payment to any of you, as long as the roll-back is more than 36 blocks and the total payments thus lost sum up to greater than 1000 ⓩ.

There might be other alternatives too!

Related: https://github.com/zcash/zcash/issues/132

**Comment by daira** [comment]
Suppose you guess R blocks. There are two cases:
* if R < K, then a double-spend can succeed regardless of whether the "refuse to roll back more than K" is implemented
* if R >= K, then you're protected against a double-spend at least as effectively than if "refuse to roll back more than K" were implemented.

But *you* chose R, which is strictly better than the protocol needing a global K that is chosen independently of *your* risk for a particular transaction.

**Comment by daira** [comment]
Another alternative is that if a million dollars of risk is too much, you limit the *total* transaction volume so that you never have that much at stake within a time window that could plausibly be rolled back. So if someone wants to exchange a million dollars between currencies, they have to do it more slowly, or using multiple services that in aggregate will accept that risk.

**Comment by zookozcash** [comment]
> Suppose you guess R blocks. There are two cases:
> 
>     if R < K, then a double-spend can succeed regardless of whether the "refuse to roll back more than K" is implemented

Agree.

>     if R >= K, then you're protected against a double-spend at least as effectively than if "refuse to roll back more than K" were implemented.

Disagree. Suppose it costs $7500 per block to roll-back. (I got that number by multiplying the current price of Bitcoin — about $600 — by the current Bitcoin miners' reward — 12.5 ⓑ. See http://fc16.ifca.ai/bitcoin/papers/Bon16b.pdf for why that's a reasonable guess for the cost of a roll-back attack. But the precise number doesn't matter for this argument, of course, I just work better with concrete examples.)

Now if your protection is choosing an R ≥ K but not having the "refuse roll-backs" defense, and let's say K is 36 and R is 48, then your protection can be overcome by $360,000 worth of attack from the attacker.

On the other hand, if you have the "refuse roll-backs" defense, i.e. you and everyone else (except the attacker) have a mutual aid pact to blacklist any forks which roll-back deeper than 36 blocks, then your defense cannot be overcome by $360,000 worth of attack from the attacker.

**Comment by zookozcash** [comment]
> Another alternative is that if a million dollars of risk is too much, you limit the total transaction volume so that you never have that much at stake within a time window that could plausibly be rolled back. So if someone wants to exchange a million dollars between currencies, they have to do it more slowly, or using multiple services that in aggregate will accept that risk.

That's a good idea.

**Comment by daira** [comment]
> a mutual aid pact to blacklist any forks which roll-back deeper than 36 blocks

How do you know which fork is the "right" one? In some cases it might be obvious to an impartial observer that one fork is an attack (if it just suddenly appears without those blocks having previously been seen by anyone). But the protocol can't distinguish that case, and so we also have the risk of this mechanism being triggered in other cases, for example due to software bugs such as the Bitcoin leveldb fork. In that case the "refuse rollbacks" mechanism could significantly complicate recovery from the bug.

**Comment by daira** [comment]
Also: why are we innovating here? Bitcoin appears to work fine without such a mechanism, and it isn't particularly related to privacy or decentralisation.

**Comment by effectsToCause** [comment]
Being that the only hard numerical measure proportional to the cost of work is the difficulty, one could reduce risk probability and maximize performance, by setting the number of required confirmations for immutability to be inversely proportional to the difficulty.  This way there is not as much risk in an immature network and it's not too conservative for effective fungibility in a mature network.

**Comment by alfiedotwtf** [comment]
> what do you do when you're running a business, and someone sends you a million dollars worth of ZEC, and then asks you to give them something worth a million dollars, irreversibly

No joke, but I'd think about making a claim on my business insurance. This is the whole business of exchanges - it's their position to take on the market risk.

You're scenario above unfortunately assumes that the attacker is only hitting a single exchange. I'd recon that this attack would work best (i.e. cheapest) when the work put into building a longer forked chain is done once, but all exchanges that accepted the targeted altcoin are extorted at the same time. In this case, exchanges would be playing Prisoner's Dilemma.

**Comment by daira** [comment]
@zookozcash Perhaps part of the cause of disagreement is that you seem to be conflating "a mutual aid pact to blacklist any forks which roll-back deeper than K blocks" with "the protocol refuses to roll back more than K blocks". See https://github.com/zcash/zcash/issues/713#issuecomment-222437833 (which was not addressed) for why the latter can't work_

Note: I am not making any statement *in this comment* about whether the former can or can't work.

**Comment by daira** [comment]
Since this ticket is "not in 1.0", I'm going to stop thinking about it until after launch.

**Comment by daira** [comment]
Peter Todd has mentioned this in https://petertodd.org/2016/cypherpunk-desert-bus-zcash-trusted-setup-ceremony#software-quality as a supposed reason why the Zcash team "doesn’t yet have a solid crypto-currency background". This is of course nonsense; even if we didn't have advisors with extensive Bitcoin and Ethereum experience, you can see from the above discussion that the core team does understand the issues quite clearly, despite some points of disagreement. (Furthermore the case Nathan mentioned in https://github.com/zcash/zcash/issues/713#issuecomment-222202198 actually happened to Ethereum since the ticket was opened.)

**Comment by zookozcash** [comment]
Here's a real world example of the phenomenon I tried to describe in https://github.com/zcash/zcash/issues/713#issuecomment-252502302:

https://github.com/zcash/zcash/issues/713#issuecomment-252502302

Charlie Lee is, in fact responsible for a company that experiences exactly the case I was describing. People deposit millions of dollars of cryptocurrency into his business and then ask him to make irreversible transactions worth millions of dollars.

It should be obvious if you think about it that there is _no way_, once his company has irreversibly sent out those millions of dollars, that it would accept _any other blockchain_ unless that blockchain also has the same transactions which deposited those millions of dollars to the company.

**Comment by daira** [comment]
They don't have a choice. They will have to claim on insurance instead if they are able to, or take the loss.

**Comment by zookozcash** [comment]
> They don't have a choice. They will have to claim on insurance instead if they are able to, or take the loss.

That's just not true. They totally have a choice, and they'll take the choice that _doesn't_ bankrupt their company and screw half of their customers. So will every other company that is in the same position.

**Comment by daira** [comment]
And how are they going to convince the rest of the network that coins on the orphaned chain are worth anything?

Bitcoin and Zcash do not have what Ethereum folks call "economic finality". There are severe obstacles to trying to implement it without making security worse.

**Comment by alfiedotwtf** [comment]
Lets say an exchange performs an action in good faith which later turned into possible future mass loss (insolvency or worse). The company could either take the hit and let nature run its course, or it could try and shield itself by rolling back via an orphaned chain.

Now... what's the difference between this organisation, and an attacker that had a big loss at the track? They too don't want to take any losses.

Once exchanges, other institutions, and attackers have the ability to roll back as normal operations, they are essentially arbiters of a currency. They can risk it all without ramifications. For more examples, see September 2008.

**Comment by nathan-at-least** [comment]
I renamed this to disambiguate from other proposals such as refusing to rollback prior to a given absolute height (which sounds like a checkpoint).

**Comment by daira** [comment]
Provided we don't conflate the refuse-to-roll-back interval with the confirmation interval (IMHO the former should be quite a bit larger than the latter), I'm coming round to this idea. Note that we currently have an assertion that will trigger for a large reorganisation when a wallet has any z-addresses (#1302), and this has not caused any problems so far.

**Comment by nathan-at-least** [comment]
Point of clarification: I only support this proposal if 'refusing to rollback' means firing a klaxxon, halting the node, and telling the user something like:

> A large rollback has been detected. This indicates a substantial change to the network has occurred, which might include a large change in miner policy, a new implementation with different consensus rules, or some other event we cannot anticipate. The only safe thing to do is to freeze this node and you, Oh Human, must figure out what's happening and decide how to proceed. Probably the most likely way to proceed is to install newer or different software.

I *definitely do not* support this feature if it means 'ignore any reorg if the length is greater than some constant then continue operating normally'.

**Comment by nathan-at-least** [comment]
Bumped from 1.0.9, and I've placed this into the Priority 0. Security and Stability project in addition to HF0, because this provides a UX-based protection mechanism that may be relevant prior to a hardfork.

**Comment by str4d** [comment]
Implementation note: while we need to pick an appropriate default because it will become a network-wide default, this will not be a consensus parameter. As with our deprecation policy, individual users can always override the value by re-compiling.

**Comment by str4d** [comment]
In a meeting today, @zookozcash explained that he does not think it is a good idea to provide users with configuration options to try and resolve a large rollback (as I implemented originally in #2463). Instead, the error message should just say something to the effect of "please upgrade", and rollback resolution can be simply implemented as a checkpoint (followed by a reindex). The user then makes a choice of what path to take based on what software version they upgrade to.

We also discussed a more subtle issue: as-implemented, #2463 only limits "simple" rollbacks, where the reorganization happens all at once. It doesn't defend against partial rollbacks (e.g. roll back 50 blocks twice), because this is much harder to detect; for instance, the above rollback could be conducted with a single block, as long as that one block has more work than all 50 other blocks.

The question was raised as to why we can't just remember the highest height ever reached, and freeze blocks that are ever at least K from the tip. This would catch all rollbacks, but would implicitly convert the underlying consensus rules from "most work" to "longest chain", which may break various underlying assumptions in the inherited Bitcoin Core codebase.

**Comment by str4d** [comment]
We decided to stick with the simple rollback limits for now, as the more advanced rollback limits are themselves limited by having sufficient hashpower to create the rollback conditions inside the rollback window (because the parent blocks rolled back to, need to themselves be inside the rollback window).

**Comment by daira** [comment]
@str4d wrote:
> The question was raised as to why we can't just remember the highest height ever reached, and freeze blocks that are ever at least K from the tip. This would catch all rollbacks, but would implicitly convert the underlying consensus rules from "most work" to "longest chain", which may break various underlying assumptions in the inherited Bitcoin Core codebase.

I don't see how this is equivalent to longest-chain; it would still behave like most-work for "short" rollbacks.
