### ISSUE TITLE
switch from ECDSA to Ed25519

### ISSUE THREAD

**Issue by daira** [zcash/zcash#715]
Advantages:
- ~~avoid the malleability problem with ECDSA signatures~~
- avoid side-channel attacks on signing
- avoid attacks on ECDSA based on not-perfectly-random nonces
- reduce reliance on collision resistance for the message hashing
- smaller public keys

(I intended to propose this at the same time as the switch to crypto_box in #558, but that proved more contentious than I had thought it would be.)

[Edit: Ed25519 is  potentially malleable ~~in the same way as ECDSA~~, with the same potential countermeasures, so that's not an advantage. See the Malleability subsection of the main paper at http://ed25519.cr.yp.to/papers.html]

**Comment by ebfull** [comment]
I really want to preserve the following process for interacting with pours and these "ephemeral" keys:

1. User constructs a pour decription and the pour.
2. User can do anything they want with the transaction, including changing fields, inputs, outputs, sequence number, adding new pours, etc.
3. User can sign the transaction.

This can only work if the keys are deterministic or stored somewhere. We were going to use bitcoin's keyring (but namespace the keys so you couldn't accidentally use a key for a pour that you could use for the other keys).

If we use libsodium to do this, we should use its PRNG to deterministically generate the keypair using some information only the signer has, like a_sk, and some other details unique to the pour, such as the serials.

**Comment by ebfull** [comment]
My proposal is that `CWallet` should give us access to a `PourSeed` which, along with sn<sub>1</sub> and sn<sub>2</sub>, seeds libsodium's PRNG to produce the keypair. This will prevent us from needing to provide a<sub>sk</sub> during `signrawtransaction` at the expense of some flexibility.

**Comment by maaku** [comment]
I would suggest not using Ed25519. It has the annoying property that because the certain bits of the private key must take particular values, it is not possible to do BIP-32 like public derivation. If you want a better signing algorithm I would recommend Schnorr as implemented Elements Alpha as a fork of libsecp256k1.

**Comment by ebfull** [comment]
@maaku Thanks for the feedback! We're not concerned about the inability to construct a public derivation for this particular use-case. The public key we're using here is supposed to be ephemeral anyway. Is there any other reason you don't like Ed25519?

**Comment by ebfull** [comment]
I see now that the thread is generally applicable to all ECDSA usage in the protocol. I'm not really sure it's a good idea to strip that out. I think we should only consider switching from ECDSA for the ephemeral key generated to prevent malleability of our pours.

**Comment by real-or-random** [comment]
That's none of my business but if you now have the chance to switch to a better signature scheme, do it. No matter whether EdDSA or Schnorr signatures. And even if the only reason is performance and a better curve. Bernstein's blog has a nice discussion about the problems with ECDSA and the relation of ECDSA, Schnorr, and EdDSA: https://blog.cr.yp.to/20140323-ecdsa.html Of course he recommends switchting to EdDSA but the reasons are valid.
Also, having two signature schemes in the protocol just means more hassle.

**Comment by daira** [comment]
It's still possible to do BIP32-like deterministic generation with Ed25519; just do the private key clamping after the HMAC-SHA512 computation.

**Comment by daira** [comment]
@ebfull wrote:
> If we use libsodium to do this, we should use its PRNG to deterministically generate the keypair using some information only the signer has, like a<sub>sk</sub>, and some other details unique to the pour, such as the serials.

It wouldn't be secure to only use a<sub>sk,i</sub> and the serial numbers, because two submitted Pours *can* have the same serials; they just can't both get into the same valid blockchain (see also #679).

**Comment by ebfull** [comment]
@daira I agree. I suspect most of the pour description would have to appear in the seed.

**Comment by maaku** [comment]
Daira, it is not possible to public derivation.

**Comment by daira** [comment]
@maaku I could be missing something, but I reviewed BIP32 and http://ed25519.cr.yp.to/papers.html and I don't see why public derivation wouldn't work, with appropriate adjustments as I mentioned.

**Comment by daira** [comment]
Note that I was wrong about Ed25519 signatures being inherently nonmalleable.

**Comment by maaku** [comment]
Daira, if you do public key derivation (meaning you don't have access to
the private key), then how can you perform the private key clamping?

You give me a public key. I derive a sub-key from it. At this point I have
no idea what the low-order bits of the private key are, and so don't know
if I need to make an adjustment. And if I do need to clamp, I don't have
access to the private key to do so.

**Comment by zmanian** [comment]
Do key pubic key derivation on ed25519 would you just insert between these BIP32 steps

Split I into two 32-byte sequences, IL and IR.

_Clamp IL to IL mod 8 = 0_

The returned child key Ki is point(parse256(IL)) + Kpar.

**Comment by gmaxwell** [comment]
> avoid side-channel attacks on signing
> avoid attacks on ECDSA based on not-perfectly-random nonces
> reduce reliance on collision resistance for the message hashing
> smaller public keys

These are not advantages of ed25519, they're properties of some particular implementations; except for the collision resistance comment-- which is also optionally available in the schnorr implementation for secp256k1 in libsecp256k1; but it comes at a considerable cost for bitcoin like applications, because it precludes sharing hashing operations for multiple signatures on the same transaction. Sharing those costs is required to avoid worst case verification cost which is quadratic in the size of the transaction.

> Clamp IL to IL mod 8 = 0

This is potentially ambiguous. I assume you mean "set the three least significant bits to zero".

This procedure still leaves the result incompatible with many 25519 implementations, which I believe require the most significant bit of the private key be set as part of their approach to side-channel resistance (their 'unified' addition law is unable to handle the point at infinity, and so it must guarantee the ladder starts off with 1 not infinity).  This can be easily avoided (just don't use this technique) but it would make these keys incompatible with common software. 

Separately,

The result of such a change would also generally result in slower verification, especially once the GLV patent expires.

**Comment by daira** [comment]
@maaku The clamping is equivalent to a cofactor multiplication with a cofactor of 8. The purpose of this is to force public keys to be in the 251-bit prime order subgroup. Since the parent key is already in that subgroup, the publically derived subkey will also be in the subgroup.

**Comment by carryforward** [comment]
I think I removed malleability in our library.  (at least from those without the private key)

https://github.com/FactomProject/ed25519/commit/dadf2ec666e4abca02e8275370686855b9e419cf

The complaint about having a valid signature for two different pubkeys is kind of moot in this space, since valid sigs from pubkeys without coins do not have interesting attacks.

**Comment by daira** [comment]
I'm not aware of any proof that the check implemented there ensures nonmalleability for Ed25519. (It's obviously necessary, but is it sufficient?)

**Comment by ebfull** [comment]
Our protocol specification currently outlines the use of secp256k1 for preventing malleability of `JoinSplit`s and cryptographically binding them to transactions. In particular, it states that we use a "compact" 64-byte representation of signatures.

Zcash uses OpenSSL's secp256k1 implementation for verification, as we're based on Bitcoin Core 0.11.2 which was tagged _before_ `libsecp256k1` was used for verification in Bitcoin Core. There are two problems with our copy of `libsecp256k1`:

1. It does not offer an API for compact signature verification.
2. It is buggy and out of date.

It is not trivial to update our copy of `libsecp256k1` because the changes made by upstream to introduce and maintain its integration in the codebase are complicated, non-linear and difficult to follow. We could hack around and add a parser or something but I don't think any of us want to maintain that.

This forces us to use the `OpenSSL`/`libsecp256k1` combo-abstraction in older Bitcoin code with some changes to fit the format described in the specification. That isn't too big of a deal if we _really_ want to keep using secp, but I personally would prefer that we navigate around this mess and further that we don't use OpenSSL for even *more* things.

I propose that we use Ed25519, which I've already [implemented](https://github.com/zcash/zcash/compare/zc.v0.11.2.latest...ebfull:35b03a5b661a01bef48519599de82297c6727bf8) on top of @defuse's #964 (along with bugfixes and test changes). It shouldn't be a huge burden to change the specification since this part of the protocol is relatively isolated.

## Simplicity

* Adopting Ed25519 means that we can eliminate a hash invocation in our protocol specification that we were using to fit the secp public keys snug in the h_sig block. This is done in my branch.
* libsodium's ed25519 API is simpler to reason about and integrate for our use case. It's also used in a lot of other projects. It should be easier for us to review its integration.
* We will be using the same RNG that we use elsewhere for our primitives since we use libsodium's RNG anyway.
* Slightly smaller public keys! :tada:

## Malleability

[This discussion](https://github.com/CodesInChaos/Chaos.NaCl/commit/2c861348dc45369508e718aa08611c53b53553db#commitcomment-8036373) suggests we're concerned with one canonical check to prevent malleability: `S` must be smaller than the group order. In fact, upstream libsodium [adopted](https://github.com/jedisct1/libsodium/commit/4099618de2cce5099ac2ec5ce8f2d80f4585606e) this check previously but [removed](https://github.com/jedisct1/libsodium/commit/cb07df046f19ee0d5ad600c579df97aaa4295cc3) it to maintain backwards compatibility. They were planning on adding an API for it but haven't gotten around to it yet.

In the mean time, other cryptocurrencies (NXT/Ripple/Stellar) that use ed25519 use the malleability patch in that commit. I've [integrated](https://github.com/ebfull/zcash/commit/35b03a5b661a01bef48519599de82297c6727bf8) it into my branch as a hard consensus rule.

**Comment by gmaxwell** [comment]
> It does not offer an API for compact signature verification.

That is not true.

> upstream to introduce and maintain its integration in the codebase are complicated, non-linear and difficult to follow

I guess thats a matter of taste, but the update from what Bitcoin Core had in 0.11.1 to now was a single pull request. IIRC.

As a competing system, I hope you do not use libsecp256k1, however.

**Comment by zookozcash** [comment]
FWIW, @gmaxwell, I think Zcash and Bitcoin Core are more complementary than competitive, at least for the forseeable future.

**Comment by gmaxwell** [comment]
That comment was at least half in jest. :P

**Comment by nathan-at-least** [comment]
Note: we're not going to alter the signature scheme for transparent / upstream / Bitcoin-style signatures, but we intend to use Ed25519 for a specific case in #977.

**Comment by chr15m** [comment]
@daira @ebfull I thought you might be interested in [BIP32-Ed25519 Hierarchical Deterministic Keys over a Non-linear Keyspace](https://ieeexplore.ieee.org/document/7966967/) which seems to address some of the deterministic key difficulties raised in this ticket.

abstract:
> We show how to adapt the Bitcoin BIP32 proposal for deterministic key generation for the Ed25519 curve which has non-linear key space.

**Comment by daira** [comment]
It seems unlikely to me that we will ever change from ECDSA for transparent signatures. The purpose of transparent functionality was a) to be compatible with Bitcoin; b) as a performance hack while shielded functionality was too expensive (solved with Sapling); and c) to avoid functionality regressions for things that couldn't be done as shielded (mainly multisig, which is likely to be solved soon). It is a higher priority to remove transparent addresses entirely than to switch them to a different, compatibility-breaking signature scheme &mdash; even if Bitcoin were to do the latter.

**Comment by zmanian** [comment]
Strong agree to close this.

Ed25519 is a bad choice to user signatures. It's a reasonable choice for consensus signatures.

Secp256k1 or Ristretto or BLS12_381 are all much better choices.

**Comment by maaku** [comment]
Ristretto *is* Ed25519. It's a way of implementing a prime-order group on top of Curve25519, not a new curve entirely.

**Comment by str4d** [comment]
@maaku Ristretto (specifically ristretto255) is _not_ Ed25519. ristretto255 is a prime-order group with unique encodings for all group elements, that supports group element addition and subtraction (and therefore scalar multiplication). It can be implemented using Curve25519 points internally (so that arithmetic from existing Ed25519 implementations can be reused), but it is also possible to implement ristretto255 using a different curve internally.

See the ristretto255 Internet Draft https://tools.ietf.org/html/draft-hdevalence-cfrg-ristretto-00 for more details.

**Comment by maaku** [comment]
Yes, it can be implemented with other curves internally. My point in the context of this thread was more that it is not definitionally a separate curve and saying "Ristretto is a better choice [than Ed25519]" is a bit nonsensical. Ristretto didn't exist when this thread started, but from the context of today "switch from ECDSA to Ed25519" would probably be realized in the form of Ristretto on top of Curve25519, since that is the state of the art for that shared curve.

**Comment by daira** [comment]
The relevant question for this ticket is just whether to switch away from ECDSA for transparent signatures. (If we did, it would likely be to aggregrated RedJubjub.) The answer is that it's exceptionally unlikely that we would do that for the reasons [given above](https://github.com/zcash/zcash/issues/715#issuecomment-457821090). Closing.
