### ISSUE TITLE
one CPU maxed out to 100%, strace shows endless nanosleep 0

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#717]
https://gist.github.com/justindthomas/bc586d91cc497c43fdd4

```
<zooko> *sigh*
<zooko> I can't believe in 2016 I'm dependent on a C++ codebase with
	pre-emptive multithreading.
* zooko cries
```

**Comment by daira** [comment]
^ that was an incorrect ticket reference

**Comment by zookozcash** [comment]
https://forum.z.cash/t/what-is-the-expected-cpu-resource-consumption-of-zcashd/508

**Comment by str4d** [comment]
https://forum.z.cash/t/what-is-the-expected-cpu-resource-consumption-of-zcashd/508/15 sheds some light on the problem: it seems that zcashd is [getting stuck in `addrman.cpp`](/zcash/zcash/blob/zc.v0.11.2.latest/src/addrman.cpp#L334) inside a `while (1) {}` loop that only exits when a random integer exceeds an increasingly-weighted "selection chance" of a randomly-selected address in a randomly-selected bucket. My guess is that our buckets are much emptier than Bitcoin Core either because our testnet architecture is much more centralised or because there are many fewer participants, and it is therefore taking much longer to satisfy the exit requirements.

**Comment by daira** [comment]
This may explain why upstream thought the problem was fixed: https://github.com/nvmd/bitcoin/issues/3 says that it regressed in a PR that was intended to mitigate Eclipse attacks.

**Comment by daira** [comment]
I believe this is fixed.
