### ISSUE TITLE
Add reserved field in the block header that could potentially be used for merged mining

### ISSUE THREAD

**Issue by maaku** [zcash/zcash#724]
Merged mining in Bitcoin is implemented by sticking a commitment to the auxiliary block headers in the coinbase or other transaction. This is suboptimal for the chain being merged mined because aux headers of that chain require log(N) hashes where N is the number of bitcoin transactions in that block, something which is entirely meaningless to the merged mined chain.

A better approach, and one Bitcoin would have used if this had been thought up in advance, is to have the block header commit to a tree of blocks, with a fixed path through that tree for each chain. A Merkle patricia trie, for example. This allows efficient merged mining with minimal impact to both chains.

Since zcash is using its own proof of work, it should take advantage of this opportunity to enable proper merge mining for any future sidechains which reuse the same PoW algorithm.

**Comment by daira** [comment]
I suggest "not in 1.0".

**Comment by ebfull** [comment]
I honestly think this feature would be pretty cool and helpful for others, but it takes a backseat to other more pressing tasks unfortunately.

**Comment by ebfull** [comment]
I have changed my mind on this suddenly and feel more of a moral obligation for us to do this, in the event that our proof-of-work can "save" Bitcoin from a catastrophic failure such as rapid centralization or an attack on their network.

Am I correct in thinking that only a small, unused portion of the blockheader could be set aside for this purpose? That we wouldn't really need to implement anything else?

**Comment by daira** [comment]
Clarification: what is in 1.0 is just a 256-bit reserved field in the block header, with no defined semantics. This will not necessarily ever be used for merge-mining.

**Comment by str4d** [comment]
Below are the current and proposed block header layouts. Recall that we are still using double-SHA256 for hashing the block header, so the input is broken into 64 byte chunks.

## Bitcoin Core block header

<table>
 <tr>
  <td colspan=7>Block header</td>
  <td rowspan=4>Padding</td>
 </tr>
 <tr>
  <td colspan=6>Block header candidate</td>
  <td rowspan=3>Nonce</td>
 </tr>
 <tr>
  <td rowspan=2>Version</td>
  <td rowspan=2>Previous hash</td>
  <td colspan=2>Merkle root</td>
  <td rowspan=2>Time stamp</td>
  <td rowspan=2>Bits (difficulty)</td>
 </tr>
 <tr>
  <td>Head</td>
  <td>Tail</td>
 </tr>
 <tr>
  <td>4 B</td>
  <td>32 B</td>
  <td>28 B</td>
  <td>4 B</td>
  <td>4 B</td>
  <td>4 B</td>
  <td>4 B</td>
  <td>48 B</td>
 </tr>
 <tr>
  <td colspan=3>Chunk 1</td>
  <td colspan=5>Chunk 2</td>
</table>

Recall that this header layout is vulnerable to [AsicBoost](http://www.asicboost.com/) because chunk 2 does not depend on the contents of chunk 1, and thus a range of alternatives for chunk 1 can be tried against a single chunk 2 (either by colliding the last 4 bytes of the Merkle root, or tweaking the leading bits of `previousHash`).

## Zcash z4 block header

<table>
 <tr>
  <td colspan=10>Block header</td>
  <td rowspan=4>Padding</td>
 </tr>
 <tr>
  <td colspan=6>Block header candidate</td>
  <td rowspan=3>Nonce</td>
  <td colspan=3>Solution (<code>k = 5</code>)</td>
 </tr>
 <tr>
  <td rowspan=2>Version</td>
  <td rowspan=2>Previous hash</td>
  <td colspan=2>Merkle root</td>
  <td rowspan=2>Time stamp</td>
  <td rowspan=2>Bits (difficulty)</td>
  <td rowspan=2>Head</td>
  <td rowspan=2>Mid</td>
  <td rowspan=2>Tail</td>
 </tr>
 <tr>
  <td>Head</td>
  <td>Tail</td>
 </tr>
 <tr>
  <td>4 B</td>
  <td>32 B</td>
  <td>28 B</td>
  <td>4 B</td>
  <td>4 B</td>
  <td>4 B</td>
  <td>32 B</td>
  <td>20 B</td>
  <td>64 B</td>
  <td>45 B</td>
  <td>19 B</td>
 </tr>
 <tr>
  <td colspan=3>Chunk 1</td>
  <td colspan=5>Chunk 2</td>
  <td colspan=1>Chunk 3</td>
  <td colspan=2>Chunk 4</td>
</table>

This is not vulnerable to an AsicBoost-style algorithm, because chunk 2 contains 20 bytes of the Equihash solution, which depends on chunk 1 (more precisely, it depends on the entire block header candidate plus the nonce).

## Proposed Zcash block header

<table>
 <tr>
  <td colspan=12>Block header</td>
  <td rowspan=4>Padding</td>
 </tr>
 <tr>
  <td colspan=7>Block header candidate</td>
  <td colspan=2>Nonce</td>
  <td colspan=3>Solution (<code>k = 5</code>)</td>
 </tr>
 <tr>
  <td rowspan=2>Version</td>
  <td rowspan=2>Previous hash</td>
  <td colspan=2>Merkle root</td>
  <td rowspan=2>Reserved field</td>
  <td rowspan=2>Time stamp</td>
  <td rowspan=2>Bits (difficulty)</td>
  <td rowspan=2>Head</td>
  <td rowspan=2>Tail</td>
  <td rowspan=2>Head</td>
  <td rowspan=2>Mid</td>
  <td rowspan=2>Tail</td>
 </tr>
 <tr>
  <td>Head</td>
  <td>Tail</td>
 </tr>
 <tr>
  <td>4 B</td>
  <td>32 B</td>
  <td>28 B</td>
  <td>4 B</td>
  <td>32 B</td>
  <td>4 B</td>
  <td>4 B</td>
  <td>20 B</td>
  <td>12 B</td>
  <td>52 B</td>
  <td>64 B</td>
  <td>13 B</td>
  <td>51 B</td>
 </tr>
 <tr>
  <td colspan=3>Chunk 1</td>
  <td colspan=5>Chunk 2</td>
  <td colspan=2>Chunk 3</td>
  <td colspan=1>Chunk 4</td>
  <td colspan=2>Chunk 5</td>
</table>

Chunk 2 no longer contains any part of the Equihash solution, but this should still not be vulnerable because the solution in chunk 3 still depends on all preceding content (including all of chunks 1 and 2).
