### ISSUE TITLE
Ensure Spec mitigates Double Spending by Colliding InternalH

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#738]
I think I found an attack that would let an attacker create as much money as they want for themselves at the cost of finding 128-bit hash collisions.

**Background:** A coin is a tuple (a<sub>pk</sub>, v, ρ, r). The coin commitment CoinCommitment((a<sub>pk</sub>, v, ρ, r)) is computed as:

>InternalH = Leading128(CRH(a<sub>pk</sub> || ρ))
>k = CRH(r || InternalH)
>cm = CRH(v || k)

The truncation of InternalH is done to make the commitment statistically-hiding, i.e no matter how much computational resources I have, I can't find out what v or a<sub>pk</sub> are.

**Attack:** Because InternalH is only 128 bits, in 2^64 operations I can find some ρ != ρ' such that:

> Leading128(CRH(a<sub>pk</sub> || ρ)) = Leading128(CRH(a<sub>pk</sub> || ρ'))

And therefore:

> CoinCommitment((a<sub>pk</sub>, v, ρ, r)) = CoinCommitment((a<sub>pk</sub>, v, ρ', r))

To carry out a double-spend attack I first acquire some real Zcash (e.g. by buying it with USD), and then double spend it to myself as follows. Ignoring the faerie gold fix, I create a new coin for myself, but as I do so I make sure to find a collision (a<sub>pk</sub>, v, ρ, r) and (a<sub>pk</sub>, v, ρ', r) where ρ != ρ'. By completeness of the protocol, I'll be able to spend the (a<sub>pk</sub>, v, ρ, r) coin, and so that's what I do. This will reveal the serial number PRF<sup>sn</sup><sub>a<sub>sk</sub></sub>(ρ). After that first spend has made it on to the ledger, as far as I can see, nothing prevents me from spending that coin *again*, using ρ', because:

- I can still give a path from the root to CoinCommitment((a<sub>pk</sub>, v, ρ', r)), namely the same path as I gave in the first spend (and because of the zero-knowledge property nobody will know the path is the same).

- With high probability PRF<sup>sn</sup><sub>a<sub>sk</sub></sub>(ρ') is not equal to PRF<sup>sn</sup><sub>a<sub>sk</sub></sub>(ρ), and I can obviously still prove I computed PRF<sup>sn</sup><sub>a<sub>sk</sub></sub>(ρ') correctly inside the pour.

- I can still satisfy spend authority (I know a<sub>sk</sub> for the a<sub>pk</sub> I used).

- I have to use the same r (old) for both spends (otherwise the commitments won't collide), but again because of the zero-knowledge property I don't think anyone (except for me, the holder of a<sub>sk</sub>) can tell it's been reused.

After the faerie gold fix, I'm forced to find colliding ρ by altering h<sub>sig</sub>, and I'm forced to commit to either ρ or ρ' because h<sub>sig</sub> gets published. This doesn't prevent the attack, since when I go to spend for the second time it is not going to be noticed that ρ' doesn't match the old h<sub>sig</sub>, at least not according to the current protocol.

**Fix:** Maybe CoinCommitment needs to be collision-resistant? Or maybe we should re-use h<sub>sig</sub> as a commitment to ρ and check it when I try to spend with ρ?

**Comment by defuse** [comment]
In other words, CoinCommitment() isn't computational binding, and the above attack is a consequence of that.

**Comment by daira** [comment]
Yes, this appears to work. Excellent catch!

> After the faerie gold fix, I'm forced to find colliding ρ by altering h<sub>Sig</sub>

Or φ.

**Comment by ebfull** [comment]
Awesome find @defuse!

I was also [suspicious](https://github.com/zcash/zcash/issues/704#issuecomment-178690032) of the security of that function but didn't realize there was an attack at the time.

**Comment by daira** [comment]
In the proof of Balance in section D.3, the attack violates either Condition I, if the double-spend is within a single Pour (i.e. the doubled coin is spent in both inputs), or Condition II, if the double-spend occurs across Pours.

For Condition I, the failure is here:
> (i) If cm<sup>old</sup><sub>1</sub> = cm<sup>old</sup><sub>2</sub>, then the fact that sn<sup>old<sup><sub>1</sub> = sn<sup>old</sup></sub> implies that the witness a contains two distinct openings of cm<sup>old</sup><sub>1</sub> (the first opening contains (a<sup>old</sup><sub>sk,1</sub>, ρ<sup>old</sup><sub>1</sub>), while the second opening contains (a<sup>old</sup><sub>sk,2</sub>, ρ<sup>old</sup><sub>2</sub>)). This violates the binding property of the commitment scheme COMM.

For Condition II, the failure is here:
> However (as argued already above), if both transactions spend cm but produce different serial numbers, then the corresponding witnesses a, a contain different openings of cm. This contradicts the binding property of the commitment scheme COMM.

(Note that the proofs should really be distinguishing between COMM<sup>r</sup> and COMM<sup>s</sup> since they are different constructions, but we'll let that pass for now.)

Let's look at whether the above arguments actually follow from the definition of binding for a commitment scheme. Note that the Zerocash paper doesn't define binding at all; it only says:

> Statistically-hiding commitments. We use a commitment scheme COMM where the binding property holds computationally, while the hiding property holds statistically. It is denoted {COMM<sub>x</sub> : {0, 1}<sup>∗</sup> → {0, 1}<sup>O(λ)</sup>}<sub>x</sub> where x denotes the commitment trapdoor. Namely, to reveal a commitment cm to a value z, it suffices to provide z and the trapdoor x; then one can check that cm = COMM<sub>x</sub>(z).

Finding a precisely-stated definition of computational binding security was suprisingly time-consuming. Wikipedia [gives a silly definition](https://en.wikipedia.org/wiki/Commitment_scheme#Defining_the_security_of_commitment_schemes) that I won't confuse you with. (Exercise: beside being asymptotic, what else is wrong with it?) Definition 24.1 in http://www.zurich.ibm.com/~cca/sft13/smart08chaps2426.pdf is good though:

> A commitment scheme is said to be [computationally] binding if no [computationally bounded] adversary can win the following game.
> • The adversary outputs a value c, plus values x and r which produce this commitment.
> • The adversary must then output a value x′ ≠ x and a value r′ such that C(x, r) = C(x′, r′).

(r is the randomness, x is the committed value.) COMM<sup>r</sup> would have this binding property if Leading128 . CRH were collision-resistant, but obviously, that doesn't hold at a 128-bit security level. (Actually, we need that the composition of COMM<sup>r</sup> and COMM<sup>s</sup> is binding on all of the inputs, i.e. a<sub>pk</sub>, ρ, and v, but the problem in this attack is with COMM<sup>r</sup>.)

Note that collision resistance of Leading128 . CRH was *not* explicitly assumed in the construction of COMM in section 5.1. (Even if we didn't need that, we would still need Leading253 . CRH to be collision-resistant, because of the truncation of h<sub>Sig</sub> and ρ.)

**Comment by daira** [comment]
So let's see: we need to commit to a<sub>pk</sub>, ρ, and v, which are a total of 256+256+64 = 576 bits. It's questionable whether we actually need the statistical hiding property, or whether we can get it (note that the scheme must also be noninteractive, which rules out some constructions in the literature) at reasonable circuit cost. Note that we don't have "everlasting anonymity" because of the encryption. If we only need computational hiding and computational binding, then we could just do:

InternalH = CRH(a<sub>pk</sub> || ρ)
cm = CRH(v || r || InternalH) where r is 192 bits

**Comment by daira** [comment]
Another option is to use the full SHA-256 hash:

cm = SHA-256(a<sub>pk</sub> || ρ || v || r)

(Length extension attacks aren't a problem here.) This also requires two compression function evaluations but leaves more scope for possible future changes, because we're effectively saving 256 bits from the input to the second compression function (minus the minimum one byte of padding) by putting it in the chaining variable.

**Comment by defuse** [comment]
Using two hashes or full SHA256 would be nicer because we could have better domain separation between things, and not have to worry as much about things like this: https://github.com/zcash/zcash/issues/500#issuecomment-187846788

**Comment by daira** [comment]
I'm inclined to use the full hash for this. It isn't very much more complicated or expensive to implement the full hash in the circuit.

That leaves the question of whether we're also going to change the PRFs to use the full hash. Either way, there's still a domain separation issue: if we don't change the PRFs, then the IV will be the same for a use of the bare compression function and a use of the full hash (i.e. the intermediate chaining variable between the two blocks of the full hash will be the same as the output of some use of the bare compression function). This is fixable if we put the domain separation tag at the beginning.

Changing the PRFs to use the full hash means that we only have 504 bits of input available rather than 512, due to the padding. This is not necessarily a problem; we could truncate a<sub>sk</sub> and φ to 244 bits (4 bits of domain separation, 8 bits padding) without significant loss of security, since those values do not need collision resistance.

If the Merkle tree sticks with the SHA-256 compression function, then there seems little motivation to change the PRF to use the full hash. If we change the Merkle tree to something else then I'd like to get rid of the only remaining use of the bare compression function for the PRF.

**Comment by daira** [comment]
(Strictly speaking, full SHA-256 takes a bit string input and so we could hash 511 bits in a single compression function evaluation. Maybe we should do that; most SHA-256 implementations do not support bit string inputs but that's not really a problem.)

**Comment by paragonie-scott** [comment]
Instead of SHA-256, could SHA-512/256 be used? :)

**Comment by daira** [comment]
@paragonie-scott Thanks for the suggestion, but we don't have a zk-SNARK circuit implementation of SHA-512, and I suspect it has similar circuit complexity to SHA-256 with two blocks of input, in any case.

**Comment by daira** [comment]
This is fixed in the current spec (not in the current implementation).

**Comment by daira** [comment]
There's a variation of the attack that I overlooked, where you collide InternalH by varying a<sub>pk</sub>, without necessarily changing ρ. (It's sufficient to know both corresponding a<sub>sk</sub>; the serial numbers / nullifiers will be different because a<sub>sk</sub> is the key input to PRF<sup>sn</sup>.) Our new note commitment scheme blocks that variation as well.
