### ISSUE TITLE
Specify transaction expiry at a given blockheight

### ISSUE THREAD

**Issue by daira** [zcash/zcash#754]
This is now a design ticket, and does not include implementation.

[This comment about address revocation](https://github.com/zcash/zcash/issues/716#issuecomment-182162636) suggests a "time to live" for transactions, after which the transaction creator can be sure that it won't get into the blockchain if it hasn't already done so (and after which nodes can safely drop the transaction from their mempools). Independently of address revocation, this seems useful to mitigate problems such as that described in http://forums.prohashing.com/viewtopic.php?f=4&t=762 . 

(Aside: I'm not sure how much to take that post at face value, because it seems to me that double-spending a coin/TXO spent in a previously submitted transaction guarantees that only one of the transactions will succeed, and is sufficient to solve the immediate issue there.)

**Comment by zmanian** [comment]
I'm of the opinion that adding an expiration blockheight field to transactions and the respective consensus rule would be a positive enhancement over the base bitcoin protocol.

This would provide a clear rule for dropping txs that are not being selected by miners from the mempool. This would be helpful situations like current Bitcoin conditions where there are a glut of transactions in the mempool that are unlikely to ever confirmed.

This has the added benefit of simplifying bidirectional payment channel protoocols because it reduces the need to for  scheme for storing and compressing revocation tokens for past states.

**Comment by nathan-at-least** [comment]
@zmanian we just decided not to put this in our launch feature set, but we are considering a future protocol upgrade with this feature.

**Comment by daira** [comment]
In https://medium.com/@bramcohen/how-wallets-can-handle-transaction-fees-ff5d020d14fb#.goms0kbs2 Beam Cohen wrote:
> [...] Unfortunately right now the only way to make sure that a transaction is permanently failed is to spend its input on something else, but that requires spending a transaction fee on the canceling transaction, which of course would be just as big as the fee you weren’t willing to spend to make the real transaction go through in the first place.
>
> What’s needed is a protocol extension so a transaction can make it impossible for it to be committed once a certain block height has been reached. The current lack of such an extension is somewhat intentional because there are significant potential problems with transactions going bad because a block reorganization happened and some previously accepted transactions can’t ever be recommitted because their max block height got surpassed. To combat this, when a transaction with a max block height gets committed near its cutoff it’s necessary to wait a longer than usual number of blocks to be sure that it’s safe (I’m intentionally not giving specific numbers here, some developers have suggested extremely conservative values). This waiting is annoying but should only apply in the edge case of failed transactions and is straightforward to implement. The really big problem is that given the way Bitcoin works today it’s very hard to add this sort of extension. If any backwards-incompatible change to Bitcoin is done, it would be a very good idea to use that opportunity to improve Bitcoin’s extension mechanisms in general and this one in particular.

(I don't agree with everything in the article but I do agree with this.)

**Comment by bitcartel** [comment]
Currently a transaction's nLockTime specifies the block height from which a miner can include a transaction.  A new transaction format and consensus rule could require including an expiry height.  This would enable wallets and service providers to provide a valid block range for miners to include a transaction, and opportunities to improve the user experience e.g. "The network did not complete your transaction."... "Would you like to try again?" ... "Would you like to increase the network fee? (we recommend X)"

**Comment by zookozcash** [comment]
Please see motivation and discussion of two issues on https://github.com/zcash/zcash/issues/2166

The two issues are:

* Reorg-safety; I just don't see why this is important. If I'm missing something someone tell me.
* Requires hard fork; It requires a hard fork to do it the clean and simple way.

**Comment by daira** [comment]
If we had FlexTrans, then there would be no reason at all to do it with a hard fork. We'd just add an optional transaction field specifying a maximum block height, that would be ignored by previous versions and enforced by the new version.

Now, because FlexTrans is a more involved change, we might want to do this one first. But I hope that it will make things like this easier in future.

**Comment by daira** [comment]
On #2166 @zookozcash wrote:
> Bitcoin upstream has a policy of not adding features that would lose "reorg-safety", meaning that a transaction that got mined should also be valid on a reorged blockchain of the same height. I don't see why "reorg-safety" is important. I think being able to manage the case that your transaction isn't getting mined is more important.

I'm a bit confused because "reorg-safety" so-defined is obviously not a property that holds in general for Bitcoin. For example, you might have transactions A and B that spend the same input; first A gets mined and excludes B, then a reorg happens, and B gets mined excluding A.

This seems to be well-known, e.g. in https://raw.githubusercontent.com/bramcohen/NotValidAfter/master/Transaction_expirations.txt :
> While waiting for some number of blocks to pass after a transaction has been committed before accepting it is prudent, an extra level of precaution should be taken for transactions which have high potential in a history reorganization to become not only not committed, but permanently not committable. All transactions have the potential to have this happen if there's a conflicting double-spend, but in practice when there have been even very deep reorganizations the overwhelming majority of historical transactions got recommitted to the new history.

... and that would still be true with transaction expiration.

https://bitcoin.stackexchange.com/questions/43180/is-there-any-way-to-make-a-transaction-invalid-if-it-is-not-confirmed-before-a-c/43181#43181 says:
> If you make a transaction that can only be included before a certain block number, and then a fork occurs that makes a chain that doesn't include it before the designated block number, then that transaction gets reversed and so do all transactions that depend on the base transaction.

Well yes, but in Zcash that's already the case, whenever an anchor that was referred to by a JoinSplit gets invalidated. So we need not worry about transaction expiration being the first feature to allow this; users of Zcash must be able to deal with it already.

**Comment by nathan-at-least** [comment]
@daira the example you gave requires the same secret key holder to create two mutually-exclusive-but-otherwise-invalid transactions, so at first glance it seems opt-in. However, any dependent transaction has the same risk of becoming invalidated. Furthermore, any private key holder may, at any time, create a double-spending transaction. Therefore I don't see any feasible way for Bitcoin to prevent this in the malicious case.

In the case of Zcash, I advocate adopting a distinction between two kinds of re-orgs: everyday/expected/minor re-orgs versus halt-the-train-and-inspect-the-engine reorgs. A reorg of depth 2 happens somewhat frequently and the software should handle that just fine. A reorg of depth 10,000 is unarguably a cataclysmic event and there's nothing the software can possibly do to protect users *except* say "Uh oh, something cataclysmic has happened, so I'm halting. Please investigate, O human."

With this distinction in place, we could then have sensible UX and policies around txn invalidations via reorg, and then we can rely on re-org sensitive features, such as JS anchors, transaction expiry, and other features. (*Especially* features that improve UX, security, and robustness.)

**Comment by nathan-at-least** [comment]
Removed from 1.0.9. This specification does not affect 1.0.9 release in any way, and we're overcapacity for 1.0.9.

**Comment by daira** [comment]
I believe this fits within the scope of HF0/NU0, and that there's a clear benefit to including it.

**Comment by nathan-at-least** [comment]
Note, we had discussed adding consensus rules to *prevent* transactions being submitted which were only valid far in the future, for example an `nlocktime > 1 year`. We've decided not do any such thing as part of this ticket or Network Upgrade 0.

**Comment by ebfull** [comment]
My understanding is that this feature allows a _transaction_ to specify a maximum block height that it is allowed to appear in. If this feature exists, @arcalinea wonders what the default should be? Should people have to opt out of this feature? What is the exact scenario where it helps and is it necessary for NU0 to be secure?

I'm worried about UX problems from a recipient's perspective that we haven't analyzed yet. This may make 0conf transactions totally unsafe, is that something we're prepared to change right now?

**Comment by arcalinea** [comment]
Yeah, zero confirmation txs will be more unsafe. But as it currently stands, they shouldn't be relied upon anyways, so making them less reliable might end up enforcing better practices. Not sure what the default for expiry blockheight should be, but think there should be one, so that the assumption moving forward is that 0conf txs can never be relied upon. 

This feature would help limit mempool size, as large transactions with insufficient fee to be mined would have to be re-sent after awhile. So you could see this as helping with fee selection for users, removing indeterminacy from 0conf txs, and as @zmanian mentioned, simplify revoking past state for protocols like lightning. 

@ebfull and I talked about doing this by adding a field `blockExpiry` to both shielded and transparent transactions, enforcing it in the consensus rules, and removing txs that have expired from the mempool. Would have to indicate to the wallet that an unmined tx with an expiry is invalid and cannot be spent. The new transaction format would also require changing the version, or how we version txs; right now the standard for nVersion is 1 or 2. @str4d how do you think we should do that, given that we need to change it for Sapling later on as well?

**Comment by arcalinea** [comment]
Another design option is discussed in #2384, `mempoolexpirytime` ejecting txs from mempool by wall clock time.

**Comment by zmanian** [comment]
Transaction expiry and replacement that is enforced by consensus rules is much better than adhoc mempool protocols like replace by fee and wall clock time especially because it can be used in layer 2 protocols.

It also seem like wallet software could use this feature to be much more conservative in the fees they charge.

**Comment by bitcartel** [comment]
`mempoolexpirytime` lets nodes decide how long they will keep tx in mempool for, so it would work against any consensus based expiry height set in a transaction. e.g. wallet creates tx with block expiry set to 576 blocks (~24 hours) but nodes decide to evict after 5 hours.  So any default value for an option like `mempoolexpirytime` could end up being the de facto expiry time.

**Comment by bitcartel** [comment]
The transaction expiry which is a block height must be >= nLockTime (expressed as block height).

It's possible that a transaction expires at a block height before nLockTime (expressed as a timestamp) is reached.

**Comment by bitcartel** [comment]
It might be useful to set nLockTime to block A and transaction expiry to block B, to provide a period between A - B for a block to be mined.  e.g. nLockTime = 200000, transaction expiry is 200576.  Or should transaction expiry be relative to block A and specify the number of blocks the transaction until expiry? e.g. nLockTime = 200000, transaction expiry is 576.

Similarly if nLocktime is a timestamp, should transaction expiry be the relative number of seconds after nLockTime until expiry? e.g. nLockTime is time t, transaction expiry is 3600, so the transaction expires 1 hour after nLockTime.

Who is creating nLockTime transactions?  Maybe a simplistic (crude) approach is to say that if nLockTime is set, transaction expiry cannot be used and is set by default to 0 i.e. no change in behaviour.

**Comment by bitcartel** [comment]
There is a Twitter discussion about transaction expiry here:
https://twitter.com/zooko/status/961975704584933376

Points raised so far in the thread (at the time of writing this comment) are things we have already discussed but not necessarily reached agreement on.

- Default on (agreement this is fine for Overwinter)
- Default value is 1 hr ~ 20 blocks (disagreement, concern over reorgs)
- Add user configuration option to change the default value or disable (disagreement, how empowered are users?)

**Comment by zookozcash** [comment]
> • Default value is 1 hr ~ 20 blocks (concern over reorgs)

The number of blocks for a transaction to be considered as "confirmed" is 10 (per https://github.com/zcash/zcash/issues/952, pending a change to the standard per https://github.com/zcash/zcash/issues/2004). Therefore there is no concern about a 20-block reorg causing an expired transaction to come back to life. (Or, to put it another way, anyone concerned about a 20-block reorg causing a expired transaction to come back to life should be a lot _more_ concerned about a 10-block reorg making a lot of people vulnerable to double-spend attacks.)

**Comment by zookozcash** [comment]
> • Add user configuration option to change the default value (disagreement)

As I've expounded at some length on chat channels, I strongly believe that user-configurable options are terrible for security, engineering, product definition, and user experience, and I strongly think that this option should not be configurable without recompiling the software, unless someone can come up with a very likely and compelling use case of some user that we want to support who can't recompile the software and can't use the default setting.
