### ISSUE TITLE
Block production launch on Bitcoin future block hash

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#758]
This is a technique Ethereum used to coordinate the production network launch in a way that removes any "insider advantage".

**Comment by ebfull** [comment]
http://www.devtome.com/doku.php?id=a_massive_investigation_of_instamines_and_fastmines_for_the_top_alt_coins

We should consider a "time bomb" style approach which avoids complexity and keeps thing deterministic. We want miners to not be caught off guard or require downloading things before mining truly begins. Rewards should not be distributed until everyone is in position.

**Comment by zookoatleastauthoritycom** [comment]
What happened to Litecoin (http://www.devtome.com/doku.php?id=a_massive_investigation_of_instamines_and_fastmines_for_the_top_alt_coins#litecoin) could also happen to us — the mining power in the early days/hours could be much higher than the initial setting of the difficulty factor, thus leading to faster than normal blocks, and making people who missed out on that period suspect that we had deliberately colluded with early miners to give the early miners an unfair advantage. A possible prevention of that would be to have a "slow start", where for the first few blocks there is only a small reward, like on the order of 0.2ⓩ, and then it periodically redoubles until it reaches 50ⓩ. The advantages of a slow start are:

1. We get a real measurement of mining power, which can be used to adjust the difficulty factor, before the more valuable rewards start coming. (In contrast, the earlier proposal to have mining of empty blocks with no reward doesn't have this advantage, because early miners would be incentivized to hide their mining power from the difficulty calculations and then turn on their mining power just in time for the first 50ⓩ reward.)

2. People have less reason to be suspicious that there was some kind of collusion in which we pulled the starting gun trigger right when their competitors had gotten to the starting line but before they had. Since the starting gun just starts doling out rewards of 0.2ⓩ per block, it is fine for late-comers to jump in.

**Comment by nathan-at-least** [comment]
Another tweak might be to adjust difficulty very frequently initially, and then extend that adjustment window as the blockchain grows. So difficulty might be highly erratic initially, but also very adaptive, and as time goes on it becomes "stickier".

**Comment by zookozcash** [comment]
Moved the notion of "slow start" to a separate ticket: https://github.com/zcash/zcash/issues/762

**Comment by zookozcash** [comment]
I'm not as sure that this one is necessary, now that #762 is an option, and it seems to solve a lot of the same problems. Nathan, what do you think?

**Comment by defuse** [comment]
This is not-in-1.0 but by its nature it could only go into 1.0, so can we close this issue?

**Comment by nathan-at-least** [comment]
Yes, this is a launch technique we decided against (in favor of slow-start which is easier for us to coordinate).
