### ISSUE TITLE
Use zkSNARK for PoW

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#760]
If proofs require a large space*time (or ideally large space only?) and verifications are very small space, they provide the kind of asymmetry we desire for a memory oriented proof-of-work.

Difficulty must be implemented over the proof string (proving output), since proofs take constant resources for a given circuit.

The circuit needs to be an appropriately-sized circuit which takes a block header (hash) as a public input.

Fun thought: which secret inputs might this circuit take that could be useful?

**Comment by daira** [comment]
Remember that the size of the proving key is proportional to the circuit size. This means that the cost can't be too much greater than that of the Pour circuit in order to be practical. Also, it might be susceptible to optimisations that reduce the memory usage of the PoW, but not necessarily in a useful way for optimising the Pour proofs.

**Comment by daira** [comment]
As demonstrated by the substantial reduction in memory usage for bellman relative to libsnark, SNARK proving is not meaningfully memory-hard.
