### ISSUE TITLE
can the multiparty setup be proven secure against adaptive corruptions?

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#771]

**Comment by daira** [comment]
As far as I understand, it means that for the protocol to be secure, at least one party must perform the protocol correctly/honestly throughout.

**Comment by amiller** [comment]
Non-adaptive usually means that the choice of which parties to corrupt needs to be made before the protocol starts.

 Suppose the attacker has already owned N-2 of the parties from the outset, and there are two good guys. The attacker waits to observe the first few exchanges of messages, and then decides to go drive over and bludgeon either Good Guy A or Good Guy B (depending on how the protocol plays out) to death and freeze his laptop before the protocol finishes.

 In this scenario, there is still one honest party that wasn't corrupted at all throughout the protocol. However, since the adversary adaptively chose which party to corrupt, and the theorem assumes non-adaptive corruptions, the theorem does not imply security in this case.

Note: this is a contrived story to illistrate the subtle difference of adaptive/non-adaptive security definitions. It doesnt say anything about the actual MPC protocol, there isnt necessarily a feasible attack even in the above case.

**Comment by daira** [comment]
Hmm. Is there some serious obstacle to proving adaptive-corruption security, or is it just the the proof for non-adaptive security was easier?

**Comment by daira** [comment]
The updatable SRS model used in https://eprint.iacr.org/2021/219.pdf ensures security against adaptive corruptions, by virtue of the dataflow involved in the protocol. Any party can come along and update the SRS, and because that party did not have to be involved in the protocol up to that point, there is no distinction between adaptive and non-adaptive corruptions. The adversary can independently decide to corrupt or not corrupt each party before its turn, but the security model takes that into account.
