### ISSUE TITLE
commit to *not* implementing Replace By Fee

### ISSUE THREAD

**Issue by daira** [zcash/zcash#774]
See https://medium.com/@octskyward/replace-by-fee-43edd9a1dd6d#.jnihofcpc for why not.

**Comment by taoeffect** [comment]
Um, unless you plan on doing something like Bitcoin NG [you will have to implement RBF](https://fixingtao.com/2016/03/bitcoin-keep-calm-and-rbfcpfp-on/).

Mike [isn't the most honest person](https://fixingtao.com/2016/01/point-by-point-response-to-mike-hearns-final-bitcoin-post/).

**Comment by ebfull** [comment]
Nothing stops miners from implementing this themselves, so this commitment isn't very valuable to the ecosystem. RBF is actually very useful. Further, we appear to be making commitments of the *opposite* form: we are urging users to consider our system as not providing "finality" for transactions within some very conservative measure of consensus.

**Comment by zookozcash** [comment]
We don't need to commit to this at this time. (Also yeah, I don't currently *want* to commit to it. But, in any case we don't need to make any decision or any public commitment at this time.)

**Comment by daira** [comment]
By the way, the *right* way to fix the 'transactions can get "stuck"' problem is transaction expiry (#754), not RBF. Transaction expiry doesn't have the same problems as RBF because it is always clear to the payee precisely what risk they are taking with respect to losing transactions due to a reorg.

**Comment by nathan-at-least** [comment]
Isn't replace-by-fee a completely local miner decision? If so, then the question becomes what kind of "standard policy" should we promote with respect to the relationship between transaction creators and miners.

IMO, any policy based on restrictions to how the mempool is managed are ill-advised and should be avoided. As a transaction creator, the only guarantees I should rely on are:

* If my transaction appears in a block sufficiently deep, it won't be voided or reversed.
* miners can (and will) do anything they please to any transaction prior to that case.

Following that logic, I'm very much for replace-by-fee. If miners didn't do replace-by-fee, they are foregoing higher transaction fees. Why? If transaction creators depend on them foregoing higher transaction fees this seems like a shaky foundation for anything, since it's conventional.

This is a special case of the "durable queue" fantasy some Bitcoin people seem to have. Transaction senders or recipients *must always* verify end-to-end, so relying on any particular behavior of the mempool is folly in one extreme, for security. Any reliance might be a seductive shortcut, but it will bite you in the ass eventually, and I don't confuse anyone into not protecting themselves.

**Comment by nathan-at-least** [comment]
From @taoeffect 's [comment](https://github.com/zcash/zcash/issues/774#issuecomment-195856678)'s comment:

Your post about RBF/CPFP is more in line with my personal inclinations (though other Zcash devs or scientists may disagree), and it is in keeping with my previous comment where I advocate "not pretending there's a durable queue based on convention rather than incentives".

I want to counter your next part, though:

> I would take everything Mike says with a canister of salt.

We strive to interpret everyone's reasoning with a [principle of charity](https://en.wikipedia.org/wiki/Principle_of_charity), and specific to their words. Mike Hearn's other posts, personality, agenda, etc… don't seem directly relevant to the blog post in question, and the blog post (which @daira [links to in her comment](https://medium.com/@octskyward/replace-by-fee-43edd9a1dd6d#.jnihofcpc)) makes some great points, such as how relying on game theory or cleverness can lead to inaccurate predictions.

I want to respond specifically to that post since it was persuasive to @daira (and to me when I first read it):

It assumes a pre-existing ecosystem of 0-conf PoS payments that's entrenched. However, *even in that ecosystem* nothing prevents individual miners from implementing RBF (also note that @taoeffect's article points out you can achieve similar behavior as a PoS purchaser with CPFP on change addresses), then those 0-conf PoS products need to adapt, because they are already vulnerable to fraud if they assume RBF doesn't happen.

I don't want to give those use case developers a false expectation that they can rely on something which I believe the protocol cannot safely guarantee. Also, if any of them engage with us, I'd love to get their feedback on how we can improve that use case in secure/safe ways.

**Comment by ebfull** [comment]
Since there is disagreement over making such a commitment, I nominate for closure.

**Comment by taoeffect** [comment]
> Mike Hearn's other posts, personality, agenda, etc… don't seem directly relevant to the blog post in question

That's the thing that a lot of people miss: they are directly relevant.

The post @daira linked to makes no mention of the words "block size", and yet Mike's entire post on RBF is about block size. It's a very clever thing, and lots of people miss it. I do not see how the principle of charity applies here, it seems to me more like you're advocating the notion of "presume good faith", which is a dangerous fallacy itself, especially in the world of cryptocurrencies in which you have to do the opposite (assume bad faith: that someone is deliberately trying to deceive you).

**Comment by ebfull** [comment]
If you assume good faith of others, it doesn't mean you have to agree or even that you must entertain their arguments. It's a good exercise of your own convictions and opinions to have them stressed even by what you perceive to be poor reasoning. This is a cultural attitude which we're striving for. I personally believe that the hostile and distrustful attitudes prevailing in the cryptocurrency community are what prevent arguments from winning on merit.

**Comment by taoeffect** [comment]
If you assume good faith of everyone by default, you will not notice sabotage, which can happen only because people assume good faith by default.

If you don't like the sound of "assume bad faith", at the very least try to be neutral and remember that *it is a fact* that governments spend millions (if not billions) of dollars to sabotage projects like this.

**Comment by taoeffect** [comment]
> *it is a fact*

Relevant link with citations: https://blog.okturtles.com/2015/11/dells-tumble-googles-fumble-and-how-government-sabotage-of-internet-security-works/

**Comment by ebfull** [comment]
@taoeffect I think this discussion is better suited for our forum.

**Comment by taoeffect** [comment]
@ebfull,

> @taoeffect I think this discussion is better suited for our forum.

The discussion is about the author of the post that was linked to in the OP and what's implied by its mere consideration.

The approach Zcash has chosen requires trust, does it not? It destroys that trust when I see decisions even being considered based on the fallacious arguments of a man [who spent his entire career in Bitcoin trying to sabotage it.](https://www.reddit.com/r/Bitcoin/comments/41a2cy/bitcoin_didnt_fail_mike_hearns_plan_did/cz0ua95)

Telling me such things aren't "relevant" or should be discussed in a place where fewer people will see it is a major red flag.

Any attempts to sweep a line of trust-based questioning, especially when it's technically relevant and on topic to the issue, is a major red flag.

You want to ask the entire world to trust you and your trusted setup? Fine, but then deal maturely with trust-based questions and don't try to sweep them under the rug.

**Comment by taoeffect** [comment]
Wow. And stealth-editing your comment to make it seem like I had ignored your request for forum discussion certainly doesn't build confidence.

![screen shot 2016-03-15 at 3 20 07 pm-zcash-stealth-edit](https://cloud.githubusercontent.com/assets/138706/13798811/ff58523e-ead6-11e5-997f-e51f3d2576d9.jpg)

**Comment by zookozcash** [comment]
Closing this ticket, as we are not going to commit to this at this time. I recommend Nathan's comment: https://github.com/zcash/zcash/issues/774#issuecomment-196950666

**Comment by daira** [comment]
I am strongly tempted to delete all of the off-topic derailing on this ticket in order to get back to discussing its actual subject, RBF (which deserves further technical consideration of its merits and demerits, without irrelevant distractions). But if I did that, it would no doubt give @taoeffect fuel to accuse me of "censorship". Nevertheless, I will not hesitate to delete off-topic comments in future if I believe they are damaging our ability to conduct technical discussions.

**Comment by daira** [comment]
I view the argument that RBF is purely a "local miner decision" with great skepticism. This isn't a case of [Don't Prohibit What You Can't Prevent](http://www.cap-lore.com/CapTheory/Prevent.html). The whole premise of PoW-based distributed consensus is to assume that more than half of the mining power is held by miners that *follow the protocol*. Thus what the protocol says miners should do to follow it is of critical importance.

I grant that miners may have misaligned incentives. To the extent that is so, let's try to fix it. RBF is not fixing it; it's entrenching behaviour that causes unnecessary problems for users.

**Comment by taoeffect** [comment]
> RBF is not fixing it; it's entrenching behaviour that causes unnecessary problems for users.

What is RBF not fixing? What "unnecessary problems" are you referring to? And what is your alternative suggestion?

**Comment by JohnHanks** [comment]
RBF is awesome.  If people don't want to use it don't use it.  Expiry is no good.  If you want to resend outputs to another input with a greater than, equal to, or less than the fee you sent before you have a single conf on your tx then I think you should be able to.  However, which tx is the one that goes and gets confirmed is up to the mining community.  I foresee someone trying to resend coin only to find their first tx went through incorrectly.  How the mempool will be managed is critical.  this is a doozy guise

**Comment by taoeffect** [comment]
> And what is your alternative suggestion?

My apologies @daira, somehow I did not see your [earlier comment regarding transaction expiry based on blockchain height](https://github.com/zcash/zcash/issues/774#issuecomment-196841172). I assume this is the alternative you're suggesting:

> By the way, the right way to fix the "transactions can get stuck" problem is transaction expiry (#754), not RBF. Transaction expiry doesn't have the same problems as RBF because it is always clear to the payee precisely what risk they are taking with respect to losing transactions due to a reorg (basically it is very unlikely to happen unless the transaction is in a block near to its expiry height).

That is certainly better than doing nothing (which is what I thought you were proposing). At least with an expiry users would have some concrete idea as far as how long their transaction would be stuck for.

Still, without RBF I think that would place many of your users in a compromised position. You have no idea what sorts of emergencies might befall them if their payment gets unexpectedly delayed. You could try to address this by making the expiry time very low (like say 30 minutes), and that would be a big improvement over the status quo in Bitcoin. Still, the ability to cancel an email within a few seconds of sending is a feature many people love. If they find that valuable, I'm certain they would find it even more valuable to do so with mistaken transactions. I've accidentally sent 10x the amount of Bitcoin than I intended to because of a silly math error when doing the exchange conversion (thankfully it wasn't an issue), but I can imagine such mistakes being frequent enough to harm the user experience. RBF would address such issues.

The desire for instant transactions is the only real argument against RBF, however it is countered like so:

- Unless you do Bitcoin-NG, your instant, 0-conf transactions are still very vulnerable to being double-spent (as mentioned in the post I linked to in my first reply).
- The people who want instant transactions are retailers (lattés at Starbucks). However, if you envision Zcash being used by at least as many users as Bitcoin, you will not be able to do instant transactions like this *anyway*, even if you were "committed against RBF", because to do so would be to completely centralize Zcash (all blockchains have an upper limit of users they can support without centralizing unless they use sharding, and I don't think you have any plans to do sharding).
- RBF can be implemented on an opt-in basis as done in Bitcoin (though it should be opt-out by default)

**Comment by daira** [comment]
@taoeffect wrote:
> Still, the ability to cancel an email within a few seconds of sending is a feature many people love.

Clients that support that do it by *not sending the email* until after a delay, and then not sending it at all if cancelled within that time. A Zcash wallet can do exactly the same thing if its users find that a valuable feature.

In general I think you're valuing the payer's convenience over the ability of the payee to rely on the transaction (which will affect their willingness to accept Zcash in the first place). While merchants can refuse transactions that enable RBF, that would also result in an inconsistent experience for users.

**Comment by taoeffect** [comment]
> Clients or web-based email services that support that do it by not sending the email until after a delay, and then not sending it at all if cancelled within that time. A Zcash wallet can do exactly the same thing if its users find that a valuable feature.

That's a fair point.

I'd like to apologize again for the tone in some of my previous comments and try to explain what happened.

I was, and am still, very much upset with Mike for what he did to the Bitcoin community. So seeing a post of his get linked to without further explanation made me think, "Oh no, not this again," and in the context of Zcash (where trust is so important) I may have overreacted a bit and misdirected some of my anger at Mike at you, @daira, and @ebfull. I still feel bad about that and I'm very sorry about it.

Returning to the discussion of the relationship between RBF, blocksize, and transaction expiry:

> In general I think you're valuing the payer's convenience over the ability of the payee to rely on the transaction (which will affect their willingness to accept Zcash in the first place). While merchants can refuse transactions that enable RBF, that would also result in an inconsistent experience for users.

So let's sketch out the specific situation that's being affected here:

- This discussion does not apply to most online transactions, where wait time for product delivery is frequently far more than the ~2 minute (?) blocktime that Zcash has.
- This discussion mostly (exclusively?) applies to situations where cash registers are used in person.

So let's imagine Zcash refused to support even opt-in RBF (which it needn't, since, as you point out yourself, that merchants could refuse to accept such transactions). The only thing we have now to protect customers is the transaction expiry, which I'm not sure what exactly that would be (this is something I'd like to see cleared up). Let's assume it's the block time equivalent of 30 minutes (~15 blocks).

So we go to Publix to buy $200 worth of groceries using Zcash. The payment interval there is about 10-30 seconds from phone-swipe to leaving the register with receipt (less than a block time).

Ignoring, for the moment, that this whole scenario is very unlikely in the first place if Zcash doesn't implement Bitcoin-NG or sharding, what happens if we decided to purchase during peek time or while a spam attack was going on? Our transaction could be automatically returned to us by the system in 30 minutes and we wouldn't even have to actively double-spend it ourselves.

So, my point is that when talking about RBF you always have to remember that it's intimately linked with these properties:

- The decentralization level of the blockchain
- The blocksize and blocktime of the blockchain (which is directly related to its decentralization)
- The design of the blockchain

Instant transactions of the Publix-variety *require* additional infrastructure support to work. If you want to get rid of RBF, you have to implement things Bitcoin hasn't implemented. Other blockchains, like Ethereum, understand this, and that's why they are implementing sharding. Emin Gun Sirer also understands this and that's why he sometimes rants on twitter about how "this wouldn't happen if Bitcoin-NG were implemented" (referring to stuck transactions), and he's right (although I'm not certain it's safe to do NG-style leader selection without also implementing sharding).

Thanks for reading and considering, sorry again for my tone in some previous comments, and keep doing that great work on Zcash!

**Comment by daira** [comment]
I appreciate the apology.

If #754 were implemented, transaction expiry height would be chosen by the transaction creator.

The premiss that this issue only affects in-person or zero-confirmation transactions is highly questionable. As far as I can see it increases the risk incurred by a payee in relying on a payment after *any given* number of confirmations.

Suppose, for example, that Bob answers questions online for a fee, and gives his answers immediately after waiting for the first confirmation. Let's say that Alice pays her ZEC for the answer to her question, and Bob answers it. Meanwhile, Alice has submitted an RBF transaction that replaces the original one and pays to herself instead of Bob. Alice is betting on the original block relied on by Bob being orphaned, so that she gets the answer without having to pay. This cannot be considered unlikely; orphans happen [relatively frequently in Bitcoin](https://blockchain.info/charts/n-orphaned-blocks?timespan=60days&showDataPoints=false&daysAverageString=1&show_header=true&scale=0&address=), and might (we don't know yet) happen more frequently in Zcash due to the higher proof verification time and possibly a shorter target block time.

Without RBF, Alice's original transaction is very likely to also be in the new chain, because it will already be in the mempools of most nodes.

Whether this is a useful attack for Alice or an acceptable risk for Bob obviously depends on the value of Bob's answer and the fee. However, *all else being equal*, Bob is taking a greater risk because of RBF, which must be compensated somehow (perhaps by charging more or requiring one extra block confirmation, which increases the latency of his service to honest users).

**Comment by taoeffect** [comment]
> As far as I can see it increases the risk incurred by a payee in relying on a payment after any given number of confirmations.

To the best of my understanding, this is simply not true.

Once a transaction makes it into a block and is relayed throughout the network it is no longer in the mempool, and the more confs it gets the less likely it is to be orphaned, so your example doesn't hold water.

**Comment by taoeffect** [comment]
Added an edit to my previous comment, but just thought of some additional reasons why this is not an issue:

- Bob is free to reject RBF transactions.
- If Bob chooses to accept RBF transactions, he can be made aware by the software anytime an RBF transaction is sent out to the network, so he will know there's another txn out there.

If this becomes a real issue, Bob would never give out answers immediately but would wait for 1-conf, or refuse RBF-txns. So this isn't a problem for Bob. Lack of RBF, however, is a real problem to Bob and everyone else.

**Comment by taoeffect** [comment]
Sorry, last thought: if Bob is relying on 0-conf, then he is about as vulnerable to double spending from RBF as he would be from a user-specified txn expiry of 1 block.

If you say, "OK, we'll make it a minimum of 2", well then seems to me Bob isn't really relying on 0-conf anymore, he's relying on 2-conf.

**Comment by daira** [comment]
Here's another well-argued post opposing RBF: https://chrispacia.wordpress.com/2015/11/29/on-zero-confirmation-transactions/

Please note: I WILL delete any comments that make ad-hominem arguments relating to Chris Pacia's other opinions regarding controversial Bitcoin issues. (Frankly I should also have done so regarding Mike Hearn, since this ticket is a mess as a result of not doing that.)

**Comment by daira** [comment]
Incidentally, taking advantage of orphans in an attack absolutely does not require 51% of mining power. Look at the rate of orphans that  naturally occur due to block propagation delay.

**Comment by daira** [comment]
As for merchants rejecting RBF transactions, that significantly impairs usability. It is not reasonable to assume that end-users will understand the detailed trade-offs of RBF: the decision of whether to opt in or out will typically be made by wallet programmers, not users. If the wallet programmer decides to opt in, then users will have their transactions rejected by RBF-rejecting merchants, for no understandable reason. If the wallet programmer decides to opt out, then users will obtain none of the benefits claimed by RBF proponents.

**Comment by zookozcash** [comment]
We're not going to commit to _not_ implementing Replace-by-Fee. :-)

But, this was a really good discussion in this ticket, for future reference.

**Comment by skyl** [comment]
I'm mulling over the merchant POS use case, pardon my relative ignorance. 

I don't want my payees to have to think about replaceable transactions. For reasonably small amounts, I want them to be able to accept 0-conf without worrying about double spend fraud. One problem with using an opt-in flag so that the merchant can reject replaceable TXs:

Alice sends payment to Bob's POS with replaceable flag. Bob's POS rejects the TX. Alice really did send the payment and didn't even know about RBF option set in her wallet. Both Alice and Bob have no idea what's going on and stand around scratching their heads and looking at a block explorer for a few minutes ...

So, maybe Bob's POS wallet can instantly accept small transactions that are not flagged as replaceable but will wait for a few minutes to confirm transactions that are marked replaceable. But, this forces Alice and Bob to know a lot more about the mempool and arcane internals than I want them to have to know.  The Zcash experience is not as good as the paper cash experience in this configuration.

I'm certainly not the person who has a great answer right now. But, I wanted to interject that I think this is an important topic. I'm hoping that Zcash's strangers-face-to-face-in-hurry story can be refined so that Zcash can be (nearly) as convenient as regular cash.

**Comment by abrkn** [comment]
Has RBF been added yet? (Would prefer if it was not)

**Comment by daira** [comment]
@abrkn It has not.
