### ISSUE TITLE
Remove SHA-256 zero fixpoint in the commitment Merkle tree

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#779]
The incremental merkle tree construction as implemented in the circuit and our consensus code has a special case: combining two empty digests also results in an empty digest. (That is, H(0 || 0) = 0.) This happens at every depth (I think?), including for leaves.

This doesn't really result in a huge performance gain and appears to be done for completeness. Can we double-check this is not a threat?

**Comment by daira** [comment]
It concerns me that this was an undocumented divergence from the Zerocash paper that was not covered by the security proof (and it seems as though you'd have to make a somewhat nonstandard assumption about the hash in order to fix the proof).

**Comment by matthewdgreen** [comment]
There've been a couple of references to the security proof, so I should probably clarify a few things about it. Most importantly, it's worth pointing out that the proofs in the Appendix of the Zerocash paper do not apply directly to the Zerocash construction, they apply to the DAP scheme construction. 

The difference is that the DAP scheme is the abstract system that's defined in Section 4 -- based on a bunch of abstract algorithms like "some commitment scheme", "some collision resistant function", "some PRF". Zerocash is a concrete instantiation of a DAP scheme that we arrived at by filling in the building blocks (PRFs, commitments, etc.) with specific concrete algorithm instantiations based on SHA256 and so on.  

So if you see an assumption in the proof of the form "we assume F is a collision resistant function" and then in Zerocash it turns out that F is implemented using, say, CRC32, then that's a bug. But the bug is not in the DAP scheme or the DAP scheme's proof -- it's in the Zerocash instantiation. We didn't do the thing the DAP scheme required, so the proof no longer applies to that instantiation. Similarly if next month Marc Stevens breaks SHA256, then the proof will also cease to apply to Zerocash -- but it won't be wrong. (Or at least it won't be wrong for _that_ reason -- I expect it does have real bugs that haven't yet been found, and I hope you find them.)

In the case of the 64-bit hash collision bug, that was a real mess. In the case of the H(0||0) = 0 special casing issue, the bug is more subtle -- since in theory if H is collision resistant, the special-cased version of H probably is too -- HOWEVER that is is just a dumb theoretical view, and adding fixed points probably _does_ have a significant impact on the concrete security of the hash function so we should absolutely fix it.

I have to be honest that I learned about the special casing after we shipped the paper, so I'm not endorsing it. It should all be cleaned up. Fortunately that's what this project is all about. :)

**Comment by daira** [comment]
(Transcript of something I said to @ebfull)

----
if we assume that SHA-256 is preimage-resistant, it isn't possible to find the coin (a_pk, v, ρ and r) corresponding to a coin commitment of 0

let's see, how else could we exploit this?

it's not an exploit, but there's a problem with the security proof

let's say that instead of H(0) = 0, it was H(x) = x for some x such that H(a) = x

then we would have a collision: H(a) = H(x)

so what is special about 0 that [possibly] makes this secure? it must be that 0 is chosen independently of the design of H

----
It would be hard to argue that zero is randomly chosen or independent of the design of SHA-256!

**Comment by daira** [comment]
We should remove this special case.

**Comment by ebfull** [comment]
I'm okay with removing the special case, but what about the tree root being zero with no elements in it? I'm a *little* concerned about changing that since so much code relies on it, but it can be done.

**Comment by daira** [comment]
We decided in the engineering meeting to remove the fixpoint. Empty leaves will still be represented as a zero hash (so we are assuming that an adversary does not know any preimage of 0).

**Comment by ebfull** [comment]
Here's a list of hints for removing this fixpoint:

* In the tree code, there should only be a couple places to change: the root calculation uses `PathFiller` to return empty tree roots. Instead, you will need to have a parallel computation of empty subtrees as you ascend the authentication path, so this requires changing PathFiller, which is nice since it's so isolated.
* In `SHA256Compress`, a line exists which checks if both inputs are null and returns null, remove that.
* Now, the root of the tree will be different when it's empty, and really, all the test vectors will break. Go ahead and fix those and remove the tests that ensure the fixpoint exists.
* Tricky part: the old tree will now diverge from the new tree. So, remove all the tests that they are equivalent. (I'm doing this anyway as part of the libzcash PR.)
* In the consensus code when we get the "best anchor" and one doesn't exist, we [return null](https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/txdb.cpp#L110), and special case that [elsewhere](https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/txdb.cpp#L73) as a blank tree.
    - In `GetAnchorAt`, use `uint256S()` to return the hash of a blank `ZCIncrementalMerkleTree`, and write a test to ensure that it's correct in case we change the depth later. (Making a tree and getting its root in code like `GetAnchorAt` would be too expensive, and initialization/atomics are overkill.) Alternatively, come up with a cool way to statically evaluate this root instead.
    - In `GetBestAnchor`, making a tree and returning its root like `ZCIncrementalMerkleTree().root()` is fine since that code will not be exercised often.

Hopefully this is all you need to change, but there isn't much consensus code using the trees or anchors, so you can probably find anything I'm missing rather easily.

**Comment by ebfull** [comment]
(One really nice way to change the tree is to centralize the fixpoint behavior to `SHA256Compress` first, and then make a replacement class for it. That way you can keep the tests against the old tree, even if we're removing it eventually anyway.)

**Comment by ebfull** [comment]
This is done!
