### ISSUE TITLE
RPC call for loading/unloading proving

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#789]
The RPC should provide a call for loading and unloading the proving key from memory, and `zcrawpour` should error if it is not loaded.

**Comment by daira** [comment]
What's the motivation for making ``zcrawpour`` error rather than implicitly loading the key? (I suspect that @zookozcash may have different tastes on this issue, but it seems to me that this choice impairs usability of the interface, since a client just ends up having to do a load before a ``zcrawpour`` in order for the client not to make assumptions about state.)

**Comment by daira** [comment]
I don't object to this call as a memory (for unloading) and latency (for pre-loading) optimisation if ``zcrawpour`` still loads the key implicitly, but I don't think it should be in 1.0.

**Comment by str4d** [comment]
The engineering meeting discussion touched on how this would tie in with memory usage on phones. Here's some docs on how Android manages memory:

http://developer.android.com/training/articles/memory.html

**Comment by daira** [comment]
That's well worth reading; in particular, note that if we don't trim memory on request but are registered as a service, then *other* apps will be killed. This is bad because it means we're being antisocial to other apps and making the phone less usable.

**Comment by daira** [comment]
#2243 will make this unnecessary.

**Comment by str4d** [comment]
Made redundant by #2670.
