### ISSUE TITLE
stub out prover for tests of other (non-prover) code

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#803]
The test suite currently takes too long to run locally; I have to comment out all the pour-related stuff (to test non-pour-related stuff). We could use a reduced-round SHA256 invocation or something in the circuit with a compilation flag like `-DTESTING_INSECURE_SHA256`.

Or perhaps we can substitute SHA256 for some other efficient hash function which would be easy to implement in libsnark hopefully. (And retain our need for 512-bit blocks, 256-bit digests.)

I don't think we _need_ to adopt this policy for buildbot (perhaps we could for `try` but not `auto`) but it should be an option for developers at least.

---

The requirements of such a hash function:
- should make heavy/exclusive use of modular addition in G(2^32) and bitshifts
- very low security collision/preimage resistance is fine
- no security from length extension attacks needed; not being used on variable-length data
- take 512-bit blocks
- produce 256-bit digests

**Comment by ebfull** [comment]
Actually, here's a much better alternative: disable the SHA256 constraints with a compiler flag. It should still end up being witnessed and we won't have to change any code external to the circuit.

**Comment by ebfull** [comment]
The downside to just disabling the constraints is that (I think) it will break tests where the evaluation of the hash function is overwritten by another input, and the constraints will be satisfied. The constraints keep us from screwing that up and testing to ensure the circuit works properly.

**Comment by ebfull** [comment]
An alternative is just stubbing out the verificiation and proving routines, but this will require a bit more surgery or throwing away test coverage. The latter might be a good thing, but the tests I discovered I felt uneasy about removing, which is why I went with the "fake sha256 constraints" approach.

**Comment by zookozcash** [comment]
I talked to Sean about this in person, and recommended that instead of stubbing-out the hash function within the circuit, we should instead stub-out the entire proving mechanism from tests. This would be even faster for tests (which do not need to test the proving code) and would avoid having "conditioned-on-whether-we're-testing" inside the circuit).

Changing the title of this ticket, and closing https://github.com/zcash/zcash/pull/828.

**Comment by zookozcash** [comment]
Oops, accidentally closed this ticket. Re-opening.

**Comment by nathan-at-least** [comment]
I'd like to get a list of tests which take a long time and which run faster when stubbing out the prover. Then I'd like to write mock tests that cover the same target code paths if possible.

I'm about to do exactly this for #862, which will mock out the verifier so that it can test the ``CheckTransaction`` cases where JoinSplit verification either passes or does not pass, all without invoking any of libsnark.

I suspect a lot of our long tests are system or large-scale integration tests, in which case replacing them with "equivalent coverage mock tests" might be a lot of mock tests, so we may still want to have another stubbing-out mechanism (aside from a mock framework) for those tests as a medium term hybrid approach.

Another option is to just get mock coverage on key points of code that we're touching, and leave all system/integration/rpc-tests unchanged with no stubbing complexity, and then only run the latter for PR merges.

**Comment by daira** [comment]
This has been done.
