### ISSUE TITLE
Move libsnark in tree

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#820]
Should we move libsnark out of the depends system and into the project, like upstream does with libsecp256k1 and other code?
- We need c++11 support for libsnark, but we shouldn't need to enable it for the entire build system like we are now.
- The depends system is primarily intended for packages that are typically available as system packages. As of now, the only package that doesn't fit in this category is libsnark. (This issue will hold back the use of Zcash on other platforms like Windows.)
- We need to isolate the compilation artifacts of libsnark to a single process; right now it is mixed between the depends system and the bitcoin build system. In addition, libsnark symbols have leaked all over the project, when we should only need them within one contained compilation unit.
- libsnark, as we currently use it, only needs us to compile [a few files](https://github.com/ebfull/bellman/blob/master/tinysnark/build.rs#L23). We're currently compiling a ton of stuff that we don't need to.

**Comment by defuse** [comment]
Moving libsnark in tree adds a lot of friction every time we try to update it and raises the possibility of us not copying upstream's code correctly (another thing security auditors need to verify). Maybe after 1.0.

**Comment by ebfull** [comment]
I don't know about the friction argument but I agree this isn't essential for 1.0.

**Comment by daira** [comment]
-1 on doing this for 1.0.

The fact that we only use a small portion of libsnark would be a good argument for moving it in tree, but might that not change if we start using BN128? I don't think we can predict whether we will use BN128 yet.

**Comment by daira** [comment]
But +1 for documenting which parts of libsnark we use, to allow auditors to concentrate their attention on those parts.

**Comment by nathan-at-least** [comment]
There are several competing goals:

a. auditability - how can an auditor easily determine what changes we've made from upstream, how easy is it to understand build flags
b. maintenance - how can we review changes to libsnark (especially when they go hand-in-hand with zcash changes)
c. build/packaging complexity - how painful is it for users to build the system, how easy is it to configure build flags (and how easy is it to accidentally have build-system bugs)
d. upstream exposure - can we get our changes reviewed or discussed by the larger upstream userbase (other users of libsnark)
e. agility / alacrity - being able to modify libsnark features quickly to meet Zcash needs.

To me, it seems like the magical ideal would be that we use upstream directly with no patches, and upstream accepts all of our changes quickly. That seems impractical for two reasons: upstream maintainer alacrity, and also cases where Zcash needs different design choices than make sense for general upstream users/design.

Another option is to bring in libsnark as a git submodule. This helps us simplify the build system c. and quickly make changes, e. Auditability is ok, except we might need to point auditors to the right git diff command to see our changes against upstream.

A third option is to leave libsnark as an external dependency and to continue to maintain patches. This has good auditability at least for the simple case of reviewing the patches against upstream, but is less agile.

If we knew whether or not there are important libsnark changes in the upstream roadmap, or if changes will be required for parameter setup, that would also impact this decision. Let's ask @madars and Alessandro Chiesa about the libsnark roadmap, and then decided next week how to proceed.

**Comment by tromer** [comment]
Upstream libsnark is receptive to pull requests (and is pingable).

What design choices do you think are different for Zcash vs. upstream libsnark, except for deleting unneeded files?

**Comment by ebfull** [comment]
We will absolutely be submitting our changes upstream! :+1: 

Here are some ongoing issues:

1. We want to use libsodium's PRNG instead of libsnark's `fread /dev/urandom` thing. libsnark could provide a hook to us, but it seems weird to me.
2. We *may* want to use components of our code, like Bitcoin's serialization, instead of libsnark's.
3. We want to remove parts of libsnark that we aren't using, and avoid building anything we don't use.
4. We want to work on MPC stuff, which requires a lot of changes to libsnark.
5. We're passing build flags to libsnark that we're not passing to our concrete instantiations of libsnark templates in our library, but I haven't been able to diagnose which ones.

The question in this ticket is whether we should use the depends system to build libsnark, or build it ourselves by bringing libsnark in as a git submodule, and bypassing the upstream `Makefile`. I've implemented this in #1021.

Is it harder to maintain our changes using patch files? Is it harder to develop upstream packages using the depends system? Is it harder for auditors to understand what flags libsnark is compiling with using the depends system?

Upstream Bitcoin seem to have made similar tradeoffs bringing in forks of leveldb and other libraries and not using the depends system and patches for a similar purpose. The depends system is basically just used for packages available as system libraries.

At the very least, #1021 is a useful developer tool when changing libsnark and testing those changes against our code.

**Comment by tromer** [comment]
1. A random-generation hook sounds very reasonable to me.
2. Can alternative serialization be provided by overloading, i.e., writing to something other than ostream? BTW, libsnark already has two serialization formats (binary and ASCII), so it would be nice to come up with elegant system for switching formats, making Zcash's format just the 3rd one.
3. For removing unneeded parts, #1020 may be the best option.
4. What changes does the MPC require?
5. Would this help? https://github.com/scipr-lab/libsnark/issues/21

On related note, libsnark's 'cmake' branch contains a fully CMake-ified build system.How do you feel about it?

**Comment by ebfull** [comment]
https://github.com/scipr-lab/libsnark/issues/21 would be fantastic!

I have not tried the cmake branch.

As for the MPC, it involves adding some things to libsnark and tweaking the code, and for development purposes it was much easier for me to do that and bring it into Zcash's code (mostly to play with the circuit reductions) when libsnark was part of our build system.

**Comment by ebfull** [comment]
At the engineering meeting today, we decided on two points:

* We will continue to contribute patches to upstream libsnark and adopt their changes, and will only maintain a fork of libsnark *temporarily* for features that haven't been adopted upstream yet. It is our goal to land everything we change into upstream libsnark and cooperate fully with upstream for technical changes.
* We will move libsnark out of the `depends` system and bring it into Zcash as a git submodule. This means we will not be using libsnark's `Makefile`, but that may change in the future as issues like https://github.com/scipr-lab/libsnark/issues/21 are resolved.

**Comment by daira** [comment]
We [decided to go with this strategy](https://github.com/zcash/zcash/issues/1020#issuecomment-228887470), as opposed to using  a submodule or an external fork via the depends system.

**Comment by ebfull** [comment]
I'm walking back on the submodule thing after I experienced some difficulty getting it to behave right with the build system -- basically, `git clean` does not act recursively, and I suspect the build system wasn't catching changes to libsnark for some reason.

The option of bringing it straight in tree is tantalizing but I think we need more evidence that it's a good approach. I implemented it and almost submitted a PR but had cold feet. Instead we're forking libsnark and using the depends system still. We can bring libsnark in tree later if we feel it's a good idea. (I do, but it's something that needs more thought and discussion.)

**Comment by tromer** [comment]
Upstream libsnark is moving to a refactored structure, with some code moved into the new `libff` libraries and `libfqfft` libraries, which are submodules of `libsnark`.

So moving libsnark in-tree forces choosing between 3 options:
* Breaking away from upstream, in a way that will make porting changing very difficult
* Porting upstream's refactoring to the zcash in-tree copy, but keeping `libff` and `libfqfft` as submodules (so what's the point?)
* Moving `libff` and `libfqfft` into the zcash tree, too

**Comment by nathan-at-least** [comment]
Good catch @tromer. I defer to @ebfull, @daira, and @str4d who are all more familiar with libsnark as well as git subtrees. However, I agree with @tromer from `#zcash-dev` that we should test a bunch of revision control operations:

- pull changes from upstream.
- cherry pick changes from upstream.
- submit changes to upstream.

Do all of that in a way that works well with their sub-library modularization.

This seems like it should be a prerequisite for merging the PR.

**Comment by nathan-at-least** [comment]
@ebfull do you want to abandon this proposal?

If not, then I propose a next step, which is just a more specific instance of my [last comment](https://github.com/zcash/zcash/issues/820#issuecomment-306622087):

- We will not merge #2252 yet, until this experiment is complete.
- Instead, create a new branch atop #2252 specifically for the purpose of pulling in a new upstream libsnark change. It doesn't even need to be a stable/complete change upstream, so we could try the multi-exponentiation changes, perhaps.
- Figure out how painful that process is and report on it. Show other engineers the process. If it's feasible enough, we might then move forward with #2252.
- Bonus: Figure out a change we want to port to upstream, and do so _starting from_ the #2252 state. See how painful that is. If it's not too painful, we could move forward with #2252.

Document the results here. If the verdict is "too painful", we can close this. Otherwise we can merge #2252.

**Comment by str4d** [comment]
After spending a few hours today looking over libsnark, here is a structure that I can imagine being feasible:

- `libsnark` in `src/snark` (following existing naming conventions for included lib subtrees)
- `libff` in `src/ff`
- Forks of the upstream repositories that each have a tracking branch containing our patches (including ones we will never upstream, like e.g. removal of unused code)

And the corresponding workflow:

- To make changes:
  - Make changes to libsnark code in the zcash repo via our standard PR process
  - Ignore the tracking branches in the forks.
- To pull in upstream changes:
  - Cherry-pick the upstream commits onto the tracking branch of our fork
    - While doing so, drop any parts of those commits that were to code we removed
  - Merge the tracking branch into a new zcash branch using `git subtree`
  - Open a PR with the new zcash branch via our standard process
- To send changes upstream:
  - Merge the in-repo changes back to the tracking branch in our fork via `git subtree`
  - Cherry-pick the patches we want to upstream from our tracking branch into feature branches.
  - Open PRs upstream with these feature branches

Notes:

- This workflow results from my attempting to satisfy the following requirements:
  - Enable our patches to libsnark to be handled via PRs on Zcash itself, instead of relying on synchronous development in a separate repository
    - This part is what `git subtree` handles
  - Only include code in the Zcash codebase that we actually use
    - This requires a tracking branch so we can keep track outside of the Zcash codebase of what code we removed
  - Enable arbitrary Zcash changes to be sent upstream
    - In combination with the presence of a tracking branch, this means manual cherry-picking is required to shuttle commits between tracking and upstream (but it might still be necessary anyway, if we wanted to be able to upstream a string of changes individually)
- This slightly differs from #2252, where the code is pulled in but then is directly compiled using our existing Makefiles, instead of leveraging libsnark's build system and then linking in the resulting library. IMHO the more modular this is kept, the easier it will be to handle any divergence.

For this to work, we would need to:

- Migrate our current patches to the CMake branches (splitting them as appropriate between libsnark and libff)
- Modify both codebases to not require the `third_party` subfolder (we would want to provide dependencies like gmp and gtest via our depends system, instead of their submodule system)
  - It should be possible to make these CMake options, and when unset `third_party` subfolder is used
- Build and test both libraries in the same way `libsecp256k1` etc are: via `make -C src/<folder>` (or the CMake equivalent thereof)

I will try a variant of this using the non-CMake branch, to see how well this process handles the cases @nathan-at-least outlined. The CMake-based version should be identical, modulo the additional upfront work to migrate our existing patches.

**Comment by str4d** [comment]
I successfully created a [new branch](https://github.com/str4d/zcash/tree/820-libsnark-subtree) that pulled in our [non-CMake fork](https://github.com/zcash/libsnark) (using the exact same commit as we currently use in the depends system). The branch includes a tweak to the libsnark code, which I have pushed into [my fork of libsnark](https://github.com/str4d/libsnark/tree/test) using `git subtree push` (and could then make a PR on the Zcash fork or upstream). I have not tried pulling in upstream commits, but I would do so the same way I pull in upstream Bitcoin PRs - by cherry-picking them onto our fork, then updating the in-tree code using `git subtree pull --squash` (or possibly `merge`, I don't recall).
