### ISSUE TITLE
Document known differences between our Equihash implementation against the designers'.

### ISSUE THREAD

**Issue by daira** [zcash/zcash#833]
There are some differences, e.g. in the hash used and possibly in serialization, but it would be nice to check that everything else is the same.

**Comment by str4d** [comment]
The designers' implementation is at https://github.com/khovratovich/equihash.

**Comment by nathan-at-least** [comment]
Let's just outline some high-level strategy differences here to close this. We can point the designers here and to our implementation for feedback/collaboration.

**Comment by str4d** [comment]
| Aspect | Designers' | Ours | Comment |
| --- | --- | --- | --- |
| Sorting & collision strategy | Iterative bucket sort | `std::sort` followed by a single-pass collision step. | We tried bucket sort in #1159; it offered no increase in overall speed and considerable memory overhead, but would enable the sorting step to be cancelled immediately. |
| Hash function | BLAKE2b | BLAKE2b with personalisation |
| Hash creation | Read output as `k+1` 4-byte integers, mask each to target collision bits | Generate string `(k+1)*ceil((n/(k+1))/8)` bytes long, mask every `ceil((n/(k+1))/8)` bytes to target collision bits | Masking only happens if `(n/(k+1)) % 8 != 0`. This will be altered to instead take the `n/8`-byte hash output and expand it to `(k+1)*ceil((n/(k+1))/8)` bytes. |
| Index truncation | None | 8 bits |
| Index storage | Separate heap structure of forks | Inline in each row |
| Row storage | The list for the current round is used to generate a new list for the next round; then the current round's list is dropped. | A single list is transformed from one round to the next in-place. |

**Comment by str4d** [comment]
I'll add any other points of comparison as I think of them, but this is sufficient for now.
