### ISSUE TITLE
Specify and code the PoW algorithm in platform-independent manner.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#850]
We need to specify our PoW in a platform independent manner, and update the code to use explicit platform-independent constructs. As far as I currently understand, I think the main issue here is around the memory layout of indices as they are provided to hash inputs. Eg: https://github.com/zcash/zcash/pull/849/commits/6d25662f258d49ab8f88635d309bc1148070a46c#r59067626

**Comment by daira** [comment]
Also https://github.com/zcash/zcash/pull/849#discussion_r59082025 .

**Comment by nathan-at-least** [comment]
@str4d, @daira: I removed the ``Engineering Meeting Agenda`` label to avoid spamming our meeting time because this seems like something we can just ensure is well specified then update the code to match.

I added this ticket to the same milestone as #857). How does this sound?

**Comment by daira** [comment]
+1

**Comment by str4d** [comment]
### Things to fix

- [Hash personalisation](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/crypto/equihash.cpp#L29)
- [Order of solution index bytes when hashing](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/crypto/equihash.cpp#L78)

I assume we should make these little-endian?

### Things to discuss:

- [Direct serialization of a solution index into a step row](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/crypto/equihash.cpp#L38)
  - Currently this is big-endian, with the intent that byte array comparison gives the same ordering as integer comparison. But right now we [convert from byte array to integer before comparing](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/crypto/equihash.h#L83). I would expect it should be faster to just compare the byte arrays directly, so unless there are objections I will make that optimisation and leave the row indices in big-endian.
- The order of the solution index bytes when doing the difficulty check.
  - I believe it is currently the same as the existing serialization order of other 4-byte integers in the block header.

**Comment by str4d** [comment]
Hmm, it's quite convenient to order the solution bytes when hashing in the same order as the step row (ie. call `EhIndexToArray()` in both cases), so I'm now leaning towards making that big-endian too.

IIRC the paper is not specific on an ordering, so the limiting factor is which bits to truncate from the solution indices (because the comparison needs to be the same for truncated and full indices, ie. trim the least-significant bits when comparing in big-endian, and vice versa). The question then becomes "does it make sense to compare in little-endian", and I'd argue no, because then byte-comparison doesn't match integer-comparison, and we lose the ability for the solution indices to "make sense" when viewed as an array of numbers.

**Comment by daira** [comment]
The first two should be little-endian, yes.

The indices will be specified as integers. The fact that they're represented as byte arrays is an implementation detail of this code. Any comparisons should be consistent with integer comparison.

I haven't looked at the difficulty check yet.

**Comment by daira** [comment]
I disagree that the serialisation for hashing should be big-endian. That's complicating the spec to avoid one extra trivial function in the code (consequent to an implementation detail) which is the wrong trade-off.

**Comment by str4d** [comment]
Mmm, fair enough ^_^

**Comment by str4d** [comment]
[Difficulty serialization](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/primitives/block.h#L49) uses [this vector serializer](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/serialize.h#L640) which outsources index serialization via [here](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/serialize.h#L210) to [`ser_writedata32`](https://github.com/zcash/zcash/blob/447444ae7a3ed4e13bfb09e0c15d458070e9b904/src/serialize.h#L92), which calls `htole32()`. So that is already in little-endian.

**Comment by str4d** [comment]
The paper only makes mention of index ordering in two ways:

- Comparison is written as `w_1 || w_2 || ... || w_l < w_(l+1) || w_(l+2) || ...`, which suggests that the same byte ordering is used as in hashing (which uses the same notation).
  - However note that they also use the same notation `H` for both the hash function that outputs an `n`-bit hash for the solver, and the hash function that outputs a 256-bit hash for difficulty-checking.
- They refer to trimming the upper `(n/(k+1))+1`th bit in their implementation.

Regardless, given that in-code we are storing these as arrays of integers, and it is conceptually simpler to think about ordering the first indexes (ie. `w_1 < w_(l+1)` since `w_1 != w_(l+1)` always), I still prefer to use big-endian for that.
