### ISSUE TITLE
Document a known bug in ``movecmd`` which reports negative account balances.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#852]
Here's an implementation of ``move`` on the commandline RPC interface (in ``movecmd``): https://github.com/zcash/zcash//blob/349a7b37145429b9b9b549c9738a6f6c868a19d2/src/wallet/rpcwallet.cpp#L784-L851

If you edit rpc tests that use ``move`` (such as ``zcpour.py``) to move greater than the sum out of the ``""`` account it results in a negative balance. Seems like a security bug, although it *might* be intentional? I don't have time to investigate further / make a reproduction aside from filing this ticket.

**Comment by bitcartel** [comment]
We should tell users not to use the "accounts" feature which are now deprecated upstream. 

Accounts are an abstraction over the addresses belonging to a node and have nothing to do with the blockchain itself.  It has led to confusion amongst users, with issues such as negative balances:
- https://github.com/bitcoin/bitcoin/issues/2079
- https://bitcointalk.org/index.php?topic=456542.0
- http://bitcoin.stackexchange.com/questions/5631/how-does-the-move-command-work
- https://en.bitcoin.it/wiki/Help:Accounts_explained

Some courses of action we can take:

1. Do nothing
2. Do nothing but document and tell users not to use "accounts".
3. Update RPC commands so that if the caller sends in a value for an "account" parameter we return an error saying that Accounts are deprecated, not supported, and that they should supply the empty string value "" (which is the default account).  However, this would mean that our JSON-RPC interface is not backwards compatible and some users, for whatever reason, may actually want to use the Accounts feature.

**Comment by nathan-at-least** [comment]
For the z8 release, let's document this on the wiki which is sufficient to close this ticket.

For a later release lets ensure the security warnings in our repo links to an updateable URL for post-release security issues (https://github.com/zcash/zcash/issues/1186).

**Comment by bitcartel** [comment]
Closing.  Added comment about not using 'Accounts' in Alpha Guide, in the 'Running' section.

**Comment by bitcartel** [comment]
Yes, useful to have a discussion, in particular around how third parties looking to have many users hosted on one node will manage/track addresses by owner.  If we launch with accounts explictly disabled, there won't be any backwards compatibility issue.
