### ISSUE TITLE
Investigate alternative mock unittesting systems for C++ (gcc, c++11)

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#865]

**Comment by defuse** [comment]
Some of these can be rejected instantly because they are Windows-only or not open-source:

- [trompeloeil](https://github.com/rollbear/trompeloeil)
- [Google Mock (part of Google Test)](https://github.com/google/googletest)
- [FakeIt](https://github.com/eranpeer/FakeIt)
- [Blog post about using C++11 features to mock stuff](http://accu.org/index.php/journals/1908)
- [Isolator++](http://www.typemock.com/isolatorpp-product-page)
- [mockpp](http://mockpp.sourceforge.net/index-en.html)
- [BMOCK](https://code.google.com/archive/p/bmock/)
- [Turtle (BOOST)](http://turtle.sourceforge.net/)

[Google mock cookbook](https://github.com/google/googlemock)

**Comment by defuse** [comment]
(Thanks to @daira for help with this, btw!)

**Comment by defuse** [comment]
@daira suggested we try writing a test with both FakeIt and Google Mock.

**Comment by defuse** [comment]
I watched [this old talk](https://www.youtube.com/watch?v=sYpCyLI47rM) to understand google mock a bit. It's crazy how many insane hacks they have to use to get their "desired API" to work without having to extend the language.

**Comment by nathan-at-least** [comment]
Ok. I'd like to work through #861 and then create some example tests that stress test the rough edges (like global state, intercepting threading calls, intercepting third party libraries) and report back here. That will probably consume all of today and tomorrow and if it's not complete by tomorrow I'll let people know.

**Comment by nathan-at-least** [comment]
Since we have a PR ready for googlemock, should we close this?

**Comment by nathan-at-least** [comment]
@defuse agrees that we can close this. If we run into snags with googlemock, we might try out FakeIt. Thanks for investigating alternatives.

**Comment by rollbear** [comment]
Stumbled upon this by accident. As maintainer of [Trompeloeil](https://github.com/rollbear/trompeloeil), I just wanted to clear the misconception that it only supports mocking via interfaces/virtual functions. There is no such limitation, and never was. Even the teaser example in the README shows a non-virtual function being mocked.

**Comment by daira** [comment]
@rollbear Thanks for clarifying. It's too late for us to use Trompeloeil, but I edited the comment above so that others who find this are not confused.
