### ISSUE TITLE
Investigate alternative coverage analysis for C++ (gcc, c++11, bitcoin-style codebase) 

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#866]

**Comment by defuse** [comment]
Here's a list of the coverage tools I found from a quick search (some can be rejected immediately because they are windows-only):

- [gcov](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html) (coveralls *does* use gcov under the hood). [Google uses gcov](http://googletesting.blogspot.ca/2014/07/measuring-coverage-at-google.html)
- [Bullseye (proprietary?)](http://www.bullseye.com/)
- [COVTOOL](http://covtool.sourceforge.net/)
- [OpenCppCoverage](https://opencppcoverage.codeplex.com/) - Windows only.
- [xCover](http://www.xcover.org/).
- [CppUnit](https://sourceforge.net/projects/cppunit/).
- [Testwell CTC++](http://www.testwell.fi/ctcdesc.html)
- [GCT](http://www.exampler.com/testing-com/tools.html)
- [C++ Test Coverage Tool](http://www.semdesigns.com/Products/TestCoverage/CppTestCoverage.html)
- [Squish Coco](https://www.froglogic.com/squish/coco/)
- [Coverity SAVE](https://www.coverity.com/products/coverity-save/)
- [Cpputest](https://cpputest.github.io/)

**Comment by defuse** [comment]
It looks like we're going with `gcov` as it's the only non-rejected option.

I use coveralls for one of my C projects to get a cool coverage % indicator icon, but I just looked at it, for example https://coveralls.io/builds/2826000 and it's one of those things (like travis) that has a super buggy UI. It won't load in either of my Firefox profiles nor Chrome, and that's a pretty small project. So I reject using coveralls.

**Comment by nathan-at-least** [comment]
Thanks for this investigation!

gcov it is, then.

**Comment by daira** [comment]
I think we ended up using lcov, because upstream already uses it.
