### ISSUE TITLE
Ensure pruning is off by default. Test pruning.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#916]
This ticket is satisfied *merely* by figuring out how to run the tests, reporting if they succeed or fail, and ensuring that this feature is disabled for our launch.

**Comment by ebfull** [comment]
Pruning in upstream Bitcoin relates to discarding old block and undo data -- data that we do not rely on except during reorgs, just as Bitcoin does. **It is disabled by default**, and when it's enabled a configurable amount of data is allocated for storing the undo/block data on disk, after which the old data is removed.

Bitcoin sets a minimum for this cutoff, 550MB. I disabled this locally and set it to 1MB, and on the testnet it works just fine. Purely by accident, the zcash RPC is disabled (it's part of the wallet) when pruning is enabled, which is a good thing since it currently relies on the ability to scan the entire blockchain, something it cannot do when pruning is enabled.

**Comment by daira** [comment]
Reviewed ebfull's explanation, LGTM.
