### ISSUE TITLE
Figure out how upstream Tor integration works, then interactively test it.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#917]
This is a first pass at getting Tor integration going, but it's not a good testing solution nor a security audit.

**Comment by str4d** [comment]
In 0.11.2, Tor support is limited to client-side connections, and requires manually setting `onion=<ip:port>` to Tor's SOCKS5 proxy in order to connect out to `.onion` addresses of peers. Setting up onion services (to provide those peers) also needs to be done manually, externally to `zcashd`.

Native support for setting up onion services was added upstream in bitcoin/bitcoin#6639, and client-side connections were enabled by default in bitcoin/bitcoin#7090.

Support for Tor's next-gen onion services, or I2P, is dependent on increasing the width of the address field used to broadcast peer addresses within the P2P network (see bitcoin/bitcoin#2091).

**Comment by ebfull** [comment]
@str4d explained pretty well how Tor is integrated into the codebase -- it's used for proxying. Also see #651.

**Comment by bitcartel** [comment]
**To launch zcashd as a hidden service:**

Install Tor
- `sudo apt-get install tor`
- or install the browser bundle from torproject.org.

Add the following to the config file /etc/tor/torrc:
```
HiddenServiceDir /var/lib/tor/zcash-service/
HiddenServicePort 8233 127.0.0.1:8233
HiddenServicePort 18233 127.0.0.1:18233
```

Launch Tor.  Once it has connected to the network, the zcash service will be given a hostname which looks like abc123.onion.

```
cat /var/lib/tor/zcash-service/hostname
```

When launching zcashd, pass in the hostname for the externalip option and use Tor's SOCKS5 proxy.  If you installed Tor as part of the browser bundle, change the port number below to 9150.  To launch zcashd so that it is only reachable via Tor.

`zcashd -daemon -proxy=127.0.0.1:9050 -externalip=abc123.onion -listen
`

**To connect to zcashd running as a hidden service:**

You can connect to zcashd by using the Tor hostname.  If you are testing on the same local machine, use the `-datadir` option.

`zcashd -daemon -onion=127.0.0.1:9050 -addnode=abc123.onion
`

To test that you are connected to the Tor service, edit zcash.conf and comment out any nodes.  For example:

`#addnode=alphatestnet.z.cash`

Next, launch zcashd and use zcash-cli to verify there is only a single peer connection.

```
zcash-cli getpeerinfo

[
    {
        "id" : 1,
        "addr" : "abc123.onion:18233",
        ...
        "version" : 70002,
        "subver" : "/Satoshi:0.11.2/",
        ...
    }
]

```

Note that upstream instructions are still valid and a useful reference: https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md

**Comment by daira** [comment]
Is it easy for us to change the length of the address field (or change it to a variable-length field) now, while we're not constrained by backward compatibility? Let's discuss that at the engineering meeting.

**Comment by bitcartel** [comment]
Change was made to tor.md documentation directly using Github's built-in editor: https://github.com/zcash/zcash/commit/85cc6f5b44edfdf9bf4ebcef148eaaddbff826a7

Should have created a pull request first rather than pushing direct to repo.  Thanks @ebfull for the reminder.
