### ISSUE TITLE
Consider changing coinbase transaction from P2PK to P2PKH

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#945]
The coinbase transaction is currently pay to pubkey (inherited from bitcoind):

https://github.com/zcash/zcash/blob/zc.v0.11.2.latest/src/miner.cpp#L402

Example output from Alpha 3:

```
"vout" : [
        {
            "value" : 40.00000000,
            "n" : 0,
            "scriptPubKey" : {
                "asm" : "039091ff4d147534477c739bf775cabe1b000eb9f0ef2ac0276559636b51870309 OP_CHECKSIG",
...
                "type" : "pubkey",
                "addresses" : [
                    "motcDxSUuZhhECog8D8AQBR51HbP8EwTHM"
```

However the trend in Bitcoin has been for miners to use P2PKH as it hides their public key until they are ready to spend their coins.  Not leaking this information might be a good idea. More info here:
- http://bitcoin.stackexchange.com/questions/32639/why-does-the-default-miner-implementation-use-pay-to-pubkey/32642
- https://bitcointalk.org/index.php?topic=515724.0

**Comment by nathan-at-least** [comment]
This doesn't affect consensus in any way, but is just a miner choice, correct? In that case, we won't prioritize this before the 1.0 launch.

**Comment by bitcartel** [comment]
Yep, this doesn't affect consensus but miners might expect to see a P2PKH transaction since that is the norm in the Bitcoin world.

**Comment by str4d** [comment]
I would like to reconsider our including this in 1.0, for three reasons:

- The block explorer does not support viewing P2PK transactions, instead treating them as P2PKH outputs (due to default rendering) and unparseable inputs (when they get spent).
- The Bitcore patches applied to `zcashd` do not support indexing P2PK transactions, which has already resulted in numerous user questions about why addresses in the block explorer are empty despite having coinbase sent to them. See [this early Bitcoin block](https://blockexplorer.com/block/00000000a3bbe4fd1da16a29dbdaba01cc35d6fc74ee17f794cf3aab94f7aaa0) vs [the corresponding coinbase address](https://blockexplorer.com/address/1CT9huFgxMFveRvzZ7zPPJNoaMm2Fo64VH) to see that it is an upstream issue (and unlikely to be changed, given that Bitcoin Core have dropped their internal miner, and all other transactions are P2PKH).
- It is a trivial one-line change in `miner.cpp` (plus adjusting any affected tests), and thus should be considerably less work than patching Bitcore and Insight to support P2PK transactions.

**Comment by daira** [comment]
I'm +1 on this.
