### ISSUE TITLE
mock out libsnark calls in zcash-gtest

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#947]
Currently running `zcash-gtest` appears to invoke the full proving machinery of `libsnark`. This should be mocked out in our tests.

**Comment by ebfull** [comment]
We are sometimes just testing the constraint systems of gadgets, so mocking isn't always an option or necessary. I can't really think of a way mocking would help us here, at least for the tests we currently have.

**Comment by ebfull** [comment]
I vote that this be closed, we don't need to mock anything out in `zcash-gtest`. The places where we don't need to exercise all of libsnark's functionality, we indeed do not (see circuit tests).

**Comment by defuse** [comment]
See https://github.com/zcash/zcash/issues/863#issuecomment-228201498 for reasons this might not be reasonable to do.

**Comment by nathan-at-least** [comment]
We're not going to close this yet. I'll look into it for 20% time.

**Comment by ebfull** [comment]
We are deliberately exercising the proving behavior in this test suite, and in the parts of it which do not need to exercise it, such as the `circuit_tests`, we already don't. That is, the API for libzcash has been designed to be unit testable, and we *can* test our constraint system without invoking proof generation.

I would oppose mocking stuff out for that purpose, since experience with this approach shows it does damage to the consistency and cleanliness of the code.

**Comment by nathan-at-least** [comment]
I understand. I wouldn't remove an existing test that tests the integration between libsnark and other code, but instead would separate them out into different testing strategies. I'll change the title after I look at the specific tests and decide how to proceed.

**Comment by nathan-at-least** [comment]
Dropping this as a 1.0 goal and adding "special to Nathan". I assert this is ok quality wise because @ebfull already has a testing approach in place.

**Comment by nathan-at-least** [comment]
Dropping this because I'll probably never have time to look into it. Hopefully a master testing champion will appear on the horizon and carry forth on this noble quest.
