### ISSUE TITLE
Spec and Zerocash paper differ on the fields of a note; does this matter given that notes are part of the circuit witness?

### ISSUE THREAD

**Issue by daira** [zcash/zcash#951]
In the Zerocash paper, a coin is (addr<sub>pk</sub>, v, ρ, r, s, cm), where addr<sub>pk</sub> = (a<sub>pk</sub>, pk<sub>enc</sub>). In the Zcash Protocol 2016.0-alpha-3 spec, a note is (a<sub>pk</sub>, v, ρ, r).

s never actually existed in the instantiated Zerocash protocol. cm can be computed from (a<sub>pk</sub>, v, ρ, r). The issue here is that a Zerocash coin contains pk<sub>enc</sub> of the recipient address, whereas this cannot be computed from a Zcash note. Does this matter?

When I chose to define a note as (a<sub>pk</sub>, v, ρ, r) in the new spec, my rationale was that pk<sub>enc</sub> is never actually used: it isn't used to compute the note commitment and it isn't *constrained* by the Zerocash Pour circuit or by the Zcash JoinSplit circuit. However, pk<sub>enc</sub> for each input and output coin is still part of the *witness* for the Zerocash Pour circuit according to the paper. Taking the paper literally, this means that the prover must select some arbitrary pk<sub>enc</sub>' for each coin, which is never constrained or checked. (It is not possible for a verifier, even the recipient of the note who knows the correct pk<sub>enc</sub>, to directly check a witness value, since that would break the zero-knowledge property. The consistency of a<sub>pk</sub> with pk<sub>enc</sub>' is also not checked because in Zerocash –unlike Zcash– they are independent. In Zcash they are related but only via a Curve25519 operation which cannot feasibly be constrained by the circuit.)

I think this is all completely fine: the inclusion of pk<sub>enc</sub> in a Zerocash Pour witness was useless-but-harmless, and its omission from a Zcash JoinSplit witness is harmless. I'm just opening this issue to get second opinions.

**Comment by daira** [comment]
@ebfull Do you know whether pk<sub>enc</sub> for input and output coins was part of the witness for the Pour circuit in the prototype Zerocash implementation?

**Comment by daira** [comment]
A related issue is whether pk<sub>enc</sub> should have been an input to the note commitment. I think that also isn't needed.

**Comment by ebfull** [comment]
pk<sub>enc</sub> was not witnessed by the old circuit.

**Comment by daira** [comment]
OK, so that was probably an oversight in the paper (or not considered by the authors to be important, since technically it has no effect and is only confusing).

**Comment by defuse** [comment]
I verified what @daira wrote in https://github.com/zcash/zcash/issues/951#issue-156211342. I agree that pk<sub>enc</sub> doesn't need to be in the commitment.

~~This may be an unrelated issue: In `protocol.pdf` addresses are malleable in a certain sense. For example, if the company puts up a donation address on their website, I can subtly replace it with a different address having the same pk<sub>enc</sub> but a different a<sub>pk</sub> (for my own a<sub>sk</sub>). Assuming I somehow have the viewing key, the company will see all of the donations (they think everything is fine) but only I would be able to spend them. This is possible in `protocol.pdf` because in "Decryption by a recipient" the recipient trusts that the a<sub>pk</sub> they extract from the note plaintext is theirs, matching pk<sub>enc</sub>. It's not possible in the Zerocash paper because a<sub>pk</sub> is an input to Receive at that value is used in the commitment check.~~ (Ignore this, I was looking at the wrong version of `protocol.pdf` that still had viewing keys. Unfortunately I closed evince so I can't find the file I was looking at.)

**Comment by defuse** [comment]
Yeah the above crossed-out text only applies to the old spec with viewing keys. I opened https://github.com/zcash/zips/issues/50.

**Comment by daira** [comment]
For completeness, here's where this was fixed for the current protocol: https://github.com/zcash/zips/commit/8b9851a431d58c45bec2b84947b4031ab1d5569c

**Comment by daira** [comment]
This is now documented in (my local copy of) the protocol spec.
