### ISSUE TITLE
decide how many blocks is considered "confirmed"

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#952]
Figure out how many blocks should be considered "confirmed". Note that per https://github.com/zcash/zcash/issues/764, our blocks will be ~150 sec instead of ~600 sec.

The need for this is first of all for collective agreement — so that everyone can assume that everyone else knows that this number is the standard/default/recommended number of blocks to wait for to consider a transaction confirmed.

But, it might also in the future get baked into the protocol, e.g. in https://github.com/zcash/zcash/issues/713

**Comment by nathan-at-least** [comment]
I'm trying to wrap my head around the security decision criteria in selecting this parameter. I present some assertions here. Are they correct?

Given a constant total mining capacity, a constant distribution between attacker and non-attacker, and a fully connected 0 latency broadcast network, winning a race to produce K blocks starting from K-1 blocks in the past (in order to rollback K-1 blocks) has probability P^K where P is the fraction of mining capacity the attacker controls. Notice this does not vary for block target time! It also ignores costs and payoffs. (Is this set of assumptions necessary and sufficient?)

If we try to account for cost and benefit of attack, I start to get lost and lose confidence that I have a good handle on the security of this choice. For example, mining capacity has a per-time cost (eg: energy consumption) that does not depend on target time, and therefore the cost per block increases with increasing target time. In *that case* a lower target time for the same K costs less to rollback.

Now there's the semi-correlated price of Zcash units. If the price is low in terms of USD, for example, then an attacker has an easier time bribing mining capacity with the same amont of USD as compared to a case where the Zcash units have a higher USD price.

Since we can't easily predict the future price or distribution/cost of mining capacity, I'm inclined to pick "some reasonable" K and then provide a running estimate of the cost of a K block rollback attack. If users are transferring amounts close to this attack cost, they may want to wait longer than our recommended K, but hopefully it's good enough for "most transfers".

**Comment by amiller** [comment]
This is a tricky problem, I haven't seen much clear writing about it. Let me offer some thoughts:

First of all, to remove a few biases, I like to think of this in terms of an insurance company that offers "double-spend insurance" to a merchant. The insurance company determines the policy of how many blocks the merchant should wait, and guarantees full payment to the merchant in case of a double-spend. (This framing removes some biasing connotations, for me anyway, because the insurance company is presumably informed/rational, perhaps unlike a merchant/user.) The question then is, how does the insurance company set this policy?

I'm not sure whether there's actually any value to Bitcoin's heuristic of 6 blocks. I don't know of any evidence of people actually waiting 6 blocks. Exchanges sometimes set their own policy and wait for more or less, perhaps depending on how much they know about their users. Individuals I've traded with wait for 1 block. Payment processes do not wait for any confirmations. The 6 blocks shows up in popular clients (like the Schildbach android wallet) but I'm not convinced it's used for anything.

One approach the insurer might take is to look at past history. So far there was that one fork of 100+ blocks, and other than that I don't think any other forks longer than 4 have occurred (I don't have the data for this off hand, I suppose one could find it by crawling blockchain.info), and most of these have been benign (no double spends). I think this kind of reasoning is why payment processors accept 0-confirmations.

Another approach is to have an attacker threat model, because now we can defend against attacks that might occur in the future but haven't occurred yet. Here's where it gets tricky, because I think it's reasonable to look at malicious attacks with bounded budget, covert attacks, etc. There are some models where if an attacker can afford to make a K-block fork, he might as well make as many double-spends as possible in that time. In this case, the best defense is to wait for *longer than everyone else waits*, so that it's diminishing returns for an attacker to make a longer one.

In short, I'm really unsure how to set this!

**Comment by bitcartel** [comment]
Ethereum is using 12 confirmations with a target block time of 15 secs:
http://ethereum.stackexchange.com/questions/319/what-number-of-confirmations-is-considered-secure-in-ethereum.

An interesting tidbit from the link is that some exchanges are said to require a couple of hundred confirmations.  So when it comes to the application layer, everyone will use their own set of criteria to determine what constitutes "confirmed".

However, formal guidance is still valuable as it will anchor conversations and determine how people discuss zcash e.g. "zcash transactions take 15 minutes to clear and settle" (6 confirmations) or "send zcash to anyone in the world within 10 minutes" (4 confirmations).

**Comment by Cryptoslave** [comment]
Beware that if mining is allowed on high latency networks such as I2P you will have a lot of small forks as show by 'getchaintips'. Those eventually resolve by themselves but if the confirmations are too low this may lead to double spends.

**Comment by nathan-at-least** [comment]
The use of IP privacy networks, such as I2P or Tor, are an important use case, so thanks for bringing this up.

Note: This isn't a use case we'll have much bandwidth to focus on for our 1.0 launch, though it is one we should avoid impinging upon as we make other decisions.

**Comment by zookozcash** [comment]
Let's just say 6 transactions (15 minutes). That closes this ticket and leaves the hard questions for https://mobile.twitter.com/zooko/status/735568649600131072

**Comment by nathan-at-least** [comment]
I agree with @zookozcash on our choice, and with @bitcartel that the main value here is a kind of expectation anchoring for the ecosystem.

**Comment by nathan-at-least** [comment]
@amiller, in the insurance metaphor, I think I understand that it may help remove bias because the insurance company is a disinterested third party aside from the user and merchant who have conflicts of interest. I'm less clear on how far to take the metaphor. Maybe an insurance company would charge different premiums for different confirmation times. I wonder what those rates would be?

And perhaps relatedly, if we close this ticket with ``K == 6``, it might be nice to have a chart which is the cost of the cheapest known attack to rollback ``K`` blocks with some probability, ``P``. This same kind of chart would be valuable for other cryptocurrencies and should just be a standard blockchain explorer feature. So what is that number for known attacks? Is a reasonable estimate the cost to bribe >50% of miners for ``K`` blocks, where the actual fraction of miners depends on the ``P`` goal?

**Comment by zookozcash** [comment]
This paper, which I haven't really read, appears to be an exploration of exactly these questions: https://eprint.iacr.org/2016/555

**Comment by mcelrath** [comment]
FWIW, I've been thinking a lot about this question with regard to braids.  The solution there will ultimately be a formula given a particular threat model.  There are multiple threat models and I don't like a "one-size-fits-all" solution.  I'll echo @amiller in that I think framing this as a probability within a threat model is the right way to go.

One useful thought...I'm considering putting a "high water mark" in my braids paper -- the highest hashrate ever seen.  This becomes the baseline to compute confirmation times, under the assumption that any missing hashpower is building an alternate chain.  So as long as the hashrate is at least 50% of the high water mark, confirmation times are finite.  If the hashrate ever drops below 50%, confirmation times are infinite.  As the hashrate decreases below the high water mark, confirmation times increase.  I can provide formulas for this if this model desirable.

Of course, I've just described one particular threat model, I'll call it the "external majority" threat model.  You may have another one.

**Comment by nathan-at-least** [comment]
Let's say "6 confirmations, like Bitcoin, except that's less wall-clock time (typically)". This means we're more vulnerable to security issues that depend on wall-clock time (such as real-world opportunity cost to mining attackers).

Now that we've chosen 6, we can do threat modeling work after the fact using that as a baseline, which can happen in a different ticket.

**Comment by nathan-at-least** [comment]
Note, because we've seen empirical evidence of block reorganizations being more frequent for larger block lengths than I anticipated, I've recommended 10 to users in a forthcoming security education website page.

See #2004 for recent investigation into reorg measurements.
