### ISSUE TITLE
decide if coinbase maturity should be the same as "how many blocks means it is confirmed?"

### ISSUE THREAD

**Issue by zookozcash** [zcash/zcash#953]
In Bitcoin, coinbases can't be transferred until 100 blocks after they were created. The justifications I've heard for this don't seem well-founded to me. Some kind of incentive misalignment between miners and users might cause 6-block coinbase maturity to be unstable? Which _specific_ incentive misalignment could arise here I still don't understand. Is there a specific threat that someone has analyzed here, or is this just vague uncertainty?

**Comment by amiller** [comment]
[This explanation](https://bitcoin.stackexchange.com/questions/1991/what-is-the-block-maturation-time) from theymos and sipa suggests that it's in order to prevent canceled transactions during a "benign fork." A benign fork is one where no one is actually trying to double spend. In this case, all the ordinary transactions can be reinserted on the correct fork so there's no harm. But transactions starting from coinbase can't be reinserted this way.

**Comment by zookozcash** [comment]
Hm. I have very little patience with that feature of "fire and forget transactions". I prefer to place the responsibility more on the sender instead of on the network. If you send a transaction, and you _don't_ come back and check the blockchain 6 blocks later, and re-send your transaction if necessary, and bump up your tx fee if necessary, then I'd rather your transaction get dropped or delayed indefinitely instead of confirmed.

**Comment by daira** [comment]
I would also rather the transaction get dropped (*not* delayed indefinitely). That's #754.

**Comment by nathan-at-least** [comment]
crosslinking to #952 which is about deciding a "standard confirmation depth".

**Comment by nathan-at-least** [comment]
We're going to launch with mining maturity threshold unchanged. However, I believe it doesn't have nearly the amount of benefit it does in Zcash.

**Comment by nuttycom** [comment]
We have decided that these are not the same (@daira, @str4d, @sellout in agreement)
