### ISSUE TITLE
Document security assumptions about network connection in new RPC api docs.

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#965]
The connection from `zcash-cli` to `zcashd` provides some specific security guarantees. We need to be sure the RPCs we add aren't assuming too much (i.e. any more than the existing RPCs assume). This is especially important if we're passing keys over this connection.

We also need to document whether there are any weaknesses in the existing RPC design.

**Comment by nathan-at-least** [comment]
Let's answer this in the payment API milestone. ("payment api" == "better RPC interface")

**Comment by defuse** [comment]
If the RPC connection is not secure, that should be documented in SecurityWarnings.md document. In particular:

1. If you connect to a remote host, will it enable a MITM to execute arbitrary RPC commands? (My guess: yes).
2. If you set it up to listen on localhost, will it enable other users of the same system to execute arbitrary RPC commands (My gues: platform/configuration dependent).
    2.1. Is this mitigated by adding a password? Or can other users sniff the localhost interface to get it? (My guess: platform/configuration dependent).

**Comment by nathan-at-least** [comment]
My imagination for the new interface _and_ my understanding of the existing Bitcoin RPC interface is that it assumes the client, if they know the RPC password, has full capabilities to the node.

One implication: if you are providing a multi-user service that uses one or more shared zcashd instances in the backend, then the RPC client must prevent confused-deputy attacks. For example, if we have a call like ``z_sendmany <from_addr> ...`` and an end user is able to control the value passed in the ``<from_addr>`` parameter, then a malicious end user would be able to spend from any zkey held by that zcashd. (This is analogous to the Bitcoin RPC calls.)

So a secure multi-user application would not let users specify that parameter and would instead have a controlled hot-wallet address there, or maybe they would store a mapping from ``{ user → zaddr }`` outside of zcashd.

(Note: the "accounts" feature from Bitcoin RPC could be used for that kind of mapping, but a. it is buggy, b. we plan to deprecate and remove "accounts", and c. we are going to exclude that kind of feature from our RPC scope, since we believe those design choices are better chosen by specific applications.)

**Comment by nathan-at-least** [comment]
Let's close this ticket by documenting security assumptions about the RPC client in our RPC documentation. I'll change the title.

**Comment by bitcartel** [comment]
Also related to documenting zcash.conf settings for rpc.

**Comment by nathan-at-least** [comment]
This was closed by #1575.
